### ISSUE TITLE
Add a brief overview of how bindings work in Bindings and Triggers ref topic

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#10]
From Mathew Charles:
I’m answering questions often (like this one this morning http://stackoverflow.com/questions/38006649/configuring-notification-tag-for-azure-function) on parameter binding. I’m wondering if we have overview doc anywhere on how binding works in general. Another possibility would be for us to indicate in the templates/bindings somehow that binding parameters are supported for various properties, but I don’t want a bunch of duplication.

I expected to see a little overview section in https://azure.microsoft.com/en-us/documentation/articles/functions-triggers-bindings/. I think it would make sense to have something on that page that gives an overview of %% and {} binding functionality that applies to all the various bindings.

**Comment by SyntaxC4** [comment]
There is a new syntax for adding random Guids, we need to add this to this doc.

**Comment by wesmc7777** [comment]
Additional material to reference for this from Donna : https://github.com/Azure/azure-webjobs-sdk-script/releases 
In particular: https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.0-beta1-10307

**Comment by lindydonna** [comment]
@wesmc7777 Please document these advanced binding options as well: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Http-Functions and https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

**Comment by wesmc7777** [comment]
@lindydonna  @mathewc   Is support for the route property new and deployed publicly?  I'm seeing two problems while testing this. 

1.) Using the nullable integer type as Mathew stated fails to compile in the portal with the following exception:

2016-10-27T08:47:04.640 Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.HttpRouteTriggerCSharp'. mscorlib: GenericArguments[0], 'System.Nullable`1[System.Int32]', on 'Microsoft.Azure.WebJobs.Host.Bindings.Invoke.StructInvokeBinding`1[TValue]' violates the constraint of type 'TValue'. mscorlib: GenericArguments[0], 'System.Nullable`1[System.Int32]', on 'Microsoft.Azure.WebJobs.Host.Bindings.Invoke.StructInvokeBinding`1[TValue]' violates the constraint of type parameter 'TValue'.

2.) If I make the id simply an integer, I'm still unable to address my function using the customized route.  Here is a fiddler trace:

GET https://wesmcfunctiontesting.azurewebsites.net/api/products/electronics/357?code=ydq1pnpmkqdqd8asir418aor7bsaneuqphp5xvjs3tt0muz0k9b21r90nxv8qvx2y3fvsa714i HTTP/1.1
Host: wesmcfunctiontesting.azurewebsites.net
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cookie: ARRAffinity=7c3fc0f0eec8c7ad13d56b234e1dbc5b9d34a81041fd9772cde087f31f9f797b

HTTP/1.1 404 Not Found
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 0
Expires: -1
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 27 Oct 2016 08:49:21 GMT

**Comment by wesmc7777** [comment]
@lindydonna  @mathewc   Nevermind, its working correctly after making sure my runtime was ~0.7

**Comment by wesmc7777** [comment]
Everything exception host.json configs included with this PR:

https://github.com/Azure/azure-content-pr/pull/32800

For the host.json configurations, I'm wondering if we should put those in the [Runtime Concepts topic](https://azure.microsoft.com/en-us/documentation/articles/functions-reference/) instead of Bindings and Triggers Reference

**Comment by lindydonna** [comment]
@wesmc7777 Agreed!

**Comment by SyntaxC4** [comment]
@lindydonna - Are you able to review this article and place in done when edits, if needed are complete?

**Comment by wesmc7777** [comment]
Feedback added including Mathew's Advanced binding support with IBinder

https://github.com/Azure/azure-content-pr/pull/33110

**Comment by lindydonna** [comment]
@SyntaxC4 Mathew already reviewed, so this is good. Thanks @wesmc7777!
