### ISSUE TITLE
Documentation of Networking Options (Open Ports) for Functions

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#101]
Basically we need a link to this document which describes the App Service Sandbox:

https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

We can reference that available ports are under the **Network Restrictions** section

**Comment by SyntaxC4** [comment]
Apparently someone has already suggested this topic via PR: https://github.com/Microsoft/azure-docs/pull/212/files

**Comment by SyntaxC4** [comment]
@ggailey777 When the topic above is moved to a more appropriate location and the content is merged, we can close this issue.

**Comment by ggailey777** [comment]
We should cover this in the function app topic #396
