### ISSUE TITLE
No validation for name > 60 chars

### ISSUE THREAD

**Issue by nhart12** [Azure/Azure-Functions#1010]
https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions
The naming convention documentation lists a limit of 60 chars for function apps. When creating a function app using either ARM or the UI, if the function name is greater than 60 characters the validation doesn't catch it and it fails during deployment with an unhelpful error.

For example: creating a function named: "A-Really-Long-Function-Name-With-More-Than-Sixty-CharactersA" will pass validation on the UI but later fail in deployment. The error is very unhelpful:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"There was a conflict. The remote server returned an error: (400) Bad Request.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"There was a conflict. The remote server returned an error: (400) Bad Request.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"ExtendedCode\": \"01020\",\r\n \"MessageTemplate\": \"There was a conflict. {0}\",\r\n \"Parameters\": [\r\n \"The remote server returned an error: (400) Bad Request.\"\r\n ],\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"There was a conflict. The remote server returned an error: (400) Bad Request.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"}]}

**Comment by ColbyTresness** [comment]
@mathewc is this a bug or by design? Either way looks like we need to improve error mesaging

**Comment by mathewc** [comment]
In the portal, I see the same validation happening for both WebApps and FunctionApps:

![image](https://user-images.githubusercontent.com/1056548/51415388-82e2f880-1b2a-11e9-89d3-60e60b272446.png)


![image](https://user-images.githubusercontent.com/1056548/51415366-72328280-1b2a-11e9-85f0-9ebcfb788259.png)

What UI aren't you seeing validation in? Definitely the UI shouldn't be letting any invalid names through.

**Comment by nhart12** [comment]
Yeah, maybe the UI has since been fixed
