### ISSUE TITLE
Deployment center GitHub connection giving "Your function app is targeting V1, but Azure host has function version V2"

### ISSUE THREAD

**Issue by jasonshave** [Azure/Azure-Functions#1013]
I'm writing a function app which has previously been published using web deploy without issue. I noticed the app version was set to ~1 in the web portal so I decided to remove it and start over since you can't edit a function app version with existing functions defined.

I started out by creating a new function app, setting the version to V2, then connecting it to my GitHub repo. The first pull/publish worked without issue but the app isn't working correctly (getting http 500 errors). I've tried pulling changes from two branches into my deployment slot and my production instance but both fail with the same error:

> Your function app is targeting V1, but Azure host has function version V2, \r\nplease change the version using the portal or update your 'FUNCTIONS_EXTENSION_VERSION' appsetting and retry

I've checked my `FUNCTIONS_EXTENSION_VERSION` setting and it is set to: `~2`

Not sure what else to check.

**Comment by jasonshave** [comment]
The fix for this was to add:

`<AzureFunctionsVersion>v2</AzureFunctionsVersion>`

...to the .csproj file. I'm thinking the templates for creating function apps should add this automatically?

**Comment by ColbyTresness** [comment]
New V2 templates do this automatically, but unfortunately for the migration story from V1 there's not a great way to fix this (to my knowledge.) Adding @nimakms, we should probably add logic in VS which tells when you're targeting a V2 App from a V1 csproj

**Comment by cpiock** [comment]
I run into the same problem. AzureFunctionsVersion is v2 and FUNCTIONS_EXTENSION_VERSION is ~2. How did you resolved?
