### ISSUE TITLE
Application Settings without content and error message

### ISSUE THREAD

**Issue by crac2003** [Azure/Azure-Functions#1014]
I'm trying to publish Azure Function App with some custom settings from local.settings.json file. Unfortunately, Application Settings form doesn't show any information available at that point. It pops up as shown on the image:
![image](https://user-images.githubusercontent.com/11277706/47800193-b2e8df80-dd23-11e8-905d-18d8364ff923.png)

When I click 'Add Setting' - nothing happens.
When I click 'Ok' - Saving message appears but it stays in that state without doing anything
![image](https://user-images.githubusercontent.com/11277706/47800479-45897e80-dd24-11e8-8bf6-9175416089f2.png)

Is there a way to get any feedback what is wrong so I can't see any variables from local file?

Technical details:
Function V2
Target framework: netcoreapp2.1

**Comment by nimakms** [comment]
@crac2003, apologies for the late response, has this been resolved for you? I was only able to see this behavior if local.settings.json had invalid json. With valid json, everything worked with latest VS 15.8.8 and Functions extension 15.8.05023.0

**Comment by crac2003** [comment]
@nimakms thanks for your message. No, I still have a problem with it - I'm using VS 15.8.9 and Function ext 15.10.2046.0. 

Probably you are right that it may be a problem with .json but:
1. it works when I run locally (which means that local file is parsed correctly and passing values to the function)
2. there is no validation issue regarding structure and configuration values (using an online tool to perform validation)

Even if there is an issue with a file - is there any place where I can see logs from the extension?
Without that, it is quite difficult to investigate what is wrong - especially that it doesn't work even with an empty config file.

**Comment by nimakms** [comment]
@crac2003 please feel free to email me (address on my profile) your .json, so I can follow up with the team with a reproducible bug.

**Comment by crac2003** [comment]
@nimakms I've sent an email. Please let me know if you need anything else.

**Comment by ColbyTresness** [comment]
Is this still an issue? Nima left the team so if you could forward this email to me I can track down.

**Comment by zmarty** [comment]
Yes, this is still an issue. I will forward you an e-mail with more information.

For everybody else, one workaround that worked for most of us was to click on your user in Visual Studio (upper right), then click on Account settings. If you see an exclamation mark it means you need to Reenter your credentials.

**Comment by ColbyTresness** [comment]
@vijayrkn thoughts on this one? Providing some sort of loading icon while app settings load maybe?

**Comment by vijayrkn** [comment]
This should be fixed. You will get an error message like this if we are unable to retrieve the credentials. 


![image](https://user-images.githubusercontent.com/3981619/59235799-0cfa2f00-8ba8-11e9-9c24-3de449104865.png)

**Comment by ColbyTresness** [comment]
Closing as fixed per above
