### ISSUE TITLE
Deploying by ZIP fails on Spanish Visual Studio

### ISSUE THREAD

**Issue by Wakusei** [Azure/Azure-Functions#1015]
¡Hola!

Deploy by ZIP file from Visual Studio 2017 with Spanish settings fails.

#### Procedure
- Change Visual Studio to Spanish. (The OS settings are not related)
- Create an Azure Function project with v2 runtime.
- Create a publish profile with ZIP deloyment.
- The name of the created profile is "implementación de archivo ZIP." This **default** name contains "**ó**" and that causes zip file creation to fail.

#### Build log
  Publicación iniciada
  FunctionApp2 -> C:\tmp\FunctionApp2\FunctionApp2\bin\Release\netcoreapp2.1\bin\FunctionApp2.dll
  FunctionApp2 -> C:\tmp\FunctionApp2\FunctionApp2\obj\Release\netcoreapp2.1\PubTmp\Out\
  Publicación completada.

The ZIP file creation message doesn't show. Changing the profile name makes things go well. I think this also happens on other languages.

Gracias 🤠🌵

**Comment by mhoeger** [comment]
Hi @vijayrkn, would you mind investigating or triaging this issue?

**Comment by vijayrkn** [comment]
We track all the VS issues in developer community. Can you please move the issue here - https://developercommunity.visualstudio.com/

**Comment by mhoeger** [comment]
Thanks Vijay! @Wakusei - I've filed an issue [here](https://developercommunity.visualstudio.com/content/problem/373397/azure-functions-zip-deployment-fails-with-spanish.html) with Visual Studio. I'm going to close this issue but continue to follow the one created in Visual Studio's developer community. Thanks!
