### ISSUE TITLE
NetCore 2.1 Azure Function: Startup Not In Extensions.json

### ISSUE THREAD

**Issue by mayoatbm** [Azure/Azure-Functions#1016]
We tried switching one of our v2 function apps to netcore 2.1 (and the 1.0.23 SDK) per the comments in this #805 issue.

The switch appeared to be successful but the startup class in our project was not included in extensions.json (in Visual Studio). The extensions.json not being generated properly is an [existing issue](https://github.com/Azure/Azure-Functions/issues?utf8=%E2%9C%93&q=extensions.json)  but the common workarounds (build target, metadatagenerator nuget) don't work when the project is netcore 2.1.

Env:

- Startup class has  the WebJobStartup attribute applied
- Startup class Implements IWebJobStartup
- VS Azure Function Tools: 15.10.2046.0
- Runtime: 2.0.12134.0

**Comment by ColbyTresness** [comment]
Can you confirm that you updated your build target per https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#visual-studio-runtime-versions?

**Comment by mayoatbm** [comment]
@ColbyTresness  Yes, I can.

**Comment by fabiocav** [comment]
This is a known issue we're addressing. In the meantime, one of the common ways to workaround the issue is to implement the startup in a separate project (targeting .NET Standard 2.0).

**Comment by psibernetic** [comment]
@fabiocav Can we re-open this issue to track this being resolved, or is there another issue?
