### ISSUE TITLE
Azure Functions Build & Publish do not include all dependencies correctly

### ISSUE THREAD

**Issue by cloudlene** [Azure/Azure-Functions#1017]
1. I have a .Net Standard assembly (Let's call it Cloudlene.Rhipheus.dll)
2. It depends on an appSettings.json.  It's marked 'Copy Always'
3. I have few .Net Core projects that depend on this assembly (Let's call it Cloudlene.MyProject.Api.dll)
4. When I build the Cloudlene.MyProject.API, the output folder ('bin\debug') contains all 3 files

Switch over to Azure Functions
1.  Function project depends on the same assembly: Cloudlene.Rhipheus.dll
2.  I build the function project
3. The dll is copied to bin\debug\netstandard2.0\bin correctly
4. The appSettings.json, though is copied to the netstandard folder!
5. So, I go ahead and add a Post build event to move this file to bin

Now, I'm able to 'func start' from command line.

Publishing time!

1. I use VS.Net to publish to my dev subscription.  Right click & Publish
2. I have a valid publish profile & all other steps to connect to Azure work as intended
3. As soon as I hit 'publish', Function project creates a 'PubTmp\Out' folder & I see it's updating my appSettings to the root of the function folder (Meaning assembly is copied to  myfuncproject\bin\ but the appSettings.json is copied to myfuncproject)
4. I login to Azure, login to the console under Platform features tab
5. I see the file is in the root AND not inside the bin folder!
6. I run move command to move the file to bin
7. Restarting the function to run without exceptions

This is vexing.  What are my options?

**Comment by nimakms** [comment]
@cloudlene, apologies for the late response. We'll be tracking this with the Visual Studio team, but I don't imagine it will be a quick fix. I'm glad you have already figured out the issue and mitigated it with workaround steps (post-build event, move command on deploy). In the short term that is still your best bet.

**Comment by cloudlene** [comment]
No it is not, unfortunately.  We need to get this to work with Azure
DevOps.  For that the build & deploy should function as expected.  We can't
use this in production, if our deployment have to be manually tweaked after
publication.   Any workarounds? Is there a way to automate the move
commands to Azure function console after publication?

**Comment by dejanberic** [comment]
I have the same problem.
I even tried to copy on post-build event to the PubTmp\Out but that folder is emptied after I copy the files I need, So that is a no go.
Is the a pre-publish event of some sorts?

**Comment by penguin20000** [comment]
Is there any update on this issue? I'm having the same issue as @dejanberic

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#298
