### ISSUE TITLE
Azure functions v2 Visual Studio 2017

### ISSUE THREAD

**Issue by eaidland** [Azure/Azure-Functions#1018]
Azure Functions and Web Job Tools v: 15.10.2046.0
Azure functions v2
Visual Studio 2017
.Net Core 2.1

Created a new HTTPTrigger in Visual studio and try to run the app, but it's not working. The defaults are set and I run the application:

[11/2/2018 8:43:51 AM] Loading functions metadata
[11/2/2018 8:43:51 AM] 0 functions loaded
[11/2/2018 8:43:51 AM] Generating 0 job function(s)
[11/2/2018 8:43:51 AM] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[11/2/2018 8:43:51 AM] Host initialized (143ms)
[11/2/2018 8:43:51 AM] Host started (155ms)
[11/2/2018 8:43:51 AM] Job host started
Hosting environment: Production
Content root path: C:\XXXXX\FunctionApp1\FunctionApp1\bin\Debug\netcoreapp2.1
Now listening on: **http://0.0.0.0:7071**
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
[11/2/2018 8:43:57 AM] Host lock lease acquired by instance ID '0000000000000000000000001D541C88'.

Why isn't the httptrigger working? In v1 one could just run the app and use postman to trigger the http.
**Update**
Looks like it's only an issue with my Azure VM and not locally on PC.

``` 
[FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
    }
```

**Comment by maiqbal11** [comment]
Are you creating the function somehow differently in your VM? Do you have a full dev environment set up in the VM  (Visual Studio, Tools etc.) as well? Just trying to understand where the inconsistency between your local and VM setup might be.

**Comment by eaidland** [comment]
I’m loading the same solution on both environments with vs2017. Can’t pinpoint the differences.

**Comment by maiqbal11** [comment]
Could you share more details about the VM you are using? I can try to repro the issue that you are facing.

**Comment by eaidland** [comment]
Size: Standard DS3 v2 Promo (4 vcpus, 14 GB memory)
Disk: 128GB encrypted host caching Read/write
Operating System: Windows Server 2016 Datacenter build 14393.2580 (64bit)
Network: No public IP, it's in a VNET/subnet with NSG. Accelerated networking disabled.

**Comment by maiqbal11** [comment]
How are you managing the VM without a public IP? Are you using some kind of gateway to access it?

**Comment by eaidland** [comment]
@maiqbal11 There's a vpn connection from inhouse to the vnet.

**Comment by eaidland** [comment]
I don't know why, but now it works on the VM also. I started the function and it started some cli download automatically. That didn't happen before. 

Should we conclude that it may be related to network issues?  It may be that VS was prevented to update due to some NSG, Firewall etc settings.

**Comment by maiqbal11** [comment]
That would be my guess as well. Since you're using a VPN connection along with an NSG, it's likely that there might have been some networking issue causing intermittent problems with access to the public internet.
