### ISSUE TITLE
Azure Function CosmosDBTrigger Imperative Binding

### ISSUE THREAD

**Issue by aderderian** [Azure/Azure-Functions#1019]
The scenario I have is that I want to declare a cosmos db input trigger with Azure functions. My database name is stored in ApplicationSettings and my secret key is stored in Azure Key Vault. I have tried some things with Imperative Bindings, but it doesn't seem this would work here. Is this possible?

`[FunctionName("BroadcastChanges")]
        public static async Task Run(IReadOnlyList<Document> input, Binder binder, ILogger log)
        {
            ISecretService _secretService = new SecretService(Environment.GetEnvironmentVariable("ApplicationKeyVault_Vault"), Environment.GetEnvironmentVariable("ApplicationKeyVault_ClientId"), Environment.GetEnvironmentVariable("ApplicationKeyVault_ClientSecret"));
            var uri = new Uri(Environment.GetEnvironmentVariable("DocumentDb_EndpointUri"));
            var authKey = _secretService.GetConfigrationSecretAsync("DocumentDb:Key").Result;

            //imperative bindings
            var attribute = new CosmosDBAttribute(Environment.GetEnvironmentVariable("DocumentDb_DatabaseName"), "MyCollection")
            {
                CreateIfNotExists = true,
                // Specify the AppSetting key which contains the actual connection string information
                ConnectionStringSetting  = "AccountEndpoint=" + uri.ToString() + ";AccountKey=" + authKey + ";",
            };

            using (var t = await binder.BindAsync<TextWriter>(attribute))
            {

            }
        }`

**Comment by aderderian** [comment]
Thanks @jeffhollan , I can def wait for the update. Excited to see it. Let me know when it rolls out and I can test.

**Comment by jeffhollan** [comment]
[Here's the blog post on the new feature](https://medium.com/statuscode/getting-key-vault-secrets-in-azure-functions-37620fd20a0b)
