### ISSUE TITLE
[Visual Studio] "ScriptHost error" Error running Azure Function in VS

### ISSUE THREAD

**Issue by lucabol** [Azure/Azure-Functions#102]
Not sure how to even start to debug this. I'm happy to do a skype call or give more info if needed. This is a port of a Function that used to work in the Function portal.

The repo is here: https://github.com/lucabol/GuruBackend

Full error below:
Starting Host (HostId=lucabol-yoga1-gurubackend, Version=1.0.0.0, ProcessId=13112, Debug=True)
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.UpdateGuruPortfolio'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
Error indexing method 'Functions.UpdateGuruPortfolio'
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Job host started
The following 1 functions are in error:
UpdateGuruPortfolio: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.UpdateGuruPortfolio'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.

**Comment by lindydonna** [comment]
I'm pretty sure this is due to the poor error message we have when you don't have a value for AzureWebJobsStorage. Can you see if your symptoms match this bug report? https://github.com/Azure/azure-webjobs-sdk-script/issues/972

**Comment by lucabol** [comment]
Thanks Donna. That was it. Fixed.

**Comment by rossedman** [comment]
@lindydonna @lucabol Hey, I have tried tracing this thread and have gotten lost in the repo hopping. What is the conclusion to this? I have tried updating DotNet, dotnetcore, nodejs, yeoman and everything else in between. I am still getting this error. 

I can open a new thread as well if needed. Thanks.

---
This happens on an infinite loop.

```
Generating 1 job function(s)
Starting Host (HostId=3b22ae929f014239
Found the following functions:
Host.Functions.AuditResourceGroupTags

A ScriptHost error has occurred
Stopping Host
Reading host configuration file 'C:\Us
Generating 1 job function(s)
Starting Host (HostId=3b22ae929f014239
Found the following functions:
Host.Functions.AuditResourceGroupTags
```

**Comment by lindydonna** [comment]
@rossedman Please do open a new issue in this repo, since it sounds like a different issue. Please include the contents of function.json and appsettings.json (but remove actual connection strings).
