### ISSUE TITLE
Nested JSON object results in warning

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/Azure-Functions#1023]
I was trying to create nested app settings, but when I add a nested object (`foo` below), it errors out and tells me it can't find the `FUNCTIONS_WORKER_RUNTIME` setting.

Repo
1. Create an Azure Function app.
2. Modify `local.settings.json` to

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "foo": {}
  }
}
```
3. Hit F5 to debug

EXPECTED: Valid JSON doesn't cause any issues

ACTUAL:

> your worker runtime is not set. As of 2.0.1-beta.26 a worker runtime setting is required.
> Please run `func settings add FUNCTIONS_WORKER_RUNTIME <option>` or add FUNCTIONS_WORKER_RUNTIME to your local.settings.json
> Available options: dotnet, node, python

VS2017 15.8.9
Azure Functions and Web Jobs Tools: 15.10.2046.0

**Comment by JohnReeson** [comment]
See [this comment](https://github.com/Azure/azure-functions-core-tools/issues/223#issuecomment-325045802), invalid format nested JSON in `Values` causes host fail to read `FUNCTIONS_WORKER_RUNTIME`.

**Comment by MisinformedDNA** [comment]
Awesome. I'll close this one.
