### ISSUE TITLE
Fix and review the Functions topic in Logic Apps

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#103]
On the doc page https://docs.microsoft.com/en-us/azure/app-service-logic/app-service-logic-azure-functions there is a javascript snippet that claims to be a function:

```javascript
function start(req, res){
    var data = req.body;
    res = {
        body: data.date.ToDateString();
    }
}
```

However this isn't a valid Azure Function. Might be good to review the rest of the doc as well for correctness.

Also, I answered a SO question http://stackoverflow.com/questions/41098486/how-to-access-azure-function-json-response-properties-in-azure-logic-apps recently - it would be good if the doc showed people how to access response properties like this as well.

**Comment by ggailey777** [comment]
The Logic App folks are in the process of moving their topics to a different folder location. This work is blocked until that migration is complete.

**Comment by jeffhollan** [comment]
This was fixed
