### ISSUE TITLE
Azure Fails to Track a Second Azure Function Deployed to GitHub

### ISSUE THREAD

**Issue by adamsk34** [Azure/Azure-Functions#1035]
I found a bug. Earlier I created [an MSDN post about this bug](https://social.msdn.microsoft.com/Forums/en-US/25ffa4b7-7955-4b0f-9eac-1b46341838ef/why-can8217t-i-add-a-new-azure-function-to-my-app-since-setting-up-continuous-deployment?forum=AzureFunctions)

Here's my details:
* OS is Windows 10
* Visual Studio version: 15.7.1
* C# Blob Trigger Azure Functions

### TL;DR
Azure failed to deploy the second Azure Function I added to a pre-existing Function App in Visual Studio, after continuous deployment had already been in place and working for 1 Azure Function in 1 Function App.

## Here's how I came across the bug:
Initially deployment was set up with 1 C# Blob Trigger Azure Function. Continuous deployment was working fine. When I added a 2nd C# Blob Trigger Azure Function and pushed it to GitHub, the new Azure Function wasn't visible or running. I was eventually able to get my new Azure Function running, see my MSDN post for how. I thought I had fixed it, but the next time I pushed to GitHub, the new changes had not been added.

I fixed the new issue myself when I updated 2 binary files in the "D:/home/site/wwwroot/bin/" directory. I copied them from my local source. The files are \<azure-function-name\>.dll and \<azure-function-name\>.pdb.
I have now realized that if the bug is not fixed I will have to do this every time, every time I push to GitHub.

Thanks in advance.

**Comment by mhoeger** [comment]
@adamsk34 - can you give us more details from Deployment Center (in the Azure Portal, under "Platform features")

You should be able to see the status of your build and commit as well as any logs your deployment may have produced.
![image](https://user-images.githubusercontent.com/8888531/48449104-12001880-e756-11e8-8a30-7f3b1f401846.png)

**Comment by adamsk34** [comment]
Hello, the status of the latest commit is "Success (Active)"
The pics are from the Deployment Center, the 2nd pic is of the logs from the latest commit.
![dep center](https://user-images.githubusercontent.com/23266447/48489968-f21a3480-e7e9-11e8-9ba8-2afb48c33122.PNG)
![dep logs](https://user-images.githubusercontent.com/23266447/48489969-f21a3480-e7e9-11e8-924b-33f7cb09363c.PNG)

**Comment by mhoeger** [comment]
@adamsk34 - I'm not able to reproduce your issue. I've created an app starting with one function and have added more functions. On deploying, I have to refresh the portal page but otherwise correctly see my app updated. The expected files are also in place in Kudu. 

What I also don't understand is that your deployment logs also say "Syncing 3 triggers", which indicates that that deployment had 3 functions in the function app that were found and should have been correctly deployed. Is that correct? 

Could you try committing again, waiting until deployment is successful, and then try refreshing (below) and checking your Kudu files?
![image](https://user-images.githubusercontent.com/8888531/48508137-a031d880-e802-11e8-822e-68159abec0ac.png)

If this still isn't working, can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? If your GitHub repository is public, a link it would be helpful too. Thanks!

**Comment by mhoeger** [comment]
@adamsk34 - So did you create the function app, create a function in the portal, as a .csx (c# script) and then hook it up to continuous deployment? I think this isn't compatible and maybe we should do more to prevent this scenario, but it would be great to know exactly what steps you have taken with this function app. (cc: @hartra344)

**Comment by adamsk34** [comment]
What you described is almost what I did. [There is a section in the Continuous Deployment docs which refers to hooking up a Function you made in the portal to continuous deployment](https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment#move-existing-functions-to-continuous-deployment) so I am surprised to hear you say that.

## The Full Process I Went Through:
I created my first Azure Function called "BlobTriggerPDF", through the portal as a .csx, c# script. It was after that, when I decided to set up Continuous Deployment.

The UI for Continuous Deployment has changed (in September I think). I tried my best to set up deployment as intended, but I had some trouble because the documentation is slightly out of date. For example, the Deployment Center shown in the pictures [in this section](https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment#set-up-continuous-deployment) is different from how it looks in the portal now.

I set up deployment through the Deployment Center and my BlobTriggerPDF Azure Function was not in my GitHub repo. At this point I had a GitHub repo with only a readme, 1 working function in Azure, and nothing set up locally. I had set up Continuous Deployment between Azure and GitHub, but I clearly wasn't ready for development, since in Azure, GitHub, and locally everything was all very different. However, I noticed that my readme had been copied to be within my Function App at this point.

I felt like the documentation was only partially complete. It doesn't say with much detail, how to get the old Azure function in GitHub. At the time I didn't know how to move my existing Function to GitHub. I decided to give up on my old Function (BlobTriggerPDF) in Azure, but I continued with the same function app that I had set up for Continuous Deployment.

When I started over I cloned the GitHub repo locally, which was just readme file. From there I used Visual Studio to create a new Azure Function (MainBlobTriggerPDF). I pushed that to GitHub.
I didn't know at the time if this would work, or if this was the right way to do it but it worked and so I assumed it was right.

At this point, I had disabled BlobTriggerPDF in the portal, and was happily working on MainBlobTriggerPDF, I pushed changes regularly and everything was fine. I later added an Azure Function called ValuePBlobTriggerPDF, this is when the issue I am posting about started. Right now, the original BlobTriggerPDF Azure Function is not in my GitHub repository, but the other 2 are.

I hope I've been clear, it is was a complicated process. I appreciate the help.

**Comment by mhoeger** [comment]
Hi @adamsk34, thanks so much for the detailed feedback.

@btardif - it looks like the deployment docs are out of date and that the GitHub scenario for "Move existing functions to continuous deployment" is not completely fleshed out. Are you the right person to take a look at this? I can open an issue on the docs repo too if you'd like.

**Comment by btardif** [comment]
@cephalin owns the docs.

**Comment by cephalin** [comment]
Actually @ggailey777 owns Functions docs.
