### ISSUE TITLE
Question: TelematryClient disable sampling

### ISSUE THREAD

**Issue by stridsbr** [Azure/Azure-Functions#1036]
I use application insights for my tracelogging in .net framework. But the logs are sampled.
This is how I create the client:

```csharp
var client = new TelemetryClient()
            {
                InstrumentationKey = _instrumentationKey
            };
```
How can I modify this code so it dont get sampled?
Or that Trace and exception logs won't get sampled?

I use TelematryClient from a common logging library. I prefere to use that class so I don't have to rewrite all the code that referense that library.

**Comment by stridsbr** [comment]
The TelemetryClient I create shuld send all the telemetry to application insights but when I look in the trace I'm missing a lot. And some of the traces have itemCount > 1.

I don't have the applicationinsights setting in host.json so it probobly defaults to:
```json
{
"applicationInsights": {
    "sampling": {
      "isEnabled": true,
      "maxTelemetryItemsPerSecond": 5
    }
  }
}
```
But does this effect the TelemetryClient I create myself and not just the TraceWriter and ILogger that is injected to the function?

I can see that the injected ILogger has 4 processor and the one I created only has one (default).

![image](https://user-images.githubusercontent.com/2290125/48607873-1f99e600-e982-11e8-902a-bfdac5b3742d.png)

Does the configuration for application insights affect the TelemetryClient created in this example: https://github.com/Azure/Azure-Functions/wiki/App-Insights#custom-telemetry

Thanks for your help

**Comment by paulbatum** [comment]
@brettsam @lmolkova Any ideas on this one? I would have guessed that our sampling settings would NOT impact any telemetry client created by a user, but that seems to be what is happening here.

**Comment by lmolkova** [comment]
@stridsbr do you have functions v1 or v2?
In any case, you should not have sampling by default on the telemetry client you created yourself. Do you see that some telemetry is lost? Do you see any telemetry from the client you've created at all?

**Comment by stridsbr** [comment]
We are running v1, I get a lot of telemetry but as I understand it, the property itemCount describes how many 'writes' each row is in an sample.

![image](https://user-images.githubusercontent.com/2290125/48660402-29464b00-ea61-11e8-96bc-05170f9114b0.png)

And when I look at the logging for some runs I have to get 2 loggs in the execution path but one is missing.

To be honest, I'm using seriloger with a sink for application insights where I provide the TelemetryClient. So the issue might be there.

I'm thinking of changing to use the provided ILogger but I haven't found any sink for it. So Maby I'll have to write one myself.
