### ISSUE TITLE
[Visual Studio] Running v2 function from visual studio fails, running directly from command line works.

### ISSUE THREAD

**Issue by ravicini** [Azure/Azure-Functions#1037]
I created a small simple function with HTTP trigger and storage binding.

``` csharp
[FunctionName("DrawRegions")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", Route = "article/{articleId}")]
    HttpRequest req,
    string articleId,
    [Blob("articles/{articleId}.json", FileAccess.Read, Connection = "ArticlesBlobStorage")]
    Stream myBlob,
    ILogger log)
    { ... }
```

When I execute the function in Visual Studio, I get the following exceptions:

```
[14.11.2018 11:45:57] Error indexing method 'DrawRegions.Run'
[14.11.2018 11:45:57] Microsoft.Azure.WebJobs.Host: Error indexing method 'DrawRegions.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'myBlob' to type Stream. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[14.11.2018 11:45:57] Function 'DrawRegions.Run' failed indexing and will be disabled.
[14.11.2018 11:45:57] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```
#### Used Tooling
VS: 15.8.9
Azure Functions and Web Jobs Tools: 15.9.02046.0
AzureFunctionTools CLI: 2.11.1
Azure Functions Core Tools (2.2.32 Commit hash: c5476ae629a0a438d6850e58eae1f5203c896cd6)
Function Runtime Version: 2.0.12165.0
Microsoft.NET.Sdk.Functions: 1.0.23

When I deploy the function on azure or I build the function with `dotnet build` and run it with 
`C:\Users\marco.ravicini\AppData\Local\AzureFunctionsTools\Releases\2.11.1\cli\func.exe start .`
it works as expected.

**Comment by ConnorMcMahon** [comment]
I am getting similar issues, but the exception is different because mine are triggers, not bindings:

Code:

```
        [FunctionName("HelloOrchestrator")]
        public static async Task<List<string>> Run(
            [OrchestrationTrigger] DurableOrchestrationContextBase context)
        {

            // First, sleep for 30s to give the Client Function time to kill the w3wp process
            DateTime thirtySec = context.CurrentUtcDateTime.Add(TimeSpan.FromSeconds(30));
            await context.CreateTimer(thirtySec, CancellationToken.None);

            // Once the orchestrator has woken up, call the activation function
            var outputs = new List<string>();

            string siteName = Environment.GetEnvironmentVariable("WEBSITE_SITE_NAME");

            outputs.Add(await context.CallActivityAsync<string>("SayHello", $"{siteName}"));

            // Writes "Hello, Seattle" to a queue
            return outputs;
        }

        [FunctionName("SayHello")]
        public static void SayHello(
            [ActivityTrigger] string name,
            [Queue("durable-completions", Connection = "AzureWebJobsStorage")] out string queueItem)
        {
            queueItem = name;
        }
```

Exceptions:

```
[11/14/2018 10:36:24 PM] The following 2 functions are in error:
[11/14/2018 10:36:24 PM] HelloOrchestrator: The binding type(s) 'orchestrationTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
[11/14/2018 10:36:24 PM] SayHello: The binding type(s) 'activityTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
```

Used Tooling:
VS: 15.9.0
Azure Functions and Web Jobs Tools: 15.9.02046.0
AzureFunctionTools CLI: 2.11.1
Azure Functions Core Tools (2.2.32 Commit hash: c5476ae629a0a438d6850e58eae1f5203c896cd6)
Function Runtime Version: 2.0.12165.0
Microsoft.NET.Sdk.Functions: 1.0.24

It looks to me like the extension metadata is not being generated. @fabiocav any ideas here?

**Comment by ConnorMcMahon** [comment]
My issue might be separate from this, as the runtime also fails when I publish and when running directly from the CLI.

**Comment by ravicini** [comment]
As I'm using paket it seems this one is related to this bug: https://github.com/fsprojects/Paket/issues/3345

**Comment by ravicini** [comment]
Some more information:
It seems the difference when working or not working is a generated extensions.json
in the bin/netstandard2.0/bin directory.

As soon the file exists and contains:
```
{
  "extensions":[
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
  ]
}
```

The function works.

I'm in a solution with mixed environment.
2 function apps with net471 and Microsoft.NET.Sdk.Functions(1.0.14)
1 function app with netstandard2.0 and Microsoft.NET.Sdk.Functions(1.0.24) or 23 - does not matter

It seems I'm expecting too much  of visual studio.

**Comment by ConnorMcMahon** [comment]
@ravicini, I am not using paket (at least to the best of my knowledge I am not), and I am also lacking the extensions.json file (along with the other files generated with it. How were you able to generate that extensions.json file? I tried using the functions CLI to install the extensions as well, and that didn't generate the file either.

**Comment by ravicini** [comment]
@ConnorMcMahon 
It seems the source of my problems were the 2 different Microsoft.NET.Sdk.Functions references.
The generation of the extensions.json was not deterministic and sometimes it was generated.

I decided to move the new v2 runtime function app to a separate solution without paket. 
Now it works as intended.

Try to build the function app with `dotnet build` then the extensions.json file was generated.

**Comment by ColbyTresness** [comment]
@ConnorMcMahon is anything else required here then? Or should we track on the other issue?

**Comment by ConnorMcMahon** [comment]
It looks like this initial issue was resolved. My unrelated issue was resolve with the latest Microsoft.NET.Sdk.Functions release.
