### ISSUE TITLE
Function Binding docs shows partial list and/or shows experimental bindings

### ISSUE THREAD

**Issue by yochay** [Azure/Azure-Functions#104]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#advanced-binding-at-runtime-imperative-binding) includes only Twilio. But we got additional binding like SandGrid which are not documented. 

We currently do not mark binding experimental (there is a different Azure Functions Portal [issues ](https://github.com/projectkudu/AzureFunctionsPortal/issues/847) for it). But we should document all binding and mark respective one as experimental

**Comment by SyntaxC4** [comment]
This is partially due to Issue #44. There was some updating going on for the SendGrid Extension so we dropped the topic into the Blocked column. I will check with @mathewc to see if the SendGrid extension is back up to date.

**Comment by SyntaxC4** [comment]
I believe the intent of this issue is that we are inconsistent in how we communicate the support for the bindings. Let's make sure all GA quality items are listed and if any experimental items are available in the list let's mark them as such.

**Comment by rachelappel** [comment]
I've reviewed the bindings documents and they are now consistent.
Twilio and Sendgrid are no longer experimental.
