### ISSUE TITLE
Support 64 bit NodeJS executable

### ISSUE THREAD

**Issue by AshleyGrant** [Azure/Azure-Functions#1041]
Switching to the 64 bit runtime does not switch to a 64 bit version of Node. Unfortunately, this causes issues as there are some NPM packages that only support running on 64 bit Node. One in particular is "sharp." This is an image manipulation library that is orders of magnitude faster than alternatives, but only supports running on 64 bit Node due to it calling to DLLs that are compiled to run on x64.

As it currently stands, Node developers have no way to utilize 64 bit Node on a consumption plan. Switching to the 64 bit Node executable when running the function app in 64 bit mode would solve this problem.

**Comment by mhoeger** [comment]
This issue was moved to Azure/azure-functions-nodejs-worker#158
