### ISSUE TITLE
pyodbc module not found. Even when in requirements.txt and others working fine.

### ISSUE THREAD

**Issue by Programmer-david** [Azure/Azure-Functions#1043]
I'm using a Linux consumption plan.

I get the following error;
`Exception: ModuleNotFoundError: No module named 'pyodbc' `

I have added `pyodbc` in the `requirements.txt` file and other modules in this file such as `azure-storage` are working fine.

Has anyone seen this issue or can confirm this is a known bug. I can't see any way to manually install this.

**Comment by nkma1989** [comment]
I have this same issue! have you solved it?

**Comment by Programmer-david** [comment]
> I have this same issue! have you solved it?

I ended up moving to Docker functions for now. However it was raised as an issue and marked as resolved here https://github.com/Azure/azure-functions-python-worker/issues/249

**Comment by ColbyTresness** [comment]
Closing as it's tracked in python repo.
