### ISSUE TITLE
Question: usage of Microsoft.Extensions.Logging 2.1.1 in Azure function V1

### ISSUE THREAD

**Issue by stridsbr** [Azure/Azure-Functions#1046]
I'm trying to use switch to ILogger for structured logging to application insights instead of TraceWriter. I have a dependency on Microsoft.Extensions.Logging 2.1.1 in a nuget package.

Is there any plan to update the dependency on microsoft.extension.logging so that I can use Microsoft.Extensions.Logging v2.1.1 in Azure Functions v1? 

Steps to reproduce: 
Create a new Azure Function V1 with Microsoft.NET.Sdk.Functions 1.0.24. I install nugetpackage  Microsoft.Extensions.Logging v2.1.1. Create a function and change from tracewriter to ILogger.

Error message:
Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding.

If I uninstall the package it works again.

**Comment by ColbyTresness** [comment]
No, we won't be fixing this in V1. The guidance here would be to use V2.
