### ISSUE TITLE
Cannot create or debug function projects in VS2017- "One ore more errors ocurred"

### ISSUE THREAD

**Issue by Dalmirog** [Azure/Azure-Functions#1047]
Hi there,

This issue started happening 2 days ago. I'm usually up to date with my tooling, so Its not like I did a big update leap around those days.

**Repro Steps A**
1) Start debugging any existing function project. Project compiles just fine but it shows this error.

![image](https://user-images.githubusercontent.com/6180562/48978255-8a84a480-f087-11e8-8ba2-5d50c7c88a04.png)

**Repro Steps B**

1) Try to add a new Function project to your solution. Similar error occurs

![image](https://user-images.githubusercontent.com/6180562/48979178-9a0aea00-f095-11e8-858f-a3176ba8a317.png)

VS and System info: https://gist.github.com/Dalmirog/a604966b64977bef5a482a412fedd301

Feel free to ask me for any other kind of logs. I couldn't find anything useful myself.

**Comment by ErniepDev** [comment]
Experiencing the same issue. I tried updating both Visual Studio 2017 (version 15.9.3 after update) and the Azure Functions and Web Job Tools are on version 15.10.2046.0

**Comment by Dalmirog** [comment]
This is still happening to me after 24days. I literally cannot develop functions with this road block.

**Comment by SashaPshenychniy** [comment]
Same for me in 2019. Just updated VS and Azure Functions Tools to the latest version. 
Did anyone find a workaround?

**Comment by SashaPshenychniy** [comment]
If anyone interested - I found a fix: you need to **Unload-Reload VS project.** 
After this run project again and VS can identify you are running Azure Function for the first time now and it will download and install Azure Functions CLI. Actually it seems it was CLI missing causing the problem...

**Comment by ErniepDev** [comment]
Unfortunately didn't work for me. Unloaded, reloaded, and installed the new azure functions CLI. Still getting the same error.

Also, tried to reinstall VS2017 as well as the function extension, but no luck.

**Comment by blu3bl00d** [comment]
Also encountered this issue and came across this https://developercommunity.visualstudio.com/solutions/366797/view.html
Hope it helps

**Comment by ColbyTresness** [comment]
Solved by linked post.
