### ISSUE TITLE
VS Tools Fx solution directory structure not compatible with continuous integration

### ISSUE THREAD

**Issue by bragma** [Azure/Azure-Functions#105]
Hi,
I am trying to work on a Functions (Fx from now) solution created in VS with the new tools (C#), sync it on a git repo on VSTS and deploy to an Fx App on the portal using Continuous Integration feature.
This setup fails because the directory structure of the solution created by VS (and preserved on git repo) is not compatible with the structure of the repository expected by Fx portal for CI.

VS creates an Fx solution in this way:

SolutionFolder
-git repo stuff
-solution file
-ProjectFolder
--host.json
--appsettings.json
--Functions folders
---Function code

When this repo is synced to VSTS, the directory structure is preserved, i.e. The solution file and ProjectFolder are in the root.
If I enable integration from Fx's portal, the entire repo is downloaded into the wwwroot folder, so the structure is once again preserved. But this structure is incompatible to the way Fx host expects it to be:

Fx expects functions to be deployed in this way:
wwwroot
-host.json
-Functions folders (ProjectFolder)
--Function code

When using CI on a repo generated with VS tools, the result is:

wwwroot
-git repo stuff
-solution file
-ProjectFolder
--host.json
--appsettings.json
--Functions folders
---Function code

This obviously does not work. Fx host does not pick up the function...

Steps to reproduce:

- Install VS Tools for Fx
- Create a new Fx solution with Git (or setup git later, but you probably want to include the solution files too so create it on the solution folder level)
- Add a function in C# (but probably the problem is the same in any lang)
- Sync the solution to a git repo on VSTS 
- Enable CI on the Fx site

--> Check the deployed structure with Kudu, also the Fx code is not recognized.

Thanks!

**Comment by lindydonna** [comment]
@bragma Thanks for the details! You're right that the directory structure is one level off. We should fix the default, but think for now you can uncheck the box "Create directory for solution" when you create a new Function project (see screen shot). 

![image](https://cloud.githubusercontent.com/assets/4260261/21247185/6a84ade4-c2e2-11e6-8a31-b885b8d18d73.png)

**Comment by lindydonna** [comment]
@bragma I forgot there's another workaround: you can use a .deployment file in your repo root, or alternatively the PROJECT app setting. 

See: https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-folder-for-a-node-php-or-aspnet-site. 

Here’s an example: 
•	https://github.com/lindydonna/TestFunctionsPublish
•	https://github.com/lindydonna/TestFunctionsPublish/blob/master/.deployment

**Comment by kapopken** [comment]
I'll check this week if this fixes my issue and report back. I had the same problem. Unfortunately the fix is not very obvious for someone to find. Can't wait till this gets farther along!

**Comment by kapopken** [comment]
If you uncheck the create directory fur the solution you can't debug I found. Once you put it the solution back in its own folder debugging works again.

**Comment by lindydonna** [comment]
@kapopken Does your project happen to have periods in the name?  We had a bug where that caused the CLI to fail. Otherwise, I can't produce the situation you're describing, can you outline the exact steps you followed?

**Comment by kapopken** [comment]
Sorry I haven't had a chance to get back to this.  My project does not have periods in it.  You are putting the solution folder in a separate folder than the project folder?  So it should be 3 levels deep.  Solution Folder => Project Folder=> {NameOfFunctionFolder}

**Comment by lindydonna** [comment]
Handled with new VS tooling, which will be released very soon
