### ISSUE TITLE
Unable to use Key Vault references

### ISSUE THREAD

**Issue by asavaritayal** [Azure/Azure-Functions#1065]
_From @zmurphy-ms on December 6, 2018 2:4_

#### Investigative information

I'm trying to enable a KeyVault reference, but it's failing with KEY_ERROR both locally, and when deployed.

#### Repro steps

I followed the steps in https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references to create a KeyVault reference and added it to my App Settings.

#### Expected behavior

```os.environ['<key>']``` returns the secret value.

#### Actual behavior

```os.environ['<key>']``` causes a KEY_ERROR

<details>
<summary>Source</summary>

```python
# __init__.py

import logging
import os
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info(os.environ['<key>'])

    return "Done"
```

```txt
azure-functions==1.0.0a4
azure-functions-worker==1.0.0a4
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.11.0
```

</details>

_Copied from original issue: Azure/azure-functions-python-worker#258_

**Comment by asavaritayal** [comment]
KeyVault references use MSI behind the scenes to authenticate, which is not available on the Linux consumption preview offering today. Adding it to the backlog for prioritization and tracking. @mattchenderson @dariagrigoriu

**Comment by SamirFarhat** [comment]
Hi, if we request the msi endpoint via rest api, will we receive a token?

**Comment by Lybecker** [comment]
I ran into this issue today too

**Comment by vikasapr** [comment]
Hijacking this open issue. I also see 
os.environ['<App Settings>'] causes a KEY_ERROR

Is this related to this issue or a separate issue? Anyone else noticing it?

**Comment by mdudis** [comment]
I am also facing this issue.

**Comment by husseinkorly** [comment]
Btw, why is the `SecretVersion` required when adding `referenceString`?
It can just get the latest one unless you specify the secret version!

**Comment by anirudhgarg** [comment]
@balag0 please close this out when MSI is rolled out.

**Comment by divyagandhii** [comment]
MSI is rolled out in all regions.

**Comment by balag0** [comment]
Not the same as MSI. Keeping this issue open to track keyvault references feature backlog.

**Comment by abij** [comment]
We are experiencing the same problem, some more context to the FunctionApp:

- Function App: Python
- AppService: WestEuropeLinuxDynamicPlan (Consumption)
- FunctionApp Settings (secrets):
CLIENT_ID = @Microsoft.KeyVault(SecretUri=https://xxx.vault.azure.net/secrets/mysecret/versionhash)
- KeyVault: ManagedIdentity (Applition) has GET permissions on Secrets.

Result:
python os.environ does not contain the secret.

**Comment by balag0** [comment]
@abij KeyVault references are in the backlog. 
In the mean time you can use REST API + MSI to access key vault secrets. 
Sample code - https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#code-examples

Let us know if you run into any issues.

**Comment by ruhkopf** [comment]
Wanted to add that this issue also exists for NodeJS environments. Environment variables with @Microsoft.KeyVault just end up being undefined/empty. I hope this will be fixed very soon.

I just tried to use REST API + MSI, but I can't get token. :-( All I see is the following error response: 
```json
{"statusCode":503,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":"..."}
```

**Comment by jjgriff93** [comment]
We're getting the same error in our Azure Function using MSI to access both KeyVault and blob storage. Interestingly it was working for a short period of time and has started failing without any changes to our code or environment:

```
Traceback (most recent call last):
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/default.py", line 105, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/chained.py", line 65, in get_token
    raise ClientAuthenticationError(message=error_message)
azure.core.exceptions.ClientAuthenticationError: No credential in this chain provided a token.
Attempted credentials:
	EnvironmentCredential: Incomplete environment configuration
	MsiCredential: Unexpected response '{'statusCode': 503, 'message': 'An unexpected error occured while fetching the AAD Token.', 'correlationId': '9f85573a-e95e-4e2a-9c46-7ea63047aced'}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_download.py", line 366, in _initial_request
    **self._request_options
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 163, in download
    pipeline_response = self._client._pipeline.run(request, stream=True, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 208, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 80, in send
    response = self.next.send(request)
  [Previous line repeated 3 more times]
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 78, in send
    _await_result(self._policy.on_request, request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 47, in _await_result
    result = func(*args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_authentication.py", line 82, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/default.py", line 112, in get_token
    e.message
azure.core.exceptions.ClientAuthenticationError: 
No credential in this chain provided a token.
Attempted credentials:
	EnvironmentCredential: Incomplete environment configuration
	MsiCredential: Unexpected response '{'statusCode': 503, 'message': 'An unexpected error occured while fetching the AAD Token.', 'correlationId': '9f85573a-e95e-4e2a-9c46-7ea63047aced'}'
```

**Comment by balag0** [comment]
Keyvault references are supported in Linux (for a while now) Please open a new issue if any one is facing any problems with it.

Some of the more recent comments here seems related to MSI and not key vault references. Please follow https://github.com/Azure/Azure-Functions/issues/1486 for updates on that issue.
