### ISSUE TITLE
MSI support for linux consumption

### ISSUE THREAD

**Issue by asavaritayal** [Azure/Azure-Functions#1066]
_From @tjhgit on November 5, 2018 20:17_

I can set an identity (az functionapp identity assign) for my function app and register this identity with keyvault.

However when using MSIAuthentification() in the function app I get the error message:
* Getting error “MSI_ENDPOINT not in environment” when running the function app (method: MSIAuthentification())

What am I doing wrong?

_Copied from original issue: Azure/azure-functions-python-worker#232_

**Comment by asavaritayal** [comment]
MSI is currently not support by Linux consumption, which Python support is built on. Renaming the issue for tracking. 

/cc @mattchenderson @cgillum

**Comment by asavaritayal** [comment]
_From @tjhgit on November 6, 2018 22:13_

@asavaritayal : Is MSI also not supported for dedicated linux (docker) app plan? What is your suggestion on to how to access keyvault secrets from a linux app, then?

**Comment by asavaritayal** [comment]
_From @mattchenderson on November 7, 2018 17:10_

@tjhgit We're hoping to have it supported for dedicated Linux very soon. Certainly by end of year.

**Comment by marshallford** [comment]
An update for those interested: I spoke with a Microsoft PFE connected to the company I work for. He said:
> Our product team has logged this issue as an item to be fixed.  Time frame I would estimate to be by end of the Year.

**Comment by anirudhgarg** [comment]
We have started the work for this and hope to release within the next 2-3 months.

**Comment by stanleykylee** [comment]
@anirudhgarg any updates on this?

**Comment by Arnavion** [comment]
I noticed `MSI_ENDPOINT` getting set on my function app as of today, though attempting to use the endpoint always fails with an HTTP 503 `{"statusCode":503,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":"..."}`. So presumably it's not ready yet.

**Comment by balag0** [comment]
can you share the sitename?

**Comment by balag0** [comment]
@Arnavion Were you able to get this working?

**Comment by Arnavion** [comment]
You mean it's supposed to work? Since it returned a 503 I assumed it wasn't ready yet, as I said in my last comment. So I removed the code that attempted MSI and just use my own SP.

If you're saying it's supposed to work I can redeploy the version that tried to use MSI. Will be some time later this week though.

**Comment by balag0** [comment]
Yes. It should work. Please share the sitename after you try it out.

**Comment by Arnavion** [comment]
Sure. If you want to look at the logs of the time I made my last comment, the function app is `www-arnavion-dev`. There should be two functions called `UpdateCdnCertificate` and `CheckKeyVaultCertificate` that attempted the MSI auth and got a 503 a number of times between 2019-08-03 00:00 and 2019-08-04 04:00 UTC

**Comment by balag0** [comment]
Thanks. Looks like this app was running an older functions host version during this time. Please give it a try again and update here.

**Comment by Arnavion** [comment]
I confirmed that both the env vars are set on the app process. A request to the endpoint succeeded with an HTTP 200 response that had a JSON body with the required `token_type` and `access_token` properties. The app was successfully able to use the access token for a KeyVault request.

So everything looks like it works as of today. Thanks!

**Comment by ruhkopf** [comment]
Is this only fixed for the Python runtime? I'm trying to get a token for a NodeJS function, but it fails with the same error message:

```json
{"statusCode":503,"message":"An unexpected error occured while fetching the AAD Token.","correlationId":"..."}
```

**Comment by balag0** [comment]
The feature is available for all languages. Looks like something failed when authenticating with AAD. Need sitename / timestamp to investigate further and recommend opening a new issue.
