### ISSUE TITLE
Where should third party libraries be uploaded to?

### ISSUE THREAD

**Issue by ryancole** [Azure/Azure-Functions#1069]
Where, on the Azure Functions service, should I upload third party libraries that my Function applications might depend on? These are not compile-time dependencies and are not part of the Functions project itself. These are things I should be able to upload once and let them sit out there.

I tried seeing what `%AppData%` brought up, but on the Azure Functions platform it references a secured path on the C drive.

I tried putting these files in the wwwroot folder, but because I'm doing zip deploy I cannot write to the virtual file system.

Is there a shared location that can be accessed that I can put these dependencies in?

**Comment by ryancole** [comment]
I'm currently just uploading things to D:\home - is this acceptable?

**Comment by ColbyTresness** [comment]
Yeah this seems fine. I'd probably go with D:\home\data though. I think either will work.
