### ISSUE TITLE
Functions with CosmosDB binding and Preferred Location configuration

### ISSUE THREAD

**Issue by jjindrich** [Azure/Azure-Functions#1073]
We recommend you add feature requests to [UserVoice](https://feedback.azure.com/forums/355860-azure-functions).  This enables centralized feature requests and users the ability to vote.

**Comment by jjindrich** [comment]
If you configure binding with CosmosDB, you cannot configure Preferred location to optimize traffic to respect regions

**Comment by ColbyTresness** [comment]
@brettsam

**Comment by brettsam** [comment]
Already tracked at https://github.com/Azure/azure-webjobs-sdk-extensions/issues/363 (which has been fixed)

@ealsur as FYI.

Some docs:  https://medium.com/microsoftazure/azure-cosmos-db-functions-cookbook-multi-master-preferred-region-ac1f7c5d1d31.
