### ISSUE TITLE
CORS support for linux consumption

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#1074]
CORS handler is similar to the EasyAuth handler and not available on linux consumption workers currently.

**Comment by zavr-1** [comment]
Just spent a lot of time to migrate to Linux because there's no Perl on Windows that I need, just to see CORS not working 😒 Can't even set headers programmatically. There's no way to implement what I want on Azure unfortunately, switching to other faas for now sadly sadly. 

```js
if (req.method == 'OPTIONS') {
    return {
      status: 200,
      headers: {
        Allow: 'OPTIONS, POST',
        'Access-Control-Allow-Origin': req.headers.origin,
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
      },
    }
  }
```

**Comment by zavr-1** [comment]
So it turns out there's a way around it with proxies!!!
```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "cors": {
      "matchCondition": {
        "route": "{*restOfPath}",
        "methods": ["OPTIONS"]
      },
      "responseOverrides": {
        "response.statusCode": "200",
        "response.headers.Allow": "OPTIONS, POST",
        "response.headers.Access-Control-Allow-Origin": "{request.headers.Origin}",
        "response.headers.Access-Control-Allow-Methods": "OPTIONS, POST"
      },
      "backendUri": "https://localhost/cors"
    }
  }
}
```
The `backendUri` does not have to exist, however a single request seems to produce a lot of lines of logs like 
```
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=4ecff1d1-8f9a-4e9e-8f4a-57421530bba8)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=e9bfb86c-8108-41c9-9010-6df11e573692)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=1cf004ea-594e-49c0-82cb-320c001d7325)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=d1b1214e-ae96-4f86-97be-d452e5ef02a5)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=ae42539f-3ee1-4bc9-bc36-c685a2b0e9b7)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=28c0c35d-ef2d-45c1-aa1b-12757ff0e7b9)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=e9772c37-2769-4cf4-8e03-259247dc4259)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=bc889293-9ee6-4e79-80cd-57ba77a2ede4)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=27088c1c-290d-42e7-896a-9d6dee21d576)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=30070e13-0bcf-42e9-a0b2-3340ad3fdaac)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=1e5dbc75-e863-450a-a84f-c64f71fe0e04)
[14/03/2019 04:23:11] Executed 'Functions.cors' (Succeeded, Id=114e0dbb-b3b9-4a89-aa30-41838e4172d4)
```
so it's probably billed, but I'm sure there're improvements just don't understand why I see all these lines for a single OPTIONS request.

**Comment by mybrokengnome** [comment]
Any updates to this? Been fighting with CORS issues on a linux consumption plan for a few days now, no matter what I try it just doesn't want to work. And for some reason the CLI never publishes my proxies.json file so I can't try zavr-1's method.

**Comment by khaosdoctor** [comment]
Any updates on this? I'm still stuck in this, @zavr-1's method worked but I had to include `Access-Control-Allow-Headers` as well, however this is not nearly the best way to solve this problem...

It'd be very cool if there was an option to control CORS as a whole either from the CLI using `az functionapp cors add` or from the portal. This solution should be in the docs too

**Comment by t-muko** [comment]
CORS support for linux consumption function apps seems to be a moving target. What worked last week (python function setting CORS headers and replying OPTIONS-method requests), does not seem to work anymore.

It looks like if the Origin-header and Access-Control-Request-Method -headers are defined, the OPTIONS queries are never passed to the Python function, but the server seems to fail before that and no log entries or invocation information is ever logged.

I tried the above mentioned proxy definition as a workaround, but the problem seems to be happen before the query is getting into the proxy handler either.

Instead of giving a python function, the problem can be tested just by defining a proxy:
```
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "cors": {
      "matchCondition": {
        "route": "/api/app/{*restOfPath}",
        "methods": ["PATCH", "OPTIONS"]
      },
      "responseOverrides": {
        "response.statusCode": "200",
        "response.headers.Allow": "OPTIONS, POST",
        "response.headers.Access-Control-Allow-Origin": "{request.headers.Origin}",
        "response.headers.Access-Control-Allow-Methods": "OPTIONS, POST"
      },
      "backendUri": "http://localhost/api/app"
    }
  }
}
```

Then OPTIONS-method gives the no content response and no other headers whatsoever. (The behavior is the same with a real Python function instead of proxy definition)
```
curl -v "https://myfunctionapp.azurewebsites.net/api/app/location" -X OPTIONS -H "Access-Control-Request-Method: POST" -H "Origin: http://contoso.com" -H "Content-Type: application/json"

< HTTP/1.1 204 No Content
< Server: Kestrel
< Request-Context: appId=cid-v1:e6ca2498-XXXXX
< Date: Sat, 09 Nov 2019 10:37:53 GMT
```

Where PATCH method behaves like this:

```
curl -v "https://myfunctionapp.azurewebsites.net/api/app/location" -X PATCH -H "Access-Control-Request-Method: POST" -H "Origin: http://contoso.com" -H "Content-Type: application/json"

< HTTP/1.1 200 OK
< Allow: OPTIONS, POST
< Content-Length: 178
< Content-Type: text/html
< Server: Kestrel
< Access-Control-Allow-Methods: OPTIONS, POST
< Access-Control-Allow-Origin: http://contoso.com
< Request-Context: appId=cid-v1:e6ca2498-XXXXX
< Date: Sat, 09 Nov 2019 10:40:04 GMT
```

**Comment by balag0** [comment]
This is due to a configuration bug. More details at this thread
https://github.com/Azure/azure-functions-host/issues/5200

Status - Fix will deploy next week.  Apologize for the inconvenience.

**Comment by mhoeger** [comment]
@balag0 - I think this should be closed (based on https://github.com/Azure/azure-functions-host/issues/4889), but wondering if we're still waiting on configuring CORS through host.json? (https://github.com/Azure/azure-functions-host/issues/4911)

**Comment by balag0** [comment]
Yes. this should be closed. Thanks
