### ISSUE TITLE
Support bring your own storage for Linux functions

### ISSUE THREAD

**Issue by asavaritayal** [Azure/Azure-Functions#1078]
_From @priyaananthasankar on October 1, 2018 20:55_

Inferencing from a Keras model seems impossible with this issue:

Keras has an api called load_model which loads a pre-trained model from disk. It does not support loading this from a blob or file storage. It can load this from a mounted disk.

Azure functions on Python must provide a facility to be able to load model files from mounted storage. 

Ideally ML libraries must support loading models from cloud like blob storage/file share etc. But they seem to be supporting disk paths. 
Observed this with gensim, NLTK and now Keras.

If there is a way to access a specific disk from Python functions - load it from runtime or support SMB, it will bridge this gap to some extent. Here are some GitHub issues raised on the libraries themselves.

https://github.com/nltk/nltk/issues/2127
https://github.com/RaRe-Technologies/gensim/issues/2184

**Workaround**: Pickle the model while training it. Load the pickled model back. scikit supports this but Keras warns against pickling models, and suggests to go with their API.

The major concern with this workaround is for data scientists to be able to consciously store models in pickle format, which they will reject with passion - and its also wrong for them to persist this way.  Keras framework does not recommend persisting their models in pickle format - so this will not be preferred by data scientists. AWS lambda solves this by allowing disk access. 

_Copied from original issue: Azure/azure-functions-python-worker#213_

**Comment by brandonh-msft** [comment]
This feature should be available to Azure Functions in all tiers (Consumption, Premium, ISE, and App Service plans) for all languages and hosting options (Linux/Windows) at a production quality level. Not providing this feature turns customers away from Azure Functions for projects relating to Machine Learning.

**Comment by anirudhgarg** [comment]
> This feature should be available to Azure Functions in all tiers (Consumption, Premium, ISE, and App Service plans) for all languages and hosting options (Linux/Windows) at a production quality level. Not providing this feature turns customers away from Azure Functions for projects relating to Machine Learning.

@brandonh-msft  - we have this now available in Linux Consumption as well.
