### ISSUE TITLE
Hard dependency on Newtonsoft.Json 11.0.2

### ISSUE THREAD

**Issue by adrianknight89** [Azure/Azure-Functions#1079]
I just upgraded Newtonsoft to the latest version (12.0.1), but it looks like Functions SDK does not like this. 

`warning NU1608: Detected package version outside of dependency constraint: Microsoft.NET.Sdk.Functions 1.0.24 requires Newtonsoft.Json (= 11.0.2) but version Newtonsoft.Json 12.0.1 was resolved.`

Nuget snippet:

![capture](https://user-images.githubusercontent.com/16855542/50194431-789dc680-0300-11e9-81c5-1ed3f9e79c4e.PNG)

Can you update your dependency to the latest version or, if possible, change it to any version at and above (>=) the current version?

**Comment by adrianknight89** [comment]
Looks like this was reported here: https://github.com/Azure/azure-functions-vs-build-sdk/issues/270

**Comment by TehWardy** [comment]
This problem is seemingly not understood by the Core team here:
https://github.com/aspnet/AspNetCore/issues/9022
