### ISSUE TITLE
Tools Version Number Mismatch in Visual Studio

### ISSUE THREAD

**Issue by mcollier** [Azure/Azure-Functions#1081]
The Azure Functions and Web Jobs Tools version is different depending on where you look.  If you look in the Visual Studio Help dialog, the version shows as an older version than what is shown in the 'Extensions and Updates' dialog.  I see the following:

- About: 15.9.02046.0
- Tools > Extensions and Updates: 15.10.2046.0

I'm running Visual Studio 2017 version 15.9.4.

**Comment by ColbyTresness** [comment]
I can repro.

**Comment by ColbyTresness** [comment]
In VS 19 this is fixed, since the extension is part of the product.
