### ISSUE TITLE
".NET Object Error" surfaced instead of "Port Already In Use"

### ISSUE THREAD

**Issue by raahmed** [Azure/Azure-Functions#1088]
Context: Running Python on Functions in Linux (Preview) on VS Code.

Severity: Blocking
Reproduction Steps:
1.	Run ‘func host start’ and start the application.
2.	Stop the application using Ctrl + Z.
3.	Restart by executing 'func host start'.
4.	This .NET error is surfaced:
 
![image](https://user-images.githubusercontent.com/25991359/50662389-0c0b0480-0f5b-11e9-8611-5cd760bfca99.png)
 
Note: Lots of people appear to be struggling with this: https://github.com/Azure/azure-functions-core-tools/issues/907

Mitigation: 
1) Surface a 'port already in use' error instead of a dot-net error when the port needed for connection is occupied.

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#956
