### ISSUE TITLE
CLI Error Messages are Inaccurate with regards to flags usage

### ISSUE THREAD

**Issue by raahmed** [Azure/Azure-Functions#1089]
Context: Running Python on Functions in Linux (Preview) on VS Code. 

Severity: Potentially Serious (Potentially Blocking)

Reproduction Steps:
1.	CLI error messages are inaccurate and confusing - notice how the --name flag is present in the command. 

![image](https://user-images.githubusercontent.com/25991359/50662506-7fad1180-0f5b-11e9-856a-5b7c6a583baf.png)

Mitigation Method: 
1.	Have accurate error messages that point, specifically, to the actual problem.
Note: In this case, the actual error was never found. While debugging this issue, I encountered other issues that, once fixed, eventually led to this error never being seen again.

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#955
