### ISSUE TITLE
Noisy Error Messages Make It Difficult To Find True Error

### ISSUE THREAD

**Issue by raahmed** [Azure/Azure-Functions#1090]
Context: Running Python on Functions in Linux (Preview)
Severity:
Medium( Time Confusing - causes Developer Frustration)

Reproduction Steps:
0.  Add an 'import azure.storage' to your code - without installing azure.storage locally.
1. Execute 'func host start'.
2. Notice that Functions error messages are quite noisy - which makes it difficult to find relevant information. On occasion, multiple pages worth of errors have to be scrolled up to find what is needed. 
![image](https://user-images.githubusercontent.com/25991359/50662648-05c95800-0f5c-11e9-8899-056d0c05e724.png)
3. After multiple pages worth of scrolling, the true cause is found:
![image](https://user-images.githubusercontent.com/25991359/50662661-1083ed00-0f5c-11e9-9c94-0367bcc698ce.png)

Mitigation Steps:
0. Reduce the noise in the error messages so that it is easier to find the error.

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-python-worker#273
