### ISSUE TITLE
Clarify and Provide Guidance on Base64 Queue Encodings

### ISSUE THREAD

**Issue by raahmed** [Azure/Azure-Functions#1091]
Context: Running Python on Functions in Linux (Preview)

Severity: Serious (Blocking)

Steps:
1.	Azure Function's incoming queue bindings expect the data to be base64 encoded. This is not the default of the queue storage SDK - and leads to a tremendous amount of confusion across languages. 
2.	Communicating this in the documentation and providing a link to code for encoding correctly in Python would be very helpful.
![image](https://user-images.githubusercontent.com/25991359/50662840-999b2400-0f5c-11e9-9b42-c177e3387d8b.png)
Note: Others have struggled with this as well: https://github.com/Azure/azure-storage-node/issues/532

Mitigation Steps:
1.	Ensure that it is clear to customers that they need to encode their queue messages in base64 – and provide guidance on how to do so in Python.

**Comment by ggailey777** [comment]
@craigshoemaker I have assigned [this work item](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1422829) to you for tracking this is a Queue binding ref issue.

**Comment by craigshoemaker** [comment]
We decided not to include Queue encoding guidance in the binding ref as it was outside the scope of the binding doc. However, there is now an [Encoding](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#encoding) section in the binding ref to help surface the `base64` requirement by the binding.

#please-close

**Comment by ggailey777** [comment]
Thanks @craigshoemaker!

**Comment by ilayn** [comment]
This decision might be OK from Azure side but it is impossible to find which is causing many many days of searching trials and errors. Just google "base64 azure queue" and you'll see the extent of this problem. There *must* be some reference to it somewhere pointing to this encoding section because it is just annoyingly cryptic. Also the error message can be extremely simplified pointing to this instead of that long and meaningless sentence.

**Comment by ilayn** [comment]
Also look at this 

![image](https://user-images.githubusercontent.com/1303842/117568405-51f2ad00-b0c0-11eb-926a-0b80ddbc9c2c.png)
