### ISSUE TITLE
Set Up Logging By Default

### ISSUE THREAD

**Issue by raahmed** [Azure/Azure-Functions#1093]
Context: Running Python on Functions in Linux (Preview)

Severity:
Potentially Serious

Steps:
1.	For Functions, one must set up logging manually. 
![image](https://user-images.githubusercontent.com/25991359/50663136-863c8880-0f5d-11e9-910c-4668bf50c979.png)
2. The logging [set up document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring) itself is very long:
![image](https://user-images.githubusercontent.com/25991359/50663149-92c0e100-0f5d-11e9-88fe-7e250aecc54f.png)

Mitigation Steps:
1.	Enable basic logging by default or an easy opt-in at the start which does not need lengthy documentation.

**Comment by v-anvari** [comment]
Closing this issue as logging can be enabled while creating a function App
