### ISSUE TITLE
Unable to Create Function in Region of Choice.

### ISSUE THREAD

**Issue by raahmed** [Azure/Azure-Functions#1095]
Context: Running Python on Functions in Linux (Preview)

Severity:
Potentially Serious (Potentially Blocking)

Steps:
1) Notice this piece of documentation indicates a feature limitation: https://github.com/Azure/Azure-Functions/wiki/Creating-Function-Apps-in-an-existing-Resource-Group
![image](https://user-images.githubusercontent.com/25991359/50663867-f815d180-0f5f-11e9-98be-23ca5a7db165.png)

Mitigation: 
1) 1.	Enable users to create Dynamic Web Apps in region of choice.

**Comment by balag0** [comment]
@raahmed the limitations don't prevent creating the app in the region of choice. the restrictions only apply at resource group level.

please reopen if i misunderstood the issue and provide more details on what you are trying to do.

**Comment by raahmed** [comment]
@balag0  - Thanks for responding. When I read the message 'This resource group already contains regular Web Apps in the same region that you're trying to create the Functions App', I read it as 'choosing a different region in the same resource group will mitigate the issue'. In fact, when I chose a different region in the same resource group, everything started working. Should this not have happened?

In any case, ultimately, I would have liked to create the Functions app in the same region and same resource group as the regular web app.

**Comment by raahmed** [comment]
@balag0  - I understand that this is due to a limitation that scale units do not support hosting multiple app types. Generally, a given developer using Functions as part of a web workload will likely want to have their functions code executing in the same geo-location in the same resource group as their standard web app. This issue, then, would translate to eliminating that limitation. Are there any plans to do so?

**Comment by balag0** [comment]
No. There are no plans currently to support different function app types in the same resource group + region.

**Comment by balag0** [comment]
@raahmed do you have any other questions on this issue? if not we can close this next week.

**Comment by raahmed** [comment]
Hi @balag0  - the team will re-evaluate the feasibility and cost for redesigning this particular piece and circle back. Please do not close this issue.

**Comment by paulbatum** [comment]
Indeed, this issue should stay open and track this limitation, even if there is no ETA for when it will be resolved.
