### ISSUE TITLE
[Premium] additional regions to deploy premium sku function app in

### ISSUE THREAD

**Issue by mdddev** [Azure/Azure-Functions#1096]
**Describe the bug**
Not a bug. It's clearly stated that there's only one supported region as of now (South Central US). And we should open an issue here if additional regions are required. So here it is. In my particular case and due to internal policies at my company, I'm only allowed to deploy any Azure resources into the WEST EUROPE region. To do conceptual testing the existing region would suffice, but if this would be to remain the only supported region, the premium sku of Azure Functions is effectively unavailable to me.

**To Reproduce**
Evaluate the premium functions sku. Reading the readme.md

**Expected behavior**
More supported regions if the premium sku moves towards public preview and or GA.

**Additional context**
https://github.com/Azure/Azure-Functions/blob/master/functions-premium-plan/overview.md#regions

**Comment by jeffhollan** [comment]
Thanks! West Europe planned to roll out in next week or so

**Comment by VladimirSorokoumov** [comment]
Great to have this in Azure West Europe in next week(s). Will that be also only private preview? When can we expect GA of this in West Europe?

**Comment by TimPosey2** [comment]
Any hope of this coming to `East US` anytime soon?

**Comment by alexkarcher-msft** [comment]
Hi Tim,

There's a pretty involved platform change rolling out on our side to get more regions enabled, but I'd expect East US to be lit up in about 6 weeks.
