### ISSUE TITLE
[Premium] Cannot create Azure Function Premium Plan with Azure CLI

### ISSUE THREAD

**Issue by markgossa** [Azure/Azure-Functions#1097]
**Describe the bug**
Unable to create an Azure Function Premium Plan

**To Reproduce**
1. Log into Azure Cloud Shell
2. az group create -l southcentralus -n functions-premium
3. az functionapp plan create -g functions-premium -n functions-premium-7984792 -l southcentralus --number-of-workers 2 --sku EP3 --debug

You can also reproduce the issue by creating the RG and plan in West Europe.

**Workaround**
Change the Sku to another like S1 however is this going to still be the premium plan?

az functionapp plan create -g functions-premium -n functions-premium-7984792 -l southcentralus --number-of-workers 2 --sku S1 --debug

**Expected behavior**
Create a function app premium plan

**Screenshots**
![image](https://user-images.githubusercontent.com/16326726/50676054-0d374280-0fea-11e9-9d9c-344692c0fd35.png)

**Additional context**
We have 4 App Service Plans in the subscription: 1 Free, 1 Standard and two Consumption. This is the first Azure Functions Premium Plan.

**Comment by jeffhollan** [comment]
Thanks for filling. Looking into this

**Comment by jeffhollan** [comment]
Circling back on this - we upped the limit to 10 plans per subscription.  That limit may increase as we progress in the preview but for now at least you should be able to get by with having more plans.  If that's not enough feel free to let me know.
