### ISSUE TITLE
Are we going to plan azure signalr service trigger/bindings?

### ISSUE THREAD

**Issue by yasin-uohyd** [Azure/Azure-Functions#1099]
Hi,

Are we going to see Azure SignalR Service to trigger a function.?

**Comment by paulbatum** [comment]
@yasin-uohyd This is best asked of the maintainers of the signalr extension. I'd suggest you post the question here:
https://github.com/Azure/azure-functions-signalrservice-extension/issues

**Comment by ColbyTresness** [comment]
Closing in favor of tracking elsewhere.
