### ISSUE TITLE
.NET SDK Installation Error Message Does Not Provide Installation Details

### ISSUE THREAD

**Issue by raahmed** [Azure/Azure-Functions#1101]
Context: Running Python on Functions in Linux (Preview)
Severity: Moderately Confusing.
Reproduction Steps:
0) Execute 'func host start' without fulfilling the .NET SDK pre-requisite.
1) Notice this error message:
![image](https://user-images.githubusercontent.com/25991359/50856265-148a8300-133f-11e9-9ca7-0072c1e5840f.png)
2) Notice that the error message does not contain details of which of the options the users should choose in the download link provided:
![image](https://user-images.githubusercontent.com/25991359/50856313-3dab1380-133f-11e9-8bad-b3c5993b139e.png)

Mitigation: 
1) In the error message, provide information as to which of the options should be clicked on the installation page.

(Related to https://github.com/Azure/Azure-Functions/issues/1087)

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#964
