### ISSUE TITLE
Visual Studio new project wizard still shows preview

### ISSUE THREAD

**Issue by ADringer** [Azure/Azure-Functions#1105]
I'm using Visual Studio 2017 and have the latest version of Functions tooling installed:

![image](https://user-images.githubusercontent.com/19554490/50964320-e20b9200-14c6-11e9-82a8-276d9d1fa9b5.png)

However when I go to create a new Function project it still says V2 is in preview:

![image](https://user-images.githubusercontent.com/19554490/50964359-fe0f3380-14c6-11e9-8723-ee00585c8743.png)

Is there something else I have to update to get the new project wizard to show the latest version? 

Thanks

**Comment by JohnReeson** [comment]
Have a look at the [wiki](https://github.com/Azure/azure-functions-tooling-feed/wiki/Fixing-Azure-Function-Core-Tools-download-issues-for-Visual-Studio) about downloading cli and templates in VS.

**Comment by ADringer** [comment]
Thanks, that worked for me (the automated script). I think the issue is related to corporate proxy as I had to amend the powershell script to use the proxy for the `BitsTransfer`.

Thanks
