### ISSUE TITLE
Cannot publish Azure Functions V2

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/Azure-Functions#1108]
Hi All,

I'm struggling with publishing my Function App directly from Visual Studio. Steps to reproduce:

1. Create a new Azure Functions V2 project
2. Create a function 
3. Try to publish it

Symptoms:
During Web Deploy I'm getting the following error:
```
Publish Started
  ServicePlatform.BuildPublisher -> C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\bin\Release\netcoreapp2.1\bin\ServicePlatform.BuildPublisher.dll
  ServicePlatform.BuildPublisher -> C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\obj\Release\netcoreapp2.1\PubTmp\Out\
  Adding directory (serviceplatformdevops-euw-buildpublisher\bin).
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Web deployment task failed. ((14.01.2019 09:05:01) An error occurred when the request was processed on the remote computer.) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :  [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : (14.01.2019 09:05:01) An error occurred when the request was processed on the remote computer. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : An error was encountered when processing operation 'Create Directory' on 'D:\home\site\wwwroot\bin'. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : The error code was 0x800703E6. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Invalid access to memory location. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :  [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :    at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :    at Microsoft.Web.Deployment.FileSystemInfoEx.set_Attributes(FileAttributes value) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :    at Microsoft.Web.Deployment.DirPathProviderBase.Add(DeploymentObject source, Boolean whatIf) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
  Publish failed to deploy.
```

During Zip Deploy I'm getting:
```
Publish Started
  ServicePlatform.BuildPublisher -> C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\bin\Release\netcoreapp2.1\bin\ServicePlatform.BuildPublisher.dll
  ServicePlatform.BuildPublisher -> C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\obj\Release\netcoreapp2.1\PubTmp\Out\
  Publishing C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\obj\Release\netcoreapp2.1\PubTmp\ServicePlatform.BuildPublisher - 20190114090906599.zip to https://{my-domain}.scm.azurewebsites.net/api/zipdeploy...
C:\Users\kamz\.nuget\packages\microsoft.net.sdk.functions\1.0.24\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Publish.ZipDeploy.targets(42,5): error : The attempt to publish the ZIP file through https://{my-domain}.scm.azurewebsites.net/api/zipdeploy failed with HTTP status code RequestTimeout. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
```

Things to note:
- I have created a new Function App using Visual Studio
- I was able to publish my project a few times but generally it's failing
- I tried to recreate deployment credentials - didn't work

I will try to recreate the Function App and will tell whether it works.

Best regards,
Kamil

**Comment by mirko-horvacki** [comment]
Hi All,

"Symptoms: During Web Deploy I'm getting the following error:
Publish Started
  ServicePlatform.BuildPublisher -> C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\bin\Release\netcoreapp2.1\bin\ServicePlatform.BuildPublisher.dll
  ServicePlatform.BuildPublisher -> C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\obj\Release\netcoreapp2.1\PubTmp\Out\
  Adding directory (serviceplatformdevops-euw-buildpublisher\bin).
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Web deployment task failed. ((14.01.2019 09:05:01) An error occurred when the request was processed on the remote computer.) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :  [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : (14.01.2019 09:05:01) An error occurred when the request was processed on the remote computer. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : An error was encountered when processing operation 'Create Directory' on 'D:\home\site\wwwroot\bin'. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : The error code was 0x800703E6. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Invalid access to memory location. [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :  [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :    at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :    at Microsoft.Web.Deployment.FileSystemInfoEx.set_Attributes(FileAttributes value) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :    at Microsoft.Web.Deployment.DirPathProviderBase.Add(DeploymentObject source, Boolean whatIf) [C:\DTC\ServicePlatform\ServicePlatform.Deployment\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher\ServicePlatform.BuildPublisher.csproj]
  Publish failed to deploy." 

- same error observed today, please write if there is solution.

Thanks,
Mirko

**Comment by kamil-mrzyglod** [comment]
@mirko-horvacki Recreating a Function App makes Web Deploy work in my case. However, still, it is just a workaround.

**Comment by eliashdezr** [comment]
I'm not able to publish too. Using the profile doesn't give any details, just this:

![image](https://user-images.githubusercontent.com/6153607/51422820-3e337d80-1b7b-11e9-8dc4-2b8351faadc1.png)

And on the output window it just displays this;
`  Publish Started`

I'm using `v1.0.24` with Visual Studio 2019 Preview 1.

**Comment by mirko-horvacki** [comment]
Hi All,

in our case publish did not worked because WEBSITE_RUN_FROM_PACKAGE setting was set to 1, after changing setting to 0 publish from VS started working.

Mirko

**Comment by ColbyTresness** [comment]
The takeaway here isn't a VS change, it's a documentation improvement that we're tracking elsewhere to make our deployment flows more transparent. Closing.

**Comment by ashkansirous** [comment]
I don't understand! Mine is failing with this error and there is no WEBSITE_RUN_FROM_PACKAGE  in my appsettings in azure function.  :
```

20-06-2019 20:26:55
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__176.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

===================



Here is the output of my VS (2019 enterprise v16.1.3)

```

**Comment by ColbyTresness** [comment]
Please open a separate issue with repro steps, I don't think the above is related to having the run from package app setting.

**Comment by pinopane** [comment]
> Hi All,
> 
> in our case publish did not worked because WEBSITE_RUN_FROM_PACKAGE setting was set to 1, after changing setting to 0 publish from VS started working.
> 
> Mirko

Thanks

**Comment by SteveFarnaby999** [comment]
Hi All,

Is there a resolution to the above problem - I am getting the same issue when publishing azure function from Visual Studio:

```
2019/09/19 12:51:45
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__205.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

System.Exception: Publishing failed.
```

**Comment by pinopane** [comment]
Hi, go to azure portal, in your azure functions options, click in configuration, set WEBSITE_RUN_FROM_PACKAGE in 0, try again.

**Comment by SteveFarnaby999** [comment]
I tried setting WEBSITE_RUN_FROM_PACKAGE to 0 but still the same publish failure

**Comment by muralidharvr** [comment]
Even I am similar issue. The function app deployment through VSTS Release pipeline worked well till last month. Yesterday when we checked, the Azure FunctionApp Deploy task is continuously failing. We now switched to App Service Deploy activity and seems to be working fine. But wanted to understand why Azure Function App Deploy activity which worked months ago is failing all of a sudden?

**Comment by SteveFarnaby999** [comment]
It seems this problem could be because Visual Studio will timeout if some part of the deployment does not happen within a certain time frame.  We have found this problem to be sporadic which would point to a timeout issue as out internet connection's speed varies quite a lot.

**Comment by keith-knight** [comment]
We ran into the same issue and found that as Steve mentioned above it was an issue with the network being too slow. There were some batch jobs that were slowing the network down - as soon as these were disabled the deployment worked.

It would be nice if there was a way to increase the timeout since if you have a slow network there is no way to deploy a package? Ours wasn't particularly big either, the zip file was only ~25mb.

**Comment by queryquandary** [comment]
I had the same problem updating my Azure function app from VS2019.  I was able to get it publishing working again by updating the Cloud Explorer extension in Visual Studio to the current version, in my case "Cloud Explorer for VS Preview" (ver 1.2.1909.172).

**Comment by NogginBox** [comment]
> The takeaway here isn't a VS change, it's a documentation improvement that we're tracking elsewhere to make our deployment flows more transparent. Closing.

@ColbyTresness Where are you tracking this? Finding debugging deployment issues very frustrating and would love it to be more transparent.

**Comment by Hemanth089** [comment]
> I had the same problem updating my Azure function app from VS2019. I was able to get function app publishing working again by updating the Cloud Explorer extension in Visual Studio to the current version, in my case "Cloud Explorer for VS Preview" (ver 1.2.1909.172).

Thanks. This works for me after lot of struggling
