### ISSUE TITLE
deploying event grid function

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#1109]
I am trying to publish an Azure Function with Event Grid binding through VS. I've created a function.json as described in the official docs:

> 
> {
>   "bindings": [
>     {
>       "type": "eventGridTrigger",
>       "name": "eventGridEvent",
>       "direction": "in"
>     }
>   ],
>   "disabled": false
> }

When publishing it to Azure, it seems that it's being overwrited to:

> 
> {
>   "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.24",
>   "configurationSource": "attributes",
>   "bindings": [
>     {
>       "type": "eventGridTrigger",
>       "name": "eventGridEvent"
>     }
>   ],
>   "disabled": false,
>   "scriptFile": "../bin/FunctionApp2.dll",
>   "entryPoint": "FunctionApp2.Function1.EventGridTest"
> }

what is the proper way to define event grid subscription when developing with Visual Studio?

**Comment by jeffhollan** [comment]
The generated function.json is still valid.  It's just adding some additional info as you are running via pre-compiled bits so it's pointing to the script and entrypoint.  The main distinction here is the Event Grid *subscription* is an actual Azure Resource you'll need to create seperate from the publish step.  The easiest way today is opening the function in the portal and clicking the "add new event grid subscription" button when the function is open.  This will give you some UX to point Event Grid to the function.  You could do it programatically but it would be with an ARM template or Azure CLI or something.  Would really depend on the event grid docs for the gesture to create those subscriptions.

**Comment by thdotnet** [comment]
Got it. So, by using precompiled functions, I'll need to run a "post script" to subscribe my function to the event grid subscription, is that correct? Shouldn't this be handled by VS when using precompiled functions? Can't we define a reserved key on function.json that would automate this?

**Comment by jeffhollan** [comment]
Correct.  And the only way to create a subscription is through the Azure Resource Management layer - so no keys or connection strings you can use to do it like our other triggers.  It has to be done with an AAD token or service principal.  Definitely worth communicating to Event Grid team though and letting them know you want the ability to create a subscription in VS.  FWIW I have a meeting with them for next week and this is one of the big items I want to bring up

**Comment by thdotnet** [comment]
Awesome! Should I send an email mvp list about it just to reforce this is a "problem"?

**Comment by thdotnet** [comment]
Thanks Jeff, I appreciate that.

**Comment by ColbyTresness** [comment]
Closing this as it seems to be resolved. Please reopen if necessary.
