### ISSUE TITLE
Blob Function Trigger supported types

### ISSUE THREAD

**Issue by brentstineman** [Azure/Azure-Functions#111]
In this document: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage#a-idstorageblobtriggera-azure-storage-blob-trigger

I think the section on "Blob trigger supported types", it could be taken as a bit misleading. The section starts off with "The blob can be deserialized to any of the following types" and the example shows using a string object. I think the section could be improved by instead talking about the overall set of bindings that are available and showing an example of one of them. Then showing that a string/json binding is also possible and you get the deserialized object.

**Comment by SyntaxC4** [comment]
Can we provide a few examples around into [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#input-usage) doc:

* String based content
* Json based content
* Binary based content

**Comment by lindydonna** [comment]
Changes in progress here: https://github.com/Microsoft/azure-docs-pr/pull/14047
