### ISSUE TITLE
Support creating "empty" linux consumption function app

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#1113]
During app creation WEBSITE_CONTENTAZUREFILECONNECTIONSTRING , WEBSITE_CONTENTSHARE are always required currently.
In scenarios where client uses Run-From-Package these app settings are never used. Provide a way to create apps without WEBSITE_CONTENT.. appsettings if we know they will never get used.

**Comment by balag0** [comment]
We needed WEBSITE_CONTENTAZUREFILECONNECTIONSTRING , WEBSITE_CONTENTSHARE earlier to support in portal creation and editing of functions. But we don't need them anymore.

**Comment by dariagrigoriu** [comment]
Completed.
