### ISSUE TITLE
Deploy Java Functions to Azure Functions Runtime

### ISSUE THREAD

**Issue by burf2000** [Azure/Azure-Functions#1117]
I can find no way to deploy a Java Azure Function to Azure Function Runtime 2?

I have raised a StackOverFlow in case I am missing something.  I did read that the Runtime does support Java
https://stackoverflow.com/questions/54382159/deploying-a-java-azure-function-to-azure-functions-runtime-on-premises

**Comment by kashimiz** [comment]
Your best bet to run Azure Functions on-premise would be to use the [container images of Azure Functions we provide on Docker Hub.](https://hub.docker.com/r/microsoft/azure-functions/) Unfortunately at this time we do not yet have a Java Docker image. I've filed issue Azure/azure-functions-docker#70 to track this gap.

One potential workaround would be to publish the [build artifacts we provide with each release,](https://github.com/Azure/azure-functions-host/releases) which are packaged versions of the runtime. However, this isn't something commonly done and there would be a fair amount you'd have to figure out as you go.

**Comment by ColbyTresness** [comment]
Closing, please track on referenced issue [Azure/azure-functions-docker#70](https://github.com/Azure/azure-functions-docker/issues/70)
