### ISSUE TITLE
Host Key does not work for v2: Unauthorized

### ISSUE THREAD

**Issue by knikol** [Azure/Azure-Functions#1118]
**Azure Function v2**
HttpTrigger function with Admin authentication type. Host Key does not work for this function: it returns "Unauthorized" (master key does work). Function was created and published with VS 2017.

Http call:
`(https://function-name.azurewebsites.net/api/v1/test?code=KEY)`
or pass code via http-header: x-functions-key

Standard App Service plan, Platform: x64

**Application Settings**
```
FUNCTIONS_EXTENSION_VERSION: ~2
FUNCTIONS_WORKER_RUNTIME: dotnet
WEBSITE_WEBDEPLOY_USE_SCM: false
```
**host.json**
```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "HubName": "DurableFunctionsHubV1"
    }
  }
}
```
**C# code**
```
    public static class Function1
    {
        [FunctionName("Test")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Admin, "get", "post", Route = "v1/test")] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            return new OkObjectResult($"Hello");
        }
    }
```

**function.json**
```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.24",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "route": "v1/test",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "admin",
      "name": "req"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/XXX.dll",
  "entryPoint": "XXX.Run"
}
```

**Comment by kashimiz** [comment]
Where/how are you getting your host and master keys from, @knikol?

**Comment by knikol** [comment]
From Azure Portal UI.
1. Select function app -> function name -> get function Url -> choose Default (Host Key)
Or 
2. Select function app -> function name -> Manage -> Host Keys (All functions) -> default
Or
3. Select function app -> function app settings -> Host Keys (All functions) -> default

**Comment by alrod** [comment]
@kihol, you should use `"authLevel": "function"` in `funciton.json` when using host key
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#trigger---configuration

**Comment by knikol** [comment]
@alrod, thank you. My bad. Indeed, it works.
