### ISSUE TITLE
See the next occurrences for TimeTrigger in Azure 

### ISSUE THREAD

**Issue by vinguan** [Azure/Azure-Functions#1120]
The Azure Functions CLI has this cool feature that shows the next schedule occurrences for a function with a Time Trigger : 
![image](https://user-images.githubusercontent.com/6222878/52197950-70660000-2848-11e9-9218-2a0877944cb3.png)
Is there a way to see this on Azure portal or through some other place? If not this would be a cool feature to add.

**Comment by ColbyTresness** [comment]
Closing, please track via the referenced issue in the function portal repo.
