### ISSUE TITLE
Linux timer-triggered function stopped firing

### ISSUE THREAD

**Issue by swt2c** [Azure/Azure-Functions#1124]
I have a Linux (Python) function that is timer triggered to fire once an hour on the :15 mark:
`"schedule": "0 15 * * * *"`

This was working fine until 2019-02-09 00:15:00.217, but the timer has not fired since.  Is this a known issue?

**Comment by maiqbal11** [comment]
This issue was moved to Azure/azure-functions-python-worker#320
