### ISSUE TITLE
Function inside App Service Environment not being triggered

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#1128]
I've started a small thread on twitter about this problem. I have an App Service Environment and a Function App inside of it. The type of the Load Balancer is Internal, I believe this is a important detail.

Using a VM in the same vnet, I can navigate to kudu and using cmd console perform tcpping to external endpoints and they are all working properly.

My function is using a Blob Trigger and on the storage account level it is not restricting any vnet so it can be achieved by the function.

The main problem is that it's not being triggered and I don't know exactly how to trobleshoot. The AzureWebJobStorage has no entries / errors neighter also on the Metrics, no Function Execution Count.

Is there any other task that I can execute in order to identify the problem?

**Comment by maiqbal11** [comment]
@ccompy, would you be able to triage since this appears to be an ASE issue?
