### ISSUE TITLE
Cannot import email.mime with Python (v3.6) Azure Function v2

### ISSUE THREAD

**Issue by chisqrd** [Azure/Azure-Functions#1129]
I cannot seem to email from an python azure function on linux consumption plan. I created a function with Visual Studio Code and it does locally run fine.

`requirements.txt` has the following

`azure-functions==1.0.0b3 ` 
`azure-functions-worker==1.0.0b3  `
`grpcio==1.14.2  `
`grpcio-tools==1.14.2  `
`protobuf==3.6.1  `
`six==1.12.0  `
`psycopg2==2.7.6.1  `
`azure-keyvault  `
`azure-common  `

Where it errors out is 
`from email.mime.multipart import MIMEMultipart`
though I did verify right before that email package was in sys.modules. 

The error I get is the following
>2019-02-14T17:46:30.945 [Error] An error occurred: No module named 'email.mime'

Is this a known issue or am i missing something?

**Comment by maiqbal11** [comment]
This issue was moved to Azure/azure-functions-python-worker#328
