### ISSUE TITLE
Clarify private and shared assemblies (C#, F#)

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#113]
Need to update the documentation here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#referencing-external-assemblies to describe the distinction between **shared** and **private** assemblies.
	
- Shared assemblies are shared across all functions within a function app
- Private assemblies are part of a given function's context
   - Supports side loading of different assembly versions from different locations
- Private assemblies **must** be in a folder called "bin"

**Comment by SyntaxC4** [comment]
Currently we only have information on the `bin` folder. We should specify more information on how assemblies can be loaded. Current doc reads as follows:

> If you need to reference a private assembly, you can upload the assembly file into a bin folder relative to your function and reference it by using the file name (e.g. #r "MyAssembly.dll"). For information on how to upload files to your function folder, see the following section on package management.

Let's ensure that we cover a number of scenarios instead of a bin directory local to a single function (as described above)

**Comment by lindydonna** [comment]
@rachelappel Can you take this?  Let me know if you need more information.

**Comment by brharr** [comment]
I would like to add a comment here on this issue. In addition to providing more clarification about uploading, I believe that there should be more clarification on the Shared as well. The way that the page reads right now is that there is a specific set of Shared assemblies that can be called using the #r operator when in fact there are a number of others. For example, I needed to use System.Data which can be referenced, but it is not on the documentation page. So there either needs to be a complete list of what can be shared automatically versus what needs to get pulled from NuGet versus what needs to be uploaded.

**Comment by rachelappel** [comment]
@lindydonna Yeap I got it.

**Comment by andresnava** [comment]
Would it be possible to add a note about what happens when we have compiled functions that use Nuget packages that are also in the set of Shared assemblies? 

For instance, if I have a compiled function that references Azure Storage Nuget package with a specific version, what happens when the Shared assembly for Azure Storage is a different version? Does the version in my Nuget package get used or will it be the Shared assembly?

**Comment by lindydonna** [comment]
@andresnava I believe the shared assembly will take precedence, but @fabiocav can confirm.

**Comment by lindydonna** [comment]
Documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#referencing-custom-assemblies
