### ISSUE TITLE
HttpTrigger - Route parameters missing

### ISSUE THREAD

**Issue by crac2003** [Azure/Azure-Functions#1131]
**Description**: Url parameters passed through route template are not parsed and they are missing from req.Query dictionary

`
 [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "local/{name}")] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            
            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }`

**Request:** [GET] /local/test-name

**Current response**: [400] "Please pass a name on the query string or in the request body"

**Expected response**: [200] "Hello, test-name"

**Details:**
Target framework: .NET Core 2.1
VS: 15.9.7

**Comment by ColbyTresness** [comment]
@soninaren thoughts on this?

**Comment by soninaren** [comment]
@crac2003 URL route parameters are accessible as method parameters. Change the method signature to 
```CSHARP
[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "local/{name}")] HttpRequest req, string name, ILogger log)
```
The code is behaving as expected since name is not present in the query string or in the request body

**Comment by crac2003** [comment]
Right, I asked about it because when I've put this as a parameter, function app couldn't resolve url with guid correctly - it seems to be working fine with strings now. Thanks.
