### ISSUE TITLE
Document that local zip performs better than external zip

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#1133]
Regarding this document:
https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package

Current data indicates that "local zip" (i.e. `WEBSITE_RUN_FROM_PACKAGE=1`) provides better cold start performance than "external zip" (i.e. `WEBSITE_RUN_FROM_PACKAGE=https://...`). This document should explain this so that users can make an informed decision.

**Comment by jeffhollan** [comment]
docs merged in
