### ISSUE TITLE
Azure Function extention update fails

### ISSUE THREAD

**Issue by Dan-cws** [Azure/Azure-Functions#1135]
**Issue**
Manual update of Azure Function and Web Jobs Tools extention fails with error "This extension is already installed to all applicable products".

**Software versions**
OS: Windows 10 Pro.
Visual Studio: Professional 15.9.7
Extention version before update: 15.0.30923.0

*Workaround*
Delete these directories as explained here: https://stackoverflow.com/questions/54243585/azure-functions-and-web-jobs-tools-extension-update-failed and rerun vsix.
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Web Tools Azure\Webjobs
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\[6randomletters].[3randomletters] (in my case was ogspqttv.htj) with the extensions.

**Step to reproduce**
- Uninstall Azure development from Visual Studio Install
- Clear MEF Cache (with the extension ClearMEFComponentCache)
- Reinstall  Azure development from Visual Studio Install

**Comment by ColbyTresness** [comment]
In VS19 this is fixed since the extension is part of the product.
