### ISSUE TITLE
blob trigger with VS C# SDK: dataAccount cannot be null

### ISSUE THREAD

**Issue by brentstineman** [Azure/Azure-Functions#114]
I'm attempting to create a blob trigger using the VS SDK. When i attempt to run the function, I get the following error:
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.BlobTriggerCSharp'. Microsoft.Azure.WebJobs.Host: Value cannot be null.
Parameter name: dataAccount.
Error indexing method 'Functions.BlobTriggerCSharp'

appsettings.json file appears like this:
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=cubicinbound;AccountKey=blahblahblah==;",
    "AzureWebJobsDashboard": ""
  }
}

function.json is like:
{
  "disabled": false,
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "inbound",
"DefaultEndpointsProtocol=https;AccountName=cubicinbound;AccountKey=blahblahblah==;"
    }
  ]
}

I've tried placing the "missing" setting in both files and have not been able to resolve the error.

**Comment by brentstineman** [comment]
I found my root issue. I have a connection string on both and the function.json should instead be the name of an appsetting parameter. In this cause, the error is simply a little misleading. :)

**Comment by soninaren** [comment]
There is a PR out to fix the error message.
https://github.com/Azure/azure-webjobs-sdk/pull/946
