### ISSUE TITLE
Container specialization fails with 404

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#1144]
/admin/instance/assign fails with the following response. The request did not reach the container, so seems to be failing somewhere earlier in the pipeline.

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /admin/instance/assign was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at 104.210.48.193 Port 80</address>
</body></html>

**Comment by balag0** [comment]
Impacted 11 sites (24 instances) in the last 30 days.

**Comment by dariagrigoriu** [comment]
No repro, closing for now.
