### ISSUE TITLE
Azure time trigger multiple times instead of one

### ISSUE THREAD

**Issue by weihangChen** [Azure/Azure-Functions#1145]
my time trigger is set to run every 10 mintues
` public static void Run([TimerTrigger("0 */10 * * * *")]TimerInfo myTimer)
`
and I log the start of the program and the end of program at exits. No error happens during the program, every 10 minutes, when the service starts, it starts ex. 50 times instead of 1 time.

**Comment by ColbyTresness** [comment]
Please open a support ticket with details about your application (name, region, timeframe of execution, etc.) We can file a github issue once we figure out what the bug is.
