### ISSUE TITLE
Provide clear messaging when the Visual Studio extension is out of date

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/Azure-Functions#1150]
_From @alexkarcher-msft on July 2, 2018 17:54_

There are many tickets reporting failed deployments, with the mitigation being to update the VS SDK. If we can make the old SDKs pop an error in VS and suggest to update, that would be ideal, but at least capturing the old SDK versions and returning a more helpful error message would be a good first step.

_Copied from original issue: Azure/azure-functions-vs-build-sdk#281_

**Comment by ColbyTresness** [comment]
_From @jeffhollan on February 28, 2019 8:9_

@fabiocav @paulbatum now that v2 is GA do we still see SDK updates as a customer support cost? Trying to assess if this label is still valid to help with prioritization

**Comment by paulbatum** [comment]
@ColbyTresness good question. I do not feel like I've seen a significant number of these in the last 6 months or so.

**Comment by ColbyTresness** [comment]
This comment was @jeffhollan . Agreed that this seems like low priority.

**Comment by ColbyTresness** [comment]
With Dev 16 there won't be a separate extension, so I'm closing this.
