### ISSUE TITLE
java mvn azure-functions:deploy not populating connectionsetting

### ISSUE THREAD

**Issue by panneerpst** [Azure/Azure-Functions#1159]
While deploying to azure cloud using mvn azure-functions:deploy, the Functions are getting created in the cloud however when i checked the connection parameter in azure portal the <connectionStringSetting> is not getting populated. The function.json file is referring to <connectionStringSetting>.As per my understanding this has to be actual connection string in the function.json. please correct me if i am missing something.

**Comment by v-anvari** [comment]
Hi @panneerpst, the Connection string is stored in local settings file [https://docs.microsoft.com/en-us/azure/azure-functions/security-concepts#application-settings](https://docs.microsoft.com/en-us/azure/azure-functions/security-concepts#application-settings)
