### ISSUE TITLE
Document binding limitations for each supported binding

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#116]
Bindings generally expose a subset of the functionality compared with using the underlying classes directly. For instance, you can only set blob properties if you bind to CloudBlockBlob. And, if you need something more advanced than what the binding supports, you need to forego input/output bindings and just directly use various SDKs.

For each binding, we should be clear about what is supported automatically through the binding and what scenarios require manual use of Azure SDKs.

**Comment by SyntaxC4** [comment]
@lindydonna Can you split this into separate topics and provide more context so that these are more actionable by our writers?

**Comment by lindydonna** [comment]
I assigned this to myself, since it'll be more expedient for me to write the content.

**Comment by lindydonna** [comment]
Closing as we haven't had any customer requests for this after updating the bindings docs.
