### ISSUE TITLE
Process function app chaining without using orchestrator functions

### ISSUE THREAD

**Issue by Archa123** [Azure/Azure-Functions#1160]
Hi team,

I am trying to write a code; that calls to different functions within a function app. Though on search I got to know this could be available only through orchestrator functions. Can we introduce something where we could make an call to another functions without calling orchestrator function in between.

Regards,
Archa Vyas

**Comment by soninaren** [comment]
@Archa123 Durable functions is explicitly designed for this scenario. Here is some documentation function chaining via durable functions. https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-concepts#chaining. 

There is no direct way of calling functions within the function other than durable functions. You can artificially create an execution order by passing the order in the payload and checking against an external data source to ensure correct execution order. However i would recommend using durable functions for this scenario.
