### ISSUE TITLE
Console.WriteLine() doesn't seems to work for Azure Functions in Function App

### ISSUE THREAD

**Issue by Archa123** [Azure/Azure-Functions#1161]
Hi Azure Team,

I have just started working on Azure Function App; and while working got to know that for azure function app Console.WriteLine() doesn't seems to work on console tab after  running the function app. 

Here is an example. 
Created an Simple Orchestrator Function. 
In Orchestrator Function added a code line:

Console.WriteLine()

On compiling and running a function. It doesn't give any error. But under console tab on azure portal it doesn't show any Console text. 

Can you please help me to analyze more on this.

Regards,
Archa Vyas

**Comment by soninaren** [comment]
@Archa123 Console in the Azure portal is not hooked into stdout. It is a console for log emitted by the function in the context. You can do that by adding `ILogger` parameter and then calling log.Info();

Here is a sample.
https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/IoTHubTrigger-CSharp/run.csx
