### ISSUE TITLE
Need docs for CI/CD patterns for Azure Functions on Azure DevOps

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/Azure-Functions#1164]
Customer and technical support staff were unable to identify any documentation or implementations of patterns for CI/CD of Azure Functions, particularly for AzDO integration. 

**Problem Statement**: Currently, there does not appear to be documentation for Azure Functions CI/CD patterns. The partner needs this information for connecting to services such as AzDO.

**Desired Experience**: Documentation and samples of Azure Functions CI/CD patterns should be available for our first party DevOps service

<details><summary>Internal Tracking</summary>#196713</details>

**Comment by brandonh-msft** [comment]
Additionally, discoverability is lacking on how to do CI/CD w/ Jenkins (must expand 'deploy' in the Azure Functions docs area and look in that list) and could be better.

**Comment by giorgited** [comment]
https://docs.microsoft.com/en-us/labs/devops/deployazurefunctionswithvsts/ this was helpful but could use some refreshing

**Comment by ColbyTresness** [comment]
@ahmedelnably

**Comment by ahmedelnably** [comment]
The docs are currently available here
https://aka.ms/functions-azure-devops

Closing the issue as resolved
