### ISSUE TITLE
AI logs missing from the monitor blade 

### ISSUE THREAD

**Issue by asavaritayal** [Azure/Azure-Functions#1167]
[Case REG:118121825001111]

Issue: 
"some Application Insights related to the function execution are missing for today for some functions in Function App"

Mitigation: 
"I understand you are able too see the correct logs under the traces table in App Insights and the function is running correctly at the moment.

Our suggestion is to use this table for accurate logging rather than requests or the monitor portal which might be skipping some logs."

**Comment by kulkarnisonia16** [comment]
We have a detector addressing this.
