### ISSUE TITLE
JS: Capturing all uncaught exceptions and things like 500s etc?

### ISSUE THREAD

**Issue by iyerusad** [Azure/Azure-Functions#1176]
I am fairly new to working in JavaScript, so apologies in advance if there is an obvious answer.

## Problem:

I don't know when my Azure Functions fail in production. I would like to get a grip on these errors as often they are my own doing and require a code change.

I have attempted:
- Looking into Azure Application insights: It seems it requires rule creation, setting up notifications; seems promising but in order to integrate it need to capture exceptions, whereas I hoping to do a catchall for uncaught exceptions
  - **EDIT (2019-06-20):** Azure Application Insights sounds like its literally covers my problem situation. See [comment](https://github.com/Azure/Azure-Functions/issues/1176#issuecomment-504275862)
- Setting `process.on('uncaughtException', function....`, but that doesn't seem to work
- Adding sentry.io to top of function `index.js` file and within module.exports (and variations thereof):
```
const Sentry = require('@sentry/node');
Sentry.init({ dsn: 'https://secretcode@sentry.io/myproject' });
```
- Considered try catching everything, but it seems excessive and messy approach.

## Goal:

Using Javascript/node within Azure Functions (v2):

- Capture/redirect uncaught exceptions in Azure Functions
- Capture/redirect host issues (e.g. 500s)
- Catch errors during development (prevention is better than alert)

For sake of simplicity, example simply redirecting to console.log would be helpful, but my goal is to hook up to a separate error consolidation service (e.g. sentry.io).

Ultimately: I want to know about an error so I can code commit a fix.

## Background
As a backend for a web app, I have written about a dozen or so Azure Functions, running on the node runtime, version 2.0. Most of my code executes gracefully, but occasionally in my inexperience I run into uncaught exceptions. My Azure function deployment is hooked up to a Azure Application Insights instance, however out of box there does not appear to be any alerting enabled and appears to require configuration of rules. Currently, whenever my Azure Functions code runs into an issue, I have no awareness of it (unless debugging locally).

For my frontend (running on top of VueJS), I have been able to add Sentry.io integration that captures uncaught (and caught, when desired) exceptions and logs them with a bunch of details that could be relevant in troubleshooting or catching the exception. Primarily, I have this enabled on production instance to know if and when a user encounters an exception I have not thought of. This is extremely useful, particularly when deploying regularly throughout a day as a novice - some (errr... more than care to admit) bugs make it through. Thanks to catching of errors in the FE, I can rest easy shipping code to production as I know I will get notification if bug crops up.

**Comment by iyerusad** [comment]
For server side exception catching, the following is what I've come up with thus far, figured worth documenting here for reuse in documentation:

1. Create action group:
```
az monitor action-group create \
  --resource-group "MyGroup" \
  --name "MyAppSupportTeam"
```

2. Add an action to alert via email someone:
```
az monitor action-group update \
  -g "MyGroup" --name "MyAppSupportTeam" \
  --add-action email "1stSupportPerson" "poorSOB@myemaildomain.com"
```

3. Create an alert rule, for all exceptions:
```
AppInsightsID=$(az resource show -g MyGroup -n "ApplicationInsightsInstance" --resource-type "Microsoft.Insights/components" --query "id" --output tsv)

az monitor metrics alert create \
  -g "MyGroup" \
  -n "Alert on Exceptions" \
  --description "All exceptions" \
  --scopes $AppInsightsID --action "MyAppSupportTeam" \
  --condition "total exceptions/count >= 1"
```

The above should (in theory) alert by email whenever a server side exception is caught. This would presumably be devoid of any request\trigger details, but awareness is step one.

That leaves capturing exceptions within the node Azure Function - not sure how best to go about it. Any thoughts?

**Comment by iyerusad** [comment]
In addition to rough exception catching/alert (see above), the following items continue to improve my experience when writing and working with Azure functions. These are probably very basic to experienced developers, I welcome better ideas on how to capture and address exceptions/etc within Azure Functions.

Linter (eslint):
---
For those unfamiliar, [stackoverflow: What is Linting](https://stackoverflow.com/questions/8503559/what-is-linting). This has helped me identify code that technically "works", but has some issues: potentially ambiguous behavior or used/incorrectly scoped variables (e.g. variable declared but never read). It generally won't catch logic/runtime errors - presumably thats where test cases could help...

1. In VScode, install [ESlint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).
2. Add ESlint npm: In your azure functions project, run in terminal `npm install --save-dev eslint`
3. Init ESlint for repo: In your azure functions project, run in terminal run `./node_modules/.bin/eslint --init`. Without this (or a ` .eslintrc.json` file), ESlint doesn't do anything.

This results in .eslintrc.json file that the VScode extension reads and then alerts you in the Problems section of issues:
_.eslintrc.json_ example
```
{
    "env": {
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
    }
}
```
![image](https://user-images.githubusercontent.com/25647368/59071277-33a02900-887b-11e9-9797-2ea7d08df811.png)

Improvements:
- Would like to see this (or similar) included by default with Azure Functions (at least in templates). 
- Would like to see an improved `.eslintrc.json`, what is deemed preferable for Azure Functions (which style guide, etc).

context.log
---
Basically, same idea as `console.log` but `context.log` info makes it back into Azure Portal. Many would probably see this as not good/anti-practice. I would like a better alternative.

Alerts on exceptions help when me know when something failed. Unfortunately, the alert email is extremely broad, and even once I drilled into Application insights and identified the failing function and then the failed run of that function, I tend to end up with error messages that aren't much use (often from libraries, rather than line errors of my code). context.log helps me provide context around how along the process is before failed, and depending how verbose I got, explicitly tell me what failed.

I now tend to use context.log: 
- before making calls to remote APIs `context.log("Calling remote API: blah.com/api/yay")`
- writing out some values that provide context to help debug a failure (user ID)
- Capturing failed remote api `context.log.warn(`Failed calling "blah.com/api/yay": ${error}`)`

[context.log](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#contextlog-method)
![image](https://user-images.githubusercontent.com/25647368/59071519-35b6b780-887c-11e9-803e-8d8f069f48fd.png)

**Comment by iyerusad** [comment]
It sounds like Azure Application Insights package (npm/C#) is literally built for this. From the [Azure Application Insights npm package page](https://www.npmjs.com/package/applicationinsights), _**emphasis** mine_:

> Azure Application Insights **monitors your backend services and components after you deploy them to help you discover and rapidly diagnose performance and other issues.** Add this SDK to your Node.js services to include deep info about Node.js processes and their external dependencies such as database and cache services. You can use this SDK for your Node.js services hosted anywhere: your datacenter, Azure VMs and Web Apps, and even other public clouds.
> 
> This library tracks the following out-of-the-box:
> - Incoming and outgoing HTTP requests
> - Important system metrics such as CPU usage
> - **Unhandled exceptions**
> - Events from many popular third-party libraries (see Automatic third-party instrumentation)
> - You can **manually track more aspects of your app and system using the API described in the Track custom telemetry section.**

I haven't been using Application Insights instrumentation _from **within**_ my Azure Functions at this point, but I have lightly used them _outside_ my functions. I will begin exploring how to implement these from within. In hindsight, I think the above quote would of been helpful when originally posting this issue.

Updating original comment to reflect this.

**Comment by ColbyTresness** [comment]
@mhoeger

**Comment by iyerusad** [comment]
So I've added Application Insights to each of my functions and its beginning to capture info. It was surprisingly simple enough, and it now captures uncaught exceptions similar to how I would see them as if I were running in local dev environment.

I must say though, Azure Application Insights UI is definitely something - I kinda wish they spun it out to a product outside of Azure Portal and built an interface that wasn't so... Azure Portal-ly.

Capture Exceptions within Function (Application Insights): 
---
1. Add Azure Application Insights npm package to your project: `npm install --save applicationinsights`
2. If not already set, add `APPINSIGHTS_INSTRUMENTATIONKEY` to your environment (`local.settings.json` in local dev, Application Settings in hosted Azure)
3. Use AppInsights package within each of your Azure Functions (at the very top):
```
const appInsights = require("applicationinsights");
if (process.env.APPINSIGHTS_INSTRUMENTATIONKEY) {appInsights.setup(process.env.APPINSIGHTS_INSTRUMENTATIONKEY).start()}
```

This will collect "HTTP requests, popular third-party library events, unhandled exceptions, and system metrics" from within Azure Function (default config - can be modified).

---
Exception caught:
![image](https://user-images.githubusercontent.com/25647368/59959774-e62adb00-947a-11e9-83b9-eee2646a8b48.png)
Performance metrics:
![image](https://user-images.githubusercontent.com/25647368/59959863-58e88600-947c-11e9-9d43-fe233cd0a414.png)

**Comment by iyerusad** [comment]
The combination of the above posts address my original goals, to recap:
- **Capture unhandled exceptions/metrics:** [Use Application Insights _within_ azure function](https://github.com/Azure/Azure-Functions/issues/1176#issuecomment-504633513)
- **Capture server/host issues:** [Set up alert rules](https://github.com/Azure/Azure-Functions/issues/1176#issuecomment-499701223), catching exceptions (or a bajillion other items)
- **Notifications on errors:** [Set up alert groups](https://github.com/Azure/Azure-Functions/issues/1176#issuecomment-499701223)
- **Catch errors during local development:** [Use a linter](https://github.com/Azure/Azure-Functions/issues/1176#issuecomment-499701223)

I'll close this request out.

@mhoeger, by all means give me a heads up if this was a super jank approach to development - you understand this stuff loads better than I do.  I also may have taken a rough and tumble route on programming basics....
