### ISSUE TITLE
Provide a Reference to each bindings Errors pages

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#118]
For the Functions Binding topic, it would be helpful to have an Error Codes section that would cross-link to the wrapped services error codes page. 

Something along the lines of:

## Bindings Error Codes

Azure Function provides a wrapper to comment services within Azure. Often times while developing your Functions, you may have errors bubble up from the underlying Azure Services SDKs. The table below is a reference off to the Error Code documentation for the services that we wrap. 

| Binding | Service | Reference |
|---|---|---|
| Blob | Azure Storage | [Blob Error Codes](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/blob-service-error-codes)
| Table | Azure Storage | [Table Error Codes](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/table-service-error-codes)
| Queue | Azure Storage | [Queue Error Codes](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/table-service-error-codes)
| Blob, Table, Queue | Azure Storage | [Storage Error Codes](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/common-rest-api-error-codes)
| Blob, Table, Queue | Azure Storage | [Troubleshooting](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/troubleshooting-api-operations)

**Comment by SyntaxC4** [comment]
Service Bus Messaging: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions

**Comment by SyntaxC4** [comment]
## DocumentDB

* [DocumentDB Error Codes](https://docs.microsoft.com/en-us/rest/api/documentdb/http-status-codes-for-documentdb)

**Comment by SyntaxC4** [comment]
## Notification Hubs

* [Operations Guide](https://docs.microsoft.com/en-us/rest/api/notificationhubs/)

**Comment by SyntaxC4** [comment]
Available: https://github.com/Microsoft/azure-docs-pr/pull/3812

**Comment by lindydonna** [comment]
@SyntaxC4 Is this done?  It looks like the PR was merged.
