### ISSUE TITLE
Long running activity

### ISSUE THREAD

**Issue by Ionesta** [Azure/Azure-Functions#1181]
I am trying to execute a sequence of activities through the orchestrator and I got timeout after 5 minutes for some activities. The activities have been splitt to atomic activities but still have some that last more than 5 minutes. Can anyone suggest a way of allowing an activity last more than 5 minutes?

**Comment by v-anvari** [comment]
Hi @Ionesta, Apologies for the delayed response, We were going through the older issue, when we found this. Were you able to find a solution. If you still having this issue persisting, then let us know the repro steps for us to understand the error

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
