### ISSUE TITLE
Deploying Azure Function is a painful mess

### ISSUE THREAD

**Issue by cbailiss** [Azure/Azure-Functions#1188]
I created a AF in Visual Studio 2017 with v15.9.02046.0 of the tools.
It is a v2 function (I selected v2 in Visual Studio when initially creating the project).  
In the host.json file it is set as v2.
The Visual Studio tooling deployed it as a v1 function (see attached screenshot) and the deployed function does not work.
There is an error displayed:

> Error:
> Function (BasicFunctionalityCheck) Error: The function type name 'TrainData.Management.Service.BasicFunctionalityCheck' is invalid.
> Session Id: 074ebc7721ca44d4b918f6263b1d01d6
> Timestamp: 2019-04-07T11:45:09.534Z

![ss1](https://user-images.githubusercontent.com/11745789/55683063-58d3f200-5933-11e9-8bc0-eef3ea9e9773.png)

Further:

I can find no examples of the current version of the ARM template described at:
https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-02-01/sites/functions
The above page is bare-bones only.

The Azure Portal generates a template with api version 2016-03-01, i.e. more than three years old (and pre v2 of Azure Functions), which hardly seems a sensible choice for a new solution.

The current Quick Start template (link below) is even older, using api version 2015-08-01. 
https://github.com/Azure/azure-quickstart-templates/blob/master/101-function-app-create-dynamic/azuredeploy.json

Please, produce some updated examples and fix the tooling.

**Comment by v-anvari** [comment]
Closing this issue as these issues have been fixed with the latest versions. 

ARM latest template - https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2020-12-01/sites/functions?tabs=json
