### ISSUE TITLE
[Premium] Storage Queue trigger service endpoint

### ISSUE THREAD

**Issue by RenePingen** [Azure/Azure-Functions#1198]
**Describe the bug**
I am unable to use VNET integration in combination with a service endpoint and storage queue trigger. From what i understand, queue triggers are based on polling, so i hoped it would work, but unfortunately it does not. Error:
```
2019-04-17T14:47:14.603 [Error] Error indexing method 'Functions.QueueTrigger1'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Functions.QueueTrigger1' ---> System.InvalidOperationException : Storage account 'XXX' is not configured.
   at Microsoft.Azure.WebJobs.StorageAccountProvider.Get(String name) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\StorageAccountProvider.cs : 43
```
**To Reproduce**
1. Create a function with premium app service plan. Integrate it with a subnet in a vnet.
2. Setup a storage account and queue, and create a service endpoint in the same subnet as the function.
3. Create a function with a queue trigger on the created queue.

**Comment by alexkarcher-msft** [comment]
From [our networking overview](https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options#virtual-network-integration)

> You cannot configure triggers to use Service Endpoint secured resources using the new VNet Integration capability.

[See our FAQ for your current workaround to trigger from a service endpoint secured resource](https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-faq#how-can-i-trigger-a-function-from-a-resource-in-a-virtual-network)

> **How can I trigger a function from a resource in a virtual network?**
You can trigger a function from a resource in a virtual network only by deploying your function app to an App Service Environment. For details on using an App Service Environment, see [Create and use an internal load balancer with an App Service Environment.](https://docs.microsoft.com/en-us/azure/app-service/environment/create-ilb-ase)
