### ISSUE TITLE
Update Timer Trigger to mention TimeZones

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#12]
See this GitHub thread for more background info: https://github.com/projectkudu/AzureFunctionsPortal/issues/420#issuecomment-228893075

**Comment by wesmc7777** [comment]
https://github.com/Microsoft/azure-docs-pr/pull/1294

**Comment by wesmc7777** [comment]
The WEBSITE_TIME_ZONE app setting may be breaking calculations shown for function duration times on the Monitor tab
