### ISSUE TITLE
Support Zip deploy for Linux Consumption Function Apps

### ISSUE THREAD

**Issue by balag0** [Azure/Azure-Functions#1200]
Tracking issue to add support for server side build.

**Comment by anirudhgarg** [comment]
AB#4640333

**Comment by anirudhgarg** [comment]
@Hazhzeng please close this when we release remote build

**Comment by avishnyakov** [comment]
@anirudhgarg @Hazhzeng @balag0 the issue is closed. Does it mean that zip deploy for Linux Consumption Function Apps is now available?

**Comment by Hazhzeng** [comment]
@avishnyakov We are rolling out the new version of KuduLite image, it is expected to complete by the end of the day, 6:00 PM PDT.

By default the <scm>/api/zipdeploy endpoint performs a [remote build](https://docs.microsoft.com/bs-latn-ba/azure/azure-functions/functions-deployment-technologies#remote-build) for your function app, if you want to disable this behavior, you can manually set **ENABLE_ORYX_BUILD = false** and **SCM_DO_BUILD_DURING_DEPLOYMENT = false** in your app settings.

After making a post request to the <scm>/api/zipdeploy endpoint, you can view the deployment progress in <scm>/api/deployments endpoint,

**Comment by Dhruv-1982** [comment]
I am getting The remote server returned an error: (404) Not Found whenever i am calling zipdeploy uri from powershell. even the https://{webappname}.scm.azurewebsites.net/api/zipdeploy is returning No route registered for '/api/zipdeploy' error.

**Comment by balag0** [comment]
@Dhruv-1982 Please open a new issue and include the sitename using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
Also please include also what client are you using

**Comment by Dhruv-1982** [comment]
Created new issue Azure Function App on Linux consumption plan zipdeploy error #6857

**Comment by swettstein** [comment]
@Dhruv-1982 did you open an issue? i am experiencing the same thing and can't find your issue

**Comment by mnriem** [comment]
@see https://github.com/Azure/azure-functions-host/issues/6857
