### ISSUE TITLE
line breaks in function.json are removed in the Portal

### ISSUE THREAD

**Issue by yokawasa** [Azure/Azure-Functions#1204]
Seeing function.json in the portal, it looks line breaks in function.json are removed like this:

<img width="1076" alt="Screen Shot 2019-04-24 at 22 16 30" src="https://user-images.githubusercontent.com/82332/56662705-8fee2580-66df-11e9-813b-ee977ec4a671.png">

I developed functions locally and published them to Azure Function. Seeing function.json from local editor, line breaks are included like this:
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "myitem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "itemsqueue",
      "connection": "MyStorageConnectionString"
    },
    {
      "name": "inputblob",
      "type": "blob",
      "path": "inputitems/{queueTrigger}",
      "connection": "MyStorageConnectionString",
      "direction": "in"
    },
    {
      "name": "outputblob",
      "type": "blob",
      "direction": "out",
      "connection": "MyStorageConnectionString",
      "path": "outputitems/{queueTrigger}"
    }
  ]
}
```

My environmental info is here:
- Azure Functions 2.0
-runtime: Python
- Running functions from a package file

**Comment by v-anvari** [comment]
Closing this issue as it has been resolved
