### ISSUE TITLE
[Visual Studio] What is the function of the "data" and "secrets" folders?

### ISSUE THREAD

**Issue by michaeldaw** [Azure/Azure-Functions#121]
When using a Functions project in Visual Studio, the project automatically adds a "data" and "secrets" folder. They don't seem to do anything. Can future versions of the tooling leave this out?

**Comment by lindydonna** [comment]
This is a duplicate of these bugs: https://github.com/Azure/azure-webjobs-sdk-script/issues/945 and https://github.com/Azure/azure-webjobs-sdk-script/issues/946

We haven't yet done a release with the fix, but you'll see the fix in version 0.10 of the CLI.

**Comment by michaeldaw** [comment]
Thanks for clarifying.
