### ISSUE TITLE
Benefits/disadvantages of multiple/single function per function app

### ISSUE THREAD

**Issue by vidarw** [Azure/Azure-Functions#1224]
Need some input on the benefits and eventually disadvantages of using a single function per function app in a enviroment or vise versa.

We have three functions consuming various service bus topics within he same servicebus namespace. Thematically it makes sense to deploy them to a single Function App, but unsure about the performance impact. I'm also wondering how his integrates with CI software which encourages one build/deployment process per repository.

This is currently the only documentation I can find which touches the topic:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#dont-mix-test-and-production-code-in-the-same-function-app

**Comment by ahmelsayed** [comment]
Functions in 1 Function App scale together and share the same limits and compute (they run in the same process). Functions in separate function apps are obviously separate. Each function app will scale independently of the other. It depends on your scenario I think. if you keep your functions in separate repos, it may be simpler for you to deploy them to separate function apps. Though usually people have lost of shared code between the functions or shared data structures. 

_Tagging few more people who may know if there is a best practice we recommend or if there is a doc that covers this, I couldn't find one_ 
/cc @jeffhollan @mattchenderson @dariagrigoriu

**Comment by jeffhollan** [comment]
Should probably be more explicit than it is right now, but yes @ahmelsayed answer is great.  Generally we summarize it with:

- Function app is the unit of deployment and the unit of scale
- All functions in the same function app will share resources per instance as it scales

So with that in mind, if you want the flexibiliy to rev Function A without having to redeploy Function B along with it, they should be in different apps.  If both Function A and Function B are pretty resource intensive, you may be better off splitting them into two apps where they can scale independently and not share resources.  I often find multiple functions in a function app is a convenience that works often, but there is no downside to splitting them up into different apps.  Just a bit more "resources" and deployments to manage.

**Comment by jeffhollan** [comment]
Sorry meant to link where in the docs this is *partially* covered

https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#runtime-scaling

**Comment by jeffhollan** [comment]
Closing as I believe we've answered this but did also bump up the doc work item to make sure this is called out better in docs AB#1093694
