### ISSUE TITLE
Host.json ignored with FunctionsStartup

### ISSUE THREAD

**Issue by lukasvosyka** [Azure/Azure-Functions#1227]
Hi,

as I posted on the Azure functions host team, but nobody seems to be available, I thought I will post it here, since I think this might be important to fix?

It seems that host.json values for "extensions" are ignored when using the new DI functionality with FunctionsStartup.

[For details see the original post here](https://github.com/Azure/azure-functions-host/issues/4480)

Should I move the issue over here?

Best,
Lukas

**Comment by lukasvosyka** [comment]
Reported here as well https://github.com/Azure/azure-functions-dotnet-extensions/issues/13

**Comment by lukasvosyka** [comment]
I close it since my issue seems resolved.

**Comment by radsolution** [comment]
I am having the same issue.
I have a Startup class which inherits FunctionsStartup and it ignores everything in host.json (except the version number).
I tried adding .AddJsonFile("host.json", optional: true, reloadOnChange: true) to the overridden Configure() method, but it seems to be ignored there too.
Please advise how to fix this this urgently.
