### ISSUE TITLE
Azure Functions V2 DotNetCore ServiceBus claims ServiceBusConnectionString is empty

### ISSUE THREAD

**Issue by justinkneff** [Azure/Azure-Functions#1230]
When creating a DotNetCore or DotNetStandard application it throws a runtime exception when creating a ServiceBus or ServiceBusTrigger attribute. The console reports the following

> A host error has occurred
> Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobsServiceBus' is missing or empty.

I get a runtime exception immediately after that posts in the Console in JobHost.cs that "The host has not yet started."

> at Microsoft.Azure.WebJobs.JobHost.StopAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 121 at Microsoft.Azure.WebJobs.Hosting.JobHostService.StopAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\JobHostService.cs:line 32 at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)

### Recreation Steps

1. Using Visual Studio 2017 go to File -> New -> Project -> Azure Functions -> Ok
2. Choose Azure Functions v2 (.NET Core)
3. Choose Empty
4. Right click Project -> Add ->New Azure Function
5. Select Service Bus Queue Trigger
6. Go to local.settings.json and add a ServiceBusConnectionString
7. Start Debugging and you'll get the exception above.

``` json
 {
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "AzureWebJobsServiceBus": "Endpoint=sb://[my_name].servicebus.windows.net/;SharedAccessKeyName=LocalManage;SharedAccessKey=[my_key]"
  }
}
```
Visual Studio 2017 Version 15.9.9
Azure Functions and Web Job Tools is 15.10.2046.0

 [Here is a related StackOverflow post](https://stackoverflow.com/questions/56295327/azure-function-converting-v1-to-v2-dotnetstandard-azurewebjobsservicebus-is-mi). Thank you for your help.

**Comment by justinkneff** [comment]
Also Installed Visual Studio 2019 Community Edition and still have the same problem.

**Comment by justinkneff** [comment]
I attempted following any suggestions in this follow issue report https://github.com/Azure/Azure-Functions/issues/931
I tried adding custom connection strings or non, I tried that appsettings.json, tried putting that item in host and local.settings json files.

**Comment by lanatmwan** [comment]
Not entirely sure if its the same issue but in VS 2019 there appears to be a bug in the wizard for creating service bus topic triggered function projects. It takes the connection string you provide and puts it in the ServiceBusTrigger attribute. When executed, the Connection value of the attribute is treated as a settings lookup. So if you change it to a key name from your settings file and add the setting it works.

`[ServiceBusTrigger("mytopic",` "mysubscription", Connection = "ConnectionString")]

local.settings.json:
```
{
    "IsEncrypted": false,
  "Values": {
    "ConnectionString": <my service bus connection string>,
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

**Comment by justinkneff** [comment]
Unfortunately my Azure Functions ServiceBus seems not to take 3 arguments into its constructor.
![image](https://user-images.githubusercontent.com/2012354/59635311-84830d80-9116-11e9-9df3-7d74e127d155.png)
I have Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.3
I also tried Microsoft.Azure.WebJobs.ServiceBus 2.2.0

**Comment by lanatmwan** [comment]
You have to use a named parameter:
[ServiceBusTrigger("mytopic",` "mysubscription", Connection = "ConnectionStringSettingName")]

**Comment by justinkneff** [comment]
Thanks I can't believe I missed that part of the parameter, that's why a second pair of eyes is always helpful, Thanks! Hopefully documentation is updated to note the requirement of the connection string as well.
