### ISSUE TITLE
SB Topic does not get created for Node.js-based Azure Function trigger bindings

### ISSUE THREAD

**Issue by billydjr-at-bentey** [Azure/Azure-Functions#1237]
We have been using Azure Functions, written in C#, for several years. Amongst these are functions triggered by SB Topic messages. Our experience with these has been that the target SB Topic is automatically created (on a previously existing service bus, of course), if necessary, when the function app is deployed. Recently, we have started using Node.js-based Azure Functions. When defining trigger bindings on a function for a SB Topic, we have noticed the topic does not get automatically created on the service bus as it did for our C#/.NET-based Azure Functions. Does this represent a deliberate change in deployment policy for Azure Functions? Or should I report this as a bug?

**Comment by ConnorMcMahon** [comment]
This looks very similar to [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/30888), though that is tied to a change from Functions V1 to Functions V2. Is your Node app V2 and your C# apps V1? If so, that could have to do with it.

**Comment by billydjr-at-bentey** [comment]
> This looks very similar to [_this issue_], though that is tied to a change from Functions V1 to Functions V2. Is your Node app V2 and your C# apps V1? If so, that could have to do with it.

Yup. You nailed it. The .NET funcApp was V1. The node.js funcApp is v2. Thanks.
