### ISSUE TITLE
[Premium] Inconsistant latency from Azure Storage Table

### ISSUE THREAD

**Issue by waltersjack** [Azure/Azure-Functions#1238]
**Describe the bug**
We have multiple read/write functions that get/set data to an azure storage table.

Functions App Service Plan: EP1
- C# netcoreapp2.2
- functions version 2
- deployed to run from package
- pre warm instance set to 1
- minimum instances for this test was set to 1
Azure Storage Table: Standard LRS Storage V2 (one for the function and one for the data)
**All working in the same region.

We have reduced the latency for all calls to less than 50ms except for initial call.  This occurs within a couple minutes of idle.  It does not appears to have to do with the function "cold start", but rather the connection to the table storage.

The majority of read connections to the storage are less that 10 ms, but if left idle for a couple minutes it grows to almost a second.  Externally (via postman) this amounts to about 50 ms on average with the initial call at 1 to 1.5 seconds.  This is with a simple timer function that runs every 5 minutes and just logs that it ran.  Without the timer function the initial call has taken over 4 seconds.

Resigned to having to use a timer function to help reduce the initial latency, we began to look at the remaining latency.  We found that the majority seemed to have to do with the storage reporting over 700ms at times per initial request.

This call must be fast so anything that slows it down will need to be accounted for.  I have search with no luck as to why this may be happening.  Any help is appreciated.

**To Reproduce**
1. add a new function app service as described above
2. set up a http trigger function to read from the data table storage
- populate with a few rows to test with - keep it simple so the calls can be quick
3. set up a timer trigger function to run every 4 minutes
- within this function set up 2 async calls to the previous read function (no need to do anything with the results)
4. deploy and watch the logs
(I know I am over simplifying a bit here, please let me know if you want more details)

In the logs you will see that each time the timer function is triggered, the first call to the table will take over 100 hundred ms while the second will be completed at about 10 ms. (results will vary depending on how your function is set up)

Example Results:
![image](https://user-images.githubusercontent.com/3019097/58922901-e5abe980-86f1-11e9-8930-ed0281d5225e.png)

I am not completely sure if it is the storage account or the function causing this slowdown.  Running the described setup above from my local, I was able to remove the latency completely, but had to have the timer function (with calls to the read function) running every 3 to 4 minutes.  Deploying to Azure I was not as fortunate even with a 1 minute timer function.

**Expected behavior**
I expect that the initial call would return more consistently in comparison to subsequent calls.

**Screenshots**
see above

**Additional context**

**Comment by marxxxx** [comment]
Azure Storage is running on a shared environment. If you need latency guarantees you will have to go for Cosmos DB.

**Comment by sawatsky** [comment]
@marxxxx Just so I understand... you're saying that Azure Storages run in a shared pool that anyone can pull from. When we are attempting to read/write to a Storage, it takes a bit of time to set up the connection to that storage (hence the initial latency). After the action, once the storage has been idle for long enough, the storage is released back into the shared pool. And there's nothing we can do about that, to maintain that connect to an Azure Storage. Yes?

**Comment by ConnorMcMahon** [comment]
@sawatsky, are you performing these reads using one of the Azure Storage bindings, or did you write code within your function that reads from Storage. Also, if you wouldn't mind sharing your app name ([privately if you prefer](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), that could help with our investigation.

**Comment by waltersjack** [comment]
Switching to Cosmos DB Table removed latency.  Thanks!
