### ISSUE TITLE
Use of sample.dat?

### ISSUE THREAD

**Issue by iyerusad** [Azure/Azure-Functions#1241]
Azure Functions [sample templates](https://github.com/Azure/azure-functions-templates) include `sample.dat` file with following explanation:

> - **Sample.dat:** Sample.dat contains sample input data for each template. The Run text box in the portal will be populated by the contents of the sample.dat file.

When I navigate to an azure function within Azure Portal, I see sidebar for test which expands to show fields for request body - I am _assuming_ this is where `sample.dat` would be populated in:
![image](https://user-images.githubusercontent.com/25647368/59138504-be038e00-894a-11e9-82c1-3ec9d8860286.png)

**Questions:**
- Is `sample.dat` primarily for Azure Portal web interface usage?
- Does `sample.dat` populate the field I mention above? (want to confirm assumption)
- Is there a use case for `sample.dat` within local development? 
  - I run something like Postman to craft requests to test locally, wondering if there is a way to integrate `sample.dat` into the process (one benefit would be `sample.dat` is in repo, my Postman collection is not currently, although [newman](https://www.npmjs.com/package/newman) appears to offer capability for this)

**Comment by kashimiz** [comment]
Hi @iyerusad,

* You're correct; `sample.dat` is primarily for Azure Portal web interface usage.
* Also correct; `sample.dat` populates the request body.
* If you're talking about [using data files to test your functions using Postman/`newman`](https://learning.getpostman.com/docs/postman/collection_runs/working_with_data_files/), you can certainly do that, but there's no logic within the Functions host or Core Tools that recognizes and uses `sample.dat` files, nor logic that would allow you to upload a `sample.dat` file that the Functions portal would recognize and use to populate the request body in the `Test` side tab.

**Comment by iyerusad** [comment]
Understood. Thank you @kashimiz . I was thinking there might have been some kind of pre-built extended use case for `sample.dat`, particularly within a local dev environment. Ill close this out as this appears to document the full extent of `sample.dat` usage (as of time of posting).

**Comment by FaresKi** [comment]
Hi! Sorry to reopen this topic but should `sample.dat` be committed? Thanks!
