### ISSUE TITLE
SDK.Function dependency on Web Jobs.

### ISSUE THREAD

**Issue by klogan12** [Azure/Azure-Functions#1247]
I have Microsoft.NET.Sdk.Functions 1 .0.28 and when i installed Microsoft.Azure.WebJobs -Version 3.0.0. Now there is a conflict between both. How to resolve this? 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'ExecutionContext' exists in both 'Microsoft.Azure.WebJobs.Extensions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	xxx	C:\Users\kloganathan\source\repos\xxx\TurinFunctionApps\Company.cs	17	Active

**Comment by kashimiz** [comment]
Could you explain how and why you installed Microsoft.Azure.WebJobs v3.0.0? Do you mean you added the Microsoft.Azure.WebJobs NuGet package to your function project?

**Comment by klogan12** [comment]
Graph binding installation mandated 3.0.0

**Comment by klogan12** [comment]
@kashimiz  This is the exact package name.
Microsoft.Azure.WebJobs.Extensions.MicrosoftGraph

**Comment by klogan12** [comment]
@kashimiz  Do u have any work around for this?

**Comment by fabiocav** [comment]
Do you have an explicit reference to `Microsoft.Azure.WebJobs.Extensions`? This is a legacy package and no longer used in Azure Functions 2.0 (and WebJobs 3.0) the Graph binding targets those newer stacks.

**Comment by klogan12** [comment]
@fabiocav  I have moved from Azure function runtime 1 to 2 and from dot net to core.
Not sure if that fixed the issue. But now things are good.
