### ISSUE TITLE
Occasional 'The decryption operation failed, see inner exception. ' with timer based function running every hour

### ISSUE THREAD

**Issue by lucabol** [Azure/Azure-Functions#125]
I am not doing anything related to cryptography in my function, hence I think it's not my code failing. Log and full code below. It fails once every 4 or 5 invocations.

LOG
```
...obs.Script.Description.FunctionInvokerBase.<Invoke>d__29.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__22.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()

   --- End of inner exception stack trace ---
```
CODE

```csharp
#r "..\sharedBin\GuruLoader.dll"
#r "Microsoft.Azure.Documents.Client"
#load "..\shared\UpdateMessage.csx"

using System;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
using System.Threading.Tasks;

// Check that the date that we have in the database is the same as the last date of the filings on the SEC website, if not queue a request to update
public async static Task Run(TimerInfo myTimer, DocumentClient client, IAsyncCollector<UpdateData> messages, TraceWriter log) {
    log.Info($"C# Timer trigger function executed at: {DateTime.Now}");

    if (client == null) throw new ArgumentException("Error documentDB handle is null");
    if (messages == null) throw new ArgumentException("The update message queue is null");

    // Gets all collections in the DB
    var db = (await client.ReadDatabaseFeedAsync()).Single(d => d.Id == "guru-portfolios");
    var cols = (await client.ReadDocumentCollectionFeedAsync(db.CollectionsLink));

    // For each collection generates (colId, cik, quarterEndDateInDB)
    var colIdDates = cols
                    .Select(col => Tuple.Create(col.Id, col.DocumentsLink))
                    .SelectMany(tup => {
                        var docs = client.CreateDocumentQuery(tup.Item2).ToList();
                        //var idDates = docs.Select(d => Tuple.Create(tup.Item1, ((dynamic)d).id, ((dynamic)d).EndQuarterDate)).ToArray();
                        var idDates = docs.Select(d => { dynamic d1 = d; return Tuple.Create((string)tup.Item1, (string)d1.id, (DateTime)d1.EndQuarterDate); });
                        return idDates;
                    });

    // Generates asynchronously the dates for the last 13F stored on the SEC site
    var secEndTasks = colIdDates
                      .Select(tup => tup.Item2)
                      .Select(cik => GuruLoader.FetchLastQuarterDate(cik))
                      .ToArray();
    var secEndDates = await Task.WhenAll(secEndTasks);

    // If the date in the database is less then the date on the SEC site, then we need to update the portfolio in the database
    var mess = colIdDates
                   .Zip(secEndDates, (tup, secDate) => tup.Item3 < secDate ? new UpdateData { collection = tup.Item1, groups = null, cik = tup.Item2, remove = false } : null)
                   .Where(o => o != null);

    // We do that by adding messages to the queue
    foreach (var m in mess) {
        log.Info($"Updated {m.collection}:{m.groups}:{m.cik}");
        await messages.AddAsync(m);
    }
    
}
```

FUNCTION.JSON
```
{
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 0 */1 * * *"
    },
    {
      "type": "queue",
      "name": "messages",
      "queueName": "update-portfolio",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    },
    {
      "type": "documentDB",
      "name": "client",
      "databaseName": "guru-portfolios",
      "collectionName": "lucabol",
      "id": "",
      "connection": "AzureDocumentDB",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

**Comment by lindydonna** [comment]
Note that you can use three backticks to format code in markdown 

```like so```

**Comment by fabiocav** [comment]
@lucabol looking at the logs for this, looks like the failure occurs when trying to communicate with the SEC endpoint used in the function (the decryption error is due to a failure to read the SSL stream) as a result of calling FetchLastQuarterDate (which in turn calls FetchRssDataAsync, where the failure occurs)

Do those 4-5 invocations happen to be close together? Are you hitting some limits on their side?

**Comment by lucabol** [comment]
@fabiocav thx. How did you get the logs? so that I don't bother you next time.

Also, I don't think I'm hitting a limit on their side as I query them once an hour. More likely the site is temporarily down at those times. In any case, not your fault, so I'll close this.

**Comment by fabiocav** [comment]
I found that information inspecting system logs and would expect that to be available in storage as well, although (and I'm suspecting that is the case here), I believe we have some length limitations and the stack might have been truncated (the file logs would still contain all the details, though). @MikeStall can confirm if that is still an issue.

@lindydonna brought up a good point about the possibility that this could also be environment related (we don't have any evidence of that, but based on previous experience, it is a possibility), so it would be worth running this outside of App Service for validation if you continue to see this issue and we could further investigate if this is something that doesn't repro outside of the environment.

**Comment by lucabol** [comment]
I will run it from VS all night. Let's see if I see any error in the morning.

**Comment by lucabol** [comment]
@fabiocav @lindydonna I am afraid you were right. It is likely an App Service issue. It run fine all night long from my machine, but failed a few times running in App Service. Below the proof that it worked fine from my machine.

'
Job host started
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-12T22:00:00.0167753+01:00', Id=038565c9-5813-4bf5-a5ad-4e3a38406149)
Function started (Id=038565c9-5813-4bf5-a5ad-4e3a38406149)
C# Timer trigger function executed at: 1/12/2017 10:00:00 PM
Function completed (Success, Id=038565c9-5813-4bf5-a5ad-4e3a38406149)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=038565c9-5813-4bf5-a5ad-4e3a38406149)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-12T23:00:00.0307867+01:00', Id=38fd0a2f-7c64-400f-9275-6b135c31d472)
Function started (Id=38fd0a2f-7c64-400f-9275-6b135c31d472)
C# Timer trigger function executed at: 1/12/2017 11:00:00 PM
Function completed (Success, Id=38fd0a2f-7c64-400f-9275-6b135c31d472)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=38fd0a2f-7c64-400f-9275-6b135c31d472)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T00:00:00.0511145+01:00', Id=5fffbc05-4ec4-4063-a2ef-d91dc85ecb76)
Function started (Id=5fffbc05-4ec4-4063-a2ef-d91dc85ecb76)
C# Timer trigger function executed at: 1/13/2017 12:00:00 AM
Function completed (Success, Id=5fffbc05-4ec4-4063-a2ef-d91dc85ecb76)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=5fffbc05-4ec4-4063-a2ef-d91dc85ecb76)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T01:00:00.0347715+01:00', Id=1082c5ed-7dcc-4cec-b263-7c0f5a0362b0)
Function started (Id=1082c5ed-7dcc-4cec-b263-7c0f5a0362b0)
C# Timer trigger function executed at: 1/13/2017 1:00:00 AM
Function completed (Success, Id=1082c5ed-7dcc-4cec-b263-7c0f5a0362b0)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=1082c5ed-7dcc-4cec-b263-7c0f5a0362b0)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T02:00:00.0285382+01:00', Id=b79fd089-2669-4e37-80bc-c339684d8727)
Function started (Id=b79fd089-2669-4e37-80bc-c339684d8727)
C# Timer trigger function executed at: 1/13/2017 2:00:00 AM
Function completed (Success, Id=b79fd089-2669-4e37-80bc-c339684d8727)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=b79fd089-2669-4e37-80bc-c339684d8727)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T03:00:00.0659059+01:00', Id=c4d9d5d8-4be9-4501-9785-af4938b282cd)
Function started (Id=c4d9d5d8-4be9-4501-9785-af4938b282cd)
C# Timer trigger function executed at: 1/13/2017 3:00:00 AM
Function completed (Success, Id=c4d9d5d8-4be9-4501-9785-af4938b282cd)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=c4d9d5d8-4be9-4501-9785-af4938b282cd)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T04:00:00.0448579+01:00', Id=f8afcb62-b1b7-4656-a2a2-9715b60eb44f)
Function started (Id=f8afcb62-b1b7-4656-a2a2-9715b60eb44f)
C# Timer trigger function executed at: 1/13/2017 4:00:00 AM
Function completed (Success, Id=f8afcb62-b1b7-4656-a2a2-9715b60eb44f)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=f8afcb62-b1b7-4656-a2a2-9715b60eb44f)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T05:00:00.0362181+01:00', Id=69569235-8bb8-406d-87af-6142fb52d867)
Function started (Id=69569235-8bb8-406d-87af-6142fb52d867)
C# Timer trigger function executed at: 1/13/2017 5:00:00 AM
Function completed (Success, Id=69569235-8bb8-406d-87af-6142fb52d867)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=69569235-8bb8-406d-87af-6142fb52d867)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T06:00:00.0288775+01:00', Id=9d4e5815-1f8f-4d8a-9fcb-c7e94558d0ec)
Function started (Id=9d4e5815-1f8f-4d8a-9fcb-c7e94558d0ec)
C# Timer trigger function executed at: 1/13/2017 6:00:00 AM
Function completed (Success, Id=9d4e5815-1f8f-4d8a-9fcb-c7e94558d0ec)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=9d4e5815-1f8f-4d8a-9fcb-c7e94558d0ec)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T07:00:00.0361118+01:00', Id=c97ee603-2b98-49a3-a9de-d8431e272bd0)
Function started (Id=c97ee603-2b98-49a3-a9de-d8431e272bd0)
C# Timer trigger function executed at: 1/13/2017 7:00:00 AM
Function completed (Success, Id=c97ee603-2b98-49a3-a9de-d8431e272bd0)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=c97ee603-2b98-49a3-a9de-d8431e272bd0)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T08:00:00.0298640+01:00', Id=0f34ff05-5932-416e-81de-0714ef76e857)
Function started (Id=0f34ff05-5932-416e-81de-0714ef76e857)
C# Timer trigger function executed at: 1/13/2017 8:00:00 AM
Function completed (Success, Id=0f34ff05-5932-416e-81de-0714ef76e857)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=0f34ff05-5932-416e-81de-0714ef76e857)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T09:00:00.0344136+01:00', Id=d045fe2f-850a-4a57-b78d-70185465cc6e)
Function started (Id=d045fe2f-850a-4a57-b78d-70185465cc6e)
C# Timer trigger function executed at: 1/13/2017 9:00:00 AM
Function completed (Success, Id=d045fe2f-850a-4a57-b78d-70185465cc6e)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=d045fe2f-850a-4a57-b78d-70185465cc6e)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T10:00:00.0239567+01:00', Id=c7439f29-9ab4-4598-9707-d2aa7ba7e030)
Function started (Id=c7439f29-9ab4-4598-9707-d2aa7ba7e030)
C# Timer trigger function executed at: 1/13/2017 10:00:00 AM
Function completed (Success, Id=c7439f29-9ab4-4598-9707-d2aa7ba7e030)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=c7439f29-9ab4-4598-9707-d2aa7ba7e030)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T11:00:00.1100619+01:00', Id=dcf6dbca-caf0-4564-9352-986f72239d87)
Function started (Id=dcf6dbca-caf0-4564-9352-986f72239d87)
C# Timer trigger function executed at: 1/13/2017 11:00:00 AM
Function completed (Success, Id=dcf6dbca-caf0-4564-9352-986f72239d87)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=dcf6dbca-caf0-4564-9352-986f72239d87)
Executing 'Functions.CheckGurusUpToDate' (Reason='Timer fired at 2017-01-13T12:00:00.0898551+01:00', Id=a4dc1f37-fe63-4ccb-971b-7c1ffc07cb53)
Function started (Id=a4dc1f37-fe63-4ccb-971b-7c1ffc07cb53)
C# Timer trigger function executed at: 1/13/2017 12:00:00 PM
Function completed (Success, Id=a4dc1f37-fe63-4ccb-971b-7c1ffc07cb53)
Executed 'Functions.CheckGurusUpToDate' (Succeeded, Id=a4dc1f37-fe63-4ccb-971b-7c1ffc07cb53)
'

**Comment by lindydonna** [comment]
Closing due to lack of repro.
