### ISSUE TITLE
Typo and missing link in storage queue doc

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#126]
In this doc: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue

> connection must contain the name of an app setting that contains a storage connection string. In the Azure portal, the standard editor in the Integrate tab configures this app setting for you when you create a storage account or selects an existing one. To manually create this app setting, see [configure this app setting manually]().

The link at the end is empty and the word selects highlighted above should be ‘select’.

**Comment by christopheranderson** [comment]
Link that it's supposed to use: https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings

**Comment by ggailey777** [comment]
There are also customer-reported bugs in this topic, which I am fixing.

**Comment by ggailey777** [comment]
Updates are staged here: https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?branch=pr-en-us-4862
