### ISSUE TITLE
Access control on Azure functions

### ISSUE THREAD

**Issue by swagulkarni** [Azure/Azure-Functions#1263]
We have the following requirement in terms of restricted access to the Azure function.

1. Allow only set of users to access the Azure function through Azure portal.
2. Deny public access to the function via internet.

Any help and guidance on how to achieve the above would be helpful.

**Comment by alexkarcher-msft** [comment]
Both of these are already available.

Portal access can be controlled via RBAC: https://docs.microsoft.com/en-us/azure/role-based-access-control/overview
Access to the Function from the internet can be configured using inbound access restrictions. The component is shared between Functions and App Service: https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions
