### ISSUE TITLE
Environment variables are ignored/overriden by azure functions

### ISSUE THREAD

**Issue by liron-navon** [Azure/Azure-Functions#1269]
I'm running azure functions v2 with a container.

I'm using the environment variable "AzureWebJobsScriptRoot" in a container, I set it to "/home/site/wwwroot/functions" and it works well when I run the container locally, but when I deploy the container with the functions it becomes "/home/site/wwwroot" -

Dockerfile
```Dockerfile
FROM mcr.microsoft.com/azure-functions/node:2.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot/functions
WORKDIR /home/site/wwwroot
#...
```

steps to reproduce:
1. create functions app with container
2. move the functions to a subdirectory, ie: "functions-project/functions" and set the "AzureWebJobsScriptRoot" variable to point to it.
3. run locally - works
4. run in container anywhere - works
5. deploy container to functions app - the functions are not detected since the "AzureWebJobsScriptRoot" variable is overridden.

**Comment by ColbyTresness** [comment]
@ahmelsayed

**Comment by ahmelsayed** [comment]
can you try setting `WEBSITES_ENABLE_APP_SERVICE_STORAGE=false` in the app setting?

**Comment by liron-navon** [comment]
I'm closing it, but still disappointed from the way the azure functions CLI works, and how the azure guys rigged the docker images without documenting these things.

---

I found the culprit here:
 [https://github.com/Azure/azure-functions-docker/blob/2fe333f0850b0cf2e7ab78ca1d93ab8a32875968/host/2.0/stretch/amd64/node.Dockerfile](https://github.com/Azure/azure-functions-docker/blob/2fe333f0850b0cf2e7ab78ca1d93ab8a32875968/host/2.0/stretch/amd64/node.Dockerfile)

Specifically these lines:
```
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    HOME=/home \
    FUNCTIONS_WORKER_RUNTIME=node
```

Instead of doing it like a normal human, I had to trick the system a bit:

1. I copy my project to `/home/site`
2. I build + copy the `function.json` files into `/home/site/wwwroot`
3. `AzureWebJobsScriptRoot` is always pointing to `/home/site/wwwroot ` so that's where it will run, nothing to do about it.

It's just confusing that now I have to build stuff into `wwwroot` instead of `dist` - very strange, also I had to force a certain flattened structure, otherwise the azure functions will not find the `function.json` files (they can only be one level deep, i.e `wwwroot/my-function`)

**Comment by liron-navon** [comment]
@ahmelsayed  it changed nothing...

**Comment by ahmelsayed** [comment]
The value set in that Dockerfile should be in a base layer of your image. You should be able to override it in a custom docker.

```dockerfile
FROM mcr.microsoft.com/azure-functions/node:2.0

ENV AzureWebJobsScriptRoot=/dist/functions
CMD [ "/bin/sh", "-c", "echo $AzureWebJobsScriptRoot" ]
```

shows `/dist/functions` for me.
