### ISSUE TITLE
Update Docs - Linux Dedicated supports WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by aluong** [Azure/Azure-Functions#1276]
According to #1076, Linux Dedicated supports `WEBSITE_RUN_FROM_PACKAGE` = <url>, and it's noted in the [Functions Deployment Technologies](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#deployment-technology-availability) matrix.

These pages need updating:

- https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-V2-hosting-options#supported-deployment-methods (Deployment Matrix)
- https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package (Top of the page... `The functionality described in this article is not available for function apps running on Linux in an App Service plan.`)

**Comment by v-anvari** [comment]
In case of any updates required to doc - please open a new issue here - https://github.com/MicrosoftDocs/azure-docs/issues/new
