### ISSUE TITLE
Missing logs in callback functions

### ISSUE THREAD

**Issue by baharedankoyuncu** [Azure/Azure-Functions#1278]
Logs in function callbacks does not seem to appear in Application Insights.

The following code sample logs the first and last log in the function to Application Insights but not anything in the function callback of `MongoClient.connect()`.

```
module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    const MongoClient = require('mongodb').MongoClient;

    // Connection URL
    const url = 'mongodb://...';

    // Use connect method to connect to the server
    MongoClient.connect(url, { useNewUrlParser: true }, function (err, client) {

        if (err) {
            context.log('Oh no!');
        } else {
            context.log('Connected successfully to server');
        }
        client.close();
    });

    context.log('Whoop whoop');
};
```

Using the above equivalent code in a plain node.js app locally, it logs properly in the function callback.

```
var go = async function () {
  const MongoClient = require('mongodb').MongoClient;

  // Connection URL
  const url = 'mongodb://....';

  // Use connect method to connect to the server
  MongoClient.connect(url, { useNewUrlParser: true }, function (err, client) {

    if (err) {
      console.log('Oh no!');
    } else {
      console.log('Connected successfully to server');
    }
    client.close();
  });
  console.log('Whoop whoop');
}

go();
```

I haven't been able to find anything in the documentation https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring related to this, which leads me to think that a) I haven't properly configured the logging or b) the logs might end up elsewhere in async code?

*Details:*
* Function runtime version: 2.0.12562.0 (~2)
* Connecting to Cosmos DB (Mongo DB)

`Host.json` file:

```
{
  "version": "2.0",
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Information",
      "Host": "Error",
      "Function": "Information",
      "Host.Aggregator": "Information"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "maxTelemetryItemsPerSecond": 20
      }
    }
  }
}
```
Let me know if I need to provide more details.

// Baha

**Comment by ColbyTresness** [comment]
@ahmedelnably for monitoring

**Comment by baharedankoyuncu** [comment]
Hi @ColbyTresness,
Just curious, I see that it has been assigned to `Active Questions`, does that mean it will be reviewed? :-)

**Comment by ahmedelnably** [comment]
@brettsam for more insights

**Comment by brettsam** [comment]
@mhoeger / @pragnagopa -- is this a case of missing async and callbacks? The callback is getting called after the function execution, which means we don't log it anywhere.

**Comment by mhoeger** [comment]
Yep, @brettsam is right!

@baharedankoyuncu - your writes to "context.log" are happening after function execution has completed (in the eyes of Azure Functions), because you are mixing callbacks and functions. I would recommend using util.promisify, as mentioned in [docs here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#use-async-and-await)

This should be the shape of things you're looking for:
```
const util = require('util');

module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    const MongoClient = require('mongodb').MongoClient;

    // Connection URL
    const url = 'mongodb://...';

    // Use connect method to connect to the server
    const connectAsync = util.promisify(MongoClient.connect);
    try {
        await connectAsync(url, { useNewUrlParser: true })
    } catch (err) {
        context.log('Oh no!);
    }

    context.log('Connected successfully to server');
    client.close();

    context.log('Whoop whoop');
};
```

**Comment by baharedankoyuncu** [comment]
Shame on me, it was already in the docs 😳
@mhoeger thanks for the explanation.

**Comment by mhoeger** [comment]
@baharedankoyuncu - no problem, it's a recent addition and the docs can be hard to navigate! i'm sure this github issue will be helpful for future others!
