### ISSUE TITLE
Recommending bot-sample addition to Samples page on Wiki

### ISSUE THREAD

**Issue by vitoc** [Azure/Azure-Functions#129]
Will like to recommend the following: 

 - [bot-sample w/ Azure Functions](https://github.com/vjrantal/bot-sample) [by Ville Rantala](https://github.com/vjrantal)

for this page:

https://github.com/Azure/Azure-Functions/wiki/Samples

Thanks!

**Comment by lindydonna** [comment]
Added to https://github.com/Azure/Azure-Functions/wiki/Samples

**Comment by vitoc** [comment]
Thanks!
