### ISSUE TITLE
Cost of pre-warmed instances in premium plan

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/Azure-Functions#1292]
Let's say I chose 2 pre-warmed instances for app scale out. I understand I would be billed for these 2 instance throughout the month. Now, let's assume that the load has increased, and it scales to 5. Now, the [documentation ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan#pre-warmed-instances)mentions that it starts warming up next instance in anticipation of next scale operation.

> As the app scales out, it first scales into the pre-warmed instances. Additional instances continue to buffer out and warm immediately in preparation for the next scale operation. By having a buffer of pre-warmed instances, you can effectively avoid cold start latencies.

So, (I think) a 6th instance will start warming up in anticipation (while only 5 are serving actual user requests). Does this 6th instance get charged at this point? OR does it get charged when this is brought into service to serve user requests?

I am trying to estimate the cost, hence the question.

I have read the following docs about pricing of premium plan:
https://azure.microsoft.com/en-us/pricing/details/functions/
https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan
https://github.com/Azure/Azure-Functions/blob/master/functions-premium-plan/overview.md

**Comment by alexkarcher-msft** [comment]
After your minimum plan size is completely utilized you will scale out at the normal consumption rate, without any extra buffer being allocated or charged. You will be charged for that time at a fixed GB / Second rate listed in the functions billing page.

**Comment by sandeepiiit** [comment]
From [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan#pre-warmed-instances):
> Additional instances **continue to buffer out and warm immediately** in preparation for the next scale operation

I might be understanding it wrong, but it sounds like while 5 instances are serving traffic, 6th is already being started and warmed to be ready for next scale operation. Whereas your comment suggests otherwise.

Should the doc be updated / clarified?

**Comment by derekrprice** [comment]
I have a very similar question.  Are pre-warmed instances still charged regardless of use?  This is no longer called out on https://azure.microsoft.com/en-us/pricing/details/functions/, but it is still mentioned on https://github.com/Azure/Azure-Functions/blob/master/functions-premium-plan/overview.md.  Does one of these need to be updated?

**Comment by alexkarcher-msft** [comment]
[From the doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan#pre-warmed-instances)

"In the Premium plan, you can have your app pre-warmed on a specified number of instances, **up to your minimum plan size.** Pre-warmed instances also let you pre-scale an app before high load. As the app scales out, it first scales into the pre-warmed instances."

We are updating the overall behavior of the pre-warmed instances over the next few months to better align with customer expectations of how the plan should behave, so expect this document to change entirely with more clear phrasing in the coming months.

**Comment by derekrprice** [comment]
That still doesn't quite answer my question.  Why isn't the minimum charge called out in the pricing document?  How do I convert $ per 100 GB-s & $ per 100vCPU-s to a price per month for a single function host that isn't being used much?  Is this the wrong place to bring that up?  I don't see a feedback link on the pricing document.

**Comment by ishepherd** [comment]
@alexkarcher-msft Do the Premium Plan charges mentioned on https://azure.microsoft.com/en-au/pricing/details/functions/ ($0.0004/100 GBs, etc) get billed even for functions running on the prewarmed instances (monthly charge)?

I hope not, because that would be double-billing right?

**Comment by alexkarcher-msft** [comment]
Yep! If you are only moving a small amount of traffic through your pre-warmed instance you will not warm up another and will be only charged for that pre-warmed instance.

Once you approach the limit of that instance we'll warm up another and you'll be charged for that instance awaiting traffic.

**Comment by ishepherd** [comment]
@alexkarcher-msft cc @jeffhollan  I am v confused on the Premium Plan accounting and I see lots of other confused people around. If you could write a deep dive on it, I'd really appreciate it.

> Once you approach the limit of that [pre-warmed] instance we'll warm up another **and you'll be charged for that instance awaiting traffic.**

(my emphasis)

What's the scenario here - Is pre-warmed instances slider set to 1? If so, why is the second instance getting charged? Isn't the per-instance charge for pre-warmed only?

**Comment by pmonte** [comment]
Pricing is still confusing, at least for me.

Let's make a simple example: 1 Min Instance, 1 pre warmed instance and 1 Max instance. We'll pay for the ~€104+7/month for the premium plan PLUS the normal consumption fee (€0.000014/GB-s etc) or are these included in the €104+7?

What if we have 1 Min Instance, 1 pre warmed instance and 2 Max instance AND the same amount of events as in the first example? As far as I understand we pay for the same € as above.

But what if the number of events grows so that it scales out to two instances? 
The doc says "Azure Functions Premium plan is billed based on the vCPU and memory that your functions consume". How much is that? I can just see an example per month/hour on that page.

The €104+7 I see on the pricing page refers to EP1? If so why if I start creating it I read "75.24 EUR/Month Baseline (Estimated)"?

Sorry, totally confused.

**Comment by przemos** [comment]
Can we get clarification on €111 vs €75.24 per month, please? This is actually a decider for us whether Premium is value for money or not :)
