### ISSUE TITLE
Unable to build VS2015 Function project with VSTS build definition

### ISSUE THREAD

**Issue by erwinkramer** [Azure/Azure-Functions#130]
Im trying to get my source control (VSTS) going with a new Functions project added to my VS solution. I'm using VS2015 with the latest App Service Tools 2.9.6 (Functons Preview). 

So local building goes fine and publishing to Azure too, however when i let the build definition fire on VSTS it produces the following error: 
`PROJECTNAME\PROJECTNAME.funproj(7,3): Error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AzureFunctions\Microsoft.AzureFunctions.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

I found the files locally on my disk (which is expected). But it doesn't have them on VSTS. 

It's written as follows in the `.funproj` file:
`  <Import Project="$(VSToolsPath)\AzureFunctions\Microsoft.AzureFunctions.Props" Condition="'$(VSToolsPath)' != ''" />
`

My build definition looks like this: 
![image](https://cloud.githubusercontent.com/assets/4255748/21686031/1abb40b0-d364-11e6-80d0-8ea8698f8f8b.png)

**Comment by probertdaniel** [comment]
Hi Erwin, this question was asked on the Functions Advisor forums, and the Product Group replied that this is a known issue: the hosted build agent (hosted in VSTS) doesn't have the functions SDK installed.
VSTS support is still in preview afaik as it's an extension of the VS support.

Function projects don't need to be built in VSTS as there is no compilation target (i.e. no need for a DLL) at the moment. Instead you just need to publish the content. 

What we did to get around this was to disable doing a build, and instead just published the content, and then deployed via an ARM template as normal.

Alternatively, if you use a local agent, you can install the functions SDK and then the build will complete successfully.

HTH.

**Comment by erwinkramer** [comment]
@probertdaniel  Thanks for the quick reply and suggestions. The solution of using local agents sounds interesting, thanks for mentioning that. However i guess i'll stick to disabling building for this project for now...

**Comment by lorenpaulsen** [comment]
I have used a combination of these two approaches:

1. http://www.clemensreijnen.nl/post/2017/01/02/CICD-Pipeline-for-Serverless-release-Azure-Functions-with-VSTS
2. http://case.schollaart.net/2016/10/20/deploy-your-azure-fuctions-using-visual-studio-team-services.html

The first link shows how to handle the Function Project, while the second link avoids the problem by not using a Function Project at all (was most likely written before they were available). However, the second link describes an easier way to do the App Service publish step than the first link does.

**Comment by lindydonna** [comment]
Closing since @lorenpaulsen provided a workaround.
