### ISSUE TITLE
Deploy Broken for 1st Party Custom Node Modules

### ISSUE THREAD

**Issue by abramjstamper** [Azure/Azure-Functions#1306]
## Background

Due to a change in [NPM](https://www.npmjs.com/), I'm having deployment issues with 1st party packages (internal custom packages developed by my company). In recent versions of NPM, the date on the file is always set to be October 25, 1985 when running an `npm pack`. If you're not familiar with `npm pack`, it creates a tar ball of your package to distribute to other Node JS projects. In the `package.json` file for other project, the dependency is a file path to your package's tarball that was created with `npm pack`. The change to wipe all metadata for the files was merged in [here](https://github.com/npm/npm/pull/20027) and discussed/confirmed that this is expected behavior [here](https://github.com/npm/npm/issues/20439#issuecomment-385121133).

While I strongly disagree with the folks at NPM with their expectation that this *should* be expected behavior, the fact is that it is expected behavior means tools must be adapted to this limitation.

## Current Issue
I'm experiencing this issue with Azure Functions where my 1st party packages never update. The only way to get them to update is turning off the Azure Function and deleting the `node_modules` folder. After, I can turn it back on and deploy from VS Code. This is unacceptable as it causes significant down time for the application to update. 

While I know this may be related to [Kudu](https://github.com/projectkudu/kudu), I haven't experienced this specific issue with [App Services](https://azure.microsoft.com/en-in/services/app-service/) that deploy via local git also using Kudu. With local git, the custom package tarballs have to be uploaded using the Diagnostic Console in the same file path before pushing. I do this with relative file paths for simplicity. I have tried that with Azure Functions, but to no avail. I think it's locking the node_modules folder when it's running to prevent it from being updated since it's being pushed from VS Code.

I have only experienced it with Azure Functions deployment. All of my Azure Functions deploy via VS Code. Therefore, I have posted this issue here in the Azure Functions repo, if it's in the wrong spot, let me know where to direct it. Since I'm deploying from VS Code, I would expect it to overwrite everything in the cloud with what I'm pushing up from VS Code rather than doing a check on the file dates. However, as I've experienced, that's not the case.

### Versions
VS Code: 1.37.1
Extensions:
- Azure Account: 0.8.4
- Azure Functions 0.18.1
- Azure Resource Manger: 0.6.0
- Azure Storage 0.7.1
NPM: 6.7.0
Node.js: 11.14.0
dotnet: 2.2.401
OS: Ubuntu 18.04 LTS

I just re-created all the Azure Function yesterday to update them to the latest run-time version. The application setting is `~2`. It's a running Windows in EASTUS2.

**Comment by ColbyTresness** [comment]
@mhoeger

**Comment by mhoeger** [comment]
@abramjstamper - if you're deploying through VS Code, it should be defaulting you to use WEBSITE_RUN_FROM_PACKAGE, which should be the solution to the problem you're seeing (see note on Predictability and Atomicity in the [feature announcement](https://github.com/Azure/app-service-announcements/issues/84)), because everything that you have locally that gets zipped up will be what you are running in the cloud.

If it is using this setting, navigating to a function on the portal would show you something like this:
![image](https://user-images.githubusercontent.com/8888531/63620044-2571c700-c5a5-11e9-830c-e21c3eadf8a4.png)

A few questions: Can you confirm that you see this? Can you confirm that your `node_modules` that you're using are under `D:\home\site\wwwroot`? And can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by abramjstamper** [comment]
Yes I remember the last set of function apps having the application setting `WEBSITE_RUN_FROM_PACKAGE`. I don't believe the set of apps that were created last week have this application setting set. I had thought the application setting got set automatically when pushing from VS Code, but maybe that isn't the case.

Region: EASTUS2
UTC Execution Time: 2019-08-26T13:19:50.093 to 2019-08-26T13:19:50.637
UUID: bc5b26fc-4c38-47b9-8faa-4c0216fa22a2

Deployment Output from VS Code after manually setting `WEBSITE_RUN_FROM_PACKAGE` to 1:
```
9:16:57 AM ...: Creating zip package...
9:17:03 AM ...: Starting deployment...
9:16:44 AM ...: Updating submodules.
9:16:45 AM ...: Preparing deployment for commit id '3e57950211'.
9:16:47 AM ...: Skipping build. Project type: Run-From-Zip
9:16:47 AM ...: Skipping post build. Project type: Run-From-Zip
9:16:52 AM ...: Syncing 3 function triggers with payload size 421 bytes successful.
9:16:53 AM ...: Deployment successful.
9:17:58 AM ...: Waiting for long running command to finish...
Deployment to "..." completed.
```

### Update
In our staging instance, I was able to successfully set `WEBSITE_RUN_FROM_PACKAGE`. `node_modules` folder appears update-to-date with the custom modules. Thank you so much for the assistance.
