### ISSUE TITLE
Unexplained storage account cost related to files

### ISSUE THREAD

**Issue by mark-buhagiar** [Azure/Azure-Functions#1307]
We are making use of Azure Functions (v2) extensively to fulfill a number of business requirements.

We have recently introduced a durable function to handle a more complex business process which includes both fanning out, as well as a chain of functions. 

Our problem is related to how much the storage account is being used. I made a fresh deployment on an account we use for dev testing on Friday, and left the function idling over the weekend to monitor what happens. I also set a budget to alert me if the cost start shooting up.

Less than 48 hours later, I received an alert that I was at 80% of my budget, and saw how the storage account was single handedly responsible for the entire bill. The most baffling part is, that it's mostly egress and ingress on file storage, which I'm entirely not using in the application! So it must be something internal by the azure function implementations. I've dug around and found issue #832. In this case the issue seems to have been solved by switching to an App Service plan, but this is not an option in our case and must stick to consumption. I also double checked and made sure that I don't have the AzureWebJobsDashboard setting.

Any ideas what we can try next?

The below are some interesting charts from the storage account. Note how file egress and ingress makes up most of the activity on the entire account.

![image](https://user-images.githubusercontent.com/20166924/63675330-dc11b980-c7e8-11e9-931a-1999ccf734b1.png)

An [SO ](https://stackoverflow.com/questions/57654009/azure-functions-unexplained-storage-account-cost-related-to-files) question has also been opened for this

**Comment by inspektor99** [comment]
We've seen the same issue when deploying Azure Functions.  We identified Trace Logging from the function as the culprit.  However, once we modified the host.json to only log Errors, we still see trace logging upon deployment once in awhile.  We are not able to figure out why the Function trace logs even though the host.json does not allow.  Upon re-deployment with the same configuration, the trace logging stops.  At this point we're not sure if this is our issue or an Azure issue.

Re-deploying seems to solve the issue, but this has cost us some unnecessary spikes in funding.

Here's our host.json:
```
{
  "version": "2.0",
  "extensions": {
    "eventHubs": {
      "eventProcessorOptions": {
        "maxBatchSize": 256,
        "prefetchCount": 512
      }
    },
    "logging": {
      "fileLoggingMode": "debugOnly",
      "logLevel": {
        "default": "Error",
        "Host.Results": "Error",
        "Function": "Error",
        "Host.Aggregator": "Error"
      },
      "applicationInsights": {
        "samplingSettings": {
          "isEnabled": true,
          "maxTelemetryItemsPerSecond": 5
        }
      }
    }
  }
}
```

**Comment by jpd30** [comment]
We are also seeing this issue. We have a .NET Core v2 function app with 8 functions, all on timer triggers - 5 run once every minute, one runs once every 15 minutes, the other two run once every day. These functions have been generating around 15k file transaction per minute, although the function code is not accessing any file storage directly.  When left unresolved this costs us around $30/day.

![image](https://user-images.githubusercontent.com/7931742/67594071-79428d00-f75b-11e9-80f9-456259f472bd.png)

As suggested by #832 we disabled and re-enabled one of the functions, this has reset the transaction count to a less alarming level (as per the right-hand side of the chart).

We are regularly reviewing the transaction rate (and also have setup alerts) and will post back if we have any additional insights.

**Comment by Jankowski-J** [comment]
Any updates on this?

**Comment by delta25** [comment]
Sorry for not providing feedback on this. We did in fact resolve the issue. It was related to our deployments. Foolishly, we had chosen to deploy and run from package instead of deploying as a ZIP. 
![New_release_pipeline_-_Pipelines](https://user-images.githubusercontent.com/20166924/72354156-88473480-36e5-11ea-859b-294f02206222.png)

**Comment by kamyker** [comment]
Any idea how to do it (Zip Deploy) with VS Code deploy? Everytime I publish function WEBSITE_RUN_FROM_PACKAGE changes to url.

Tried VS Studio but linux deployment also doesn't work.

**Comment by thomasrosdahl** [comment]
@mark-buhagiar I don't see how **Zip Deploy** could have improved storage utilization. Zip deploy will extract the files to wwwroot whereas  **Run From Package** will mount the zip directly into wwwroot without extracting any files: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#run-from-package I think the whole point with **Run From Package** is to reduce deployment / cold start times by avoiding unnecessary file copy. Please correct me if I'm wrong.

**Comment by e14mattc** [comment]
We're seeing the same problem ..

![image](https://user-images.githubusercontent.com/9819307/79970707-3ef84500-848b-11ea-8815-435418adb327.png)

- Azure Functions Runtime: 3.0.13139.0
- Language: javascript
- Deployment slots: 2
- App Service plan: consumption
- Region: UK West
- Deployment option: none.. we deploy from VS Code

AzureWebJobsDashboard config option is not set.

We turned off logging via the _host.json_ file...

```
{
  "version": "2.0",
  "logging": {
    "fileLoggingMode": "never",
    "logLevel": {
      "Function": "Error",
      "default": "None"
    }
  }
}
```

We're now wondering what to try next?

**Comment by mark-buhagiar** [comment]
Hey @e14mattc I can't quite recall what's the default deployment option when deploying through VS Code. To check if you're having the same problem I was, you can open up `Storage Explorer` on your Mac/Windows, find the storage account hosting the function app, and then having a look at the `site>wwwroot` directory. In my experience, this should only have the `host.json` file. If it has all your DLLs in there you're probably facing the same issue I was. To resolve, you could either figure out how to set up zip deployments on VS Code, or set up a super quick pipeline on AZ DevOps. This shouldn't take more than an an hour even if it's your first time. Plenty of guides to guide you out there.

**Comment by e14mattc** [comment]
You don't get a choice when you publish from VSC, but looking at the logs it does a zip file deployment. When you look in Storage Explorer you see everything in the wwwroot folder, not just host.json.. that's for a nodejs/javascript project.

I'd be surprised if it was the deployment method.. we've not touched this code in weeks, so it's not like it's getting any changes published. I've used DevOps pipelines before, so can take a look at that. 

From other posts elsewhere it sounded like switching from a Consumption plan might also solve the issue, but we like the flexibility of the Consumption plan for scaling automatically & not having to pick hardware :)

Can anyone from the Azure team comment on this, please?

**Comment by mark-buhagiar** [comment]
My app was a .net core app, and I had nothing in my wwwrooot. Like you I was adamant on using the consumption plan. Unfortunately I'm somewhat limited in the help I can offer, since I no longer work for that company, and therefor don't have access to the tenant. Best of luck, with Azure support 😬

**Comment by fhtino** [comment]
In my case Files activity is mainly on Egress. I've compared Function runs and Storage Files transactions counts. It seems there is a correlation between Storage Files and Functions runs. I guess Files activity is caused by Functions startup on different instance because it's running on Consumption plan. If the underlying server does not have the app, it must get app's files form Files.

**Comment by LXBdev** [comment]
In Stackoverflow, the current suggestion is this:
https://stackoverflow.com/a/61259940/336378

> After weeks of investigation the Azure support team and I think we have found the line that causes the issue and this is it:
>
>     .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
>
> The config file was not published as part of the publish process and is not present in Azure. Experiments for now seem to confirm that when this is present the transactions spike and when not they are normal. This does not answer

**Comment by elmalakai** [comment]
I have the same issues, and recently found out it was costing us nearly $600 a month.  I think logging is the key to this problem.

![image](https://user-images.githubusercontent.com/614641/81113248-281b0f00-8edd-11ea-908a-3fef22f042d6.png)

I do us the ConfigurationBuilder to make my config, like the previous bug submitter uses:
`                var config = new ConfigurationBuilder()
                 .SetBasePath(context.FunctionAppDirectory)
                 .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                 .AddEnvironmentVariables()
                 .Build();
`
That code was added on May 8th, 2019. 

From 5/8/2019 to 12/10/2019 this change had no impact. Our LRS Write Operations each month were below the threshold, and therefore free.

Starting with our December invoice, on 12/10/2019 we blew through our LRS Write operation limit in a day, and added 433. 

By 1/1/2019 we added 17,719 operations. That was 259 dollars worth. 

Jan, Feb, March and April were all bad or worse. By 4/2/2020-5/1/2020 we were up to 33K LRS Write Operations a month (After our free 100k). That's $507 worth.

If I go back to source control for 12/10/2019, the biggest change I see in that release is V2 to V3, and .Net Core 3.0 to .Net Core 3.1. Also we had to add in EF Core, to perform some database operations. 

So I guess the possible culprits in my book are:
- V3
- .Net Core 3.1
- EF Core

**Comment by Feday** [comment]
I am also surprised with the high cost that my Azure Function presented regarding storage operations.
It is a simple BlobTrigger function and it is firing over 10k operations for about 100 function executions:
![image](https://user-images.githubusercontent.com/4411803/93873066-77ed4d80-fca7-11ea-8aaa-339460645ae9.png)
![image](https://user-images.githubusercontent.com/4411803/93873138-95221c00-fca7-11ea-8903-645018dc3473.png)

This is not acceptable, the function simply reads the blob (less than 100kb), deserializes it and outputs an average of 3 messages to a storage queue (on this controlled test).
Notice the high amount of GetBlobProperties and also the CreateQueue operations, actually, none of the metric counts make sense at all.
I am using v3 on a .Net Core 3.1 C# compiled function, zip deployed.

**Comment by przemos** [comment]
I have the same problem and I think it is a generic problem of Azure Function implementation. I have a function in Premium plan that has only HttpTrigger with the fileLogging set to never. It is deployed with Zip deployment. It generates unreasonable number of operations with Azure Files. 

We are forced to care about how Azure Function uses Azure Files underneath which, to be fair, is hardly documented and rational. There is no explanation whatsoever how Azure Functions interact with Azure Files. The associated cost is not insignificant yet Azure team seem to consider it a non-issue. It feels the whole Azure Function concept in Azure is Beta stage rather than anything mature. 

When you calculate the cost of ownership you are told to use CPU and memory utilization which is not true and unfair to the user. There is no way to understand the Azure Files cost generated by the function and that is terrible. I've been struggling to understand for over 3 years now how it is possible that Azure teams can keep it that way.

**Comment by nzthiago** [comment]
Hi everyone - the Functions team certainly does not want unnecessary storage file transactions to be the behavior of the platform. There might be different reasons for high number of file storage transactions observed though. Merely accessing files via SMB can show up in logs as file Create operations as [the SMB2 CREATE Request packet](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/e8fb45c1-a03d-44ca-b7ae-47385cfd7997) is sent by either a creation of **or access to** a file. This could lead us to different investigations for your scenarios like high number of access to referenced node modules, antivirus checks, etc., and subsequently a few ways for us to address these issues. 

Therefore I would please ask you to either: 

- Open a support ticket if this is impacting a production app that needs immediate attention or 
- Follow these steps to [share your function app name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) here together with the region your app is deployed to for us to investigate
