### ISSUE TITLE
Middleware in azure function code

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/Azure-Functions#1322]
Hi All,

In Asp.NET core we have the facility to add middleware in http pipeline. In Azure function is that possible. Basically I'm want call another service in Azure function. But I want to use Circuit breaker with this. Instead writing that in the code it would be good If I write that in pipeline so that it gets executed when the request leaves my function scope every time.

**Comment by fabiocav** [comment]
Apologies for the long delay here. This issue was, unfortunately, not flagged for triage. 

This is not currently supported in Functions today. Some of the options you have today range from sharing a common service for the shared logic or having a common base function class.
