### ISSUE TITLE
[Az CLI] Create command should support setting runtime version

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/Azure-Functions#1341]
Mirror Issue to https://github.com/Azure/azure-cli/issues/10549, for tracking purposes

**Comment by ankitkumarr** [comment]
For now, the only case where the user would have a choice is Python (3.6 or 3.7).

**Comment by ankitkumarr** [comment]
Sounds like we also want to support this for Node.

**Comment by ColbyTresness** [comment]
Yeah sorry I should have specified that, this should be made generic and for now should include the Node 8 vs Node 10 split as well.

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-cli/pull/10871
