### ISSUE TITLE
Environment.GetEnvironmentVariable stopped returning values (started returning null values)

### ISSUE THREAD

**Issue by zmarty** [Azure/Azure-Functions#1347]
We are a team inside Microsoft using Azure Functions v2 - **App Service Plan** - Runtime version: 2.0.12673.0 (~2)
On our dev machines we run a mix of Visual Studio 2017 and more recently Visual Studio 2019
**App Service name**: FastPath-prod-east-us

**Symptom 1**: Environment.GetEnvironmentVariable(...) calls started returning null values on servers in production. However, we can see those settings in our code AND in the portal just fine. Example Exception you can search for: Config value for key CosmosDbTestEndpointUrl had a null or empty value
**Symptom 2**: We slightly modified the text of the exception message above and we deployed the change through zip deploy from Visual Studio 2017 multiple times. The app service continued to run the old code and display the old exception message above. Renaming the function does not help, **there is still a function with the old name consuming queue items**.

**Comment by zmarty** [comment]
Fixed, please ignore.

**Comment by androidand** [comment]
I have this issue, what mistake did you also do which you didn't want to share with your fellow googlers?

**Comment by zmarty** [comment]
I regret not writing more information here because I have been trying to remember for the past 10 minutes and I can't so far. Sorry!

**Comment by zmarty** [comment]
Ok, I remembered! From Visual Studio it's easy to publish projects into app service instances. However, it's also easy to publish the wrong code in the wrong instance. One of our team members published the incorrect project to the incorrect instance. That instance did not have the expected app settings set, so the code started logging null from Environment.GetEnvironmentVariable. So we had a good instance running in parallel with a bad instance (that did not have the correct environment variables set), both of them logging into the same Application Insights log.
