### ISSUE TITLE
Document new context.log methods

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#135]
In this PR https://github.com/Azure/azure-webjobs-sdk-script/pull/1058 @mamaso added context.log.verbose, context.log.error, context.log.warn methods to compliment the existing info method. We need the documentation updated.

**Comment by lindydonna** [comment]
@ggailey777 Can you take this one?

**Comment by ggailey777** [comment]
There seems to be an issue with the context.log.verbose() method: https://github.com/Azure/azure-webjobs-sdk-script/issues/1370

**Comment by ggailey777** [comment]
@mathewc is there any difference between how error(), warn(), and info() are logged? Also, is verbose() doing something else, I don't see it getting logged?

**Comment by mamaso** [comment]
@ggailey777 I'll take a look at this

**Comment by mamaso** [comment]
@ggailey777 I think you need to set the level to verbose in host.json: https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

**Comment by ggailey777** [comment]
@mamaso Thanks, I'll make sure we doc that in the main topic.

**Comment by ggailey777** [comment]
@mamaso @lindydonna I have added info about the new trace level for console logging in the Node.js topic, which you can review [here](https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?branch=pr-en-us-9679#contextlog-method). I also added a section about writing to the console. 
This is the PR: https://github.com/Microsoft/azure-docs-pr/pull/9679
