### ISSUE TITLE
Azure function output binding IoT Hub

### ISSUE THREAD

**Issue by Toofle** [Azure/Azure-Functions#1351]
Hi,

I'm currently trying to create an Azure Function with a HTTP trigger.

The trigger will perform some minor translations for a message and should then send it to IoT Hub.

The documentation provided states that IoT Hub is suited for output binding. See here:

docs.microsoft.com/nl-nl/azure/azure-functions/functions-triggers-bindings#supported-bindings

Whenever I try to send a message, the Azure Function throws the following exception:

Microsoft.Azure.EventHubs: Unauthorized access. 'Send' claim(s) are required to perform this operation

While searching the internet I haven't found a solution yet. Most answers I find tell me it's not possible (as opposed to the documentation by Microsoft stating that it is possible?! ).

Can anyone from Microsoft please clarify what is actually possible?

Kind regards

**Comment by angellmethod** [comment]
Can you share how you are trying to send the message to IoT Hub and the binding setup?
