### ISSUE TITLE
[Premium] Error "Failed to restart app"

### ISSUE THREAD

**Issue by ishepherd** [Azure/Azure-Functions#1353]
Portal gave this error when trying to restart an app hosted on a Premium Plan. I have just emailed you with the app name. ('RE: 119091326000294 | Trying to secure to VNET, getting UnauthorizedAccessException')

Actually it happened for all 3 apps on this plan.
Restarted at ~06:56 UTC on Oct 5.

There are no exceptions in App Insights, but there was a "The application was terminated" in kudu log streaming, so perhaps the restart in fact did work?

**Comment by alexkarcher-msft** [comment]
We have followed up in a separate thread

A quick summary for anyone viewing this thread in the future:

This issue is related to a fixed timeout in the portal for ARM calls. If your restart takes longer than 60 seconds you'll receive this error, regardless of the status of your restart.

**Comment by ishepherd** [comment]
Thanks again Alex!
So this is a feedback for portal UX. Please direct as appropriate.
Feel free to close - thanks again.
