### ISSUE TITLE
[Az CLI] Change node version to ~10

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/Azure-Functions#1355]
Talked to @ankitkumarr adding this to Sprint 60 as it is a very small change

**Comment by ahmedelnably** [comment]
Mirror issue to https://github.com/Azure/azure-cli/issues/10766

**Comment by fabiocav** [comment]
Leaving this in sprint 60 as it will still close within the appropriate CLI sprint.

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-cli/pull/10871
