### ISSUE TITLE
Offer a streamlined article outlining Azure Functions deployment

### ISSUE THREAD

**Issue by atrauzzi** [Azure/Azure-Functions#136]
Following up from my discussion with @lindydonna on [Twitter](https://twitter.com/lindydonna/status/819015036588806144).

_Also, I'm reserving the right to edit/update this description. I did a lot of reading about functions over the holidays, any important examples will take time to dig up again. So what I'm putting here is just a general brain-dump summary.  I don't mind refining/correcting any points with the help of everyone here._

Currently documentation for Functions suffers from a few issues:

 - Inconsistent - no Core support, yet there's a `project.json`?
 - Out of date (core support)
 - Too heavily focused on Azure CI/CD which is a pull-centric model
 - Guidance on local development scenarios not offered on equal footing to the proprietary web editing experience
 - The consumption Azure Application Service Plan is an opaque and inflexible resource that comes mostly as a surprise during experimentation
 - There is no clarity about how to deploy Azure Functions alongside an existing Azure App Service
 - There is no clear source of guidance for building and deploying Azure Functions from a CI/CD server like Team City or Octopus

Individual articles do well to present the small tidbits that they focus on.  But I find together, they leave me without a working understanding of how to create Azure Function projects, work in them and deploy them.  There's a frustrating myopic focus on trying to get me to leverage Azure CI/CD - which is great for toy projects and prototyping but also completely opposed to good configuration management.

Moreover, my confidence level with local development is quite low, whether with or without Visual Studio.  Despite my most diligent tinkering, I can't figure out how Functions works and what kind of beast it is to even begin to make inroads on it.

Which is unfortunate, because conceptually, **it's exactly the kind of service I've wanted for quite some while**!
Believe me when I say I'm [no stranger](https://github.com/atrauzzi/laravel-drydock) to [complexity](http://atrauzzi.blogspot.ca/2016/12/making-typescript-npm-packages.html).  I'm saying this only because I really think when it comes to deployment, the way developers interact with Azure and especially in this case Functions is just too fuzzy.

### My Suggestion 

Currently I think it's worthwhile to revisit Azure Functions documentation in a top-down fashion.  A series of articles that pick up from a completed-and-ready project sitting on the filesystem, to bundling it up and pushing it up to Azure, assuming a Linux CI/CD server.
By taking this approach, the advice will be easy to automate and disciplined, having no way to reach out to the kludges in the Azure web UI.

On top of this, there are a few fundamental mysteries still lingering in my mind:

 - Directory structure - Ideally I'm only dealing with it from the top. No dependency splicing/copying-in, etc...  If I'm working inside of the directory structure, hopefully it's on only my own sources.
 - Process model
 - Dependency management
 - Any potential to live alongside existing web projects (or any explicit lack thereof) and what that might entail against the Azure App Service directory structure

Ultimately, I'd like to read just one document per objective, and not a series of disparate articles. Something similar to the ASP.net Core docs.  Many of the issues could just be down to presentation.  On that, I definitely do not claim to be an expert.  I've heard people in the past draw a distinction between lesson-style and objective-driven documentation, maybe more of the latter is needed?  I will however include one last contrived list which is basically my priorities when assessing a technology:

 - Can I run it locally?
 - Can I make it run the same on my teams machines?
 - Can I automate getting it running on my teams machines?
 - Can I run that same setup on my CI/CD servers?
 - Bonus: Can I do it on all platforms? Most of the time this basically ensures everything above is a _"yes!"_
 - Does it produce a single, consistent, versionable artifact?
 - Bonus: Is how I run that artifact in production the same as when I run it locally?

Obviously none of this is a surprise, most of it is common sense.  But I'm just having troubles ticking all these items off my list.

Really, there may even be items that can be refined from this ticket into other Azure and ASP.net properties.

**Comment by lindydonna** [comment]
I'll let other folks on the team comment on deployment and the consumption compute plan. A few comments:

- We do support .NET Core as we support netstandard class libraries. However, the Functions runtime currently runs on the full .NET framework and we are porting the runtime to .NET Core. Our development is done in the open, and you can track the progress here: https://github.com/Azure/Azure-Functions/issues/98
- project.json is used by other project types than just .NET Core, and it was a good format for specifying NuGet packages.
- Deploying alongside an existing App Service instance is no different from other App Service resources. Just create an App Service Plan and you can deploy multiple Web Apps, API Apps, Mobile Backend Apps, and Function Apps to it. Just choose an existing App Service Plan during Function App creation. This is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-portal#create-a-function-app

**Comment by SyntaxC4** [comment]
I will reserve the same right to update this post to provide additional context over-time to avoid a very long thread. 

### On Deployment

We provide documentation on the CI/CD model which is integrated into our platform for a good reason, we are intimately familiar with the design, code and implementation of these features. They do reflect a great deal of industry standard and developer friendly services. One option of interest for you is we do provide integration using Visual Studio Team Services (VSTS), which does provide an experience similar to Team City. Furthermore, you might be interested to learn about [VSTS integration with Jenkins](https://www.visualstudio.com/en-us/docs/integrate/get-started/service-hooks/services/jenkins)

As for providing guidance on software from other companies, we're not experts on their software, so I consider it counter productive to do so. In this regard, we are very happy to see that there are other continuous integration providers that are writing articles around how you can leverage their software with our platform, which is definitely something we encourage. 

For example, Octopus Deploy, a company that you reference above, created this blog post on [Automating Octopus with Azure Functions](https://octopus.com/blog/automating-octopus-with-azure-functions).

I have also tracked a separate bug #138 which will add in an expanded explanation around our command-line deployment options, which would be easily leveraged with continuous deployment or integration software.

**Comment by atrauzzi** [comment]
@SyntaxC4 - Thanks for jumping in.  A few things in your first two paragraphs I want to address and then move on to the more interesting last two.

 - Regarding VSTS, my sentiment towards it is exactly the same as Azure CI/CD. This particular issue seems to be a cultural one internally at Azure as I keep getting funnelled towards these products.
    Proprietary hosted CI/CD is just not acceptable and should be dealt with separately to your product.  Not as an integral part of it.  Such that when I hear this:
    > ...we are intimately familiar with the design, code and implementation of these features
    I see a **huge** problem.  To the extent that I would really try to get out of even the habit of suggesting VSTS unless people explicitly ask for a turn key solution.  What this statement does is validate for me that there is a lot of unmitigated complexity in deploying Functions/Web Applications. 

 - I'm not asking you to show me how to use Octopus or TeamCity.  I asked - with emphasis:
    > ..from a CI/CD server _**like**_ Team City or Octopus
    The general CLI deployment option information would suffice, but they will have to be comprehensive.

 - I'm a little pressed for time this week, but my next development task is basically a dead ringer for Functions and I'd like to basically get myself into the _yes_ camp on using it.  Seriously.  I will sooner set up hangfire or a containerized VM again than use current Azure queue & worker options right now.
If I/we can start bringing together all the links to documentation like the octopus one you provided, I'd like to be able to review them all together in one go.  I'll see about bringing in the links @lindydonna gave me on twitter as well.

 - Bug #138 sounds like the way forward overall.  It sounds like initially it'll be .net 4.5 and then eventually there will be a core equivalent.  The only thing I'd like to caution is that Azure functions must not insist so strongly that its identity be coupled with VSTS or Azure CI/CD.  It just doesn't help advanced users trying to get up to speed with things.

**Comment by lindydonna** [comment]
@atrauzzi You can use FTP for deployment, that's probably as simple as it gets. :)  Most of our customers are asking for a turnkey and integrated solution, which is why we have articles about VSTS and integration with that platform. 

For deploying an Azure Function, you just need to match the directory structure here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#folder-structure (that's the same link I pointed from Twitter).

**Comment by atrauzzi** [comment]
I'd say your audience is split now and any customers who are asking for tools are doing so after years of being conditioned to depend on them.
It's not that there isn't such a thing as turn-key solutions coming from the other direction.  But it tends to be that they're less obtrusive to the project.  VSTS is just not a level of detached I want to be from my deliverables.

I'd say using the Azure CLI with a zip or nupkg will eventually emerge as the preferred option.  Make tools like VSTS speak *that* language, and let developers decide for themselves.

I suspect any Azure functions I set up will likely target their own Web Application due to the different billing scheme?  If I did use CLI to push some Azure functions up, specifically what steps would I have to take?  What would the .zip or .nupkg have to look like?  More documentation and specific points within welcome.  Just trying to build up my stockpile of docs now. :)

**Comment by atrauzzi** [comment]
@lindydonna & @SyntaxC4 

Finally got some time to do a bit of reading and am booting up a clean Functions project again.  I've got a couple of questions ready, hopefully you can help me out :)

My intention - and you can set me straight if this isn't in line with the project templates design - is to have the functions project invoke separate .net Core projects.  The first structural snag I have there is to do with how the worker code is situated to the Functions project:

 - Is it a console app?
 - Is it a library?
 - How do I maintain the worker code separately to functions while still allowing the Functions project to reference its deliverables?
 - Is there a way to make this work by adding projects from other solutions to the solution my Functions project lives in?

My ideal scenario is that I create two solutions.  One with the worker code and another with the Functions definitions.  With that approach, the Functions project and solution serve as little more than entrypoints for functionality I can code, build and test separately.

Another challenge I can think of is that depending on whatever structure is best to use, I still have the dilemma of ensuring that when I deploy my functions code, it has all the assemblies in place when being pushed up to Azure.

Looking at all this, I'm fairly certain there's going to be a way forward.  But as you can see, I want to protect my business logic from any kind of vendor lock in.  Ideally I'd like any implementation I do in Functions to simply be bootstrap.

**Comment by atrauzzi** [comment]
Just to experiment, I've tried making an empty Functions project with one `csx` function.  Ended up with this error trying to run it:

```
Unable to retrieve functions list: No MediaTypeFormatter is available to read an object of type 'FunctionEnvelope[]' from content with media type 'text/plain'.
```

Considering all I did was accept defaults - this is very strange.

**Comment by atrauzzi** [comment]
Here is a blog post from someone else raising fairly similar if not identical concerns to my own: http://blog.stephencleary.com/2016/11/azure-functions.html

**Comment by lindydonna** [comment]
@atrauzzi  The Azure Functions CLI is still in beta, and we need better error messages. The bug you saw about FunctionEnvelope[] is tracked here: https://github.com/Azure/azure-functions-cli/issues/6

You can reference an external library using #r. It should be a NetStandard 1.3 project if you're using .NET Core. See https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#referencing-external-assemblies. Then you can have the structure that you're describing. 

Note that any input bindings and triggers other than HTTP are specific to the Functions runtime. If you want to minimize your dependencies on a custom framework, you should either restrict yourself to only HTTP triggers, or create your own triggering logic if you don't want to run in Azure.

**Comment by atrauzzi** [comment]
How would I use `#r` to reference a library I've included via `package.json`?

If I can make a library and call it from a `csx` file, that would give me a vector to insulate my business logic from Functions.

 - Would there be any issues with transitive dependency issues?
 - Is there any way during local development to have Visual Studio substitute that library with the local version if it's sideloaded into the solution?

**Comment by lindydonna** [comment]
@atrauzzi You don't need to use #r if you've added the library via package.json. If you want to use a different library locally, you'd have to use conditional compilation or a separate project.

**Comment by atrauzzi** [comment]
@lindydonna - I think it might just be better to show the issues I've been having as it's very difficult to explain one by one the ways Functions throws up barriers.  More so because it seems like any time I raise an issue, there's always some document to be referenced that doesn't actually serve to address any real issues.

I've made a repository just to act as a testbed and also somewhere to collect specific items as I encounter them with as much information as possible.  This will ideally include screenshots and pointers to the specific source files.

When I talk about how Functions is not quite complete, **these** are the sorts of scenarios that I don't think are at all unreasonable to encounter.  Most of it is really just a question of whether Functions works within the already established norms of Visual Studio projects.

**Comment by lindydonna** [comment]
@atrauzzi I see the GitHub issues you filed, thanks for the level of detail. (Btw, next time please add a new comment with links to them, since GitHub doesn't notify on issue references, just comments.)

The Visual Studio Functions tooling is in preview, and as such has a lot of gaps. Your issue essentially boil down to 2 problems that we're already planning to address. 

- The .funproj project type is similar to xproj and automatically includes all folders in the root directory. Most customers find this unusual, and we plan to move to a model that is more similar to other project types.
- The .funproj project type is missing many of the features of regular project types, especially project references. This will be fixed and is tracked by this GitHub issue: https://github.com/Azure/Azure-Functions/issues/90

See also this related issue: https://github.com/Azure/Azure-Functions/issues/132
