### ISSUE TITLE
dotnet core function does not run

### ISSUE THREAD

**Issue by abelal83** [Azure/Azure-Functions#1365]
We have a working Azure function app running succesfully in Azure however, we are trying to migrate it into docker and have come across a massive problem with it.

The function app works fine locally in Visual Studio as well as in Azure function app. When we create a dockerised version it simply doesn't work. The only output we get is this

```
Hosting environment: Production
Content root path: /home/site/wwwroot
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

When accessing http://localhost function app runtime reports this
`Function host is not running.`

This is not our first function app that's running in docker, we have dozens running fine but I can't work out why this one fails.

Annoyingly, there is no log to indicate what could be wrong, any help would be much appreciated!

**Comment by bartlomiejzuber** [comment]
@abelal83 what was the issue ? Could you please share the solution ?

**Comment by abelal83** [comment]
Hi @bartlomiejzuber from what I recall it was a config issue in our host.json file. On runtime startup it simply crashed without any useful message.
