### ISSUE TITLE
Visual Studio - Remote Debugging - "The breakpoint is currently won't be hit. No symbols has been loaded for this document"

### ISSUE THREAD

**Issue by ariesmun** [Azure/Azure-Functions#137]
Hi,

I have successfully create and build Functions in VS, and deploy it to the Azure Cloud.  Everything works fine.
Everything seems to be working fine when i do "attach debugger" except the it won't stop at any breakpoints.
The message is : "The breakpoint is currently won't be hit. No symbols has been loaded for this document".

I have tried to load all the symbols, but still no luck with the breakpoints during the remote debugging.
Any idea?

Regards,
Aries

**Comment by lindydonna** [comment]
What kind of function are you trying to debug?  Remote debugging only works for C# functions.

**Comment by ariesmun** [comment]
Just tried it again, it works. Yes, the code is in C#

**Comment by lindydonna** [comment]
Glad to hear the issue is resolved! Remote debugging can be a bit flaky, and sometimes it requires restarting the site or Visual Studio.
