### ISSUE TITLE
v3-preview: Could not load file or assembly 'netstandard, Version=2.1.0.0

### ISSUE THREAD

**Issue by DrBarnabus** [Azure/Azure-Functions#1385]
After updating to Functions v3-preview and upgrading the TargetFramework to netcoreapp3.0 I am getting the following error:

```
Microsoft.NET.Sdk.Functions.Generator.dll "C:\dev\repos\Eruza\CS.Eruza\src\CS.Eruza.Functions.Administrator\bin\Debug\netcoreapp3.0\bin\CS.Eruza.Functions.Administrator.dll " "C:\dev\repos\Eruza\CS.Eruza\src\CS.Eruza.Functions.Administrator\bin\Debug\netcoreapp3.0\ " "False "
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes()
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun()
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Error generating functions metadata
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :
6>    C:\Users\<UserName>\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Metadata generation failed.
6>  Done executing task "GenerateFunctions" -- FAILED.
```

From my understanding, v3-preview should be able to use netcoreapp3.0 and netstandard2.1 so I am unsure why I am getting this error.

**Comment by DrBarnabus** [comment]
I opened this issue in this Repo because I thought this could be an issue with the VS Tooling as its the `icrosoft.NET.Sdk.Functions.Generator.dll` causing the error. But if this is better off being logged somewhere else please let me know and I will close and open it there.

**Comment by DrBarnabus** [comment]
For Reference, the same project still with `<AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>` compiles and runs successfully with functions SDK v1.0.30-beta2.

**Comment by nbalu** [comment]
I have the same issue. If reference exists and linking finds anything that is comming form a standard 2.1 it encounters to the same issue.

We've been using startup + adding extra values to the function which for example gives a bit different error, but the source is the same.

1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeMethodInfo.GetParameters()
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.MethodInfoExtensions.GetDisabled(MethodInfo method)
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.MethodInfoExtensions.HasUnsuportedAttributes(MethodInfo method, String& error)
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.GenerateFunctions(IEnumerable`1 types)+MoveNext()
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun()
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Error generating functions metadata
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :
1>C:\Users\bnagy2\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Metadata generation failed.

**Comment by kevinchatham** [comment]
Same issues for me as well trying to use Microsoft.EntityFrameworkCore & Microsoft.EntityFrameworkCore.Cosmos 3.0.0 with Functions v3-preview.

This thread seems similar in nature so I am leaving it here.

https://github.com/azure/azure-functions-vs-build-sdk/issues/334

**Comment by DrBarnabus** [comment]
This issue appears to be being addressed here: https://github.com/Azure/azure-functions-core-tools/issues/1642

So I am going to close off this issue.
