### ISSUE TITLE
{"Entry point was not found.":""} when referencing own assembly

### ISSUE THREAD

**Issue by skorunka** [Azure/Azure-Functions#140]
Hi,
I have a .Net Core project which is targeting net46:
	"dependencies": {
		"StyleCop.Analyzers": {
			"version": "1.0.0",
			"type": "build"
		},
		"WindowsAzure.ServiceBus": "3.4.4",
		"WindowsAzure.Storage": "8.0.1"
	},
	"frameworks": {
		"net46": {}
	}

The dll is then copied to a Function project bin fulder and referenced like:

#r "bin\myass.dll"

in a Run method, I can create a Instance of a class defined in myass but when I try to call a method, I get:
{"Entry point was not found.":""}
exception.

What does it mean?

**Comment by skorunka** [comment]
Ok, this took me few days to figure out: Azure Functions(as of now) do not wupport NetCore libraries.
So ALL of the DLL libraries you reference(by r#) must be classic cspro Class Libraries, not xproj.

**Comment by lindydonna** [comment]
@skorunka FYI, they can be netstandard libraries, but you're right that they need to be csproj based.
