### ISSUE TITLE
Deploying Azure Functions in Java with Terraform

### ISSUE THREAD

**Issue by riferrei** [Azure/Azure-Functions#1400]
Terraform is an IaC ("Infrastructure-as-Code") tool that allows developers to define immutable infrastructure along with other pieces of the software architecture, such as code. While there is an official provider for Microsoft Azure in Terraform, there are no official examples that would show how to deploy an function written in Java with Terraform.

The example would need to showcase, preferably:

- How to structure the source-code using Maven;
- How to package the source-code (Ex: zip, jar);
- How to upload the source-code to Azure (Ex: Storage containers?)
- How to deploy it using Terraform;
- How to retrieve the generated endpoint for usage;

**Comment by brunoborges** [comment]
// @jeffhollan fyi

**Comment by brandonh-msft** [comment]
Function code is not infra; Terraform isn't built to help you here. Rather, you must do like most DevOps pipelines do and deploy the infra, then use the code platform's method to deploy the code - in separate operations.

In this way, the fact that your code is java matters not; Terraform simply sets up the Azure resources that _hold_ your code. You can see how to do this in Terraform here:

https://github.com/brandonh-msft/azure-functions-terraform

For an example of the whole process, this Azure Samples deploys both terraform & Function code:

https://github.com/Azure-Samples/azure-functions-event-grid-terraform

as well as retrieves the host keys from the Function instance. If you take the function app name (known by terraform), the host key retrieved by Terraform, and the name of the function you deploy (known by your code), you can piece together the resulting Function URL (in the case of HTTP functions)

**Comment by v-anvari** [comment]
closing as resolved
