### ISSUE TITLE
Question about plan differences of Premium and Consumption

### ISSUE THREAD

**Issue by BenjaBobs** [Azure/Azure-Functions#1402]
From [Subscription Service Limits](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#functions-limits) and [Functions Scale Service Limits](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits) I found the following numbers (except the last two derived rows).

Resource | Consumption plan | Premium plan
-- | -- | --
Max instances | 200 | 20
ACU per instance | 100 | 210-840
Max memory (GB per instance) | 1.5 | 3.5-14
||
ACU Total | 20,000 | 4,200-16,800
Max Memory Total (GB) | 300 | 70-280

It seems that if what I'm looking for is just as much scaling and total compute as possible, I'm better off choosing the Consumption Plan than the Premium Plan. Is this the case? Am I missing something?

And if it is the case, are there any plans to increase the limits of the Premium Plan?

Thanks for your time.

**Comment by olitomlinson** [comment]
@BenjaBobs you can now get up to 100 instances in Premium in certain Regions - [Premium Plan GA Announcement](https://azure.microsoft.com/en-us/updates/azure-functions-premium-plan-is-now-generally-available/)

**Comment by BenjaBobs** [comment]
That's great news! I'm unable to find out which regions though. >_>

**Comment by v-anvari** [comment]
[region-max-scale-out](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#region-max-scale-out)
