### ISSUE TITLE
Azure Blob cold start times

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#141]
We should document the cold start for Blob storage being slow for now:
-	When things are warms: blobs processed quickly
-	When cold: up to 10 minute delay

**Comment by lindydonna** [comment]
FYI @SyntaxC4 @christopheranderson  I'm bumping the priority of this up to P0, as I'm seeing lots of customer questions around this. 

@ggailey777 or @rachelappel If you have cycles, this is good low-hanging fruit. The documentation should go in both the Consumption plan article and also the blob trigger one.

**Comment by rachelappel** [comment]
@lindydonna @ggailey777 I'll grab it.

**Comment by lindydonna** [comment]
@rachelappel Awesome!  Please get me or Chris to review.

**Comment by rachelappel** [comment]
@lindydonna @christopheranderson these articles?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale
and
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob

**Comment by lindydonna** [comment]
Yes, and for the blob one you'd want to put it in the trigger section (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#storage-blob-trigger)

**Comment by rachelappel** [comment]
Both articles have been updated.
