### ISSUE TITLE
Blobtrigger A initialized with dev connection string polling queue in Prod storage! +Blobtrigger B not firing

### ISSUE THREAD

**Issue by Syltty** [Azure/Azure-Functions#1411]
Hi,

I have 2 problems here which are maybe related:

1- old blobtrigger using dev storage connection polling something in prod! :/ (azure-webjobs-blobtrigger-\<guid\>)
(Project is using Microsoft.Azure.WebJobs.Extensions.Storage 3.0.10)

2- new blobtrigger B not firing (but registered OK with dev storage connection string on startup)
  (old blobtrigger A is firing OK (1) - I tried with exact same signature and different name and nothing)

Is there some kind of cache somewhere that I should clear?

Thank you!

@LuckyWave27 
https://github.com/Azure/Azure-Functions/issues/1261
Hi, You say "As we know". Could you maybe provide a link where I can get more info please?

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
