### ISSUE TITLE
App Service Auth passes through anonymous requests despite being configured to redirect them to AAD

### ISSUE THREAD

**Issue by waldekmastykarz** [Azure/Azure-Functions#1412]
I have a Function App secured with App Service Auth. It uses the AAD identity provider and is configured to redirect all anonymous calls to AAD. Despite this configuration, anonymous requests are passed on and functions are called anonymously.

The Function App is on v2 runtime. The function itself is built on .netcore 2.2 and published from VS2019. The same code deployed to other Function App, also secured with App Service Auth works as expected.

**Comment by cgillum** [comment]
Hi @waldekmastykarz, are you still observing this issue?

**Comment by waldekmastykarz** [comment]
Not anymore, no. Now, when calling the function, I'm now correctly being prompted to authenticate through AAD. Did anything change on your end?

**Comment by cgillum** [comment]
@waldekmastykarz thanks for confirming. Yes, a change rolled out to a small number of locations that broke authentication for Consumption function apps in certain situations. That change has since been rolled back and the team is working to figure out how exactly this happened.

**Comment by waldekmastykarz** [comment]
Awesome! Appreciate your quick response.
