### ISSUE TITLE
Cold start on Elastic Premium due to slots cache issue

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/Azure-Functions#1416]
There was a bug identified in the platform that rarely a Premium App with slots enabled may scale down pre-warmed instances for a few seconds which could result in a cold start.  
The fix is being applied in the next platform release and is targeted to roll out beginning early next year.

To mitigate that issue, please open a support ticket and ask the support engineer to change the scaling behavior of your function app.

**Comment by kulkarnisonia16** [comment]
@ahmedelnably Can you add some more details of what the call to action for support engineer would be?

**Comment by ahmedelnably** [comment]
There is a configuration at the scale unit level that would change the scaling behavior of the functionapp.

**Comment by jcavell** [comment]
Is it possible for us to configure it ourselves rather than require a support engineer to do it? Is it possible to change the scaling behaviour of the function app appropriately via the CLI?

**Comment by ghclo** [comment]
> The fix is being applied in the next platform release and is targeted to roll out beginning early next year.

@ahmedelnably Thanks. Could you please help to confirm if this fix has already been rolled out?

**Comment by kulkarnisonia16** [comment]
@cgillum - do you know if this is deployed already?

**Comment by cgillum** [comment]
This should be deployed to all public Azure regions. App Service Environments (ASEs) should be done in the next few days. National clouds will come a bit later.

/cc @glennamanns
