### ISSUE TITLE
[Premium] Maximum Maximum Burst

### ISSUE THREAD

**Issue by BenjaBobs** [Azure/Azure-Functions#1418]
**Describe the bug**
In the elastic scale settings the slider for `Maximum Burst` appears to have a maximum of 20, even though the slider goes all the way to 100. Might be related to #1401.

**Expected behavior**
That the `Maximum Burst` can be set to 100.

**Screenshots**
![image](https://user-images.githubusercontent.com/8708965/69803753-3f8ef700-11dd-11ea-8b8e-83ad18cb1a85.png)

**Comment by jeffhollan** [comment]
Can you confirm what region you are seeing this in and the plan type?  Possible the UX is not pulling the correct limit for that region. Limits should reflect this doc here (see footnotes) https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan#regions

**Comment by BenjaBobs** [comment]
North Europe and Premium.

**Comment by jeffhollan** [comment]
Windows / Linux?

**Comment by BenjaBobs** [comment]
Windows I think. I can confirm tomorrow at work.

**Comment by BenjaBobs** [comment]
I can confirm it's windows.

**Comment by jeffhollan** [comment]
Thanks was able to repro and can confirm.  Must be a bug here - I believe 100 instances should be allowed in this region.  Let me file a bug and expect team will be able to patch on Monday.  Hopefully that works ok.  Thanks for reporting

**Comment by BenjaBobs** [comment]
Closing as I just tested and was now able to set the value to 100 successfully.
