### ISSUE TITLE
[Premium] Authorization Levels not being Honoured VNET

### ISSUE THREAD

**Issue by heymega** [Azure/Azure-Functions#1426]
**Describe the bug**
Authorization levels of the function are not being honoured when the function app is connected to a VNET on the premium plan.

**To Reproduce**
1. Create a Function App on a Premium Plan
2. Create an in portal HTTP Trigger Function
3. Set the Authorization Level to Function
4. Connect the Function App to a VNET
5. Hit the HTTP URL of the function WITHOUT the auth code.
6. The function app works without an auth code :(
7. Disconnect the VNET
8. Hit the HTTP URL of the function WITHOUT the auth code
9. 401 Unauthorized response :)

**Expected behavior**
I would expect a 401 unauthorized regardless of whether or not the Function App is connected to a VNET.

**Comment by alexkarcher-msft** [comment]
I'm not able to reproduce this on my side. What version and OS of the runtime are you running and what language are you using?

Also, if you don't mind sharing your application name I'd love to take a look at our logs.

**Comment by heymega** [comment]
Hi Alex 👋 

I don't have the original resource but I've created a new one.

I've managed to reproduce the issue again but it seems to rectify itself after about 30 seconds (after 30 seconds I get a 401 unauthorized). When I originally got the issue it took a lot longer than that (I gave up in the end). 

I'm guessing that changing the Function Level is an asynchronous process and it will take time to resolve.

**Application Name: githubissue1426
Runtime Stack: .Net Core
Operating System: Windows**

I've managed to reproduce the issue again by doing the following...
1. Set the function level to anonymous
2. Attach the function to a vnet
3. Change the function level to Function
4. Hit the endpoint without the auth code
5. You will get a successful response for about 30 seconds after which you'll receive a 401.

I'm guessing this probably isn't an issue and 30 seconds is quite a reasonable time to wait. I think I must have been unlucky at the time and my change took a lot longer to propagate through. 

Does this sound reasonable?

Sorry if I've wasted your time 😊

**Comment by alexkarcher-msft** [comment]
It's odd that it took so long to propagate in the first place, but changing the authorization level requires deploying new code and reloading all of your running processes. Without virtual networks this takes about a second, but ~30 seconds is about in line with what we've been seeing for virtual network connected workers to reattach to their network. Normally you don't see this delay because it's hidden behind pre-warmed workers :)

**Comment by heymega** [comment]
Makes sense! Thank you for the explanation 👍

**Comment by heymega** [comment]
@alexkarcher-msft - Do you happen to know if there would be a ~30-second delay when using Deployment Slots on the Premium Plan, after swapping slots?

**Comment by alexkarcher-msft** [comment]
Yep, I'd consider 30s totally normal for the swap to take place, but you should not see 30 second response times during that time. The staging slot should be warmed up and ready to accept requests before traffic is routed to it.
