### ISSUE TITLE
Clarify authentication requirement for WebHooks

### ISSUE THREAD

**Issue by fabiocav** [Azure/Azure-Functions#143]
`authLevel` does not apply to WebHooks and the authentication is based on the receiver type selected. It would be good to make this clearer in the documentation to avoid confusion.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#keys

**Comment by ciwchris** [comment]
Perhaps using the same text for the genericJson webHookType as the other types would be helpful.

> genericJson: A general purpose webhook endpoint without logic for a specific provider. The authLevel property should not be set if this is chosen.

**Comment by SyntaxC4** [comment]
Add a note which mentions that the AuthLevel does not apply to WebHooks.
