### ISSUE TITLE
[Premium] VNET integration unable to talk to on prem via Azure FW

### ISSUE THREAD

**Issue by jabbera** [Azure/Azure-Functions#1433]
**Describe the bug**

I'm unable to talk to an on-prem resource via an Azure FW and expressroute. Summary from support case 119121121001330:

I have a routing table that should allow all traffic from <vnet> to access <onpremip> via an Azure firewall and our ER. This works fine from the VM deployed in the same vnet (See screenshot 1), but does not work from the function app (screenshot 2). VNET integration is working because I can talk from the function app to the VM that shares a vnet with the function app (screenshot 3). Something is broken between the function app and on prem

**To Reproduce**
It's very complicated. See support case.

**Expected behavior**
Communication to work

**Screenshots**
See support ticket

**Comment by alexkarcher-msft** [comment]
Route tables are currently not supported in the version of Virtual network integration that we use. You can connect using VNET peering or by integrating with a subnet in the network that hosts your expressroute connection.

In our documentation we link to the top level App Service doc on regional VNET integration which lists this as a limitation:

https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet#regional-vnet-integration

**Comment by jabbera** [comment]
What if we switch to appserviceplan instead?

**Comment by jabbera** [comment]
Also, Christina told me at Ignite and in Azure Advisors that route tables for RFC1918 were rolled out in October.

**Comment by alexkarcher-msft** [comment]
Unfortunately we leverage the same networking component as App Service plan, so they share that limitation. 

We're expecting to get route table support from Azure Networking in a few weeks. They found some late breaking bugs and have delayed the feature by a few months.

**Comment by jabbera** [comment]
It really doesn't work when you forget to apply the routing table.... sorry for the spam. All was well once the RT was applied.
