### ISSUE TITLE
Blob Trigger for Azure Functions on Kubernetes with KEDA

### ISSUE THREAD

**Issue by amtandon** [Azure/Azure-Functions#1444]
Do functions deployed to a K8 Cluster with Keda support Blob Triggers?

**Comment by amtandon** [comment]
As off KEDA V1.1, blob trigger functions are supported.

**Comment by jainshikha** [comment]
Hi @amtandon, 
Does the deployment of blob trigger worked for you in KEDA, can you share the sample project with docker file n deployment. Yml file for the same... 
Tried for 3-4 days it's not able to create the hpa for my blob trigger azure function
Thanks in advance.

**Comment by Ashley-alex** [comment]
i tried it out its not working, anyone has deploymnet yml with or with out secrets

**Comment by jainshikha** [comment]
Hi @Ashley-alex,
yes i tried and its working fine.
sharing the sample yml file

`---
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: test
  namespace: default
spec:
  secretTargetRef:
    - parameter: AzureWebJobsStorage
      name: tt-keda-auth
      key: KedaScaler
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: test
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: test
  maxReplicaCount: 10
  triggers:
    - type: azure-blob
      metadata:
        # Required
        blobContainerName: trigger-container-name
        # Optional
        blobCount: "5" # default 5
        blobDelimiter: "/{name}" # Default: "/"
        connection: AzureWebJobsStorage
        path: trigger-container-name/{name}
        name: entry-point
        type: blobTrigger
        direction: in
      authenticationRef:
        name: test `


before creating/registering your application to HPA run/generate the secrets with following:

`kubectl create secret generic tt-keda-auth --from-literal KedaScaler=$AzureWebJobsStorage`

**AzureWebJobsStorage** you storage connction string.

**Comment by Ashley-alex** [comment]
Thank you so much @jainshikha 
Could you also please share the complete yml which also includes the kind:deployment object as well.
Also how we mentioned the secret (setting)  AzureWebJobsStorage in deployment object

Thanks in advance

**Comment by jainshikha** [comment]
attaching the full yml i have used, modify it according to your needs in app setting you can store the a data as shown in yml

`data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsStorage: RGVmYXV==
apiVersion: v1
kind: Secret
metadata:
  name: test-app-name
  namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-name
  namespace: default
  labels:
    app: test-app-name
spec:
  selector:
    matchLabels:
      app: test-app-name
  template:
    metadata:
      labels:
        app: test-app-name
    spec:
      containers:
        - name: test-app-name
          image: shikha/test-app-name
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
            - name: AzureFunctionsJobHost__functions__0
              value: src  #specify the folder where the entry point exists
            - name: PYTHONHTTPSVERIFY
              value: "0"
            - name: AzureWebJobsStorage
              value: "DefaultEndpointsProtocol=****" #provide the connection string for you storage account            
          envFrom:
            - secretRef:
                name: test-app-name
      imagePullSecrets:
        - name: xx # optional
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 10

---

apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: test-app-name
  namespace: default
spec:
  secretTargetRef:
    - parameter: AzureWebJobsStorage
      name: tt-keda-auth
      key: KedaScaler

---

apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: test-app-name
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: test-app-name
  maxReplicaCount: 10
  triggers:
    - type: azure-blob
      metadata:
        # Required
        blobContainerName: trigger-container-name
        # Optional
        blobCount: "5" # default 5
        blobDelimiter: "/{name}" # Default: "/"
        connection: AzureWebJobsStorage
        path: trigger-container-name/{name}
        name: entry-point
        type: blobTrigger
        direction: in
      authenticationRef:
        name: test-app-name  # authenticationRef would need either podIdentity or define a connection parameter

---`

**Comment by Ashley-alex** [comment]
Thanks Jain shikha for sharing the complete deployment.
I was trying with KEDA for blob trigger azure function (.NET), though the pods are scaling but the inside functions didn’t kicked off , not sure what missing
1) do we need to explicitly open any port in our “Deployment” ??
2) Does the Azure function pick the settings (AzureWebJobsStorage) from the “Deployment” say env: -name: AzureWebJobsStorage value: 

when debugging inside docker with in visual studio all is good.

public static void Run(
[BlobTrigger(“samples-containerthree/{name}”,Connection = “AzureWebJobsStorage”)]
Stream myBlob,
string name,

**Comment by Ashley-alex** [comment]
Thanks @jainshikha 
1) Yes "Func start" is working perfect and processing blobs locally
2) Attaching complete yaml. (namepace "tt")
3) How i can share the docker image ? docker 
registery details?

[funckedadeploythree2.txt](https://github.com/Azure/Azure-Functions/files/4771072/funckedadeploythree2.txt)

public static void Run(
[BlobTrigger(“samples-containerthree/{name}”,Connection = “AzureWebJobsStorage”)]
Stream myBlob,
string name,.....

**Comment by Ashley-alex** [comment]
@jainshikha i can see 4 pods are getting created though i have mentioned replicas in my deployment , coudnt scale down as well
Attaching yml,settings (functions.json,host.json,local.settings.json) and program .cs file


[Dockerfile.txt](https://github.com/Azure/Azure-Functions/files/4781922/Dockerfile.txt)
[funcblobtriggerimagethree_cs.txt](https://github.com/Azure/Azure-Functions/files/4781923/funcblobtriggerimagethree_cs.txt)
[function.txt](https://github.com/Azure/Azure-Functions/files/4781924/function.txt)
[host.txt](https://github.com/Azure/Azure-Functions/files/4781925/host.txt)
[local_settings.txt](https://github.com/Azure/Azure-Functions/files/4781926/local_settings.txt)

Thanks in advance

**Comment by Ashley-alex** [comment]
@jainshikha yaml file as well
[Deployfunckedadeploythree2.txt](https://github.com/Azure/Azure-Functions/files/4781955/Deployfunckedadeploythree2.txt)

**Comment by jainshikha** [comment]
@Ashley-alex  try to delete or move the files from your blob it will scale down your pods,
for blob trigger it works in this was, otherwise HPA is unable understand that the blob file is processed or not.

**Comment by Ashley-alex** [comment]
Yes @jainshikha  the pods getting destroyed after the blobs are deleted.
inside functions still not triggered or i didnt see any logs

**Comment by Ashley-alex** [comment]
thanks @jainshikha by any chance you able to take a look? all files are attached

**Comment by lindaxu** [comment]
Hi, @Ashley-alex , have you finally figured out whether blob trigger function could run on Kubernetes or not? I am looking for the similar solution also.  Thanks!

**Comment by Ashley-alex** [comment]
Yes it was working for me
________________________________
