### ISSUE TITLE
[Az CLI] Add support for Node 12

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/Azure-Functions#1447]
Scenarios we care about:

Creation of Node 12 app
Validation that versions match on publishing
When a user upgrades to V3, ensure that their Node versions are compatible

**Comment by ahmedelnably** [comment]
https://github.com/Azure/azure-cli/issues/11364

**Comment by fabiocav** [comment]
@dariagrigoriu @ahmedelnably this will be completed next sprint.

**Comment by fabiocav** [comment]
This is currently in PR here: https://github.com/Azure/azure-cli/pull/11987

**Comment by gzuber** [comment]
PR has been merged
