### ISSUE TITLE
[Az CLI] Add the ability to create v3 function apps

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/Azure-Functions#1448]
Mirror issue for az CLI https://github.com/Azure/azure-cli/issues/11349

**Comment by fabiocav** [comment]
@dariagrigoriu this will be completed on sprint 68.

**Comment by fabiocav** [comment]
This is currently in PR here: https://github.com/Azure/azure-cli/pull/11987

**Comment by gzuber** [comment]
PR has been merged.
