### ISSUE TITLE
InvalidHostServicesException when using AddDataProtection()

### ISSUE THREAD

**Issue by pajzo** [Azure/Azure-Functions#1449]
When I want to start my Azure Functions locally with Visual Studio it gives the following error. But if I compile it and deploy to an Azure Function instance running in Azure it seems to be working.

```
Microsoft.Azure.WebJobs.Script.InvalidHostServicesException: 'The following service registrations did not match the expected services:
  [Invalid] ServiceType: Microsoft.Extensions.Hosting.IHostedService, Lifetime: Singleton, ImplementationType: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService'
```

The problem begin to occur when I added this in my startup:
`services.AddDataProtection()`

Other information:
```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.2" />
  </ItemGroup>
```

Tools:
- Visual Studio Professional 2019 - Version 16.4.2
- Azure Functions Core Tools (3.0.2009 Commit hash: 77395527a4e9c28da8400dcfd1a450f4e0d0c36c)
- Function Runtime Version: 3.0.12930.0

**Comment by Dona278** [comment]
Same issue

**Comment by progs** [comment]
Same issue here, any updates?

**Comment by ranjithsnair** [comment]
Same issue any updates ?

**Comment by progs** [comment]
Found this issue with some more information, but also no solution yet: https://github.com/Azure/azure-functions-host/issues/5447

**Comment by fabiocav** [comment]
Closing as resolved. More information at https://github.com/Azure/azure-functions-host/issues/5447
