### ISSUE TITLE
"connect EACCES" Error when using Azure Storage SDK & Documentation

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/Azure-Functions#145]
The client (node.js / table storage) is unable to establish a connection when running within an Azure Function, it throws the error `EACCES 52.226.8.138:443` (error code 500). 

The only way I'm able to reach Table Storage is through `table` bindings. If this is supposed to be the case, then the only documentation / reference I could find was to `context.bindings.outputTable.push()` all other APIs (if implemented at all) are not documented.

Am I missing on something here? Thanks.

**Comment by 1N50MN14** [comment]
The issue seemed to have been "magically" resolved on its own after few runs (I'm using timer trigger), it would still be good to know what causes this error. I'm relying on `Promise.map` to make concurrent calls, is it possible Azure Functions have some sort of firewall setting that limits the number of outgoing connections?

**Comment by brettsam** [comment]
Yes, there are limitations to the number of connections that can be created from a single function app. On a Consumption site, that limit is 300: https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#per-sandbox-per-appper-site-numerical-limits

**Comment by 1N50MN14** [comment]
@brettsam Thanks for the clarification. According to the link the "Basic+" plan imposes no such limitation, but no such plan exists in the portal when creating a Function App. Where do I find more information about the "Basic+" plan?

**Comment by brettsam** [comment]
If you create a function app with an 'App Service' plan (rather than Consumption), you're able to scale up to the Basic plan. See here for more info: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-plan-options.

Let me know if you still can't find it.

**Comment by 1N50MN14** [comment]
@brettsam Found it, thank you! ;)
