### ISSUE TITLE
Docker on consumption plan

### ISSUE THREAD

**Issue by mslot** [Azure/Azure-Functions#1458]
Reading this: 

1. https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-V2-hosting-options
2. https://github.com/MicrosoftDocs/azure-docs/issues/44083
3. https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale 

Is it correctly understood that:
1. Linux can be run on consumption plan, dynamic scaling works as with Windows. This always runs in a docker container. You can't bring your own docker? I get confused reading this: https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-V2-hosting-options#4--docker-container - "_When running on Linux, you're always running in a Docker Container."_. Does this only apply for Premium, or also consumption running Linux?
2. If you want your own docker image, you have to move to a premium plan. This still provides dynamic scaling

As I read this link: https://azure.microsoft.com/en-us/updates/azure-function-consumption-plan-for-linux-is-now-available/ - and it is the only place which mentions that the Linux engine also uses the dynamic event driven scale. I know it sounds stupid, but I cant read it from the above docs. I cant even read if this only applies to Linux, or if you put docker in the mix, it still applies. I know that running Azure Functions in docker on k8s require KEDA, to scale.

I hope someone will enlighten me!

**Comment by mslot** [comment]
Maybe this is how it should be understood:

1. Linux can be run on consumption plan, dynamic scaling works as with Windows. This always runs in a docker container. You can't bring your own docker
2. If you want your own docker image, you have to move to a premium plan. This still provides dynamic scaling

Local development can be run through docker, and then just the code is deployed to an Azure function running Linux on a consumption plan. 

Am I completely off?

**Comment by Alexabix** [comment]
Is anyone able to shed some light on the questions above? I would also like clarification on how this works.

**Comment by balag0** [comment]
>Linux can be run on consumption plan,  
>>Yes

>dynamic scaling works as with Windows. 
>>Yes

>This always runs in a docker container. 
>>Yes

>You can't bring your own docker? 
>>When running on consumption Linux plans BYOC is not supported. It is only available in Premium or dedicated plans

>I get confused reading this: https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-V2-hosting-options#4--docker-container - "When running on Linux, you're always running in a Docker Container.". Does this only apply for Premium, or also consumption running Linux?
>>Running inside a docker container applies to all Linux skus including consumption / dedicated / premium

>If you want your own docker image, you have to move to a premium plan. This still provides dynamic scaling
>>Yes

**Comment by lrsperanza** [comment]
Azure Container Apps are a new and very good answer to the needs involved in requiring Azure Functions with containers.
