### ISSUE TITLE
Incorrect performance counter values for Linux consumption plan

### ISSUE THREAD

**Issue by mcopik** [Azure/Azure-Functions#1462]
Hi!

I'm trying to understand the performance of my Python function app deployed with Linux consumpion plan. I had no problems with querying logs from app insights to get durations of each invocation, and now I'm trying to find any information on memory consumption of my program. I understand that it's not possible to have this value per each function invocation and I tried to use Azure Monitor web interface. However, after selecting my function app and using few different metrics, I didn't see any data. Almost like my function never executed.

Then I tried to use performance counters, [as suggested by the documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported) and I discovered that my app reports three counters: `% Processor Time`, `% Processor Time Normalized` and `Private Bytes`. However, the value of the last counter is always zero:

![Screenshot from 2020-01-22 02-05-52](https://user-images.githubusercontent.com/720619/72856764-d3e87800-3cbb-11ea-9e77-9e5e1d0a2f92.png)

The first result at 9 PM corresponds to a period of time shortly after one function invocation and before another one. I guess that two others are coming from a warm process that does not execute any requests. For all events I see that memory is reported as zero.

I do have App Insights resourced created and `APPINSIGHTS_INSTRUMENTATIONKEY` is present in my function settings. Furthermore, I can see standard execution logs. Thus, I believe App Insights are properly enabled for my function app.

**Comment by v-bbalaiagar** [comment]
Hi @mcopik , Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
