### ISSUE TITLE
When routing fails because parameters contains slash, there are no logs

### ISSUE THREAD

**Issue by adecr** [Azure/Azure-Functions#1468]
When an HttpTrigger function has route such as "action/{value}" and is called with value containing a urlencoded /slash the function host emits no logs at all to inform of the issue.

Also, the Azure Functions development runtime will accept and work fine so long as slashes are urlencoded.  Some consistent behaviour here would be nice.

I understand that the failure is by design and the workaround is a ruute like "action/{*value}".  Its the lack of any error output and inconsistency in the development runtime that are the issues.

Many thanks

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
