### ISSUE TITLE
System.Data.SqlClient is not supported on this platform when debugging with visual studio

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/Azure-Functions#1473]
I have the application running in azure, its running just fine. When i try to **debug** it, I got the System.Data.SqlClient is not supported in this platform.

Visual Studio 16.4.3
Microsoft.NET.Sdk.Functions v3.0.3
TargetFramework netcoreapp3.1
AzureFunctionsVersion v3

I dont see functions.deps.json, I see {assembly}.deps.json

**Comment by v-bbalaiagar** [comment]
Hi @andrew-vdb, Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue.

**Comment by andrew-vdb** [comment]
I don't use azure functions anymore
