### ISSUE TITLE
[Premium] Multiple Subnets on Single Premium Plan

### ISSUE THREAD

**Issue by heymega** [Azure/Azure-Functions#1474]
**Describe the bug**

If two function apps are sharing the same Premium App Service Plan, then it appears they need to be on the same subnet.

If we try to attach the second function app to a different subnet it fails with a 500 error and eventually times out...

```
2020-01-29T19:07:22.8890627Z ERROR: cli.azure.cli.core.util : request failed: Error occurred in request., 
RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): 
Max retries exceeded with url: /subscriptions/{subscription id removed}/resourceGroups/{name removed}/providers/Microsoft.Web/sites/{func app name removed}/networkConfig/virtualNetwork?api-version=2018-11-01 (Caused by ResponseError('too many 500 error responses',))
```

**To Reproduce**
1. Create a Function App on a Premium Plan
2. Assign this function to a subnet
3. Create another Function App on the same Premium Plan as the first Function App
4. Assign the second Function App to a different subnet.
5. An error is returned

**Expected behavior**
I'd expect to be able to use different subnets for the same Premium App Service Plan.

If this is a limitation of using the premium plan, then it would good if this was explicit in the documentation.

**Comment by alexkarcher-msft** [comment]
Hello, you can currently attach to just one subnet per plan. Since your sites share the same workers we currently do not have a way to restrict traffic to only one virtual interface.

Where were you trying to configure this? It should fail gracefully in all of our tooling.

**Comment by heymega** [comment]
I was doing this directly on the portal and it was timing out.

I also tried this in our build pipeline using the `az functionapp vnet-integration add` command which resulted in a timeout as well.

**Comment by alexkarcher-msft** [comment]
Perfect! That should be enough for us to get those commands returning the correct error messages.

Thanks!

We're still a ways out from actually supporting multiple subnets in the same plan, so I'm going to close this issue. This is a limitation of both Premium and Dedicated, for any future finders of this thread.

**Comment by pradeep-gali-by** [comment]
Hi @alexkarcher-msft - just checking. Is this feature supported now -  supporting multiple subnets in the same plan?

**Comment by gfrankel97** [comment]
Would also like to know if this is supported now. We cannot have network-separated app environments without making an ASP per environment.
