### ISSUE TITLE
Documentation Issue : It isn't clear about which appSetting key to use for StorageAccount

### ISSUE THREAD

**Issue by piyushmutha** [Azure/Azure-Functions#1476]
Documentation isn't clear about which appSettings key to use for an **HTTP** triggered function with **AppService Plan**. 

![image](https://user-images.githubusercontent.com/14413941/73725415-3bbfa980-4725-11ea-9b48-91882e3ed9c6.png)

This states that **AzureWebJobsStorage** should be used for all functions except **HTTP** triggered ones.
(Mine is an HTTP function so can't use this)

![image](https://user-images.githubusercontent.com/14413941/73725576-948f4200-4725-11ea-8c06-0db71586b08b.png)

This states that **WEBSITE_CONTENTAZUREFILECONNECTIONSTRING** should only be used for **Consumption or Premium plans**.
(Mine is an AppService plan so can't use this)

What I tried doing?
- Using **WEBSITE_CONTENTAZUREFILECONNECTIONSTRING** works well but this conflicts with the documentation.

**Comment by v-bbalaiagar** [comment]
Hi @piyushmutha, Apologies for the delayed response. Can we understand if this issue require further triaging or is good to be closed?

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue.
