### ISSUE TITLE
Improvements to Visual Studio tooling

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#148]
This issue is tracking the top features for the Functions Visual Studio tooling to be release quality. I'll create individual issues for bigger items. Folks can suggest items in comments below, and I'll add them to this categorized list.

Note: this list is **not a promise** that these features will actually be implemented, but just tracks the relative priority. :)

## P1 - Visual Studio tooling
- When creating a new Functions project, the IDE should add tooling to fill in required settings like `AzureWebJobsStorage`  
- Connection strings for resources such as Event Hub, Service Bus, etc, should be streamlined as in the Azure Portal
- Support project references #90 
- Support precompiled functions #132 
- Customize the command line for running the CLI (e.g., specify different ports) #88 
- Provide an automated way of pulling down remote connection strings (via equivalent of `func azure functionapp fetch-app-settings`)
- Debugging for F# Functions

## P2 - Visual Studio
- Provide a local test webpage with similar functionality to the **Test** pane and **Run** button in the Azure Portal
- IntelliSense for CSX files
- IntelliSense for FSX files

## P1 - Azure Functions CLI
- Support HTTPS (https://github.com/Azure/azure-functions-cli/issues/20)
- Support Publish via CLI (https://github.com/Azure/azure-functions-cli/issues/8)

**Comment by garrardkitchen** [comment]
Hi @lindydonna, debug for F# functions would be my top request. I don't know whether this is already in the works.  Next it would be better IntelliSense for FSX files. I would also appreciate a greater list of default F# templates to choose from.

Warmest regards,

Garrard.

**Comment by justinyoo** [comment]
@lindydonna In addition to #88 , It would be also good to support to run the debugging on local HTTPS. Here's an issue: https://github.com/Azure/azure-functions-cli/issues/20

**Comment by jsiegmund** [comment]
IntelliSence is a P1 for me, it's THE thing a VS developer just expects to work. First thing I noticed as being absent. Furthermore it would be nice to have Reference support for things like NuGet, NPM along with external projects or DLLs. In general, developer productivity should be high on the list imho :)

**Comment by lindydonna** [comment]
@jsiegmund If you have regular class libraries and .cs files and full IntelliSense, is CSX IntelliSense still a P1?

**Comment by cmatskas** [comment]
@lindydonna @jsiegmund if people are still heavily invested in .csx based functions, then I would like to see Intellisense in there as well as a P1. Do you guys have any telemetry on what's more popular right now maybe with a small insight into the future projections to help make a decision?

Things I would really like to see are:
- HTTPS support in the CLI
- Merge the Azure Functions CLI and the Azure CLI. This is a **P1** for me

**Comment by atrauzzi** [comment]
Everything we've talked about so far. I'll gladly re-summarize here if needed.

**Comment by atrauzzi** [comment]
- Linux support for the CLI

**Comment by andresnava** [comment]
When adding a connection to a Service Bus queue, I believe it has to be a connection to the Service Bus and then we specify which queue to listen on.

I would feel more comfortable having the connection to the queue, instead of to the Service Bus so we can limit what the connection has access to.

**Comment by lindydonna** [comment]
@andresnava That would actually be a feature request for the underlying Functions Host, rather than the tooling for it. Could you file a feature request here (https://github.com/Azure/azure-webjobs-sdk-script) and provide the exact functionality that you are looking for?

**Comment by lindydonna** [comment]
@atrauzzi Linux/Mac support for the CLI is already in progress. It's not strictly related to this item, since this is about Visual Studio on Windows.

**Comment by dtriana** [comment]
Hi @lindydonna. About authentication, specifically AzureAD B2B, it works when done in the portal but not locally. In the portal we have the UI to set all the configuration needed but locally there seems to be no way to configure it, which makes the local development process very time consuming, having to deploy every time to test. Am I missing something? is this something that can be enabled locally in any way? Thanks.

**Comment by lindydonna** [comment]
@dtriana No, authentication/authorization is only available when running on the port. You might be able to fake something with Fiddler, but I don't have any experience with that.

**Comment by TclasenITVT** [comment]
Why can we only publish our functions with an app service plan instead of the consumption plan using Visual Studio 2017 15.4.2?

**Comment by ColbyTresness** [comment]
I'm closing this since it's stale and in general we want to track these individually.
