### ISSUE TITLE
HttpClientFactory works remotely, but not when deployed

### ISSUE THREAD

**Issue by gdodd1977** [Azure/Azure-Functions#1480]
I've converted a function app to use HttpClientFactory. When I run it locally, it works fine. When we deploy it to our azure app, we get the following error:

No service for type 'Microsoft.Extensions.Http.DefaultHttpClientFactory' has been registered.

Why would this work when running locally but not work in Azure?

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue.
