### ISSUE TITLE
Python Azure Function Remote App publish error

### ISSUE THREAD

**Issue by Godase** [Azure/Azure-Functions#1482]
Whenever I am trying to publish Azure Function for Python app on Azure Function then I got the below error:-
command:- `func azure functionapp <Function Name> --Python` 
![image](https://user-images.githubusercontent.com/25449649/74085733-330f0080-4aa2-11ea-80f8-f3c2e3229012.png)

But whenever I am trying it on local using `func host start` then it works.
Is there any way to resolve the above issue?

**Comment by v-anvari** [comment]
Hi @Godase , Closing this issue as there is no further activity. Please open a new issue here for any issue related to python worker
https://github.com/Azure/azure-functions-python-worker
