### ISSUE TITLE
func pack fails to create zip file with relevant content

### ISSUE THREAD

**Issue by FlippieCoetser** [Azure/Azure-Functions#1483]
**Before:** 
Given Windows 10
Given Visual Studio Code version 1.42.0
Given Azure Function Extension version **2.7.1948**
When running `func pack` 
Then a Zip file **with relevant content** gets created.

**Action:** Update VS Code Extention:

**After:**
Given Windows 10
Given Visual Studio Code version 1.42.0
Given Azure Function Extension version **2.7.2100**
When running `func pack` 
Then an **empty** Zip file gets created.

**Comment by v-anvari** [comment]
Hi @FlippieCoetser , Apologies for the delayed response, I was unable to reproduce it with latest version following the document here - https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions

https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs-code?tabs=csharp

If you are still seeing this scenario, please open a new issue.
