### ISSUE TITLE
azure functions local debugging dosent work with vscode when node installed using nvm 

### ISSUE THREAD

**Issue by chauhansachinkr** [Azure/Azure-Functions#1488]
Tasks dosent find the npm installed using nvm 

Terminal out
-------------
> Executing task: npm install <
/bin/bash: npm: command not found
The terminal process terminated with exit code: 127
Terminal will be reused by tasks, press any key to close it.

Env details 
-------------
vscode details :
=============
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

OS details :
=============
MacOS mojave 10.14.6 

Node details
==========
node installed via nvm 
/Users/xxxxxxx/.nvm/versions/node/v12.16.0/bin/node

**Comment by aronchick** [comment]
+1 on this issue.

VScode:
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

OS:
Linux 5.4.0-1026-azure #26-Ubuntu SMP Thu Sep 10 13:17:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Node:
❯ which node
/home/user/.nvm/versions/node/v12.18.3/bin/node

Launch.json
    {
      "name": "Attach to .NET Functions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureFunctions.pickProcess}"
    }

**Comment by v-bbalaiagar** [comment]
Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue.
