### ISSUE TITLE
Update System.Configuration.ConfigurationManager.Appsettings property to read appsettings.json

### ISSUE THREAD

**Issue by jimt4593** [Azure/Azure-Functions#149]
Right now, the only way to read appsettings, stored is apsettings.json, is from the environment.  My Azure Function uses assemblies that user ConfigurationManager.AppSettings to read app setting values.  These assemblies are also used by Azure web apps and web apps that still run on web servers running on premise.    

I do not want to have to update these assemblies to  access app settings in 2 ways. Using ConfigurationManager. AppSettings first.  Then, if not found, using Envirorment.GetEnviromentVariable.  I'd like to requst that ConfigurationManager.Appsettings be updated to read values from the application.json file.

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-functions-cli#33
