### ISSUE TITLE
Exception 'The 'Id' property of a CosmosDB single-item input binding cannot be null or empty.' when trying to post to Azure / Cosmos DB

### ISSUE THREAD

**Issue by vbrodsky** [Azure/Azure-Functions#1495]
I am using python 3.7 / v2 function run-time and I have build a simple REST resource that uses an Azure function to create / update / read a simple document in CosmosDB. This resource supports a POST without an uuid to create a new document, POST with a uuid to update an existing document and GET with a UUID to retrieve a document.
functions.json:
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ],
      "route":"thingpage/{id?}"
    },
    {
      "type": "cosmosDB",
      "direction": "out",
      "name": "docWriter",
      "databaseName": "thing_book",
      "collectionName": "ThingPages",
      "createIfNotExists": "false",
      "connectionStringSetting": "AzureCosmosDBConnectionString"
    },
    {
      "type": "cosmosDB",
      "name": "docReader",
      "direction": "in",
      "databaseName": "thing_book",
      "collectionName": "ThingPages",
      "id" : "{id}",
      "PartitionKey": "{id}",
      "connectionStringSetting": "AzureCosmosDBConnectionString"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

python function declaration:
```
def main(req: func.HttpRequest, docReader: func.DocumentList,  docWriter: func.Out[func.Document]) -> func.HttpResponse:
```

All works fine EXCEPT when I invoke a POST WITHOUT a UUID, I get the following exception:
_System.Private.CoreLib: Exception while executing function: Functions.thingpage. Microsoft.Azure.WebJobs.Extensions.CosmosDB: The 'Id' property of a CosmosDB single-item input binding cannot be null or empty._

I understand this exception is not coming from your azure-functions package, but from the runtime. I think it is trying to instantiate the docReader object and throws an exception since the id is missing. It is confusing I can not handle this kind of an exception in my code because it happens BEFORE the function invocation. I have found a workaround to pass in a fake uui when I invoke a POST to create a new document.

Any better ideas?

**Comment by v-bbalaiagar** [comment]
Hi @vbrodsky, Since its an year old issue, can you confirm if this issue needs to be closed or requires a Triage.

**Comment by vbrodsky** [comment]
Sure close it

**Comment by v-bbalaiagar** [comment]
Thank you for the update. Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
