### ISSUE TITLE
Azure Functions CLI - Local Dev Updates

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#15]
Replace the existing article: https://azure.microsoft.com/en-us/documentation/articles/functions-run-local 

See CLI readme here: https://github.com/Azure/azure-functions-cli/blob/master/README.md

**Comment by lindydonna** [comment]
Will include Visual Studio tooling. I'll author the content and will just ask others for review.

**Comment by SyntaxC4** [comment]
@lindydonna - When do you think we'll have updates for the CLI so we can work on this item?

**Comment by lindydonna** [comment]
Other work is currently displacing this, will be at least 2 weeks before I have something to share.

**Comment by ggailey777** [comment]
Just so that I am clear.  We can use this CLI to work with functions in an existing Function App, but it can't be used to create a new function app instance? Do we have any CLI support for creating a new function app?

**Comment by lindydonna** [comment]
We don't currently have any CLI support for creating a new Function App, but we will add support to the Azure CLI 2.0. The Functions CLI will be renamed to Azure Functions Core Tools, since it's more about local development and deployment, rather than resource management. Timeline for the rename is TBD.

**Comment by lindydonna** [comment]
@ggailey777 Also here's a blog post that walks through some of the commands: https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/

**Comment by ggailey777** [comment]
@lindydonna two questions 1) are we now calling the Functions "CLI" "Azure Functions core tools?" 2) Do we want to show both VS and  VSCode + core tools in the local dev topic?

**Comment by lindydonna** [comment]
@ggailey777 We're going to rename it in the next release, see https://github.com/Azure/azure-functions-cli/issues/92

I think we should have one topic that just explains the command-line by itself. Then, we can have a topic that specifically talks about debugging that has VS Code and VS. 

The VS tooling is going to substantially change in the next release, so we should only cover debugging IMO.

**Comment by lindydonna** [comment]
Article is published: https://azure.microsoft.com/en-us/documentation/articles/functions-run-local
