### ISSUE TITLE
[CLI] Azure CLI needs to use Stacks API configuration templates for new functions apps

### ISSUE THREAD

**Issue by gzuber** [Azure/Azure-Functions#1503]
This is something that should be available in ANT87.

We now have an API where we can get a JSON that contains configuration info for new functions apps. We need to use this to validate/configure apps in `az functionapp create`

**Comment by gzuber** [comment]
cc @pragnagopa -- I don't think we had made a tracking issue for CLI yet

**Comment by fabiocav** [comment]
@anthonychu FYI - moving this back to `Triaged` for now.

**Comment by gzuber** [comment]
@Francisco-Gamino wouldn't that be taken care of when we change to using the Stacks API? Is there something we would need to do different for powershell specifically or are these properties in the Stacks API?

**Comment by Francisco-Gamino** [comment]
@gzuber -- yes, the Stacks API should take care of it. All the information you need is already included in https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/blob/master/WindowsFunctionsStacks.json

**Comment by gzuber** [comment]
Mirror issue in CLI: https://github.com/Azure/azure-cli/issues/14061

**Comment by fabiocav** [comment]
Leaving this in sprint 78. Work is complete and should be merged following the CLI release cadence

**Comment by anthonychu** [comment]
@apawast FYI

**Comment by gzuber** [comment]
Closed by https://github.com/Azure/azure-cli/pull/14063
