### ISSUE TITLE
[Premium] Is pre-warm instance free ?

### ISSUE THREAD

**Issue by qcnguyen** [Azure/Azure-Functions#1505]
hi team, please help me to estimate cost when moving to azure function premium plan.
I have an scenario that need you help to answer, so I can understand more about billing mechanism:
- if I setup 1 instance at minimum scale setting, and 1 prewarm instance. let's say my app don't have much consumer, so it doesn't need to scale out. So if that the case, how much do I pay for 1 month, 1 instance, or 2 instance ? If I pay 1 instance, does that mean pre-warm instance is free ?
Thank team.

**Comment by alexkarcher-msft** [comment]
Hi @qcnguyen , 

Good question!

Short answer is yes, your min instance will be used to pre-warm your site, and you'll pay for 1 instance running 24x7 while idle.

Think of your pre-warmed count like a buffer above your site's required number of workers. So, when you're in the idle state your site requires 0 workers, but you keep one pre-warmed 24/7. 

Your minimum worker count is held at a plan level, and just provides a dedicated pool of workers for your sites to pull from. This hedges you against the noisy neighbor problem, and you can ensure that your site will never be blocked from scaling out within that min-plan size, even when experiencing resource limitations.
