### ISSUE TITLE
[UX] - incorrect file content in App Files 

### ISSUE THREAD

**Issue by omiossec** [Azure/Azure-Functions#1506]
# Issue Title
[UX] - incorrect file content in App Files 
## Description

Browsing file in the App Files menu don't work with certain file Type 
It the function app contain a file named extensions.csproj nothing happen

- Include Screenshots if possible
   - make sure to include the whole browser window we need to so see the issue in context.
![image](https://user-images.githubusercontent.com/14043056/75453712-9dfe7980-5974-11ea-87e1-f102fa10837b.png)

- Include a network trace  
   - See how to capture a network trace below.
- Include any browser console errors if present
![image](https://user-images.githubusercontent.com/14043056/75453797-be2e3880-5974-11ea-900c-02cb00cec21e.png)

**Comment by btardif** [comment]
@takyyon can you take a look?

The expectation here is that if a file shows up in the dropdown it should render in the code editor.

not sure why we got a 404 on that one.

**Comment by takyyon** [comment]
Looking into this.

**Comment by takyyon** [comment]
We are getting `extensions.csproj` in the list of files in the folder, but for some reason while fetching the content it returns 404. @btardif Can we transfer this bug to the api team please?

Also, 404 is occurring only for `.csproj` file type

**Comment by btardif** [comment]
hey @mathewc can you take a look? I believe @takyyon already gave you context on this one.

**Comment by mathewc** [comment]
Guys - I recommend you create an issue in the functions runtime repo https://github.com/Azure/azure-functions-host/issues for this so it can be triaged and assigned out.

**Comment by takyyon** [comment]
Created an issue on the repo mentioned - https://github.com/Azure/azure-functions-host/issues/5744

**Comment by btardif** [comment]
@takyyon I think this issues can be closed given we have underlying fix coming from runtime.
