### ISSUE TITLE
How to run Time Binding functions synchronously? 

### ISSUE THREAD

**Issue by skorunka** [Azure/Azure-Functions#151]
Can I configure Timer functions to run synchronously? So, another "tick" does not occur unless the previous one was finished.

**Comment by skorunka** [comment]
Is this possible?

**Comment by lindydonna** [comment]
You'll probably get a faster answer on StackOverflow or the MSDN forums, but I'll see if an expert can answer here.

**Comment by mathewc** [comment]
Let me understand what you're trying to accomplish. You want to ensure that your timer function only ever runs a single instance at a time? That's how it already works. Are you seeing differently?

**Comment by skorunka** [comment]
@mathewc Lets say you set timer trigger to execute function every 5 seconds. If the function takes 7 seconds to finish, will be another instance fired after 5 seconds of execution of the 1st one? If I put a debugger in a function a can see a multiple instances are executed, maybe this only happens on local host and debug. Do you know what I mean?

**Comment by lindydonna** [comment]
@skorunka For this kind of behavior, we recommend manually scheduling the work using a combination of queue trigger and timer trigger. You could have a queue message that controls whether or not the next timer should start or delay.

**Comment by thuansoldier** [comment]
@lindydonna could you please suggest on how to combine both Timer and Queue Trigger? Thank you!
