### ISSUE TITLE
[UX] - Integration pane shows trigger as output

### ISSUE THREAD

**Issue by MarkXA** [Azure/Azure-Functions#1510]
When navigating to the Integration pane of a function in the new portal UX, triggers are being listed in the outputs box.

Screenshot and network trace are attached.

[Functions UX issue.zip](https://github.com/Azure/Azure-Functions/files/4270897/Functions.UX.issue.zip)

**Comment by btardif** [comment]
Thanks for the bug @MarkXA 

@ammanifold can you take a look?

**Comment by ammanifold** [comment]
Thanks @MarkXA and @btardif 

@refortie can you help take a look?

**Comment by refortie** [comment]
The binding in question is missing the required direction property. If you add the "in" direction it will be displayed correctly. I've added a bug to handle this situation more gracefully

**Comment by MarkXA** [comment]
FYI that one was actually generated by a Functions v1 C# TimerTrigger attribute, so it's the tooling that left out the direction.

**Comment by btardif** [comment]
@fabiocav looks like there might be a bug in functions V1 tooling as called out by @MarkXA  where the direction of the binding is not being included. Who can take a look at that?

**Comment by btardif** [comment]
@MarkXA we have a UX fix that will provide a warning when a binding is missing direction.

@refortie can you attach a screenshot of the proposed solution. I think we can close this out with that.

**Comment by refortie** [comment]
![image](https://user-images.githubusercontent.com/37600290/76452444-60dfb180-638e-11ea-909b-99035b598563.png)
