### ISSUE TITLE
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Did not find functions with language [python].

### ISSUE THREAD

**Issue by erwinsalubre** [Azure/Azure-Functions#1511]
I have created a Python Queue Trigger function that runs successful locally but a bit finicky when deployed through VS code.  It runs initially then sometimes lost its grip and breaks.

I created a deployment for the function using terraform over Gitlab with the code below.

```
resource "azurerm_function_app" "function" {
  depends_on                = [data.azurerm_storage_account_sas.storage_sas]
  app_service_plan_id       = azurerm_app_service_plan.plan.id
  location                  = azurerm_resource_group.eventgridrg.location
  name                      = "func-apps"
  resource_group_name       = azurerm_resource_group.eventgridrg.name
  storage_connection_string = azurerm_storage_account.storage_account.primary_connection_string
  version                   = "~2"

    app_settings = {
      https_only                            = true
      FUNCTIONS_WORKER_RUNTIME              = "python"
      AzureWebJobsStorage                   = azurerm_storage_account.storage_account.primary_connection_string
      CleanupPackerImagesConnection         = var.function_storage_connection_string
      FUNCTIONS_EXTENSION_VERSION           = "~2"
      FUNCTION_APP_EDIT_MODE                = "readonly"
      HASH                                  = base64encode(filesha256("${var.function_name}.zip"))
      WEBSITE_RUN_FROM_PACKAGE              = "${azurerm_storage_blob.storage_blob.url}${data.azurerm_storage_account_sas.storage_sas.sas}"
    }
}
```
The function gets deployed and I am able to see the codes in read-only mode but getting the error below and the function url is not running.

```Error:

The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Did not find functions with language [python].
Session Id: 0ebad842dbfc426e8ac26ba7a1219f11

Timestamp: 2020-03-02T03:46:59.477Z
```

**Comment by FirstInternetUser** [comment]
Is there any update as to why this is occurring? I am getting the same issue when deploying using the serverless framework.

**Comment by Josh-a-e** [comment]
If it's of any use, I found my deployed functions got a lot more reliable when I changed `FUNCTIONS_EXTENSION_VERSION` from `~2` to `~3`

**Comment by FirstInternetUser** [comment]
@Josh-a-e how do you do this?

**Comment by ParasDoshi** [comment]
Had the same issue when deploying from azure-pipelines was anybody able to find a way around this

**Comment by ParasDoshi** [comment]
I think you may wanna rebuild the service plan to be linux. That might work

**Comment by davidweterings** [comment]
We're seeing this issue too. Destroying the functionapp and recreating it with the same name also doesn't work reliably.

**Comment by donghwicha** [comment]
I experienced the same error but changing to linux made it work. Too bad that this kind of basics are not included in the document.

**Comment by epapineau** [comment]
I'm also experiencing this issue when deploying from VS Code - has there been any resolution? We're using `~3`, able to successfully run the function locally. When I deploy, we get Microsoft.Azure.WebJobs.Script.HostInitializationException : Did not find functions with language [python].  I have verified the `FUNCTIONS_WORKER_RUNTIME` is set to python

**Comment by v-bbalaiagar** [comment]
We apologize for the delayed response, were you able to find a solution to this problem. Can you let us know if this scenario is still seen.

**Comment by v-maudan** [comment]
> We apologize for the delayed response, were you able to find a solution to this problem. Can you let us know if this scenario is still seen.

@v-bbalaiagar , Yes , we are facing same issue. Thanks!

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue

**Comment by wtfiwtz** [comment]
Q: Will Windows support `python`, or will Linux Functions support Python logging (that isn't broken)? 
Catch-22.

... and then Azure Function references just randomly seem to stop working 🤷 

(**EDIT**: seems to be a limitation of KeyVault resources in Terraform / CDKTF - `az functionapp update  ... --set keyVaultReferenceIdentity=${identityResourceId}` manually run)
