### ISSUE TITLE
Azure Functions at portal: Unable to load DLL 'sni.dll' or one of its dependencies:

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure/Azure-Functions#1513]
Trying to run Azure function from portal with above error. I've documented error at stackoverflow: https://stackoverflow.com/questions/60518486/azure-functions-unable-to-load-dll-sni-dll-or-one-of-its-dependencies-the-sp
Help really appreciated, thank you

**Comment by v-bbalaiagar** [comment]
Hi @sergiosolorzano, Since its an year old issue, Can you confirm if this issue needs to be closed or requires a Triage.

**Comment by sergiosolorzano** [comment]
solved in the stackoverflow url above
