### ISSUE TITLE
RBAC Permission: microsoft.web/sites/hostruntime/host/_master cant be added to Custom Role

### ISSUE THREAD

**Issue by riangiddings** [Azure/Azure-Functions#1516]
When I attempt to create a custom role for a subscription that contains a grouped and deployed Azure Function App resource, upon adding the microsoft.web/sites/hostruntime/host/_master permission to the Custom Role JSON object, I am met with the following error:

![image](https://user-images.githubusercontent.com/12454860/75917917-c7158300-5e28-11ea-8152-b159b080d80d.png)

I am wondering if this is intended to prevent unintentional changes specific to this permission, or if this is a possible bug related to parsing rules around the name of a permission during creation of the role.

I understand this permission grants read access to sensitive data, so I could see how this could have been intentionally named with an underscore to prevent Custom Role configuration.

Any insight would be much appreciated, thanks!

**Comment by v-bbalaiagar** [comment]
Hi @riangiddings,  Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required. I shall follow with the right team members to resolve this issue. The issue was somehow lost in the trace.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
