### ISSUE TITLE
2x applications insights configuration settings added.

### ISSUE THREAD

**Issue by PatrickFroberg** [Azure/Azure-Functions#1519]
Hey

When deploying a new azure function on azure I get 2x applications insights configuration settings added? It used just to be one and the values are almost the same, it looks alot like something new and old is used at the same time :)

Enable Application Insights:
![image](https://user-images.githubusercontent.com/14177527/76200125-5cca5d00-61f1-11ea-947f-2f1d7f482fe8.png)

The double configuration settings (Used just to be the "APPINSIGHTS_INSTRUMENTATIONKEY"):

![image](https://user-images.githubusercontent.com/14177527/76746532-f5278b00-6777-11ea-9c39-7f65116f52ca.png)

![settings](https://user-images.githubusercontent.com/14177527/76746447-ce695480-6777-11ea-96f7-2c08892d3ab4.png)

**Comment by mhazelwood** [comment]
@PatrickFroberg You should just use one or the other. 

> We don't recommend setting both Connection String and Instrumentation key. In the event that a user does set both, whichever was set last will take precedence.

https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string

**Comment by PatrickFroberg** [comment]
That's the whole issue i don't set anything other than telling it to use "Application Insights" (I'm using the "Add" function form).
The json is generated by following the form :)
![appinsights](https://user-images.githubusercontent.com/14177527/76743524-0d48db80-6773-11ea-8b0f-62540284ba27.gif)

**Comment by PatrickFroberg** [comment]
Here is a gif, had to cut it to remove some values.
Hope it helps explaining my issue :)

![appinsights](https://user-images.githubusercontent.com/14177527/76745578-66663e80-6776-11ea-9843-4a176ebb4767.gif)

**Comment by v-bbalaiagar** [comment]
Hi @PatrickFroberg,  Apologies for the delayed response, Can we know if you were able to find a solution, are you still seeing this issue. The issue was somehow lost in the trace.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
