### ISSUE TITLE
Document Script experience

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#152]
For the various languages which use the scripting experience, which are still in preview, we should document how they work.

This should include some language specific info as well, such as:
1. Which version do I have and can I change it? (ie. Python/PowerShell version)
2. Package/dependency management

**Comment by SyntaxC4** [comment]
For the current versions, let's have a matrix, like the one below.

| Language | Version |
|---|---|
| Python | 2.7, 3.4|
| PowerShell | |
| Node.js | 10.0 |

As for the "How do I change it", we should include a list of properties which need to be changed for the Function Host to pick it up. These are typically set in App Settings.

**Comment by tdykstra** [comment]
We could add a column for available version(s) to the [languages table in the languages doc](https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages#languages-in-runtime-1x-and-2x). Possibly include footnotes for brief how-to-set-version instructions.

**Comment by ColbyTresness** [comment]
I don't think this is relevant anymore - if anyone protests I'll reopen.
