### ISSUE TITLE
HttpTrigger returns 0 result code.

### ISSUE THREAD

**Issue by vbondaryuk** [Azure/Azure-Functions#1522]
We have a function which called from the ADF pipelines by http, it works correctly, but from time to time, function **returns code 0** and our pipeline failed with exception:

> 502 - Web server received an invalid response while acting as a gateway or proxy server.

But from Function -> Monitor and AppInsight we can see, that function finished successfully
![image](https://user-images.githubusercontent.com/5966463/76418564-e6c02480-63af-11ea-98f1-9ae777c70374.png)

![image](https://user-images.githubusercontent.com/5966463/76418105-17ec2500-63af-11ea-8132-080def597153.png)

What is the reason for that behavior?
How can we handle it except retry logic?

net. core 2.1
sdkVersion: 2.0.13017.0

**Comment by v-bbalaiagar** [comment]
Hi @vbondaryuk, Kindly let us know if this issue is still persisting, or are we good to close the issue.

**Comment by v-bbalaiagar** [comment]
Hi @vbondaryuk, Closing this issue as the required information is provided[ here](https://github.com/Azure/azure-functions-host/issues/5813), please feel free to reach back to us in case of any further queries related to this issue.
