### ISSUE TITLE
Azure Functions are triggered whenever logged in function app manually instead of time trigger

### ISSUE THREAD

**Issue by vefae** [Azure/Azure-Functions#1527]
Hi there, I have a time triggered Azure Function (Consumption plan). It is scheduled to run every day 5:30 AM ( "0 30 5 * * *") 
It used to work OK for sometime, since last three days it stopped following the schedule. 
I have a habit of checking the logs every day and I realized that instead of following the timer, it starts running whenever I go to the functions app. 
I saw some previous issue with local timing, related settings are:
WEBSITE_TIME_ZONE = W. Europe Standard Time
WEBSITE_USE_PLACEHOLDER = 0
I am going to remove these two to check if these are the reasons. 

Any other ideas maybe?

**Comment by vefae** [comment]
As I suggested in my question, I removed WEBSITE_TIME_ZONE and WEBSITE_USE_PLACEHOLDER app settings and trigger started to work properly. But I lost my local time information. I think there is a bug when you use these two settings.

**Comment by 23min** [comment]
I experience a similar thing.

It seems like a timer isn't fired (scheduled) if the function app hasn't warmed up for the day.
As soon as I use the app (i.e. wake the app, I don't even have to use the portal), the timer fires even though it was due the day before.

**Comment by anthonychu** [comment]
@23min can you please share your function app info as described here? https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by 23min** [comment]
@anthonychu Is `InvocationId` in a `Trigger details` trace the same as `Execution Id`?

Region: North Europe
Timestamp: 2021-03-16T15:21:27.4791174Z
Invoication Id: e5add596-6142-4712-bac5-d950924342b1

This morning I opened our site which calls an API on the functions app. This triggered a function that was scheduled for last Friday 16:45 UTC.

**Comment by 23min** [comment]
Is there any news on this? This should be fairly easy to replicate. 
This is causing us a lot of headaches and lost productivity.

**Comment by simenhagelid** [comment]
Not sure if it is related, but I have been running timer triggered functions in consumption plan, both Windows and Linux. After a while, only the Linux functions continue to trigger.

**Comment by v-bbalaiagar** [comment]
Hi @anthonychu, Can you kindly look into this.

**Comment by v-bbalaiagar** [comment]
Apologies for the delayed response, Were you able to find a solution. Let us know if you are still seeing this issue. if yes please provide us the latest invocation id, time stamp and region so that we can follow up with the team.

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
