### ISSUE TITLE
[UX] - wrong graph in Integration menu

### ISSUE THREAD

**Issue by buchizo** [Azure/Azure-Functions#1528]
# wrong graph in Integration menu

## Description

Trigger and Output object of graph is wrong in Integration menu.

For example:

- Using EventHubTrigger
    - EventHub doesn't displayed in trigger graph object.
    - But EventHub wrong displayed in output graph object.
- Using HttpTrigger
    - Http (req) doesn't displayed in trigger graph object.

![image](https://user-images.githubusercontent.com/1254213/76652610-48e47980-65aa-11ea-97f2-e22937c96e0e.png)

### sample code

1. create new v3 function app using C#
1. add EventHub Trigger as follows:

```csharp
[FunctionName("Example")]
public async Task Run([EventHubTrigger("%EventHubName%", Connection = "EventHubsConnection")] EventData eventData, ILogger log)
{
}
```

3. deploy to Azure using RunFromPackage

**Comment by btardif** [comment]
@refortie can you take a look? is this similar to #1510

**Comment by refortie** [comment]
It looks to be exactly the same issue. I can repro it locally. The templates that VS code are using don't appear to have the direction in the bindings that it generates.

**Comment by btardif** [comment]
@fabiocav and @jeffhollan need your input here since this looks like a bug in VSCode the the templates being used there.

CC: @fiveisprime

**Comment by btardif** [comment]
@jeffhollan we got another hit: see #1581

**Comment by Camios** [comment]
@btardif it also affects Visual Studio Enterprise 2019 v16.5. So what ever means of creating the function.json has the bug (AzureFunctionsTools CLI? or SDK?).

**Comment by btardif** [comment]
@refortie can you provide an update on this WI based on ongoing conversations? I think we have a short term mitigation and a longer range plan. I think it would be good to share details here.

**Comment by refortie** [comment]
We've identified that that SDK doesn't generate some of the information that the portal UI expects. We are putting in some better logic to handle triggers and clearer information stating that inputs and outputs won't be visible in the portal for the time being.

**Comment by vllama** [comment]
Using TimerTrigger functions also causes this issue:

> The following bindings are missing the required direction property and may have been placed incorrectly: generatorFunctionTimer. Please update the bindings in your functions.json file.Learn more

**Comment by btardif** [comment]
We have a design and are working through this to group bindings missing directions in the UX

CC: @refortie

**Comment by refortie** [comment]
For issues involving the SDK and misplaced bindings, we've deployed a fix. For bindings in general that are missing their direction we will be adding a new field to display them.
