### ISSUE TITLE
[azure-cli] az functionapp create should change LinuxFxVersion for dotnet

### ISSUE THREAD

**Issue by gzuber** [Azure/Azure-Functions#1529]
Mirror for https://github.com/Azure/azure-cli/issues/12577

Copying description here:
"For dotnet, the setting needs to be empty, rather than `Dotnet`. Setting it to `Dotnet` is not recommended and will fail to create on Linux Consumption.

We should set it to empty string for all skus for consistency."

**Comment by fabiocav** [comment]
Currently in PR for CLI. Leaving in sprint 72.

**Comment by gzuber** [comment]
Resolved by https://github.com/Azure/azure-cli/pull/12817
