### ISSUE TITLE
[UX] - Unable to test run non-HTTP triggered functions

### ISSUE THREAD

**Issue by jbeeko** [Azure/Azure-Functions#1530]
# Unable to test run non-HTTP triggered functions

## Description

In the current version of the functions portal it is possible test run functions of all kinds. This is useful in a number of scenarios. 

### Utility functions
For example this feature allows for `manualTrigger` functions that can take parameters. We have a suite of these that are used for various system maintenance tasks (in a more traditional environment these might exist as a set of command line utilities). For example see the one below which takes as a parameter if it should be run in log-only mode or live. if run in log-only mode it just logs what it will do, otherwise it does it. 

Here is a skeleton of the function (apologies for the F#, I don't know C#):
```
module CleanUpDB =
    [<FunctionName("utils-CleanUpDB")>]
    [<NoAutomaticTrigger>]

    type Params = {
        LogOnly: bool
    }
    let run (input: string, iLog: ILogger, context: ExecutionContext) =
        let log = Logger.getLogger iLog context.FunctionName context.InvocationId
        let param = deserialize<Params> input
        if param.LogOnly
        then log.Info "Running in log only mode"
        else log.Info "Running in live mode"
```

And here is what it looks like in the portal:
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/4968704/76678277-6deae380-65ce-11ea-9b09-b41df30bb36a.png">

### Off schedule timer function invocation
We also sometimes need to run timer functions off-schedule, for example when timer-function has failed in some way and needs to be re-run. Today that is possible but it does not look like that will be possible with the new portal. 

### Testing of other trigger types
This is not something we have done, but if we were to write functions that took other input bindings, such as queue events, I can see we would want to be able to run these with arbitrary input. In fact I would not even use the language "Test" but rather just "Run". Or "Run Manually"

## Behaviour of Preview Portal
This is how the Preview Portal looks for a non-HTTP triggered function:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/4968704/76678717-fb7c0280-65d1-11ea-8b8e-68683722dce6.png">

**Comment by btardif** [comment]
@ehamai we need to take a look a this scenario

**Comment by ericsampson** [comment]
Oh no! Everything else about the new experience is great. But this would be a significant loss : (

**Comment by btardif** [comment]
@takyyon I believe you have fixed this, can you provide an update

**Comment by takyyon** [comment]
Made the updates to enable test for non-http functions also. Should go out with our next deployment

**Comment by ericsampson** [comment]
@takyyon thanks! 👍

**Comment by euangordon** [comment]
Have they now removed this functionality? Been using it for years and suddenly can't now manually run a timer triggered function......

![image](https://user-images.githubusercontent.com/32622054/201910480-97f41611-fba3-4daa-9912-c3d42b1b2642.png)

**Comment by jbeeko** [comment]
> Have they now removed this functionality? Been using it for years and suddenly can't now manually run a timer triggered function......

I hope not! I did just check my portal and the functionality is still there.
