### ISSUE TITLE
[UX] - Test run functions is not working

### ISSUE THREAD

**Issue by yuanfulou** [Azure/Azure-Functions#1531]
# Test run functions is not working

## Description
I create a HTTP trigger function for trying preview version user interface. The preview did not show the response for test run the function. It works in the original user interface.

Original
![image](https://user-images.githubusercontent.com/3755714/76692566-a3ff8600-6615-11ea-80c3-30216f7da989.png)

Preview (It's a youtube link since input and output is in the different tab)
https://youtu.be/GMA4vIB6Iq4

## Environment 
MacOSX 10.15.3
Chrome 80.0.3987.122

## HAR
[portal.azure.com.har.zip](https://github.com/Azure/Azure-Functions/files/4333614/portal.azure.com.har.zip)

**Comment by btardif** [comment]
@takyyon can you please take a look?

**Comment by takyyon** [comment]
Hi @yuanfulou , I cannot seem to repro the issue. Are you still facing the issue? 

If so, please attach a snapshot of the console errors and a new har file.  And, can you please send me these on the email - krmitta@microsoft.com

**Comment by btardif** [comment]
@takyyon please provide an update, I think this has already been fixed

**Comment by yuanfulou** [comment]
Hi all, sorry for the late reply. I still can't get the test output from the preview UI. Here's an updated screen recording I just done. https://youtu.be/M4U1cY0lfe4
My environment:
Macbook Air 2014 early
macOS Catalina 10.15.4
Chrome Version 80.0.3987.163 (Official Build) (64-bit)
I also tried on FireFox 75.0 (64-bit) but I forgot to record it. There's no result on Firefox either.

**Comment by btardif** [comment]
@yuanfulou yes, we are in a no-fly-zone for deployments given ongoing quarantine procedures. @takyyon will confirm that code fixes have been done we we haven't been able to push to production until deployment restrictions have been lifted.

**Comment by yuanfulou** [comment]
@btardif Thanks for your reply. I hope my feedback help :)

**Comment by takyyon** [comment]
Made the updates to fix the issue. The updates should go out with our next deployment
