### ISSUE TITLE
[UX] - incorrect content for publish profile after download it using the new azure functions management experience

### ISSUE THREAD

**Issue by Aghyad85** [Azure/Azure-Functions#1535]
Incorrect content for publish profile after download it using the new azure functions management experience

Repro Steps : 
1) visit the portal select the new azure functions management experience for the function app.
2) On Overview tap select Get Publish profile, it will download it with wrong content (URL).

**The expected behavior**: To download the publish profile with content same as in the current experience.

**Comment by PdroCorrea** [comment]
Same issue here...

**Comment by btardif** [comment]
@takyyon can you please take a look?

**Comment by btardif** [comment]
@takyyon I think you did a fix for this already, can you comment on latest status

**Comment by takyyon** [comment]
Yup, fix has been made. Should go out with our next deployment
