### ISSUE TITLE
[Bug Report] Problems for using Durable Functions

### ISSUE THREAD

**Issue by glaucia86** [Azure/Azure-Functions#1536]
In a thread on Twitter, a CTO from a Brazilian Startup, reported a problem they had when using Durable Functions in a project in January.
Below is the reproduction they used to try to solve the problem of using Durable Functions

**[https://pastebin.com/umsHxz8i](https://pastebin.com/umsHxz8i)**

Below the reported thread on Twitter:

-  **[https://twitter.com/GGondim/status/1241453557813051394](https://twitter.com/GGondim/status/1241453557813051394)**

- **[https://twitter.com/GGondim/status/1241454198178414593](https://twitter.com/GGondim/status/1241454198178414593)**

**Comment by glaucia86** [comment]
cc: @anthonychu @fabiocav

**Comment by khaosdoctor** [comment]
Translation to English so it is easier to be international:

```
We had the same problem this guy (https://stackoverflow.com/questions/52692682/azure-durable-functions-going-to-sleep) had.
 
We tried the following workarounds:
- Duplicated maxConcurrentActivityFunctions and maxConcurrentOrchestratorFunctions configs (https://github.com/Azure/azure-functions-durable-extension/issues/455)
- Increased functionTimeout config
- Click on the refresh button, as suggested in other threads (by @davidebbo) (https://github.com/Azure/azure-functions-durable-extension/issues/467 and https://github.com/Azure/azure-functions-host/issues/3573), but this is not scalable and does not always work, and it resets the state of the functions being used.
- Config `WEBSITE_USE_PLACEHOLDER=0` (https://github.com/Azure/azure-functions-durable-extension/issues/630)
- We guaranteed that the name in the task hub was not the same as in a test environment (https://github.com/Azure/azure-functions-durable-extension/issues/529#issuecomment-441765353)
```

**Comment by glaucia86** [comment]
@khaosdoctor thanks a lot Lucas!

**Comment by v-bbalaiagar** [comment]
Hi @glaucia86, Can we understand if this issue require further triaging or is good to be closed?

**Comment by khaosdoctor** [comment]
I think this can be closed

**Comment by fabiocav** [comment]
Thank you, @glaucia86 and @khaosdoctor 

If you need anything else, please let us know.
