### ISSUE TITLE
Graph API Extensions don't support multi-tenant configuration

### ISSUE THREAD

**Issue by antonGritsenko** [Azure/Azure-Functions#1538]
Pre: I know, there is dedicated repo for the Graph API extensions, but looks like it dead (no commits approved and no bug resolved) and MSFT suggest posting bugs here (https://github.com/MicrosoftDocs/azure-docs/issues/50960#issuecomment-604443755)

## Bug description
The bug is in the Graph API extension when working with multi-tenancy setup. The repro steps are very a simple:
1. Create new project in Visual Studio with any version of Azure SDK and default "Hello, {name}" function
2. Create new functions app in the Azure Portal, setup Azure AD Authentication with advanced settings, leave Issue URI empty (https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad?toc=/azure/azure-functions/toc.json#-configure-with-advanced-settings) - IMPORTANT: app registration must support multi-tenancy!
3. Publish functions app to the azure
4. Check authentication, everything (should) works fine
5. Now add the Graph API bindings (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-microsoft-graph) and add attribute:
```
[Token(Identity = TokenIdentityMode.UserFromRequest, Resource = "https://graph.microsoft.com")] string graphToken,
```
6. Publish code to azure again, try to execute function

NullReference error occurred. The problem is here: https://github.com/Azure/azure-functions-microsoftgraph-extension/blob/265ede3da9ac3dbe61c3d3ff49178e808689f048/src/TokenBinding/AadClient.cs#L28
The code tries to send empty IssueUrl to the AuthenticationContext, which is not allowed. 

Two possible solutions:
1. You can extract tenant from the user's token:
```
        private string GetTenant(string rawToken)
        {
            var jwt = new JwtSecurityToken(rawToken);
            var tidClaim = jwt.Claims.FirstOrDefault(c => c.Type == "tid");
            return tidClaim?.Value;
        }
```
and then use it if TenantUrl is empty.
2. Allow to send tenant in a header (less required IMHO)

Currently I'm using own fork, so not an urgent, but will be nice to fix this (not all customers are happy about custom binding).

**Comment by v-bbalaiagar** [comment]
Hi @antonGritsenko, Since its an year old issue, can you confirm if this issue needs to be closed or requires a Triage.

**Comment by antonGritsenko** [comment]
Up to you, we did our own implementation for the customer

**Comment by v-bbalaiagar** [comment]
Thank you for the update. Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
