### ISSUE TITLE
Explain the finer points of input bindings

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#154]
Some points on bindings:
•	Every Function has a trigger.
•	A Trigger is implicitly an input.
•	A Function can have 1 or many non-trigger input bindings.
•	A non-trigger input can use information from the trigger event to fetch its contents.
•	Message type bindings (queues, topics, event hubs) are not, generally, non-trigger inputs.

What this means is that I can have a trigger for something like a queue. That can have, in its message, an id for a record in DocDB. Maybe it has two records, the customer record ID and an ID for a record the customer is interacting with. I can then add two DocDB bindings, each using one of the ID in the queue message, to fetch those records as additional inputs to my Function. That looks, conceptually, like this:

![diagram](https://cloud.githubusercontent.com/assets/2252976/22082645/7318a3b0-dd7d-11e6-9787-958d7ad0c835.png)

**Comment by SyntaxC4** [comment]
This is a conceptual topic which for now would make sense to go under **How-to** > **Plan & Design**

**Comment by lindydonna** [comment]
Incorporated in https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings
