### ISSUE TITLE
Azure Functions 3.0.5 will not load Microsoft.Extensions.Configuration.Abstractions, Version=3.1.3.0

### ISSUE THREAD

**Issue by grahambunce** [Azure/Azure-Functions#1540]
Debugging Azure Functions locally via Visual Studio 16.5.1

Error on Functions startup (.net core 3.1)

>  A host error has occurred during startup operation '0d78e5a3-d279-4c6c-979e-51fd4aaf8776'.
> xxxxxxxs.Consumer.Function: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.

Using the following packages:

AutoMapper 6.2.2
Microsoft.ApplicationInsights.NLogTarget 2.13.1
Microsoft.Azure.Functions.Extensions 1.0.0
Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.1.1
Microsoft.Azure.WebJobs.Logging.ApplicationInsights 3.0.14
Microsoft.NET.Sdk.Functions 3.0.5
NLog 4.7.0
NLog.Extensions.Logging 1.6.2
NLog.Web.AspNetCore 4.9.0

Installed the .NET Core 3.1 SDK 3.1.201

I really just need this to work :( I've used the latest versions of all packages (except AutoMapper) and I can't get a combination to load (reminds me of DLL hell I thought we'd fixed) so all I care about is using the right version of Sdk.Functions with Service Bus that will run.

**Comment by sailane** [comment]
Did anyone find the problem on this issue ? I've been struggling on the exact same issue for a few hours

**Comment by grahambunce** [comment]
Not sure if this is relevant but the same project doesn't fail on MacOS using Rider and the latest azure-functions-host (https://github.com/Azure/azure-functions-host/releases)

**Comment by sailane** [comment]
Yes that's what I have. Azure function v3. And .net core 3,1. 
I didn't find the issue.. but for now my work around was to downgrade the versions ... 
to azure functions v2, .net core 2.2 and also downgraded some of the libraries to older versions and it fixes the issue for me..
