### ISSUE TITLE
[UX] - Different between System Keys and Host Keys

### ISSUE THREAD

**Issue by prawin2k** [Azure/Azure-Functions#1544]
In the new UI, I can see System Keys and the Host Keys. What is the different between these two.?

## Description

In the new UI, I can see System Keys which was not available in the OLD UI. Is this a new feature? Could you please share a link to the documentation?

I created a new System key and a new Host Key using the Preview UI as shown below.

![image](https://user-images.githubusercontent.com/10738750/78157969-32567300-7430-11ea-8795-34a50c508caf.png)

Now, when I go to old UI, I can both of them under the Host Keys as shown below.

![image](https://user-images.githubusercontent.com/10738750/78158068-50bc6e80-7430-11ea-9de9-405ab36635d4.png)

Can you please give some insights on this?

Thanks,
Praveen

**Comment by btardif** [comment]
@mattchenderson can you help here?

**Comment by mattchenderson** [comment]
System keys have been around but haven't been surfaced as a collection in the portal until this new preview. They are connected to extensions, enabling an extension-specific webhook endpoints from the host itself. Most of the time these are presented in the context in which they are used. For example, Durable Functions has an [HTTP API](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api) that leverages such a key.

I don't know of any scenarios which call for creation of new system keys. These are typically referenced by a particular name if memory serves. The host generates them if needed, although you could create one with the right name and it would get picked up.

There is definitely a docs gap here in general. It's something I've discussed with @ggailey777 and @fabiocav

**Comment by fabiocav** [comment]
The description you've provided is correct. System keys are created, usually automatically, by extensions and a few host features as a way to provide tighter access to those features only (e.g. extensions using the webhook endpoints like Durable Functions and Event Grid), so having that key allows you access to that capability only.

As mentioned, those are usually created by the runtime and you don't have to explicitly provision them, but you can reset them if needed.

Host keys are a little better documented and serve as authentication keys for your functions, the difference when defined at the host level is that they apply to ALL functions in your app.

**Comment by prawin2k** [comment]
Okay. Thanks for the response. Hope you guys improve the documentation in the near future!

**Comment by btardif** [comment]
We are working on adding some context in the UX to help clarify this concepts and use cases.

**Comment by btardif** [comment]
@takyyon please take care of this with the new helper text we discussed.

**Comment by takyyon** [comment]
Closing this as the updates have been made
