### ISSUE TITLE
ServiceBus output binding - duplicate detection not working (Javascript)

### ISSUE THREAD

**Issue by bradoyler** [Azure/Azure-Functions#1546]
For Javascript functions, with an output binding like:
```
 {
      "name": "myEvent",
      "type": "serviceBus",
      "queueName": "my-events",
      "connection": "my-servicebus",
      "direction": "out"
 }
```

I have tried setting the messageId, like so: 
```
context.bindings.myEvent = { messageId: '123', foo: 'bar' } 
```
But the duplicate detection on the sb queue never seems to work.

I was, however, able to get get dup detection working by using the `@azure/service-bus` client.

Is 'duplicate detection' a supported feature of the `serviceBus` output binding? I can't seem to find the messageId referenced in any example or this repo. 

Also posted this issue @ https://github.com/Azure/azure-functions-nodejs-worker/issues/293
Thanks.

**Comment by v-anvari** [comment]
I shall follow up with the product team for a response here - https://github.com/Azure/azure-functions-nodejs-worker/issues/293. Closing issue here as duplicate
