### ISSUE TITLE
Azure Functions does not load settings from the Connected Services dependencies

### ISSUE THREAD

**Issue by hansmbakker** [Azure/Azure-Functions#1547]
I'm using [Visual Studio 16.6 preview 2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.6.0-pre.2.0) and Azure Functions v3.

This VS version added a new experience for Connected Services dependencies:
> **New experience for configuring Azure services and emulators:** The Connected Services tab now offers a new experience for connecting your application to Azure services such as Azure SQL, Storage, Key Vault and many others. It helps you provision new instances (or select existing ones) and ensures your code has the most update to date NuGet packages and the right startup configuration code. Wherever possible local emulation options are also available.

![image](https://user-images.githubusercontent.com/3463496/78270975-dfea8480-750b-11ea-90d1-626193d731e9.png)

I added the dependencies I wanted to use from my Azure Functions project:
![image](https://user-images.githubusercontent.com/3463496/78274385-6c974180-7510-11ea-9570-fb473ccb4ab8.png)

It creates named connection strings / environment variables. Also, it added the [`Azure.Extensions.Configuration.Secrets`](https://www.nuget.org/packages/Azure.Extensions.Configuration.Secrets) nuget package. However,
- it does not generate any startup configuration code, which I thought it would do based on reading the release notes quoted above.
- the environment variable `ASPNET_HOSTINGSTARTUP__KEYVAULT__CONFIGURATIONVAULT` is not set when I execute my function app locally (probably because `launchSettings.json` is absent?)
- the added nuget package is not mentioned on the [documentation page, via `Learn more`](https://docs.microsoft.com/en-us/azure/key-vault/vs-key-vault-add-connected-service) that the KeyVault connected service links to

Is this Connected Services experience supposed to work with Azure Functions or only with ASP.Net Core? If not, it would be helpful if it would be supported, or if it was made clear to users that it does not support Azure Functions.

cc @LyalinDotCom

**Comment by hansmbakker** [comment]
Reported as https://developercommunity.visualstudio.com/content/problem/976562/azure-functions-does-not-load-settings-from-the-co.html

**Comment by v-bbalaiagar** [comment]
Hi @hansmbakker,  We apologize for the delayed response, were you able to find a solution to this problem. Do let us know if you want us to look at this issue further.

**Comment by hansmbakker** [comment]
Hi, I have not investigated further.

**Comment by Prinsn** [comment]
@hansmbakker they stated "Do let us know if you want us to look at this issue further.", it might be prudent to specify that you do if you do.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue.
