### ISSUE TITLE
[UX] - Unable to copy the Keys (Function key and Host Keys)

### ISSUE THREAD

**Issue by prawin2k** [Azure/Azure-Functions#1548]
#  Unable to copy the Keys (Function key and Host Keys)

## Description

Hi Team,
The new UI is awesome. 

I noticed that the Copy button is missing. It would be great if you could add the feature.

OLD UI
![image](https://user-images.githubusercontent.com/10738750/78321559-d8eb6280-755b-11ea-9cc9-062ff41d1031.png)

New UI
![image](https://user-images.githubusercontent.com/10738750/78321509-b5c0b300-755b-11ea-9400-ce8731003e5d.png)

**Comment by btardif** [comment]
@prawin2k thank you this is good feedback. You can copy the content from the edit view but we will look into bubbling that up in the ux so that you don't have to do that extra click

@takyyon please look into this.

**Comment by takyyon** [comment]
Made an update for this on canary.
