### ISSUE TITLE
Azure servicebus namespaced topics not recognised

### ISSUE THREAD

**Issue by vdex42** [Azure/Azure-Functions#1550]
Observed using the latest Microsoft.NET.Sdk.Functions V 3.0.5 with ServiceBusTrigger functions:

When specifying the connection string using a [ servicebus namespace](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview#namespaces) e.g. `Endpoint=sb://acme-bus.servicebus.windows.net/mynamespace/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=.....`  (notice the **/mynamespace** in the connection string)

And then creating a ServiceBusTrigger with `ServiceBusTrigger("mytopic",...`

The expected result is that it will monitor the topic `"mynamespace/mytopic"` however it is monitoring `"mytopic"` at the rootlevel instead, and not the topic inside the namespace.

**Comment by v-bbalaiagar** [comment]
Hi @vdex42, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue.
