### ISSUE TITLE
[UX] - Missing button to manually run deployed function

### ISSUE THREAD

**Issue by flatproject** [Azure/Azure-Functions#1551]
# Issue Title
Missing button to manually run code deployed function

## Description
Current Functions interface allow you to run a function manually.
![image](https://user-images.githubusercontent.com/18282373/78766727-8b1e9200-7981-11ea-98d0-b02249b40bd7.png)

Preview interface doesnt.
![image](https://user-images.githubusercontent.com/18282373/78766872-c325d500-7981-11ea-8d7f-6559c3b4bc15.png)

Is there a way to manually run the function or the functionality is not going to be available on the new experience?

**Comment by btardif** [comment]
This is a dup of #1530 we are fixing this issue
