### ISSUE TITLE
Unable to run Azure function in Java - Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. Parameter name: receiverConnectionString.

### ISSUE THREAD

**Issue by VallabhL** [Azure/Azure-Functions#1552]
![image](https://user-images.githubusercontent.com/45813123/78969513-bab9cf80-7b24-11ea-95ba-44185d9059a6.png)

I am trying to read logs received in event hub using functions. When I deploy the app I am getting a pop-up saying "Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. Parameter name: receiverConnectionString.". 

Following is my local.settings.json file.
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "java",   "connectionURL":"Endpoint=sb://rteventhubtemp.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=YISrGFP9FozWULLHdiZLR7RzOnCRAv0q06Zq9kRcz8U="
  }
}

**Comment by frvasquezjaquez** [comment]
were you able to solve the issue?

**Comment by v-bbalaiagar** [comment]
Hi @VallabhL, Kindly let us know if this issue is still persisting, or are we good to close the issue.

**Comment by v-bbalaiagar** [comment]
Hi @VallabhL, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue
