### ISSUE TITLE
Issue with VS 2019 along with Azure

### ISSUE THREAD

**Issue by Hrashid789** [Azure/Azure-Functions#1553]
Hello,

I am trying to run the code that I downloaded from the below link:
https://github.com/Microsoft/AzureSearch_JFK_Files
Here are the screenshots for the errors:
![image](https://user-images.githubusercontent.com/59919959/78999882-3a12c780-7b54-11ea-8ae5-c6a19125e888.png)
![image](https://user-images.githubusercontent.com/59919959/78999896-4008a880-7b54-11ea-8c0a-cdfce26e46d1.png)

**Comment by v-anvari** [comment]
Hi @Hrashid789 , Kindly let us know if this issue is still persisting, or are we good to close the issue

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
