### ISSUE TITLE
Azure function cannot access connected wcf service

### ISSUE THREAD

**Issue by maggiecandyland** [Azure/Azure-Functions#1554]
We are evaluating Azure Functions to compare with other solution on the market. We have an Azure Function (v2) using .net Core 3.1 stack. It will invoke wcf service. It has been tested in localhost without issue. After deploying to Azure, the function got issue to invoke wcf service ( there was no endpoint listening at https://dev_service.ca/ourservice.svc that could accept the message ).

It looks like Azure Function only can connect to wcf services which are hosted on Azure ?

If we put this wcf service into Azure, I am not sure this will solve the issue or not. Also, inside of this wcf service, we will invoke call on XRM toolbox to create CRM entity.

I am wondering even if I put wcf into Azure, then, would the connection to CRM instance be the issue again?

In general, how do we allow Azure Functions to invoke call on WCF service which is not on Azure?
I searched google and found some clue. Just wondering  Is this caused by DNS proxy not enabled? 
Thanks

**Comment by v-bbalaiagar** [comment]
Hi @maggiecandyland, Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
