### ISSUE TITLE
Publishing VS2019 zip deployment sometimes has no effect on the server

### ISSUE THREAD

**Issue by petro2050** [Azure/Azure-Functions#1555]
This happens to me every once in a while, but when it happens, it happens consistently. I will clean and rebuild the solution and publish the zip deployment. Publish will be successful, but when I test the remote functions (even after waiting for 5-10 mins), it seems the code changes are not actually deployed. What's worse is that sometimes code gets deployed partially. :(

When I publish a zip, what happens behind the scenes? Are you trying to detect deltas and make incremental changes or deploy all files from scratch? Perhaps, some servers are getting the new deployment whereas others are stale?

**UPDATE:** I was able to fix this by restarting the function app. I'm still looking for an explanation as to why this happened as it seems to be a bug to me.

**Comment by v-anvari** [comment]
Closing this issue here as a duplicate. Please find any follow up updates in the Functions-host repo
