### ISSUE TITLE
TestServer for Azure function

### ISSUE THREAD

**Issue by kmughal** [Azure/Azure-Functions#1556]
Hi

I am trying to create a TestServer for my simple Azure function for integration test.
Below method creates HttpClient instance which I use to ping the end point. Assertion is failing as it is unable to find the end point. First of all is it possible to create in-memory TestServer for Azure function if yes then can you please help me ? If not then I guess that code can go to trash.

           var client = CreateServer(functionPath); 
            var response = await client.GetAsync("api/Employees");
            Assert.Equal(System.Net.HttpStatusCode.OK, response.StatusCode);

     private static HttpClient CreateServer(string functionPath)
        {
            functionPath = @"azure function folder path";
            var server = new TestServer(WebHost
             .CreateDefaultBuilder()
             .ConfigureAppConfiguration((builderContext, config) =>
             {
                 config
                     .SetBasePath(functionPath)
                      .AddJsonFile("host.json")
                        .AddJsonFile("local.settings.json")
                     .AddEnvironmentVariables();
             })
             .UseStartup<Startup>());
            return server.CreateClient();
        }

Regards
Khurram

**Comment by kmughal** [comment]
I have uploaded my sample code to the following repository https://github.com/kmughal/IntegrationTestAzureFunc

If you go to the Test project you will see that I am trying to create a TestServer in memory

**Comment by v-anvari** [comment]
Apologies for the delayed response.  let us know if a follow up is required

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
