### ISSUE TITLE
Azure function slots UI causing confusion

### ISSUE THREAD

**Issue by yeahsicy** [Azure/Azure-Functions#1559]
Currently, we can add slots on Windows Consumption following https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots#add-a-slot

However, it's confusing that if you go to the app menu as below, you will see the slot feature grayed out and saying it's unavailable. 
![image](https://user-images.githubusercontent.com/34499027/79390940-731cb480-7f25-11ea-86f1-0bffe333b4d4.png)

As this feature is GA on Windows function app in Consumption plan, we should improve user experience and eliminate this UI confusion.

**Comment by v-bbalaiagar** [comment]
Hi @yeahsicy, Apologies for the delayed response, We are able to add slots as expected. Let us know if you are still facing the same issue.

**Comment by v-bbalaiagar** [comment]
Hi @yeahsicy, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue
