### ISSUE TITLE
[UX] - Show compilation error on clicking Save

### ISSUE THREAD

**Issue by prawin2k** [Azure/Azure-Functions#1560]
# Show compilation error on clicking Save

## Description

In the OLd UI, the portal shows the compilation errors as soon as the Save button is clicked. In this new UI, the compilation errors are shown only after running the function.

It would be great if you could enable that feature.

Thanks,
Praveen

**Comment by btardif** [comment]
Thanks for the feedback @prawin2k 👍🏽

@takyyon I think this makes sense can you take care of it?

**Comment by btardif** [comment]
@takyyon can you provide an update

**Comment by takyyon** [comment]
This should be related to the logs. For the file based logging system this should still be the case but I am not sure about AI logs. @ammanifold  Can you please help look into this?

**Comment by btardif** [comment]
@ammanifold can you provide an update here?

**Comment by ammanifold** [comment]
@prawin2k thanks for your feedback. We will be providing an option to use filebased logs in our next deployment.
