### ISSUE TITLE
Getting Error An assembly specified in the application dependencies manifest in Azure function V3 while using EF core 3.1

### ISSUE THREAD

**Issue by masaab** [Azure/Azure-Functions#1561]
I am trying to use EF core (3.1.3) in my Azure function project. When I run the below command.

Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=ScheduleDb;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Project Scheduler.TimerTrigger.Data

I am getting error:

Error: An assembly specified in the application dependencies manifest (Scheduler.TimerTrigger.deps.json) was not found: package: 'Scheduler.TimerTrigger', version: '1.0.0' path: 'Scheduler.TimerTrigger.dll'

My Startup Project is the Scheduler.TimerTrigger which is a TimerTrigger Azure function. My class Library is Scheduler.TimerTrigger.Data.

I execute the command setting my Azure function project (Scheduler.TimerTrigger) as the startup Project and default project.

It works fine if I use a Console application

**Comment by v-bbalaiagar** [comment]
Hi @masaab, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue.
