### ISSUE TITLE
Make sure the value of Authorization header is formed correctly including the signature

### ISSUE THREAD

**Issue by prawin2k** [Azure/Azure-Functions#1563]
# Description
I have created a simple Http Trigger along with Azure Storage Table o/p binding. I'm getting the error "Make sure the value of Authorization header is formed correctly including the signature" when I submit the Http Requests. 
# Below are the steps to reproduce

1. Create a Function app (Consumption)
1. Directly navigate to the new UI and add a new Http Trigger by clicking on the Add button.
1. Add Azure Storage Table Output Bindings as shown below.
![image](https://user-images.githubusercontent.com/10738750/79555916-dc203b80-808f-11ea-8df6-e647861b3db7.png)

1. Submit the Http Trigger. The error in the App Insights as shown below
![image](https://user-images.githubusercontent.com/10738750/79555997-f8bc7380-808f-11ea-8146-ec18212e8fc5.png)

To My Suprise, when i switch back to OLD UI, I got the same error. So, this time, I created a new Function App and created the new Http Trigger from the portal using the Old UI. Everything worked.

# Additional info:
When I tried to view the setting of Table Storage o/p binding in the new UI, below is what I see. I didn't see a new storage instead of AzureWebJobStorage
![image](https://user-images.githubusercontent.com/10738750/79556207-476a0d80-8090-11ea-81ad-269808be379e.png)

**Comment by btardif** [comment]
@ammanifold please take a look

**Comment by ammanifold** [comment]
@refortie and @soninaren would you be able to look into this?

**Comment by refortie** [comment]
There are 2 issues here: the failed to authenticate and the binding information failing to load. The information failing to load issue was just fixed and should be going out with our next deployment. For the auth header failing to authenticate, I'm unable to reproduce the issue. We've had a few bug fixes in the area which may have cleared that up. @prawin2k, if you are still having issues please reopen the issue and we can take another look.
