### ISSUE TITLE
ServiceBusTrigger not obeying IConfiguration ordering.

### ISSUE THREAD

**Issue by shaneholder** [Azure/Azure-Functions#1565]
I am working to integrate App Configuration into Azure Functions.  In configuration I am attempting to put the Azure Configuration first so that local.settings.json would override any values.  This appears to work except for the Connection property in the ServiceBusTriggerAttribute.

All functions are classes, not static and we use the Configure() method of FunctionsStartup for configuration.  The following code is in the Configure method:

```
//per https://github.com/Azure/azure-functions-host/issues/4363#issuecomment-569632971
var provider = builder.Services.BuildServiceProvider();
IConfiguration existingConfig = provider.GetRequiredService<IConfiguration>();
var newBuilder = new ConfigurationBuilder()
	.AddAzureAppConfiguration(o =>
	{
		var cred = new DefaultAzureCredential();
			o.Connect(new Uri(existingConfig["AppConfigEndpoint"]), cred)
		.ConfigureKeyVault(kv => kv.SetCredential(cred));
	})
	.AddConfiguration(existingConfig);
var newConfiguration = newBuilder.Build();
builder.Services.Replace(ServiceDescriptor.Singleton(typeof(IConfiguration), newConfiguration));
```

Running this in the debugger, I can confirm that the order in which AddConfiguration() and AddAzureAppConfiguration() are executed affect the output of newConfiguration["bus"] with the last one added taking precedence.

However no matter how I order them when I run the function project the functions always listen to the bus assigned in App Configuration.  I am attempting to test this by creating a connection string in local.settings.json with an incorrect SharedAccessKey which creates all sorts of chaos. :)

Is there something else that needs to be done to configure the ServiceBusTriggerAttribute?

Regards,
Shane Holder

**Comment by v-bbalaiagar** [comment]
Hi @shaneholder, Kindly let us know if this issue is still persisting, or are we good to close the issue.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
