### ISSUE TITLE
Modify robots.txt

### ISSUE THREAD

**Issue by isaacrlevin** [Azure/Azure-Functions#1567]
I have a scenario where I am doing a URL redirect using Azure Functions. One of things I have noticed is that previews of final URLs are not showing on Twitter via cards. This seems be because the robots.txt for my platform is blocking TwitterBot. Per [Twitter Documentation](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#url-crawling-and-caching), I need to update my robots.txt to something like this

````
User-agent: Twitterbot
Disallow:

User-agent: *
Disallow: /
````

But I have not been able to find where the original file is, and placing a new one does not overwrite the old. How can I update robots.txt?

**Comment by v-bbalaiagar** [comment]
Hi @isaacrlevin, Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue, if yes , can you provide us with the repro steps.
