### ISSUE TITLE
If I create a function with certain connection string and its value (From Visual studio) - I am not able to change the connection string param name

### ISSUE THREAD

**Issue by madhusameena** [Azure/Azure-Functions#1569]
I created a function (Queue trigger) like below
```
[FunctionName("StartFun")]
public async Task RunAsync([QueueTrigger("%QueueName%", Connection = "AzureWebJobsStorage")]string queueDetails)
{}
```
And I have the value of `AzureWebJobsStorage` in `local.settings.json`

After I renamed to 
```
[FunctionName("StartFun")]
public async Task RunAsync([QueueTrigger("%QueueName%", Connection = "AzureQueueStorageConnectionString")]string queueDetails)
{}
```
And I give the value of  `AzureQueueStorageConnectionString` in json

If `AzureQueueStorageConnectionString` value is different from `AzureWebJobsStorage` 
I am getting `system.xml.xmlexception: 'root element is missing.'` error 
Is this expected?

I cannot listen a queue from another storage account than  `AzureWebJobsStorage` ?

**Comment by v-bbalaiagar** [comment]
Hi @madhusameena, Apologies for the delayed response, Were you able to find a solution. Let us know if you are still seeing these error.

**Comment by madhusameena** [comment]
> 
> 
> Hi @madhusameena, Apologies for the delayed response, Were you able to find a solution. Let us know if you are still seeing these error.

Hi

I think I got the problem already
with out the value of `AzureWebJobsStorage` in appsettings.json we cannot use function app - This is what I understood, 
Please let me know If I am wrong.

**Comment by v-bbalaiagar** [comment]
Hi @madhusameena, Yes, you are right the Azure Functions runtime uses the `AzureWebJobsStorage `connection string to create internal queues. These are preset variables which are required for function app to run as expected. [App settings reference for Azure Functions | Microsoft Docs,](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsstorage)


While running from visual studio, By default the value will be as below:

"Values": {

"AzureWebJobsStorage": "UseDevelopmentStorage=true",

.....

 

You can change the values into the connection string that you require like below: - [Automate function app resource deployment to Azure | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code#storage-account)

"appSettings": [
    {
        "name": "AzureWebJobsStorage",
        "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(variables('storageAccountid'),'2019-06-01').keys[0].value)]"
    },
  

You can find your storage account's connection strings in the Azure portal. Navigate to SETTINGS > Access keys in your storage account's menu blade to see connection strings for both primary and secondary access keys : [Configure a connection string - Azure Storage | Microsoft Docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#configure-a-connection-string-for-an-azure-storage-account)

**Comment by v-bbalaiagar** [comment]
Hi @madhusameena, Closing this issue as there is no response, Please feel free to reach back to us in case of any further queries related to this issue
