### ISSUE TITLE
Show a meaningful error if specificed ServiceBus queue does not exist or cannot be found

### ISSUE THREAD

**Issue by tomasmcguinness** [Azure/Azure-Functions#157]
I'm using a set of functions to process data in a short pipeline. One Function reads from an input ServiceBus queue and writes to an output ServiceBus queue. When I start the host, I would get this message; "A Scripthost error has occurred" 

<img width="211" alt="error" src="https://cloud.githubusercontent.com/assets/302741/22197692/0fcf5b42-e14b-11e6-9f21-a8c79405383f.PNG">

The underlying cause was that one of the ServiceBus queues referenced in the function.json didn't exist. Once I created the queue in ServiceBus, the Scripthost started working without issue. An error indicating this would be useful in the event of forgetfulness (!) or typos.

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-functions-cli#37
