### ISSUE TITLE
Timeout value of 00:05:00 was exceeded by azure function 

### ISSUE THREAD

**Issue by Srinivas-Potnuru** [Azure/Azure-Functions#1571]
Getting the timeout exception though the "functionTimeOut" is having value for 10 mins under host.json. This issue is coming for an activity function which is called from an azure durable function.

Azure function version : V3.

**Comment by v-bbalaiagar** [comment]
Hi @Srinivas-Potnuru, Since its an year old issue, can you confirm if this issue needs to be closed or requires a Triage.

**Comment by v-bbalaiagar** [comment]
Hi @Srinivas-Potnuru, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue.
