### ISSUE TITLE
Function app "Could not load file or assembly 'NuGet.Versioning'"

### ISSUE THREAD

**Issue by erYasar** [Azure/Azure-Functions#1575]
Recently, I did a Azure Function App migration from .Net Standard 2.0 to .Net Core 3.1. With some referenced class library projects with .Net Standard 2.1.

One or more referenced projects in Function app has Nuget.Versioning 4.9 package.

Strange things happened during my function app build, Nuget.Versioning was copied at start but after sometime during build it vanished.

Due to this I am facing runtime exception "Could not load file or assembly 'NuGet.Versioning'". Any idea could help me to proceed further.

**Comment by v-bbalaiagar** [comment]
Hi @erYasar, Since its an year old issue, can you confirm if this issue needs to be closed or requires a Triage.

**Comment by erYasar** [comment]
@v-bbalaiagar require triage

**Comment by v-bbalaiagar** [comment]
Hi @erYasar, Thank you for the update, We are checking internally for any known issue

**Comment by v-bbalaiagar** [comment]
Hi @erYasar, Can you please go through this[ issue](https://github.com/NuGet/Home/issues/10118) which is being addressed and worked upon on a similar scenario. Let us know if that helps.
