### ISSUE TITLE
Add Azure Function in Cosmos DB using Portal

### ISSUE THREAD

**Issue by prawin2k** [Azure/Azure-Functions#1576]
# Add Azure Function in Cosmos DB using Portal
I created an Azure Function using the "Add Azure Function" feature from Cosmos DB to work with Change Feed. 
Below are the errors that I'm getting.
![image](https://user-images.githubusercontent.com/10738750/80896729-d4dc6d00-8ce0-11ea-8b65-f5e3641a20e9.png)

**Comment by prawin2k** [comment]
attaching the trace
[AzureFunctionsCosmosdb.zip](https://github.com/Azure/Azure-Functions/files/4569535/AzureFunctionsCosmosdb.zip)

**Comment by v-bbalaiagar** [comment]
Hi @prawin2k, Apologies for the delayed response, Were you able to find a solution. Let us know if you are still seeing these error.

**Comment by v-bbalaiagar** [comment]
Hi @prawin2k, Closing this issue as there is no response, Please feel free to reach back to us in case of any further queries related to this issue.
