### ISSUE TITLE
Event hub trigger and documentDb in binding

### ISSUE THREAD

**Issue by jokarl** [Azure/Azure-Functions#1578]
[This document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=javascript#queue-trigger-get-multiple-docs-using-sqlquery-1) talks about a queue trigger and shows how it is possible to extract data from the messages body.

Is it possible to do the same with the event hub trigger, providing cardinality is set to `one`?

We have a need to extract multiple variables from an event hub message from our IoT hub to get a document from the correct container in our Cosmos account.

Something like:
```json
{
    "name": "documents",
    "type": "cosmosDB",
    "direction": "in",
    "databaseName": "MyDb",
    "partitionKey": "{property.customer}",
    "collectionName": "collection",
    "sqlQuery": "SELECT x FROM x WHERE x.id = {id} AND x.property = {property} AND ARRAY_CONTAINS(x.array, {'property': {arrayValue} }, true)",
    "connectionStringSetting": "CosmosDBConnection"
}
```

Where the event hub message looks like this:
```json
{
    "id": 1,
    "property": "property",
    "arrayValue": "arrayValue"
}
```
And customer is a property on the message: `"customer" = "customer"`

Is this possible?

**Comment by v-bbalaiagar** [comment]
Hi @jokarl, Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
