### ISSUE TITLE
Post Build Event to copy files does not work with 3.0.7

### ISSUE THREAD

**Issue by kuromukira** [Azure/Azure-Functions#1582]
Steps:
1.) Create an Azure Functions project using 3.0.7
2.) Create other class library project
3.) Add the new class library as reference for the azure function
4.) In the csproj file of the azure function, add post build event to copy the .dll files from
`AzureFunction/bin/Debug/netcoreapp3.1/bin/MyClassLib.dll` to `AzureFunction/bin/Debug/netcoreapp3.1`

`
    <Copy SourceFiles="$(TargetDir)bin\MyClassLib.dll" DestinationFolder="$(TargetDir)" />
`
No file is copied to the out directory.

**Comment by v-bbalaiagar** [comment]
Hi @kuromukira, Apologies for the delayed response, can we know if you are still seeing this issue.

**Comment by kuromukira** [comment]
@v-bbalaiagar Thanks for replying. But I got it working now.
