### ISSUE TITLE
Remote build won't happen on Linux when using WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by yliu** [Azure/Azure-Functions#1583]
I have same issue as https://github.com/MicrosoftDocs/azure-docs/issues/52501

> I'm having a problem with remote build on Linux host for python based functionapp.
> After specifying ENABLE_ORYX_BUILD,
> SCM_DO_BUILD_DURING_DEPLOYMENT and WEBSITE_RUN_FROM_PACKAGE, 3rd-party packages in requirement.txt still could not be imported.

**Comment by anirudhgarg** [comment]
Please do not use WEBSITE_RUN_FROM_PACKAGE setting if you want Remote Build. We are making this better - but for now please remove it. Remote Build will handle the blob for you.

**Comment by sylnsr** [comment]
Is this still relevant? It would seem insane that the documentation still shows how to deploy using  WEBSITE_RUN_FROM_PACKAGE ... and for the previous comment to still be relevant.

**Comment by anirudhgarg** [comment]
We have updated the documentation that it is not supported. https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enable-functions-to-run-from-a-package

https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#considerations-for-deploying-from-an-on-site-package

**Comment by sylnsr** [comment]
Looking forward to seeing this fixed. Having Linux treated as a 3rd rate citizen in Azure is the main reason we push all our customers to AWS.

**Comment by sylnsr** [comment]
The documentation does not mention `--build-remote` for `az functionapp deployment source config-zip`. It seems like it should. I know there is the `.deployment` file option ... but the `--build-remote` option seems cleaner and worth mentioning.
