### ISSUE TITLE
Unable to get Azure Function Python 3.8 to work in Azure

### ISSUE THREAD

**Issue by mgolois** [Azure/Azure-Functions#1586]
Code is working fine locally, but when I deploy I get the following error:

> Result: Failure
> Exception: ImportError: libpq.so.5: cannot open shared object file: No such file or directory
> Stack:   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 238, in _handle__function_load_request
>     func = loader.load_function(
>   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/loader.py", line 66, in load_function
>     mod = importlib.import_module(fullmodname)
>   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/site/wwwroot/NotifyAttendees/__init__.py", line 3, in <module>
>     import psycopg2
>   File "/home/site/wwwroot/.python_packages/lib/site-packages/psycopg2/__init__.py", line 51, in <module>
>     from psycopg2._psycopg import (                     # noqa

My requirements.txt file

> astroid==2.4.1
> azure-functions==1.2.1
> colorama==0.4.3
> DateTime==4.3
> isort==4.3.21
> lazy-object-proxy==1.4.3
> mccabe==0.6.1
> psycopg2==2.8.5
> pylint==2.5.2
> python-http-client==3.2.7
> pytz==2020.1
> sendgrid==6.3.0
> six==1.14.0
> toml==0.10.0
> wrapt==1.12.1
> zope.interface==5.1.0

Am I missing something?

**Comment by mgolois** [comment]
For someone else having this issue, use `psycopg2-binary` instead of `psycopg2`

**Comment by sanghvi-yash** [comment]
Thanks a lot for this

**Comment by ericthomas1** [comment]
Hm...seems like `psycopg2-binary` isn't meant for production use: https://github.com/psycopg/psycopg2#installation. Any alternatives?
