### ISSUE TITLE
Enable just my code seems to not work

### ISSUE THREAD

**Issue by ranouf** [Azure/Azure-Functions#1588]
Hi,

I have hard time debugging my azure function. I deleted the .vs folder just in case but still have issues.

I don't know why but it keeps asking to find SystemLogger.cs:
![image](https://user-images.githubusercontent.com/1764519/81908317-1568a000-9597-11ea-89a9-56ba979fb00b.png)

Details:

> Locating source for 'C:\azure-functions-host\src\WebJobs.Script.WebHost\Diagnostics\SystemLogger.cs'. Checksum: SHA256 {a8 24 a3 b1 8 2e 96 1d d2 a0 c5 dc 5c 52 14 73 d3 75 db 3b 9b 1e 79 d5 6b d4 f6 bf 3e 31 40 da}
> The file 'C:\azure-functions-host\src\WebJobs.Script.WebHost\Diagnostics\SystemLogger.cs' does not exist.
> Looking in script documents for 'C:\azure-functions-host\src\WebJobs.Script.WebHost\Diagnostics\SystemLogger.cs'...
> Looking in the projects for 'C:\azure-functions-host\src\WebJobs.Script.WebHost\Diagnostics\SystemLogger.cs'.
> The file was not found in a project.
> Searching for documents embedded in the symbol file.
> An embedded document was not found.
> The debugger will ask the user to find the file: C:\azure-functions-host\src\WebJobs.Script.WebHost\Diagnostics\SystemLogger.cs.
> The user pressed Cancel in the Find Source dialog. The debug source files settings for the active solution have been modified so that the debugger will not ask the user to find the file: C:\azure-functions-host\src\WebJobs.Script.WebHost\Diagnostics\SystemLogger.cs.
> The debugger could not locate the source file 'C:\azure-functions-host\src\WebJobs.Script.WebHost\Diagnostics\SystemLogger.cs'.

And as you can "Just my code" is enabled:
![image](https://user-images.githubusercontent.com/1764519/81908516-5365c400-9597-11ea-8d43-eb61cb67927b.png)

I have no issue to debug with Webjob or WebAPI.

Do you have any idea?

**Comment by v-anvari** [comment]
Hi @ranouf , Are you still facing this issue, can you give us the repro steps for us to understand the error better and find a workaround
