### ISSUE TITLE
First class support for Deno

### ISSUE THREAD

**Issue by aadamsx** [Azure/Azure-Functions#1589]
Will we get first class support for Deno now that its reached [version 1.0](https://deno.land/v1)?

**Comment by anirudhgarg** [comment]
Please have a look at the Deno Worker that @anthonychu created using Custom Handlers

https://github.com/anthonychu/azure-functions-deno-worker

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
