### ISSUE TITLE
Update Functions Overview article to remove mention of "long-running tasks"

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#159]
This article: https://docs.microsoft.com/en-us/azure/azure-functions/functions-overview#what-can-i-do-with-functions has the following text:

> Consider Functions for tasks like image or order processing, file maintenance, long-running tasks that you want to run in a background thread, or for any tasks that you want to run on a schedule.

We need to remove the phrase "long-running" from the text, so it is just "...file maintenance, tasks that you want to run in a background thread..."

**Comment by lindydonna** [comment]
@ggailey777 Can I assign to you since it's an easy change?  My repo is out of date so it will take me a while to submit the fix.

**Comment by ggailey777** [comment]
Fixed by @rachelappel https://github.com/Microsoft/azure-docs-pr/commit/c114d73c15ffb58b504dd0ad729c3aa6a7fa5008
