### ISSUE TITLE
Monitoring for functions in deployment slots use production for query, causing empty results

### ISSUE THREAD

**Issue by emilbm** [Azure/Azure-Functions#1590]
It appears as if the Monitor Tab in the new UI for "Invocations" use a query that's constructed for your production slot. If you click "Run Query In Application Insights", you can see that it uses the production name, and adding your slot name to the cloud_RoleName property returns results as expected. 

The problem with this is that it'll show no results in the "invocation" tab.

**Comment by v-bbalaiagar** [comment]
Hi @emilbm, Apologies for the delayed response, We would like to know if you are still facing the same issue.

**Comment by v-bbalaiagar** [comment]
Hi @emilbm, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue.
