### ISSUE TITLE
[UX] - Testing functions via Code + Test panel wraps request payload into another object

### ISSUE THREAD

**Issue by mrakn** [Azure/Azure-Functions#1592]
I am trying to test my **queue triggered** function through the new **Code + Test** panel on the Azure portal:
![image](https://user-images.githubusercontent.com/64434438/82205948-a6c57280-9907-11ea-8bc3-13e2d189ca71.png)

As you can see, I am trying to send following JSON:
`{"property1":"value1"}`

However after clicking **Run** the payload is transformed and function is then invoked with the updated payload:
`{"body":"{\"property1\":\"value1\"}"}`

This can be confirmed by closing and reopening the *Test* panel:
![image](https://user-images.githubusercontent.com/64434438/82206336-5569b300-9908-11ea-8a30-37ef9622c053.png)

This breaks the function I am trying to test. It works fine when I push the message to queue and then wait for function to pick and process the message.

I am not aware of this transformation happening in old testing panel.

**Comment by btardif** [comment]
@mrakn thanks for reporting this issue. @takyyon will be taking a look and will provide updates.

I'm able to repro this myself.

**Comment by takyyon** [comment]
An update has been pushed for this, it should be live next week.
