### ISSUE TITLE
Service bus trigger variables generated as output instead of input

### ISSUE THREAD

**Issue by jezzipin** [Azure/Azure-Functions#1593]
I have the following function code:

```
[FunctionName("ProcessServiceBusMessageAsFirebaseNotification")]
        public static async void Run(
            [ServiceBusTrigger("testqueue")]
            string myQueueItem,
            ILogger log)
        {
            if (FirebaseApp.DefaultInstance == null)
            {
                var serviceAccount = BuildServiceAccount();

                FirebaseApp.Create(new AppOptions()
                {
                    Credential = GoogleCredential.FromJson(serviceAccount)
                });
            }

            var message = JsonSerializer.Deserialize<MulticastMessage>(myQueueItem);

            var messaging = await FirebaseMessaging.DefaultInstance.SendMulticastAsync(message);

            log.LogInformation("Notifications sent to devices " + string.Join(",", message.Tokens));
        }
```

When running this solution on Visual Studio 2019 in debug mode, the function connects to the relevant service bus and is triggered when a message is added to queue.

However, when the project is built or deployed using Azure Devops or indeed when it is built locally the function.json file is incorrect and does not define the myQueueItem variable as an input variable. This is further demonstrated when looking at the integration tab within the function on Azure shown below:

![image](https://user-images.githubusercontent.com/4697711/82263996-00578c80-995c-11ea-9976-0cffde8ed05d.png)

Upon looking at the deployed function.json file via the Code + Test window on Azure, the following generated file is displayed:

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.7",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "queueName": "testqueue",
      "isSessionsEnabled": false,
      "name": "myQueueItem"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/FirebaseNotifications.dll",
  "entryPoint": "FirebaseNotifications.ProcessServiceBusMessageAsFirebaseNotification.Run"
}
```

Clearly this is incorrect as the Trigger attribute is used in the code above meaning the parameters should be input only.

As it is incorrect for a developer to modify or adjust the function.json file in this scenario as it is auto-generated could you please provide a solution or workaround so that we can ensure our code is source controlled as we do not wish to use the Azure inline function editors.

The following at the details of the systems involved:

**Local Machine**

Windows 10 Professional 
Visual Studio 2019 Professional
.Net Core 3.1

**Project packages**
Microsoft.NET.Sdk.Functions 3.07
Microsoft.Azure.Webjobs.Extensions.ServiceBus 4.1.1

**Azure Function App**

OS: Windows

**Comment by v-bbalaiagar** [comment]
Hi @jezzipin, Apologies for the delayed response, Were you able to find a solution. Let us know if you are still seeing these error.

**Comment by v-bbalaiagar** [comment]
Hi @jezzipin, Closing this issue as there is no response, Please feel free to reach back to us in case of any further queries related to this issue.
