### ISSUE TITLE
Binding input CosmosDB collection error (NodeJS)

### ISSUE THREAD

**Issue by mkarczewski85** [Azure/Azure-Functions#1594]
I'm trying to bind CosmosDB collections as input parameter:

`{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "name": "updatedDocs",
      "databaseName": <dbname>,
      "collectionName": <collection_name>
      "createIfNotExists": false,
      "connectionStringSetting": <conn_string_setting>,
      "partitionKey": "partitionKey",
      "direction": "out",
      "type": "cosmosDB"
    },
    {
      "name": "inputDocs",
      "direction": "in",
      "type": "cosmosDB",
      "databaseName": <dbname>,
      "collectionName": <collection_name>
      "connectionStringSetting": <conn_string_setting>,
      "id": "",
      "sqlQuery": ""
    }
  ]
}`

If I test this generated template code: 

`module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
};`

I get following error and 500 status:

> Can't bind CosmosDB to type 'System.String'. Possible causes: 1) Tried binding to 'Microsoft.Azure.Documents.Client.DocumentClient, Microsoft.Azure.DocumentDB.Core, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' but user type assembly was 'System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e.

It doesn't occur in case if C# script version, but I need to implement my function app in JS.

EDIT:
It seems that error occurs only when using Function App v3. When I downgraded to v2.0 everything was fine.

**Comment by v-bbalaiagar** [comment]
Hi @mkarczewski85 , Apologies for the delayed response, can we know if you are still seeing this issue.

**Comment by v-bbalaiagar** [comment]
Hi @mkarczewski85, Closing this issue as there is no further activity, Please feel free to reach back to us in case of any further queries related to this issue.
