### ISSUE TITLE
Missing step in tutorial chain-azure-functions-data-using-bindings

### ISSUE THREAD

**Issue by cdeil** [Azure/Azure-Functions#1599]
For https://docs.microsoft.com/en-us/learn/modules/chain-azure-functions-data-using-bindings/5-read-data-with-input-bindings-portal-lab?pivots=javascript I get the issue that for "Cosmos DB account connection" there's nothing that I can select.

Looks like there's an instruction missing in the tutorial to set an app setting with the CosmosDB connection string?

![Screenshot 2020-05-23 at 23 32 29](https://user-images.githubusercontent.com/852409/82740972-e350fe00-9d4d-11ea-8420-d8e1776a2e0e.png)

**Comment by cdeil** [comment]
Also, on the same tutorial page with the "integrations" tab I keep getting this error:

> One or more bindings failed to load, please refresh the page.

Only on every ~ fifth page refresh is the error gone.

Looks like a bug (or race condition / too tight timeout) how you load things on that page.

![image](https://user-images.githubusercontent.com/852409/82741132-658df200-9d4f-11ea-95db-0dd736b0cb19.png)

**Comment by cdeil** [comment]
I added a COSMOS_CONNECT system setting, then I could finish the dialog to create the CosmosDB binding, which resulted in this:
```
    {
      "name": "bookmark",
      "direction": "in",
      "type": "cosmosDB",
      "databaseName": "func-io-learn-db",
      "collectionName": "Bookmarks",
      "connectionStringSetting": "COSMOS_CONNECT",
      "id": "{id}",
      "partitionKey": "{id}",
      "sqlQuery": ""
    }
```

Now I get the error "Can't bind CosmosDB to type System.String

Bug? Or am I making a mistake?

![Screenshot 2020-05-24 at 00 04 22](https://user-images.githubusercontent.com/852409/82741474-7855f600-9d52-11ea-860a-3f588ba266d5.png)

**Comment by LeopoldoD** [comment]
> Also, on the same tutorial page with the "integrations" tab I keep getting this error:
> 
> > One or more bindings failed to load, please refresh the page.
> 
> Only on every ~ fifth page refresh is the error gone.
> 
> Looks like a bug (or race condition / too tight timeout) how you load things on that page.
> 
> ![image](https://user-images.githubusercontent.com/852409/82741132-658df200-9d4f-11ea-95db-0dd736b0cb19.png)

I got the same error

**Comment by tutugreen** [comment]
Same

“One or more bindings failed to load, please refresh the page.” Ramdom appear.

And

Got 500 error on section "Read data with input bindings".

Invocation Details
2020-06-02 18:17:50.598
Executing 'Functions.find-bookmark' (Reason='This function was programmatically called via the host APIs.', Id=9120dd94-d6c5-47c9-a352-bcccf42d1cb7)
Information
2020-06-02 18:17:50.925
Can't bind CosmosDB to type 'System.String'. Possible causes: 1) Tried binding to 'Microsoft.Azure.Documents.Client.DocumentClient, Microsoft.Azure.DocumentDB.Core, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' but user type assembly was 'System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e.
Error
2020-06-02 18:17:50.925
Executed 'Functions.find-bookmark' (Failed, Id=9120dd94-d6c5-47c9-a352-bcccf42d1cb7)
Error
2020-06-02 18:17:50.934
Can't bind CosmosDB to type 'System.String'. Possible causes: 1) Tried binding to 'Microsoft.Azure.Documents.Client.DocumentClient, Microsoft.Azure.DocumentDB.Core, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' but user type assembly was 'System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e.
Error

**Comment by jefffhaynes** [comment]
Getting the same thing when I add table bindings

**Comment by vikas-explorer** [comment]
Same thing is keep bugging.. Do anyone know where we can get actual connection string connection settings? they mentioned it is in appsettings. But I can find appsettings anywhere. could somebody direct to me that

**Comment by considerITman** [comment]
> For https://docs.microsoft.com/en-us/learn/modules/chain-azure-functions-data-using-bindings/5-read-data-with-input-bindings-portal-lab?pivots=javascript I get the issue that for "Cosmos DB account connection" there's nothing that I can select.
> 
> Looks like there's an instruction missing in the tutorial to set an app setting with the CosmosDB connection string?
> 
> ![Screenshot 2020-05-23 at 23 32 29](https://user-images.githubusercontent.com/852409/82740972-e350fe00-9d4d-11ea-8420-d8e1776a2e0e.png)

In step 5, it actually says to click on "new" to create one - I missed it too, on my first read:
![image](https://user-images.githubusercontent.com/47301302/83857180-e3240b80-a71a-11ea-8312-d12e4a0c2dbb.png)

**Comment by considerITman** [comment]
> I added a COSMOS_CONNECT system setting, then I could finish the dialog to create the CosmosDB binding, which resulted in this:
> 
> ```
>     {
>       "name": "bookmark",
>       "direction": "in",
>       "type": "cosmosDB",
>       "databaseName": "func-io-learn-db",
>       "collectionName": "Bookmarks",
>       "connectionStringSetting": "COSMOS_CONNECT",
>       "id": "{id}",
>       "partitionKey": "{id}",
>       "sqlQuery": ""
>     }
> ```
> 
> Now I get the error "Can't bind CosmosDB to type System.String
> 
> Bug? Or am I making a mistake?
> 
> ![Screenshot 2020-05-24 at 00 04 22](https://user-images.githubusercontent.com/852409/82741474-7855f600-9d52-11ea-860a-3f588ba266d5.png)

I have the same problem. As soon as I add the input binding, the function fails.
I've tried creating a new function and recreating the input-binding without success.
I don't even have to use the binding - just add it and leave the default http-trigger code in -> instant fail.

**Comment by herao67** [comment]
SOLVED
Turn on the classic view, then recreate the binding. To do that, click on your functions app. On the top you see "Having issues? Click to go back to the classic Function App management experience". Do that, then delete your old cosmosDB binding and recreate it.

**Comment by cristiaan3003** [comment]
How I "Turn on the classic view" ?

**Comment by lassealfastsen** [comment]
> How I "Turn on the classic view" ?

Go to the top level of your App Service.
There is a button in the top that will let you switch to the old experience
![image](https://user-images.githubusercontent.com/10941370/86114945-87576300-bacb-11ea-9cbe-fae79cf0ed71.png)

**Comment by kmadof** [comment]
The issue is with `  "sqlQuery": ""`. If you remove it should be fine. Please check this [question on SO](https://stackoverflow.com/questions/61988060/azure-cosmos-db-input-binding-for-an-azure-function-doesnt-work/62753612#62753612).

**Comment by walter-csharp** [comment]
> The issue is with ` "sqlQuery": ""`. If you remove it should be fine. Please check this [question on SO](https://stackoverflow.com/questions/61988060/azure-cosmos-db-input-binding-for-an-azure-function-doesnt-work/62753612#62753612).
that worked for me but it would be nice in detail why this causing the issue

**Comment by v-anvari** [comment]
Hi @cdeil , Apologies for the delay in response. Recently the Microsoft learning team had updated this tutorial module. You can find the confirmation here - https://github.com/Azure/Azure-Functions/issues/1885#issuecomment-867426333. Also, in case of any problems regarding any update or feedback regarding MS learn, please report issue below the tutorial.
