### ISSUE TITLE
Update existing documentation pages which are missing Node.js Code Samples

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#16]

**Comment by SyntaxC4** [comment]
Also - Updating the documentation to make sure everything is consistent.

**Comment by cephalin** [comment]
Updated docs are now staged at:
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-documentdb/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-event-hubs/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-http-webhook/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-mobile-apps/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-service-bus/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-storage-blob/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-storage-queue/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-storage-table/
- http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-bindings-timer/

**Comment by SyntaxC4** [comment]
Add in a link to the CloudQueueMessage Documentation in the Storage Queue Docs.

**Comment by SyntaxC4** [comment]
@christopheranderson - Can you take a look at this for a review

**Comment by christopheranderson** [comment]
Notes:

- For the output types in C# and F#, we should mention the ICollector and IAsyncCollector
- For the Event Hub trigger, we should mention that you should use batching for optimum throughput.
      - Essentially, if you set a type as `T[]` (where T is string, POCO, etc.), we'll send a batch of messages to you.
      - For Node.js, you have to set "cardinality" to "many". I'm working on a portal update to add this.

**Comment by cephalin** [comment]
@christopheranderson do ICollector and IAsyncCollector apply to all output bindings? Some docs have it and some docs don't.
Setting cardinality to many is in JSON?

**Comment by christopheranderson** [comment]
ICollector/IAsyncCollector works for following output:

- Queue Storage
- Service Bus Queue
- Service Bus Topic
- Doc DB
- Table Storage
- Blob Storage
- Event Hub

**Comment by christopheranderson** [comment]
Ignore cardinality for now. We're still smoothening experience from product side. There are open issues/questions with Event Hubs Node implementation.

**Comment by cephalin** [comment]
Hi Chris, sorry I'm back to working on this. Does the ICollector/IAsyncCollector pattern for Node.js (param.push()...) work for all the output bindings above?

**Comment by cephalin** [comment]
@christopheranderson  I've added text about ICollector/IAsyncCollector to the bindings you listed now.
