### ISSUE TITLE
Issues for azure-functions-ux ?

### ISSUE THREAD

**Issue by cdeil** [Azure/Azure-Functions#1600]
In your issue template you currently have this suggestion:

> - For portal issues, use https://github.com/azure/azure-functions-ux

That repo doesn't have issues activated.

Can you please either allow issues there, or update this suggestion?

**Comment by v-bbalaiagar** [comment]
Hi @cdeil, Apologies for the delayed response, can we know if you are still seeing this issue.

**Comment by cdeil** [comment]
@v-bbalaiagar - what's your current issue template for Azure functions?

**Comment by v-bbalaiagar** [comment]
Hi @cdeil, Can you please confirm were you asking about template issues, If yes for template issues, use https://github.com/azure/azure-functions-templates.

**Comment by cdeil** [comment]
It's been over a year, and unfortunately I don't remember from which MS docs azure function page I was redirected to the wrong issue tracker. Could be fixed in the meantime, and if there's still some issue I guess active users will just re-raise it. Closing.
