### ISSUE TITLE
Azure Functions Worker documentation

### ISSUE THREAD

**Issue by AlexeyRaga** [Azure/Azure-Functions#1601]
I would like to build an Azure Functions Worker for Haskell language.

I see that there are already several language-specific workers exist (Java, Python, JS), so building a new one should be possible and maybe even straightforward. 

Where do I find a technical documentation about how it can be done? 
Is it possible to receive some guidance in how it can/should be done?

**Comment by v-anvari** [comment]
@AlexeyRaga , Please find the documentation for [Azure functions custom handlers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers). You shall find examples here
