### ISSUE TITLE
Diagnose and solve problem in Azure portal show wrong info

### ISSUE THREAD

**Issue by snerting** [Azure/Azure-Functions#1607]
I have trouble with my Timer trigger, it would not fire. To find more info I use the "Diagnose and solve problem". I check the "Timer Trigger Issue Analysis" and got info about that Always on must be enabled. I do as I was told, and go to my Terraform script and turn it on. What happend next is that Terraform return info about error response reportet from Function. When I went back to my function, all the code who was deployet to the function was gone. Must deploy it againt to have my function back. (this is very bad).
Since I still have problems with my trigger I go into the "Diagnose and Solve problem" again, and I see the "AlwaysOn check", and try it out. This give me info that's all fine and AlwaysOn must be disabled on a Premium Tier. Please fix so it's show correct info in both checks.
![image](https://user-images.githubusercontent.com/1882879/83104872-e899aa00-a0b9-11ea-9bca-ecc86e30a7c4.png)

**Comment by v-bbalaiagar** [comment]
Hi @snerting, Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue.

**Comment by v-bbalaiagar** [comment]
Hi @snerting, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
