### ISSUE TITLE
DocumentDB 'id' documentation needs better description

### ISSUE THREAD

**Issue by brettsam** [Azure/Azure-Functions#161]
The DocumentDB docs (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb#documentdb-input-binding) are misleading here: 

> id supports bindings similar to {queueTrigger}, which uses the string value of the queue message as the document Id.

In reality, the id property supports parameter binding: https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#parameter-binding. We should update that line to point to the param binding doc.

**Comment by markrey** [comment]
Need proper example as well. It took me almost an hour to understand and it is still not working!

**Comment by brettsam** [comment]
Direct query support is not supported (yet). It's close -- we're tracking it here: https://github.com/Azure/azure-webjobs-sdk-script/issues/289.

You can, however, use a DocumentClient object as a parameter and issue queries directly from within your functions. Your signature would be a little different since you want HTTP, but it would look something like:

Code:
```
#r "Microsoft.Azure.Documents.Client"
 
using System;
using Microsoft.Azure.Documents.Client;
 
public static void Run(string input, DocumentClient client, TraceWriter log)
{       
    // client has connection string already set up based on binding
}
```
Binding:
```
{
     "type": "documentDB",
      "name": "client",
      "connection": "myconnection_DOCUMENTDB",
      "direction": "in"
}
```

**Comment by markrey** [comment]
Thanks a lot @brettsam . I will start tracking that as well.

**Comment by mschmidt-healthx** [comment]
The documentation (and configuration UI) also appears to be missing the partitionKey element.  Using the advanced editor I was able to add it and actually get results from a partitioned collection (using a fixed partition key).  I'm interested too if there is a way to bind both the id and partition key to inputs from, say, a service bus queue message; there doesn't seem to be an obvious way of getting multiple values out of the one message for use in parameter bindings.

**Comment by mschmidt-healthx** [comment]
I was able to figure it out, I needed to create a POCO that a json document in the queue message would be bound to, and those field names are then available as binding parameters.  It's really not obvious though.

**Comment by lindydonna** [comment]
@mschmidt-healthx We've improved the bindings conceptual article. Could you see if this article helps make things more clear? https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#bind-to-custom-input-properties-in-a-binding-expression. Please provide any feedback.

**Comment by mschmidt-healthx** [comment]
@lindydonna - Yea, that's more clear, thanks.  

The documentdb documentation still seems to be missing any mention of the partitionkey being a valid parameter.  The input binding setup UI is also missing it as a parameter, I can only use it by editing the function.json directly.

Example:

```
    {
      "type": "documentDB",
      "name": "inputDocument",
      "databaseName": "logdb",
      "collectionName": "log",
      "id": "{documentId}",
      "partitionKey": "{partitionKey}",
      "connection": "test",
      "direction": "in"
    }
```

**Comment by lindydonna** [comment]
@mschmidt-healthx Good feedback!  @brettsam Did you add this feature?  We need to add it to the schema for function.json as well as [bindings.json](https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Bindings/bindings.json) so the portal picks it up. We'll also need a resource string.

**Comment by lindydonna** [comment]
The original feedback is in progress here: https://github.com/Microsoft/azure-docs-pr/pull/10887

**Comment by lindydonna** [comment]
@mschmidt-healthx The partitionKey issue is tracked here: [Add new DocDB partitionKey property to bindings\.json \#454](https://github.com/Azure/azure-webjobs-sdk-templates/issues/454)

Closing this issue as the DocDb article has been revised.
