### ISSUE TITLE
servicebus queue trigger function works from VS but not from cloud

### ISSUE THREAD

**Issue by pthibodeaux** [Azure/Azure-Functions#1615]
Wrote a simple service bus trigger function to process a service bus queue message.  It all works fine in Visual Studio, but when I deploy to the cloud, it is not picking up the queue messages.  I verified that the appsetting for the service bus connection string is deployed as well (and it shows in the portal under Configuration (Application Settings), but it still does not work.  Perhaps it needs a prefix, like I see for other settings????
I cannot find clear concise instructions on how to make this work.  Am I missing something?
I added app insights logging and see that the function is "running", but it never responds to queue messages.   It works fine from visual studio.   
Is there a way to "log" the appsettings when the function initiates - to confirm my setting?

**Comment by v-bbalaiagar** [comment]
Hi @pthibodeaux, Apologies for the delayed response, Are you changing the Azure Service Bus connection string in the "App Settings" pane in the Azure Portal? And if so, please include your app name (either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)).
