### ISSUE TITLE
"Warm" routing is slow

### ISSUE THREAD

**Issue by a-vishar** [Azure/Azure-Functions#1616]
Region: West Europe
Invocation Id: e5019951-0cc4-4136-89fe-cd824f0ecbda 

When invoking a function which is "warm" (called by a timer trigger, sometimes considerable time is lost to routing.

As you can see in the image below, routing to the function took ~400ms.

![image](https://user-images.githubusercontent.com/7255079/83799147-466f5880-a69d-11ea-8c64-6c4581eabbb4.png)

You can see that the function itself doesn't have any complex bindings:

![image](https://user-images.githubusercontent.com/7255079/83799319-86ced680-a69d-11ea-9d60-4e0d3b7c3405.png)

There is one bit of DI which is a pre-initialized singleton (in my Startup):

```
            var cosmosDataProvider = new CosmosDataProvider<SomeType>();
            builder.Services.AddSingleton<ICosmosDataProvider<SomeType>>(cosmosDataProvider);
```

**Comment by a-vishar** [comment]
Another good example of this (Invocation Id: 3c3f2400-9d4e-4fa3-99af-b1136b2b0909)

![image](https://user-images.githubusercontent.com/7255079/83804562-3c9e2300-a6a6-11ea-97ee-8f163591dc8f.png)


![image](https://user-images.githubusercontent.com/7255079/83805382-aff46480-a6a7-11ea-9d45-be547cde7bce.png)

**Comment by a-vishar** [comment]
Any update on this?

**Comment by a-vishar** [comment]
Any update on this?

**Comment by v-bbalaiagar** [comment]
Hi @a-vishar, Apologies for the delayed response, the issue was somehow lost in the trace. Please let us know if you are still seeing this issue, so that we will further look into the backend logs.

**Comment by v-bbalaiagar** [comment]
Hi @a-vishar, Closing this issue as there is no further activity, Feel free to re-open the issue with the latest invocation id, if at all you come across the issue in future.
