### ISSUE TITLE
Missing method exception when adding a message to a storage queue

### ISSUE THREAD

**Issue by GitMarJansen** [Azure/Azure-Functions#1617]
I am using a timer trigger to queue message in a storage queue. Out-of-the-blue, last friday the function stopped to work due to the following error:
Exception while executing function: UpdateVoiceworksRegistration Method not found: 'System.Net.Http.HttpContent Microsoft.Azure.Storage.Shared.Protocol.HttpContentFactory.BuildContentFromStream(System.IO.Stream, Int64, System.Nullable`1<Int64>, System.String, Microsoft.Azure.Storage.Core.Executor.RESTCommand`1<!!0>, Microsoft.Azure.Storage.OperationContext)'. Method not found: 'System.Net.Http.HttpContent Microsoft.Azure.Storage.Shared.Protocol.HttpContentFactory.BuildContentFromStream(System.IO.Stream, Int64, System.Nullable`1<Int64>, System.String, Microsoft.Azure.Storage.Core.Executor.RESTCommand`1<!!0>, Microsoft.Azure.Storage.OperationContext)

I didn't deploy anything to the environment. Redeploying the latest version also doesn't solve the problem.

I am using this overload. In this case, delay is a default timespan and the queueRequestOptions is null (I am using those in some cases to extend the MaxExecutionTime).

await cloudQueue.AddMessageAsync(new CloudQueueMessage(message), null, delay, queueRequestOptions, null);

**Comment by GitMarJansen** [comment]
Upgrading these nuget packages solved the problem. Was there a breaking change in the azure runtimes?
![image](https://user-images.githubusercontent.com/1133052/84014644-f33a2600-a97a-11ea-8289-9f8eaa50d33d.png)

**Comment by v-bbalaiagar** [comment]
Hi @GitMarJansen , Apologies for the delayed response, can we know if you are still seeing this issue

**Comment by GitMarJansen** [comment]
I'm not seeing this issue anymore. Looks like the update I mentioned fixed it. Still unknown what caused it at that moment
