### ISSUE TITLE
C# V3: Newtonsoft support

### ISSUE THREAD

**Issue by topres** [Azure/Azure-Functions#1618]
It appears that V3 of azure functions is using either System.Text.Json or another serializer by default when model binding in azure functions.

I have the following function:
     
        [FunctionName("Test")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "test")] Request request)
        {
            return new OkResult();
        }

        public class Request
        {
            public string SerialNumber { get; }

            public Request(string serialNumber)
            {
                SerialNumber = SerialNumber;
            }
        }

I have tried using the same extension methods used when doing this in MVC projects, like this:

    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder
                .Services
                .AddMvcCore()
                .AddNewtonsoftJson();
        }
    }

I am not looking for solutions to work with System.Text.Json, our team has decided that we want to use Newtonsoft for various reasons.

We would just very much like to use the built in model binding of the framework, to avoid taking in a `HttpRequest` and deserializing for each function.

**Question**
How do I use Newtonsoft in Dotnet Core Azure Functions V3?

**Comment by v-anvari** [comment]
Hi @topres , The ability to customize the deserializer stack is not a possible feature for now.

Closing this issue, please feel free to reach back to us in case of any further queries related to this issue

**Comment by Sti2nd** [comment]
Created a post on UserVoice. https://feedback.azure.com/forums/355860-azure-functions/suggestions/43644627-allow-to-use-newtonsoft-for-all-model-binding

I assume UserVoice is the correct channel since you closed the feature request here, @v-anvari ?

**Comment by v-anvari** [comment]
Hi @Sti2nd , Yes, That would be the right channel to raise a feedback or feature.
