### ISSUE TITLE
az functionapp vnet-integration add, allow adding a VNET for a function app running in a consumption plan

### ISSUE THREAD

**Issue by anilpras** [Azure/Azure-Functions#1619]
az functionapp vnet-integration add -g <RG Name> -n <function-AppName> --vnet <VNET Name> --subnet <SubNet Name>

The above command allows binding a VNET with the function app running in a Consumption Plan.

I am able to reproduce this for the function app "Powershell-func"
    "name": "Powershell-func",
    "management_state": "",
    <trimmed>
    "sku": "Dynamic",
    <trimmed>
    "vnet_name": "<trimmed>f4a54_default",

**Comment by v-bbalaiagar** [comment]
Hi @anilpras , Apologies for the delayed response, let us know if you were able to find a solution.

**Comment by anilpras** [comment]
@v-bbalaiagar - Essentially the command should not allow the VNET integration for the function app running in a consumption plan. The idea was to report a bug.

**Comment by v-bbalaiagar** [comment]
Hi @anilpras, Apologies for the delayed response, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Closing this issue as the new issue is opened. Please provide your inputs here- https://github.com/Azure/azure-cli/issues/19469
