### ISSUE TITLE
Azure Service Bus Trigger Issue(s)

### ISSUE THREAD

**Issue by AndyWorral** [Azure/Azure-Functions#1621]
Hello,

I've been working with internal Microsoft support on a couple of Function portal issues as well as brought to their attention this issue: 

https://github.com/Azure/azure-functions-servicebus-extension/issues/77 

that ticket was the driver for some of the discovered portal issues I previously mentioned.

I was informed that given the age of some of the issues under that project in GitHub that I may get more attention if I posted in the "main" github.  I'm honestly not entirely sure which project would be the "main" project, but since the issue is functions related I thought I would start here.

If this is not the correct place to post, then please direct me to the correct place.  If it is I would love some assistance in figuring out how to handle the Service Bus message processing failing after the execution of a function job.

Thanks!

**Comment by v-anvari** [comment]
Hi @AndyWorral , Please accept my apology for the delay in response. Kindly let us know if you were able to find a solution. The mistakes in monitor logs must be a temporary glitch. We are dealing with one such issue related to scale controller events.

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
