### ISSUE TITLE
Best practices for inter-service communication.

### ISSUE THREAD

**Issue by kaveenr** [Azure/Azure-Functions#1623]
I'm aware of the documentation provided for [Durable functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp)

But what are the best practices for inter-service communication that spans multiple function-apps? Can Durable functions be used for this scenario?

**Comment by v-anvari** [comment]
Hi @kaveenr , Apologies for the delayed response. You can use Durable functions for this scenario where you use multiple functions. But, the ask is not completely clear. If you are still looking for a solution to this scenario, please feel free to re-open the issue or a new issue.
