### ISSUE TITLE
Update Functions CI article to mention the Project app setting

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#163]
I've seen a few questions from customers about how to set the right directory for deployment.

I suggest we updated this article: https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment with the following:
- Link to https://github.com/projectkudu/kudu/wiki/Customizing-deployments
- Show a sample .deployment file such as the following:
   `[config]
project = MyFunctionRoot
   `

**Comment by SyntaxC4** [comment]
I have documented some of this as part of the ARM Template document: https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code
