### ISSUE TITLE
Azure functions eventhub trigger broken without any code change

### ISSUE THREAD

**Issue by dhanush987** [Azure/Azure-Functions#1632]
logging.info('QC EventHub trigger for: %s',
                 event.get_body().decode('utf-8'))
    data = json.loads(event.get_body().decode('utf-8'))

Error: 
2020-06-20 01:02:24.268
Result: Failure Exception: AttributeError: 'list' object has no attribute 'body_as_json' Stack: File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 338, in _handle__invocation_request self.__run_sync_func, invocation_id, fi.func, args) File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 470, in __run_sync_func return func(**params) File "/home/site/wwwroot/EventHubTrigger1/__init__.py", line 22, in main logging.info(event.body_as_json(encoding='UTF-8'))

This function was not even changed from last couple of weeks, Not sure why this is happening

**Comment by bGridSven** [comment]
We are experiencing the exact same thing. Nothing changed, but suddenly it stopped working completely. Suddenly event has turned into a list.

**Comment by grik001** [comment]
Are you also experiencing some sort of delays or even messages not being read from EH?

**Comment by v-bbalaiagar** [comment]
Hi @dhanush987,  Apologies for the delayed response, Let us know if you are still facing the issues, if yes could you please provide us the invocation id of the error and time stamp during the error to get the logs and check the cause.

**Comment by v-bbalaiagar** [comment]
Hi @dhanush987, Closing this issue as there is no response, Please feel free to reach back to us in case of any further queries related to this issue.
