### ISSUE TITLE
Azure Functions on AKS + KEDA

### ISSUE THREAD

**Issue by alexandrelimait** [Azure/Azure-Functions#1633]
Hi,
It is not an issue, but a doubt.
I containerized my Function and deploy it on AKS + KEDA.
To use the Function I have an APIM in front of, in this APIM I inject the headers x-functions-key with the keys available in the Function to authenticate.
If I start with AKS, do I need to change the way I authenticate or there are some way to retrieve the keys inside the AKS? I am asking because i have a process to do a key rotation and another point if will i lost the IAM as well? 

![image](https://user-images.githubusercontent.com/47575699/85406456-24f9e200-b562-11ea-8968-9bd3e1e5a7cf.png)

**Comment by v-anvari** [comment]
Hi @alexandrelimait , Apologies for the delayed response, The Authentication mechanism would still work in AKS the same way. You can continue to use either the header or the query string.

Tagging @ahmelsayed , for further insights on how to retrieve the keys

**Comment by ahmelsayed** [comment]
Yes, you can set your keys in a Kubernetes Secret, then set an env `AzureWebJobsSecretStorageType=kubernetes` You can then either create a serviceAccount to give the POD permissions to query for that secret, or mount it to the file system using Kubernetes volume mount. More on that here https://github.com/Azure/azure-functions-host/pull/4462
