### ISSUE TITLE
[UX] - Better error message needed

### ISSUE THREAD

**Issue by winterlimelight** [Azure/Azure-Functions#1634]
The following host.json gave an error in the Azure Portal functions overview page: "There are some issues with your runtime version. Click here for details."
Clicking on 'details' gives no more information, but winds up taking me to the configuration page.
Turns out the function timeout is too high for the consumption plan (it was supposed to be 00:10:00).

```
host.json
{
    "version": "2.0",
    "functionTimeout": "01:00:00"
}
```

Is there someway the nature of such problems could be better communicated?
 
The message "There are some issues with your runtime version" is misleading at best given the error was to do with host.json settings and nothing to do with the runtime version (v3, dotnetcore3.1).

**Comment by btardif** [comment]
@takyyon can you take a look and provide an update?

**Comment by takyyon** [comment]
We have made an update for this and it should fly out with our next deployment
