### ISSUE TITLE
[CLI] Should the CLI support Functions v1

### ISSUE THREAD

**Issue by gzuber** [Azure/Azure-Functions#1635]
As it stands today, a user is not able to create a Functions v1 app through the CLI. I implemented a change [here](https://github.com/Azure/azure-cli/pull/11987) that added support for v3 apps and allowed a user to choose extension version with a flag. The [issue](https://github.com/Azure/azure-cli/issues/11349) I was fixing was only to add v3 so I didn't add an option to specify v1. Is this something we need?

It's also important to note that I don't think a user has ever been able to create a v1 function app (at least since v2 was released) since the CLI hard coded extension version to 2 before these changes.

**Comment by gzuber** [comment]
cc @fabiocav @pragnagopa for their input

**Comment by fabiocav** [comment]
There are no plans to add support for 1.0 at this point.
