### ISSUE TITLE
Unable to regenerate key from function app with managed identity

### ISSUE THREAD

**Issue by jlichwa** [Azure/Azure-Functions#1638]
I have a function application with MSI assigned and I tried RedisCacheContributor and an Owner role assignment on Redis Cache service, but I'm still getting an error.

I'm getting :
New-AzRedisCacheKey : The client 'bd42cf38-c4d8-4469-b14f-b27eb8707a21' with object id 'bd42cf38-c4d8-4469-b14f-b27eb8707a21' does not have authorization to perform action 'Microsoft.Cache/Redis/regenerateKey/action'

I

**Comment by SeaDude** [comment]
Curious if its a **s**ystem-**a**ssigned (SAMI) or user-assigned **m**anaged **i**dentity? I came across a similar issue today when trying to assign `Microsoft.Security/something/read` permissions to a SAMI. 

`.../read` at a Resource Group (RG) scope was not enough. I had to assign `Microsoft.Security/something/**owner**` at the RG level. 
Sounds like you already tried this. 

One thing to try... I assigned all permissions at the SAMI *itself* not on the Resource end.

**Example:**
- From the `Identity` tab of the resource with the SAMI, click `Azure role assignments`
![image](https://user-images.githubusercontent.com/8636973/85655416-5529a980-b664-11ea-85f3-4020e12de147.png)
- Click `Add role assignment` then select the Scope
- Search for role accordingly
![image](https://user-images.githubusercontent.com/8636973/85655547-82765780-b664-11ea-83d8-65fea10b8bdc.png)

This method is an _alternative_ to going to the resource you wish to assign a role **to** and selecting the SAMI. 

**Example2:** 
- From the resource you wish to assign access to, click `Access control (IAM)`
- `Add a role assignment`
- Select role and type of identity
- Select the identity and click `Save`
![image](https://user-images.githubusercontent.com/8636973/85656126-41327780-b665-11ea-8577-4bc1abcdd375.png)

(Hope this makes sense.)

**Comment by jlichwa** [comment]
It was a mistake on my part #please-close thank you

**Comment by jlichwa** [comment]
#please-close
