### ISSUE TITLE
Document use of Azure Storage lock when creating a Function App and storage account together

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#164]
When creating a Function App, you can create a new storage account at the same time. Since it ends up with a random auto-generated name, we had instances of customers deleting the storage account. So, we added a lock at the ARM level that prevents the storage account from being deleted unless the customer takes an extra step.

People who have only contributor access to a subscription cannot create storage locks, due to the design of ARM. So, we are getting customer support cases where customers think they can't create a Function App.

We need to document the dependence on storage, explain the lock, and explain the workaround which is to choose an existing storage account if you have only contributor access. See https://github.com/projectkudu/AzureFunctionsPortal/issues/831.

**Comment by SyntaxC4** [comment]
@lindydonna - Could you provide the text needed for this and where you think it would sit best in the documentation?

**Comment by lindydonna** [comment]
The storage account lock is no longer created.
