### ISSUE TITLE
Could not load file or assembly 'NCrontab, Version=3.3.1.0 on Microsoft.NET.Sdk.Functions 3.0.7

### ISSUE THREAD

**Issue by Tri125** [Azure/Azure-Functions#1641]
[Repo with minimal repro case](https://github.com/Tri125/azurefunction-bug-report-ncrontab/tree/master)

# Description
On an Azure function with `Microsoft.NET.Sdk.Functions 3.0.7` if your function is calling a class library that use `NCronTab 3.3.1` the function will throw the following error:

``
System.Private.CoreLib: Exception while executing function: Function1. ClassLibrary1: Could not load file or assembly 'NCrontab, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
``

The issue is not present on `Microsoft.NET.Sdk.Functions to 3.0.3`. I found the issue to be present as early as 3.0.4.

The Azure function target netcore 3.1 and use the AzureFunctionsVersion v3.

The Class Library target netstandard 2.1.

**Comment by Nazgaul** [comment]
Microsoft.NET.Sdk.Functions version3.0.7 uses NCrontab.Signed version 3.3.0  
I changed my csproj to have the same nuget package and it works

**Comment by georgemathieson** [comment]
I'm also getting this issue with `Microsoft.NET.Sdk.Functions 3.0.9`. Dropping back to `3.0.3` isn't a great solution.

**Comment by Tri125** [comment]
Thank you!
