### ISSUE TITLE
Function Dependency Injection fails when having multiple functions

### ISSUE THREAD

**Issue by henrikweimenhog** [Azure/Azure-Functions#1642]
I have 5 functions running in the same AppService. I recently switched to DI and it works as expected, but only for the last published function. 
As soon as I republish a function the others stop working.
In application insight I get things like:
Unable to resolve service for type 'Parking.Logic.Interfaces.IReservationRepo' while attempting to activate 'Parking.Functions.ParkingExpireAlert'.

**Comment by v-bbalaiagar** [comment]
Hi @henrikweimenhog, Apologies for the delayed response, Were you able to find a solution. If you still having this issue persisting, then let us know the repro steps for us to understand the error.

**Comment by henrikweimenhog** [comment]
I gave up on using DI and just new-ed up my classes instead.
There is another issue when publishing multiple functions: the Settings value "WEBSITE_RUN_FROM_PACKAGE" is set to a 1. And al the functions disappear. So manually correcting this setting will make the functions appear again.
Maybe that would have solved my DI issue as well.  Not sure, just fishing...

**Comment by v-bbalaiagar** [comment]
Hi @henrikweimenhog, We will have to look at the scenario to provide a solution. If you can provide us the repro steps and the namespaces used and also the code that is busted, we can try to repro from our end to get the error.

**Comment by henrikweimenhog** [comment]
I'm sorry this was a long ago. I have nothing for you guys. I worked around it.

**Comment by v-bbalaiagar** [comment]
Hi @henrikweimenhog, Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
