### ISSUE TITLE
VS2019 Functions template for Queue Storage uses old major version

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/Azure-Functions#1648]
The template references `Microsoft.Azure.WebJobs.Extensions.Storage` version 3.0.10 when 4.0.2 is available

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new Azure Functions with Storage Queue trigger
2. Reference a package that has the latest major version of Microsoft.Azure.WebJobs.Extensions.Storage as a dependency

NuGet will complain about package downgrade that requires a manual override.

#### Expected behaviour

The template should be updated to reference the latest major version of Microsoft.Azure.WebJobs.Extensions.Storage should

#### Known workarounds

Explicitly override package reference 

#### Other

Microsoft Visual Studio Enterprise 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.04084

Azure Functions and Web Jobs Tools   16.6.954.58314

**Comment by fabiocav** [comment]
@soninaren we have an issue tracking template updates for the new storage extension, right? Can you please provide a link to that? If we don't have one, I can move this to the templates repo.

@paulbatum @brettsam @anthonychu , FYI

**Comment by soninaren** [comment]
> @soninaren we have an issue tracking template updates for the new storage extension, right? Can you please provide a link to that? If we don't have one, I can move this to the templates repo.

Here is the issue tracking extension version updates in dotnet templates https://github.com/Azure/azure-functions-templates/issues/957
