### ISSUE TITLE
Use of ICloudBlob/CloudBlockBlob/CloudAppendBlob/CloudPageBlob requires "inout" binding type

### ISSUE THREAD

**Issue by brettsam** [Azure/Azure-Functions#165]
The list of blob output types here lists ICloudBlob/CloudBlockBlob/CloudPageBlob: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#output-usage

First, we should include CloudAppendBlob there.
Second, you actually need to use "inout" as your binding direction when using these.

```
{
  "type": "blob",
  "name": "appendBlob",
  "path": "container/{rand-guid}.txt",
  "connection": "AzureWebJobsStorage",
  "direction": "inout"
}
```

**Comment by brettsam** [comment]
And, we should add "inout" to the list of possible binding directions here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference

**Comment by lindydonna** [comment]
The bindings concepts article has "inout". I've updated the blob documentation here: https://github.com/Microsoft/azure-docs-pr/pull/14047
