### ISSUE TITLE
servicebus queue trigger function is not working after publishing it to azure

### ISSUE THREAD

**Issue by akhil117** [Azure/Azure-Functions#1652]
Hi,

I have implemented an Azure function with service bus queue trigger, using visual studio 2019. the function works fine when I am running locally, but after publish it to the azure. the function is not working. it does not trigger at all.

I also checked, service bus connection string in azure portal (configuration tab), the key and value all are correct.

any idea why this happen and how to fix that please?

Thanks

**Comment by v-bbalaiagar** [comment]
Hi @akhil117, Apologies for the delayed response, We tried to reproduce and we are able to trigger the function as expected. Let us know if you are still facing the same issue.

**Comment by v-bbalaiagar** [comment]
Hi @akhil117, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue
