### ISSUE TITLE
Build fails with Microsoft.NET.Sdk.Functions 3.0.8 due to unsupported TaskAssemblyDirectory parameter in targets file.

### ISSUE THREAD

**Issue by marcduiker** [Azure/Azure-Functions#1653]
I'm building a .NET Core 3 Function App in VS2019 (16.6.1), Azure Functions, and Web Job Tools 16.6.936.3669.

## Behaviour
I upgraded Microsoft.NET.Sdk.Functions from 3.0.6 to 3.0.8 and now I get the following errors:

```
Error MSB4063 The "GenerateFunctions" task could not be initialized with its input parameters. <PROJECT> C:\Users\<USER>\.nuget\packages\microsoft.net.sdk.functions\3.0.8\build\Microsoft.NET.Sdk.Functions.Build.targets	44
Error MSB4064 The "TaskAssemblyDirectory" parameter is not supported by the "GenerateFunctions" task. Verify the parameter exists on the task, and it is a settable public instance property. <PROJECT> C:\Users\<USER>\.nuget\packages\microsoft.net.sdk.functions\3.0.8\build\Microsoft.NET.Sdk.Functions.Build.targets	51
```

This is the part in the targets file it is complaining about:
```xml
 <GenerateFunctions
      TargetPath="$(TargetDir)bin\$(TargetFileName)"
      OutputPath="$(TargetDir)"
      UseNETCoreGenerator="$(UseNETCoreGenerator)"
      UseNETFrameworkGenerator="$(UseNETFrameworkGenerator)"
      UserProvidedFunctionJsonFiles="@(UserProvidedFunctionJsonFiles)" 
      FunctionsInDependencies="$(FunctionsInDependencies)"
      TaskAssemblyDirectory="$(_FunctionsTasksDir)"/>
  </Target>
```
## Expected Behaviour

The build should complete without warnings.

## Workaround

Downgrading to Microsoft.NET.Sdk.Functions 3.0.7 and the build works again.

**Comment by marcduiker** [comment]
I just upgraded VS2019 to 16.6.3 with Azure Functions and Web Jobs Tools 16.6.954.58314 and then SDK 3.0.8 works as expected.

**Comment by v-bbalaiagar** [comment]
Hi @marcduiker, Apologies for the delayed response, Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by marcduiker** [comment]
No worries, the latest SDK works fine for me. This can be closed.

**Comment by v-bbalaiagar** [comment]
Hi @marcduiker, Closing this issue as resolved, Please feel free to reach back to us in case of any further queries related to this issue.
