### ISSUE TITLE
Auto swap is not seamless unlike what the official documentation claims

### ISSUE THREAD

**Issue by petro2050** [Azure/Azure-Functions#1655]
I'm deploying my function app into a slot with auto swap turned on. Unfortunately during swapping, I get 503 errors when I repeatedly query my public endpoints. This is a very frustrating experience for end-users. I created this SO question for help: https://stackoverflow.com/questions/62767337/azure-function-deployments-cause-brief-503-errors-even-when-auto-swap-is-turned/62863861#62863861.

I'd really appreciate your input on how this issue can be fixed. I was under the impression that everything would be seamless to the end users.

**Comment by v-bbalaiagar** [comment]
Hi @petro2050, We apologize for the delayed response, were you able to find a solution to this problem. Do let us know if you want us to look at this issue further.

**Comment by mm-gmbd** [comment]
bump

**Comment by v-bbalaiagar** [comment]
Hi @mm-gmbd, Here is a [tracking issue](https://github.com/Azure/Azure-Functions/issues/862) which is being addressed and worked upon on a similar scenario, Please find the space for further updates.
