### ISSUE TITLE
Clearer documentation of IIS Hidden Segments features as it relates to Function Apps

### ISSUE THREAD

**Issue by AlexDickerson** [Azure/Azure-Functions#1656]
Please describe the documentation request or issue.  Be as specific as possible.
This Hidden Segments feature of IIS blocks certain keywords from being used as Function App Names/Endpoints.
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/hiddensegments/

More concise documentation as to the words affected by this feature would be appreciated.

**Comment by v-bbalaiagar** [comment]
Hi @AlexDickerson, Closing this issue as document issue is opened. Please provide your inputs here -  https://github.com/MicrosoftDocs/azure-docs/issues/80704
