### ISSUE TITLE
[Visual Studio] PublishTemp directory is not cleaned before publish

### ISSUE THREAD

**Issue by martijns** [Azure/Azure-Functions#166]
When publishing a function project from Visual Studio to a function app service using web deploy, the obj\PublishTemp directory is not cleaned. Using a feature like "Remove additional files at destination" behaves unexpected because of this.

Reproduction steps:
1) Create a function
2) Publish to a function app
3) Rename the function directory
4) Publish using "Remove additional files at destination" checked
5) Find two functions (original + renamed) running in the portal

Right-click (project or solution) => Clean does not clean the PublishTemp directory either.

Workaround is to manually remove the PublishTemp directory and publish again.

**Comment by lindydonna** [comment]
Handled by new version of VS 2017 tooling
