### ISSUE TITLE
HttpTrigger custom type binding paramater cannot be named 'command'

### ISSUE THREAD

**Issue by mikanyg** [Azure/Azure-Functions#1660]
Just run into an issue with HttpTrigger binding to a custom type.

I get the following error: *The 'RunCommand' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'RunCommand'. Microsoft.Azure.WebJobs.Host: Can't bind parameter 'command' to type 'MyType'*
Example with error: 
```
    public static class DeviceFunctions
    {
        [FunctionName(nameof(RunCommand))]
        public static async Task<IActionResult> RunCommand([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "devices/{deviceId}")]MyType command, string deviceId, ILogger log)
        {
            return new OkResult();
        }
    }

    public class MyType
    {
        public string Command { get; set; }        
    }
```

Working example
```
public static class DeviceFunctions
    {
        [FunctionName(nameof(RunCommand))]
        public static async Task<IActionResult> RunCommand([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "devices/{deviceId}")]MyType cmd, string deviceId, ILogger log)
        {
            return new OkResult();
        }
    }

    public class MyType
    {
        public string Command { get; set; }        
    }
```

Only difference is the name of the parameter the HttpTrigger is bound to. **command** is not working, **cmd** is. If its by design that certains names are reserved it should be documented.

Runtime: Azure Function V3
Visual Studio 2019 function project.

**Comment by Jtango18** [comment]
This doesn't appear to be relevant to the name `command` but is an issue that occurs when you use the same name as the property name in the Request object. 

So the following fails in the same way.

```csharp
    [FunctionName("AZRepro1660")]
    public static async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "devices/{deviceId}")] MyType cmd,
         ILogger log)
    {
       log.LogInformation("C# HTTP trigger function processed a request.");
        return new OkObjectResult("JT Rules - " + cmd.Cmd);
    }

    public class MyType
    {
        public string Cmd { get; set; }
    }
```

Looks like an issue with reflection lookup in the FunctionIndexer

**Comment by v-bbalaiagar** [comment]
Hi @mikanyg, Apologies for the delayed response. Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by mikanyg** [comment]
@v-bbalaiagar as I recall, I simply renamed the parameter. My reason for opening the issue was that I could not find any docs stating the rules for naming of parameters. So I spend a long time to figure out why I got the error.

**Comment by v-bbalaiagar** [comment]
Hi @mikanyg, Apologies for the delayed response. We don't have any document stating the rules for naming of parameters

**Comment by v-bbalaiagar** [comment]
Hi @mikanyg, Closing this issue as we don't have any document, please feel free to reach back to us in case of any further queries related to this issue.
