### ISSUE TITLE
e_sqlite3.dll not being properly loaded with Azure Functions v1 (.NET 4.8) and V3 (.NET Core 3.1)

### ISSUE THREAD

**Issue by aderderian** [Azure/Azure-Functions#1664]
I have an integration environment I am building and SDKs/APIs span the entire .NET universe. I have to support a legacy Azure Function V1 with .NET 4.8 to leverage an existing SDK. I also have Functions V3 for newer APIs. In the middle tier I am leveraging .NET Standard in my data services in order to provide common code for both of these functions. The database tier uses Dapper and we support SQLite for local dev. For some reason when my code runs in either of these functions I receive an exception indicated that "e_sqlite3.dll" is not found. 

For Azure Functions V3 the workaround is to just copy the missing DLL manually into the bin directory and it runs. This is fine for local dev, but still something is not being properly loaded. 

In V1, copying the dll into the bin does not work and the dll is not found. Is there a workaround anyone can suggest? It is either something with Microsoft.Data.Sqlite and the dependency chain or the way Azure Functions is loading this particular dll. Any ideas on manually including this dll in the function so it is loaded?

Data Project :

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.35" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.35" />
    <PackageReference Include="FluentMigrator.Abstractions" Version="3.2.6" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="3.1.6" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="3.1.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

**Comment by aderderian** [comment]
Anyone got a temporary workaround for me perhaps? With Functions V1, the dll won't load if I just put it in the bin. Tried adding it to my PATH and everywhere else I could think but it won't load the non-manged assembly e_sqlite3.dll. Need some options to keep moving forward : https://github.com/ericsink/SQLitePCL.raw/issues/343

**Comment by claudiuchis** [comment]
Downgrading Microsoft.Data.Sqlite nuget package from 5.0.0 to 3.1.14 fixed the problem for me.

**Comment by v-bbalaiagar** [comment]
Hi @aderderian, Closing this issue as duplicate, Here is a [tracking issue](https://github.com/ericsink/SQLitePCL.raw/issues/343) which is being addressed and worked upon on a similar scenario, Please find the space for further updates.
