### ISSUE TITLE
Startup will not execute if UserSecretsId is present and if project is also referencing a RCL

### ISSUE THREAD

**Issue by hermesramos** [Azure/Azure-Functions#1667]
Startup will not execute if the two following conditions are met:

1. Azure Functions .csproj file contains UserSecretsId;
2. Azure Functions project references a Razor Class Library.

Attached is a minimal sample project to reproduce the issue.

Thanks
[FunctionApp1.zip](https://github.com/Azure/Azure-Functions/files/4985386/FunctionApp1.zip)

**Comment by v-bbalaiagar** [comment]
Hi @hermesramos, We apologize for the delayed response, were you able to find a solution to this problem. Do let us know if you want us to look at this issue further.

**Comment by v-bbalaiagar** [comment]
Hi @hermesramos, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
