### ISSUE TITLE
Can't save file

### ISSUE THREAD

**Issue by bszewczyk** [Azure/Azure-Functions#1669]
I'm using python Azure Functions to create and save math models. I was able to save them in the past but since today I'm getting error:

Result: Failure
Exception: OSError: [Errno 30] Read-only file system: 'model_45c4a17e-f175-481d-893b-678f51cb8c75_3.sav'
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 345, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/CreateModel_Function_CreateModel/__init__.py", line 37, in main
    moduleSerilizer.save_model(best_model, predictions_to_save, str(model_id) + '.sav')
  File "/home/site/wwwroot/Helpers/Serilizer.py", line 7, in save_model
    joblib.dump(model, "model_" + filename)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 501, in dump
    with open(filename, 'wb') as f:

This is my python code;

    joblib.dump(model, "model_" + filename)
    joblib.dump(predictions, "predictions_" + filename)
    block_blob_service = BlockBlobService(account_name=os.environ["StorageAccount"],
                                          account_key=os.environ["StorageKey"])
    block_blob_service.create_blob_from_path('aml-models', filename, "model_" + filename)
    block_blob_service.create_blob_from_path('aml-predictions', filename, "predictions_" + filename)

**Comment by v-bbalaiagar** [comment]
Hi @bszewczyk, We apologize for the delayed response, were you able to find a solution to this problem. Do let us know if you want us to look at this issue further.

**Comment by v-bbalaiagar** [comment]
Hi @bszewczyk, Closing this issue as there is no response, Please feel free to reach back to us in case of any further queries related to this issue.
