### ISSUE TITLE
[azure-cli] Add support for CustomHandlers

### ISSUE THREAD

**Issue by gzuber** [Azure/Azure-Functions#1673]
Due to the changes to the stacks API caused by [custom handlers](https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/issues/8) (PR [here](https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/13)), the CLI can't assume linuxFxVersion will be in the Stacks API site configs.

**Comment by pragnagopa** [comment]
@gzuber - is it ok to use this issue to track adding support for creating CustomHandlers?

**Comment by pragnagopa** [comment]
cc @anthonychu

**Comment by gzuber** [comment]
> @gzuber - is it ok to use this issue to track adding support for creating CustomHandlers?

How big of an item would supporting CustomHandlers be? If it's just updating the CLI's stacks json, then that makes sense.

But anything bigger we might want to make a separate issue because this is a quick fix

**Comment by pragnagopa** [comment]
Updated the title. I believe this is just about updating stacks and testing. If it requires more work, then please open other specific issues. Thanks!

**Comment by gzuber** [comment]
Resolved by https://github.com/Azure/azure-cli/pull/15170
