### ISSUE TITLE
Using System.Text.Json with Azure Functions

### ISSUE THREAD

**Issue by andres-j** [Azure/Azure-Functions#1676]
While attempting to use [System.Text.Json](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) in our functions app we have run into an issue where the returned IMvcCoreBuilder's _AddJsonOptions_ function expects an _MvcJsonOptions_ object. The _MvcJsonOptions_ object contains only _SerializerSettings_, which accepts only Newtonsoft-specific types for converters and options:

![image](https://user-images.githubusercontent.com/17058214/89321807-61d0f280-d651-11ea-9153-441c02fd641a.png)

This in turn prevents us from using System.Text.Json or applying json options/converters that use System.Text.Json. The expected behavior is an options object that implements _AddJsonOptions_  and accepts json converters that use System.Text.Json

**Comment by andres-j** [comment]
We have identified a possible fix by including 

```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

in our project file. Our only concern is whether adding this dependency directly might interfere with WebJobs specific dependencies designed to work with Azure Functions?

**Comment by andres-j** [comment]
Unfortunately this is not a viable solution - while it allows the project to compile this does not actually configure what is used to serialize a response. The application continues to serialize following the separate (and unconfigurable) webjobs framework configuration

**Comment by v-bbalaiagar** [comment]
Hi @andres-j, Apologies for the delayed response, Were you able to find a solution. Let us know if you are still seeing the same issue.

**Comment by v-bbalaiagar** [comment]
Hi @andres-j, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue.
