### ISSUE TITLE
Edit, commit to repo, and deploy site compressor extension

### ISSUE THREAD

**Issue by mhoeger** [Azure/Azure-Functions#1677]
Deploy duplicate compressor that creates hardlinks using prebuilt hashes.txt file

https://github.com/Azure/azure-functions-host/issues/5787

**Comment by mhoeger** [comment]
I was OOF this past sprint, bumping forward (cc: @pragnagopa)

**Comment by pragnagopa** [comment]
Moving to Traiged due to higher priority items.

**Comment by pragnagopa** [comment]
@fabiocav - bringing this to sprint 85 as part of #6592

**Comment by fabiocav** [comment]
PR is out against the Antares codebase. Moving to 86 as it won't be completed this sprint.

**Comment by pragnagopa** [comment]
This is checked in to ANT91.
