### ISSUE TITLE
YAML: Remove additional files at destination

### ISSUE THREAD

**Issue by petro2050** [Azure/Azure-Functions#1679]
I'd like to check "remove additional files at destination" option when deploying my function app via a yaml pipeline. How is this accomplished exactly? I don't see it in the `Azure Functions` task.

![image1](https://user-images.githubusercontent.com/62858360/89485792-2aed0080-d767-11ea-9ec5-0901321fcb33.PNG)

**Comment by lspangler584** [comment]
Any updates to this question?

**Comment by v-anvari** [comment]
@dariagrigoriu @apawast , can you share more inputs for this question.

**Comment by v-anvari** [comment]
Hi @petro2050 , Have you tried using Git hub actions as it is an alternative option for pipelines. [Use GitHub Actions to make code updates in Azure Functions | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=dotnet)

Closing this issue, please feel free to reach back to us  in case of any further queries related to this issue
