### ISSUE TITLE
Add "Try Functions" to pages which reference the "Free Trial"

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#168]
Can we review the documentation pages for areas where we reference the "Free Trial" and include a link to [Try Azure](https://functions.azure.com/try) so that we can encourage customers to try Functions without having to sign up for an account.

**Comment by SyntaxC4** [comment]
We should make sure that we exclude this from unsupported features. I think only Functions with Timer & Storage are support.

**Comment by ggailey777** [comment]
Final missing **Try it now** additions are part of [this PR]( https://github.com/Microsoft/azure-docs-pr/pull/8332).
