### ISSUE TITLE
Timer triggers - required static class/function entrypoint?

### ISSUE THREAD

**Issue by VaclavK** [Azure/Azure-Functions#1680]
Hi,

am I correct that timer triggered functions (v3) must be represented by static entrypoint in a static class? I see all samples as such. When a  non static timer triggered functions is deployed to an  actual Function App Service (as in backed by actual app service plan), we see it is not triggered. Converting back to static flavour immediately resolves this - timers are honoured and function wakes up 

I am trying to understand whether such behavioural is expected and whether the static requirement is documented - the major side effect is the DI (as it relies is constructor based) not being available..

for http triggered functions, they are happily "non static"

**Comment by klenium** [comment]
No, it is not required. While the documentation and generated files in Visual Studio contain static classes/methods, the function works fine without them. I have a timer triggered method (also uses constructor DI to connect to the database) that runs perfectly every day. You may check if there is any other error in your code.

**Comment by VaclavK** [comment]
I have resolved this in the meantime - being unable to reproduce the original issue

may be good idea to provide non static samples in the doco - I think they are all remnants of Azure Functions v2 world

**Comment by klenium** [comment]
V2 also accepted non-static functions. :) I think the reason is that when you create a new console application, the Main method is static too. And if you have only one function, why not make the method and its class static. Probably Azure Function can reach better performance. The samples didn't do any complex job, so the default static method was fine for them I think.

**Comment by VaclavK** [comment]
yeah you are probably right...closing then
