### ISSUE TITLE
Class with a namespace not starting in "Function" won't log

### ISSUE THREAD

**Issue by elias-rod** [Azure/Azure-Functions#1681]
A class that is injected won't log if the namespace doesn't start with Function. That means that FunctionAnything will work but AFunction won't. I leave a sample repo [here ](https://github.com/elias-rod/Functions-V3-sample)that logs properly and if you change the namespace [here](https://github.com/elias-rod/Functions-V3-sample/blob/master/MyService.cs#L7) to something not starting with "Function" it won't log.

**Comment by Jtango18** [comment]
Hey there, thought this was an interesting issue so forked your repo in an attempt to replicate. You can take a look here: [https://github.com/Jtango18/AF-1681-Repro](https://github.com/Jtango18/AF-1681-Repro)

Added some write up about the results, but ultimately is appears to work as expected for me.

Hope this helps.

**Comment by elias-rod** [comment]
Indeed, now it has been solved, thanks!
