### ISSUE TITLE
Azure Function with service bus trigger - autoComplete and maxAutoRenewDuration

### ISSUE THREAD

**Issue by asipras** [Azure/Azure-Functions#1685]
I have Azure Function with service bus trigger running on AKS. I have few question around configuration settings in host.json. The function can run for longer than 10 mins hence i have set the functionTimeout setting to 01:00:00.

Currently I have set autoComplete = true in my host.json. As per documentation here, [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp]

> The Functions runtime receives a message in PeekLock mode. It calls Complete on the message if the function finishes successfully, or calls Abandon if the function fails. If the function runs longer than the PeekLock timeout, the lock is automatically renewed **as long as the function** is running.

When i run my function on development machine it runs for over 10 mins without any errors but then i see the following error by Azure function runtime in my terminal window

> Message processing error (Action=Complete, ClientId=MessageReceiver1calculation_requests, EntityPath=calculation_requests, Endpoint=mhservice12.servicebus.windows.net)
[8/11/2020 8:21:33 PM] Microsoft.Azure.ServiceBus: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:633c9f49-7063-441e-a02f-9e33c2cca04b, TrackingId:9a1f2e8d0000e97b0005ea6a5f32fc40_G11_B26, SystemTracker:mhservice12:Queue:calculation_requests, Timestamp:2020-08-11T20:21:33.

**Do i have to set maxAutoRenewDuration setting?**

 The documentation says that the max value for maxAutoRenewDuration is 5 minutes as per service bus documentation but I cannot find this anywhere.

> The maxAutoRenewDuration is configurable in host.json, which maps to OnMessageOptions.MaxAutoRenewDuration. The maximum allowed for this setting is 5 minutes according to the **Service Bus documentation**, whereas you can increase the Functions time limit from the default of 5 minutes to 10 minutes. For Service Bus functions you wouldn’t want to do that then, because you’d exceed the Service Bus renewal limit.

Also, if we can configure functionTimeout to whatever value when running on AKS shouldn't maxAutoRenewDuration be configurable to whatever value the user wants?

Can anybody explain me how to configure Azure Function runtime with service bus trigger with autoComplete=true setting so that it does not throw exception if the function finishes within functionTimeout value.

**Comment by v-bbalaiagar** [comment]
Hi @asipras, Closing this issue as duplicate. For more updates please follow the space - https://github.com/Azure/azure-functions-host/issues/6500
