### ISSUE TITLE
How to Scope Hierarchical Namespace Permissions to Directory?

### ISSUE THREAD

**Issue by ericthomas1** [Azure/Azure-Functions#1686]
Hello,

I want to create an Azure Function triggered by file uploads to a DataLake Gen2 directory. I've created the Function and an associated System-Assigned Managed Identity (SAMI). 

**Questions:**
- How do I scope the SAMI permissions down to a specific directory within the DataLake rather than supplying the Function with the entire DataLake's connection string?

**Example:**
![image](https://user-images.githubusercontent.com/42788729/90259278-989bcb00-ddfe-11ea-957a-ff85b8e6935c.png)

Thank you

**Comment by SeaDude** [comment]
Anyone?

**Comment by v-anvari** [comment]
Hi @ericthomas1 , . Please find the doc here - https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace

PR: https://github.com/MicrosoftDocs/azure-docs/issues/55824. 

You would still require a storage account and connect your storage account with the Functions. As mentioned here - https://github.com/Azure/azure-webjobs-sdk/issues/2387#issuecomment-692944356
https://docs.microsoft.com/en-us/azure/storage/blobs/create-data-lake-storage-account

https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-multi-protocol-access
