### ISSUE TITLE
Cannot apply attribute class 'Queue<T>' because it is generic, with sdk.functions 3.0.7

### ISSUE THREAD

**Issue by extellior** [Azure/Azure-Functions#1690]
Yesterday, in creating a new durable functions project to add incoming data to a queue, VS Code was giving me this message:

`Cannot apply attribute class 'Queue<T>' because it is generic`

However, when I pasted the **exact** same queue binding into another project from a few days earlier, I did not get this error.  To understand why, I examined every single file between the old solution and the new one, and found that the one and only difference is in this reference added by VS Code:

`<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />`

When I change this reference to the older one, the error goes away:

`<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />`

Steps to reproduce:

1. In .csproj file, ensure reference is set as above.
2. Use a simple queue binding as follows:

`        [FunctionName("MySpecialOrchestrationTest")]
        public static async Task<List<string>> RunOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            [Queue ("MySpecialQueue")] IAsyncCollector<MySpecialItem> MySpecialQueue)
        {
            var outputs = new List<string>();
            MySpecialItem data = context.GetInput<MySpecialItem>();    
            string res = await context.CallActivityAsync<string>("AddMySpecialDataAsync2", data);
            return outputs;
        }
`
3. Changing the reference, closing the project and then re-opening it causes the problem to either vanish or re-appear depending on the version you reference.

Code formatting was being problematic and chopping things up.  Full code here: [https://pastebin.com/0ezMebTZ](https://pastebin.com/0ezMebTZ)

Class and function names were changed to protect the innocent :)

**Comment by v-anvari** [comment]
Hi @extellior , Thank you for your feedback! Apologies for the delayed response, can you kindly confirm if you are still seeing this issue with the latest packages. I tried to reproduce this issue with a simple queue trigger, but it worked as expected.

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this request in case of any further queries related to this issue
