### ISSUE TITLE
[UX] - Safari Display Glitch

### ISSUE THREAD

**Issue by jbeeko** [Azure/Azure-Functions#1691]
# Safari Display Glitch

## Description

When viewing the list of functions on Safari the summary metrics scroll. See video. This happens both on the view of all functions and when viewing an individual function. 

Safari Version 13.1.2 (15609.3.5.1.3)
MacOS Version 10.15.6 (19G2021)

But this has been happening since the new portal came out. 

[scrolling-functions.mov.zip](https://github.com/Azure/Azure-Functions/files/5091478/scrolling-functions.mov.zip)

**Comment by btardif** [comment]
@ehamai this one is interesting. I suspect it's a bug in the metrics controls?

**Comment by jbeeko** [comment]
> @ehamai this one is interesting. I suspect it's a bug in the metrics controls?

Does not happen in some other metrics controls, for example AppInsights is fine.

**Comment by v-anvari** [comment]
Hi @jbeeko , This is a quick follow up, does this issue still exist. Is this good to be closed?

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
