### ISSUE TITLE
[UX] - Test Input field display glitch on Safari

### ISSUE THREAD

**Issue by jbeeko** [Azure/Azure-Functions#1692]
# Test Input field display glitch on Safari

## Description

When triggering functions using the test feature of the portal right-clicking on the content of the input field will result in it being slightly scrolled off screen. 

Safari Version 13.1.2 (15609.3.5.1.3)
MacOS Version 10.15.6 (19G2021)

<img width="528" alt="image" src="https://user-images.githubusercontent.com/4968704/90690700-05f89300-e227-11ea-932f-7bb1b7f64d61.png">

**Comment by btardif** [comment]
@takyyon  can you take a look?

**Comment by v-anvari** [comment]
Hi @jbeeko , This is a quick follow up, does this issue still exist. Is this good to be closed?
