### ISSUE TITLE
Publishing Azure Function adds UserSecret to Project File without adding reference to Microsoft.Extensions.Configuration.UserSecrets

### ISSUE THREAD

**Issue by aderderian** [Azure/Azure-Functions#1697]
Azure Function fails to hit the new Configure method in FunctionsStartup when a UserSecretId is inside he project file. The startup must be silently erroring out until 👍     <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.7" />

Is added to the project file. This solves the issue. An error should be thrown or reference injected upon publishing when adding the user secret.

**Comment by v-bbalaiagar** [comment]
Hi @aderderian, Apologies for the delayed response, Were you able to find a solution. If you still having this issue persisting, then let us know the repro steps for us to understand the error.

**Comment by v-bbalaiagar** [comment]
Hi @aderderian, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue
