### ISSUE TITLE
Local debugging in visual studio code loads older grpcio module in python

### ISSUE THREAD

**Issue by tvse-central-da** [Azure/Azure-Functions#1698]
## Issue
I have a dependency on latest version of grpcio library in python i.e 1.31.0. This is what I have mentioned in the requirements file. When I try to debug the python program, the debugger does not load this file but an older version of grpcio library i.e. 1.24.0 which breaks my code

##versions
Python = 3.8
python extension : 2020.8.03604

I am using visual studio code on my mac machine
Here is the version for VSC
Version: 1.48.0 
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Deploying and running it via portal works

The trigger is http.

**Comment by v-bbalaiagar** [comment]
Hi @tvse-central-da, Apologies for the delayed response. We would like to know if you were able to find a solution to this issue. Kindly let us know so that we can look into this further.

**Comment by v-bbalaiagar** [comment]
Hi @tvse-central-da, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
