### ISSUE TITLE
Azure Function : HTTP Trigger binding expression pattern in blob binding

### ISSUE THREAD

**Issue by disssid** [Azure/Azure-Functions#1699]
Is there a way to achieve this
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#json-payloads

with a regular HTTP trigger in Python.

So, to set the context, I'd like to pass a parameter from my HTTP request and use it as a blob name in the input blob binding. (Can't use a Blob trigger have to use a Http trigger)

Http request
`http://localhost:7071/api/FileTrigger?name=sample_invoice`

function.json
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "name": "inputBlob",
      "type": "blob",
      "direction": "in",
      "path": "invoice-file/{name}.csv",
      "connection": "AzureWebJobsStorage"
    }
  ]
}
```
The path in the input blob binding probably should be this `"path":"invoice-file/sample_invoice.csv"`

Is there any deserialization approach available for Python, like in the above link for C#, F# and JavaScript ?

Edit:

Found this issue, something that's related to what I'm looking for
https://github.com/Azure/azure-functions-python-worker/issues/652#issuecomment-625461101

**Comment by v-anvari** [comment]
Hi @disssid , The worker doesn't allow this behavior as of today. Similar kind of structure is being tracked here.

https://github.com/Azure/azure-functions-python-worker/issues/838

Closing this issue as such feature requests are tracked in the python worker. For any pyton code related queries, please open a issue in the python worker repo for better reach
