### ISSUE TITLE
SaaS File/Table bindings docs

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#17]

**Comment by SyntaxC4** [comment]
Hamid is the source of truth for these. They mostly work like Blob and Table do, but there are a few things, like how the Connectors themselves work that are very different.

Also these are going to be renamed: **External File Trigger**

**Comment by lindydonna** [comment]
Changing to P1 since this will be in preview

**Comment by SyntaxC4** [comment]
@lindydonna @christopheranderson  - Is this ready to be unblocked now and added to the ready column?

**Comment by lindydonna** [comment]
External file is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-external-file

External table shouldn't be documented, as it's experimental and may be pulled entirely.
