### ISSUE TITLE
"download app content" generates an invalid zip file in the new experience, but works correctly for the "classic" experience

### ISSUE THREAD

**Issue by siweletan** [Azure/Azure-Functions#1701]
I click the "Download app content" button, it generates a .zip file which is downloaded, but is invalid. It cannot be opened by the default Windows functionality nor by using 7-zip. I tried refreshing. I also tried each combination of options (visual studio, include settings). The behavior was consistently broken, and the download file size identical.
However, if I switch to the the classic experience, clicking "Download app content" works just fine and the zip file opens correctly. 
The file that is broken is 106MB. The file that works correctly is 58MB.
My function is very simple and just references a .net package. FWIW the package is hosted in a separate subscription and I only have access to the shared storage where the package is hosted.

**Comment by HAL377** [comment]
Same problem form, works in classic mode but doesn't in the latest interface and I receive the same "zip file xxxxx is invalid" error message when trying to unpack.

**Comment by Jtango18** [comment]
This looks to have been resolved recently, and I can't replicate. Are either of you still experiencing this issue?

**Comment by ToninoBruno** [comment]
It works now for me.. thx for having this fixed.

**Comment by siweletan** [comment]
I confirmed that it also works for me now. This issue can be closed.

**Comment by v-bbalaiagar** [comment]
Hi @siweletan, Closing this issue as resolved, please feel free to reach back to us in case of any further queries related to this issue
