### ISSUE TITLE
New Azure Function experience does not show exceptions on Function start up. 

### ISSUE THREAD

**Issue by mikeoconnor1980** [Azure/Azure-Functions#1705]
We are using AutoMapper in our functions, and we have a mapping exception - fine.
In the old experience we would see something like this:

![image](https://user-images.githubusercontent.com/24374214/92075420-5ab41600-edb0-11ea-84a1-90b0b13dbe5c.png)

But in the new experience - this exception is no where to be found - and the assumption is its all working fine:

![image](https://user-images.githubusercontent.com/24374214/92075575-aa92dd00-edb0-11ea-8c85-36e84bedb13c.png)

Please can you ensure that if there is an exception on start up (stopping the function running) that this exception is visible somewhere.

**Comment by v-bbalaiagar** [comment]
Hi @mikeoconnor1980, To diagnose failures in your monitored applications, Please go through the document in the below link 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions#diagnosing-failures-using-the-azure-portal

**Comment by v-bbalaiagar** [comment]
Hi @mikeoconnor1980, Closing this issue as the required information is provided, Please feel free to reach back to us in case of any further queries related to this issue.
