### ISSUE TITLE
Cannot access the deployment center

### ISSUE THREAD

**Issue by jmorenobl** [Azure/Azure-Functions#1706]
I can only access the deployment center in the classic view

**Comment by v-bbalaiagar** [comment]
Hi @jmorenobl,  Apologies for the delayed response, We would like to know if you are still facing the same issue

**Comment by jmorenobl** [comment]
I'm not using it anymore, sorry.

**Comment by v-bbalaiagar** [comment]
Hi @jmorenobl, Closing this issue, please feel free to reach back to us in case of any further queries related to this issue
