### ISSUE TITLE
[Premium] Private Endpoint Functions App returns 403 from within VNET

### ISSUE THREAD

**Issue by erwelch** [Azure/Azure-Functions#1707]
I have 2 Premium Azure Functions that have private endpoints. I have a VM in the VNET that I login through Bastion to verify the connections within the VNET. The function site returns 403, but the scm site does not. I would expect them to both work. Here are screenshots of the Private Endpoint configuration and the private DNS zones:

Private Endpoint: 
![image](https://user-images.githubusercontent.com/38870842/92180817-c9b75c00-edfc-11ea-8726-801dac67e535.png)

Private DNS Zone:
![image](https://user-images.githubusercontent.com/38870842/92180852-dcca2c00-edfc-11ea-8a3b-90a3821e7b87.png)

I see the records for both the site and the scm site. Why is only the site returning a 403?

**Comment by v-anvari** [comment]
Hi @erwelch , Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue, if yes , can you provide us with the repro steps

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or reopen this issue in case of any further queries related to this issue
