### ISSUE TITLE
[Premium] Issue with "Azure App Service Deploy Task" for "Function App on Linux"

### ISSUE THREAD

**Issue by tehmufifnman** [Azure/Azure-Functions#1708]
I don't believe any code is necessary to reproduce this issue since the problem is obvious before you ever get to the code deploy step.

Reproduction Steps:

1. Create new Azure Pipeline using Classic Editor/Empty Job.
> Note: My organization does not allow YAML pipelines due to DevOps security policies in Production
2. Add a new Azure App Service Deploy Task" to the pipeline.
3. Select "Function App on Linux" under App Service Type.
4. Select a valid Subscription.
5. Populate a valid App Service Name.
6. Select ".NET" under Runtime Stack.
7. To see the issue, click "View YAML" at the top.  
Note the setting
`RuntimeStackFunction: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'`

There is no way to change this when using this task as is, it is the only .NET option provided.  If you're Azure Function is actually V3, this obviously will cause all kinds of issues.

**Comment by Jtango18** [comment]
The Azure Pipelines team has an issue related to this [here:](https://github.com/microsoft/azure-pipelines-tasks/issues/12811)

**Comment by v-anvari** [comment]
Thank you for your feedback. Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
