### ISSUE TITLE
When downloading Azure App content through the new portal - Zip corrupted

### ISSUE THREAD

**Issue by apdekock** [Azure/Azure-Functions#1709]
When downloading Azure App content through the new portal - Zip corrupted

Switching to classic view resolves the issue.

**Comment by v-bbalaiagar** [comment]
Hi @apdekock, Apologies for the delayed response, We are able to download the app content through the new portal. Let us know if you are still facing the same issue.

**Comment by v-bbalaiagar** [comment]
Hi @apdekock, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue
