### ISSUE TITLE
FTP Connection from Azure Functions, different IP between request

### ISSUE THREAD

**Issue by dieterdp** [Azure/Azure-Functions#1713]
Hello

I am using the FluentFTP library to connect from Azure Functions inside an Timer trigger to an FTP server on premise. This works correct in 95% of the cases. But sometimes the Azure Functions fails to connect and fails to download or upload the file. Azure Functions sometimes changes the IP-address during this 2 requests: The connection is established with IP-address A and for the data transfer Azure uses IP-address B and this isn't allowed on many firewalls. the only thing we can do is retries and even then it does not always works. 

Is this a know issue or is there a workaround?

regards
Dieter

**Comment by Jtango18** [comment]
Have you got some repo code that shows what you're doing to establish/work with the connections?

**Comment by v-bbalaiagar** [comment]
Hi @dieterdp, Apologies for the delayed response, Were you able to find a solution. If you still having this issue persisting, then let us know the repro steps for us to understand the error.

**Comment by v-bbalaiagar** [comment]
Hi @dieterdp, Closing this issue as there is no response, Please feel free to reach back to us in case of any further queries related to this issue.

**Comment by StefH** [comment]
@dieterdp Did you find a solution?
