### ISSUE TITLE
Exception: Operation is not valid due to the current state of the object on running Azure Function

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/Azure-Functions#1714]
I'm using an Azure function - Service Bus queue trigger C#. I'm able to run this function locally fine. I was able to deploy this function app in Azure:

[![enter image description here][1]][1]

On running the function:

[![enter image description here][2]][2]

I see the following error:

[![enter image description here][3]][3]

[![enter image description here][4]][4]

How do I resolve this error?

  [1]: https://i.stack.imgur.com/fSRLU.png
  [2]: https://i.stack.imgur.com/9UU2p.png
  [3]: https://i.stack.imgur.com/uRkNN.png
  [4]: https://i.stack.imgur.com/7sc7R.png

**Comment by v-anvari** [comment]
Hi @lipalath-ms , I have tried to reproduce your scenario, but I am able to run the Function App locally as well as in the portal after deployment.

My repro steps: 
1. Create an azure function app with the service bus queue template in Visual studio
2. My local host settings :
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsServiceBus": "end......."
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}
3. Deploy the app
4. Add the connection string in the function app config
5. Run the function in the portal

Executed 'function**' (Succeeded)

Can we get the code snippet that you are using or the binding parameters. Please provide us more details of your project to look into it.

**Comment by v-anvari** [comment]
closing the issue, as there is no error
