### ISSUE TITLE
[UX] - classic experience is getting deprecated

### ISSUE THREAD

**Issue by sergsalo** [Azure/Azure-Functions#1715]
# Classic experiences is getting deprecated without providing analogous functionality

Classic experience has a benefit of quickly switching between individual functions and see their individual logs. New experience is taking 3 more clicks every time to switch to a different function code and logs. Would you guys consider making new experience better and not worse?

**Comment by sergsalo** [comment]
the other thing is that in classic experience I was able to see "index.js" file, but new experience is not able to show that file because its path is not in default function folder: "scriptFile": "../dist/engine/index.js". Typescript "index.ts" is under default function folder, but when it is compiled - it is compiled into /dist/engine folder.

**Comment by patrickjlee** [comment]
I agree! Another problem with the new experience which is worse is that I can't see how to view change Function App settings which are in host.json, like maxDequeueCount, functionTimeout. 
Please, please add this to the new experience BEFORE you remove the classic experience!!

**Comment by gary5199** [comment]
https://docs.microsoft.com/en-us/learn  still uses the old interface to provide instruction, and the old instructions make no sense when looking at the new interface.

**Comment by btardif** [comment]
> https://docs.microsoft.com/en-us/learn still uses the old interface to provide instruction, and the old instructions make no sense when looking at the new interface.

@anthonychu @jeffhollan  can you guys please help follow up on the content update?

**Comment by btardif** [comment]
In general the new functions UX experience has been well received by a majority of customers.
