### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception.  ---> System.DllNotFoundException: Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by ChaunceyJ** [Azure/Azure-Functions#1717]
## problem
When I was using Azure-function with .net core 3.1, I used the System.Data.SqlClient to connect Azure SQL server. And it failed. The detail is the following.
> 2020-09-14T07:44:19.042 [Information] System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNILoadHandle..ctor()
   at System.Data.SqlClient.SNILoadHandle..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.TdsParser..cctor()
   --- End of inner exception stack trace ---
I used run.csx to build my function and edited and test it on the web page. Also the runtime version is 3. 

## solution
I changed the runtime version to 2. Then, the function can run successfully.

**Comment by Jtango18** [comment]
If you switch from `System.Data.SqlClient` to `Microsoft.Data.SqlClient` it should solve your problem and work as expected with .NET Core 3.1

**Comment by ChaunceyJ** [comment]
> If you switch from `System.Data.SqlClient` to `Microsoft.Data.SqlClient` it should solve your problem and work as expected with .NET Core 3.1

Thank you so much. But, I have tried to reference the 'Microsoft.Data.SqlClient' using NuGet. I added a *function.proj* file into my folder like this. 
```
FunctionsProject
 | - MyFirstFunction
 | | - run.csx
 | | - function.json
 | | - function.proj
```
And the *function.proj* file is the following.
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.1" />
    </ItemGroup>
</Project>
```
And I also added ```"D:\home\site\wwwroot\Microsoft.Data.SqlClient.2.0.1\runtimes\win\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll"``` or ```#r "D:\home\site\wwwroot\bin\Microsoft.Data.SqlClient.dll"``` and ```using Microsoft.Data.SqlClient;``` in *run.csx*.  But new error occurs 'System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.'.

Could you please tell me what I should do? Thank you so much.

**Comment by Jtango18** [comment]
I created a small repo [here](https://github.com/Jtango18/AZ-1717-Repro) including a ReadMe which works.

**Comment by ChaunceyJ** [comment]
Thank you so much.
