### ISSUE TITLE
What is the best way to configure deployed Azure Functions?

### ISSUE THREAD

**Issue by skorunka** [Azure/Azure-Functions#172]
Should we use .json files and:

	var builder = new ConfigurationBuilder()
		.SetBasePath(Directory.GetCurrentDirectory())
		.AddJsonFile("appsettings.json", false)
		.AddEnvironmentVariables();
	var config = builder.Build();
	var test = config.GetValue<string>("test");

Or use "App Service\Application settings" of underlaying WebApp host?
![image](https://cloud.githubusercontent.com/assets/218913/22507174/1ffbda1c-e87c-11e6-8618-ecfb35e06437.png)

Thank you.

**Comment by lindydonna** [comment]
The recommended approach is to use an ARM template with values for the appsettings. Here's a sample for a consumption plan function app: https://github.com/Azure/azure-quickstart-templates/tree/master/101-function-app-create-dynamic

**Comment by nhwilly** [comment]
Wow, that's complex.  Seems like a lot of fragile things a simple app developer could mess up (esp. me).

I've created objects that are instantiated using `ConfigurationBuilder` in my Asp.Net MVC project and it's working great.  The are shaped like the example below.  This same structure is to be shared by all the functions (see below).

There's no simple way of creating a static poco and populating it from a simple json file?

    {
      "CosmosConfig": {
        "Database": {
          "Id": "sampledb",
          "Endpoint": "https://****.documents.azure.com:443/",
          "Collections": [
            {
            "CollectionType": "default",
            "CollectionId": "tests",
            "DefaultTimeToLive": "-1",
            "Partitioned": "True",
            } 
          ] 
        },
