### ISSUE TITLE
While creating Azure functions, option to choose "Experimental Language Support' in not available in modern 

### ISSUE THREAD

**Issue by spreetvirdi** [Azure/Azure-Functions#1720]
In classic view,
Go to function app and create a new function. You have radio button "Experimental Language Support" which lets you write function in Basic, Power shell,, Typescript as well
However count
![Classic View](https://user-images.githubusercontent.com/64831193/93184919-70cfb800-f75a-11ea-9cf2-6b1665133224.png)
![Modern View](https://user-images.githubusercontent.com/64831193/93184924-71684e80-f75a-11ea-8627-fda9d2271d88.png)

 find any provision to create azure function using powershell in Modern view. Every time i need it i have to switch to classic view

**Comment by The-ARMR** [comment]
Yes this is one of the main issue which always comes around. 
Does the modern view support creation of Function Apps with powershell scripts ? If it does which i really hope it does, then how to do it ?

**Comment by VishnuMohan259** [comment]
Yes for me i have the same issue . I'm able to add power shell experimental languages from function apps but from modern view it was not there for https triggers. Is it because it is experimental language? If it is present in modern view then how to enable it?

**Comment by AnoopNagappan** [comment]
Modern indeed a wise choice if you could bring back old features which we widely used .. Very true @The-ARMR me too having the same question arises in my mind 

#powershell

**Comment by dmeadkagool** [comment]
This will be an issue for me once the Classic Experience disappears - please allow Experimental Language Support in the modern experience

**Comment by v-bbalaiagar** [comment]
Hi @spreetvirdi, Apologies for the delayed response. While creating you can choose the runtime stack and choose the preferred language. 
[Manage remote on-premises resources by using PowerShell functions | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-hybrid-powershell#create-a-powershell-function-app-in-the-portal)
Are you trying to create using V1, if yes then all the languages are not supported.
[Supported languages in Azure Functions | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages#languages-by-runtime-version)
Related information:
[Create a PowerShell function using Visual Studio Code - Azure Functions | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-powershell)

**Comment by v-bbalaiagar** [comment]
Hi @spreetvirdi, Closing this issue as the required information is provided, Please feel free to reach back to us in case of any further queries related to this issue
