### ISSUE TITLE
`HttpTrigger` function ignores `JsonConvert.DefaultSettings` for response via `OkObjectResult`

### ISSUE THREAD

**Issue by atsapura** [Azure/Azure-Functions#1721]
Azure functions version: v3
Runtime version: .net core 3.1

Startup.fs file:

```fsharp
type Startup () =
    inherit FunctionsStartup()

    let settings =
        let jsonSettings = JsonSerializerSettings()
        jsonSettings.ContractResolver <- CamelCasePropertyNamesContractResolver()
        jsonSettings.Converters.Add(CompactUnionJsonConverter())
        jsonSettings
    do JsonConvert.DefaultSettings <- Func<_>(fun () -> settings)

    override __.Configure(builder : IFunctionsHostBuilder) =
        // some services registration, unrelated to serialization
        ()

module DummyModuleOnWhichToAttachAssemblyAttribute =
    [<assembly: FunctionsStartup(typeof<Startup>)>]
    do ()
```

In function itself I just return `OkObjectResult(myObject) :> IActionResult`

## Expected result:

Object is serialized with settings, specified in `Startup.fs`, including `CompactUnionJsonConverter`.

## Actual result:

`CompactUnionJsonConverter` is ignored. Camel case is still there, but I doubt that it comes from my settings.

**Comment by v-bbalaiagar** [comment]
Hi @atsapura, We apologize for the delayed response, were you able to find a solution to this problem. Do let us know if you want us to look at this issue further.

**Comment by v-bbalaiagar** [comment]
Hi @atsapura, Closing this issue as there is no further activity, Please feel free to reach back to us in case of any further queries related to this issue.
