### ISSUE TITLE
Azure function throws exception DryIoc.ContainerException: Scope is disposed and scoped instances are disposed and no longer available

### ISSUE THREAD

**Issue by iamsuresha** [Azure/Azure-Functions#1722]
Once the azure function started running I am getting the scope Disposed issue after sometime.

DryIoc.ContainerException: Scope disposed{no name, Parent=disposed{no name, Parent={no name, Parent={no name, Parent={no name, Parent={no name}}}}}} is disposed and scoped instances are disposed and no longer available. at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.

@markheath @cgillum

**Comment by iamsuresha** [comment]
@brettsam I am still facing this issue and I couldn't able to run my Timer Triggered Azure Function. Please let me know what should i do to fix this issue.

**Comment by v-bbalaiagar** [comment]
Hi @iamsuresha, Could you please give us the function app details privately by following the below link - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

Also, Can you please share the code where you are seeing that exception take place.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
