### ISSUE TITLE
Azure Function V1 TimeTrigger with async overlapped

### ISSUE THREAD

**Issue by johnn82** [Azure/Azure-Functions#1725]
Hi,

I'have created a TimeTrigger AZF v1 hosted with:
- A specific AppPlan (no Consumption Plan)
- AlwaysOn is enabled.
- The function uses the async pattern. 
- The scheduled time is every minute ("0 */1 * * * *"). 

The function takes **more** than 1 minute to complete but from the log I can see that the function is triggered again after 1~/2~ miunutes. 

As far as I understand, the azure enviroment **guarantees** only **ONE** execution at a time for a TimeTrigger function. If a function is scheduled every minute, but it takes more time to be executed, the next execution should be tirggered after the previous one is completed.

https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#singleton-locks

> Behind the scenes, TimerTrigger uses the Singleton feature of the WebJobs SDK to ensure that only a single instance of your triggered function is running at any given time. When the JobHost starts up, for each of your TimerTrigger functions a blob lease (the Singleton Lock) is taken. This distributed lock ensures that only a single instance of your scheduled function is running at any time. If the blob for that function is not currently leased, the function will acquire the lease and start running on schedule immediately. If the blob lease cannot be acquired, it generally means that another instance of that function is running, so the function is not started in the current host. When this happens, the host will continue to periodically check to see if it can acquire the lease. This is done as a sort of "recovery" mode to ensure that when running steady state, if an instance goes down, another instance notice and pick up where the other left off.

I tried also with a dummy function, the problem is still there.

```
public static class ExecuteQueuedJobsFunction
{
	[FunctionName("ExecuteQueuedJobs")]
	public static async Task Run(
		[TimerTrigger("0 */1 * * * *", RunOnStartup = false)]TimerInfo myTimer,
		TraceWriter log,
		ExecutionContext context)
	{
		log.Info("This the timer triggered function just started!");
		log.Info("We wait for 15 minutes...");
		await Task.Delay(60 * 15 * 1000);
		log.Info("Wow it was fun to wait for 2 minutes!");
		log.Info("This function just finished!");
		log.Info("");
		log.Info("");
	}
}
```

> 2020-09-15T13:45:17Z   [Information]   This the timer triggered function just started!
> 2020-09-15T13:51:28Z   [Information]   Function started (Id=4859623d-624b-4452-9694-61a54a4241fc)
> 2020-09-15T13:54:58Z   [Information]   Function started (Id=1fc88b8c-dc39-42e5-b0cf-2a79d5bf31e4)
> 2020-09-15T13:55:28Z   [Information]   Function started (Id=5fa9f3b6-7ada-44f1-9eb2-dc5658999477)
> 2020-09-15T13:59:28Z   [Information]   Function started (Id=07091308-eed6-4904-8a7e-1c27de0835cc)
> 2020-09-15T13:59:28Z   [Information]   This the timer triggered function just started!
> 2020-09-15T13:59:28Z   [Information]   We wait for 15 minutes...
> 2020-09-15T14:01:09Z   [Information]   Function started (Id=72189971-5fc6-4e45-a466-03c3380d94b6)
> 2020-09-15T14:01:09Z   [Information]   This the timer triggered function just started!
> 2020-09-15T14:01:09Z   [Information]   We wait for 15 minutes...
> 2020-09-15T14:02:48Z   [Information]   Function started (Id=c8e155de-c92d-4cd3-8379-a23a9e22a97e)
> 2020-09-15T14:02:48Z   [Information]   This the timer triggered function just started!
> 2020-09-15T14:02:48Z   [Information]   We wait for 15 minutes...
> 2020-09-15T14:04:36Z   [Information]   Function started (Id=6dc92bc2-10a8-4576-84c7-56ff6f795b43)
> 2020-09-15T14:04:36Z   [Information]   This the timer triggered function just started!
> 2020-09-15T14:04:36Z   [Information]   We wait for 15 minutes...
> 2020-09-15T14:06:08Z   [Information]   Function started (Id=79e7d69f-14c5-420c-ba76-7e3cbba02788)
> 2020-09-15T14:06:10Z   [Information]   This the timer triggered function just started!
> 2020-09-15T14:06:10Z   [Information]   We wait for 15 minutes...
> 2020-09-15T14:07:48Z   [Information]   Function started (Id=83cf91ff-bc1c-4733-8898-31adcae98b39)
> 2020-09-15T14:07:48Z   [Information]   This the timer triggered function just started!
> 2020-09-15T14:07:48Z   [Information]   We wait for 15 minutes...
> 2020-09-15T14:09:28Z   [Information]   Function started (Id=c3c9cf9e-0888-444e-9ee8-0faf15be3265)
> 2020-09-15T14:09:28Z   [Information]   This the timer triggered function just started!
> 2020-09-15T14:09:28Z   [Information]   We wait for 15 minutes...
> 2020-09-15T14:12:48Z   [Information]   Function started (Id=93e18312-5b64-4bdf-8a3d-3df8c51835ab)
> 2020-09-15T14:12:48Z   [Information]   This the timer triggered function just started!
> 2020-09-15T14:12:48Z   [Information]   We wait for 15 minutes...

**Comment by anthonychu** [comment]
I think the wiki (and our [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#scale-out)) are not quite accurate.

The lock ensures only one instance of a function _app_ is invoking a single timer triggered function at any given time. For example, if you have a timer that runs at midnight every night, this guarantees that the function is only invoked once at midnight by a single instance, even if the function app has scaled out to multiple instances.

What the lock does not do, however, is prevent different invocations of the same timer function from overlapping. A function will fire at the scheduled time, even if the previous invocation has not completed. This is by design. I don't believe you can change this behavior in the timer trigger. If you want to run jobs periodically but do not want overlapping invocations, you can use a Durable Functions [eternal orchestration](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-eternal-orchestrations?tabs=csharp#periodic-work-example) (there's also an explanation in this document on how this differs from a timer trigger).

/cc @mathewc @craigshoemaker @cachai2 on the wiki and bindings docs

**Comment by johnn82** [comment]
Hi @anthonychu, thank you for the clarification.
I have two more questions:
- You said that timer function is triggered on schedule, whatever the previous one is completed. So the same function can run in paraller right? Can you confirm that the lastest triggered doesn't cancel the previous one?
- Why I'm not seeing the complete log of my function? As you can see from the output I can only see the first two call of the log.info() methiod. No trace of the tow subsequent calls after the await Task.Delay()

**Comment by anthonychu** [comment]
@johnn82 I looked into this and it turns out the wiki and Timer trigger docs are correct, and that the note about overlaps in the Durable Functions eternal orchestrations might be incorrect. A timer function won't fire again if the previous one is still running. I've tested it out with both async and not async. It's unclear what is happening here. Can you confirm you get the same behavior in a different function app?

**Comment by johnn82** [comment]
Yes @anthonychu I have deployed the same function into two different app and I get the same behavior.

**Comment by johnn82** [comment]
Hi @anthonychu do you have any news about this? We are facing very strange behavior in our apps. Some time the function hangs forever, no exception is thrown, but no further executions are done. It seems that when the function takes too much time to be executed, it kill the application. We are using an App Plan for our timer trigger function.

**Comment by anthonychu** [comment]
If possible, can you submit a support ticket? They're better equipped to drill into specific issues like this. Looks like there may be other issues involved that could make it difficult to troubleshoot here.

**Comment by johnn82** [comment]
Hi @anthonychu, you mean an azure ticket?

**Comment by smartpcr** [comment]
I am having similar problem, below is func code,
![image](https://user-images.githubusercontent.com/9336638/117356958-33df3f80-ae69-11eb-9390-c989842b6f75.png)

Here is what I get from app insights, i am observing 4 concurent, interleaved instance running at the same time!
``` kql
traces
| where operation_Name == "ProjectDeploymentManager"
| where timestamp between (todatetime('2021-05-05 15:55:00.2843848')..todatetime('2021-05-05 21:56:00.2843848'))
| order by timestamp asc 
| project timestamp, operation_Id, message
```


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xd/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xd/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



timestamp | operation_id | message
-- | -- | --
5/5/2021, 3:56:00.003 PM | 128d108f-1013-4cdb-9411-b60748ed2f4d | C# Timer   trigger started execution at: 5/5/2021 3:56:00 PM
5/5/2021,   3:56:00.003 PM | 128d108f-1013-4cdb-9411-b60748ed2f4d | Function   started (Id=128d108f-1013-4cdb-9411-b60748ed2f4d)
5/5/2021,   3:56:00.003 PM | f7508e9f-2cec-4256-841b-b23629e70d43 | Function   started (Id=f7508e9f-2cec-4256-841b-b23629e70d43)
5/5/2021,   3:56:00.003 PM | f7508e9f-2cec-4256-841b-b23629e70d43 | C# Timer   trigger started execution at: 5/5/2021 3:56:00 PM
5/5/2021,   3:56:00.003 PM | f7508e9f-2cec-4256-841b-b23629e70d43 | C# Timer   trigger function completed execution at: 5/5/2021 3:56:00 PM
5/5/2021,   3:56:00.007 PM | 927c5adb-5196-4c39-95b8-74664f90f104 | C# Timer   trigger started execution at: 5/5/2021 3:56:00 PM
5/5/2021,   3:56:00.007 PM | 927c5adb-5196-4c39-95b8-74664f90f104 | C# Timer   trigger function completed execution at: 5/5/2021 3:56:00 PM
5/5/2021,   3:56:00.007 PM | 927c5adb-5196-4c39-95b8-74664f90f104 | Function   started (Id=927c5adb-5196-4c39-95b8-74664f90f104)
5/5/2021,   3:56:00.013 PM | fb8c918c-397b-4e64-9805-f1123e6800cb | Function   started (Id=fb8c918c-397b-4e64-9805-f1123e6800cb)
5/5/2021,   3:56:00.013 PM | fb8c918c-397b-4e64-9805-f1123e6800cb | C# Timer   trigger function completed execution at: 5/5/2021 3:56:00 PM
5/5/2021,   3:56:00.013 PM | fb8c918c-397b-4e64-9805-f1123e6800cb | C# Timer   trigger started execution at: 5/5/2021 3:56:00 PM
5/5/2021,   3:56:00.019 PM | f7508e9f-2cec-4256-841b-b23629e70d43 | Function   completed (Success, Id=f7508e9f-2cec-4256-841b-b23629e70d43, Duration=20ms)
5/5/2021,   3:56:00.023 PM | 927c5adb-5196-4c39-95b8-74664f90f104 | Function   completed (Success, Id=927c5adb-5196-4c39-95b8-74664f90f104, Duration=19ms)
5/5/2021,   3:56:00.028 PM | fb8c918c-397b-4e64-9805-f1123e6800cb | Function   completed (Success, Id=fb8c918c-397b-4e64-9805-f1123e6800cb, Duration=20ms)
5/5/2021,   3:56:03.737 PM | 128d108f-1013-4cdb-9411-b60748ed2f4d | Function   completed (Success, Id=128d108f-1013-4cdb-9411-b60748ed2f4d, Duration=3744ms)
5/5/2021,   3:56:03.737 PM | 128d108f-1013-4cdb-9411-b60748ed2f4d | C# Timer   trigger function completed execution at: 5/5/2021 3:56:03 PM
5/5/2021,   3:57:00.009 PM | d4aa73d4-a28a-4211-bda5-a7dedef29495 | C# Timer   trigger started execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:57:00.009 PM | d4aa73d4-a28a-4211-bda5-a7dedef29495 | Function   started (Id=d4aa73d4-a28a-4211-bda5-a7dedef29495)
5/5/2021,   3:57:00.009 PM | baa83422-69b7-40e7-a378-e1068895768b | C# Timer   trigger started execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:57:00.009 PM | baa83422-69b7-40e7-a378-e1068895768b | Function   started (Id=baa83422-69b7-40e7-a378-e1068895768b)
5/5/2021,   3:57:00.009 PM | baa83422-69b7-40e7-a378-e1068895768b | C# Timer   trigger function completed execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:57:00.011 PM | b22fe726-47da-4408-9084-c7588dc3c08f | C# Timer   trigger started execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:57:00.011 PM | b22fe726-47da-4408-9084-c7588dc3c08f | C# Timer   trigger function completed execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:57:00.011 PM | b22fe726-47da-4408-9084-c7588dc3c08f | Function   started (Id=b22fe726-47da-4408-9084-c7588dc3c08f)
5/5/2021,   3:57:00.016 PM | 74775700-64ad-44ab-a03e-e4c3231e76b2 | Function   started (Id=74775700-64ad-44ab-a03e-e4c3231e76b2)
5/5/2021,   3:57:00.016 PM | 74775700-64ad-44ab-a03e-e4c3231e76b2 | C# Timer   trigger started execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:57:00.016 PM | 74775700-64ad-44ab-a03e-e4c3231e76b2 | C# Timer   trigger function completed execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:57:00.025 PM | baa83422-69b7-40e7-a378-e1068895768b | Function   completed (Success, Id=baa83422-69b7-40e7-a378-e1068895768b, Duration=25ms)
5/5/2021,   3:57:00.026 PM | b22fe726-47da-4408-9084-c7588dc3c08f | Function   completed (Success, Id=b22fe726-47da-4408-9084-c7588dc3c08f, Duration=16ms)
5/5/2021,   3:57:00.032 PM | 74775700-64ad-44ab-a03e-e4c3231e76b2 | Function   completed (Success, Id=74775700-64ad-44ab-a03e-e4c3231e76b2, Duration=20ms)
5/5/2021,   3:57:00.259 PM | d4aa73d4-a28a-4211-bda5-a7dedef29495 | Function   completed (Success, Id=d4aa73d4-a28a-4211-bda5-a7dedef29495, Duration=257ms)
5/5/2021,   3:57:00.259 PM | d4aa73d4-a28a-4211-bda5-a7dedef29495 | C# Timer   trigger function completed execution at: 5/5/2021 3:57:00 PM
5/5/2021,   3:58:00.002 PM | f2ab68d3-49a8-4f4b-a2d6-6a4beca942b3 | Function   started (Id=f2ab68d3-49a8-4f4b-a2d6-6a4beca942b3)
5/5/2021,   3:58:00.012 PM | bfba170a-b730-4653-9ef9-1a12cd2141b3 | Function   started (Id=bfba170a-b730-4653-9ef9-1a12cd2141b3)
5/5/2021,   3:58:00.012 PM | bfba170a-b730-4653-9ef9-1a12cd2141b3 | C# Timer   trigger started execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:58:00.012 PM | bfba170a-b730-4653-9ef9-1a12cd2141b3 | C# Timer   trigger function completed execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:58:00.015 PM | 2d371ab8-7786-404d-9416-44aebc88d632 | C# Timer   trigger function completed execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:58:00.015 PM | 2d371ab8-7786-404d-9416-44aebc88d632 | Function   started (Id=2d371ab8-7786-404d-9416-44aebc88d632)
5/5/2021,   3:58:00.015 PM | 2d371ab8-7786-404d-9416-44aebc88d632 | C# Timer   trigger started execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:58:00.016 PM | 7c4eeb44-8a0a-45b2-ab8b-4fb47ef29c7e | C# Timer   trigger started execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:58:00.016 PM | 7c4eeb44-8a0a-45b2-ab8b-4fb47ef29c7e | Function   started (Id=7c4eeb44-8a0a-45b2-ab8b-4fb47ef29c7e)
5/5/2021,   3:58:00.018 PM | f2ab68d3-49a8-4f4b-a2d6-6a4beca942b3 | C# Timer   trigger started execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:58:00.018 PM | f2ab68d3-49a8-4f4b-a2d6-6a4beca942b3 | Function   completed (Success, Id=f2ab68d3-49a8-4f4b-a2d6-6a4beca942b3, Duration=23ms)
5/5/2021,   3:58:00.018 PM | f2ab68d3-49a8-4f4b-a2d6-6a4beca942b3 | C# Timer   trigger function completed execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:58:00.027 PM | bfba170a-b730-4653-9ef9-1a12cd2141b3 | Function   completed (Success, Id=bfba170a-b730-4653-9ef9-1a12cd2141b3, Duration=17ms)
5/5/2021,   3:58:00.031 PM | 2d371ab8-7786-404d-9416-44aebc88d632 | Function   completed (Success, Id=2d371ab8-7786-404d-9416-44aebc88d632, Duration=19ms)
5/5/2021,   3:58:00.328 PM | 7c4eeb44-8a0a-45b2-ab8b-4fb47ef29c7e | Function   completed (Success, Id=7c4eeb44-8a0a-45b2-ab8b-4fb47ef29c7e, Duration=325ms)
5/5/2021,   3:58:00.328 PM | 7c4eeb44-8a0a-45b2-ab8b-4fb47ef29c7e | C# Timer   trigger function completed execution at: 5/5/2021 3:58:00 PM
5/5/2021,   3:59:00.004 PM | 4e1325e0-c28a-4677-889f-f69ccd8eb5c8 | C# Timer   trigger started execution at: 5/5/2021 3:59:00 PM
5/5/2021,   3:59:00.004 PM | 4e1325e0-c28a-4677-889f-f69ccd8eb5c8 | Function   started (Id=4e1325e0-c28a-4677-889f-f69ccd8eb5c8)



</body>

</html>

**Comment by johnn82** [comment]
Hi @smartpcr,
to my end the problems was related to database locks. 
In simple words, the logic I was running in the azure function was using EF to read/write some data from a table in a SQL Server database. It turned out that the Table was HUGE so execution of every call of my AZF was falling into a lock waiting for the previous call to finish.  The problem could be also related to the fact that using the "async" pattern will cause the timed function to be called over and over, because of the await on the SQL operation locked.
I hope that sharing this can help you out finding the problem.
