### ISSUE TITLE
Azure Functions Event Hub Trigger with Invalid Event Hub Name causing random trigger from Event Hubs under same Namespace

### ISSUE THREAD

**Issue by softnado** [Azure/Azure-Functions#1727]
I have one Event Hub Namespace contains several Event Hub. When using Azure Functions Event Hub Trigger with Invalid Event Hub Name (Since triggers the function call without issue, I assumed it uses the Entity Path from connection string). But deep investigation indicate that is not the case. The function with Invalid Even Hub Name got triggered randomly by the events from other Event Hub hosted in same Namespace. Not sure if this is related to the additional Consumer Group or not.

**Comment by v-anvari** [comment]
Hi @softnado , Apologies for the delayed response, I tried to reproduced with no problem, but not sure about the scenario you mentioned above. If you are facing this issue still, could you run through the repro steps and code that is busted. What are you trying to achieve

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
