### ISSUE TITLE
Function App Download Publish Profile is disabled

### ISSUE THREAD

**Issue by capita-davidwoakes** [Azure/Azure-Functions#1728]
I created a new function app and the download link was greyed out. I can reset the publish settings but not download

**Comment by v-bbalaiagar** [comment]
Hi @capita-davidwoakes,  Apologies for the delayed response, We would like to know if you are still seeing the button is grayed out in the portal.
 Also, Could you please go through [here](https://stackoverflow.com/questions/61178231/cant-download-app-content-of-azure-function-via-portal?rq=1) to download the app content of azure function. Let us know if you are able to solve with this information.

**Comment by v-bbalaiagar** [comment]
Hi @capita-davidwoakes, Closing the issue, In case of any further concerns regarding this issue, please feel free to re-open the issue.

**Comment by DataBach-maker** [comment]
This is still a problem for Python Function App.
