### ISSUE TITLE
Document exact requirements on Azure Storage

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#173]
This article (https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-portal) should explain the requirement on Storage.

> When creating a Function App, you must create or link a general-purpose Azure Storage account that supports Blob, Queue, and Table storage. Internally Azure Functions uses Azure Storage for operations such as managing triggers and logging function executions.  Some storage accounts do not support queues and tables, such as blob-only storage accounts (including premium storage) and general purpose storage accounts with ZRS replication. These accounts are filtered from the Storage Account blade when creating a new Function App.

> When using the Consumption hosting plan, Function App content (such as function code files and binding configuration) are stored on Azure Files shares on the main storage account. If you delete the main storage account, this content will be deleted and cannot be recovered. 

> To learn more about storage account types, see [Introducing the Azure Storage Services](https://docs.microsoft.com/en-us/azure/storage/storage-introduction#introducing-the-azure-storage-services).

Related to https://github.com/Azure/Azure-Functions/issues/39

**Comment by lindydonna** [comment]
@rachelappel Do you have cycles to make this change?  This content should be in its own section, because we will have a fwlink from the portal. Currently we don't filter storage accounts, but we're about to add the filter.

**Comment by lindydonna** [comment]
Once this article is written, I will update this fwlink: go.microsoft.com/fwlink/?linkid=843013.

**Comment by rachelappel** [comment]
@lindydonna  complete https://github.com/Microsoft/azure-docs-pr/pull/7585
