### ISSUE TITLE
Run and Save buttons are not available for non Http functions like they were available in classic mode

### ISSUE THREAD

**Issue by satrajitchoudhury** [Azure/Azure-Functions#1732]
Run and Save buttons are not available for non HTTP functions like they were available in classic mode.

See the screenshots below, 

![image](https://user-images.githubusercontent.com/55864885/93966451-6036c780-fd82-11ea-8e2d-7898e22452cd.png)

**Comment by satrajitchoudhury** [comment]
Is there an update on when these buttons would be included in the new Azure Interface ?

**Comment by v-bbalaiagar** [comment]
Hi @satrajitchoudhury, Apologies for the delayed response, In the new UI, You can find the test/run and save options in the code + Test of the function App.
Please find the below links which can guide you better.
Http trigger -[Create your first function in the Azure portal | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-app-portal#test-the-function)
Non-Http functions -for example - [Create a function triggered by Azure Cosmos DB | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-cosmos-db-triggered-function#create-azure-cosmos-db-trigger)

**Comment by v-bbalaiagar** [comment]
Hi @satrajitchoudhury, Closing this issue, please feel free to re-open the issue for any further queries regarding this issue.
