### ISSUE TITLE
Turning on Auto-heal slows down function response time substantially

### ISSUE THREAD

**Issue by nnanto** [Azure/Azure-Functions#1733]
Turning on auto-heal increased the response time of a simple query. This response time continued to increase with requests.

Auto-Heal description

![Auto heal description](https://i.stack.imgur.com/dyc5S.png)

Consider the following code run inside a HTTP triggered function
```c#
string validationToken = req.Query["validationToken"];

if (!string.IsNullOrEmpty(validationToken))
{
    await Task.CompletedTask;
    return new OkObjectResult(validationToken);
}

return new BadRequestResult();
```
---

**Auto-heal enabled:**

Profiling Data:

![Profiling Data](https://i.stack.imgur.com/paeLo.png)

Apache JMeter Load Test:

![JMeter AH enabled Load Test](https://i.stack.imgur.com/omjwl.png)

---

**Auto-heal disabled:**

Apache JMeter Load Test:
![JMeter AH disabled Load Test](https://i.stack.imgur.com/B5QA5.png)

**Comment by v-anvari** [comment]
Hi @nnanto , Apologies for the delayed response. Please let us know if you are still seeing this issue on you Function App, so that we will further look into the backend logs

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
