### ISSUE TITLE
[Premium]queue trigger function for azure storage api call not getting completed

### ISSUE THREAD

**Issue by riktimmondal** [Azure/Azure-Functions#1735]
**Describe the bug**
Using queue trigger based function to consume message from queue which are the subscription name where for each subscription around 400 to 500 storage api calls are made. since 100calls/5min are restricted we get 429 error response at 101th call. To mitigate this we use exponential retry logic with delay for few seconds with some logging operation to monitor our retry logic through live metric or search in Application Insight. We observed some subscription is able to complete all 400 to 500 api calls through retry logic(like trying for 3 times with subsequent dealy in between). For some subscription after hitting "too many request" condition for first time, even after waiting for 60 sec, it does not request again for any more retries. Since function app automatically creates many function instance for scaling, sometimes cpu usage of some instance goes to 0% which leads to killing of that instance. The message is pushed back to queue again and another function instance for that particular subscription is created which starts api calls again with 429 error.
 Our first suspect was that due to delay(thread sleep) the cpu might be going to ideal and that function instance is killed. But in our delay there are operation like looping, logging and also since we are on premium plan atleast one VM will be always on, so why the function app host is killing some function instance in between of operation.

**To Reproduce**
1)Messages from queue picked up from queue triggered function.
2) Storage api calls starts.First 100 request status 200. Then 101th request give 429 error response. Retry logic is applied. Wait for 60 seconds. 
a)For successful subscription, again request and it may get 429 error. Wait for  120 sec. Again call. If 200 then rest calls are called. If 429 wait wait for 180 sec, and then again api calls which are successful.
b)For unsuccessful subscription, some may get killed within that 60 sec wait due to cpu 0% or some may try for new retry and get killed. Message pushed back to queue. New instance created to start again. That this goes on and on untill it hit max count of message that can be pushed to queue and later move to poison queue.
3)Observe from live metric and transaction search of application insight for the logging details. Also queried logs of application insight and checked "operationId and Parent_operationId" in "dependency" to investigate killing of instances.

**Expected behavior**
For subscription with small storage account calls like below 100 can easily get completed. A very few no. of subscription with around 300 to 400 calls can complete all the call using retry logic. 

**Screenshots**

**Additional context**
Please note that no exception other than 429 dependency is thrown. Those few subscription keeps on trying for max no. of retries(i.e messages are pushed to queue) and does not get completed.

Delay Code used in retry logic(we tried our own as well as polly library)-
```
private void Delay(int Time_delay, string requestUri, int retryCount)
{
   for (int i = 0; i < Time_delay; i++)
   {
       _logger.LogWarning($"Sleep initiated for id: {requestUri.ToString()}, RetryCount: {retryCount} CurrentTimeDelay: {Time_delay}");
        Thread.Sleep(10000);
        _logger.LogWarning($"Sleep completed for id: {requestUri.ToString()}, RetryCount: {retryCount} CurrentTimeDelay: {Time_delay}");
    }
}
```

**Comment by v-anvari** [comment]
Hi @riktimmondal , Apologies for the delayed response, the issue was lost in the trace, could you tell us if you are still seeing this pattern. If yes, we can further investigate the backend logs to understand the error.
