### ISSUE TITLE
Azure functions - New Azure Portal UX left pane navigation to application insights does not work

### ISSUE THREAD

**Issue by harisubramaniam1** [Azure/Azure-Functions#1736]
# Unable to navigate to correct and linked app insights resource from the new UI

## Description

Go to the function app UI. Make sure the appsettings has the correct App insights instrumentation key.
Try clicking on App insights navigation to see that it asks for a new App insights resource to be created

## Expected
The portal should navigate to the already linked app insights

## Actual
It asks to create a new App insights resource to be created
![image](https://user-images.githubusercontent.com/63234380/94426396-6a433680-0185-11eb-81fd-b59cf9da5089.png)

**Comment by btardif** [comment]
+ @Michael Milirud<mailto:Michael.Milirud@microsoft.com> FYI, this looks like a bug in AI blade?

Byron Tardif

**Comment by btardif** [comment]
+@Julia<mailto:Julia.Goloshubina@microsoft.com> who owns APM enablement blade

Thanks - MM
[cid:image002.png@01D69593.9F0849E0]
Cell: 425-444-5060 / Skype: micweb

From: Byron Tardif <byvinyal@microsoft.com>
Sent: Monday, September 28, 2020 9:54 AM
To: Azure/Azure-Functions <reply@reply.github.com>; Azure/Azure-Functions <Azure-Functions@noreply.github.com>; Michael Milirud <Michael.Milirud@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [Azure/Azure-Functions] Azure functions - New Azure Portal UX left pane navigation to application insights does not work (#1736)

+ @Michael Milirud<mailto:Michael.Milirud@microsoft.com> FYI, this looks like a bug in AI blade?

Byron Tardif

**Comment by harisubramaniam1** [comment]
Is there an ETA on this?

The problem is amplified when anybody tries to navigate and they get presented with a choose app insights screen and they go on to make changes which then causes the function app to restart as app settings get updated. This is easy to go wrong on the new UX and cause a restart of the function app

**Comment by eamonoreilly** [comment]
@harisubramaniam1 I am not able to reproduce this? Are you still seeing this issue and any specific steps required to reproduce beyond those mentioned above?

**Comment by harisubramaniam1** [comment]
@eamonoreilly  I am still seeing this. I just created a sample azure function(1 one consumption and other on ASP)

![image](https://user-images.githubusercontent.com/63234380/97470132-158b0b00-193f-11eb-81e6-ae887220666c.png)

**Comment by shimedh** [comment]
We released the change to open the new AI blade on 10/29. Could you please make sure to hard refresh your Portal to make sure you are hitting the latest bits? From your screenshot looks like you are still hitting the old blade.

Also, if it still repros, can you run 'Ctrl+Alt+D' and send a screenshot?

Below is what I see on my end:
![image](https://user-images.githubusercontent.com/14221995/98053323-27f8bf00-1ded-11eb-86b3-30ff7c120517.png)

**Comment by harisubramaniam1** [comment]
Thank you. Works fine now
