### ISSUE TITLE
Error to deploy project python when to install pyodbc in linux

### ISSUE THREAD

**Issue by rodrigopessoa1979** [Azure/Azure-Functions#1738]
Trigger: HTTP
Local: East US 2
I have an Azure function witch python that connect a database azure SQL, I’m using the package pyodbc to connect database. 
On my computer it's working, but when I deploy via vscode, azure does all the python installations based on the requirements and he tries to do the download through website <https://github.com/pypa/pip/issues/8368./n> , which is out

And pyodbc is in requirements.txt

I’m using the above tools
Developer in VSCODE in Windows 10
Azure Functions: Linux
Type azure function is “HTTP”
Local is East 2

**Comment by anthonychu** [comment]
Please see the following issues for progress on a fix:

https://github.com/Azure/azure-functions-core-tools/issues/2243#issuecomment-701001347
https://github.com/Azure/azure-functions-python-worker/issues/746#issuecomment-701012618

**Comment by v-bbalaiagar** [comment]
Hi @rodrigopessoa1979, Kindly let us know if this issue is still persisting, or are we good to close the issue.

**Comment by v-bbalaiagar** [comment]
Hi @rodrigopessoa1979, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue. 
Also the updates will be provided in the above mentioned issues.
