### ISSUE TITLE
Consumption to EP Migration - via CLI 

### ISSUE THREAD

**Issue by fabiocav** [Azure/Azure-Functions#1739]
Mirror for CLI item https://github.com/Azure/azure-cli/issues/15252

**Comment by gzuber** [comment]
Work has been scoped, moving to next sprint for implementation

**Comment by gzuber** [comment]
While discussing the specifics of where this command should be implemented, we found the command `az functionapp update --plan` which allows a user to swap a functionapp between app service plans. This effectively accomplishes this upgrade scenario to a point where making another command might be redundant. The existing command doesn't create a new plan for the customer, so it's not exactly the same but very close.

For now, we've decided to stick with this old command. However, this command enables a user to switch from an ElasticPremium plan to a consumption plan which is potentially dangerous. Created https://github.com/Azure/azure-cli/issues/15694 to make changes to adequately inform a user of the risks involved.

**Comment by gzuber** [comment]
PR: https://github.com/Azure/azure-cli/pull/15695

**Comment by fabiocav** [comment]
PR open. Leaving this assigned to sprint 87, but they may not merge by the end of the sprint as they have a different release cadence

**Comment by fabiocav** [comment]
Code complete for AZ CLI is today. We're following up with them to have this work merged.

**Comment by gzuber** [comment]
PR Merged
