### ISSUE TITLE
Chunked encoding with HttpResponseMessage doesn't seem to work when deployed

### ISSUE THREAD

**Issue by josh-endries** [Azure/Azure-Functions#1740]
I am trying to return an HttpResponseMessage in a v3 Function, using chunked transfer encoding, writing to the stream when I receive an item from an IAsyncEnumerable. When I run locally, it works perfectly fine, outputs one chunk per item, even if it's cached in memory. When deployed in Azure, no matter what I do, it isn't acting as expected or reliably or consistently. Sometimes it doesn't chunk at all, buffering up the whole response. Sometimes it doesn't use chunked encoding at all (no header). Sometimes it returns one small chunk, then everything else in one large chunk. I've tried PushStreamContent and an HttpResponseMessage subclass (SerializeToStreamAsync) and they both have similar results.

Is there a way to disable this behavior or make it work the same as when running locally?

**Comment by josh-endries** [comment]
I found a workaround by delaying each yield by ~50ms.

**Comment by v-bbalaiagar** [comment]
Hi @josh-endries,  Apologies for the delayed response, Were you able to find a solution. Let us know if you are still seeing this issue.

**Comment by v-bbalaiagar** [comment]
Hi @josh-endries, Closing this issue as there is no response, please feel free to reach back to us in case of any further queries related to this issue.
