### ISSUE TITLE
C# Http trigger with payload parameter 'Query' throws Exception

### ISSUE THREAD

**Issue by PaulWildReb** [Azure/Azure-Functions#1741]
Simple http trigger function written in C# throws an exception if the payload has a parameter named 'Query'.

Example Code:

```
      public class ReqObject
        {
            public string Query { get; set; }
        }
        
        [FunctionName("Example")]
        public static async Task<IActionResult> RunAsync(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]
            ReqObject req, ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            
            return req.Query != null
                ? (ActionResult) new OkObjectResult($"Hello, {req.Query}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
            
        }
```
This results in the following exception message: 

> System.Private.CoreLib: Exception while executing function:. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. System.Private.CoreLib: Object must implement IConvertible.

Renaming the parameter stops the error and the function completes successfully.

**Comment by ryepup** [comment]
I'm seeing the same issue trying to support graphql in a azure static webapp

My csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataAccess.GraphQL\DataAccess.GraphQL.csproj" />
  </ItemGroup>
</Project>
```

My hosts.json has `"version": "2.0"`

**Comment by v-anvari** [comment]
Hi @PaulWildReb , Apologies for the delayed response, are you still seeing this error. Can you please give some more code and repro steps to investigate this issue a little bit more?

**Comment by andybooth** [comment]
I reproduced this issue with Functions Runtime 3.0.15417.0, with a case as per the sample code in the original report. When a POCO bound request object has a string property named Query the exception `Object must implement IConvertible` is returned. Renaming the root string property Query to MyPrefixQuery resolves the issue.

**Comment by v-anvari** [comment]
Hi @PaulWildReb , @andybooth , This issue is relating to an issue which is already being tracked - https://github.com/Azure/azure-functions-host/issues/5378. Here the name "Query "  is working like a reserved word, and the team is investigating on the issue to identify if it should be made as by-design. 

Thank you for your patience, closing this issue as its tracked in the above mentioned issue.
