### ISSUE TITLE
Azure Functions App cannot access storage (but is provided app config with access key)

### ISSUE THREAD

**Issue by KarFan-FS** [Azure/Azure-Functions#1742]
I have recently (from 29/9/20) had an unexplained issue (twice!) with my Azure Functions App. For seemingly no reason, the app will randomly crash and report this error on Azure portal:

```Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.```

I should mention:
- I am able to successfully deploy the app and runs it fine for some time initially.
- I have the "AzureWebJobsStorage" app config with appropriate value for storage access key.
- A weird fix I found was to delete the app config and re-add it (using exact same key:value pair).

It's like the app temporarily forgets/ignores the fact it has the app config required and re-adding reminds the app.

Also, I've noticed that a new Azure CLI version was released on 29/9/20. This could be related...

**Comment by balag0** [comment]
Could you share the app name. You can use the instructions at https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately if required.

**Comment by KarFan-FS** [comment]
Sure. I believe this is what you need:

```2020-10-06T06:34:54Z   [Information]   Executed 'Functions.user' (Succeeded, Id=f326df73-9164-44cc-a42e-44ee31d03995, Duration=196ms)```

Also, the region is "West Europe".

Some additional info on our function app that may be of use:
- It uses multi-threading to handle multiple simultaneous requests: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#async.
- Language of choice is python (3.7).
- It uses the SignalR negotiate endpoint supported in default extension bundle: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-python.

Update, the same error just happened 20-ish mins before this post so maybe you can search the logs around this time range? Weird thing is, this time it resolved itself (I did nothing to break or fix it!).

**Comment by balag0** [comment]
Thanks. I found the app and the error. Let me take a closer look at this.

**Comment by balag0** [comment]
Found the issue and deployed a quick mitigation that should help reduce the no. of occurances of this error. More comprehensive fix will roll out in a month. Please let us know if you are seeing this error again. ( I do see that this app hasn't been impacted in the last 4 days)

**Comment by older** [comment]
I see this error 2 days in a row. It disappears after manual stop/start. 
I run it in Western Europe. C# functions on linux.

**Comment by balag0** [comment]
@older could you please share the appname.

**Comment by older** [comment]
> 
> 
> @older could you please share the appname.

func-usersync-prod

**Comment by v-anvari** [comment]
Hi @older , Please open a new issue in case the issue persists. Closing the issue as main issue has been fixed
