### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by DamonStamper** [Azure/Azure-Functions#1743]
Please describe the documentation request or issue.  Be as specific as possible.

**Comment by LeonidasKapassakalis** [comment]
In your samples for Azure Python Code you are mentioning and using pyodbc.
Please mention as alternative pypyodbc as in https://github.com/Azure/azure-functions-python-worker/issues/746

**Comment by v-anvari** [comment]
Hi @DamonStamper , Closing this issue as it isn't specific to a particular functionality. In case of any queries, please feel to re-open a new issue with all the details
