### ISSUE TITLE
Update the documentation on creating a bug.

### ISSUE THREAD

**Issue by DamonStamper** [Azure/Azure-Functions#1744]
When creating a bug on github the documentation points to https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions, which has a pinned accouchement directing readers to the "Microsoft Q&A" which is https://docs.microsoft.com/en-us/answers/index.html.

Can the documentation for creating a bug be updated to reflect this change in process?

**Comment by v-anvari** [comment]
Hi @DamonStamper , Apologies for the delayed response, Can you point us to the link that you want an update to

**Comment by v-anvari** [comment]
Closing this issue   as there is no response, please feel free to reach back to us in case of any   further queries related to this issue
--
