### ISSUE TITLE
Log Stream is erratic

### ISSUE THREAD

**Issue by pdhimate** [Azure/Azure-Functions#1746]
The Classic => Platform Features => Log Stream work very well. All logs are shown instantaneously and none of the logs are missed out.

Whereas the Log Stream in the new UI does not work well. 
- Often it does not misses out logs. 
- After a while it completely stops showing logs even after clearing and starting logs again. 
- After Clearing logs, the old logs are shown again.

**Comment by v-anvari** [comment]
Hi @pdhimate , Apologies for the delayed response. The fix should be made by now, please tell us if you are still facing the same issue, so that we can take a closer look

**Comment by v-anvari** [comment]
Closing this issue   as there is no response, please feel free to reach back to us in case of any   further queries related to this issue
--
