### ISSUE TITLE
Clarification on Client Certificates

### ISSUE THREAD

**Issue by SeaDude** [Azure/Azure-Functions#1748]
I'm unable to get client certificates working in my Python HTTP-triggered Azure Function. Please advise on what I can do here. 

**Setup:**

- Python runtime
- HTTP triggered Function
- Successfully deployed to a B1 App Service Plan
  - Per the docs [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth#scale-up-your-app-service-plan), B1 supports mTLS
- `Incoming client certificates` set to `Require`
![image](https://user-images.githubusercontent.com/8636973/95665497-b5eecc00-0b05-11eb-9d8a-a841cf94f520.png)
- `Protocol settings` set to `HTTPS only`
![image](https://user-images.githubusercontent.com/8636973/95665508-c99a3280-0b05-11eb-80b0-b795d253cc64.png)
- Python code is set to read a certificate string from the `X-ARR-ClientCert` header...

```
import logging
import os
import OpenSSL.crypto
import azure.functions as func
from datetime import datetime, timezone, timedelta
from azure.identity import DefaultAzureCredential
from azure.keyvault.certificates import CertificateClient
from azure.cosmosdb.table.tableservice import TableService
from azure.cosmosdb.table.models import Entity
from azure.storage.blob import BlobServiceClient, generate_container_sas, ContainerSasPermissions

def main(req: func.HttpRequest) -> func.HttpResponse:
    try:
        logging.info('Python HTTP trigger certificate validation function processing a request.')

        # Retrieve user certificate from headers

        requestor_cert_string = req.headers.get("X-ARR-ClientCert")
        requestor_id = req.headers.get("requestor-id")

        # Return bad request response if certificate is missing.

        if not requestor_cert_string:
            return func.HttpResponse(
                "Please pass a certificate in request.",
                status_code = 400
            )
```
-... Function then proceeds to check `not_valid_before/after`, `issuer`, `common_name` and `thumbprint` against a pre-shared certificate stored in a database.

- Requestors copy the text from their `cert.pem` file (with correct `/n` characters) into the `X-ARR-ClientCert` header
- Requestor issues GET request to HTTP endpoint

**Issues:**
- When `Incoming client certificates` set to `Require`, response if a Status 403 Forbidden error (**produced by Azure**):
![image](https://user-images.githubusercontent.com/8636973/95665542-40373000-0b06-11eb-9473-f23658ec5a57.png)
- When `Incoming client certificates` set to `Allow`, response is a Status 400 Bad Request error (**produced by the Function code**):
![image](https://user-images.githubusercontent.com/8636973/95665569-7e345400-0b06-11eb-9b65-34eb7a43d371.png)
  - Its like the Function code is not "seeing" the `X-ARR-ClientCert` header in this case

**Questions:**
- Am I approaching this correctly? 
- Is there a Function App setting I'm missing somewhere that will allow `X-ARR-ClientCert` header to be loaded into `pyOpenSSL` for validation?

Thank you

**Comment by anthonychu** [comment]
`X-ARR-ClientCert` header is injected by the App Service platform if a client cert is provided in the request. Your client should not use the `X-ARR-ClientCert` header directly. Instead, pass a certificate in a request as you normally would. Here are the instructions for Postman: https://learning.postman.com/docs/sending-requests/certificates/

If a certificate is provided in the request, the platform should let the call go through to your function and the function should be able to access the cert in the header.

**Comment by SeaDude** [comment]
Aha. Thank you for that clarification. 

So the **Function code** (Python) will still access the cert via `X-ARR-ClientCert` header or is there another name for the relayed header?

**Comment by anthonychu** [comment]
It should be in `X-ARR-ClientCert`. Hopefully that's the correct casing or you can access it in a case insensitive way.

**Comment by SeaDude** [comment]
After generating and uploading self-signed certs in `.crt` and `.key` formats to Postman, here is the response I now get from the Function:
![image](https://user-images.githubusercontent.com/8636973/95666437-80021580-0b0e-11eb-9c22-41b4b7bc37ea.png)

I added some extra logging to see if the headers are being passed... the code is only seeing the first `logging` message, not the subsequent logs:

```
import logging
import os
import OpenSSL.crypto
import azure.functions as func
from datetime import datetime, timezone, timedelta
from azure.identity import DefaultAzureCredential
from azure.keyvault.certificates import CertificateClient
from azure.cosmosdb.table.tableservice import TableService
from azure.cosmosdb.table.models import Entity
from azure.storage.blob import BlobServiceClient, generate_container_sas, ContainerSasPermissions

def main(req: func.HttpRequest) -> func.HttpResponse:
    try:
        logging.info('Python HTTP trigger certificate validation function processing a request.')
        # Certificate Validation
        # ========================

        # Retrieve user certificate from headers
        requestor_cert_string = req.headers.get("X-ARR-ClientCert")
        requestor_id = req.headers.get("requestor-id")

        logging.info('####### Cert header: ' + requestor_cert_string + ' #######')
	logging.info('####### Requestor-id header: ' + requestor_id + ' #######')
```
The Function triggers and "executed successfully", but the code didn't reach completion:
![image](https://user-images.githubusercontent.com/8636973/95666453-a3c55b80-0b0e-11eb-9467-7ffb93c375ba.png)

**Does Azure Function require certs to be in `.pem` format?**

**Comment by anthonychu** [comment]
> Does Azure Function require certs to be in `.pem` format?

Looks like that might be true. @btardif can you confirm?

**Comment by SeaDude** [comment]
K. Trimmed it all down to the bones...

**Created a `.crt` and `.key` file using:** `openssl req -newkey rsa:2048 -nodes -keyout domain.key-x509 -days 365 -out domain.crt`

**Uploaded `.crt` and `.key` files to Postman "Certificates" area**

**Sample Function code:**
```
import logging
import os
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
	
	logging.info('Python HTTP trigger certificate validation function processing a request.')

	# Retrieve user certificate from headers
	requestor_cert_string = req.headers.get("X-ARR-ClientCert")
	requestor_id = req.headers.get("requestor-id")

	logging.info('####### Cert header: ' + requestor_cert_string + ' #######')
	logging.info('####### Requestor-id header: ' + requestor_id + ' #######')

	return func.HttpResponse('yay')
```

**Generate a GET request in Postman results in Status 200:**
![image](https://user-images.githubusercontent.com/8636973/95666924-bb531300-0b13-11eb-9c12-e6e984df9db6.png)

**BUT... the value shown in the Function log for `X-ARR-ClientCert` is nowhere near the original `domain.crt` file...**
![image](https://user-images.githubusercontent.com/8636973/95666947-edfd0b80-0b13-11eb-909a-b4e2790221cb.png)

I expected it have `---BEGIN Cert---` `---END CERT----` or the like. 

**Thoughts on the transformation that is occuring between Postman request and the actual Azure Function?**

**Comment by anthonychu** [comment]
Guessing the header might be base64 encoded. Can you try decoding it before printing?

**Comment by SeaDude** [comment]
Need to know what the characters are encoded with...`UTF8`, `ascii`, `cp1252`, etc. I can't get results (though my .decode might be incorrect).

**New Function testing code:**

```
import logging
import os
import base64
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
	
	logging.info('####### Python HTTP trigger certificate validation function processing a request. #######')

	# Retrieve user certificate from headers
	requestor_cert_string = req.headers.get("X-ARR-ClientCert")
	requestor_id = req.headers.get("requestor-id")

	message_bytes = base64.b64decode(requestor_cert_string)
	message = message_bytes.decode('ascii')
        # Also tried: message = message_bytes.decode('UTF8')
        # Also tried: message = message_bytes.decode('cp1252')

	logging.info('####### Cert header: ' + message + ' #######')
	logging.info('####### Requestor-id header: ' + requestor_id + ' #######')

	return func.HttpResponse('yay')
```
**Postman request:** Same as previously tested (.crt uploaded using Postman `Settings/Certificates`)

**Postman response:** `Status 500 Internal Server Error`

**Function log:**

- If `message = message_bytes.decode('ascii')`:

```
Result: Failure Exception: UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 1: ordinal not in range(128) Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 343, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func return func(**params) File "/home/site/wwwroot/certiFunc/__init__.py", line 19, in main message = message_bytes.decode('ascii') 
```
- If `message = message_bytes.decode('UTF8')`:

```
Result: Failure Exception: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 343, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func return func(**params) File "/home/site/wwwroot/certiFunc/__init__.py", line 15, in main message = message_bytes.decode('UTF8') 
```
- If `message = message_bytes.decode('cp1252')`

```
Result: Failure Exception: UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 403: character maps to <undefined> Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 343, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func return func(**params) File "/home/site/wwwroot/certiFunc/__init__.py", line 15, in main message = message_bytes.decode('cp1252') File "/usr/local/lib/python3.8/encodings/cp1252.py", line 15, in decode return codecs.charmap_decode(input,errors,decoding_table)
```

**Comment by SeaDude** [comment]
Ok. I'm determined to get this today! Need help though!

The `X-ARR-ClientCert` header is not coming over in just base64. There is somekind of additional char encoding or something.

**Revised test code:**
```
import logging
import base64
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
	
	logging.info('####### Python HTTP trigger certificate validation function processing a request. #######')

	# Retrieve client cert from headers
	req_cert_bytes = req.headers.get("X-ARR-ClientCert")
	req_id = req.headers.get("requestor-id")

	req_cert_string = req_cert_bytes.decode('utf-8')
	decoded_header = base64.b64decode(req_cert_string)

	logging.info('####### Requestor-id header: ' + req_id + ' #######')

	return func.HttpResponse(decoded_header)
```

**Results in:**
![image](https://user-images.githubusercontent.com/8636973/95689472-d67e5b00-0bc5-11eb-82c1-bf4b36abbf22.png)

**This is part decoded text, part binary(?) or something.** Please advise on how to decode this header!
Thank you

**Comment by anthonychu** [comment]
Not sure if this is helpful or if you’ve found it already, but these are the instructions on how you’d do it in Node or Java. https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth#access-client-certificate

Hopefully it gives you some clues. Looks like we are missing a Python example in that doc.

**Comment by SeaDude** [comment]
Thanks @anthonychu . Yes, I've seen this (and tried to translate just about every other example on the net!). 

I need the Python equivalent of:
```
byte[] clientCertBytes = Convert.FromBase64String(certHeader);
                        certificate = new X509Certificate2(clientCertBytes);
```

**Comment by SeaDude** [comment]
**The X-ARR-ClientCert header passed from Azure is not merely base64 encoded...**

```
import logging
import base64
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
	
	logging.info('####### Python HTTP trigger certificate validation function processing a request. #######')

	# Retrieve client cert from headers
	req_cert_bytes = req.headers.get("X-ARR-ClientCert")
	
	return func.HttpResponse(
		base64.b64decode(req_cert_bytes)
	)
```

**Results in:**
![image](https://user-images.githubusercontent.com/8636973/95690614-e7cb6580-0bcd-11eb-8359-c017aba83153.png)

If I knew how it was encoded, I could determine how to decode in using python. This is the big mystery.

**Comment by SeaDude** [comment]
[StackOverflow time](https://stackoverflow.com/questions/64309694/how-to-decode-x-arr-clientcert-header-using-python)...

**Comment by SeaDude** [comment]
I feel like the answer lies [here](https://docs.microsoft.com/en-us/archive/blogs/asiatech/configuring-arr-with-client-certificate) (step 4). 

- Because Python 3 encodes by default as utf-8, i'll have to do something "special" to encode as ascii
- Then encode the header as ascii bytes(?) and somehow call it an "X509" using the `cryptography(?)` Python library

Definitely above my paygrade! 

Would be awesome if someone from Microsoft could weigh in difinitevely.

**Comment by anthonychu** [comment]
Adding other Python functions folks @stefanushinardi @anirudhgarg @Hazhzeng @vrdmr

**Comment by SeaDude** [comment]
Woohoo! @krishg helped out [here](https://stackoverflow.com/questions/64309694/how-to-decode-x-arr-clientcert-header-using-python?noredirect=1#comment113737180_64309694) on StackOverflow. 

**Turned out being:**
```
req_cert_str = req.headers.get("X-ARR-ClientCert")
  
req_cert_bytes = base64.b64decode(req_cert_str)

cert = x509.load_der_x509_certificate(req_cert_bytes)

```

**Comment by anthonychu** [comment]
🎉🎉🎉

Would be good to add an example in the docs. @stefanushinardi @ggailey777 can you please follow up? (this is app service docs though)

**Comment by krish-gh** [comment]
@anthonychu, I guess https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth is the doc you mean? I will also see if I can raise a PR to add a python example there.

@SeaDude , that's not my id here in github :)

**Comment by bigdatamoore** [comment]
HI @SeaDude  or @anthonychu if you were able to get this working, could one of you share a sample or example of the MTLS verification for Python functions?  I see examples for other languages here: https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth
but I can't find a working solution for Python.

**Comment by ericthomas1** [comment]
Hi @bigdatamoore ,

I was able to get this working and off into production. I can't share the code and its likely highly subjective depending on your org's requirements. 

**In my case, the gist is:**
- Retrieve the cert from the `X-ARR-ClientCert` header
- Pull the properties from the cert using the library of your choice (I chose `cryptography`, but I believe `OpenSSSL` also has the tooling)
- If required, perform an OCSP lookup
  - This will require you first get the CA's cert URL from the appropriate property on the request cert
  - [Here](https://stackoverflow.com/questions/64436317/how-to-check-ocsp-client-certificate-revocation-using-python-requests-library) is the bounty I put out to get this done!
- Aside from that, again, it will be highly subjective
- I'm doing some fun stuff with Key Vault, Table Storage, etc. but again, can't share the code. 
Good luck!

**Comment by raj4j2ee** [comment]
please let me know once the value is read req_cert_bytes = req.headers.get("X-ARR-ClientCert"), now how this need to be validated in Function app python to find correct certification are passed. I was planning to store .cer content in Azure keyvault and compare this with req_cert_bytes. Appreciate any suggestions soon.

**Comment by ericthomas1** [comment]
I store the cert text in an Azure Table, pull it into the Azure Function, then compare all the attributes (the cert passed in the `X-ARR-ClientCert` header and the one stored in the Azure Table).
