### ISSUE TITLE
How to update Machine Learning model deployed using Azure Function

### ISSUE THREAD

**Issue by jay2017-git** [Azure/Azure-Functions#1749]
I have a machine model that I deployed using docker on Azure Function(HTTP Trigger).  How do I continuously update the PyTorch model running in the Azure function?

**Comment by anthonychu** [comment]
One way is to put the model in Azure Files or Blob Storage and [mount it](https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-mount-files-storage-linux). If you're caching the model in your function app, you need some code to check if the file has been updated and refresh the cache. Another strategy is to upload new models as new files, and use an app setting to configure the name of the file to read. When you update the app setting, the app will restart and obtain the new value.

**Comment by jay2017-git** [comment]
@anthonychu Thanks, for the recommendation. Is there a way I can configure the Function app to restart itself or have something externally restart it.

**Comment by v-anvari** [comment]
Apologies, Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue. In case you still have queries, please open a new issue for better reach, with all the required template details. This will help us in faster resolution
