### ISSUE TITLE
[Visual Studio] project.lock.json is published, which breaks NuGet restore on the server

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#175]
The Publish dialog in the Functions Visual Studio tooling publishes `project.lock.json` even if it is excluded from the list. This causes NuGet package restore to **not** be performed on Azure Functions in Azure, since it sees that there is an up-to-date `project.lock.json` file.

**Workaround \# 1**, suggested by @mattdrewitt below:

Add following to `.funproj`:
```
<ItemGroup>
  <JsonLocks Include="$(ProjectDir)\**\project.lock.json" />
</ItemGroup>
<Target Name="AfterBuild">
  <Delete Files="@(JsonLocks)" />
</Target>
```

**Workaround \# 2**

Add a line to exclude `project.lock.json` in `ExcludePatterns` in the file `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AzureFunctions\Microsoft.AzureFunctions.Publishing.targets`.

NOTE: you will need to open the file in an admin context to be able to make edits.

![image](https://cloud.githubusercontent.com/assets/4260261/22571155/68d5eebc-e953-11e6-87ec-4c3684247f19.png)

Full file:
```xml
	<Target Name="MsDeployPublish" DependsOnTargets="$(MsDeployPublishDependsOn)">
 
            <PropertyGroup>
                  <PublishIntermediateOutputPath Condition="'$(PublishIntermediateOutputPath)' == ''">obj\PublishTemp\</PublishIntermediateOutputPath>
                  <PublishIntermediateOutputPath Condition="'$([System.IO.Path]::IsPathRooted($(PublishIntermediateOutputPath)))' == 'False'">$(MSBuildProjectDirectory)\$(PublishIntermediateOutputPath)</PublishIntermediateOutputPath>
                  <ExcludePatterns>
                        $(MSBuildProjectDirectory)\bin\**;
                        $(MSBuildProjectDirectory)\obj\**;
                        $(MSBuildProjectDirectory)\**\*.funproj;
                        $(MSBuildProjectDirectory)\**\*.pubxml;
                        $(MSBuildProjectDirectory)\**\*.user;
                        $(MSBuildProjectDirectory)\**\project.lock.json;
                  </ExcludePatterns>
            </PropertyGroup>
 
            <ItemGroup>
                  <PublishOutDir Include="$(MSBuildProjectDirectory)\**" Exclude="$(ExcludePatterns)" />
            </ItemGroup>
 
            <Copy
                  SourceFiles="@(PublishOutDir)"
                  DestinationFiles="@(PublishOutDir -> '$(PublishIntermediateOutputPath)\%(RecursiveDir)%(Filename)%(Extension)')" />
 
      </Target>
```

**Comment by mattdrewitt** [comment]
For a solution that can be used within a team without the need for everyone to manually modify, we added the following to our `.funproj` file:
```
<ItemGroup>
  <JsonLocks Include="$(ProjectDir)\**\project.lock.json" />
</ItemGroup>
<Target Name="AfterBuild">
  <Delete Files="@(JsonLocks)" />
</Target>
```

**Comment by lindydonna** [comment]
@mattdrewitt Thanks for the workaround!  I've added it to the comment at the top so more folks can see it.

**Comment by lindydonna** [comment]
Handled by new version of VS 2017 tooling
