### ISSUE TITLE
[Detector] Show bundle changes in function app changes detector

### ISSUE THREAD

**Issue by fabiocav** [Azure/Azure-Functions#1752]
From the detector work item:

We have the Detector called Function App Changes. It has children that shows the Host Version, Antares Changes, Deployment from customers. It is useful to show when things have changed even if the customer thinks nothing has changed.

**Comment by pragnagopa** [comment]
Added `ListExtensionBundleVersions` detector - that lists extension bundle versions used by the app in the past 7 seven days.

Also, updated `DetectChangesInAFunctionApp` detector to include `ListExtensionBundleVersions`

Closing as addressed.
