### ISSUE TITLE
Monitoring doesn't show function executions when custom cloud role name is used

### ISSUE THREAD

**Issue by PiotrPerak** [Azure/Azure-Functions#1755]
Monitoring of Azure functions does not show function executions when custom cloud role name is used
![image](https://user-images.githubusercontent.com/789129/96995982-61007c00-152f-11eb-883d-5b6571532ac6.png)

```
public class Startup : IWebJobsStartup
{
    public void Configure(IWebJobsBuilder builder)
    {
        builder.Services
            .AddSingleton<ITelemetryInitializer, CloudRoleNameInitializer>();

        // more registrations
    }

CloudRoleNameInitializer

 public class CloudRoleNameInitializer : ITelemetryInitializer
 {
    public void Initialize(ITelemetry telemetry)
    {
        telemetry.Context.Cloud.RoleName = "EmailPuller";
    }
 }
```
When I click run query in application Insights the query generated is

```
requests
| project timestamp, id, operation_Name, success, resultCode, duration, operation_Id, cloud_RoleName, invocationId=customDimensions['InvocationId']
| where timestamp > ago(30d)
| where cloud_RoleName =~ 'emailpuller-UNIQUE_ID_FROM_ARM_TEMPLATE' and operation_Name =~ 'OurOperationName'
| order by timestamp desc
| take 20
```
It's not taking into account custom cloud role but should.

**Comment by anthonychu** [comment]
@brettsam @apawast

**Comment by brettsam** [comment]
I'm not sure if there's anything we can do there as we don't know what your custom role name is from the portal. That's all happening in code at runtime and the Functions portal makes an assumption that the role name matches the app name.

If you need to run a custom cloud role name, you may have to run your queries directly in the App Insights portal blade -- which allows for much richer queries and charts, etc.

**Comment by PiotrPerak** [comment]
I decided to not use custom role names because of this. Easy monitoring is more important to me than nice names.

**Comment by furier** [comment]
Could we not be able to set custom cloud_rolename through an application setting or something and then the portal could pick up on that?
