### ISSUE TITLE
Azure Function "App Service Authentication" configured but still can't access the resource.

### ISSUE THREAD

**Issue by mallecespedes** [Azure/Azure-Functions#1756]
We're trying to use an Azure Function (HTTP type) from Azure Data Factory (ADF). 
In the beginning, we executed the function with the App Service Authentication feature **OFF** and it worked correctly.

Due to security implementation, we had to turn **ON** the App Service Authentication and in "Action to take..." select other than "Allow Anonymous requests". As we are using ADF to call the function, we selected "Log in with Azure Active Directory". We set up all the configuration needed: Created AAD App and used the IDs generated to link the Azure Function to the App.

The configuration looks like this:
![image](https://user-images.githubusercontent.com/35578657/97059050-12fe6f00-1555-11eb-8045-6814b7954e83.png)

- The client ID is the one from the AAD App.
- In the Issuer URL we have the endpoint + the tenant id.

We have tried with:

- Empty "Allowed Token Audiences" 
- The issuer URL as <authentication-endpoint>/<tenant-id>/v2.0
- The issuer URL as <authentication-endpoint>/<tenant-id>/.auth/login/aad/callback
- The issuer URL as https://login.microsoftonline.com/common/oauth2/v2.0/authorize
- The issuer URL as https://login.microsoftonline.com/common/oauth2/authorize

All this with no successful result.

**Comment by v-anvari** [comment]
Hi @mallecespedes , I tried to reproduce the scenario and got "Call to provided Azure function 'HttpTrigger1' failed with status-'Unauthorized' and message - 'You do not have permission to view this directory or page.'." Can you confirm if this is the error that you are getting.

**Comment by v-anvari** [comment]
From the Functions stand point we are not sure if its a feature that data factory supports. Kindly connect with the data factory support team.
[https://feedback.azure.com/forums/270578-data-factory](https://feedback.azure.com/forums/270578-data-factory)
[https://azure.microsoft.com/en-us/support/options/#submit](https://azure.microsoft.com/en-us/support/options/#submit)

**Comment by mallecespedes** [comment]
> Hi @mallecespedes , I tried to reproduce the scenario and got the following error "Call to provided Azure function 'HttpTrigger1' failed with status-'Unauthorized' and message - 'You do not have permission to view this directory or page.'." Can you confirm if this is the error that you are getting.

Yes, it is.

**Comment by balag0** [comment]
@mallecespedes In case you haven't seen this page already - https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad#-enable-azure-active-directory-in-your-app-service-app


Issuer Url | Use **<authentication-endpoint>/<tenant-id>/v2.0**, and replace <authentication-endpoint> with the authentication endpoint for your cloud environment (e.g., "https://login.microsoftonline.com" for global Azure), also replacing <tenant-id> with the Directory (tenant) ID in which the app registration was created. This value is used to redirect users to the correct Azure AD tenant, as well as to download the appropriate metadata to determine the appropriate token signing keys and token issuer claim value for example. For applications that use Azure AD v1 and **for Azure Functions apps, omit /v2.0 in the URL**.
-- | --

Can you check if this helps?
