### ISSUE TITLE
How to control the max concurrent calls (for a servicebus trigger)?

### ISSUE THREAD

**Issue by worldspawn** [Azure/Azure-Functions#176]
Hello,

I was wondering how one can control the maximum number of concurrent calls a service bug trigger will run. In my case the code is hitting a sql server so theres only so much concurrency I want going on. 

Webjobs api allows you to do this when configuring the service bus however it doesn't allow control over specific triggers (just all service bus triggers) which causes you to deploy more webjobs than u would otherwise need - hope theres better control for functions.

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1466
