### ISSUE TITLE
[FunctionApp create] Add permission check for an existing storage account resource in pre-flight validation API

### ISSUE THREAD

**Issue by shimedh** [Azure/Azure-Functions#1761]
@jeffhollan FYI. Currently, during FunctionApp create, there is no permission check in the pre-flight validation API for the storage account selection. Due to this, the user may start create and it would fail on creation. Having the check in pre-flight validation API will block them at Review and Create step and also will benefit all clients (not just Portal). For new storage account selection, the check already happens as part of ARM validation of the template.

**Comment by v-anvari** [comment]
Hi @shimedh , Its a quick follow up to understand if this is yet to be implemented or require validation.
