### ISSUE TITLE
ILogger logs written in Application Insight are of EventType Trace when I am logging Error messages

### ISSUE THREAD

**Issue by chigivigi** [Azure/Azure-Functions#1762]
I have a netcore 3.1 Azure Function v3 project. I have set ILogger to log my Error Messages to Application Insights.
The problem is that the logs are not written as Event Type Exception but asEvent Type Trace and when you look at Live Metrics they won't be counted as Exception and you would need to use additional filtering criteria that would be unnecessary if the logs were of event type exception.

My ILogger configuration is defined in my host.json file and it looks like this:
{
  "logging": {
    "logLevel": {
      "NameOfFunctionNamespace": "Information",
      "default": "Information"
    },
    "applicationInsights": {
      "enableLiveMetrics": true,
      "enableDependencyTracking": false
    },
    "snapshotConfiguration": {
      "agentEndpoint": null,
      "captureSnapshotMemoryWeight": 0.8,
      "failedRequestLimit": 7,
      "handleUntrackedExceptions": true,
      "isEnabled": true,
      "isEnabledInDeveloperMode": false,
      "isEnabledWhenProfiling": true,
      "isExceptionSnappointsEnabled": true,
      "isLowPrioritySnapshotUploader": true,
      "maximumCollectionPlanSize": 20,
      "maximumSnapshotsRequired": 3,
      "problemCounterResetInterval": "24:00:00",
      "provideAnonymousTelemetry": false,
      "reconnectInterval": "00:15:00",
      "shadowCopyFolder": null,
      "shareUploaderProcess": true,
      "snapshotInLowPriorityThread": true,
      "snapshotsPerDayLimit": 50,
      "snapshotsPerTenMinutesLimit": 3,
      "tempFolder": null,
      "thresholdForSnapshotting": 1,
      "uploaderProxy": null
    },
    "samplingExcludedTypes": "Request",
    "samplingSettings": {
      "isEnabled": true
    }
  },
  "version": "2.0"
} 

Additionally I have added Logging as a Service in my IFunctionsHostBuilder builder like this (Startup.cs):

        public override void Configure(IFunctionsHostBuilder builder)
        {
            var hostingEnvironment = builder.Services.BuildServiceProvider().GetService<IHostingEnvironment>();
            string environment = "Development";
            if (!string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")))
                environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT").ToLower();
            IConfigurationRoot config = new ConfigurationBuilder()
                        //.SetBasePath(!string.IsNullOrEmpty(Environment.GetEnvironmentVariable("FUNCTIONS_ROOT_PATH")) ? Environment.GetEnvironmentVariable("FUNCTIONS_ROOT_PATH") : Environment.CurrentDirectory)
                        //.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true).AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: false)
                        .AddEnvironmentVariables()
                        .Build();

            builder.Services.AddMvcCore().AddNewtonsoftJson(o =>
            {
                o.SerializerSettings.ContractResolver = new DefaultContractResolver();
            });

            builder.Services.AddLogging();

            builder.Services.AddSnapshotCollector();
            //builder.Services.AddSnapshotCollector(configuration =>
        }
    }

This is an example of a function sending an error log:

    public class TestFunction
    {
        private readonly ILogger<TestFunction> logger;

        public TestFunction(ILogger<TestFunction> logger)
        {
            this.logger = logger;
        }

        [FunctionName("GetTest")]
        public IActionResult Get(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "Test")] HttpRequest req,
            ILogger log)
        {
            try
            {
                logger.LogError("text exception");
                return new OkResult();
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
                return null;
            }
        }
    }
}

How do I change my ILogger configuration that my Error logs are written as Event Type Exception in Application Insights ?

**Comment by v-anvari** [comment]
Hi @chigivigi , Use the Azure Application Insights core telemetry API to send custom events and metrics, and your own versions of standard telemetry. [api-custom-events-metrics#trackexception](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#trackexception). Let us know if this helps

**Comment by bmedlin** [comment]
@chigivigi - Why would it be necessary to use the application insights API? I think most azure functions developers would assume an exceptions logged via the ILogger API would be treated as exceptions within application insights? Why does trace make more sense?

**Comment by kwaazaar** [comment]
I found that when using ILogger.LogError and only passing a message, so no exception, the error is logged in traces with severityLevel 3. You will still find them, but it's harder to monitor for 'exceptions'.
