### ISSUE TITLE
EventGrid-triggered Python Function keeps triggering

### ISSUE THREAD

**Issue by ericthomas1** [Azure/Azure-Functions#1763]
There are a couple other topics out there, but none with solutions or none pertaining to Python Functions.

**Background**:

- EventGrid-triggered, Python Azure Function
- EventGrid messages created only when a blob is uploaded to a given Storage Account
- Function receives message, downloads blob from message URL and does "stuff"
- Function *can* run for several seconds/minutes (up to 120 seconds for large blobs) but generally runs in ~1 - ~10secs.

**Example of issue:**

- 4 files uploaded to blob container in correct Storage Account
- Function successfully triggered 4 times, by 4 separate EventGrid messages
- Function downloads blob from URL in each message, does "stuff"
- **NOTICE: The Function in this case is only running for ~1 - 4.5secs. This is well within the EventGrid 30sec retry window!!**
- ~55 seconds later, 4 more EventGrid messages trigger the Function all over again (for the same 4 files!)
- Everything repeats

**This happens multiple times resulting in 12 Function executions for 4 files:**

**And corresponding output from the "stuff" the Function does!**

![image](https://user-images.githubusercontent.com/42788729/98144828-6ccd3600-1e7f-11eb-93b4-c470248c208d.png)

It gets ridiculous when 2500 files are uploaded to the Storage Account!

Seems like I need to adjust the EventGrid retry timing. But I don't see a setting for this in the Portal:

![image](https://user-images.githubusercontent.com/42788729/98145177-9b4b1100-1e7f-11eb-9f6c-33cfcf3422ac.png)

**How do I prevent this behavior?**

**EDIT 1:**  Then today... no issue with 16 files uploaded... why is this Function inconsistently being triggered by EventGrid?

![image](https://user-images.githubusercontent.com/42788729/98150309-4a3d1c00-1e83-11eb-86a6-0dd15d4da15f.png)

**EDIT 2:** And again today... for no reason, ~an hour later... EventGrid fired off a bunch more triggers... 

![image](https://user-images.githubusercontent.com/42788729/98154092-14029b00-1e89-11eb-99af-9b6ba30216af.png)

**...though NO MORE FILES have been uploaded to the storage account.**

![image](https://user-images.githubusercontent.com/42788729/98154239-5926cd00-1e89-11eb-8600-b6aebda3c19e.png)

This is quite frustrating. I need help debugging this.

Thank you

**Comment by ericthomas1** [comment]
This is what the Event Grid monitoring currently looks like for 16 files uploaded to storage. Should be 16 EventGrid messages sent and 16 received. 

**You can clearly see the numbers are all over the place:**
![image](https://user-images.githubusercontent.com/42788729/98154695-03065980-1e8a-11eb-9c2d-ca9d9ffb17d3.png)

Some are successful, some are not. Every one has been retried multiple times....ehk!

**Comment by v-bbalaiagar** [comment]
Hi @ericthomas1, Apologies for the delayed response, We would like to know if you are still seeing these error. We would like to check the back end logs to understand the scenario better.
Can you please provide the following details to check the logs?
Timestamp:
Function App version: -
Function App name: -
Function name(s) (as appropriate):
Invocation ID:
Region:

**Comment by ericthomas1** [comment]
Hi @v-bbalaiagar ,

I was able to figure this out. 
**The issue was:**
- In my DEV setup, i usually upload blobs using Azure Storage Explorer (ASE) to test my Function's Event Grid Trigger
- In PROD, blobs are uploaded using Azure *Data Factory* (ADF)
- Turns out, these two tools use **different** blob storage API's to upload
- My Function code pulls the URL from the EventGrid message
- When ASE API is used, this is no problem as the URL is retrieved from the `data:url` parameter
- When ADF API is used (`FlushWithClose`), there was no `data:url` parameter in the EventGrid message 
- The `data.url` parameter was recently added to the schema, so this solved the issue
- I also amended my Function code to handle the exception where url is not found
