### ISSUE TITLE
 Could not load type 'Microsoft.Azure.Cosmos.Table.CloudTable'

### ISSUE THREAD

**Issue by NoelOConnell** [Azure/Azure-Functions#1767]
We have a Function running with a `QueueTrigger("%Queues:Name%")`

Using the combination of packages below causes the function to throw an error on startup.

```
<PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="2.0.0-preview" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
```

```
 Microsoft.Azure.WebJobs.Extensions.Storage: Could not load type 'Microsoft.Azure.Cosmos.Table.CloudTable' from assembly 'Microsoft.Azure.Cosmos.Table, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
``` 

![image](https://user-images.githubusercontent.com/966495/98272830-74790180-1f89-11eb-8709-e188c4fc4db1.png)

**Comment by fabiocav** [comment]
@NoelOConnell you're using and binding to a version of the storage SDK that is not yet supported by the extension. The type you're binding to is not recognized by the binding.

If you want to use the preview package, you'd need to consume the SDK directly and not use the biding/extension until that version is supported.
