### ISSUE TITLE
[Spec] Orchestrator that is not durable

### ISSUE THREAD

**Issue by MhAllan** [Azure/Azure-Functions#1769]
Looking at orchestrators, I think the only reason orchestrators need to be durable is that we want to destroy it during IO and resume with new one after IO return. While that is valid reason, there are so many reasons to create non-durable orchestrator

- Scenarios where simplicity is more important than cost
- Avoid complexity and limitations introduced by durable orchestrator
- Avoid slowness of using state on storage
- Ability to pass cancellation to activity functions
- Replace Http triggered functions with Activity functions (by replacing asp.net core calling http triggered functions with orchestrator calling activity functions)

**Comment by v-anvari** [comment]
Hi @MhAllan , As this would require changes in the design. You can submit a feature/ idea request here, this would increase the visibility https://feedback.azure.com/forums/355860-azure-functions

**Comment by MhAllan** [comment]
Thanks @v-anvari 

for voting: https://feedback.azure.com/forums/355860-azure-functions/suggestions/43769364-orchestrator-that-is-not-durable
