### ISSUE TITLE
[Spec] Automatic function name without [FunctionName]

### ISSUE THREAD

**Issue by MhAllan** [Azure/Azure-Functions#1771]
Simply, function name is ClassName.MethodName .. no need to always be forced to provide this attribute.

**Comment by v-anvari** [comment]
Hi @MhAllan , can you share more details of your use case, how does it help? Thanks!

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue

**Comment by MhAllan** [comment]
Hi, sorry I missed the question to me. That will help in two ways. First, I was getting my functions failing to trigger and I spent long time to realise the attribute is a must. So if we drop the attribute we avoid that. Second, there is no need to such attribute, we can use the method name itself if the attribute is missing.
