### ISSUE TITLE
Azure Proxies Functions App - Headers not applied

### ISSUE THREAD

**Issue by chchadha** [Azure/Azure-Functions#1773]
I am trying to add a no sniff header and have added the following configurations in my proxies.json file and have the proxies.json file configured below. The changes are deployed through a CI / CD pipeline (variables are applied during deployment, etc). However, I am unable to override the response header. 

Azure Function Runtime 3.0

Proxies Values (In Azure Portal)

Proxy URL: .....azurewebsites.net/{*allpaths}
RouteTemplate: {*allPaths}
BackendUrl: https://%BackendDomainName%{*allPaths}

``{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "globalProxy": {
      "matchCondition": {
        "methods": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ],
        "route": "{*allPaths}"
      },
      "responseOverrides": {
        "response.headers.X-Content-Type-Options": "nosniff"
      },
      "backendUri": "https://%BackendDomainName%/{*allPaths}"
    }
  }
}

host.json

{
  "extensions": {

    "http": {
      "routePrefix": "api",
      "customHeaders": {
        "X-Content-Type-Options": "nosniff"
      }
    }
  },
  "functionTimeout": "00:10:00",

  "version": "2.0"
}

**Comment by v-anvari** [comment]
Hi @chchadha , We would like to have more insights on the scenario to understand it better. Can you please give us more details regarding the error that you are seeing. Kindly provide the repro steps for us to clone the issue and get the error.
