### ISSUE TITLE
Fixes + clarifications to CoreTools Release pipeline

### ISSUE THREAD

**Issue by madelinegordon** [Azure/Azure-Functions#1774]
[Pipeline](https://azfunc.visualstudio.com/Azure%20Functions/_releaseDefinition?definitionId=23&_a=environments-editor-preview)

"Upload MSI to storage":
-  Add "Note: this does not apply to V2 CoreTools release."
- change to only execute the task when the branch is not main (e.g. only execute the task during the v3 release)

"Update NPM":
- Add to instructions: 
`cd src/Azure.Functions.Cli/npm`
 `npm version [VERSION of azure-functions-core-tools]`
`npm publish`

**Comment by madelinegordon** [comment]
+ @sidkri 

More updates in [this release]( https://azfunc.visualstudio.com/Azure%20Functions/_releaseProgress?releaseId=2022&_a=release-pipeline-progress) to be copied over to the pipeline.

**Comment by fabiocav** [comment]
Initial work scoped by this issue has been completed. @madelinegordon is opening a new issue to track the additional work that has been identified.
