### ISSUE TITLE
[Premium] unhandled exception host is shutting down did not complete in 00:02:00 Microsoft.Azure.WebJobs.Extensions.Storage.TimeoutHandler

### ISSUE THREAD

**Issue by lovettchris** [Azure/Azure-Functions#1776]
**Describe the bug**
My Azure Function works perfectly when I run it locally, but in azure on Premium SKU "P1V2" I'm getting a weird timeout in platform code "azure-webjobs-sdk-rqm4t".

**To Reproduce**
1. Set host.json functionTimeout to 20 minutes (allowed on premium plan).
2. Deploy an C# Azure Function that runs on x64 platform, that uses an intensive managed C++ library for image processing.  In my case I'm doing 3D reconstruction from photos (see https://aed-synthetics.azurewebsites.net/).  
2. Try and run a job that takes more than 10 minutes.

**Expected behavior**
Should run to completion.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/18707114/99037583-d19c2680-2538-11eb-8145-9e8631b97145.png)

**Additional context**
Could be related to https://github.com/Azure/azure-webjobs-sdk/issues/2506 which apparently is an issue that has been plaguing the team for months.  Well I have a 100% repro to help debug this.  I suspect some sort of thread starvation is happening that is blocking azure storage traffic somehow... or a deadlock on those azure storage threads, not sure which.

**Comment by v-anvari** [comment]
Hi @lovettchris , Apologies for the delayed response. There were few changes made to the timeout attribute the recent past, Can you tell us if you still this exception. If yes, then we would require to further investigate this issue

**Comment by lovettchris** [comment]
I moved to P3V2 and things are working fine with longer timeouts.

**Comment by v-anvari** [comment]
Thank you for the confirmation, closing this issue as the error doesn't exist anymore
