### ISSUE TITLE
[Premium] Function CPU consumption reaches 100% on host spin up

### ISSUE THREAD

**Issue by abinashkd** [Azure/Azure-Functions#1782]
**Describe the bug**
I have function which is running in EP2 with max burst set to 20. 
I have checked the logs, for few of the times the CPU reaches 100% when a new host spins up. Though this is a momentary issue (stays barely for 2s-3s and avg. cpu is below 50%). 
Is this a known issue. Any help is much appreciated.

**Comment by abinashkd** [comment]
![CPU](https://user-images.githubusercontent.com/12938474/99936369-f8ecc200-2d88-11eb-82fd-8d4a8bdf2478.png)

**Comment by v-anvari** [comment]
Hi @abinashkd , Apologies for the delayed response, Can we know if you are still facing this issue.

**Comment by abinashkd** [comment]
@v-anvari Yes last I checked the issue was still present. Though I don't have access to the function runtime anymore, but faced observed the CPU spike on numerous occasions on a host spin up.

**Comment by v-anvari** [comment]
Hi @abinashkd , Apologies, but, we would require some details to look into the logs, even a  support request can be helpful in such cases where the issue is specific to your function App.

**Comment by abinashkd** [comment]
@v-anvari I don't have access to the resource any more, let's close the issue. Thank you for your guidance.
