### ISSUE TITLE
[Premium] Functions stopping randomly during the middle of execution without throwing any exceptions

### ISSUE THREAD

**Issue by toni-ar** [Azure/Azure-Functions#1789]
**Describe the bug**
When triggering multiple azure function executions with Service Bus, some randomly stop without throwing any exceptions while some finish their work normally. As far as I can see, functions that freeze are almost always on the same `ProcessId`

**To Reproduce**
1. Create a function that does some work and gets triggered by service bus
2. Trigger multiple function executions close to each other (about 30-50 of them, started 1-5 seconds apart, I can be even minutes apart)
3. Some percentage of triggered functions will stop during their work without throwing any exceptions, rest will finish their work.

**Expected behavior**
All functions should finish without exceptions or throw an exception that shows why they stopped.

**Additional context**

Plan: Elastic Premium (EP1: 1)
Azure function is Windows based

## Repository with code that can reproduce the problem

https://github.com/toni-ar/stress-test
I created a GitHub repository with code that simulates data processing, Data processing is simulated by calculating Nth prime number, writing and deleting files from the disk.

- Implemented 2 function that use `Service Bus`:
   - `DataProcessingStressTestTrigger`
      - Developer should trigger this function using `Service Bus Explorer` and `stress-test-dp-trigger` queue
      - This function triggers N amount of `DataProcessingStressTest` functions with a provided delay using `Service Bus`
      - The whole execution is given a `GUID`
      - Assigns an `Id` to each triggered function `[1 .. N]`
   - `DataProcessingStressTest`
      - Function is triggered by `stress-test-dp`
      - This function simulates data processing
 -  "autoComplete" for azure functions is turned off, we manually remove messages from the Service Bus queue at the beginning of our function code.

That code can **sometimes** reproduce this problem, it happens randomly though, sometimes all functions started finish, sometimes a huge percentage freeze.

README in the repository describes in detail how to run the test, example parameters, Application Insights queries that show what is happening and screenshots of the logs of one execution where out of 30 functions started 19 finished successfully and 11 that stopped without exceptions.

## Another report with logs:
https://github.com/toni-ar/stress-test/wiki/Report
50 functions started, 10 of them stopped without any exceptions in the middle of execution.
All functions that stopped were on the ProcessId = 1812
Function numbers that stopped: 22, 23, 25, 27, 29, 31, 33, 35, 38, 42
Note that number 17 was on the same process id but it didn't stop, it finished normally

**Comment by v-anvari** [comment]
Hi @toni-ar, Apologies for the delayed response. We were unable to reproduce the scenario, can you let us know if you are still facing this issue in premium plan
