### ISSUE TITLE
Does Azure Functions have non-persistent (or persistent) disk space?

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#179]
This question was raised over twitter. Let's see if we can get a topic that addresses this in the general developer topics.

**Comment by SyntaxC4** [comment]
Technically, the user has access to non-persistent disk space in `d:\local`, however, because we move Functions around to different machines for scale, the disk space would only be available for the life-time of a single execution.

**Comment by lindydonna** [comment]
Customers should use their storage account for disk usage.

**Comment by SyntaxC4** [comment]
@christopheranderson - There are probably a lot of issues that we would need to outline around d:/local is this something that we want to address as we'll have a hard time listing all of the exceptions of when you shouldn't use this.

**Comment by lindydonna** [comment]
They can use the HOME environment variable to get to their local directory. If using the Consumption plan, this will be backed by Azure Storage.

I don't know that there's any action here, other than documenting the HOME variable.

**Comment by lindydonna** [comment]
Superceded by https://github.com/Azure/Azure-Functions/issues/313

**Comment by jsimmonsdavidccook** [comment]
How much space is available in HOME or D:\local ?
Is there a recommended solution for using System.IO based APIs? I want to create a zip file from multiple blobs, and send that in a response.
