### ISSUE TITLE
Azure Functions can't read the portal underscore configurations

### ISSUE THREAD

**Issue by MhAllan** [Azure/Azure-Functions#1793]
I spent 12 continues hours on this but no hope with whatever I tried or read online.

so I did this
```csharp
Configuration = configBuilder.SetBasePath(context.ApplicationRootPath)
                                         .AddJsonFile("appsettings.json", true, false)
                                         .AddJsonFile($"appsettings.{context.EnvironmentName}.json", true, false)
                                         .AddEnvironmentVariables()
                                         .Build();
```

which worked for appsettings.development.json.

so having this
```json
"CosmosDbSettings": {
    "Database": "LoadTestDb"
  }
```

this worked : ```var settings = Configuration.GetSection("CosmosDbSettings").Get<CosmosDbSettings>();```

But when I deploy, and I write the configuration by azure portal configuration, the function can't read it and it always null.

So this ```CosmosDbSettings_Database``` will not be read by: ```Configuration.GetSection("CosmosDbSettings").Get<CosmosDbSettings>()```

**Comment by anthonychu** [comment]
@MhAllan The .NET convention is to use *double* underscores as separators. Try changing the app setting in Azure to `CosmosDbSettings__Database` and try again.

For more information, take a look at this article: https://docs.microsoft.com/aspnet/core/fundamentals/configuration/#environment-variables

**Comment by MhAllan** [comment]
Thanks a lot @anthonychu
