### ISSUE TITLE
[Question] Azure Function to execute a Shell Script/Function

### ISSUE THREAD

**Issue by chirangaalwis** [Azure/Azure-Functions#1794]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All)
Shell scripting

#### Question
I am in need of executing a Linux Shell based script at an event trigger in Azure (most specifically for [Azure Key Vault Secret rotation](https://docs.microsoft.com/en-us/azure/key-vault/secrets/tutorial-rotation)).

- Is it possible to execute a Shell Script (in the form of a Shell Function) via a an Azure Function to achieve the above?
- If yes, do you have any documentation of guidelines/samples which would aid in achieving this?

**Comment by balag0** [comment]
Shell script is not a supported language. So recommend using one of the languages with first class support since this might break in the future even if you are able to get it working now.

https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages

**Comment by anthonychu** [comment]
Based on what you're trying to do, here are a couple of alternatives:

- Use PowerShell Azure Functions - you can leverage the Az PowerShell module directly to work with Key Vault
- Use the Key Vault SDK with any of the supported languages to programmatically interact with Key Vault

In both of these cases, you can leverage Managed Identity to access Key Vault using the function app's identity.

**Comment by chirangaalwis** [comment]
> Based on what you're trying to do, here are a couple of alternatives:
> 
> * Use PowerShell Azure Functions - you can leverage the Az PowerShell module directly to work with Key Vault
> * Use the Key Vault SDK with any of the supported languages to programmatically interact with Key Vault
> 
> In both of these cases, you can leverage Managed Identity to access Key Vault using the function app's identity.

@balag0 @anthonychu yes I am currently following the option 2.

Thanks for the input.

**Comment by v-anvari** [comment]
Closing the issue as resolved
