### ISSUE TITLE
Unable to Access Key Vault from Azure Functions using User Managed Identities

### ISSUE THREAD

**Issue by swatisatpathy** [Azure/Azure-Functions#1795]
I want to create a "User-Managed Identities" and add to a Function App, and then use that identity to grant our Function App access to a secret stored in Azure Key Vault. But I am getting below error while adding the secrets to the azure function application settings

Status:MSINotEnabled
Error Details: "Key Vault reference was not able to be resolved because site Managed Identity not enabled”

Below are the steps I followed:
1.	Created Managed Identities. In the managed Identities>> Azure role assignments added the azure function as a contributor. 
![image](https://user-images.githubusercontent.com/74755541/100596158-daa33b00-3321-11eb-83d4-78accec641ac.png)

2.	In the azure function Identity section added the managed identity as user-assigned. 
![image](https://user-images.githubusercontent.com/74755541/100596176-e131b280-3321-11eb-895b-cbfb48ea4a48.png)

3.	Now in the Key Vault I have provided access to the managed Identity by adding the access policy.  
![image](https://user-images.githubusercontent.com/74755541/100596197-e68efd00-3321-11eb-90d0-4f8033da4447.png)

4.	Now I have added the secret Key Vault Secret value in Azure function Application Settings 
@Microsoft.KeyVault(SecretUri=<secret URL from Key Vault>) .But It is giving me the below error. 
The error information is not showing in the screenshot but when I select all paste it in a notepad. It is saying “Key Vault reference was not able to be resolved because site Managed Identity not enabled”. 
Not sure how the azure function is checking for System Managed Identity when the only User managed Identity is on. 
![image](https://user-images.githubusercontent.com/74755541/100596223-eee73800-3321-11eb-9d10-93bbe876348b.png)
Can anyone help me with what I am doing wrong here?

**Comment by balag0** [comment]
Only system assigned managed identity is supported for keyvault references currently.

https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

![image](https://user-images.githubusercontent.com/28721598/100666459-e2f17b00-330d-11eb-8740-c969d6fe1710.png)

**Comment by swatisatpathy** [comment]
Thanks @balag0 closing the issue.

**Comment by kmadof** [comment]
I will just leave a note that this is possible now and required is this [step](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#access-vaults-with-a-user-assigned-identity). You need to set `keyVaultReferenceIdentity` as app configuration to indicate that user managed identity will be used to resolve key vault references.

**Comment by Kruti-Joshi** [comment]
@kmadof Does this imply that we need to specify references for all the secrets that we need to fetch in the function, and cannot dynamically pass the secret names and fetch them?

**Comment by kmadof** [comment]
@Kruti-Joshi you can but when you do this programmatically directly from code. Above issue refer to case when you want to map secrets to App Settings and  env variables.
