### ISSUE TITLE
Can no longer create Linux Node.js Function App on Free Tier App Service Plan

### ISSUE THREAD

**Issue by adamhwang** [Azure/Azure-Functions#1796]
Repro steps:
- Create a new Function App through the portal
  - Code based
  - Node.js
  - 12 LTS
  - East US
  - OS: Linux
  - Plan type: App service plan (Free F1)

Expected behavior: This used to work without issue and the new function app would be created as expected

Actual behavior: Deployment fails with the following error:
```
{
    "Code": "Conflict",
    "Message": "Cannot update the site 'FUNCAPPNAME' because it uses x64 worker process which is not allowed in the target compute mode.",
    "Target": null,
    "Details": [{
            "Message": "Cannot update the site 'FUNCAPPNAME' because it uses x64 worker process which is not allowed in the target compute mode."
        }, {
            "Code": "Conflict"
        }, {
            "ErrorEntity": {
                "ExtendedCode": "04066",
                "MessageTemplate": "Cannot update the site '{0}' because it uses x64 worker process which is not allowed in the target compute mode.",
                "Parameters": ["FUNCAPPNAME"],
                "Code": "Conflict",
                "Message": "Cannot update the site 'FUNCAPPNAME' because it uses x64 worker process which is not allowed in the target compute mode."
            }
        }
    ],
    "Innererror": null
}
```

**Comment by anthonychu** [comment]
@adamhwang Do you have an option to create a consumption plan instead? Azure Functions have limitations when running on the free plan and it's not recommended (and as you have seen, there are issues with it with certain combinations like Node + Linux free plan). We're in the process of removing the option from the portal to reduce confusion.

**Comment by adamhwang** [comment]
@anthonychu Yes, thank you. I went with the consumption plan as a workaround. I'm not 100% about the code backed one, but I am fairly confident Linux used to work with a docker container so this feels like a regression. But if this is working as intended removing the options will be helpful. Thanks again

**Comment by v-anvari** [comment]
Closing this issue   as the required information is provided, please feel free to reach back to us   in case of any further queries related to this issue
