### ISSUE TITLE
Document NuGet restore behavior

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#18]
In the Functions runtime, NuGet restore works by comparing project.json and project.lock.json. If they match, NuGet restore is NOT performed, and the packages won't exist. So, project.lock.json should never be deployed and should be in .gitignore.

Update this article: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#package-management

**Comment by SyntaxC4** [comment]
See Also #25

**Comment by SyntaxC4** [comment]
Related to #24

**Comment by SyntaxC4** [comment]
Just started this article recently.

**Comment by SyntaxC4** [comment]
https://github.com/Azure/azure-webjobs-sdk-script/wiki

**Comment by SyntaxC4** [comment]
@lindydonna Hey could you post the kudu doc link for this?

**Comment by lindydonna** [comment]
@SyntaxC4 I misunderstood earlier and thought we were talking about NPM restore, which you have to do manually with deploy.cmd with Kudu. For NuGet restore, I can write up the text and a writer can decide where to put it.
