### ISSUE TITLE
Incorrect guidance in blob output docs

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#180]
See SO post here: http://stackoverflow.com/questions/42172044/how-to-output-multiple-blobs-from-an-azure-function. Blob binding doesn't support ICollector/IAsyncCollector - only singleton outputs.

Errors are on doc page: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob

**Comment by mathewc** [comment]
We should also remove the section that talks about using ICloudBlobStreamBinder for binding to POCOs. That is a core SDK mechanism, and not really usable in Functions. Proper POCO support for blobs is tracked [here](https://github.com/Azure/azure-webjobs-sdk/issues/995).

**Comment by brettsam** [comment]
Related to #162.

**Comment by lindydonna** [comment]
Removed reference to POCOs and ICloudBlobStreamBinder from blob binding article. See https://github.com/Microsoft/azure-docs-pr/pull/14047
