### ISSUE TITLE
Azure Functions do not properly copy versioned dlls to output directory

### ISSUE THREAD

**Issue by aderderian** [Azure/Azure-Functions#1801]
Can someone explain to me why Azure Functions has issues loading dlls referenced by other projects? I am using an older version of a function in order to support a legacy SDK. I then have created a variety of .NET Standad libraries that are used by this function and also my other .NET Core Apps and Azure Function. 

When the functions load I continually get errors that "Could not load x.z.y.dll of version x.z.y". The dlls from other projects referenced don't get copied in to the bin. I then can't even find nuget packages for the requested versions. Shouldn't this be handled for me? I had to create a hacked together assembly redirect binder, but that is not holding up. 

What is the correct approach here?

Azure Function V1 Runtime - .NET 4.8       (Throws errors on missing dlls from references in Common Lib)
   - References Common Library Project . NET Standard

Common Library . NET Standard

Azure Function V3 .NET Core V3.1
      - References Common Library Project . NET Standard
      
.Net Core Web App
     - References Common Library Project . NET Standard

**Comment by HassanBadir** [comment]
If I understood you correctly, your problem is:

V3 Azure Function (.Net Core) removes runtime dependencies .. so you might want to check that.

a workaround would be to add:
```
<PropertyGroup>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
```

**Comment by v-bbalaiagar** [comment]
Hi @aderderian, Apologies for the delayed response, Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by aderderian** [comment]
Will verify shortly

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
