### ISSUE TITLE
Async method in ServiceBusTrigger azure function taking too long and getting timed out

### ISSUE THREAD

**Issue by absognety** [Azure/Azure-Functions#1804]
We have a service bus trigger azure function, where the utilties functions are written asynchronously for writing information to cosmos (we are upserting metadata to cosmos)

Recently we encountered an issue where this particular activity in data factory is timing out and failing, we have seen application insights and real-time metrics also when this function is running and we didn't get much information from that, just bunch of stacktrace related to worker status initializations and CPU load,

I ran the same function in my local and its getting completed as expected and sometimes it is running fine in ADF also, its non-reproducible. Please let us know if we are missing to enable certain config or any parameter we have to add for async functions so that this issue won't even occur initermittently

**Comment by v-anvari** [comment]
Hi @absognety , Apologies for the delayed response. We understand the errors, let us know if your App is still facing this issue, we need to know the Function App name, time stamp of the error and the invocation id of the error so that we see the backend logs

**Comment by v-anvari** [comment]
Thank you for reaching out to us. Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
