### ISSUE TITLE
Azure function App not displaying the existing storage account in the Azure portal

### ISSUE THREAD

**Issue by sudhirbabu1979** [Azure/Azure-Functions#1806]
Hi ,I created new Azure function with HTTP trigger and trying to store output into BLOB .I already created the storage account with in the same region .unfortunately I am unable to find the existing storage account in the Integration in the [Functions]([url](url)) .please find the screenshot in the attachment for your reference. I saw in one of the microsoft document storage account should be available while creating the function APP but at that time also option is not [available.[](url)](url
[]([]([]([](![Azurestorage_1](https://user-images.githubusercontent.com/46627761/103033613-c0dcc8
![microsoftdocument](https://user-images.githubusercontent.com/46627761/103033702-f8e40b80-455a-11eb-9d1f-a72ad2036bca.png)
80-455a-11eb-95f3-11c072cec909.png)))))
)

**Comment by balag0** [comment]
Is the storage account in the same subscription and region as the function app?

**Comment by sudhirbabu1979** [comment]
Yeah Bala,I created storage account in the same region and storage and function app under the same resource group.
