### ISSUE TITLE
VSCode Azure-Function Extension Javascript httptrigger template have function.json file, but C# doesn't have it.

### ISSUE THREAD

**Issue by shps951023** [Azure/Azure-Functions#1808]
# Javascript httptrigger template have function.json file, but C# doesn't have it.

Javascript Httptrigger project set up with VSCode extension [Azure Functions](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions), contains function.json file, and can be modified to update to azure.   

![](https://i.imgur.com/ilP5EYu.png)

But the C# project doesn't have function.json, and even if you set it up manually, you `can't upload` it to Azure.  

![](https://i.imgur.com/xFJFfvy.png)

**Comment by v-bbalaiagar** [comment]
Hi @shps951023, Please try using the steps [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vscode?view=aspnetcore-5.0#generate-the-deployment-package-locally) to generate a publish file and add function.json, you should be able to deploy a function app to azure. Let us know if you get stuck anywhere.

**Comment by anthonychu** [comment]
@shps951023 For C# apps, you don't need to modify function.json files. If you need to modify any bindings, update the attributes on the function:

```cs
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]
    HttpRequest req, ILogger log)
{
```

When the app is built, it generates the function.json files behind the scenes from those attributes. You normally don't need to know about function.json when writing functions in C#.

**Comment by shps951023** [comment]
> @shps951023 For C# apps, you don't need to modify function.json files. If you need to modify any bindings, update the attributes on the function:
> 
> ```cs
> public static async Task<IActionResult> Run(
>     [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]
>     HttpRequest req, ILogger log)
> {
> ```
> 
> When the app is built, it generates the function.json files behind the scenes from those attributes. You normally don't need to know about function.json when writing functions in C#.

thanks!
