### ISSUE TITLE
Deployment of Azure Function doesn't delete old DLL's (MSDeploy, ZipDeploy)

### ISSUE THREAD

**Issue by HassanBadir** [Azure/Azure-Functions#1817]
Hello,

As part of our migration to **.Net Core Azure Functions**, we moved most of our projects to **.NetStandard**, for some reason when deploying our functions in AzureDevOps .. (With ARM Template) some of the NetStandard DLL's aren't being extracted to the Function file system and we are stuck with the old **.NetFrameWork** DLL's, which casue failures to my functions.

of course, if I delete the old net framework dll, it would copy the new .netstandard dll to the function files and everything work fine, I can't take this as a solution when we want to deploy the change worldwide with many functions versions (i check in kudo).  

we deploy our azure function with **ARM Templates**.

what I have tried so far:

this didn't work, ZipDeploy didn't exactly overwrite everything, old dlls still exist.
1. https://github.com/projectkudu/kudu/wiki/MSDeploy-VS.-ZipDeploy

tried adding this app setting property (bottom of page), also didn't help, deployment works but dlls don't get overwritten
2. https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url

3. I think WEBSITE_RUN_FROM_PACKAGE isn't an option for me, tried also doesn't work since it has problems working with "list-keys", and I get an error like NotFound

these images related to using run_from_package .. 
![image](https://user-images.githubusercontent.com/37299319/104321916-ea02d000-54ec-11eb-9a14-9f2f9dc89ab6.png)

![image](https://user-images.githubusercontent.com/37299319/104321729-ad36d900-54ec-11eb-9dae-8b64b911a53d.png)

also SitePackages are empty:
![image](https://user-images.githubusercontent.com/37299319/104322027-0e5eac80-54ed-11eb-89a1-138f73f31ef9.png)

is there an option to make a clean deploy? which overwrites everything or remove everything? with arm templates?

Thank you.

**Comment by v-anvari** [comment]
Hi @HassanBadir , Please let us know if this is yet to be triaged, so that I can route this issue to concerned team.

**Comment by BadirHassan** [comment]
was fixed thanks.

**Comment by v-anvari** [comment]
Thank you for the confirmation. Closing this issue as resolved

**Comment by jchannon** [comment]
What was the solution, we have spotted something similar

**Comment by HassanBadir** [comment]
This was a multiple issue scenario... some of them weren't related:

1- ZipDeploy with WEBSITE_RUN_FROM_PACKAGE : Solution - (Deploy Twice)

This flag must not be switched On\Off back and forth .. it confuses the system since on first try it looks for a zip where it doesn't exist, but on 2nd time it will work. ( We faced this issue cause our pipieline had multiple version runs and each time me and my colleges ran the pipeline switching On\Off occurred and made it fail ).

2- Listkeys: Solution Dependancy step between function appsettings and zipdeploy 
there were another issue with a race condition, so we had to add a dependancy step between the AppSetting of the function and the zip deploy to be safe .. you can look [here](https://docs.microsoft.com/en-gb/archive/blogs/hosamshobak/arm-template-msdeploy-race-condition-issue)
