### ISSUE TITLE
More reliable deployment

### ISSUE THREAD

**Issue by petro2050** [Azure/Azure-Functions#1818]
I've been using Functions for a while now and I hate the fact that deployment issues make Functions a real pain in the a**. It's not uncommon when a DevOps pipeline successfully deploys changes to an app and the app becomes unresponsive (either with 500 or 503 errors). Sometimes going to the portal and restarting the app works, but other times it does not.

Please provide a better deployment path.

**Comment by balag0** [comment]
Please share the app name.
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by v-anvari** [comment]
Hi @petro2050 , Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue

**Comment by giovannaalves** [comment]
Hi there, I am having the same problem, any deploy turned to return 500 after functions v4 release.
Would somebody help me please?
2021-11-13T02:22:31Z | 3ae916b0-a927-4c82-9bd6-3a8fe0f7cef1| East US 2
