### ISSUE TITLE
Message order and time 

### ISSUE THREAD

**Issue by ddobric** [Azure/Azure-Functions#1822]
I'm not sure if this is the correct repo for this "issue". I have a function which is a long-running one. It takes approx. an hour to complete. When monitoring the function execution in the Log-stream, I notice a very strange order of messages.
First, some messages do not seem to be ordered.
Second, The the representation of the time changes from 24 to 12 after midnight.

![image](https://user-images.githubusercontent.com/1756871/104787577-20ac4500-5790-11eb-86ee-32ce44d4c751.png)

Even more interesting, stream seems to live-stream messages at Jan.15th at the time (see on the bottom right) 00:22 Jan.16th.

![image](https://user-images.githubusercontent.com/1756871/104787806-df686500-5790-11eb-8d99-300c8328b12f.png)

I'm not saying all this is wrong or a big deal. However, it does not appear correct and trying to find some explanation.

### Version
![image](https://user-images.githubusercontent.com/1756871/104787964-54d43580-5791-11eb-813d-d272386ff756.png)

Thanks.

**Comment by ddobric** [comment]
Tried right now
![image](https://user-images.githubusercontent.com/1756871/104815630-05841880-5816-11eb-87ef-d0871d119117.png)

**Comment by balag0** [comment]
The logs are from 
D:\home\LogFiles\Application\Functions\function\[FunctionName]\\[LogFIleName].log

May be browsing the contents of those files using kudu console will help answer some of these questions.

**Comment by ddobric** [comment]
Thanks @balag0 . This is exactly how I do it. However, my intension here is not a workaround. We expect that logging and insights, which are great Azure features, work always a reliable way. Means, the expectation is high quality.
Purpose of dashboards is to help and to confuse us.
Anyway, AzureFunctions is a really high-quality service and I guess this is a temporary issue.
