### ISSUE TITLE
Which Always-On Documentation Is Correct

### ISSUE THREAD

**Issue by hrafnkel** [Azure/Azure-Functions#1823]
Please describe the documentation request or issue.  Be as specific as possible.

 This URL https://github.com/Azure/Azure-Functions/wiki/Enable-Always-On-when-running-on-dedicated-App-Service-Plan says on Premium then Alwas-On should be off/false/disabled.

My Azure Portal says as follows.
" We detected that your function app is running on App Service Plan (PremiumV2). Please make sure you have enabled the Always on setting so that your function app runs correctly. "

I'm having problems with Function Apps not automatically starting and it's problematic when you see conflicting advice. This is a live production issue impacting my employer. 

In addition the ticket submission in the DevOps portal never reaches a state where a new ticket can be raised so I have come here for help.

**Comment by balag0** [comment]
I think (understandably) there is some confusion between PremiumV2 and Premium. The sku for the premium plan (where Always On should be off) is ElasticPremium or EP(1-3)
https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#available-instance-skus

PremiumV2 (P1V1-3) sku is still considered running on an app service plan and so always on should be on. Hope this clarifies things.

**Comment by hrafnkel** [comment]
@balag0 Thank you. I am accepting your answer and closing this issue. 

I think the documentation is vague and needs updating.
