### ISSUE TITLE
Unreachable functions runtime

### ISSUE THREAD

**Issue by ddobric** [Azure/Azure-Functions#1824]
When I deploy the function that is correctly running, I have noticed from time to time that the runtime is not reachable.

![image](https://user-images.githubusercontent.com/1756871/105323300-42f7f580-5bca-11eb-9001-c45fc4222c72.png)

As you see the function is running. It is correctly triggered, writes correctly to logs etc.

![image](https://user-images.githubusercontent.com/1756871/105323221-2bb90800-5bca-11eb-9100-dea1dab160d4.png)

I cannot say this happens very often, but I see this for a very long time and it should never happen.

To work around this issue, I go to configuration, change some setting and save it to enforce the restart of the whole application. Sometimes this helps.

Moreover, in this case, the portal does not show some functions (indeterministic), but functions are running. Following picture shows a single function in the portal. Kudu shows two functions. Both are running.

![image](https://user-images.githubusercontent.com/1756871/105370346-ca158f80-5c03-11eb-92e2-d9bfdfccfa47.png)

**Comment by balag0** [comment]
Looking at the health of this app (what I think), I see a large number exceptions related to

System.NotSupportedException : Unsupported parser.
System.InvalidOperationException : Unable to load metadata for function
System.InvalidOperationException : %% does not resolve to a value.

I have not pasted the complete exceptions here but you should be able to see the details in AppInsights. Exceptions like these can impact the availability of the app leading to the unreachable status as reported on the portal.

**Comment by ddobric** [comment]
@balag0 that might be some possibility to solve that kind of issue. In fact, this is exactly what we do. We start looking for any reasonable information. This is not the first time we see such an error message. Unfortunately, in the end, we delete the app, create the new one and it works. Or we are digging in some logs etc.
My suggestion is to make that kind of error more understandable. If the system says "runtime not available" I do not think the application should be the problem. The fair solution would be to tell us what the problem is. 
If the health knows what the problem is, why not put that knowledge in the error box above instead of "runtime not available"?

People who deploy the application, think and should think in their business context and not in the runtime context. This is why we find Azure Functions great and want to make it even better.

None of the listed exceptions above is business-related. When we deploy the function we do not use any parser (it is and it should remain transparent for us). The same comment is related to "loading of metadata" and '%%'.

I do no expect anybody is able to tell me what the issue here really is. I'm happy to close the issue if we agree that the error above is not helpful and will be improved.

**Comment by balag0** [comment]
Thanks for the feedback. I agree this is a reasonable ask and the below issue is tracking some of these improvements and should make debugging easier - https://github.com/Azure/azure-functions-host/issues/6536
