### ISSUE TITLE
VS Debugger does not work with windows docker containers

### ISSUE THREAD

**Issue by DrEight** [Azure/Azure-Functions#1825]
If I try to attach the debugger to a windows docker container, the debugger fails to attach.
I notice that even if the tag <DockerDefaultTargetOS> is set to 'Windows', VS still consider the Linux environment. (see the debugger path below)

This is the command spawn by Visual Studio :
docker run -dt -v "C:\Users\[my user]\onecoremsvsmon\16.8.0713.0:C:\remote_debugger:ro" -v "[my project path]:c:/home/site/wwwroot" -v "[my project source]:c:\src" -v "C:\Users\[my user]\AppData\Local\AzureFunctionsTools\Containers_2109029\Releases\3.18.0\ **linuxCLI** :C:\functions_debugging_cli:ro" -v "C:\Users\[my user]\.nuget\packages\:c:\.nuget\fallbackpackages" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" -e "NUGET_PACKAGES=c:\.nuget\fallbackpackages" -e "NUGET_FALLBACK_PACKAGES=c:\.nuget\fallbackpackages" -p 31061:31061 --name [my project] --entrypoint C:\remote_debugger\x64\msvsmon.exe [my image]:dev /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646 /LogDebuggeeOutputToStdOut

for the moment I found a workaround, forcing an additional volume in docker and a different debugger path:
< DockerfileRunArguments >-v "C:\Users\[my user]\AppData\Local\AzureFunctionsTools\Releases\3.18.0\cli_x64:C:\functions_debugging:ro"< /DockerfileRunArguments >
    < DockerDebuggeeProgram >C:\functions_debugging\func.exe< /DockerDebuggeeProgram >

did I made something wrong or is it a bug?

**Comment by balag0** [comment]
How are you building the Windows functions container? I believe we only publish Linux debian based images currently.

**Comment by DrEight** [comment]
@balag0  in VS if you right-click on the project and select 'Add Docker Support' a dockerfile is created.
MS does have a windows function container: mcr.microsoft.com/azure-functions/dotnet:3.0-nanoserver-1809

**Comment by moodmosaic** [comment]
>for the moment I found a workaround, forcing an additional volume in docker and a different debugger path

I'm more or less in the same situation as @DrEight. Would be nice to know if this is a bug.

**Comment by balag0** [comment]
I see. 
+ @vijayrkn Would you know if VS supports debugging Windows containers?

**Comment by vijayrkn** [comment]
Adding @NCarlsonMSFT who might know if this is supported.

**Comment by NCarlsonMSFT** [comment]
@vijayrkn My recollection is that when I added support for functions in containers support for windows was blocked by: https://github.com/Azure/azure-functions-core-tools/issues/1396

@DrEight Are the VS tools letting you add container support to a functions project as a windows container, or are you altering it to be a windows image and then it fails? Also is your issue happening on Launch (F5) or Attach? You say attach, but the commands you reference would be for a Launch (where only Linux is supported).
 If you have a running windows container for your Azure Function you should be able to attach to the running process from within VS:  https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-process-running-in-docker-container?view=vs-2019#attach-to-a-process-running-on-a-windows-docker-container

**Comment by DrEight** [comment]
@NCarlsonMSFT VS add the right image to the dockerfile I didn't alter the file. 
As I wrote, the bug is VS that tries to push the wrong debugger inside the container. If you see the docker command above, the Linux debugger is injected into the container. I forced to inject the windows debugger and then everything works.
IMO the problem is that VS does not correctly detect the container OS even if it is specified in the project file.

**Comment by NCarlsonMSFT** [comment]
@DrEight I'm still not sure I understand your repro steps.
My attempted repro:
- Change my Docker Dameon to windows
- Create an Azure Functions Project (I choose v3, Blob)
- Right Click->Add->Docker Support
I immediately get the message:
![Your Docker server host is configured for 'Windows', however your project targets 'Linux'. Would you like to switch Docker to Linux containers now?](https://user-images.githubusercontent.com/14239288/106177726-b7441300-614d-11eb-96b3-3458e274a7ed.png)
- I clicked No and then F5ed anyway and got the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CTC1005	Your Docker server host is configured for 'Windows', however your project targets 'Linux'.	FunctionApp3	C:\Users\ncarlson\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.10.9\build\Container.targets	198	

This is the expected behavior, as currently only Linux is supported for Azure Functions so the scaffolding is targeting Linux.
How did you get your project into a state where it was attempting to run on windows?

**Comment by v-bbalaiagar** [comment]
Hi @DrEight, Can you please provide the above requested details.

**Comment by DrEight** [comment]
Sorry if I did not provide additional details. I solved the problem by not using the Linux image.
You can close the ticket.

**Comment by v-bbalaiagar** [comment]
Hi @DrEight, Thank you for the confirmation, Closing this issue as resolved, please feel free to reach back to us in case of any further queries related to this issue.

**Comment by DrEight** [comment]
> Hi @DrEight, how were you able to resolve this? I am trying to use windows image to run functions. It works fine in VS but when I package them in a docker image, all I get on accessing my functions is "function host is not running." Would be really helpful if you could share the dockerfile that worked for you.

I can not share my dockerfile because it has a lot of unrelated stuffs, but if I simplify it it would look something like this:

FROM mcr.microsoft.com/azure-functions/dotnet:3.0 AS base
WORKDIR /home/site/wwwroot
#COPY ./bin/x64/Debug/netcoreapp3.1 .
COPY ./bin/x64/Release/netcoreapp3.1 .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

**Comment by abhinav12** [comment]
Ohh that wont work for me, I thought you had solved the issue with the mcr.microsoft.com/azure-functions/dotnet:3.0-nanoserver-1809 image. Thanks anyway.
