### ISSUE TITLE
Dependency registration model during startup in Azure Function App

### ISSUE THREAD

**Issue by adrianbontea** [Azure/Azure-Functions#1826]
We used to use the following approach across multiple Function Apps for dependency registration during startup:

```
public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var config = GetConfiguration(builder);
            builder.Services.AddScoped<IX, X>(provider =>
                new X(config.GetConnectionString("blabla")));
        }

        private IConfigurationRoot GetConfiguration(IFunctionsHostBuilder builder)
        {
            var descriptor = builder.Services.FirstOrDefault(d => d.ServiceType == typeof(IConfiguration));
            return (IConfigurationRoot)descriptor?.ImplementationInstance;
        }

    }

```

This used to work fine until around **January 14th** when all function apps using this approach started to break with `NullReferenceExceptions` in Azure.

We realized that the `IConfiguration` object resolved during startup was null later at runtime during the execution of implementation factory for dependency `IX/X` so we changed to a better approach:
```

public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
             builder.Services.AddScoped<IX, X>(provider =>
            {
                var config = provider.GetService<IConfiguration>();
                var connectionString = config.GetConnectionString("blabla");
                return new X(connectionString );
            });
        }

    }

```

**Question Is**

How come the original approach (although obviously less than optimal) used to work and it stopped working around **January 14th**? Is there any official documentation about this?

**Comment by v-anvari** [comment]
Hi @adrianbontea , Kindly let us know if you are still seeing this scenario, so that we can look into it further
