### ISSUE TITLE
[Premium] Unable to deploy Azure Functions Premium plan in Python Runtime in West India

### ISSUE THREAD

**Issue by sanghvi-yash** [Azure/Azure-Functions#1828]
**Describe the bug**
As per https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#region-max-scale-out, the Premium plan is supported in West India. Since Python runtime is supported in Linux, it is expected that I should be able to deploy Python runtime functions under the Premium plan in West India. However, on deploying either through VSCode or through the Azure portal, I get the following error message: Requested features are not supported in region.

**To Reproduce**
1. Create a new Resource Group in West India
2. Click on 'Add' to create a new function app
3. Name your function. Select Python 3.8 as the Runtime Version, and 'West India' as the region. 
4. In the Hosting Tab, create a new Storage Account, and select Premium as the Plan type. Let a new linux plan be created.
5. Skip monitoring, or choose Central India as the region fornew Application Insights (not supported in West India)
6. Click on Create in Review+Create

**Expected behavior**
A new Function app (premium plan) should be created in the selected resource group in West India

**Screenshots**
![Screenshot (380)](https://user-images.githubusercontent.com/50194122/105970359-49e1a500-60af-11eb-8f89-a831370cba80.png)

**Additional context**
-

**Comment by balag0** [comment]
Thanks for reporting this. We are looking into this and I will post an update soon.

**Comment by sanghvi-yash** [comment]
Thanks for your reply. Will wait for your update.

**Comment by cachai2** [comment]
The issue should be fixed, and you should be able to deploy Azure Functions Premium plan in Python Runtime in West India now. Thanks again for reporting this.

**Comment by sanghvi-yash** [comment]
It is working now. Thank you for resolving the issue.
