### ISSUE TITLE
Azure timer function running under consumption plan stops after a random period of time?

### ISSUE THREAD

**Issue by sonic1981** [Azure/Azure-Functions#1829]
I have the following Azure function:

```c#
 public class Schedule
    {
        private readonly ILogger<Schedule> logger;
        private readonly IScheduleMediator scheduleMediator;
        

        public Schedule(ILogger<Schedule> logger, IScheduleMediator scheduleMediator)
        {
            this.logger = logger;
            this.scheduleMediator = scheduleMediator;
        }

        [FunctionName("RunSchedule")]
        public async Task RunSchedule(
            [TimerTrigger("0-59 * * * *")] TimerInfo myTimer)
        {
            logger.LogInformation($"Runing schedule triggered by timer function: Last: {myTimer.ScheduleStatus.Last} Next: {myTimer.ScheduleStatus.Next} LastUpdated:  {myTimer.ScheduleStatus.Next}");

            await this.scheduleMediator.DeQueueRequests();
        }

        
    }
```

I'm expecting this to run continually every minute until stopped. This function seems to run for a random period of time and then just stop processing:

![image](https://user-images.githubusercontent.com/1443217/106013100-0c334b00-60b4-11eb-8cee-4c971e43625c.png)

This issue seems very similar to this one https://github.com/Azure/azure-functions-host/issues/1160 and others I've found on GIT hub. I know there is an issue with a mixed [timer and HTTP function](https://github.com/Azure/azure-functions-host/issues/1160#issuecomment-284949362) but this function is just a timer. I don't have any custom timezone, etc set. 

I've looked though https://github.com/Azure/azure-functions-host/wiki/Investigating-and-reporting-issues-with-timer-triggered-functions-not-firing and I cant see any issues?

[As per](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) the function information is:

```
Executing 'RunSchedule' (Reason='Timer fired at 2021-01-27T15:38:00.0101996+00:00', Id=84b2f217-2bf8-4177-9b88-1670ea52d6ee)
```

**Comment by sonic1981** [comment]
The function is deployed vs if that helps:

```
az functionapp deployment source config-zip --src file.zip -n functioname --resource-group RG
```

**Comment by sonic1981** [comment]
If I refresh the app I get the following messages:

```
Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2021-01-27T15:39:00.0000000+00:00
```

and I can see my logging from above as:

```
Runing schedule triggered by timer function: Last: 1/27/2021 3:38:00 PM Next: 1/27/2021 3:39:00 PM LastUpdated: 1/27/2021 3:39:00 PM
```

so the next execution time is getting set, but it's just not running...

**Comment by sonic1981** [comment]
I've just noticed this on the last failure:

```
2021-01-27 16:13:00.008
Runing schedule triggered by timer function: Last: 1/27/2021 4:12:00 PM Next: 1/27/2021 4:13:00 PM LastUpdated: 1/27/2021 4:13:00 PM
```

so the Next time is already in the past, I wonder if this is the problem. I've increased the cron to every second minute to see if this fixes the problem

**Comment by sonic1981** [comment]
I managed to get this working by switching my cron pattern from `"0-59 * * * *"` to `"0 */2 * * * *"`. I based this on the information from this site https://arminreiter.com/2017/02/azure-functions-time-trigger-cron-cheat-sheet/ specifically:

> The following values are good if you want a regular frequency:

> - for minutes and seconds: /2, /3, /4, /5, /6, /10, /12, /15, /20 and /30 (60 is divisible by these numbers)
> - for hours: /2, /3, /4, /6, /8 and /12
> - for months: /2, /3, /4 and /6
> - for days: nothing, because there are leap years and months with 28, 29, 30 or 31 days.

Can someone explain why my first cron pattern caused a crash? Also it would of been nice to get some kind of error message from this not just a silent freeze

**Comment by v-anvari** [comment]
Hi @sonic1981 , We need to further investigate the logs of your function App to understand the error. My guess is that since you are specifying 0-59 which means "At every minute from 0 through 59" ie; 00:00:00, 00:00:01.....00:00:59, 00:00:00 and */1 means "At every minute". You can find the calculation metrics in [Crontab guru](https://crontab.guru/#0-59_*_*_*_*).

Let us know if this helps. Please provide us the function App name and timestamp of the error for us to investigate further

**Comment by sonic1981** [comment]
Hi @v-anvari 

Yes I know it was because the cron was set to run every minute, what I'm getting at is that I wouldn't expect this to just fail after a period of time. It seems perfectly legitimate to want to run this every minute and I can't see anything in the documentation that states this isn't possible. It also produces no errors and just stops working, which, again, I would state is a bug. I'd expect an error message at least?

I have already provided information on the Id and timestamp in my original question. To repeat that:
> executing 'RunSchedule' (Reason='Timer fired at 2021-01-27T15:38:00.0101996+00:00', Id=84b2f217-2bf8-4177-9b88-1670ea52d6ee)

**Comment by anthonychu** [comment]
It’s likely that you had problems with the initial cron expression because Azure Functions expects a “seconds” value in the expression. In other words, your cron expression should contain 6 segments, not 5.

However we have identified that the format without seconds works in some situations and not others. This has caused some issues and we will work to address them. This appears identical to this issue here: https://github.com/Azure/azure-functions-host/issues/7100

**Comment by mookid8000** [comment]
@sonic1981 If you're using NUnit, then maybe you can benefit from having this test case around:
```csharp
  [TestFixture]
    [Description(@"Verifies that all of the used CRON expressions can be validated using the variation that Azure uses.

As per https://github.com/Azure/azure-functions-host/issues/7100 it can be seen that Azure uses NCronTab (with seconds enabled) to parse the expressions, and so that is what we do here too.
")]
    public class CheckCronExpressions
    {
        [TestCaseSource(nameof(GetCronExpressions))]
        public void CheckExpression(CronExpression expression)
        {
            Console.WriteLine($"EXPRESSION: {expression}");

            var options = new CrontabSchedule.ParseOptions { IncludingSeconds = true };
            var crontabSchedule = CrontabSchedule.Parse(expression.Expression, options);

            Console.WriteLine(crontabSchedule);
        }

        static IEnumerable<CronExpression> GetCronExpressions()
        {
            return typeof(Startup).Assembly.GetTypes()
                .SelectMany(type => type.GetMethods())
                .Where(method => method.GetCustomAttributes(typeof(FunctionNameAttribute), inherit: true).Any())
                .Select(method => new CronExpression(method, method.GetParameters().Select(p => p.GetCustomAttribute<TimerTriggerAttribute>()?.ScheduleExpression).FirstOrDefault(expression => expression != null)))
                .Where(e => e.Expression != null);
        }

        public class CronExpression
        {
            public MethodInfo Method { get; }
            public string Expression { get; }

            public CronExpression(MethodInfo method, string expression)
            {
                Method = method;
                Expression = expression;
            }

            public override string ToString() => $"{Method.DeclaringType?.Name}.{Method.Name}: {Expression}";
        }
    }
```

It uses the cron expression parser used by Azure Functions ([ncrontab](https://www.nuget.org/packages/ncrontab/)) to parse all of the used cron expressions, giving you errors if they fail.

The thing that tricked me was that I could run my functions locally, and seemingly also in Azure for a while, with a cron expressions _without a seconds component_. The cron parser in the test has `new CrontabSchedule.ParseOptions { IncludingSeconds = true }`, which then causes the parser to fail on expressions that lack the seconds component.

**Comment by sonic1981** [comment]
Thanks for getting back to me @anthonychu . With regards to:

> This has caused some issues and we will work to address them

Is there anything tracking this work that I can follow? TBH my main motivation with this issue is to prevent someone else throwing loads of time on this like I did only to find that it's the cron that's wrong. I still feel like this should of produced some kind of error... From my perspective it was very difficult to track down the issue

**Comment by sonic1981** [comment]
I'll close this in lieu of the linked issue
