### ISSUE TITLE
Support debugging F# Functions in Visual Studio

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#183]
_From @davidtme on February 16, 2017 13:11_

I have a blank c# function which works:

```C#
using System;

public static void Run(string input)
{
}
```

Which runs and I can debug:

![image](https://cloud.githubusercontent.com/assets/1804141/23022484/fe96b490-f448-11e6-9922-e70b0d50ed0c.png)

If I change it to an F# file:

```F#
open System

let Run(input: string) =
    ignore()
```

it runs but I get an error meaning I can't debug:

![image](https://cloud.githubusercontent.com/assets/1804141/23022530/39f16d8c-f449-11e6-8e54-f57d03e29d9f.png)

_Copied from original issue: Azure/azure-functions-cli#73_

**Comment by lindydonna** [comment]
@davidtme I've moved to this repo since it's a Visual Studio feature request.

**Comment by ColbyTresness** [comment]
We don't plan to do this as far as I know. Reopen if necessary.
