### ISSUE TITLE
Azure Queue and Trigger. 

### ISSUE THREAD

**Issue by klogan12** [Azure/Azure-Functions#1830]
I have Azure Queue and couple of queue triggers registered
What is the best way to find which queue triggers dequeued the message. Ideally how to find who dequed the message from queue. It could be an user or process.

**Comment by v-anvari** [comment]
Hi @klogan12 , The de-queued messages are sent to [poison queue](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=csharp#poison-messages) after certain retries which can be handled in different methods
[https://docs.microsoft.com/en-us/previous-versions/windows/handling-poison-messages](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms703179(v=vs.85)#handling-poison-messages-1).

You can trace the de-queued messages with its unique id in the errors and exceptions of the application insights.
[https://docs.microsoft.com/diagnosing-exceptions-using-visual-studio/ Portal](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions#diagnosing-exceptions-using-visual-studio)

If you want to additionally trace the messages in the poison queue, you can plug a function into your poison queue which can actually inspect and log information about the messages. As the messages going into poison queue is not lost, its a great way to analyze the reason behind the de-queued messages
[Example: Dealing-With-Unprocessed-Storage-Queue-Poison-Messages](http://dontcodetired.com/blog/post/Dealing-With-Unprocessed-Storage-Queue-Poison-Messages-in-Azure-Functions)

**Comment by v-anvari** [comment]
Closing this issue, please feel free to re-open it in case of any query regarding this issue
