### ISSUE TITLE
I could not create a valid HDF5 file in data lake  in Azure Function

### ISSUE THREAD

**Issue by dianweih73** [Azure/Azure-Functions#1838]
Hi Azure Function team,

I was blocked by this issue for a while. In Azure Function (main), I can create a hdf5 file. Created a memory block  via file-like object  and then create a new file in data lake. But the file is empty. I need your help on it. Here I just put some of code snippet. 

    bio = BytesIO()
    with h5py.File(bio, 'w') as f:
   
        sub_group = f.create_group('series')
        sub_group_df = sub_group.create_dataset('data', data = '1021')
        bio.seek(0)

        try:
          storage_account_name = 'myaccount'
          storage_account_key = 'myacount_key'
          #Create instance of Data Lake Service Client
          service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format("https", storage_account_name), credential=storage_account_key)

          # ADLS Container (this is currently hard-coded for the test) 
          file_system_client = service_client.get_file_system_client(file_system="sandbucket")

          # ADLS Directory path (this is currently hard-coded for the test) 
          directory_client = file_system_client.get_directory_client("debug")
        
          file_client = directory_client.create_file('new.hdf5')
        
          # write test file hdf5 to ADLS
          file_client.append_data(data=f, offset =0, length = len(f))
        
          file_client.flush_data(len(f))
        
          f.close()
          bio.close()
         
        except Exception as e:
          print(e)

**Comment by v-bbalaiagar** [comment]
Hi @dianweih73 , Let us know if you are able to find a solution here [https://docs.microsoft.com/en-us/answers/topics/azure-data-lake-storage.html](https://docs.microsoft.com/en-us/answers/topics/azure-data-lake-storage.html) The right place to find a solution to this would be the forum.
Please feel free to reach back to us in case of any further queries regarding this issue
