### ISSUE TITLE
Which repo contains code for ASP.NET Core to run user-uploaded CScript files, like Azure Functions?

### ISSUE THREAD

**Issue by ExperimentsAndIdeas** [Azure/Azure-Functions#1839]
I'm looking to take Azure Function code I publish into azure and run it locally or in a seperate cloud. 

The minimum I need to do is run the Function code, minus the GUI (though it would be nice), and run it in anything from ASP.NET Core or a xross platform application / console.

Which repo or subdirectory should I look at for this parallel execution (which may or may not include CPU, disk, and network throttling/capping features)

Related or similar enabling technologies I'm looking at include: Quartz.Net, Background Tasks, and MicroServices IHostedService

**Comment by v-anvari** [comment]
Hi @ExperimentsAndIdeas , You can go through the below, let us know if they help
ASP.NET core repo : [https://github.com/dotnet/aspnetcore](https://github.com/dotnet/aspnetcore)
ASP.NET core Doc : [https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-5.0](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-5.0)

Related information: [serverless platform-for-all-developers](https://azure.microsoft.com/en-us/blog/serverless-for-all-developers-bringing-azure-functions-to-linux-mac-planet-scale-nosql-real-time-analytics-and-productivity-apps/)

Background tasks with hosted services: [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio)
Repo for SDK - [https://github.com/Azure/azure-webjobs-sdk/wiki](https://github.com/Azure/azure-webjobs-sdk/wiki)
