### ISSUE TITLE
[Premium] Scale in/out operations details not captured in the Activity Log

### ISSUE THREAD

**Issue by maximivanov** [Azure/Azure-Functions#1841]
**Describe the bug**
Whenever I change scaling options in the Scale Out blade of a Function App, corresponding Activity Logs do not have details of the operation performed. It's good to know someone did the update but without knowing what the update was the logs are not very useful.

**To Reproduce**
1. Go to a Function App (Linux EP1 hosting plan in my case) in the Portal
2. Go to the Scale Out blade.
3. Change Maximum Burst value from 1 to 2
4. Change Always Ready instances value from 1 to 2
5. Save settings
6. After a few minutes "Update web sites config" entries appear in the Activity Logs.
7. While inspecting JSON I couldn't find anything related to the config options I changed.

**Expected behavior**
I can see what was changed in the config. E.g. Max Burst: 1 => 2; Always Ready: 1 => 2

**Additional context**
Activity logs for scale in operations do not have specifics either.

**Comment by v-anvari** [comment]
Hi @maximivanov , I have tried to reproduce the scenario, and whenever I make any changes in the scale out configuration, there are two activity logs that get created.

**Operation name:**
'auditIfNotExists' Policy action.
Update web sites config

The details of the changes made are mentioned in the 'auditIfNotExists' Policy action, in the change history like the below:

![image](https://user-images.githubusercontent.com/66122429/121899568-2b203a00-cd42-11eb-807a-426d06eb6ad3.png)


I have tested by changing the numbers again, and I see that the numbers have been changed in the policy action successfully. 

![image](https://user-images.githubusercontent.com/66122429/121917445-c1f4f280-cd52-11eb-88e6-a44b2441d382.png)


Closing this issue as the query is resolved.
