### ISSUE TITLE
[Premium] Minimum Instances scale in delay

### ISSUE THREAD

**Issue by maximivanov** [Azure/Azure-Functions#1842]
**Describe the bug**
After manually decreasing the number of Always Ready instances to the minimum, Minimum Instances follow the scale in after a significant delay incurring extra costs of running unused premium instances.

**To Reproduce**
1. In a Function App hosted in a Linux EP1 plan, increase both Maximum Burst and Always Ready instances from 1 to 2. Observe Minimum Instances value (not editable in the portal) changes to 2.
2. After some time (10 minutes) decrease the Always Ready value back to 1. Observe Minimum Instances stays at 2
3. Wait for 1 hour
4. Minimum Instances is still 2

**Expected behavior**
Minimum Instances scale-in follows Always Ready decrease in a reasonable time (minutes).

**Additional context**
I confirmed this behavior multiple times under different accounts. I filed a support ticket with this problem and the response was that Minimum Instances change should be immediate - from which I conclude what I'm seeing is a bug.
Right now I'm seeing this in my personal account. App Plan has only 1 function app in it. The FA has 0 traffic. It's been roughly 1h:30 since I reset Always Ready count to 1. 
In the past I've seen Minimum Instances took more than 24 hours to scale in. It's hard to tell how much time it takes exactly since there's no entry in the Activity Log for this event.

**Comment by qcnguyen** [comment]
I also encounter this problem as well, happen for windows plan EP1

**Comment by v-anvari** [comment]
Hi @maximivanov , When I try to decrease the Max burst, I get the following warning, where I cannot reduce the Max burst 

![image](https://user-images.githubusercontent.com/66122429/121918196-7262f680-cd53-11eb-924c-f979be95e5f1.png)

When I reduce the burst further and click refresh, the value of minimum instances change to 1. 

![image](https://user-images.githubusercontent.com/66122429/121918420-a63e1c00-cd53-11eb-89ec-ad52b1cc3f81.png)


Closing this issue as the functionality is working as expected
