### ISSUE TITLE
Is there, and if so what is, the maximum number of functions I can create/host in a Function App?

### ISSUE THREAD

**Issue by NickSevens** [Azure/Azure-Functions#1848]
I'm working on an application heavily relying on using Durable Functions.

The number of (sub-)orchestrations and activities is increasing rapidly; so we were wondering if there was a limit on how many Azure Functions can be deployed on a single Function App.

We couldn't find any limitation in the docs, so I was wondering _if_ it is documented, and if so, where - if such a limit applies at all?

**Comment by v-anvari** [comment]
Hi @NickSevens , There is certainly a limit but is not specified by a maximum number, you will get an error like : "Maximun number of functions ({0}) exceeded. Ignoring function.....". The limit depends on the usage of each individual function. 
Here is the information of the limit implementation [Implementing a simple check to limit the maximum number of functions loaded](https://github.com/Azure/azure-functions-host/pull/177). 

However, it is not suggested to load the Function App, as if one function is the cause of the failure, then it will impact others as well. You, may please go through the [best practices](https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices) to know what works for you better.
