### ISSUE TITLE
Network access restrictions 'Name' field 

### ISSUE THREAD

**Issue by vipulkelkar** [Azure/Azure-Functions#1852]
To configure a network access restriction in Azure Function app/Web app, Rule 'Name' is not a required field. However, to [remove an access restriction using the CLI](https://docs.microsoft.com/en-us/cli/azure/webapp/config/access-restriction?view=azure-cli-latest#az_webapp_config_access_restriction_show), the Name is required. 'Name', in my opinion must be a required field to configure a rule and also enforce uniqueness.

![image](https://user-images.githubusercontent.com/13727430/109112400-9973c900-7760-11eb-9d75-d2011307dea6.png)

![image](https://user-images.githubusercontent.com/13727430/109112815-3df60b00-7761-11eb-9f1d-6ec5eb29bfba.png)

The rule isn't assigned a name internally either. On fetching the [rule details using azure cli](https://docs.microsoft.com/en-us/cli/azure/webapp/config/access-restriction?view=azure-cli-latest#az_webapp_config_access_restriction_show)

![image](https://user-images.githubusercontent.com/13727430/109113427-413dc680-7762-11eb-9f27-8626bf40b002.png)

**Error in CLI while trying to remove a rule using VNET name. Rule name is a required field.**

![image](https://user-images.githubusercontent.com/13727430/109112746-2028a600-7761-11eb-9957-e109dde6edb5.png)

**Duplicate rule names** 

![image](https://user-images.githubusercontent.com/13727430/109113165-cecce680-7761-11eb-989e-291c0803e3d5.png)

**Comment by madsd** [comment]
@vipulkelkar --rule-name is not required. But --name|-n is. The name is referring to the web app name. It is more likely that you have a syntax error. Can you post the exact command that you run to produce this error?

**Comment by vipulkelkar** [comment]
@madsd Yes, I did provide the Resource group name and App name. However, for a rule configured like below, trying to remove it using IP address doesn't work and the CLI recommends to use the command with --rule-name. Not sure if I am missing anything ?

![image](https://user-images.githubusercontent.com/13727430/109293923-7aedfa80-7852-11eb-9321-0c19ce1b7a77.png)


_TRY THIS:
az webapp config access-restriction remove --resource-group ResourceGroup --name AppName --rule-name developers
Remove Access Restriction named developers from the main site.

az webapp config access-restriction remove --resource-group ResourceGroup --name AppName --rule-name internal_agents --scm-site true
Remove Access Restriction named internal_agents from the scm site._

**Comment by madsd** [comment]
@vipulkelkar to remove that, you just do:
az webapp config access-restriction remove --resource-group ResourceGroup --name AppName --ip-address 1.2.3.4/32

**Comment by vipulkelkar** [comment]
@madsd right, I had tried that earlier and figured out an issue in my pipeline input. Works with the IP now thanks :) I will try the Vnet approach in a similar way

**Comment by v-anvari** [comment]
Thank you for the information Mads, Closing this issue as resolved

**Comment by madsd** [comment]
No problem - glad I could help :-)
