### ISSUE TITLE
CosmosDB Scale Controller/App Settings Mismatch

### ISSUE THREAD

**Issue by cachai2** [Azure/Azure-Functions#1857]
Customers are using the Cosmos connection string in ConnectionStrings which works fine with the Functions runtime. However, Scale Controller appears to only check App Settings, so function apps keep falling asleep after scaling in. This is a mismatch between the runtime and Scale Controller similar to what happened with the Timer trigger and should be investigated/fixed.

**Comment by apawast** [comment]
@cachai2 can you check if this is resolved?

**Comment by cachai2** [comment]
Pragna's team has it as planned work.

**Comment by cachai2** [comment]
Vincent investigated. Related issue: https://github.com/Azure/Azure-Functions/issues/1862
