### ISSUE TITLE
Using Managed/User Identity to authenticate to function app.

### ISSUE THREAD

**Issue by klogan12** [Azure/Azure-Functions#1859]
I know Azure function allows Azure AD authentication. Want to see if there is a way for Using Managed/User Identity to authenticate to function app.

The  application running inside azure VM should be able to authenticate to Azure function app API using managed identity - This is my requirment,

**Comment by Arash-Sabet** [comment]
@klogan12 Does [this article](https://www.sabet.dev/posts/securing-daemon-apps-azure-ad-b2c/) help?

**Comment by v-anvari** [comment]
Hi @klogan12 , please let us know if you are still finding a solution

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
