### ISSUE TITLE
Link to Azure Functions Proxies repository

### ISSUE THREAD

**Issue by mikezks** [Azure/Azure-Functions#186]
Could you please add the link to the Azure Functions Proxies repository if it is already available as OSS?
Thanks!

**Comment by yochay** [comment]
@mikezks  the proxies run-time are internal implementation of Azure App Service (the engine for Azure Functions) and therefore no available as a public repo.

**Comment by mikezks** [comment]
@yochay I see, thanks for clarification.
The issue can be closed.
