### ISSUE TITLE
"Operation_Name" pulling proxy name instead of function name - breaking Invocation Traces view

### ISSUE THREAD

**Issue by ReisHRedeploy** [Azure/Azure-Functions#1861]
Issue: 
'Invocation Traces' on a function used to utilise the function name for "operation_name" instead of the proxy name. For our function app (v2) this appears to have changed on February 18th so instead of the function name it now utilises the proxy name as the "operation_name". This means that the invocations on the function app are no longer showing.

Detailed:
We have a function app that makes use of proxies for friendly naming and providing request overrides. Until February 18th I could see all the invocations for the function app regardless of what proxy was calling it:

![image](https://user-images.githubusercontent.com/69844351/110455693-083e1400-80c9-11eb-8fcc-4b7bfe03c593.png)

The invocation view utilises the following application insights code to generate it:

![working](https://user-images.githubusercontent.com/69844351/110457739-3fadc000-80cb-11eb-804a-5fa628b01d12.jpg)

The application insights code uses the function name as the "operation_name" and was working perfectly as expected, until the 18th February, with our proxies setup.  As you can see in the above screenshot, it appears that the invocations stopped on February 18th but if I remove the "operation_name=" filter and run again I can see that it is working as expected but instead started pulling in the proxy name as the "operation_name" which caused the invocation list on the function app monitor to break:

![notworking](https://user-images.githubusercontent.com/69844351/110458267-dbd7c700-80cb-11eb-8132-fedb9ac538e2.jpg)

Is there any way I can revert this behaviour or have the operation_name appear as the function that is running instead of the proxy name?

**Comment by ReisHRedeploy** [comment]
> 
> 
> @ReisHRedeploy - Please let us know which HostVersion your function app is running.

Thanks, where do I find that to verify? I can't find a "HostVersion" on the environment settings of the web app. If it's the "FUNCTIONS_EXTENSION_VERSION" you're referencing then that is set to ~2

**Comment by pragnagopa** [comment]
This could be related to Functions V2 apps auto-upgraded to Functions V3 - please see https://github.com/Azure/app-service-announcements/issues/266 for more details.  To confirm the issue - please try pinning to Functions V2 by updating `FUNCTIONS_EXTENSION_VERSION` to  **`~2.0`**

**Comment by ReisHRedeploy** [comment]
Perfect! This appears to have fixed the issue. We did have the `FUNCTIONS_EXTENSION_VERSION` set to `~2` but changing this to `~2.0` appears to have fixed the issue. We'll migrate in the near future but we needed this functionality first. Thanks.
