### ISSUE TITLE
Service Bus Scale Controller/App Settings mismatch

### ISSUE THREAD

**Issue by cachai2** [Azure/Azure-Functions#1862]
Customers are running into issues where their function app won't trigger for hours despite having 100+ messages in queue. This can be fixed by adding an Application Setting to the function app named ConnectionStrings:AzureWebJobsServiceBus, with the value of the Service Bus Connection String. It does not work if the ServiceBus connection string is only set in the 'Connection Strings' portion of the Function App Configuration blade.

**Comment by apawast** [comment]
@cachai2 can you check if this has been resolved?

**Comment by cachai2** [comment]
Pragna's team has it as planned work.

**Comment by chiangvincent** [comment]
Talked with Kar and tested on a consumption production app -- was able to verify that the service bus extension starts up correctly when defined in the Connection Strings blade in portal. The idling + failure to restart is likely a separate and unrelated issue. Taking time to look into this.
