### ISSUE TITLE
Unable to user Memory Cache with Azure Function App V3 (local emulator)

### ISSUE THREAD

**Issue by PrakashRajanSakthivel** [Azure/Azure-Functions#1867]
I have created Azure Function App with Http trigger in that I want to use memory cache from system.runtime namespace to cache the token. but when I run the application its throwing the error `" System.Runtime.Caching: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified."`

I have made sure the exact version is installed in the project. here is the csproj file.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
    <PackageReference Include="System.Runtime.Caching" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
```

Here is the bare minimum version of the code where I am facing the issue.

```
public static class Function1
    {
        public static MemoryCache accessTokenCache = MemoryCache.Default;
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
           // errors are same irrespective of the invocation. If I add Get or Set I am getting the same error.
            log.LogError(accessTokenCache.CacheMemoryLimit.ToString());
            return new OkObjectResult("");
        }
    }
```

Framework: .net core 3.1
OS: Windows
It works fine with the package System.Runtime.Caching version 4.7.0 without having to install system.configuration.configurationmanager.

**Comment by v-anvari** [comment]
Hi @PrakashRajanSakthivel ,  5.0 package is not supported in this scenario. The .NET Worker is the supported approach to use those dependencies

**Comment by anandsowm** [comment]
@v-anvari Even today, only the 4.7 version of the Nuget works with Azure function app. How to use the latest version of that Caching Nuget in my Function App ( .NET 6 and Function worker runtime 4.x) ?
