### ISSUE TITLE
How do I force the telemetry client to be a servertelemetrychannel

### ISSUE THREAD

**Issue by SavaNDragos** [Azure/Azure-Functions#1868]
This is missing from the documentation for v3.

Seeing in app-insight 20-30% of logs missing. Maybe this would do the trick (note no issue from samples because I disabled it, same applies to data ingestion -> 100%)

**Comment by v-bbalaiagar** [comment]
Hi @SavaNDragos, We would like to know which logs are missing from app insights so that we can investigate this further.

**Comment by v-bbalaiagar** [comment]
Hi @SavaNDragos, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
