### ISSUE TITLE
Document file logging behavior

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#187]
Per https://github.com/Azure/azure-webjobs-sdk-script/issues/1222#issuecomment-282072378

Should document: File logs are only for driving the portal debugging scenario when you're in the portal. If the portal has not connected in 15 minutes, the logs will disable themselves. This is for performance reasons. You can force file logs to stay on, but for high throughput scenarios that can of course have perf impact.

**Comment by SyntaxC4** [comment]
We should also check to see if we have documented this for App Service.

**Comment by lindydonna** [comment]
@SyntaxC4 This is specific to how the functions runtime does logging. App Service logging is orthogonal.
