### ISSUE TITLE
Incorrect Language under "Integration" items

### ISSUE THREAD

**Issue by bluuf** [Azure/Azure-Functions#1876]
I've noticed that the interface language of the Azure Portal is ignored when you edit a trigger in Azure Functions.
Whenever I go to a function and choose for Integration all the items I select have localized property names.

For instance: If I choose to edit the triggers words like Route Template are shown in Dutch in my case. This happens on most of the settings.
I've double checked that my language settings in Azure are set to English, this is the case (everything else is also in English).

See the screenshots for some of the examples

![image](https://user-images.githubusercontent.com/30879608/114147411-f7c3c800-9918-11eb-870a-319e7ca665c0.png)
![image](https://user-images.githubusercontent.com/30879608/114147502-0e6a1f00-9919-11eb-9b46-d1005b6cf758.png)
![image](https://user-images.githubusercontent.com/30879608/114147617-28a3fd00-9919-11eb-9a29-e093176d7b3f.png)

**Comment by v-bbalaiagar** [comment]
Hi @bluuf, It requires a support ticket for resolution. Please follow the below path to raise a support ticket- Portal > menu > help and support >New support request

**Comment by v-bbalaiagar** [comment]
Hi @bluuf, Closing this issue as the required information is provided, Please feel free to reach back to us in case of any further queries related to this issue.
