### ISSUE TITLE
Any limitation on 302 temporary redirect?

### ISSUE THREAD

**Issue by DadvDadv** [Azure/Azure-Functions#1877]
Hi, I'm facing a pb on Azure function using MS Graph Pdf Converter (https://docs.microsoft.com/fr-FR/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)

When i call this in Azure i've got this message : 

> 502 - Web server received an invalid response while acting as a gateway or proxy server. There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

This error is from the Function Process i think (none of my try/catch was call)

When the function is launch in local, all work fine, it's only when i publish it.

So is there any limitation for this ? any doc to explain it ?

Thx

(You can find my request here : https://stackoverflow.com/questions/67002455/deal-with-httpstatus-302-in-azure-function)

**Comment by balag0** [comment]
This could be a result of timeouts. If you could share the app name we can investigate further
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by DadvDadv** [comment]
Thank's for your answer, my informations : 

Region : 

> France-Centre

Log informations : 

> 2021-04-13T08:27:33.194 [Information] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=d6c3dfd8-d1cc-453b-a5e7-298e2e528a1c)

Error message in web client : 

> 502 - Web server received an invalid response while acting as a gateway or proxy server.
> There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

No error in log function console

**Comment by DadvDadv** [comment]
This function is for a test so her some of my code : 

   ```
var token = await authProvider.ClientApplication.AcquireTokenForClient(new string[] { "https://graph.microsoft.com/.default" }).ExecuteAsync();


            HttpClient httpClient = new HttpClient();

            httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token.AccessToken);
            try
            {
                var response = await httpClient.GetAsync($"https://graph.microsoft.com/v1.0/drives/{DRIVE_ID}/items/{word_Id}/content?format=pdf");

                log.LogInformation($"Status Code : {response.StatusCode}");  //Never call

                if (response.StatusCode == System.Net.HttpStatusCode.Redirect)
                {
                    var bytes = await httpClient.GetByteArrayAsync(response.Headers.Location);

                    return new FileContentResult(bytes, "application/pdf");
                }

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    var bytes = await response.Content.ReadAsByteArrayAsync();

                    return new FileContentResult(bytes, "application/pdf");
                }

            }
            catch (Exception ex)
            {
                log.LogInformation($"Error : {ex.Message}");  //Never call
            }
```
My catch is never call and the Status did'nt show on log...

I think the app have been "stop" because nothing is write in the console

**Comment by DadvDadv** [comment]
I found that my pb was on the upload of the file, the stream was close to early and that was making the function to exit...

Sorry for the search and thx for all
