### ISSUE TITLE
URGENT: Something weird has happened recently with PUT requests

### ISSUE THREAD

**Issue by richardhauer** [Azure/Azure-Functions#1878]
I have APIs that have been in production for ages. Very recently - perhaps only the last few days - PUT requests with a path containing only 1 segment have started to fail.

__To reproduce:__
1) VS Enterprise 16.9.3 - totally up to date
2) Create an Azure Fn project, C#, HTTP Trigger
3) Add "put" method into the sample function, set auth to `Anonymous`, set `Route` = 'test'
4) Remove body of method and simply `return new OkObject();`
5) Open `host.json` and `, "extensions": { "http": { "routePrefix": "" } }` before the last bracket

Run and use postman to observe that GET and POST works as expected.
Switching to the PUT method returns a 202 and an odd payload.

From my investigations it seems that the routing system is not identifying the Method mapped to the route properly, and there's some type of fallback to a default MVC style route, that obviously also fails.

Interestingly if you change the route from `test` to `test/1` it works as expected in the emulator - so it's only the single segment for the PUT method that's affected. Leaving the default route prefix `api` in place in the hosts file also makes it work.

Putting the 'api' route prefix into the Azure functions does not seem to make it work (I'm still experimenting), but I am getting a 401 now with a response header: `*WWW-Authenticate:* Bearer error="invalid_token", error_description="The signature key was not found"` - note that the exact same token (AzureAD) works perfectly for requests using GET, POST so I really don't think it's an actual token issue.

This issue isn't coming from a nuGet package either - I rolled my code back 2 months and I still get the issue.
It isn't related to VS either, because my production functions in Azure are also having this issue.
There must have been a recent change to the Functions runtime and emulator that has caused this - I have tried source stepping with the debugger but I just can't find it.

Can anyone please confirm this problem?

**Comment by anthonychu** [comment]
@fabiocav Do you know if this is a known issue?

**Comment by anthonychu** [comment]
This issue is tracked here: https://github.com/Azure/azure-functions-host/issues/7260#issuecomment-813666977

**Comment by richardhauer** [comment]
Hi @anthonychu  yes I worked with the MS Critical Incident team yesterday after logging a SEV A on this. The workaround was to pin the runtime to version `3.0.15406` using the `FUNCTIONS_EXTENSION_VERSION` AppSetting, rather than the usual `~3`.

Thanks for following up on this.
