### ISSUE TITLE
Document RE: Azure Functions 5 minute execution time limit

### ISSUE THREAD

**Issue by yochay** [Azure/Azure-Functions#188]
Azure Functions under Consumption Plan limits the execution time to a maximum of 5 minutes. The documentation does NOT mention this! It's only mentioned in comments on a couple Github issues...

this issue https://github.com/Azure/Azure-Functions/issues/75
https://github.com/Azure/azure-webjobs-sdk-script/issues/18#issuecomment-254603536

Both of these Github issues and comments are a bit dated. Is this "5 minute runtime max" still a limitation with Azure Functions today?

**Comment by lindydonna** [comment]
It is a limitation on Consumption. This needs to be documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale

**Comment by justinyoo** [comment]
I actually created an issue #131 that is related to this, a while ago. Could you also clarify this, please?

**Comment by mikezks** [comment]
It is mentioned in a blog post by @christopheranderson  as well:
See [Making Azure Functions more “serverless”](https://blogs.msdn.microsoft.com/appserviceteam/2016/11/15/making-azure-functions-more-serverless/).

**Comment by ggailey777** [comment]
@lindydonna @christopheranderson It seems like we need to document all of the host.json settings (and the defaults) in the main docs and not just the wiki, don't you think?

**Comment by lindydonna** [comment]
@ggailey777 Yes, but I think that's a lower priority item than things that aren't documented anywhere. We now have a json schema for host.json which means it will be automatically documented in Visual Studio.

**Comment by lindydonna** [comment]
Documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#consumption-plan
