### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException while processing a blob trigger in Azure Function .net 5

### ISSUE THREAD

**Issue by iamnicoj** [Azure/Azure-Functions#1881]
I have an Az Function writte in C#, .Net 5, configure with a blob trigger like this:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.2" />
    <PackageReference Include="TinyCsvParser" Version="2.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

and the trigger configured expecting a Stream 

``` c#
     [Function("function_name")]
        public static async Task Run([BlobTrigger("datatoingest/{name}", Connection = "STORAGE")] Stream myBlob, string name,
            ILogger logger)
```

If I either deploy it or debug it locally I get the following exception soon as it triggers and detects a new blob stating it can't convert  to type 'System.IO.Stream' from type 'System.ReadOnlyMemory

> Result: Failure Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'nicos_nyctrips_ingestion': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13 at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169 Stack: at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13 at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169

**Comment by v-anvari** [comment]
Hi @iamnicoj , Can we have the repro steps to reproduce this error, in order to understand the cause of the error.

**Comment by iamnicoj** [comment]
1. Using vscode 1.55 for MacOS. and Azure Functions Extension v.1.3.0
2. Select the option to create and azure function 
3. Select C#
4. Select .net 5 isolated
5. Select Blob trigger 
6. Add local.settings.json
7. Select an existing v2 Storage account and define the container to subscribe to
8. Afer following this steps it creates this function:
`using System;
using System.IO;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace mycompany
{
    public static class BlobTriggerCSharpError
    {
        [Function("BlobTriggerCSharpError")]
        public static void Run([BlobTrigger("reproerrorazbt/{name}", Connection = "nicocsetrips_STORAGE")] string myBlob, string name,
            FunctionContext context)
        {
            var logger = context.GetLogger("BlobTriggerCSharpError");
            logger.LogInformation($"C# Blob trigger function Processed blob\n Name: {name} \n Data: {myBlob}");
        }
    }
}
`
9. I change the first input parameter from string to Stream 
10. Either run it locally or deploy it to a new AZ App. it will run and start listening to the blob.
11. As soon as i drop a new file in the blob it will break with the exception I mentioned above. I did not include any other package, nor did I even change the basic template generated code. 
12. I created a repo with the project [here](https://github.com/iamnicoj/FailiingAZBlobTriggerTemplate.git): 
12. This is the full log when running locally and dropping a file in the blob:

> > Executing task: dotnet clean /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <
> 
> Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 4/15/2021 4:35:14 PM.
>      1>Project "/Users/nicolasjimenez/myrepos/az_bst_test/az_bst_test.csproj" on node 1 (Clean target(s)).
>      1>_CleanFunctions:
>          Removing directory "/Users/nicolasjimenez/myrepos/az_bst_test/bin/Debug/net5.0/".
>      1>Done Building Project "/Users/nicolasjimenez/myrepos/az_bst_test/az_bst_test.csproj" (Clean target(s)).
> 
> Terminal will be reused by tasks, press any key to close it.
> 
> > Executing task: dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <
> 
> Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   az_bst_test -> /Users/nicolasjimenez/myrepos/az_bst_test/bin/Debug/net5.0/az_bst_test.dll
>   Determining projects to restore...
>   Restored /var/folders/b1/7jq596h103l6rnztd5k46r700000gn/T/3rg1mrvv.3rr/WorkerExtensions.csproj (in 2.95 sec).
>   WorkerExtensions -> /var/folders/b1/7jq596h103l6rnztd5k46r700000gn/T/3rg1mrvv.3rr/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll
> 
> Terminal will be reused by tasks, press any key to close it.
> 
> > Executing task: func host start <
> 
> 
> Azure Functions Core Tools
> Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
> Function Runtime Version: 3.0.15417.0
> 
> [2021-04-15T20:35:31.674Z] Worker process started and initialized.
> 
> Functions:
> 
>         BlobTriggerCSharpError: BlobTrigger
> 
> For detailed output, run func with --verbose flag.
> [2021-04-15T20:35:37.942Z] Host lock lease acquired by instance ID '000000000000000000000000E728AB97'.
> [2021-04-15T20:36:03.857Z] Executing 'Functions.BlobTriggerCSharpError' (Reason='New blob detected: reproerrorazbt/basicseedgreen.csv', Id=86f13d1a-10c0-4309-a45a-293b5bd6910f)
> [2021-04-15T20:36:03.860Z] Trigger Details: MessageId: 4c01302e-7855-4674-9b44-86caba0c2aca, DequeueCount: 1, InsertionTime: 2021-04-15T20:36:03.000+00:00, BlobCreated: 2021-04-15T20:36:00.000+00:00, BlobLastModified: 2021-04-15T20:36:00.000+00:00
> [2021-04-15T20:36:04.451Z] Executed 'Functions.BlobTriggerCSharpError' (Failed, Id=86f13d1a-10c0-4309-a45a-293b5bd6910f, Duration=658ms)
> [2021-04-15T20:36:04.451Z] System.Private.CoreLib: Exception while executing function: Functions.BlobTriggerCSharpError. System.Private.CoreLib: Result: Failure
> [2021-04-15T20:36:04.451Z] Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'BlobTriggerCSharpError': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
> [2021-04-15T20:36:04.458Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:04.458Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:04.458Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:04.461Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
> [2021-04-15T20:36:04.462Z] Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:04.462Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:04.464Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:04.464Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.
> [2021-04-15T20:36:05.112Z] Executing 'Functions.BlobTriggerCSharpError' (Reason='New blob detected: reproerrorazbt/basicseedgreen.csv', Id=1527c097-66a8-4a34-86eb-be78da370b85)
> [2021-04-15T20:36:05.113Z] Trigger Details: MessageId: 4c01302e-7855-4674-9b44-86caba0c2aca, DequeueCount: 2, InsertionTime: 2021-04-15T20:36:03.000+00:00, BlobCreated: 2021-04-15T20:36:00.000+00:00, BlobLastModified: 2021-04-15T20:36:00.000+00:00
> [2021-04-15T20:36:05.137Z] Executed 'Functions.BlobTriggerCSharpError' (Failed, Id=1527c097-66a8-4a34-86eb-be78da370b85, Duration=90ms)
> [2021-04-15T20:36:05.137Z] System.Private.CoreLib: Exception while executing function: Functions.BlobTriggerCSharpError. System.Private.CoreLib: Result: Failure
> [2021-04-15T20:36:05.137Z] Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'BlobTriggerCSharpError': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
> [2021-04-15T20:36:05.137Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:05.138Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:05.138Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:05.138Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
> [2021-04-15T20:36:05.139Z] Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:05.139Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:05.139Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:05.140Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.
> [2021-04-15T20:36:05.553Z] Executing 'Functions.BlobTriggerCSharpError' (Reason='New blob detected: reproerrorazbt/basicseedgreen.csv', Id=fdadfd3b-4670-4071-87ad-663dcfb84e5e)
> [2021-04-15T20:36:05.557Z] Trigger Details: MessageId: 4c01302e-7855-4674-9b44-86caba0c2aca, DequeueCount: 3, InsertionTime: 2021-04-15T20:36:03.000+00:00, BlobCreated: 2021-04-15T20:36:00.000+00:00, BlobLastModified: 2021-04-15T20:36:00.000+00:00
> [2021-04-15T20:36:05.640Z] Executed 'Functions.BlobTriggerCSharpError' (Failed, Id=fdadfd3b-4670-4071-87ad-663dcfb84e5e, Duration=142ms)
> [2021-04-15T20:36:05.640Z] System.Private.CoreLib: Exception while executing function: Functions.BlobTriggerCSharpError. System.Private.CoreLib: Result: Failure
> [2021-04-15T20:36:05.643Z] Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'BlobTriggerCSharpError': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
> [2021-04-15T20:36:05.646Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:05.649Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:05.653Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:05.655Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
> [2021-04-15T20:36:05.657Z] Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:05.657Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:05.662Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:05.662Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.
> [2021-04-15T20:36:05.916Z] Executing 'Functions.BlobTriggerCSharpError' (Reason='New blob detected: reproerrorazbt/basicseedgreen.csv', Id=6214ed9f-7040-43ea-960f-b1b31e7703e9)
> [2021-04-15T20:36:05.916Z] Trigger Details: MessageId: 4c01302e-7855-4674-9b44-86caba0c2aca, DequeueCount: 4, InsertionTime: 2021-04-15T20:36:03.000+00:00, BlobCreated: 2021-04-15T20:36:00.000+00:00, BlobLastModified: 2021-04-15T20:36:00.000+00:00
> [2021-04-15T20:36:05.947Z] Executed 'Functions.BlobTriggerCSharpError' (Failed, Id=6214ed9f-7040-43ea-960f-b1b31e7703e9, Duration=60ms)
> [2021-04-15T20:36:05.947Z] System.Private.CoreLib: Exception while executing function: Functions.BlobTriggerCSharpError. System.Private.CoreLib: Result: Failure
> [2021-04-15T20:36:05.947Z] Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'BlobTriggerCSharpError': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
> [2021-04-15T20:36:05.947Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:05.947Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:05.947Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:05.947Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
> [2021-04-15T20:36:05.948Z] Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:05.948Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:05.949Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:05.949Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.
> [2021-04-15T20:36:06.307Z] Executing 'Functions.BlobTriggerCSharpError' (Reason='New blob detected: reproerrorazbt/basicseedgreen.csv', Id=574ba953-c597-4560-a192-2784a453319b)
> [2021-04-15T20:36:06.309Z] Trigger Details: MessageId: 4c01302e-7855-4674-9b44-86caba0c2aca, DequeueCount: 5, InsertionTime: 2021-04-15T20:36:03.000+00:00, BlobCreated: 2021-04-15T20:36:00.000+00:00, BlobLastModified: 2021-04-15T20:36:00.000+00:00
> [2021-04-15T20:36:06.395Z] Executed 'Functions.BlobTriggerCSharpError' (Failed, Id=574ba953-c597-4560-a192-2784a453319b, Duration=112ms)
> [2021-04-15T20:36:06.399Z] System.Private.CoreLib: Exception while executing function: Functions.BlobTriggerCSharpError. System.Private.CoreLib: Result: Failure
> [2021-04-15T20:36:06.404Z] Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'BlobTriggerCSharpError': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
> [2021-04-15T20:36:06.405Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:06.411Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:06.411Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:06.412Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
> [2021-04-15T20:36:06.412Z] Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
> [2021-04-15T20:36:06.413Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
> [2021-04-15T20:36:06.413Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2021-04-15T20:36:06.424Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.
> [2021-04-15T20:36:06.441Z] Message has reached MaxDequeueCount of 5. Moving message to queue 'webjobs-blobtrigger-poison'.
>

**Comment by v-anvari** [comment]
Hi @iamnicoj , Thank you for the information, We will repro this scenario and update you with the findings

**Comment by v-anvari** [comment]
Hi @iamnicoj , Apologies for the delayed response, Streams aren't supported when using BlobTriggers in .Net 5.0.

[https://github.com/Azure/azure-functions-dotnet-worker/issues/378#issuecomment-820768693](https://github.com/Azure/azure-functions-dotnet-worker/issues/378#issuecomment-820768693)

Duplicate issue : [azure-functions-dotnet-worker/issues/398](https://github.com/Azure/azure-functions-dotnet-worker/issues/398).

The right repository for this scenario is Dot Net worker. 

>
