### ISSUE TITLE
Tutorial chain-azure-functions-data-using-bindings

### ISSUE THREAD

**Issue by PhakornKiong** [Azure/Azure-Functions#1885]
https://docs.microsoft.com/en-us/learn/modules/chain-azure-functions-data-using-bindings/5-read-data-with-input-bindings-portal-lab?pivots=javascript

In the above tutorial, the resulting `function.json` created would be 
```JSON
    {
      "name": "bookmark",
      "databaseName": "func-io-learn-db",
      "collectionName": "Bookmarks",
      "connectionStringSetting": "****",
      "id": "id",
      "partitionKey": "/id",
      "direction": "in",
      "type": "cosmosDB"
```

This setting would cause all query to cosmosDB  to return undefined.

By updating `function.json` to the following, everything works as it should be.
```JSON
    {
      "name": "bookmark",
      "databaseName": "func-io-learn-db",
      "collectionName": "Bookmarks",
      "connectionStringSetting": "****",
      "id": "{id}",
      "partitionKey": "{id}",
      "direction": "in",
      "type": "cosmosDB"
```

There are other users who reported the same as well (Look at the answer by `Chetan`)
https://stackoverflow.com/questions/61988060/azure-cosmos-db-input-binding-for-an-azure-function-doesnt-work

I'm using Azure Function version ~3.

**Comment by v-anvari** [comment]
Hi @Darkripper214 , Thank you for reporting this issue. We shall check this internally and make the appropriate changes.

**Comment by v-anvari** [comment]
@ggailey777 / @anthonychu  , Can you help us with the team who can update the Microsoft.Learn with the correct information. As the Id and partition key would require to be considered as bindings here.

**Comment by ggailey777** [comment]
@v-anvari I'll check with the current owner of that module. @Darkripper214 thanks for reporting this, we'll get it fixed 👍

**Comment by v-anvari** [comment]
Thank you @ggailey777

**Comment by rmcmurray** [comment]
Thanks for the feedback, @v-anvari. I'll look into this.

**Comment by v-anvari** [comment]
@rmcmurray , Thank you for the update, could you please transfer this issue to the right repository, if applicable

**Comment by v-anvari** [comment]
Hi @rmcmurray , I have reproduced this scenario recently and this is still the case. Do you have any updates here. 

Thank you

**Comment by v-anvari** [comment]
One more user has raised a similar concern with the same learning path in - https://github.com/Azure/Azure-Functions/issues/1670

cc - @rmcmurray

**Comment by v-anvari** [comment]
Transferring this issue to Azure-docs , as this still requires correction

**Comment by rmcmurray** [comment]
FYI - All three exercises in this module needed updating, and I've been working on a rewrite for the past few days. I should have this in review later today.

**Comment by v-anvari** [comment]
Thank you for the update @rmcmurray 

Closing this issue here. For further queries regarding MS learn, please report issue below the tutorial

![image](https://user-images.githubusercontent.com/66122429/123271654-af32a880-d51e-11eb-84ad-9b699b7f8e04.png)
