### ISSUE TITLE
[Kudu] Show a banner saying content is R/O when RunFromPackage

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/Azure-Functions#1888]
Tracking issue for kudu

**Comment by fabiocav** [comment]
This is currently in draft. Leaving in sprint 101 as the work should be merged soon.

**Comment by ankitkumarr** [comment]
Completed via https://github.com/projectkudu/kudu/commit/6c62ba710e42e18043eb3e5f3443d8cc22bd7af1
