### ISSUE TITLE
Guidance for Versioning Functions

### ISSUE THREAD

**Issue by jamessdixon** [Azure/Azure-Functions#189]
Is there any guidance for versioning my functions?  For HTTP triggers, I assume we could use a header variable.  However, for Timers and other Triggers, do I use a naming convention?  Seems clunky... 

Thanks

**Comment by SimonLuckenuik** [comment]
For C# assemblies, I use the traditional assembly version, for CSX, I add a replacement token in source files that is being replaced by the CI server. The Replacement token should be applicable to any "file based" programming language. The version is also added to my logs to make sure I have good visibility on it. It is also visible from the portal for all file based scripts. That's the best I found so far.

**Comment by lindydonna** [comment]
@SimonLuckenuik's answer is good. If you have more questions on this, 
 [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so)  will get you a much faster reply.
