### ISSUE TITLE
[Premium] Azure Function v3 not picking up latest code after deployment

### ISSUE THREAD

**Issue by alrios-ms** [Azure/Azure-Functions#1890]
Hi Team,

We are having an intermittent issue with our Azure Functions v3, we have several Azure Functions sharing common code,  after code deployments via YAML Azure Pipelines using this task AzureFunctionApp@1 set to runFromPackage, one of the functions is not picking up the latest code while the others got updated. We tried redeploying the code again which takes around 40 min but the result was the same. We got the same issue on our last deployment, we had to manually stop and start the Function App again in order for it to pickup the latest code.

1. Deploy function through Azure Pipeline
2. Navigate to KUDU to SitePackages
3. We can tell by the dates (and examining the code) that it hasn't been updated.

**Expected behavior**
Azure Function get updated with the latest code without having someone to go stop and start the Function App

**Screenshots**
This was taken after the deployment completed
![image](https://user-images.githubusercontent.com/70599097/116747581-f97e2a00-a9b2-11eb-8af0-4b5b6bd769d1.png)

This was the content of siteversion.txt
\\?\d:\local\SitePackages\1975050890.zip

Once we stopped the Function App and restarted it we found a new zip package and siteversion.txt was updated.

This has happened several times lately for us.

Regards,
Alberto

**Comment by v-anvari** [comment]
Hi @alrios-ms , Can we have the function app details so that we can see what is the issue

**Comment by alrios-ms** [comment]
Hi Anusri_Varier,

Resource group: gmm-compute-prodv2
SubscriptionId: 35a55dce-4df3-4970-82ed-e61d13b5193a
App Service Plan: gmm-compute-prodv2-premium (EP1: 1)
Function App: gmm-compute-prodv2-OneCatalog

Let me know if you need some other details.

Regards,
Alberto

**Comment by alrios-ms** [comment]
Hi @v-anvari , is there a way to share privately that information?

**Comment by v-anvari** [comment]
Sharing   Your Function App name privately · Azure/azure-functions-host Wiki   (github.com)
--

**Comment by alrios-ms** [comment]
Hi @v-anvari,

Here you go.

2021-05-02 20:40:00.801
97ede1cd-68d5-42cf-a9fa-360301104135
West US 2

**Comment by v-anvari** [comment]
Thankyou

**Comment by alrios-ms** [comment]
Commenting to prevent auto closing

**Comment by v-anvari** [comment]
Thank you @alrios-ms , The team is looking this issue backend, will update you any information

**Comment by v-anvari** [comment]
Hi @alrios-ms , While the team is investigating, this looks like an issue related to your specific app. Did you have a chance to submit a support request. If not, can you submit a support request and check if the support team could find out something from their end specific to your app.

**Comment by alrios-ms** [comment]
Hi @v-anvari, I haven't submitted a support request yet, I will do that.

**Comment by v-anvari** [comment]
Hi @alrios-ms , Have you received any solution from the support team

**Comment by alrios-ms** [comment]
Hi @v-anvari , yes I have, they suggested to disable dynamic cache by setting WEBSITE_DYNAMIC_CACHE = 2
https://github.com/projectkudu/kudu/wiki/Configurable-settings

I will test it and report back.
Thank you.
