### ISSUE TITLE
TCP starvation when using ClientCertificate

### ISSUE THREAD

**Issue by riccardobecker** [Azure/Azure-Functions#1892]
We have a function app running on the S1 plan. We are calling an external http endpoint which is protected with a client certificate. We experience increasing outbounds connections and it seems that the used HttpClientFactory does not clean up its resources thoroughly. Our setup:

- Azure Function
- Using named httpclient
- Taking certificate from keyvault (once and then cache it)

Startup.cs:
```
builder.Services.AddSingleton<IKeyVaultCertificateService, KeyVaultCertificateService>();
builder.Services.AddHttpClient("namedclient")
                .ConfigurePrimaryHttpMessageHandler((sp) =>
                {
                    var httpHandler = new HttpClientHandler();
                    httpHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
                    var keyvaultService = sp.GetRequiredService<IKeyVaultCertificateService>();
                    var (activeCertificate, _) = keyvaultService.GetCertificatesFromKeyVault().GetAwaiter().GetResult();
                    httpHandler.ClientCertificates.Add(activeCertificate);
                    return httpHandler;
                });
```

Next snippet is from a timertriggered function that pulls data from the external source every 5 minutes. I have simplified it and brought it back to its essence.

```
public class PullDataFunction
{
		private readonly HttpClient _httpClient;

		public PullDataFunction(IHttpClientFactory clientFactory)
		{
			_logger = logger;
			_httpClient = clientFactory.CreateClient("namedclient");

		}
		
		[FunctionName(nameof(PullEvseStatusFunction))]
		public async Task Run([TimerTrigger("0 */5 * * * *")] TimerInfo myTimer,
			[ServiceBus("sometopic", EntityType.Topic, Connection = "someconnection")] IAsyncCollector<Message> collector)
		{
		    var somepageRequest = new HttpRequestMessage();
			
			var result = await _httpClient.SendAsync(pageRequest);
	
	}
}
```

This figure illustrates the increasing tcp connections, they continue to rise until they reach around 2K and then break the whole service.
![image](https://user-images.githubusercontent.com/3964719/116978030-7535ea80-acc3-11eb-8b51-837974ad3004.png)

We are wondering if this is the recommended way of using ClientCertificates? Can you explain why the tcp connections continue to rise?

thanks in advance,
Riccardo

**Comment by v-anvari** [comment]
Hi @riccardobecker , Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-anvari** [comment]
Hi @riccardobecker , Apologies for the delayed response, I have discussed this internally and the team was interested to understand how the services manage the key vault internally. Also, this issue is dependent on your code and how the connections are made. It could be possible that the connection at the client is left open and is enabled when communicating with the key vault.

The recommendation here would be to analyze the memory dump, also a support ticket in this case would be helpful as this looks like client side error. 

Thank you for reaching us, please feel feel free to reach back to us in case of any further queries
