### ISSUE TITLE
Azure Function Unable to Run pg_dump.exe after uploading exe file into Azure Function Shared Folder

### ISSUE THREAD

**Issue by jitendriyag2** [Azure/Azure-Functions#1895]
I Created a Azure Function using PowerShell as well as C# in Azure Portal then i tried to run some .exe file by uploading to corresponding folder but it is not executing such exe without failing with the error, if something happing also it should show corresponding error but it is not displaying.

Code to Repro:

#r "Newtonsoft.Json"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;
using System.Diagnostics;
using System.IO;
using System.Text;

public static  IActionResult Run(HttpRequest req, out string outputBlob, ILogger log)
{
    outputBlob = "";
        try
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            try
            {
                log.LogInformation("Starting Try");
                ProcessStartInfo startInfo = new ProcessStartInfo();
                log.LogInformation("Starting startInfo");
                startInfo.CreateNoWindow = true;
                startInfo.RedirectStandardOutput = true;
                startInfo.UseShellExecute = false;
                string filePath = @$"C:\home\site\wwwroot\Executables\pg_dump.exe";
                log.LogInformation(filePath);
                startInfo.FileName = filePath;
                startInfo.WindowStyle = ProcessWindowStyle.Hidden;
         
                startInfo.Arguments = @"-h {server}.postgres.database.azure.com -U {dbUser}-Fc -d {dbName}-n {schema}";
                //startInfo.Arguments. = "";
                Environment.SetEnvironmentVariable("PGPASSWORD", "PASSWORD");
                
                StringBuilder output = new StringBuilder();
                try
                {
                    // Start the process with the info we specified.
                    // Call WaitForExit and then the using statement will close.
                    using (Process exeProcess = Process.Start(startInfo))
                    {
                        log.LogInformation("Inside Process Start");
                        while (!exeProcess.StandardOutput.EndOfStream)
                        {
                            log.LogInformation("Getting Output");
                            var line = exeProcess.StandardOutput.ReadLine();
                            output.Append(line);
                        }
                        log.LogInformation("Completed Output");
                        string outputString = output.ToString();
                        log.LogInformation(outputString);
                        outputBlob = outputString;
                        exeProcess.WaitForExit();
                        //myBlob.Write(ASCIIEncoding.Default.GetBytes(outputString), 0, outputString.Length);
                    }
                }
                catch (Exception ex)
                {
                    log.LogError("Error Occured while Executing File", ex.Message);
                    // Log error.
                }
            }
            catch (Exception ex)
            {
                log.LogError("Error Occured AT Root ", ex.Message);
            }
            log.LogInformation("Completed Operation");
            string responseMessage = "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.";

            return new OkObjectResult(responseMessage);
        }
        catch (Exception ex)
        {
            return new OkObjectResult(ex);
        }
}

**Comment by v-bbalaiagar** [comment]
Hi @jitendriyag2, Thank you for reaching out to us, Shall try to reproduce this scenario and update you with findings.

**Comment by v-bbalaiagar** [comment]
Hi @jitendriyag2, We would like to know when you attempted to run this, Can you provide an execution id and timestamp so that we can look at the logs to understand whether you are running into a sandbox issue.
