### ISSUE TITLE
Error: Failed to sync triggers for function 

### ISSUE THREAD

**Issue by wpitallo** [Azure/Azure-Functions#1897]
Getting this error when deploying to a function:

Error: Failed to sync triggers for function app 'xxx function-name xxx'. Error: BadRequest - Encountered an error (InternalServerError) from host runtime. (CODE: 400)

This only happens tho when I create the function using:

az functionapp create --subscription ${subscription} --resource-group ${resourceGroup} --consumption-plan-location ${location} --runtime node --runtime-version 14 --functions-version 3 --name ${functionName} --storage-account ${storageAccount} --os-type Linux

When I create the function manually and run the deployment everything works.

**Comment by balag0** [comment]
Please share the app name using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by wpitallo** [comment]
Hi @balag0 the app name is: avataaars-functions-test-eu-c1.azurewebsites.net

**Comment by wpitallo** [comment]
I am deploying from an Azure DevOps pipeline. When I get the error.

**Comment by wpitallo** [comment]
Hi @balag0 , any idea what is causing this.

**Comment by balag0** [comment]
@wpitallo Sorry for the delay. Looks like the problem is due to
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: Failure Exception: Worker was unable to load function avataaars: 'TypeError: Assignment to constant variable.' Stack: TypeError: Assignment to constant variable.
main.server.js:12:17

Does that help?

**Comment by wpitallo** [comment]
Hi @balag0 So I redeployed and I get the same error, where can I view that error that you shared? Thanks so much for the help!

**Comment by balag0** [comment]
It should be available in application insights(check the traces / exceptions table). Did you identify any issue with main.server.js that you had to update with the recent deployment?
I will also verify the logs from today to check if there are any other issues.

**Comment by wpitallo** [comment]
Thanks so much, I am busy updating some stuff now will keep you posted thanks so much for the help, its greatly apporeciated!

**Comment by wpitallo** [comment]
Hi @balag0 

Thanks again for the help. So there does seem to be something wrong.

I did make some changes and I redeployed the code. The code I deployed to the app I created using the CLI failed in the deployment. 

Here is a test link (failed function release):
https://avataaars-functions-test-eu-c1.azurewebsites.net/api/v1/documentation/publicGlobal/ping/ping.json

Then I created a function manually and deployed the exact same package. The release passes and I got a success response:
https://avataaars-functions-test-eu-c2.azurewebsites.net/api/v1/documentation/publicGlobal/ping/ping.json

This stopped working then after a few hours and now I get an error. So I setup another function and same thing happened. 

https://avataaars-functions-test-eu-c3.azurewebsites.net/api/v1/documentation/publicGlobal/ping/ping.json

![image](https://user-images.githubusercontent.com/12214559/119364107-dd6a6180-bcae-11eb-8d08-84809c5c2558.png)

This is a windows function tho.

Now I get this error:
{"status":500,"statusText":"failed","message":"Request failed with status code 500","stack":"Error: Request failed with status code 500\n    at createError (C:\\home\\site\\wwwroot\\node_modules\\@wpitallo\\global-server\\dist\\main.min.cjs:68695:15)\n    at settle (C:\\home\\site\\wwwroot\\node_modules\\@wpitallo\\global-server\\dist\\main.min.cjs:68954:12)\n    at IncomingMessage.handleStreamEnd (C:\\home\\site\\wwwroot\\node_modules\\@wpitallo\\global-server\\dist\\main.min.cjs:68081:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}

However I cant seem to see any error in the log. Also this URL was responding and I did not make any changes and then it just started erroring:

https://avataaars-functions-test-eu-c3.azurewebsites.net/api/v1/documentation/publicGlobal/ping/ping.json

How strange does this look (these are requests to the same build):

![image](https://user-images.githubusercontent.com/12214559/119364860-a779ad00-bcaf-11eb-974d-b08bd53a9e3f.png)

**Comment by wpitallo** [comment]
Hi @balag0, hope that you are keeping well.

So I am still getting a failed deployment returned now even thought the function seems to be working. 

https://avataaars-functions-test-eu-c1.azurewebsites.net/api/v1/avataaars/ping/unsecure

I also do not see any exceptions generated when this fails. (Note this is only for the function created using az cli)

I deploy the same package to another function that I created manually using the exact same parameters and the deploy runs successfully. 

Any other ideas as to what could be causing this?

Thanks for the help!

**Comment by wpitallo** [comment]
Ok cool thanks, will give it a try. Also just to confirm it works perfectly if I deploy to a manually created function with everything exactly the same. Its only failing on the function created using the Azure cli. And also just to confirm even tho its failing from Azure devOps the function is working 100% correctly. But will try check the logs for that now. Thanks again for the help, really appreciate it!

**Comment by wpitallo** [comment]
Hey @balag0,

So I did that and I could not find a kudu-mnt share but I did find the deploy logs with this error:

text="There is not enough space on the disk. 

However in the entire storage account is only using 3.6 Gb is there something else I might be missing?

This may explain why the manual one works, it probably because I am using a different storage account.

Any idea where I can get more info about the possible storage limits?

```
-<step title="Incoming Request" X-Forwarded-TlsVersion="1.2" X-AppService-Proto="https" X-Forwarded-Proto="https" WAS-DEFAULT-HOSTNAME="avataaars-functions-test-eu-c1.scm.azurewebsites.net" X-SITE-DEPLOYMENT-ID="avataaars-functions-test-eu-c1" ....'>

<!-- duration: 750ms -->

<step title="Cleanup Xml Logs" date="2021-05-12T10:27:43.361"/>

<!-- duration: 47ms -->

-<step title="ZipPushDeploy" date="2021-05-12T10:27:43.440">

<step title="LockFile 'C:\home\site\locks\deployments.lock' acquired" date="2021-05-12T10:27:43.486"/>

<!-- duration: 31ms -->


<step title="Saving request content to C:\home\data\SitePackages\20210512102743.zip" date="2021-05-12T10:27:43.549"/>

<!-- duration: 62ms -->


<step title="LockFile 'C:\home\site\locks\deployments.lock' released" date="2021-05-12T10:27:43.658"/>

<!-- duration: 16ms -->


</step>
<!-- duration: 375ms -->
<step title="Error occurred" type="error" date="2021-05-12T10:27:43.830" stackTrace=" at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access) at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated() at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile) at System.Web.HttpRawUploadedContent.TempFile..ctor() at System.Web.HttpRawUploadedContent.AddBytes(Byte[] data, Int32 offset, Int32 length) at System.Web.HttpBufferlessInputStream.EndRead(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.WebHost.SeekableBufferedRequestStream.<ReadAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Kudu.Services.ByteRanges.HttpRequestMessageExtensions.<CopyToAsync>d__1.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\ByteRanges\HttpRequestMessageExtensions.cs:line 54 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Services.Deployment.PushDeploymentController.<WriteSitePackageZip>d__20.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 751 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Services.Deployment.PushDeploymentController.<>c__DisplayClass12_0.<<PushDeployAsync>b__0>d.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 402 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Contracts.Infrastructure.LockExtensions.<LockOperationAsync>d__6.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 115 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Services.Infrastructure.LockExtensions.<LockHttpOperationAsync>d__1.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Infrastructure\LockExtensions.cs:line 30 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Services.Deployment.PushDeploymentController.<PushDeployAsync>d__12.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 398 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Kudu.Services.Deployment.PushDeploymentController.<ZipPushDeploy>d__8.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Deployment\PushDeploymentController.cs:line 100 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()" text="There is not enough space on the disk. "/>

<!-- duration: 32ms -->


<step title="Outgoing response" Content-Type="application/json; charset=utf-8" type="response" date="2021-05-12T10:27:44.002" X-AspNet-Version="4.0.30319" Cache-Control="private" x-ms-request-id="b9492f40-ae92-4caf-afd5-ea55830edc6f" Server="Microsoft-IIS/10.0" statusText="Internal Server Error" statusCode="500"/>
<!-- duration: 16ms -->
</step>
```

**Comment by wpitallo** [comment]
Quota for the file share says 5 TiB

**Comment by wpitallo** [comment]
Hey @balag0 just wanted to say thanks for the help. I still think something went wrong there that should not have. I should not have been anywhere close to maxing out the storage accounts. I did manage to fix it though by deleting the old storage account and function and then re-deploying. So its working but not sure where that There is not enough space on the disk. error is coming from?

Thanks again for the help.
