### ISSUE TITLE
Create a learning path for Azure Functions

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#19]
Example: https://azure.microsoft.com/en-us/documentation/learning-paths/virtual-machines/

**Comment by rachelappel** [comment]
Text and links are complete, but I am waiting on where to get the tool to create the tree structure found in learning path docs.

**Comment by SyntaxC4** [comment]
There is a series of guidelines from ACOM on how to create this in the fancy hierarchical drawing that the other items use.

**Comment by SyntaxC4** [comment]
These aren't being shipped in docs... We'll have to review to see if these are something that will eventually come over to docs.

**Comment by sateeshmachineni** [comment]
What is Blocking this Learning Path ?
