### ISSUE TITLE
Support for UPDATE and DELETE to Azure Storage

### ISSUE THREAD

**Issue by jamessdixon** [Azure/Azure-Functions#190]
Currently, AF supports GETS and POSTS to Azure Storage.  For Update and delete scenarios, I have to write to the Azure Storage API directly.  Can this support be implement OOB with Azure Functions?  Where can the community submit that code?

**Comment by lindydonna** [comment]
Sorry for the delay in responding. Contributions can be made to the Azure WebJobs SDK (which are used under the covers by Functions). See https://github.com/Azure/azure-webjobs-sdk

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1131
