### ISSUE TITLE
Azure Function times out in 5 minutes

### ISSUE THREAD

**Issue by syedyakoobali** [Azure/Azure-Functions#1901]
Greetings

I have deployed an Azure function with App Service Plan. It gets timedout in 5 minutes. Is there anyway he can set the timeout to unlimited.

**Comment by jedjohan** [comment]
Consumption plan ? then max execution time is 10 min. Set in host.json: { "functionTimeout": "00:10:00" }. If you need more you will need to leave consumption and go dedicated/premium. See more here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout

**Comment by v-bbalaiagar** [comment]
Hi @syedyakoobali, Let us know if the above information resolves your query, or if you have any further queries.

**Comment by v-bbalaiagar** [comment]
Hi @syedyakoobali, Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.
