### ISSUE TITLE
[Premium] Why is it recommended to disable Health Checks?

### ISSUE THREAD

**Issue by mikebranstein** [Azure/Azure-Functions#1903]
**Question**
Can you expand on why it is recommended to disable Health Checks in Premium Function Apps, as noted in https://docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check#limitations?

It sounds like health checks *could* cause Premium Function Apps to scale unnecessarily, but it's not apparent by reading the docs site.

**Comment by sfgadjo** [comment]
I am interested in an answer to this as well.

**Comment by v-bbalaiagar** [comment]
Hi @mikebranstein, Thank you for your feedback! We will investigate and update as appropriate.

**Comment by v-bbalaiagar** [comment]
Hi @mikebranstein, Health check will not cause Premium Function Apps to scale unnecessarily. The official document means that Premium Functions sites scale quickly, such as scaling more instances, using Health check will cause a lot of unnecessary traffic consumption.
In addition, Premium Functions has its own health check mechanism, so there is no need to enable Health check.
Let us know if you want any further explanation.

**Comment by onionhammer** [comment]
@v-bbalaiagar How would one enable healthcheck of functions with 3rd party dependencies? The docs mention "its own health check mechanism" but where is that documented?
