### ISSUE TITLE
Monitoring tab shows orange exclamation marks but no explanations

### ISSUE THREAD

**Issue by ghost** [Azure/Azure-Functions#191]
The monitoring tab shows orange exclamation marks as status for some function invocations but there is no explanation given on what went wrong. I can't discern a pattern there.

<img width="1105" alt="screen shot 2017-02-27 at 09 17 30" src="https://cloud.githubusercontent.com/assets/20243858/23353957/4fad31cc-fccf-11e6-9d6d-36efa8b934fe.png">

**Comment by panchagnula** [comment]
@stefan-akelius Orange indicated that the function never completed execution (see never finished below)
Also, I noticed that the Logs section is empty in the above screen shot - is this expected for your function? Any exception or error logged , is displayed here.
    public enum FunctionInstanceStatus
    {
        None, // shouldn't be used. Can indicate a serialization error.
        Queued, // Queued from Dashboard but the host has not yet started running it.
        Running, // Started running (first status for non-Dashboard invoked functions).
        CompletedSuccess, // ran to completion, either via success or a user error (threw exception)
        CompletedFailed, // ran to completion, but function through an exception before finishing
        NeverFinished // Had not finished when host stopped running
    }

**Comment by stefan-akelius** [comment]
@panchagnula sorry for getting back to you late. Yes, there are no log outputs in this function. But what does `Had not finished when host stopped running` mean? When does the host exit? Because there are no loose path inside this function and requests to dependent systems contain timeouts so it should not happen that this function does not exit. Some runs just might take a while (already hosted on a S1 App Service Plan)

**Comment by panchagnula** [comment]
@MikeStall , can you clarify @stefan-akelius question above please?

**Comment by wottah** [comment]
This issue is occurring for me as well. No logging, no running time (0ms), and no predictability as to when this issue occurs. 
I see the original poster of this issue deleted his account, but I would still like some answers/resolution regarding this issue.

**Comment by panchagnula** [comment]
@wottah  Sorry you are facing this issue - the orange icon on the UX means the API I returning the status to be 'Never Finished'. Mike  owns the API and can comment more on it. In the meanwhile if you are still seeing this can you share the name of your FunctionApp & Function that reproes this? I can atleast narrow this down to the API or UX issue. Thank you.

**Comment by lindydonna** [comment]
Closing due to lack of repro.

**Comment by ttrace1995** [comment]
Azure functions is incredibly slow and unpredictable. I don't understand how they could screw something up this bad considering they seem to pride themselves on this feature.

**Comment by panchagnula** [comment]
@ttrace1995 sorry that you are having a bad experience with functions, can you please comment if the slow behavior is specific to the Monitoring tab or are there other components that you are having problems with. Please let us know. Thank you!

**Comment by ttrace1995** [comment]
@panchagnula So my node.js function pulls data from a database and sends a chunk of that data to a service bus in json format. The function is doing what its supposed to, meaning that I am seeing the messages appear on the service bus. However in the monitor tab for my function, the logs show all yellow exclamation marks with no log messages. I am using context.done() to signify when the function should be complete too.

**Comment by ttrace1995** [comment]
ok everyone who may be having this same problem. FIRST, make sure you are using context.done() to exit out of your function when exceptions are thrown or if the function completes. SECONDLY, go to Function Apps -> YourFunction -> Platform Features -> Diagnostic Logs  to turn on logging for your function. Why in gods name you have to manually turn this on I have no idea. But this way you can at least see your context.log("xxxxx") statements coming from your function.

**Comment by lindydonna** [comment]
Btw, turning on logging is only required if you want logs when you're not in the portal. When not connected to the portal, logging is automatically turned off.

**Comment by Samwise001** [comment]
I'm also having this issue quite a bit. I've got logging turned on, but don't have a context object to play with in c#, so can't do a context.done - is there an equivalent?

**Comment by lindydonna** [comment]
@Samwise001 You should just return a task if you have an async method. Otherwise, just returning from the function will stop it.

Btw, we don't monitor closed issues. In the future, please post on the [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so).

**Comment by sergei3000** [comment]
I have these orange circles too. And there are no logs in this case, while Application Logging is on in my app.
Is there any work being done on this issue?
I think it should be reopened.

**Comment by Sharaz15** [comment]
same issue. have an automated email sending function set up to execute every day. noticed it hadn't sent any recently so went on to it, status showed as blue dots, duration showed as some milliion ms (which worked out to be 50 hours) - so it started when it was supposed to, two days ago, but no logs shown or error, which is strange because we have a log near the entry point. 

I then manually triggered and it worked fine, also worked fine locally on my machine.

returned to it today and it had a status of exclamation mark and duration 0ms, still no logs.
