### ISSUE TITLE
[Premium] HttpTrigger AzureFunction started failing with 503 Service Unavailable after 230 seconds

### ISSUE THREAD

**Issue by sureshtadisetty** [Azure/Azure-Functions#1914]
**Describe the bug**
HttpTrigger AzureFunction failing with 503 Service Unavailable after 230 seconds. 
This used to work till last week with out functionTimeout setting, take ~20mins to complete request. Request your help to identify what's changed.
It's failing now even with functionTimeout setting.

AzureFunction execution id:
2021-05-26T11:21:29.262 [Information] Executing 'OnInt***' (Reason='This function was programmatically called via the host APIs.', Id=b0dd7119-1a5e-4637-8728-ff40f59bf80d)
Region: WestUS

**Comment by v-bbalaiagar** [comment]
Hi @sureshtadisetty, Thank you for your feedback! We will investigate and update as appropriate.

**Comment by v-bbalaiagar** [comment]
Hi @sureshtadisetty, This would require investigation. Can you open a support incident as this is impacting the production site.

**Comment by v-bbalaiagar** [comment]
Hi @sureshtadisetty, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
