### ISSUE TITLE
How to get Query Parameters from HttpRequestData

### ISSUE THREAD

**Issue by tomaustin700** [Azure/Azure-Functions#1920]
Hi,
I'm looking at moving a .NET Core 3.1 HTTP Trigger function to .NET 5 and struggling slightly with the migration when it comes to getting query parameters. Previously Query Parameters could be read by doing the following:
```csharp
req.Query["parameter"];
```
However now that `HttpRequest` has been replaced by `HttpRequestData` this is no longer possible. I can't seem to find a way to read Query Parameters using `HttpRequestData` at all. Would you be able to document how to do this please? Or if you can point me in the right direction I'll happily modify the documentation to show this and submit a PR.

Thanks

**Comment by jedjohan** [comment]
Hello, dont know if it is "correct", but I am getting the parameters with this:

`var name = executionContext.BindingContext.BindingData["name"];`

**Comment by v-bbalaiagar** [comment]
Hi @tomaustin700, Let us know if the above information resolves your query, or if you have any further queries.

**Comment by tomaustin700** [comment]
Hi @v-bbalaiagar, if getting it from `BindingData` is the recommended way of doing it then I think my question has been answered. Feel free to close this if that's the case. Thanks

**Comment by v-bbalaiagar** [comment]
Hi @tomaustin700, With the current implementation of HttpRequestData, your code to retrieve queries as a dictionary would be:

HttpUtility.ParseQueryString(req.Url.Query); // work with the dictionary 
Or
context.BindingContext.BindingData["myquery"]; // direct access to the dictionary.

Closing this issue as `Binding Data` is the recommended way here. Please feel free to reach back to us in case of any further queries related to this issue.

**Comment by Manthazar** [comment]
> Hi @tomaustin700, With the current implementation of HttpRequestData, your code to retrieve queries as a dictionary would be:
> 
> HttpUtility.ParseQueryString(req.Url.Query); // work with the dictionary Or context.BindingContext.BindingData["myquery"]; // direct access to the dictionary.
> 
> Closing this issue as `Binding Data` is the recommended way here. Please feel free to reach back to us in case of any further queries related to this issue.

I am not understanding the recommendation: 
- HttpUtility doesnt return a dictionary, but a NameValueCollection -which in particular doesn't have a try get value, nor can be converted to a dictionary via Linq. Most importantly you cannot determine whether a parameter is missing or having null value -except you iterate over 'Keys' -which then defeats the purpose of a dictionary.
- BindingContext.BindinData["Query"] doesn't neither return a dictionary, but the json representation of it. This leads an effort of deserialization into a usually case sensitive dictionary -except we somehow work around it.

For an basic capability of Http -this is a lot of work to be done outside of the framework. Hence, this looks to me more like a missing feature than a good recommendation of an alternative path.

**Comment by tomaustin700** [comment]
@Manthazar if you're using .NET 6 you can just go back to using

`req.Query["parameter"];`
