### ISSUE TITLE
Port 7071 is unavailable when debugging locally

### ISSUE THREAD

**Issue by trailmax** [Azure/Azure-Functions#1921]
I had previous function execution crashing and burning and it probably did not have a chance to clean up. Unfortunatley can't repro this easily - last time this happened when I started .Net 5-based function to debug in Visual Studio, but aborted starting process before it managed to start.
And all consequential attempts to start functions failed with error:
```
Port 7071 is unavailable. Close the process using that port, or specify another port using --port [-p].
```
I've checked ports in use and there is nothing: `netstat -aon | findstr ":7071"` - just returns nothing. There are no processes open that takes that port. 

I've tried starting functions with the other port:
```
func start --dotnet-isolated-debug --port 7072
```
And got the same error: `Port 7072 is unavailable. Close the process using that port, or specify another port using --port [-p].` And surely there are no processes that use that port. 

The only way to get this resolved is a PC reboot, but I'm not a fan of this.

**Comment by v-bbalaiagar** [comment]
Hi @trailmax, Thank you for your feedback! Checking this internally for any other workarounds.

**Comment by v-bbalaiagar** [comment]
Hi @trailmax, Please try the following steps:

![image](https://user-images.githubusercontent.com/74654421/121566589-48e85900-ca3b-11eb-8da3-32466dfd4df3.png)

Right click and select properties:

![image](https://user-images.githubusercontent.com/74654421/121566723-6ae1db80-ca3b-11eb-8d8c-f755df2b07cd.png)

Enter the following in the Application arguments box on the right side of debug:

`host start --pause-on-error --port 5860`

![image](https://user-images.githubusercontent.com/74654421/121566892-9795f300-ca3b-11eb-9fea-9cd2b2b03b63.png)

You can specify an alternate port to use aside from the default.

**Comment by v-bbalaiagar** [comment]
Hi @trailmax , Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.
