### ISSUE TITLE
Make HTTPS requests appear as HTTPS for HTTP triggers on Linux dedicated/premium/(consumption?)

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/Azure-Functions#1926]
Discussion: https://github.com/Azure/Azure-Functions/discussions/1927

Web apps frontends terminate SSL requests on the frontend. On the Windows platform, we have an IIS module that looks for headers populated by the frontend to "rewrite" the request as HTTPS. We do not do that on the Linux dedicated/premium offerings, and I am unsure about consumption.

### Motivation
From the client perspective, the request is HTTPS, so the HTTP trigger should also treat the request as HTTPS.

### Impact
I don't believe many customers will be relying on the fact that their request looks like HTTP instead of HTTPS, but if so, this could break customers relying on this behavior.

### Compat-mode support
Could be a flag in the host.json.

### Alternatives
I don't know of any alternatives.

### Detection
I don't believe that we could easily detect this, because we would have to know if customers have written custom code around the HTTP request looking like HTTP instead of HTTPS.

### Support
I don't believe their would be a large support burden.

### Documentation
We may want to add some notes to the HTTP trigger documentation.

### Components impacted
It should just affect the host.

### Performance
There may be a very small perf overhead on each HTTP request to look for the forwarded headers from the frontends and update the protocol accordingly.

**Comment by brettsam** [comment]
https://github.com/Azure/azure-functions-host/issues/6602

**Comment by brettsam** [comment]
Closed with https://github.com/Azure/azure-functions-host/pull/7629
