### ISSUE TITLE
Many connection time out in Azure Function in a short amount of time and very little call stack information

### ISSUE THREAD

**Issue by CarlosOnline** [Azure/Azure-Functions#1928]
Many connection time out errors in a short burst within an Azure Function.  This has been happening pretty frequently over the last week.

There is almost no call stack.  And very little diagnostic information available.
I suspect the connection timeout is happening while trying to process a QueueTrigger function.

1. Can you please provide more diagnostic information.  For example can you specify what operation was being attempted.  Which endpoint / function was not completed because of the error?

2. Is the storage account really going down frequently?  It seems that its not very reliable, nor 24/7 availability.

6/4/2021, 9:54:27 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
6/4/2021, 9:54:25 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 9:54:23 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 9:54:23 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:51:33 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:51:33 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:51:29 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:51:29 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:41:55 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:41:55 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:41:53 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:41:51 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:22:52 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:22:52 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:22:52 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:22:50 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:12:56 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:12:54 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:12:54 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 4:12:52 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 3:42:41 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 3:42:41 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 3:42:39 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 3:42:37 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 3:11:51 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 3:11:51 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;
6/4/2021, 3:11:48 AM | &nbsp; | Connection timed out | &nbsp; | company-optimize-fa | Connection timed out | System.Net.Sockets.SocketException | Microsoft.Azure.Storage.StorageException | System.Net.Sockets.SocketException | &nbsp; | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw | Microsoft.Azure.Storage.Common, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 | Microsoft.Azure.Storage.Core.Executor.Executor+&lt;ExecuteAsync&gt;d__1`1.MoveNext | &nbsp;

**Comment by v-anvari** [comment]
Hi @CarlosOnline , Can you  provide us with the repro steps and share your app name privately 
[Sharing Your Function App name privately · Azure/azure-functions-host Wiki (github.com)](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by CarlosOnline** [comment]
Did option 2:

https://xxx-optimize-fa.azurewebsites.net/api/e620ba98-aca6-435f-adec-d9055ab9451c

UTC: 2021-06-08 03:30:42.484

**Comment by v-anvari** [comment]
Hi @CarlosOnline , Thank you for the information, can I have the region as well

**Comment by CarlosOnline** [comment]
Yes it's west Europe

**Comment by v-anvari** [comment]
Hi @CarlosOnline , I have checked the backend logs and looks like there is a configuration mismatch, I can't confirm unless I can reproduce the situation. Can you share the repro steps.

Also, Can you share some more details about the project

**Comment by v-anvari** [comment]
Also, The since we see the exception - System.Net.Sockets.SocketException. Please check if the communication is proper and if any authentication is missing. A support request can help you for this case, as they will be able to help you identify these errors for your function App.

**Comment by CarlosOnline** [comment]
I stopped using QueueTrigger and rolled my own polling logic.  Problem went away.  What configuration do you mean?

**Comment by v-anvari** [comment]
Hi @CarlosOnline , Thank you for the feedback, by the errors and exceptions, it looked like a configuration was over-ridden, I can't confirm what configurations unless I can reproduce the issue. I couldn't reach your function's backend logs, it says it is not found. 

We are glad to hear that you could find a solution. Do you want us to further look into this issue

**Comment by CarlosOnline** [comment]
For other users this issue was not fixed.  The solution was to not use QueueTrigger since the code will shutdown the Azure Function if it can't connect to the storage account.  Writing my own queue polling code work.   It seems there is no interest in fixing the QueueTrigger so I recommend not using it.

**Comment by v-anvari** [comment]
Hi @CarlosOnline , Thank you for the feedback, we will be happy to help you. Can you provide the repro steps to reproduce the error, with the source code that you are using. This will help us understand the cause of the error.
