### ISSUE TITLE
content destroyed after WEBSITES_ENABLE_APP_SERVICE_STORAGE = true

### ISSUE THREAD

**Issue by chtourou-youssef** [Azure/Azure-Functions#1934]
I have a docker container with a php app inside (custom image)

The app is up and running without problems - with WEBSITES_ENABLE_APP_SERVICE_STORAGE==false.

If i change this setting to true then the content of /home/site/wwwroot is completly deleted

Any idea ?

WITHOUT mount or WEBSITES_ENABLE_APP_SERVICE_STORAGE everything is working....

any help/idea is welcome

regards

**Comment by balag0** [comment]
The content is not deleted, it is just hidden. Removing the app setting should make the content visible again
More details 
https://docs.microsoft.com/en-us/azure/app-service/faq-app-service-linux#custom-containers

When using custom images, that setting should be false. Any reason you are setting it to true?

**Comment by balag0** [comment]
Instructions are for webapps but I think it should work for functionapps as well. Haven't personally used it with custom images but you can give it a try
https://docs.microsoft.com/en-us/azure/app-service/configure-connect-to-azure-storage?pivots=container-linux

**Comment by chtourou-youssef** [comment]
this options shouldn't work without adding mounted volume ?

**Comment by chtourou-youssef** [comment]
thanks .

**Comment by v-bbalaiagar** [comment]
Hi @chtourou-youssef, Let us know if the above information resolves your query, or if you have any further queries.

**Comment by v-bbalaiagar** [comment]
Hi @chtourou-youssef, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
