### ISSUE TITLE
Azure Function : Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBTriggerListener' for function 

### ISSUE THREAD

**Issue by rahul230691** [Azure/Azure-Functions#1935]
I've created a CosmosDBTrigger Azure function, which is hosted on Azure cloud stops automatically and never re-triggered again for 2 days even inserting new data into cosmos container. After 2 days when I went to check function in Azure portal whether it has not been stopped. As soon as I opened function window in portal, function triggered automatically. Not sure what happened. I have checked logs into Azure ApplicationInsights and found below logs -

"Draining invocations from language worker channel completed. Shutting down 'RpcFunctionInvocationDispatcher'"
"Stopping JobHost"
"Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBTriggerListener' for function"
"Job host stopped"
"Disposing ScriptHost."
"Disposing FunctionDispatcher"
Important thing to point here few seconds ago, this function processed some data.

host.json

```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Trace"
    },
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  }
}
```

Project file

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.18.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.14" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Thanks

**Comment by v-bbalaiagar** [comment]
Hi @rahul230691, Thank you for reaching out to us, checking internally on this issue.

**Comment by rahul230691** [comment]
@v-bbalaiagar any update on this plz?

**Comment by v-bbalaiagar** [comment]
Hi @rahul230691, Could you please give us the function app details privately by following the below link -  https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by v-bbalaiagar** [comment]
Hi @rahul230691, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
