### ISSUE TITLE
Document http $return / output binding

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#194]
I was answering http://stackoverflow.com/questions/42548199/azure-function-not-returning-response-through-context-res and I wanted to point to doc explaining this. However https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node doesn't cover any of this, nor does it mention $return.

**Comment by lindydonna** [comment]
@rachelappel This is another good one for the C# developer reference article https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp

**Comment by lindydonna** [comment]
$return is documented for JavaScript now. Documentation for C# just added here: https://github.com/Microsoft/azure-docs-pr/pull/14242
