### ISSUE TITLE
Azure Functions reverts settings after several seconds after their changes

### ISSUE THREAD

**Issue by Alessar** [Azure/Azure-Functions#1941]
We have a script to make some deployments related to the `Azure Functions`.
In some cases, the script should change settings and update it on the Azure portal like this:
```
$appSettings = @{}
$appSettings.$SomeName = $SomeValue
Set-AzureRMWebAppSlot -ResourceGroupName $rgName -Name $afName -Slot $slot -AppSettings $appSettings
```
**Expected**:
Application settings should be changed on Azure Functions according to the latest provided values.
**Actual**:
Application settings were not changes on Azure Functions.
**Details**:
It is strange but according to the logs from the Azure portal, settings were changed to the latest values.
But immediately after that in 2-5 seconds settings were reverted back to the previous values.

What workarounds we already tested:
```
Stop-AzureRMWebAppSlot ...
Start-Sleep -Seconds 300
Set-AzureRMWebAppSlot ... -AppSettings $appSettings
Start-Sleep -Seconds 300
Start-AzureRMWebAppSlot ...
```
Or like this:
```
Restart-AzureRMWebAppSlot ...
Stop-AzureRMWebAppSlot ...
Set-AzureRMWebAppSlot ... -AppSettings $appSettings
Start-AzureRMWebAppSlot ...
Restart-AzureRMWebAppSlot ...
```
But unfortunately, none of these workarounds don't help to suppress the issue.

**P.S.:**
* Script uses `PowerShell 7` and `Enable-AzureRmAlias` for using old named functions.
* It is a stable issue. It is repeated permanently on the current Azure Functions environment.
* Permissions for changes are good because manual settings editing via the Azure portal works well.

It is a very strange issue, which we found. So fixing or any help to make a workaround will be appreciated.

**Comment by balag0** [comment]
Please share the app name using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2
and the timestamp when the Set-AzureRMWebAppSlot command failed.

**Comment by Alessar** [comment]
For detecting function in `WEST US` region:
2021-06-30T17:51:39.078 [Information] Executing 'Functions.***' (Id=958938fc-ea9f-4348-9541-8a38201e0b99)
2021-06-30T17:51:45.764 [Information] Succeeded, Id=958938fc-ea9f-4348-9541-8a38201e0b99, Duration=6692ms

Timestamps when settings were changed / settings were reverted back:
`21.06.2021, 17:40:18 GMT+3` / `21.06.2021, 17:40:21 GMT+3`
`23.06.2021, 11:52:13 GMT+3` / `23.06.2021, 11:52:16 GMT+3`
`23.06.2021, 17:31:26 GMT+3` / `23.06.2021, 17:31:28 GMT+3`
`23.06.2021, 20:38:29 GMT+3` / `23.06.2021, 20:38:31 GMT+3`

**Comment by Alessar** [comment]
@balag0 is there any news?
The additional attempt was tested today one more time. The issue still exists.
Settings were changed: `16.07.2021 12:47:20 GMT+3` / Settings were reverted back: `16.07.2021 12:47:22 GMT+3`

**Comment by balag0** [comment]
Thanks. Investigated the repro on 16.07.2021 12:47:20 GMT+3

Looks like there were 2 calls to update settings
2021-07-16 09:47:20.9777603 PUT /appsettings
2021-07-16 09:47:23.4624558 PATCH /config/web

There were no errors with either of the calls. The logs do not contain the values being updates just the fields. So it is difficult to be sure but my theory is the 1st calls update was overwritten by the 2nd PATCH call.

Is the 2nd call expected? Can you try it again without the 2nd call and see if that helps.

**Comment by Alessar** [comment]
@balag0  We have no "second" call. We have only one call of `Set-AzureRMWebAppSlot` function.
The verbose output of that function shows a lot of internal invokes (17 items), but we have no capabilities to change that function.
It is provided by the library which we use. So how we can suppress the "second" call if it exists in the library.

**Comment by balag0** [comment]
Just to rule out any issues with the Cmdlet, could you try the same operation using Azure CLI or some other client and share the timestamp here.

**Comment by Alessar** [comment]
The assumption is that the issue is related to Cmdlet. Attempts to change settings via the Azure portal works well.

**Comment by Alessar** [comment]
@balag0 looks like the issue can be closed.
The issue was in the `Az.Websites 2.4.0` library.
So updating to `Az.Websites 2.8.0` helps to fix the issue.

**Comment by balag0** [comment]
Great. Thanks for the update.
