### ISSUE TITLE
Sendgrid issue

### ISSUE THREAD

**Issue by tnlthanzeel** [Azure/Azure-Functions#1946]
hi, i created a fresh azure function to send email using sendgrid and iim getting this error

![image](https://user-images.githubusercontent.com/18216790/123952155-3e2e3d80-d9c3-11eb-973e-122e868e5109.png)

i took the sample from here https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-functions/functions-bindings-sendgrid.md#asynchronous

**Comment by v-bbalaiagar** [comment]
Hi @tnlthanzeel, Thank you for your feedback! We will try to reproduce this issue and update as appropriate.

**Comment by v-bbalaiagar** [comment]
Hi @tnlthanzeel, Apologies for the delayed response. Can we know what you are giving in the local.settings.json to check further.

**Comment by tnlthanzeel** [comment]
hi  @v-bbalaiagar , i have pasted it below

`{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "AzureWebJobsServiceBus": [redacted]
  }
}`

**Comment by v-bbalaiagar** [comment]
Hi @tnlthanzeel, Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @tnlthanzeel, Apologies for the delayed response, I am able to reproduce the mentioned scenario exactly. I shall discuss this internally and get back to you with the findings.

**Comment by tnlthanzeel** [comment]
thanks for 

> Hi @tnlthanzeel, Apologies for the delayed response, I am able to reproduce the mentioned scenario exactly. I shall discuss this internally and get back to you with the findings.

thanks for the reply. hope this fixes soon

**Comment by v-bbalaiagar** [comment]
Hi @tnlthanzeel, I checked this internally. These are my findings : 

You are missing the setting for the SendGrid API key with the name specified in the attribute. Looking at the example you linked to, the name of the setting used there is CustomSendGridKeyAppSettingName. The platform uses the name used in the attribute to get the value for the SendGrid binding.

Also, the AzureWebJobsSendGridApiKey setting in your local.settings.json file is commented out, meaning it is non-existent as far as your Function goes.

If we use the name of the setting as used in the example, your local.settings.json file should look something like this:

```
{ 
  "IsEncrypted": false,
  "Values": 
  {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true", 
    "FUNCTIONS_WORKER_RUNTIME": "dotnet", 
    "AzureWebJobsServiceBus": " ..." 
    "AzureWebJobsSendGridApiKey": "<YOUR_API_KEY_HERE>"
  }
}
```

**Comment by tnlthanzeel** [comment]
> Hi @tnlthanzeel, I checked this internally. These are my findings :
> 
> You are missing the setting for the SendGrid API key with the name specified in the attribute. Looking at the example you linked to, the name of the setting used there is CustomSendGridKeyAppSettingName. The platform uses the name used in the attribute to get the value for the SendGrid binding.
> 
> Also, the AzureWebJobsSendGridApiKey setting in your local.settings.json file is commented out, meaning it is non-existent as far as your Function goes.
> 
> If we use the name of the setting as used in the example, your local.settings.json file should look something like this:
> 
> ```
> { 
>   "IsEncrypted": false,
>   "Values": 
>   {
>     "AzureWebJobsStorage": "UseDevelopmentStorage=true", 
>     "FUNCTIONS_WORKER_RUNTIME": "dotnet", 
>     "AzureWebJobsServiceBus": " ..." 
>     "AzureWebJobsSendGridApiKey": "<YOUR_API_KEY_HERE>"
>   }
> }
> ```

hi there. thanks for the reply. we just followed the documentation and did accordingly to what the documentation. but did work.
