### ISSUE TITLE
Method not found on HtmlContentBuilder.WriteTo since VS update to 16.10.3

### ISSUE THREAD

**Issue by andyb70** [Azure/Azure-Functions#1948]
We are using dependency Microsoft.NETCore.App version 3.1.0 and since updating our Visual Studio environments to 16.10.3 the following method call is failing within a HTTP triggered function: -

```
Method not found: 'Void Microsoft.AspNetCore.Html.HtmlContentBuilder.WriteTo(System.IO.TextWriter, System.Text.Encodings.Web.HtmlEncoder)'
```

Whilst debugging the code in question the CreateDetail method as shown below does not get call, the above error is raised immediately.

```
private string CreateDetail(TblFormResponseQuestion response)
{
    var htmlContentBuilder = new HtmlContentBuilder();
    using (var writer = new StringWriter())
        {
            _.... add some stuff via htmlContentBuilder.AppendHtml_
    
            htmlContentBuilder.WriteTo(writer, HtmlEncoder.Default);
            return writer.ToString();
    }
}
```
I tested the code in a console application and it works fine, hence the failure only occurs when running within the Azure Function environment.

**UPDATE**
I have compared the version of Microsoft.AspNetCore.Html.Abstraction found in the `\AppData\Local\AzureFunctionsTools\Releases\3.23.5\cli_x64` folder with the version found in my `bin\Debug` folder and they are as follows: -

```
cli_x64: 3.100.1321.11713
debug: 3.100.1020.52004
```

**UPDATE 2**
I decided to create a blank Azure function project and implement the code within that and hey presto it works. I cannot reference the `HtmlContentBuilder` class without installing the specific package `Microsoft.AspNetCore.Html.Abstractions`. However I have noticed that if go to the definition of `WriteTo` in the new project it gives me this: -

```
    #region Assembly Microsoft.AspNetCore.Html.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
    // C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.html.abstractions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Html.Abstractions.dll
    #endregion
```
However in my old project I do not have to add a package to reference the `HtmlContentBuilder` class it simply exists via the same namespace i.e., `namespace Microsoft.AspNetCore.Html` and the location is and version is different: -

```
    #region Assembly Microsoft.AspNetCore.Html.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
    // C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.10\ref\netcoreapp3.1\Microsoft.AspNetCore.Html.Abstractions.dll
    #endregion
```

**UPDATE 3**
The issue seems to be something to do with `Microsoft.AspNetCore.Authentication.JwtBearer` which we do use in a referenced project, this provides access to the `HtmlContentBuilder` class in a dependency that is somehow then not available when deployed.

**Comment by v-anvari** [comment]
Hi @andyb70 , Can we have a complete repro to this issue, it will help us understand and analyze the issue better

**Comment by andyb70** [comment]
I eventually traced it back to some form of dependency version incompatibility which was caused by several different components `Microsoft.AspNetCore.Authentication.JwtBearer` being one. I eventually removed all references to this component and then finally traced an incompatibility to `Serilog.Sinks.AzureBlobStorage` v3.0.1 simply downgrading this to v3.0.0 then rectified the problem.
