### ISSUE TITLE
Contributor can delete Function App but documentation is stating this capability only for Owner

### ISSUE THREAD

**Issue by azbpa** [Azure/Azure-Functions#1949]
As the documentation states here https://docs.microsoft.com/en-us/azure/azure-functions/security-concepts#user-management-permissions only the Owner role should be able to delete a Function App.

> Functions supports built-in Azure role-based access control (Azure RBAC). Azure roles supported by Functions are Contributor, Owner, and Reader.
> 
> **Permissions are effective at the function app level. The Contributor role is required to perform most function app-level tasks. Only the Owner role can delete a function app.**

However, in my tests I granted an identity the Contributor role at Function App scope but could still delete it (which is at the end not intended for my use case). 

So, is this a bug in the service or documented wrong? How can I achieve that a Contributor cannot delete a Function App?

**Comment by v-anvari** [comment]
Hi @azbpa , Thank you for reaching out to us, a contributor should be able to delete the Function App, I am able to delete it with the contributor access.

![image](https://user-images.githubusercontent.com/66122429/124595640-e4c08580-de7e-11eb-9c0c-ed9c0ca207b0.png)

Transferring this issue to docs repository for further corrections if required.

**Comment by v-anvari** [comment]
Tracking issue : https://github.com/MicrosoftDocs/azure-docs/issues/77943

**Comment by v-anvari** [comment]
The document https://github.com/MicrosoftDocs/azure-docs/issues/77943 has been updated and merged. Closing this issue as resolved
