### ISSUE TITLE
5 Minute warning

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#195]
Need to add 5 minute limit for Consumption Plan warning here:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale

**Comment by davidebbo** [comment]
Tracked by #188

**Comment by ggailey777** [comment]
We probably should document all of the host.json settings in the main docs and not just the wiki, don't you think?

**Comment by davidebbo** [comment]
@ggailey777 this issue was closed as dup. Please add any context to the active one instead. Thanks!
