### ISSUE TITLE
Failed to create default: Encountered an error (InternalServerError) from host runtime.

### ISSUE THREAD

**Issue by makokui** [Azure/Azure-Functions#1950]
Hi, I have created new Azure Function from Azure portal. When I click 'renew key value' of 'default', the 'Failed to create default: Encountered an error (InternalServerError) from host runtime.' can be seen and failed to update the default 'App key'.

Issue:
Cannot update App key.

Repro steps:
1. Create Azure Function following the instructions (use service endpoints) - https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network
2. Add NSG 'Deny all outbound internet from vnet'. 
![image](https://user-images.githubusercontent.com/19471946/124704895-c9fa1980-df2f-11eb-9590-be15046090c5.png)
3. Click 'Renew key value'
![image](https://user-images.githubusercontent.com/19471946/124705071-07f73d80-df30-11eb-86b1-83309e7e5c79.png)
4. Then the error occurrs
![image](https://user-images.githubusercontent.com/19471946/124705492-b4d1ba80-df30-11eb-8d2c-0cd94c4cd502.png)

If I drop NSG  'Deny all outbound internet from nsg', the 'Renew key value' can success. Hence, I think it is necessary to allow some IP or service tags for successful execution. However, there are no information on this.

I want to limit access destinations as much as possible without allowing all Internet access.
Could you please clarify the connection destinations that should be allowed?

**Comment by v-anvari** [comment]
Hi @makokui , I tried to re-produce the issue, but my key value was renewed without any issue. 

Here are my repro steps:

- Create a Vnet and subnet
- Create a NSG and add the security rule
- Integrate the vnet with the Function App.
- Renew the key value for Default app key

All resources created within the same location, also I'm using a Premium plan for my Function App. Can you tell me if I am missing any step to repro the error

![image](https://user-images.githubusercontent.com/66122429/124747895-13eafb80-df40-11eb-952b-85ea9037440d.png)

![image](https://user-images.githubusercontent.com/66122429/124747932-1f3e2700-df40-11eb-9987-c173053e58e9.png)

**Comment by v-anvari** [comment]
Also, you can find more information regarding Network groups in the below links

- [Tutorial: Control Azure Functions outbound IP with an Azure virtual network NAT gateway](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-nat-gateway)
 
- [Azure Functions networking options](https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options)

**Comment by makokui** [comment]
Hi @v-anvari , Thank you for the comment. I found some differentiation. The correct steps is as follows.

1. Create a Vnet and subnet.
2. Allow Service endpoint of 'Microsoft.Storage' on the subnet.
3. Create a NSG and add the security rule, 'Deny all outbound internet from NSG',
4. Create new Function App on App Service Plan and new Storage account.
5. Integrate the Vnet (Regional Vnet Integration) with the Function App.
6. Enable access restriction of Storage, Storage only allow the Vnet Integration subnet.
![image](https://user-images.githubusercontent.com/19471946/124750986-16118200-df61-11eb-89ed-28a108a9d5d9.png)
7. Create a file share in the Storage account which was created as step 4.
8. Update the Application Settings under Configuration for the Function to the following:
   AzureWebJobsStorage: not change.
   WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: Copy from AzureWebJobsStorage
   WEBSITE_CONTENTSHARE: Set the same name as step 7
   WEBSITE_CONTENTOVERVNET: 1
   WEBSITE_VNET_ROUTE_ALL: 1
   WEBSITE_DNS_SERVER: 168.63.129.16
The above step is referred the article - https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network
9. Renew the key value for Default app key.

**Comment by v-anvari** [comment]
Thank you for the details, I shall try to reproduce the above steps and update the findings

**Comment by v-anvari** [comment]
Hi @makokui , I followed the above steps and I was able to reproduce the error, while I created a new NSG rule. Also, the host keys were missing because of the reason mentioned here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account#storage-account-is-inaccessible. 

I kept the app settings as it is as mentioned here https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network. Well this time I dint create a new rule in NSG, and this time I could renew the Host keys. 

As per the below statement, all the outbound traffic goes through VNET. Do you want to specify only the internet access instead of any, in the NSG rules?

<html>
<body>


WEBSITE_VNET_ROUTE_ALL | 1 | Forces all outbound traffic through the virtual network. Required when the storage account is using private endpoint connections.
-- | -- | --



</body>
</html>

![image](https://user-images.githubusercontent.com/66122429/124803585-ecfbec00-df76-11eb-8432-a9f3319f9cc7.png)

**Comment by makokui** [comment]
Hi @v-anvari , Thank you for the confirmation repro.

In my thought, Azure Storage restriction settings are appropriate because the issue only occurs when I add the NSG settings, 'Denly all outbound traffic to the internet'.
The flow is here:
![image](https://user-images.githubusercontent.com/19471946/124845533-e484cf00-dfd1-11eb-9cd7-58955c4f2fbd.png)

If NSG settings remove, the request will be success. Therefore, I think that Function needs some kind of outbound traffic. 

I would like to know what kind of traffic I need to allow in order to limit the traffic to the Internet as much as possible. Could you please clarify that?

**Comment by v-anvari** [comment]
Hi @makokui , Apologies for the delay, yes, you are right, even I had the error only while blocking internet. I was checking this internally with the function team, but this question is more related to the networking team. In my thoughts, this scenario is blocking the traffic at the gateway level, but, we are not sure about the possibilities here. We suggest you to submit a support request, it will be easier to transfer the issues between the right teams.
