### ISSUE TITLE
HTTP 404 on first call

### ISSUE THREAD

**Issue by askpatrickw** [Azure/Azure-Functions#1951]
When an azure function has not been used for a while, you get a 404 on the first call.

**Expected**
Always available API.

**Observed**
Confusing behavior which wrongly indicates a service outage.

**Comment by v-bbalaiagar** [comment]
Hi @askpatrickw, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @askpatrickw, Could you please provide us the invocation id of the error and time stamp to get the logs and check the cause.

**Comment by askpatrickw** [comment]
No, I cannot sorry.
