### ISSUE TITLE
'LinuxDynamicWorkersNotAllowedInResourceGroup' error occurs when trying to have an app service and a linux function app in same resource group

### ISSUE THREAD

**Issue by onionhammer** [Azure/Azure-Functions#1952]
This seems like a relatively common need for an unsupported scenario;

You want a web app (on linux), and you want a function app (on linux).

However, if you have a linux app service for webapps, you cannot create a dynamic linux app service in the  same resource group:

```json
      {
        "code": "ValidationForResourceFailed",
        "message": "Validation failed for a resource. Check 'Error.Details[0]' for more information.",
        "details": [
          {
            "code": "LinuxDynamicWorkersNotAllowedInResourceGroup",
            "message": "Linux dynamic workers are not available in resource group yourResourceGroup. Use this link to learn more http://go.microsoft.com/fwlink/?LinkId=825764."
          }
        ]
      }
```

https://github.com/Azure/Azure-Functions/wiki/Creating-Function-Apps-in-an-existing-Resource-Group

Are there plans to eventually fix this limitaiton?

**Comment by balag0** [comment]
Yes, There is work in progress to remove this limitation. But no ETA yet.

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided, please find any further updates in  the App Service Announcements issues page: https://github.com/Azure/app-service-announcements/issues

**Comment by petrkoutnycz** [comment]
How does this look like please at the moment? This is really awkward limitation :-/

**Comment by GeorgDangl** [comment]
We also just hit this yesterday. Not a big deal, since it's easy to workaround, but makes deployment a bit more complicated and ugly. Is there any current status for this?

**Comment by shakthifuture** [comment]
I am also facing same issue, what is the solution?

**Comment by florinasaveiext** [comment]
In my case, I just choose to use Windows Function Apps since it didn't really matter to me but I did want to keep the AppService Plan on Linux.

**Comment by elier** [comment]
I encountered this issue today while deploying with bicep.  I'm creating 2 service plans with 'Microsoft.Web/serverfarms@2022-09-01', one for an App Service, and another for 2 Functions App.
I managed to make it work by changing the order of the creation. 

- I create the service plans first, and the Function App's service plan is also created before the App Service plan.
- Then, I create the App Service at the very end, and it works.

**Comment by Sharparam** [comment]
We are encountering this as well, but strangely it works in one resource group but not the other.

They are both set up the same way using a bicep file.

**Comment by onionhammer** [comment]
Odd to close this issue years before it's actually available

**Comment by ggirard07** [comment]
@bhagyshricompany any chance to look back into this?
In my case, the same ARM template is working fine in one subscription, while it fails with `Requested features 'Dynamic SKU, Linux Worker' not available in resource group Sandbox-BuilderRestoreBkp2. Please try using a different resource group or create a new one.` in another subscription...
I do have both app service plan for function apps in the template, one is Y1 Linux and the other is EP1 Linux, both in East US 2.

**Comment by jammastergirish** [comment]
Seems this is still not fixed? Seems very strange to have to create a new resource group for a function if there's an existing app service?

**Comment by BorgPrincess** [comment]
Apparently, it is enough that _the first plan created_ was not a Y1, no matter whether any non-Y1 plans still exist.

Which makes IaC _really_ ugly, as we now need to make sure _what order_ things are deployed in.
One of the very things we are using IaC to avoid.

Also, closing an issue while the problem persists - no. Just... no.

**Comment by roblohmann** [comment]
@v-anvari closing this issue is wrong as the problem still persists. Any ETA on an proper solution?

**Comment by tgoodlock-ai** [comment]
I just ran into this issue as well.  What is the current ETA?

**Comment by CCT-JackUnderwood** [comment]
Sad to see this is still an issue! For the love of Azure!!

**Comment by AartBluestoke** [comment]
> Sad to see this is still an issue! For the love of Azure!!

i'd suggest raise a new issue pointing at this one - it hasn't been re-opened in 2 years since it was closed. things have moved enough it "might" be a different root issue, especially since the first response was "we are working to fix this"
