### ISSUE TITLE
Azure functions .net 5.0 isolated ( extentions.json do not generated)

### ISSUE THREAD

**Issue by GleamStar** [Azure/Azure-Functions#1958]
I did everything as in doc https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-developer-howtos?tabs=browser&pivots=development-environment-vs
When I try to run it does not generate  extentions.json and does not run. 
![image](https://user-images.githubusercontent.com/10872587/125095929-55fd7400-e0dd-11eb-8a46-ea08f479fa79.png)
Or it runs but does not see any functions
![image](https://user-images.githubusercontent.com/10872587/125096101-7b8a7d80-e0dd-11eb-9716-7ffdb552c04c.png)

**Comment by v-bbalaiagar** [comment]
Hi @GleamStar, Thank you for the feedback, we will reproduce this issue and update as appropriate

**Comment by v-bbalaiagar** [comment]
Hi @GleamStar,  I have tried to reproduce the mentioned scenario exactly. Below are the repro steps:

 1. Created function project with HTTP trigger function and set the Authorization level to Anonymous.

![image](https://user-images.githubusercontent.com/74654421/125280846-28aa0380-e333-11eb-9aa3-0a18ce51ff38.png)


When I debug the app, The function get executed successfully as below.

![image](https://user-images.githubusercontent.com/74654421/125281487-e6cd8d00-e333-11eb-8b41-e14a67ea1430.png)

When I hit the URL A "Welcome to Azure Functions!" message is displayed- http://localhost:7071/api/HttpExample




Let us know if I am missing a step.

**Comment by GleamStar** [comment]
Hi  . After a lot of tries, I solved the problem. I've cleaned up the .nuget folder at my computer and it helps.

**Comment by v-bbalaiagar** [comment]
Hi @GleamStar, Closing this issue as resolved, please feel free to reach back to us in case of any further queries related to this issue.
