### ISSUE TITLE
Add a way to trigger functions from my Azure portal dashboard

### ISSUE THREAD

**Issue by atrauzzi** [Azure/Azure-Functions#196]
I think it'd be neat if there was a type of button that could be used to call azure functions on click from the dashboard.

Prompting for values might be a consideration.

Would be extra neat if these buttons could be shared somehow as part of a resource deployment.

**Comment by lindydonna** [comment]
This is already supported in the Test tab in the Functions portal. Are you looking for something beyond that?

**Comment by atrauzzi** [comment]
What I had in mind was more like binding a function to a tile in my Azure dashboard.

**Comment by lindydonna** [comment]
Unfortunately, this isn't possible, since tiles have to conform to the Azure Portal extension model. The Functions experience is an Angular 2 web app, and we don't plan to create this kind of extension.
