### ISSUE TITLE
Error: A ScriptHost error has occurred when run azure function

### ISSUE THREAD

**Issue by vanhuynhnguyen2001140321** [Azure/Azure-Functions#1960]
I have a problem with Host, i tried some ways, but the problem is not solved.
I was created a sample project on Visual 2019 and run it, but there is a problem about Host as shown in the picture below. Please any one help me resolved this problem?
![11](https://user-images.githubusercontent.com/38435142/125390714-8559fc80-e3cd-11eb-85f5-114da71318be.png)
![22](https://user-images.githubusercontent.com/38435142/125390720-8723c000-e3cd-11eb-994f-0304d68f89ed.png)
![33](https://user-images.githubusercontent.com/38435142/125390724-8723c000-e3cd-11eb-8364-cf96e5cf5b73.png)

**Comment by v-bbalaiagar** [comment]
Hi @vanhuynhnguyen2001140321, Thank you for the feedback, we will reproduce this issue and update as appropriate.

**Comment by vanhuynhnguyen2001140321** [comment]
> Hi @vanhuynhnguyen2001140321, Thank you for the feedback, we will reproduce this issue and update as appropriate.

Yes, thanks for the team.

**Comment by v-bbalaiagar** [comment]
Hi @vanhuynhnguyen2001140321, I have tried to reproduce the mentioned scenario exactly. Below are the repro steps:

1.Created function project with Timer trigger function.

![image](https://user-images.githubusercontent.com/74654421/126334646-dffb6b35-ed5d-4811-bf8d-ac18b117b007.png)

![image](https://user-images.githubusercontent.com/74654421/126334999-e32b5dfb-8d81-46cc-8abd-f419db619111.png)

When I debug the app, The function get executed successfully as below.

![image](https://user-images.githubusercontent.com/74654421/126335198-98e2c610-8580-44d7-9f36-ae90ac26546c.png)


Let us know if I am missing a step here.

**Comment by v-bbalaiagar** [comment]
Hi @vanhuynhnguyen2001140321, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
