### ISSUE TITLE
Questions on Access Restrictions and NSG rules for VNet integrated Function App

### ISSUE THREAD

**Issue by JamesDuggan** [Azure/Azure-Functions#1961]
I have two questions on Function App (premium) VNET integration.

When securing the the Function App via Access Restrictions are there service tags that must be configured in order that the function app remains healthy? For example, there is plenty of documentation suggesting the ```AppServiceManagement``` service tag should be allowed, but it remains unclear that it is actually required for a Function App.

Similarly for outbound NSG rules, allowing the ```Storage``` and ```AzureMonitor``` service tags is necessary, but what is the implication of denying the default ```AllowVNetOutbound``` and ```AllowInternetOutbound``` rules?

**Comment by JamesDuggan** [comment]
Appreciate this is potentially a wide question, but really what it boils down to is guidance on the impact of implementing inbound traffic via Access Restrictions and outbound traffic via NSG outbound rules on the the ability (or need) of the underlying VMs to update, and the overall health of the Function App. For a multi-tenant Function App on Premium, the docs are not clear. Thanks

**Comment by JamesDuggan** [comment]
I have bottomed out the behaviour for default ```AllowVNetOutbound```.

Really would appreciate your input on the impact of implementing aggressive inbound traffic restrictions via Access Restrictions such as only allow AzureDevOps, and outbound traffic restrictions via NSG outbound rules that restrict the default ```AllowInternetOutbound``` on the the ability (or need) of the underlying VMs to update, and the overall health of the Function App.

Thanks

**Comment by v-anvari** [comment]
Hi @JamesDuggan , This question is more for the networking team, as this requires 
 change in the Networking behavior. The Networking forum covers all aspects of Networking in Azure, including endpoints, load-balancing, network security, DNS, Traffic Manager, virtual networks, and external connectivity. https://feedback.azure.com/forums/217313-networking?category_id=77469. 

As you have mentioned, the documentation is not clear. Can we have the docs link that you are referring to. For any document changes, you can raise a new issue here - https://github.com/MicrosoftDocs/azure-docs/issues/new

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
