### ISSUE TITLE
Enable dependency isolation for Python function apps

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/Azure-Functions#1969]
Discussion: https://github.com/Azure/Azure-Functions/discussions/1976

### Motivation
What is the motivation for the change?
Python customer's has function app that are using the incompatible libraries that will override our worker's dependencies (e.g. protobuf). This feature will mitigate these issues and ensure the customer's code always load from their own .python_packages after worker initialization.

### Impact
How many customers (roughly) would be impacted by this break? If not known, how can we figure it out? This may require host changes to gather metrics.
Number of impacted customers can be queried by "ModuleNotFound" or "ImportError" keywords in FunctionsLogs table.

### Compat-mode support
We'd like to enable compat-mode support for every breaking change. This may not be feasible in reality, but each proposal should include a plan to switch back to the previous behavior with a feature flag. This requirement will be evaluated on a case-by-case basis.
If customer's are impacted by this upgrade, turning off the feature flag PYTHON_ISOLATE_WORKER_DEPENDENCIES should mitigate the issue.

### Alternatives
Were any alternatives discussed? Is there any way to do this without a break?
Because this is a contract between Python worker and customer's code, and most of them don't have context in Python worker. It is unreasonable to ask our customer to change all their apps. This work needs to be done on the Python worker side.

### Detection
Can we detect that a customer is using this when they upgrade from v3? Is there a specific error that can be thrown with a link to migration guidance?
Customer function apps which use this feature will have a initialization message for this process "Applying prioritize_customer_dependencies". If the process completes successfully, it will emit another message "Finished prioritize_customer_dependencies"
All('FunctionsLogs')
| where PreciseTimeStamp >= ago(1d)
| where Source contains ".python."
| where Summary startswith_cs "Applying prioritize_customer_dependencies"
| limit 1

### Support
Will there be any incidents-per-day impact? Who will be the support contact? Does support need to be notified of this change? (SPOT)
If there's an increasing number of **ModuleNotFound**, **ImportError**, or **unhandled error in functions worker** in FunctionsLogs summary, @Hazhzeng is the person to contact.

### Documentation
App setting reference needs to be updated for V4 default value.

### Components impacted
What components does this change impact? Examples of areas (this list may not be exhaustive):
        - Worker

### Performance
Does the change have any performance impact? There may need to be some implementation complete before this can be measured.
We tested it during the project prototyping phrase, no significant increase in cold start time for Python apps.

/cc: @AnatoliB @vrdmr @stefanushinardi

**Comment by brettsam** [comment]
This will no longer be considered a breaking change; it will be implemented in v4 and hidden behind a flag.
