### ISSUE TITLE
npm install just hangs

### ISSUE THREAD

**Issue by atrauzzi** [Azure/Azure-Functions#197]
When I go to kudu to perform an npm install for my nodejs based functions app, I get the feeling like things just aren't working or going extremely slowly:

![image](https://cloud.githubusercontent.com/assets/115199/23580343/6f3761d0-00c5-11e7-9c43-bd5127b6c81b.png)

Screen sits like this seemingly indefinitely.  I mean, long enough that I strongly suspect something is wrong as nobody should be expected to wait this long doing an npm install.

**Comment by lindydonna** [comment]
This is probably a limitation of Azure Files, which has latency with multiple small files. Consider using a webpack tool as a workaround: https://github.com/christopheranderson/azure-functions-pack

**Comment by atrauzzi** [comment]
I've actually been able to come up with a build flow that deploys to app service after gathering everything.  Thanks!

**Comment by facadev** [comment]
@lindydonna Is it also Azure Files that causes Azure Functions to start very slowly? I have Functions that take 100s or even more in cold start, around 6s in warm start (if there is any mechanism I suppose) and 600ms to complete if they are called frequently.

**Comment by lindydonna** [comment]
@facadev Yes, this is a limitation on the Consumption plan, which can cause cold start problems. Webpack will make things much better all around: https://github.com/christopheranderson/azure-functions-pack

**Comment by THEjoezack** [comment]
I've bumped into this a couple times too. Running npm under --verbose ends up freezing the browser so I'm not seeing where it gets hung. (Chrome latest)

Trying to install an individual module now, and it's still hanging (npm install request).
