### ISSUE TITLE
Azure Function to read large file in chunks through http trigger request

### ISSUE THREAD

**Issue by ashgit24** [Azure/Azure-Functions#1970]
Hi
I have an API in Azure function that uses Http trigger to receive data and send that across to the on-prem application. We have the UI front-end where user can upload large file size (no limit) and that would send data in chunks to the API.

I am aware that the limitation of the function App is 100MB and I also see the recommendation for handling large file size is to use Blob Storage. However for synchronous process, we wanted to achieve this through the API (avoiding storing data in blob storage in the intermediate process).

Is there a way how I can receive data in chunks via the Http trigger request? eg: UI -> send data in chunks -> API (uses HttpTrigger) read data in chunks and send data in chunks -> on-prem.

Eg:
public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function,  "post", Route = null)] HttpRequest req,
            ILogger log)

here how do I read data from req in chunks if the sender is streaming data in chunks already ? 
If I read something like below, it works fine as long as the payload is <=100mb and fails with the error "data too large" if it is over 100mb.

_bufferSize = 1048576;
byte[] datapayLoad;
while (dataRead >0){
dataRead = req.Body.Read(datapayLoad, 0, _bufferSize);
....
}

Appreciate your help in this regard.

**Comment by v-bbalaiagar** [comment]
Hi @ashgit24, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @ashgit24, Apologies for the delayed response, Can you please go through here which addresses similar scenario - https://docs.microsoft.com/en-us/answers/questions/471693/azure-function-to-read-large-file-in-chunks-throug.html

Please check and let us know if this helps.

**Comment by v-bbalaiagar** [comment]
Hi @ashgit24, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
