### ISSUE TITLE
Missing Application Insight Logs 

### ISSUE THREAD

**Issue by ponnmohan** [Azure/Azure-Functions#1971]
**Describe the bug**

I have created an Azure Function App that uses ServiceBus Queue triggered which is hosted in Elastic Premium Plan. I have used **Managed Identity** to authenticate the function app with the service bus. In that function, I'm logging service bus queue messages. The number of messages which I sent to the service bus queue has differed from the number of Function App insight logs. And this is seen intermittently. 

Ex. If I sent 1000 messages to the service bus queue, I can see only 991 entries in Function App insight logs.

**To Reproduce**

1. Create an Azure Function App in Elastic Premium Plan.
2. Create a simple service bus queue trigger function that will log a service bus queue message.
3. Create a simple console app that will trigger 1000  messages (with a unique batch Id) to the service bus queue.
4. Go to Function App AppInsights and query in trace where the message contains batch Id
5. Verify the Count.

**Expected behavior**

The number of messages which we send to the service bus queue should be same as the number of Function App insight logs.

**Screenshots**

![image](https://user-images.githubusercontent.com/22073815/125628899-b9588143-1010-4edb-9926-12835b73af7a.png)

![image](https://user-images.githubusercontent.com/22073815/125629072-0d9b380c-8497-4f54-b928-84e2e22c7d16.png)

**Message Simulator (Console App) :**

![image](https://user-images.githubusercontent.com/22073815/125629690-e9c6c181-a5ad-48a7-88f8-99d6f6538162.png)

**Function App:**

![image](https://user-images.githubusercontent.com/22073815/125630410-8898069a-57c8-47b2-9051-2c7c06bd0a4e.png)

Please help me to resolve this.

**Comment by jedjohan** [comment]
Hi, have you tried adjusting the logging in host.json ? Could this be some case of sampling kicking in ?("logging":"applicationInsights": "samplingSettings": )
https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#sample-hostjson-file

**Comment by ponnmohan** [comment]
This works well. Thanks @jedjohan

**Comment by ponnmohan** [comment]
Closing this issue, since provided comment works well.
