### ISSUE TITLE
Proxies Json Backend Uri Forwarding Infinite Loop/Not found

### ISSUE THREAD

**Issue by JagadishLakhini** [Azure/Azure-Functions#1980]
I am Trying to Add Security Headers using Proxies JSON and need to forward the URL to the same func app, when I don't pass the backend uri, the page that I access from forwarding shows an empty page and when I try to pass the backend uri same as the func app, It says infinite loop. 

Tried to add settings like below and With these settings, the main URL stops working and headers added to /api

"matchCondition": {
        "route": "/api/"
      },
      "backendUri": "https://localhost/api/httptriggerC#1",

Help me figure out what needs to be done in this case.

**Comment by v-bbalaiagar** [comment]
Hi @JagadishLakhini, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @JagadishLakhini, Can you provide us with the repro steps so that we can repro it from our end.

**Comment by v-bbalaiagar** [comment]
Hi @JagadishLakhini, Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
