### ISSUE TITLE
Behaviour when maximum number of functions used

### ISSUE THREAD

**Issue by dmathijs** [Azure/Azure-Functions#1981]
Hi,

I tried finding information about what happens if the maximum amount of concurrent functions is called.
Does Azure respond with a specific status code?
Is this documented somewhere? Can I add it?

Thank you!

**Comment by v-bbalaiagar** [comment]
Hi @dmathijs, Thank you for the feedback, checking this internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @dmathijs, We would like to know which trigger are you using because the concurrent invocations we have a slightly different behavior depending on the trigger type.

**Comment by dmathijs** [comment]
Hi,

I'm using the HTTP trigger

Thank you!

**Comment by v-bbalaiagar** [comment]
Hi @dmathijs, There is a distinction between executing the function and accepting the HTTP requests. So when the maximum  number of concurrent functions is reached, the default runtime behavior at that point would be to queue the requests.
This information is documented here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-output#hostjson-settings

**Comment by dmathijs** [comment]
Great thanks!
