### ISSUE TITLE
SCALE_CONTROLLER_LOGGING_ENABLED not showing scale trigger to indicate reason for scale

### ISSUE THREAD

**Issue by markdore** [Azure/Azure-Functions#1982]
### Background
We have a number of function apps sitting within one premium elastic app service plan.  The app service plan is hosted on an EP2 instance.  We originally had performance issues and ascertained this was down to 2 things:

1) We were originally on an EP1 instance
2) We were not setting the 'pre-warmed instances'

I wanted to understand what caused the scaling of the machines in the background as over a small period of time (couple of hours) we were using up to 9 instances under really small load.  I thought this may have been due to CPU utilisation of the EP1 instances but upon upgrading to EP2, CPU is no longer an issue but the behaviour remains consistent.

Please see the below graph showing this behaviour.
<img width="1294" alt="09-07-UAT-Instance-Split" src="https://user-images.githubusercontent.com/49562934/126475715-0f406a2f-91c6-463a-8355-5a6d9a827e91.png">

### What have we done and the problem we see
So, in order to further diagnose this, we turned on "SCALE_CONTROLLER_LOGGING_ENABLED" across all of our function apps.  I was then expecting to review these logs and be told why the scale controller was deciding to scale our instances.

`"SCALE_CONTROLLER_LOGGING_ENABLED" = "AppInsights:Verbose"`

Upon enabling and running some load through our UAT environment, I then ran the following command:

`traces 
| extend CustomDimensions = todynamic(tostring(customDimensions))
| where CustomDimensions.Category == "ScaleControllerLogs"
| where message == "Instance count changed"
| extend Reason = CustomDimensions.Reason
| extend PreviousInstanceCount = CustomDimensions.PreviousInstanceCount
| extend NewInstanceCount = CustomDimensions.CurrentInstanceCount`

This produced the following results, well heres one example but they are the same across the board:

<img width="864" alt="AI-scale-logs" src="https://user-images.githubusercontent.com/49562934/126476308-728547f3-e1d7-42f5-9ce6-9ba361b72c84.png">

As you can see, it doesn't tell us the trigger that caused the scaling so I am still in the dark as to why this behaviour is present.

Thank you for your help in advance

Mark

**Comment by v-anvari** [comment]
Hi @markdore , Thank you for your feedback, Kindly share us the Function App details privately, so that we can check the backend logs for you Application. 
[Sharing-Your-Function-App-name-privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by v-anvari** [comment]
Meanwhile, I shall try to reproduce this scenario on a test Function App.

**Comment by markdore** [comment]
Thank you for your prompt response and apologies for the delay in getting back to you, I have been on annual leave.  Here are the details you require:

2021-08-05T16:42:23.824 [Information] 
Executing 'method' 
(Reason='This function was programmatically called via the host APIs.', 
Id=aedd10b2-a2c3-46e2-ac43-f159729844ed)

This is just one of the function apps that are deployed against our elastic service plan.

**Comment by markdore** [comment]
Hi, just in case the above was missed, hopefully this provides you with the information you require so you can remove the Needs: Author feedback label.  Please let me know if you do need anything else from me

**Comment by v-anvari** [comment]
Hi @markdore , Apologies for missing the comment, I shall check the backend logs and discuss this issue internally as update appropriate

**Comment by v-anvari** [comment]
Kindly, provide us with the region details as well

**Comment by markdore** [comment]
North Europe

**Comment by v-anvari** [comment]
Hi @markdore , I have reproduced the issue, but seems like this issue is specific to HTTP requests or messages that is happening outside the scale controller. I have discussed this issue internally and the team has looked into it. They suspect a bug as the message is incomplete. A bug has been reported to further work on it.

**Comment by v-anvari** [comment]
Hi @markdore , The team has fixed the bug, the issue should probably occur no more. Closing this issue as resolved, please feel free to reach back to us or re-open this issue in case of any queries.

**Comment by markdore** [comment]
Hi @v-anvari - apologies it has taken so long for me to get round to checking this.  I have just logged in and I can't see any changes.  

`
An instance was added due to the following triggers requesting help:
--
`

As you can see, it still just has a blank list of triggers which still gives us no indication as to why this behaviour is occurring?  Could you please re-open this ticket or let me know if there is anything I need to do in order to resolve this?

Thanks

**Comment by v-anvari** [comment]
Hi @markdore , Scale controller logs shows only how the scaling takes place.  There are other queries you can use in the Application insights to view these parameters. A document on this is here https://docs.microsoft.com/en-us/azure/azure-monitor/app/performance-counters. Let us know if this helps.

**Comment by v-bbalaiagar** [comment]
Closing this issue as the required information provided, please feel free to reach back to us or re-open this issue in case of any queries.
