### ISSUE TITLE
Use SAS token to connect to Azure storage

### ISSUE THREAD

**Issue by jaysnanavati** [Azure/Azure-Functions#199]
Hi - I am trying to follow (https://docs.microsoft.com/en-us/azure/storage/storage-dotnet-shared-access-signature-part-1) in order to use a SAS connection for a blob trigger but I get the error message: Microsoft.WindowsAzure.Storage: No table endpoint configured. on the dashboard, please if someone could guide me with this.

Thanks

**Comment by lindydonna** [comment]
You need to provide a connection string with full permissions to the storage account, because tables and queues in the account will also be used.

**Comment by jaysnanavati** [comment]
Thanks! - that makes sense, and I recall from the documentation reading about blob receipts (which would require additional data structures, hence the tables and the queues)
