### ISSUE TITLE
Java 8 stop supporting loading the worker jars 

### ISSUE THREAD

**Issue by amamounelsayed** [Azure/Azure-Functions#1991]
Currently the default for the java worker is loading the java worker jars first then loading the customer jars. This was the solution to not make any break change after shading the java worker jars (note the gson jar is the only one that is not shaded).
The jars is uploaded at https://github.com/Azure/azure-functions-java-worker/tree/dev/lib_worker_1.6.2
There is around 32 jars in the folder.

To switch the order the customer needs to add the application setting FUNCTIONS_WORKER_JAVA_LOAD_APP_LIBS True or 1
https://github.com/Azure/azure-functions-java-worker/issues/381

Note: the jars that loaded first takes presence.

### Motivation
The default jars are on old versions and we do not support any upgrades.

### Impact
There is no evidence or numbers that we can know how much of the customer will get impacted. All java 8 users will get the change. The apps will break is the ones the application depends on any of the mentioned 32 jars and the customer did not add them to be part of their app deployment.

### Compat-mode support
We will not add compact-mode support

### Detection
Can we detect that a customer is using this when they upgrade from v3? Is there a specific error that can be thrown with a link to migration guidance?
Yes the exception will be class not found exception.

### Support
The support team needs to be informed in case the customer app failed to start and guide them for which package it is missing and ask the customer to deploy and upload it.

### Documentation
We may need to document the new behavior of Java worker and deprecate the issue https://github.com/Azure/azure-functions-java-worker/issues/381

### Components impacted
Java worker

### Performance
No expected perf impact.

**Comment by amamounelsayed** [comment]
PR: https://github.com/Azure/azure-functions-java-worker/pull/454

**Comment by kaibocai** [comment]
Notes: with functions v4 rolling out, the default for java 8 will be exactly same as java 11. It will only load customer dependencies by default. No need to set FUNCTIONS_WORKER_JAVA_LOAD_APP_LIBS any more. Azure/Azure-Functions#1991. The pr is #454
