### ISSUE TITLE
Java 11 use single class loader

### ISSUE THREAD

**Issue by amamounelsayed** [Azure/Azure-Functions#1997]
Currently for each function we created in a specific class loader. The impact Static variable appears to be difference for each function even though it's in the same class
https://github.com/Azure/azure-functions-java-worker/issues/412

### Motivation
What is the motivation for the change?
We will need to fix the issue and have the same behavior like java 8

### Impact
We do have a way to know how many java 11 users that will get impacted by this issue. The impacted users will be java 11 users that use static variables. 

### Compat-mode support
We will not add compact-mode support

### Detection
N/A

### Support
We may need to inform the support with the change and explain how azure functions behavior.

### Documentation
N/A

### Components impacted
Java worker

### Performance
No impact

**Comment by amamounelsayed** [comment]
PR: https://github.com/Azure/azure-functions-java-worker/pull/460

**Comment by brettsam** [comment]
PRs to host:
- https://github.com/Azure/azure-functions-host/pull/7721
- https://github.com/Azure/azure-functions-host/pull/7719

**Comment by purijatin** [comment]
I believe this is no longer an issue and has already been resolved. Or does this issue still exist?
