### ISSUE TITLE
Improve Doc for Binder and other advanced scenarios

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#2]
Original issue created by @seanfeldman here: https://github.com/Azure/azure-webjobs-sdk-script/issues/739

See http://stackoverflow.com/questions/39855409/how-do-i-use-binder-to-perform-dynamic-bindings-in-my-c-sharp-function for details, including the blob post Sean wrote :)

**Comment by SeanFeldman** [comment]
Only wrote it to compensate for the missing doco :)
Thank you @mathewc so much for patiently answering my questions.

**Comment by cephalin** [comment]
Improved documentation can be previewed at https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?branch=pr-en-us-216#advanced-binding-at-runtime-imperative-binding.

**Comment by SeanFeldman** [comment]
@cephalin is preview intended for all? Can't access it.

**Comment by cephalin** [comment]
Only for MS employees.

**Comment by SeanFeldman** [comment]
😞

**Comment by cephalin** [comment]
@mathewc Can you please take a quick look at the content and give your feedback so we can close this item? It's live now [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#advanced-binding-at-runtime-imperative-binding).

**Comment by cephalin** [comment]
@mathewc  PING

**Comment by SeanFeldman** [comment]
@cephalin 👍
