### ISSUE TITLE
Could not load file or assembly 'NuGet.Frameworks, Version=3.4.3.0,

### ISSUE THREAD

**Issue by abhi004** [Azure/Azure-Functions#200]
Hi,
Started getting issue with VS 2015 while running the Generic web hook project  in C# .
I am getting below exception 
Could not load file or assembly 'NuGet.Frameworks, Version=3.4.3.0,

**Comment by DKincer** [comment]
Also receiving the same error as of March 7th.

StackOverflow on the issue: https://stackoverflow.com/questions/42673617/cant-local-debug-azure-function-cli-update-march-7th-2017

MSDN: [Report](https://social.msdn.microsoft.com/Forums/en-US/d599889a-8ec7-4213-9b21-2544d6a18f51/visual-studio-tools-for-azure-functions?forum=AzureFunctions)

**Comment by juunas11** [comment]
This was fixed in version 1.0.0-beta.93 of the Azure Functions CLI. VS should ask you to update.

**Comment by lindydonna** [comment]
Yes, thanks @juunas11 for the StackOverflow post and update on this issue!
