### ISSUE TITLE
Update Azure Function resource group restrictions

### ISSUE THREAD

**Issue by Robertj1983** [Azure/Azure-Functions#2002]
This [wiki article](https://github.com/Azure/Azure-Functions/wiki/Creating-Function-Apps-in-an-existing-Resource-Group) lists the restrictions for creating Azure Functions in the same resource group.

Based on the answer to the question [here](https://docs.microsoft.com/en-us/answers/questions/491371/azure-function-resource-group-restrictions.html), the documentation could be updated to reflect the fact that, under any circumstance, one would be able to create Windows Consumption and Linux Consumption Function Apps in the same resource group, which would be in line with the [associated app-service documentation](https://docs.microsoft.com/en-us/azure/app-service/overview#limitations).

**Comment by v-bbalaiagar** [comment]
Hi @Robertj1983, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @Robertj1983, Closing this issue as document issue is opened, Please find the space for further updates - https://github.com/MicrosoftDocs/azure-docs/issues/79332
