### ISSUE TITLE
Publishing functions to function app from Visual Studio does not remove deleted functions

### ISSUE THREAD

**Issue by codebrane** [Azure/Azure-Functions#2009]
After creating a function app in the Azure portal and deploying a locally developed function app in Visual Studio with one function it works as expected.

e.g. TestFunctionApp has one function called TestFunction

After Renaming TestFunction to NewFunction in VisualStudio and re-publishing to the function app in Azure, the function app has two functions:

TestFunction and NewFunction.

There are no references to TestFunction in the Visual Studio project after renaming.

Is there a way to remove non-existent functions from a function app?

**Comment by v-bbalaiagar** [comment]
Hi @codebrane, You can disable functions in the function app as mentioned in the document- https://docs.microsoft.com/en-us/azure/azure-functions/disable-function?tabs=portal#disable-a-function
Please check and let us know if this helps.

**Comment by codebrane** [comment]
thanks for that. I've been disabling them to show they are not relevant but they don't exist so I shouldn't have to disable them. They also propagate through Azure. If I import from the function app to APIM the non existent functions are displayed as options to be imported. Is there a way to remove them entirely from the function app? Removing them from the function app in Visual Studio doesn't remove them from the function app in Azure.

**Comment by codebrane** [comment]
It turns out it's a VisualStudio thing. I found [this issue](https://github.com/Azure/Azure-Functions/issues/564) which describes how to delete non-existent functions on publish. For VisualStudio Mac this worked for me:

`Properties/PublishProfiles/TestFunctionApp - Web Deploy.pubxml`

and adding:

`<SkipExtraFilesOnServer>False</SkipExtraFilesOnServer>`

It only works if I choose that publish profile from the list otherwise using Publish to Azure overwrite the publish profile and sets SkipExtraFilesOnServer back to True and non-existent functions aren't deleted.
