### ISSUE TITLE
Azure Function stopped without any changes

### ISSUE THREAD

**Issue by dobrybajer** [Azure/Azure-Functions#2010]
Since Monday (yesterday; 09/08) my AF stopped working. I haven't made any changes. Instead of immediate result on HTTPTrigger function (less than 1sec) it's working 300sec (5min) and then the error can be found in Application Insights:

```
Message:
Exception while executing function: Functions.MetricsHttpStart Did not find any initialized language workers    

Exception type: 
System.InvalidOperationException
    
Failed method: 
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel

Assembly:
Microsoft.Azure.WebJobs.Script, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null

SDK version: 
azurefunctions: 3.1.4.0
```

I'm aware of similar [issue](https://github.com/Azure/azure-functions-host/issues/4974)

I've tried to redeploy, change runtime version, etc. and nothing helped. What am I missing?

AF properties/settings:

1. Azure Function (Durable)
2. Consumption plan Y1
3. Linux
4. FUNCTIONS_WORKER_RUNTIME: python
5. FUNCTIONS_EXTENSION_VERSION: ~3 (which is 3.1.4.0 at this moment)
6. python code
7. requirements.txt updated today (see below)
8. linuxFxVersion: "Python|3.8"

```
requirements.txt:
azure-functions==1.7.2
pandas==1.3.1
pyodbc==4.0.31
openpyxl==3.0.7
azure-storage-blob==12.8.1
azure-functions-durable==1.0.3
typing==3.7.4.3
azure-identity==1.6.0
azure-keyvault-secrets==4.3.0
numpy==1.21.1
```
```
host.json:
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```

Last correct execution was 06/08 and `sdkVersion` was `azurefunctions: 3.0.15885.0`. Next one 09/08 was failed and `sdkVersion` was `azurefunctions: 3.1.4.0`. I've tried to set `FUNCTIONS_EXTENSION_VERSION` to `3.0.15885.0` but as a result, I see  "The service is unavailable." (status 503).

**Comment by balag0** [comment]
@dobrybajer Do you have protobuf in your requirements.txt by any chance? if not please share the appname using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
+@vrdmr

**Comment by dobrybajer** [comment]
@balag0 as you can see above I don't have `protobuf` in `requirements.txt` file. 

My app name:
- 2021-08-10 20:07:32.132
- b4e4ba7d-7529-4892-be25-d01db1846c81
- West Europe

**Comment by dobrybajer** [comment]
Hi, do you have any update on this? It's quite important.
Also I've updated post with following:

> Last correct execution was 06/08 and sdkVersion was azurefunctions: 3.0.15885.0. Next one 09/08 was failed and sdkVersion was azurefunctions: 3.1.4.0. I've tried to set FUNCTIONS_EXTENSION_VERSION to 3.0.15885.0 but as a result, I see "The service is unavailable." (status 503).

**Comment by balag0** [comment]
@yojagad Could you please check if this is the same as 
https://github.com/Azure/azure-functions-host/issues/7590

**Comment by dobrybajer** [comment]
@balag0 how could I check it? I've pasted error that is visible via Application Insights.
AF is based on Linux and logging to FTP doesn't reveal any filesystem logs.

**Comment by dobrybajer** [comment]
Here you have additional logs from Log Stream, but it doesn't seem related:
![image](https://user-images.githubusercontent.com/5682146/129276054-5658d1ae-e15e-4ba4-8c63-675a23b40760.png)

**Comment by yojagad** [comment]
> @yojagad Could you please check if this is the same as
> [Azure/azure-functions-host#7590](https://github.com/Azure/azure-functions-host/issues/7590)

@balag0 
The symptom seems to be the same but I see some difference python worker process starting up between the two versions in placeholder mode. The current rollout (3.1.4.1) might potentially fix this.

Meanwhile @dobrybajer , can you follow instructions from here https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal and set linuxfxversion to `DOCKER|mcr.microsoft.com/azure-functions/mesh:3.0.15885-python3.8` instead of `python|3.8` and see if that works ?


@vrdmr I also see python worker process startup error as below . Does this sound familiar ?
```
Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException : python exited with code 1  AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

**Comment by dobrybajer** [comment]
@yojagad thanks for info.

I've followed instructions from [HERE](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal)
and it's not possible to change `linuxfxversion`:
![image](https://user-images.githubusercontent.com/5682146/129340481-b84a0f4e-c2e6-481e-a638-a339f76baa69.png)
What am I missing?

**Comment by balag0** [comment]
probably double quotes since | has special meaning.

3.1.4.1 should be available in all regions by middle of next week.

**Comment by dobrybajer** [comment]
@balag0 please look at the screenshot once again - I've tried double quotes "", single quotes '' and no quotes at all. None of those has worked.

**Comment by balag0** [comment]
Not sure if that will fix the app, but the below syntax fixes the command 
az functionapp config set --name name --resource-group resource-group --linux-fx-version '"DOCKER|mcr.microsoft.com/azure-functions/mesh:3.0.15885-python3.8"'

**Comment by dobrybajer** [comment]
@balag0 as I've already written earlier (13/08 12:21 CEST):
![image](https://user-images.githubusercontent.com/5682146/129694935-2d2bc653-ea85-4197-9b90-f925afe69b98.png)
 (you even have a screenshot with `show` command as proof) and it's not working. What's more, this version is set all the time.

So is there something new, not mentioned in this conversation that I can do to fix this issue? It's really annoying and painful...

**Comment by yojagad** [comment]
> @balag0 as I've already written earlier (13/08 12:21 CEST):
> ![image](https://user-images.githubusercontent.com/5682146/129694935-2d2bc653-ea85-4197-9b90-f925afe69b98.png)
> (you even have a screenshot with `show` command as proof) and it's not working. What's more, this version is set all the time.
> 
> So is there something new, not mentioned in this conversation that I can do to fix this issue? It's really annoying and painful...

@dobrybajer If you take a closer look, the command posted above has a combination of single and double quotes. It's very easy to miss that.

**Comment by dobrybajer** [comment]
@yojagad I've executed from Azure CLI locally below command
` az functionapp config set --name wa-test-euw-func-metrics01 --resource-group wa.test.euw.rg.metrics01 --linux-fx-version '"DOCKER|mcr.microsoft.com/azure-functions/mesh:3.0.15885-python3.8"'`

and indeed it was executed properly with a result:
![image](https://user-images.githubusercontent.com/5682146/129778059-a6f381ba-7782-4426-8838-c10d022c51c3.png)
but executing `show` command returns same output as earlier
![image](https://user-images.githubusercontent.com/5682146/129778216-03b31b8d-10c1-464c-b783-11353f24d29e.png)

What's more, function is still not working. Any other ideas?

**Comment by dobrybajer** [comment]
Newest version fixed the problem, thus I'm closing this issue.

However, would be really helpful if you would write some guidelines on what (and how) to check in the future in similar cases.
