### ISSUE TITLE
CORS Preflight error occurs while calling azure function in javascript by locally

### ISSUE THREAD

**Issue by viswanathan1693** [Azure/Azure-Functions#2025]
**Azure Function:**

[FunctionName("negotiate")]
        public SignalRConnectionInfo Negotiate(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", "get","options")] HttpRequest req,
            [SignalRConnectionInfo(HubName = "notifications")] SignalRConnectionInfo connectionInfo, IBinder binder)
        {
            string userId = req.Headers["x-ms-signalr-userid"].ToString();

            SignalRConnectionInfoAttribute attribute = new SignalRConnectionInfoAttribute
            {
                HubName = "notifications",
                UserId = userId
            };

            connectionInfo = binder.Bind<SignalRConnectionInfo>(attribute);

            return connectionInfo;
        }

**local.settings.json** 

{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "AzureSignalRConnectionString": "Endpoint=https://my-dev-signalr.signalr.net;AccessKey=***;Version=1.0;"
  },"Host": {    "LocalHttpPort": 7071,    "CORS": "https://localhost:44346",    "CORSCredentials": true  }
}

**Javascript**

var functionUrl = "http://localhost:7071/api/";

var connection = new signalR.HubConnectionBuilder()
.withUrl(functionUrl)
.withAutomaticReconnect()
.configureLogging(signalR.LogLevel.Information)
.build();

connection.start().then(function () {               
    console.log('SignalR connection established successfully !');
}).catch(console.log(err));    

I got this below error,

Access to XMLHttpRequest at 'http://localhost:7071/api/negotiate?negotiateVersion=1' from origin 'https://localhost:44346' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

![image](https://user-images.githubusercontent.com/12513475/131446964-f0801242-189e-4eb7-a22f-85cc8265e52f.png)

Azure version .Net Core 2.1

Client Side : .Net Framework 4.6.2

**Comment by v-bbalaiagar** [comment]
Hi @viswanathan1693,  Thank you for your feedback! We will check for the possibilities internally and update you with the findings.
Meanwhile, Here is a [PR](https://github.com/Azure/azure-functions-signalrservice-extension/pull/20)  which addresses similar scenario where the PR talks about SignalRConnectionInfo and solutions to resolve it.
 Please check and let us know if this helps.

**Comment by viswanathan1693** [comment]
Hi @v-bbalaiagar ,
I have tried the above PR changes, and I am still facing the issue.

**Comment by v-bbalaiagar** [comment]
Hi @viswanathan1693 , Thank you for your feedback! We will investigate this further and update as appropriate.

**Comment by v-bbalaiagar** [comment]
Hi @viswanathan1693, I checked this internally. We don't have course configuration that would apply to local runs against a core tools. We do have the course piece of middleware that handles both authentication and end cores, but that is not enabled in local scenarios.

**Comment by viswanathan1693** [comment]
Hi @v-bbalaiagar ,
Can you give us a fix for this localhost scenario ?

**Comment by v-bbalaiagar** [comment]
Hi @viswanathan1693, Unfortunately, we can't provide a course configuration that would apply against a core tools.

**Comment by viswanathan1693** [comment]
Hi @v-bbalaiagar ,

Issue is resolved by changing localhost url http://localhost:7071/api/ to http://127.0.0.1:7071.

In Chrome, after Option request of negotiate API, it is redirecting to **https:**//localhost:7071/api/ (http changed into https)

So I just used function url as  http://127.0.0.1:7071 insted of http://localhost:7071/api/

**Comment by EntityAdam** [comment]
nah, this isn't ok. Everything else works with http://localhost, why should a work-around be acceptable for azure functions?

The lack of CORS configuration options available isn't sufficient.

These are all the available options for local.settings.json

```
  "Host": {
    "CORS": "*",
    "CORSCredentials": true
  }
```
The only thing CORS does is set the origin.  What about allowed methods? What about allowed headers?

The reason preflight fails is because OPTIONS isn't allowed. From looking at the response headers only POST is allowed.

Not to mention, at the time of writing this, CORSCredentials options is broken. If I set it to true, the functions app won't even start locally


```
Azure Functions Core Tools
Core Tools Version:       4.0.7030 Commit hash: N/A +bb4c949899cd5659d6bfe8b92cc923453a2e8f88 (64-bit)
Function Runtime Version: 4.1037.0.23568

[2025-03-28T19:01:47.630Z] Found C:\repos\...\source\Api\Api.csproj. Using for user secrets file configuration.
Cannot access a disposed object.
Object name: 'IServiceProvider'.
Press any key to continue....
```
