### ISSUE TITLE
Links to slide decks not working

### ISSUE THREAD

**Issue by shaunthomas999** [Azure/Azure-Functions#2026]
All links to slide decks in the page [https://github.com/Azure/Azure-Functions/wiki/Samples-and-content](https://github.com/Azure/Azure-Functions/wiki/Samples-and-content) are not working

**Comment by v-bbalaiagar** [comment]
Hi @shaunthomas999, Thank you for your feedback! Team removed the dead links.

Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.

**Comment by shaunthomas999** [comment]
Hi @v-bbalaiagar, what I expected is that someone will correct the link so that everyone can get the documents. Didn't expect it to be removed completely! Can you please help to get the documents?

**Comment by v-bbalaiagar** [comment]
Hi @shaunthomas999,  They are not available documents. They have been removed.
Here is the documents link where you can find all the documents for azure developers  -  https://docs.microsoft.com/en-us/users/cloudskillschallenge/collections/1o3xtm51q6ko?WT.mc_id=cloudskillschallenge_42d24499-4f97-4a7a-9238-103bda9ebd6c
Please check and let us know if this helps.
