### ISSUE TITLE
Moving Application Insights into an extension and removing references from the host.

### ISSUE THREAD

**Issue by gzuber** [Azure/Azure-Functions#2027]
Moving Application Insights into an extension, and removing all references in the host.

Discussion: https://github.com/Azure/Azure-Functions/discussions/2030

### Motivation
What is the motivation for this change?

Our Application Insights integration, as it exists today, is very tightly coupled with the Functions Host. The package is included in the project as well as all releases and there is special-cased setup that occurs on startup. As a result, customers are limited to only using the version of Application Insights that the host is currently running. They must wait until we adopt a new version to be able to use its features, and if there are any bugs or issues it requires a full host release to upgrade to a new version. This is limiting and might be confusing to customers that don't realize this requirement and run into issues.

This would also represent the first step in introducing alternatives to Application Insights. Once Application Insights is moved to an extension, we (or Functions customers) would be able to create similar extensions for other providers -- like New Relic, DataDog, etc... -- that utilize this template and the changes to the infrastructure that were necessary to make a monitoring extension work.

### Impact
How many customers (roughly) would be impacted by this break? If not known, how can we figure it out? This may require host changes to gather metrics.

This would apply to any function app using Application Insights, which is most (almost all) apps. This shouldn't impact the functionality of how app insights behaves and logs, but it would impact customers during the transition from V3 to V4. For customers that use extension bundles, the app insights extension should be installed automatically and there shouldn't be any issues. However, for apps that don't use bundles (e.g. dotnet), the extension would not be installed automatically. The customer would need to manually install the extension to get their app insights logs. We would need to make this very clear in the event an app is upgrading without being properly configured with clear notifications and well documented steps for customers to install the extension (more information in the [Documentation](#documentation) section).

### Compat-mode Support
We'd like to enable compat-mode support for every breaking change. This may not be feasible in reality, but each proposal should include a plan to switch back to the previous behavior with a feature flag. This requirement will be evaluated on a case-by-case basis.

This would be hard to do without defeating the purpose. In order to provide a flag to turn this feature on and off, we'd have to leave the current references to Application Insights in the host. This means the customer would still be bound to the version used by the host and we'd lose the benefits of this change.

It's possible we could keep the current Application Insights setup for compat-mode support for now to ensure a fall back if there are any unforeseen issues with the extension, but we wouldn't see the benefit (or removing Application Insights) until we remove it from the host.

### Alternatives
Were any alternatives discussed? Is there any way to do this without a break?

I don't believe there's another way to accomplish this while removing Application Insights from the host.

### Detection
Can we detect that a customer is using this when they upgrade from v3? Is there a specific error that can be thrown with a link to migration guidance?

All customers using v4 will have this enabled. We would also be able to tell if they're using this because the extension should be adding its extension version to the logs.

### Support
Will there be any incidents-per-day impact? Who will be the support contact? Does support need to be notified of this change?

In terms of app insights functionality, there shouldn't be much change from the customer's perspective. However, as previously discussed there may be a rough transition for customers that aren't using extension bundles. We would want to discuss this with support and let them know to check for this if the customer moved to V4 and their host won't start or they're not seeing logs. If there are issues @gzuber is the right person to contact. @brettsam is also someone to contact if Graham is not available.

<h3 id="documentation">Documentation</h3>

This change would need to be very well documented since there will be customers' apps that will be broken without manual intervention. Some of the options that have been discussed:

 - Detecting if a customer has either `APPINSIGHTS_INSTRUMENTATIONKEY` or `APPLICATIONINSIGHTS_CONNECTION_STRING` but don't have the extension installed and failing the host with a clear exception
   - We would need to make sure this exception is clearly surfaced to the customer since app insights would not be working.
   - We could potentially use the Error API in the portal for this.
 - Adding a warning to the host when their app is run locally that will tell the customer to install the extension if they plan to use app insights
   - Most customer won't have either app settings configured when run locally, so we would be able to determine if they have the app insights extension installed but not if they _should_ have it installed (presence of app setting)
   - This unfortunately leads to a situation where we may have to warn everyone about the extension not being installed even if they don't intend to use it, just to make sure those who do need it are warned
   - We should also provide a way for customers to suppress this warning
 - A page of documentation that clearly explains how the customer can install the extension in the event their host won't start

### Components Impacted
What components does this change impact? Examples of areas (this list may not be exhaustive):

Azure Functions Host
Monitoring

### Performance
Does the change have any performance impact? There may need to be some implementation complete before this can be measured.

There may be some performance implications with this change since Application Insights setup is involved with cold start. Performance needs to be measured and tested.

**Comment by brettsam** [comment]
Done. Relevant PRs: 
- https://github.com/Azure/azure-functions-host/pull/7639
- https://github.com/Azure/azure-functions-applicationinsights-extension/pull/1

**Comment by gzuber** [comment]
This breaking change has been abandoned and is not included in the Functions V4 release. We're re-evaluating the Application Insights Extension, but for now the default integration/behavior remains unchanged.

**Comment by CEbbinghaus** [comment]
Why? This is a feature that could have saved me a lot of work. I have been fighting with Application Insights before giving up and writing something myself over the last month. This change would have been a lifesaver allowing us to simply use a higher version of app insights to give me the necessary features I needed. Hope this can be added for V5 at the very least
