### ISSUE TITLE
Unable to root cause why one of my orchestrations within a function died.

### ISSUE THREAD

**Issue by nairashu** [Azure/Azure-Functions#2028]
I have a Function App that has multiple long-running orchestrations inside of it. One out of the 7 orchestrations suddenly crashed in the middle and I do not see any exceptions around the time of the crash. Where do I look to find what resulted in the orchestration being terminated?

**Comment by v-anvari** [comment]
Hi @nairashu , Please find the documentation here to diagnose the errors and exceptions: 

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling?tabs=csharp

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-orchestrations?tabs=csharp

Surround your code with a try catch block and then log the exception using the Ilogger.

It can be achieved by like this
```

try
{
   //Do something
}
catch(Exception ex){
   log.LogError($"Error in function: {ex.Message}");
}
```
Then you can view the error messages in the logs or as well as Application insights if you have one.


You can also configure Application Insights for Azure Functions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring 

In addition (or when you don't want Application Insights) you can query the status of the orchestration either via C# or HTTP. This also works very nicely when you run & debug on your local machine!

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-all-instances-status

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#query-instances

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
