### ISSUE TITLE
Functions Tooling is incompatible with Azure SDK 3.0.0

### ISSUE THREAD

**Issue by meikelenboom** [Azure/Azure-Functions#203]
I was using the preview project template in Visual Studio 2015 as part of a presentation I'm giving next week. 

Today I've updated the Azure 2.9.6 .NET SDK to version 3.0.0 and I've updated my VS 2017 RC to RTM. With these updates, the project template has gone missing. And I can't seem te get it back. I tried to revert the SDK back to 2.9.6 and I've reinstalled the preview tools again. Unfortunately that doesn't seem to work.

Any suggestions or alternatives?

**Comment by GenesisCoast** [comment]
@meikelenboom I am having the same problem to any luck yet?

**Comment by meikelenboom** [comment]
No luck so far. Had a chat with Andrew Hall on twitter (@AndrewBrianHall), although he's very helpful, it's not solved yet. 

@GenesisCoast did you do any of the updates I did?

**Comment by GenesisCoast** [comment]
Yep, I upgraded the Azure SDK to 3.0.0 and installed VS 2017 and then the project template went missing and VS refused to open any existing function projects. Tried reinstalling VS, Tools, SDK etc... to no avail.

**Comment by GenesisCoast** [comment]
I just tried completely nuked the entire VS installation. Still no luck. I am wondering if it has something to do with the recent Azure SDK release 3.0?

**Comment by meikelenboom** [comment]
I reverted the SDK back to 2.9.6 (the version recommended in the blog post) and that didn't solve it either.

**Comment by lindydonna** [comment]
We're trying to find a workaround, I'll update this thread shortly.

**Comment by lindydonna** [comment]
Here's the workaround:

1. Close VS 2015

2. Uninstall **Microsoft Azure App Service Tools v3.0.0** from the Windows "uninstall or change a program dialog"

![image](https://cloud.githubusercontent.com/assets/4260261/23810334/11c3de82-0586-11e7-83ce-1ac7e35de7e4.png)

3. Reinstall the Azure Functions Tooling: https://aka.ms/azfunctiontools

**Comment by mikeeager** [comment]
That workaround doesn't seem to work either.

**Comment by GenesisCoast** [comment]
Same for me.

**Comment by lindydonna** [comment]
@mikeeager The only other advice I can offer is to restart the machine and try running `devenv setup` from an **admin** developer command prompt. [/Setup \(devenv\.exe\)](https://msdn.microsoft.com/en-us/library/ex6a2fad.aspx)

**Comment by lindydonna** [comment]
@GenesisCoast and @mikeeager Did reinstalling the Functions Tools work without errors?

**Comment by mikeeager** [comment]
@lindydonna ...it was a clean install without errors. 
![broken](https://cloud.githubusercontent.com/assets/8737783/23811185/c059254e-0589-11e7-9f20-8e138e53f9be.jpg)

**Comment by lindydonna** [comment]
@mikeeager Try the `devenv /setup` command then from my previous comment

**Comment by GenesisCoast** [comment]
I have tried the above command. Reinstalling, Reinstall with Force. Removing all Visual studio Components and Doing a Clean install. I haven't had any luck with any possible workaround so far...

**Comment by nirmalkumarv** [comment]
Same Issue. Azure Functions are missing even in VS 2015. 

The following options doesn't work
- UnInstalled VS 2015, Restarted and Installed Fresh Copy
- UnInstalled Azure SDK 3.0
- UnInstalled Azure SDK 2.9.6 and Re-Installed
- Copied the Project Templates from Peer and Copied to ProjectTemplates Cache. But the error says "The template location not found"
- Explored the Registry Package to check whether that ClassId (AzureFunctions) is registered. But i can't see one

**Comment by GenesisCoast** [comment]
I have just tried a clean windows install on a VM. Azure Functions Preview Installed fine. However if the Azure SDK 3.0 is installed or has been previously installed at any point on the machine, you will not be able to use the Azure Functions Preview at all.

**Comment by nirmalkumarv** [comment]
Any Luck or Temporary Workaround?

**Comment by Intranoggin** [comment]
I've gone so far as to uninstall both VS 2017 and VS 2015 and all their related components. After reinstalling just the VS2015 Azure SDK 2.9.6, and the function tools, I'm in worse shape. I see the function project available, but when i try to create a new one, or open an existing function project, it throws a VsProjectFault<guid>.txt file into the appdata/local/temp directory. The log always contains this message:
3/14/2017 8:31:08 AM
Recoverable
System.Exception: The following error occurred during discovery of project files on disk. The operation was canceled..
   at Microsoft.VisualStudio.Web.WindowsAzure.AzureFunctions.ProjectSystem.FileMirroring.SourceItemsInMemoryProject.<InitializeFromDiskAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.WindowsAzure.AzureFunctions.ProjectSystem.FileMirroring.SourceItemsInMemoryProject.<Creator>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__6_0>d.MoveNext()
[VsProjectFault_5445d7f3-b4b6-40b4-80af-0874637a7ccc.failure.txt](https://github.com/Azure/Azure-Functions/files/841373/VsProjectFault_5445d7f3-b4b6-40b4-80af-0874637a7ccc.failure.txt)

**Comment by lindydonna** [comment]
@Intranoggin Thanks for reporting, and sorry to hear you're having so much trouble.

Here's a workaround: you can instead create a Web Application project and customize the "Start Action" to run the Functions CLI, which will attach a debugger. Here are the steps: https://github.com/lindydonna/CoderCardsv2#local-debugging-in-visual-studio

I'll have a blog post in a few days that walks through from start to finish.

**Comment by nirmalkumarv** [comment]
Finally able to resolve temporarily in a Harsh way
- UnInstalled SDK 3.0, Installed again the SDK 2.9.6
- Added Missing Entries in Registry
- Copied the Necessary Packages and DLL's to C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools Azure
![azurefunctions](https://cloud.githubusercontent.com/assets/897323/23938428/4a60aef0-0982-11e7-9ecb-2b8364a88ef2.png)

**Comment by Intranoggin** [comment]
@lindydonna  Unfortunately still no luck. I tried cloning that project on two machines and couldn't get it running on either. 

1 machine still has VS 2017 installed. After reading host.json, this one says "ScriptHost initialization failed. Microsoft.WindowsAzure.storage: unable to connect to the remote server. System: unable to connect to the remote server. System: no connection could be made the target machine actively refused it 127.0.0.1:10000

The other machine has on vs 2015 installed (but had 2017 installed and removed). This one launches the functions cli, which then immediately crashes. A red message appears just before it crashes, but is not there long enough to read. No logs are being generated that I can locate.

**Comment by lindydonna** [comment]
@Intranoggin Ah yes, there is a situation where the port handle can be allocated to an app that is no longer running. In the CLI we have a bug to use a new port if the existing one is taken. 

Try passing an explicit port via "-p 7072" for instance. Visual Studio always uses 7071.

**Comment by Intranoggin** [comment]
Using the Compiled function method you linked to, I was able to get it running from VS 2017! 

The port issue you pointed to was solved with the -p as you indicated. 

The System: no connection could be made the target machine actively refused it 127.0.0.1:10000 issue was because I had not yet initialized the Azure Storage Emulator (I had reinstalled it).

On my VS 2015 install, my web deploy is now broken, but if i can get it working in VS 2017 that won't be an issue.

Where I'm at now is trying to create the hello world http triggered function. The code from the sample function uses HttpRequestMessage.GetQueryNameValuePairs and req.CreateResponse(HttpStatusCode.OK, "Hello " + name);

From what I can tell, those come from extension methonds in system.net.http and are sourced from the system.web.http.dll. However, I can't seem to locate that .dll in my VS2017 references or in Nuget. Any ideas how I can add that reference?

**Comment by lindydonna** [comment]
I've posted a blog with detailed instructions on how to use precompiled functions in VS, which is the direction we'll take with the new tooling: https://aka.ms/precompiled-functions

**Comment by lindydonna** [comment]
@Intranoggin Afaik it's Microsoft.AspNet.WebApi.Client as specified in packages.config: https://github.com/lindydonna/FunctionsAsWebProject/blob/master/FunctionsAsWebProject/packages.config#L3

However, you may also need to install one of the ASP.NET SDKs on your machine. [HttpRequestMessageExtensions\.GetQueryNameValuePairs](https://msdn.microsoft.com/en-us/library/system.net.http.httprequestmessageextensions.getquerynamevaluepairs(v=vs.118).aspx) is in System.Web.Http.dll.

**Comment by mikeeager** [comment]
@lindydonna I followed blog you authored about pre-compiled functions to a tee and all works well. Thanks for that. I actually really like the flow much better. As soon as I tried to hook up a VERY simple Storage Table read / write in the function I get errors indicating that I don't have my connection string set up properly to my remote Storage Account...but indeed I do have it set in the appsettings.json file.

Are there any know issues with developing locally and trying to connect to a remote storage account??

Errors when trying to launch the function:

A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.PaymentReceived'. Microsoft.Azure.WebJobs.Host: Microsoft Azure WebJobs SDK 'AzureWebJobsStorage' connection string is missing or empty. The Microsoft Azure Storage account connection string can be set in the following ways:
1. Set the connection string named 'AzureWebJobsStorage' in the connectionStrings section of the .config file in the following format <add name="AzureWebJobsStorage" connectionString="DefaultEndpointsProtocol=http|https;AccountName=NAME;AccountKey=KEY" />, or
2. Set the environment variable named 'AzureWebJobsStorage', or
3. Set corresponding property of JobHostConfiguration.

**Comment by lindydonna** [comment]
@mikeeager That should work fine, I do this all the time.

Make sure that you don't have encrypted settings in appsettings.json. Also make sure the structure is correct; it has a property for whether or not the contents are encrypted.

Should look like this:

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
  },
  "ConnectionStrings": {}
}
```

**Comment by mikeeager** [comment]
You are a life saver!!! I've been fighting this one for awhile. All good now and thank you so much. Seems there is much to learn for others in this thread.

**Comment by lindydonna** [comment]
@mikeeager In the future, the tooling will help with these connection strings.

You can also use the Functions CLI to add and edit them. Do `func settings add` and `func azure functionapp fetch-app-settings`

**Comment by dreadeddev** [comment]
Ok, so following this thread all the way through it seems unless you do a lot of hacking (a post mentioned adding missing registry settings but didn't say which ones) and copy of dll's, If you've installed 3.0 of the SDK you're basically fubar'd for working with Azure Functions locally??

 Is my understanding correct? 

And if so, that makes me worry for creating an architecture where basic development support has been withdrawn from the latest SDK? Can someone assure me that the SDK team are working on a patch for 3.0 to put Functions back in or should we all be running away from Functions as fast as we can and redoing them as an Azure WebJob (as essentially that's all they are anyway)

**Comment by SimonLuckenuik** [comment]
@dreadeddev, what is broken is the Visual Studio integration, not the "working locally part". The link posted by @lindydonna above should be sufficient to work locally with Azure Functions until they release the new VS Functions Tooling: https://aka.ms/precompiled-functions

**Comment by dreadeddev** [comment]
Well yes @SimonLuckenuik, but that's just semantics. essentially it was all working locally, they release an update that breaks it and so we now have to move everything from the original functions project into a new project, thus loosing all history etc in source control, and then will this project then just work with the new tooling? or will we need to repeat this process again? Pretty poor experience from the developer stand point! But thanks, will do the above as I'm guessing that waiting for "until they release the new VS Functions Tooling" is, an as yet, undetermined amount of time.

**Comment by dreadeddev** [comment]
Also, can I just check soemthing with you @SimonLuckenuik / @lindydonna 

Are you recommending that we uninstall 3.0 and install 2.96 as from some of the comments here and on the other page it seems that when you do that it causes more issues later on when you need to upgrade again? Is there any workaround that works with 3.0 installed?

**Comment by SimonLuckenuik** [comment]
@dreadeddev, no need to be so upset, just trying to help here... 

- Azure Functions Visual Studio support tools are tagged as Preview for a reason, it's a preview that can change in time (Quote: "These tools are offered as a preview release and will have some rough spots and limitations" : https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/). 
- It was working locally with the CLI alone, before the released the tooling to include it in Visual Studio, and today the same approach with the CLI is still working.
- The funproj project is simply including all files found in the folder by default and doesn't contain much. You probably never modified that specific project file after initial creation. The CLI execution relies on the content of the folder with the functions, not the funproj.
- You will keep the exact same files at the exact same location, if for some reason you decide to do differently and move the files around, most, if not all, modern source control repository support moving and renaming files, so no impact there as well on your work history. 
- The only impact I can see is that you will add a new csproj file in a the funproj folder and that will probably cover most of it and at some point they will release a final "non preview" of the tooling is out you will either upgrade your funproj to the new format or simply take 5 minutes of your time to create a new project.

**Comment by dreadeddev** [comment]
@SimonLuckenuik Apologies if I come across stroppy, I tend to be a little sarcastic in life generally (as anyone whose worked with me will testify) however, tongue in cheek sarcasm doesn't always come across too well when typed! I appreciate the help! Much love guys!

**Comment by timmyreilly** [comment]
I've found a workaround following Donna's instructions on YouTube: 
https://www.youtube.com/watch?v=R7F92POLGaE 

But first you need a copy of the Azure.Functions.Cli version 2.9.6 somewhere on your machine. 
Here's a zip of it: https://1drv.ms/u/s!AtRpIbCPWnV4m91PFE_EgcVc29zWrA 

Follow Donna's instructions and extract the zip and you'll be back in Visual Studio.

**Comment by lindydonna** [comment]
@timmyreilly There's an easier way, simply download the CLI and unzip, or install from [npm azure-functions-cli](https://www.npmjs.com/package/azure-functions-cli). (FYI I'm removing your OneDrive link out since I don't really want to recommend that approach).

This URL will give you a JSON payload with the URL of the latest CLI: https://aka.ms/functions-cli

**Comment by ChrisGarty** [comment]
@lindydonna Installing from https://www.npmjs.com/package/azure-functions-cli and/or running func.exe from the latest CLI... don't seem to fix up Visual Studio so that New > Project > Templates > C# > Cloud will show a Azure Function template. How do I get that Visual Studio template from 2.9.6 back?
Thanks!

**Comment by lindydonna** [comment]
@ChrisGarty Right, the Functions CLI won't fix the Visual Studio template back. You can try uninstalling Azure SDK 3.0 and re-installing 2.9.6, then the Functions Preview tooling.

Alternatively, just use a Web Project and customize your start action. See https://aka.ms/precompiled-functions for details. You can also convert your csx files to .cs, but that's optional.

**Comment by feeloor** [comment]
Is there any headways here? I've tried to re-install 2.9.6 and Functions Tooling with no luck. I've also tried installing Azure SDK 3.0 again and uninstalling **Microsoft Azure App Service Tools v3.0.0** and then installing the Functions Tooling, no luck here either.

**Comment by Intranoggin** [comment]
I don't think there is a way that you can get successfully back to the 2.9.6 and working templates. You'll need to switch to the pre-compiled option.

**Comment by feeloor** [comment]
@Intranoggin Okey, thank you. Do you/anyone know when this will be fixed? Or any work arounds?

**Comment by Intranoggin** [comment]
@feeloor My interpretation is that moving to the pre-compiled technique is the fix. There may be a new template in the future that streamlines the setup of bindings and pointing to the CLI for local debugging, but I'm only guessing there.

**Comment by nirmalkumarv** [comment]
I have provided some notes on how i resolved this issue. This may help someone who want to get rid off this blocker. https://medium.com/@nirmal_kumar/resolving-functions-tooling-incompatibility-with-azure-sdk-3-0-0-1708f28e7cb

**Comment by lindydonna** [comment]
@Intranoggin Yes, moving to precompiled is our recommendation. Aside from a better tooling experience, you will see performance improvements for cold start. We've just released a blog post about the tooling roadmap: https://blogs.msdn.microsoft.com/webdev/2017/04/14/azure-functions-tools-roadmap/

**Comment by dreadeddev** [comment]
Hello again!!

Indeed this does work well this way, I can code it and publish it and all
is well, however, how in the name of all that's holy, how are we now meant
to start a manual trigger through the portal?? It very much seems with
Functions that this is not production ready (The whole portal changing look
and feel in the middle of the working day without warning also points to
this), a SDK is released which doesn't work with the latest IDE, then the
work around, (which according to your blobs is the way the future of
Functions tooling is going) doesn't work with the brand new functions blade
in the Portal.... Left hand not knowing what the right is doing springs to
mind!!!

Getting more and more frustrated with the lack of joined up thinking at MS
around Functions!!

Thanks,

Ian

**Comment by gabrielius** [comment]
@nirmalkumarv The link is not accessible anymore...

Is there any way to get back to Azure SDK 2.9.6? I have problems when trying to publish using Visual Studio 2015 and don't want to publish using `func`.

**Comment by dreadeddev** [comment]
@gabrielius Unfortunately not!! It seems the way forward is with precompiled functions! It's a bit painful as it doesn't support everything that other apps do (like assembly binding redirection, etc) but seems to be the way forward. Once you've got it set up it works okay though. Link is [https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions)

**Comment by nirmalkumarv** [comment]
@gabrielius The link issue fixed. https://medium.com/@nirmal_kumar/resolving-functions-tooling-incompatibility-with-azure-sdk-3-0-0-1708f28e7cb

**Comment by lindydonna** [comment]
Closing this issue, as we don't plan to support the old Functions Tooling, and instead use the class library model. Stay tuned for more announcements at BUILD.

See https://blogs.msdn.microsoft.com/webdev/2017/04/14/azure-functions-tools-roadmap/ for more details

**Comment by BatriderLEL** [comment]
So still no fixes for VS15\17 on AzureFunctions template?

**Comment by lindydonna** [comment]
@BatriderLEL We have VS 2017 tooling, but we won't be supporting VS 2015. See https://blogs.msdn.microsoft.com/webdev/2017/05/10/azure-function-tools-for-visual-studio-2017/.

**Comment by ChrisGarty** [comment]
Donna, the new VS2017 tooling looks great. Upgrade time :). Thanks!

**Comment by lindydonna** [comment]
We recommend that customers use the new VS 2017 tools. The VS 2015 tools are no longer being maintained. See https://aka.ms/vs2017functiontools
