### ISSUE TITLE
Not able to store multiple files in blob storage using output binding  (python)

### ISSUE THREAD

**Issue by mouhannadali** [Azure/Azure-Functions#2036]
is it possible to store multiple files in blob storage using an output binding?

I have created the following output binding in function.json
```
    {
      "type": "blob",
      "direction": "out",
      "name": "outputBlob2",
      "path": "outputitems/{rand-guid}.json",
      "connection": "stplmaipocalgdev001_STORAGE"
    }
```

if try to save multiple files in Azure function:
  ```
  for index in range(len(output_json)):
        json_object = json.dumps(output_json[index])
        outputBlob2.set(str(json_object))
```

the stored file is overwritten with a new one. any suggestion?

**Comment by v-bbalaiagar** [comment]
Hi @mouhannadali,  Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @mouhannadali, I checked internally. Multiple blob outputs for the same output binding are not currently supported. For now, the best option would be to pull in the storage module.
