### ISSUE TITLE
Will Azure Functions .NET 6 support Linux App Service plans (both consumption and dedicated) soon or at least at .NET 6 launch?

### ISSUE THREAD

**Issue by mikequ-taggysoft** [Azure/Azure-Functions#2037]
A few months ago we started using Azure Functions with the .NET 5 isolated runtime stack. At that time, it was supported on Windows App Service plans only.

Now I see that the option to select .NET 5 has been removed when deploying Function App via Azure Portal. Instead we now have .NET 6 Preview.

That is great, however, it's again limited to Windows only for now. I read the various MS blogs that explained the reasons behind the delayed support for .NET 5 on Azure Functions, and how .NET 6 support will be much faster and smoother.

It's a bit disappointing considering the fact that the non-function ".NET 6 Early Access" runtime stack is already available on Linux App Service plans.

So my question is can we expect Linux support for .NET 6 functions very soon, or at the latest when .NET 6 goes GA in November?

**Comment by anthonychu** [comment]
Linux support will be coming in the next week or two. It's currently rolling out. We expect public preview to be announced soon and are still on track to GA Azure Functions v4 at the same time as .NET 6.
