### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by sadiqkhoja** [Azure/Azure-Functions#2038]
We are facing this strange issue in production. While making remote https request to APIM, following error is thrown:

```
The SSL connection could not be established,  see inner exception.
Inner exception: Authentication failed because the remote party has closed the transport stream.

{"assembly":"System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Security.SslStream.StartReadFrame","level":0,"line":0}
{"assembly":"System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Security.SslStream.PartialFrameCallback","level":1,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":2,"line":0}
{"assembly":"System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Security.SslStream.ThrowIfExceptional","level":3,"line":0}
{"assembly":"System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Security.SslStream.InternalEndProcessAuthentication","level":4,"line":0}
{"assembly":"System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Security.SslStream.EndProcessAuthentication","level":5,"line":0}
{"assembly":"System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Security.SslStream.EndAuthenticateAsClient","level":6,"line":0}
{"assembly":"System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Security.SslStream+<>c.<AuthenticateAsClientAsync>b__65_1","level":7,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic","level":8,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":9,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":10,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":11,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult","level":12,"line":0}
{"assembly":"System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.Http.ConnectHelper+<EstablishSslConnectionAsyncCore>d__4.MoveNext","level":13,"line":0}
```

We have set security protocol to tls1.2 in the code:

```
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
```

When I hit https://www.howsmyssl.com/a/check from production, I get following response:

```
{
  "given_cipher_suites": [
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
    "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
    "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
    "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
    "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
    "TLS_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_RSA_WITH_AES_256_CBC_SHA256",
    "TLS_RSA_WITH_AES_128_CBC_SHA256",
    "TLS_RSA_WITH_AES_256_CBC_SHA",
    "TLS_RSA_WITH_AES_128_CBC_SHA",
    "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
    "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256",
    "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256",
    "TLS_DHE_DSS_WITH_AES_256_CBC_SHA",
    "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",
    "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA",
    "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
  ],
  "ephemeral_keys_supported": true,
  "session_ticket_supported": true,
  "tls_compression_supported": false,
  "unknown_cipher_suite_supported": false,
  "beast_vuln": false,
  "able_to_detect_n_minus_one_splitting": false,
  "insecure_cipher_suites": {
    "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA": [ "uses 3DES which is vulnerable to the Sweet32 attack but was not configured as a fallback in the ciphersuite order" ],
    "TLS_RSA_WITH_3DES_EDE_CBC_SHA": [ "uses 3DES which is vulnerable to the Sweet32 attack but was not configured as a fallback in the ciphersuite order" ]
  },
  "tls_version": "TLS 1.2",
  "rating": "Bad"
}
```

Same function works correctly in DEV and QA environment. All environments are created using same pipeline (arm templates and code)

**Comment by v-anvari** [comment]
Hi @sadiqkhoja , If it requires immediate attention to your prod env, please open a support ticket and they would have all the required access to your Application, also, because it looks like a client side error. We would only be able to reproduce the issue if possible, or check the generic logs. If you wish for us to further investigate this issue, please provide us the invocation id of the failed log, timestamp and the region in which the function app is deployed to.

**Comment by sadiqkhoja** [comment]
Thanks @v-anvari ,
invocation id: 60a9c6a6-2ca7-4806-9430-3b6986c2bc03 
timestamp: 2021-09-13T22:00:00.0380000Z
region: Canada Central

**Comment by v-anvari** [comment]
Thank you for the details We will investigate this further and update you with the findings.

**Comment by sadiqkhoja** [comment]
Just an update, we removed private endpoint from the function app and it started working. We are no longer facing SSL issue. I don't know what happens under the hood when we add/remove private endpoint. Is it possible that underlying virtual machine switched to another instance, which doesn't have this problem.

**Comment by v-anvari** [comment]
That could be a Networking issue related to any firewall or NSG rules. We won't be able to check that from our end. The support team will be able to route the issue to the right team after investigation. Create a support ticket by following the below path.

Portal> Menu > Help and support

Here is a document explaining the support - https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options
Here is a document explaining the NSG - https://docs.microsoft.com/en-us/azure/virtual-network/manage-network-security-group
Few troubleshooting methods are here - https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-domain-ssl-certificates

**Comment by sadiqkhoja** [comment]
@v-anvari Update: we engaged MS support, after 2 days of investigation we solved the problem by removing following two app settings:

- WEBSITE_DNS_SERVER=168.63.129.16
- WEBSITE_VNET_ROUTE_ALL=1

Now I have following questions:

- How WEBSITE_DNS_SERVER and WEBSITE_VNET_ROUTE_ALL are related to SSL handshake?
- Why MS document for creating private endpoints and vnet integration azure function still asks to add above mention settings: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-vnet
- Why our QA and DEV environment having same configurations (created using same ARM templates and devops pipeline) as PROD don't have any SSL issues?

I have asked same questions to our MS support person, asking here as well in a hope to have insights from people who are building this awesome platform

**Comment by v-anvari** [comment]
I shall follow up with the networking team to understand this behavior. We are not really sure what kind off restrictions are implemented.

**Comment by sadiqkhoja** [comment]
Update: root cause was the wrong IP Address configured in private DNS zone. We had two private DNS zone to resolve custom domain name of APIM, one was pointing to QA's APIM and other one pointing to PROD's APIM. We shouldn't have two private DNS zone in the first place and having wrong IP address was terrible mistake :(. Lesson learnt. Thanks @v-anvari  for the help.
