### ISSUE TITLE
Deployment slots on the same elastic plan share the same files?

### ISSUE THREAD

**Issue by viclin-msft** [Azure/Azure-Functions#2039]
I have an app service _A_ (S1) and function app _F_ (EP1), with one deployment slot each (_A-staging_, _F-staging_).

_F_ and _F-staging_ appear to share the same filesystem, while _A_ and _A-staging_ are independent:

1. With debug consoles (`https://<name>.scm.azurewebsites.net/DebugConsole`) open for both _F_ and _F-staging_, adding a new file in _F-staging_ will immediately update _F_, and vice versa. This is not the case for the app service.
2. Running `hostname` shows the same value for _F_ and _F-staging_, while it shows different values for _A_ and _A-staging_.

Not sure if this is a bug or just an undocumented feature. If files are shared across deployment slots on function apps, this defeats the purpose - deploying to a slot meant for "staging" will immediately change what runs in the production slot.

**Comment by balag0** [comment]
Does F and F-staging have the same value for the appsetting WEBSITE_CONTENTSHARE?

**Comment by balag0** [comment]
Also wanted to make sure you have the right scm url for the different slots.
(https://<name>.scm.azurewebsites.net will always point to the prod slot)

**Comment by viclin-msft** [comment]
Thank you @balag0, yes they had the same value for `WEBSITE_CONTENTSHARE`. I made them different and now the filesystem is separate (although `hostname` is the same, but that is fine).
