### ISSUE TITLE
Add the ability to execute code after configuration & DI has completed

### ISSUE THREAD

**Issue by dom380** [Azure/Azure-Functions#2046]
I need to execute a function before the function app has fully "stood up" but the code relies on various injected dependencies as well as the database context which makes `FunctionsStartup` unsuitable as a hook in point.

In essence a callback at the end of the bootstrapping cycle or perhaps a `Trigger` that fires after the app has finished initializing.

**Comment by v-anvari** [comment]
Hi @dom380 ,

Can you explain the scenario with a sample code. Also, Can you point out the expected and actual behavior
