### ISSUE TITLE
Reconcile our various logging mechanisms

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#205]
For a function app we have our portal logging which drives log streaming/portal debugging, as well as long term Monitor tab logging. There is also the Web Apps enable logging UI which is something completely separate. This confuses Function App users who go in there and enable that - see https://github.com/Azure/azure-webjobs-sdk-script/issues/1222. I excerpt:

> This is however, extremely misleading, since there is a setting for turning on App Logging explicitly under:
Function App -> Settings -> (Monitoring) Diagnostic Logs 

> If that doesn't do anything on a function app, it should at a minimum be disabled with something that points you where you can turn on logging for the function App. 

> Likewise, turning on log streaming in Visual Studio should be disabled for a function app and point you in the right direction for enabling what we're actually looking for.

> Even better yet, if both options ALSO triggered the function app logging, that would make everything much more intuitive and make a lot more sense.

**Comment by JasonKleban** [comment]
It's been 18 months.  Any progress on getting `context.log()` to work?

**Comment by ColbyTresness** [comment]
Is this still relevant @mathewc ?

**Comment by mathewc** [comment]
No longer relevant. We've made portal updates to disable unsupported logging features.

**Comment by wpitallo** [comment]
So how do you see a node console.log ?

**Comment by spencerwasden** [comment]
I saw context.log not working 2 days ago.  Then I refreshed, and I see context.log, context.log.warn, context.log.err and context.log.warn working.  (please ignore verbose in the screenshot; I guess I don't have it configured https://github.com/Azure/azure-functions-host/issues/1370)  Then it DIDN'T work after that with no configuration changes made!!!  To get this screen shot today I had to refresh 3 times!  There's a problem here and it's very relevant to anyone writing function apps.  It is unreal that this issue has been around this long....imho.

![image](https://user-images.githubusercontent.com/3638882/76808869-a21cfa80-67ae-11ea-8591-43aa8df28f9e.png)

**Comment by Divine1** [comment]
```
context.log("")  -- unable to find the log message
```
this issue has been reported since 2017 and i have noticed developers reporting this issue on multiple websites and threads

@wpitallo i think this will never get fixed, but looks like the contributer's never forget to close any issues related to this.
