### ISSUE TITLE
Failed to download zip when using WEBSITE_RUN_FROM_PACKAGE, Vnet Integration and public blob storage

### ISSUE THREAD

**Issue by mapoitras** [Azure/Azure-Functions#2058]
Issue:

We are attempting to configure an Azure app service with vnet integration (regional) for outbound traffic and a private endpoint for inbound traffic.  On the regional vnet integration the 'route all' toggle is set to true.

The app service is configured with a Function App.  The function app is using zip deploy, with the app config setting of WEBSITE_RUN_FROM_PACKAGE set to a blob storage account.

The app service inbound traffic is routed via an application gateway, including the SCM site to access it remotely via the private endpoint

The network which the app service in integrated with does NOT have any UDR's or NSG's that would block the outbound traffic from the app service.

Result:
In this configuration the entire app service, including SCM becomes unavailable.

Troubleshooting:
With the app service plan configured to a single worker node, the SCM runtime is stable enough to get to the SCM site.
Using the 'Process Explorer' tool in SCM (kudu) it is clear that both the w3wp.exe services are constantly crashing and rebooting - cpu time always less than 1 seconds, and the PID's change at each refresh.  This is exacerbated when multiple workers are enabled to the point you cannot access the SCM site to debug.

This seems to only happen when BOTH private endpoints and VNET integration is enabled.  We tried every permutation of private endpoints, vnet integration and the 'route all flag' - this troubleshooting was difficult because some settings take some time to apply, need a restart, etc.

We implemented a managed NAT to attempt to confirm outbound internet traffic flow from the app service was not the problem, no change in the issue.

We found the eventlog.xml in the app service logfiles folder which led us to the next step:
<Event>
<System>
<Provider Name="ZipFS"/>
<EventID>0</EventID>
<Level>1</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2021-10-06T19:28:39Z"/>
<EventRecordID>13829312</EventRecordID>
<Channel>Application</Channel>
<Computer>RD00155D7DAE80</Computer>
<Security/>
</System>
<EventData>
<Data>Failed to download zip. See the text file located in the wwwroot folder for more details. Error: 0x80070003</Data>
</EventData>
</Event>
<Event>
<System>
<Provider Name="ZipFS"/>
<EventID>0</EventID>
<Level>1</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2021-10-06T19:28:39Z"/>
<EventRecordID>13829312</EventRecordID>
<Channel>Application</Channel>
<Computer>RD00155D7DAE80</Computer>
<Security/>
</System>
<EventData>
<Data>Failure zip was generated to \\?\d:\local\SitePackages\13782843.zip</Data>
</EventData>
</Event>
<Event>
<System>
<Provider Name="ZipFS"/>
<EventID>0</EventID>
<Level>1</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2021-10-06T19:28:39Z"/>
<EventRecordID>13829312</EventRecordID>
<Channel>Application</Channel>
<Computer>RD00155D7DAE80</Computer>
<Security/>
</System>
<EventData>
<Data>Failed to copy zip from remote source.</Data>
</EventData>
</Event>

Removing WEBSITE_RUN_FROM_PACKAGE from the application config instantly stopped the w3wp crashing and allowed us access to the root default app service startup page.

At this stage the blob storage account containing the zip file was configured to be publicly available.  The zip was protected with a SAS token, but not behind any network.

We reconfigured the zip deploy blob storage account to have a private endpoint inside the same network the app service was vnet integrated into and reset the WEBSITE_RUN_FROM_PACKAGE flag.  In this configuration the functions deployed, and the problem was resolved.

Questions:
Is it expected that an app service which is vnet integrated is not able to access public network blob storage accounts when using the WEBSITE_RUN_FROM_PACKAGE flag?  Again, it seems to only happen when private endpoints, vnet integration and route all traffic flags were all enabled, but that may have been a fluke in our testing - have not tried to reproduce it again with just route all vnet integration alone

Is it expected that this configuration will completely crash the app service w3wp.exe processes and put the app into an endless loop of restarts causing the entire control plane to fail (Even the portal ground to a halt and showed that the function app runtime was not available)

We also tried to configure this with the zip deploy still public, but it did not help the issue:
https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network

**Comment by v-anvari** [comment]
Hi @mapoitras , As confirmed by the networking team, this is not an expected behavior unless you have an NSG rule to block the internet

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us or re-open this issue in case of any further queries related to this issue
