### ISSUE TITLE
Wrong function key returned by listkeys endpoint after swapping slots

### ISSUE THREAD

**Issue by iulian-popescu** [Azure/Azure-Functions#2060]
I've deployed an azure function with staging and production slot.
Sometimes, after slot swap the list keys management endpoint is returning the other slot function key, causing our application issues.
I attached the arm template of the function.

reproduction steps:

1. Deploy azure function infrastructure (deploying azure function resources using arm template)
2. Deploy azure function code for production slot
3. Deploy azure function code for staging slot 
4. Start running the script I will write below
5. Swap the slots using azure portal UI

```
$subscriptionId=''
$resourceGroup=''
$appName=''
$url = "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Web/sites/$appName/host/default/listkeys?api-version=2019-08-01"

$azureAuth = az account get-access-token | ConvertFrom-Json

$token = $azureAuth.accessToken

$headers = @{ "Authorization" = "Bearer $token"}
while(1 -eq 1){

$result = iwr -Headers $headers -DisableKeepAlive -Uri $url -Method Post | ConvertFrom-Json

$functionKey = $result.functionKeys.default
Write-Host $functionKey
$pingResult = iwr -Uri https://$appName.azurewebsites.net/api/health -Headers @{ "X-functions-Key" = $functionKey }
Write-Host $pingResult


sleep -Milliseconds 700

}
```

the api/health endpoint 

[worker_armTemplate.txt](https://github.com/Azure/Azure-Functions/files/7325247/worker_armTemplate.txt)
[scriptResult.txt](https://github.com/Azure/Azure-Functions/files/7325292/scriptResult.txt)
.

**Comment by v-anvari** [comment]
Hi @iulian-popescu , An ICM has been created[ here](https://github.com/Azure/azure-functions-host/issues/7710) and is being tracked already, closing this issue as duplicate
