### ISSUE TITLE
The type initializer for 'Microsoft.Data.SqlClient.LocalAppContextSwitches' threw an exception. Could not load file or assembly  'System.Configuration.ConfigurationManager'

### ISSUE THREAD

**Issue by sabrite** [Azure/Azure-Functions#2064]
Hey guys, I have a func app running on .NET Core 6 RC2 with func runtime 4 latest preview. The app has two projects:
1- a function app with service bus triggered function
2- a class library which acts as data layer. 

Both projects have "Microsoft.EntityFrameworkCore.SqlServer" version "6.0.0-rc.2.21480.5". The class library has additional package "EFCore.BulkExtensions" version "6.0.0-rc.2".  Both these libraries depend on "Microsoft.Data.SqlClient" and there is no conflict.
 
The dbcontext has the constructor defined like this:

`        
public AppDataContext(DbContextOptions<AppDataContext> options) : base(options)
{
    Database.SetCommandTimeout(Constants.DatabaseCommandTimeout);
    //the below lines will only work in release mode, in Azure when getting an access token instead of using a full connection string
    #if DEBUG
    var conn = (Microsoft.Data.SqlClient.SqlConnection)Database.GetDbConnection();
    conn.AccessToken = (new AzureServiceTokenProvider()).GetAccessTokenAsync("https://database.windows.net/").Result;
   #endif
}
`

the startup class in func project uses the typical AddDbContext to inject AppDataContext, passing the connection string. 

On local machine, everything works fine. But when I deploy to a func app running on Windows, targeting .NET 6, I get the following error:

`The type initializer for 'Microsoft.Data.SqlClient.LocalAppContextSwitches' threw an exception. Could not load file or assembly 
'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. `

What I have tried so far is:

1. Add System.Configuration.ConfigurationManager to both projects (although its not required as "Microsoft.Data.SqlClient" has an internal dependency on it)
2. Add "Microsoft.Data.SqlClient" to class library project.
3. Explicity FTP "System.Configuration.ConfigurationManager.dll" to bin folder in app deployment folder.
4. Tried not to use AzureServiceTokenProvider to authenticate with Sql server and instead just passed a full connection string with username and password.

and many more hacks I could think of. But nothing is working.

What am I missing there? Or is there a breaking change just like we have with app insights in v4 runtime? I really appreciate your help. Thanks,

**Comment by GeordieStew** [comment]
I've added the below to my project and seems to be working again 

    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>

**Comment by sabrite** [comment]
Yes can confirm that adding this setting to csproj file does resolve the issue. For anyone who doesnt know where exactly to jam this thing:

`<PropertyGroup>
<TargetFramework>net6.0</TargetFramework>
<AzureFunctionsVersion>v4</AzureFunctionsVersion>
<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
</PropertyGroup>
`

**Comment by sabrite** [comment]
Thanks @v-bbalaiagar that does fix it. Happy to close it if this is the official fix.

**Comment by thuijer** [comment]
> @v-bbalaiagar the fix works for now. Is it just a transitional issue between releases? When can we remove the "fix"?

Agree with @GeordieStew here, this should not be a permanent fix. Setting _FunctionsSkipCleanOutput to true might have unwanted side effects.

**Comment by evsl** [comment]
@v-bbalaiagar fix also worked out for me, totally agree with the others that this shouldn't be permanent though.

**Comment by kshyju** [comment]
Hi @sabrite If you are using 4.0.0 version of `Microsoft.NET.Sdk.Functions`, you do not need the explicit `_FunctionsSkipCleanOutput` change in your function app project file. Make sure you are not using the preview version.

You mentioned that everything works fine locally, but you are getting this error when deployed to azure. What is the runtime version you are seeing for your app ? That information should be in the "Overview" tab.

**Comment by kshyju** [comment]
@sabrite Would it be possible to share a minimal repro? A github repo link would work. Thanks!
