### ISSUE TITLE
Please support deploying function app from sub folder in root of repository

### ISSUE THREAD

**Issue by rachelxj-ms** [Azure/Azure-Functions#2065]
refer to this wiki: https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-folder-for-a-node-php-or-aspnet-site
If the folder you want to deploy is not the root of the repository, you can specify which folder to deploy. e.g.

[config]
project = MyWebRoot

This is not working for Function app with local git enabled. 
Reproduce steps:
1. create Nodejs function app
2. enable local git from deployment center
3. function app is in sub folder in root of the repository as screenshot
![image](https://user-images.githubusercontent.com/66855967/138020500-aacbce35-77ef-430f-8640-6934c0e78062.png)
4. create .deployment in the root of repository
![image](https://user-images.githubusercontent.com/66855967/138020646-34980f26-ef05-4880-85b4-487c8661c4ae.png)
5. commit the code, got error: Source and destination directories cannot be sub-directories of each other
![image](https://user-images.githubusercontent.com/66855967/138020735-6011da18-2bb9-4356-b5c0-60a1250bf35b.png)

**Comment by rachelxj-ms** [comment]
the project source code is in SubPath, which has been shown in first screenshot.

**Comment by v-bbalaiagar** [comment]
Tagging @balag0  for kudu guidance

**Comment by balag0** [comment]
I am not sure if this works for functions but the right place for this issue is https://github.com/projectkudu/kudu

**Comment by v-bbalaiagar** [comment]
Hi @rachelxj-ms, Can you open a new issue [here](https://github.com/projectkudu/kudu) as suggested above for further guidance.
 
Closing this issue here.
