### ISSUE TITLE
Azure Function app  did not support to customize the deployment directory for the code.

### ISSUE THREAD

**Issue by yongding701** [Azure/Azure-Functions#2066]
I am using the Function app module to implement service functions in the form of uploading code. In the meantime, I was going to customize the deployment directory, and referred to the documentation, I added .deployment file under the root directory to specify the deployment directory, but that didn't work.

https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-folder-for-a-node-php-or-aspnet-site

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
