### ISSUE TITLE
Azure Function V3 Net Core FixedDelayRetry  

### ISSUE THREAD

**Issue by twiga2013** [Azure/Azure-Functions#2068]
Hi,
I have an Azure Service Bus Queue Trigger Function V3 in .NET Core with the following attribute [FixedDelayRetry(1, "00:00:10")]
but the Azure Service Bus function runs 5 times. Here is the DeadLetterErrorDescription "Message could not be consumed after 5 delivery attempts."

My other question is there a way to subscribe to an event before the message goes to a deadletter queue so I can update my system. 

Thanks

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
