### ISSUE TITLE
Event Hubs Webjobs extension 4.2.0 fails with V4 function

### ISSUE THREAD

**Issue by nzthiago** [Azure/Azure-Functions#2072]
Function App name: tried locally only 
Tools used: VS Code and Core Tools
New V4 app or existing V3 app migrated to V4: Existing V3 migrating to V4 - https://github.com/nzthiago/event-processing-spark

According to https://github.com/Azure/Azure-Functions/issues/1987 the Microsoft.Azure.WebJobs.Extensions.EventHubs package version 4.2.0 should work with Functions v4 for triggering and from.
VS Code Debugging and Func start works, but throws this exception when trying to read from Event Hubs with Microsoft.Azure.WebJobs.Extensions.EventHubs 4.2.0: 
```
[2021-10-21T20:58:05.336Z] The listener for function 'EventHubTrigger1' was unable to start.
[2021-10-21T20:58:05.339Z] The listener for function 'EventHubTrigger1' was unable to start. Microsoft.Azure.EventHubs.Processor: Encountered error while fetching the list of EventHub PartitionIds. Microsoft.Azure.Amqp: Operation is not valid due to the current state of the object.
```
![image](https://user-images.githubusercontent.com/1563288/138356019-afd09670-8744-4168-b795-4823047fef38.png)

After updating Microsoft.Azure.WebJobs.Extensions.EventHubs to version 5.0.0-beta.7 and making all the code updates to use the new Event Hubs SDK type changes, it worked fine.

**Comment by alrod** [comment]
This fix is merged

**Comment by nzthiago** [comment]
@paulbatum  - I think this means #1987 should update the Event Hubs one to 4.3.0

**Comment by paulbatum** [comment]
@nzthiago done.
