### ISSUE TITLE
V4 using VS22- mismatch in AI connection string key

### ISSUE THREAD

**Issue by RohitRanjanMS** [Azure/Azure-Functions#2075]
Function App name: NA
Tools used: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 4.1
New V4 app or existing V3 app migrated to V4: New V4 app

I created and published an app using Visual Studio. I also configured AI using visual studio. VS added an entry "APPINSIGHTS_CONNECTIONSTRING" in the configuration but the function failed to start.  

Function is looking for "APPLICATIONINSIGHTS_CONNECTION_STRING", there's a mismatch in the key name.

Error message form admin/host/status
{"id":"httptriggerv4test","state":"Error","version":"4.0.0.16714","versionDetails":"4.0.0-preview.5.16714+72f5eb56fd472e76fa8d5f7e85822a870d8532ad","platformVersion":"95.0.7.554","instanceId":"b30287cbee699cda1201e2d3178d34d3ea84486afe74d0d028f6cfaaf2dbe004","computerName":"10-30-7-145","errors":["Microsoft.Azure.WebJobs.Script: The Application Insights Extension is installed but is not properly configured. Please define the \"APPLICATIONINSIGHTS_CONNECTION_STRING\" app setting."],"processUptime":234915}

**Comment by DominikErnst** [comment]
There are 3 different declarations in a Blazor Server App:

- In appsettings.json: "ApplicationInsights": {  "ConnectionString": " ... (From Template ?? appsetting.json in Blazor Server)
- APPINSIGHTS_CONNECTIONSTRING  (From Template?? wwwroot/appsetting.json in Blazor Client)
- APPLICATIONINSIGHTS_CONNECTION_STRING (From Service Dependency in Blazor Server)
