### ISSUE TITLE
Difference in user experience .NET 6 in-proc and .NET 6 isolated when executing functions in VS Code

### ISSUE THREAD

**Issue by satvu** [Azure/Azure-Functions#2077]
**Function App name:**
n/a local

**Tools used:**
- VS Code
- Azure Functions VS Code Extension v1.5.2
- `dotnet --version` = `6.0.100-rc.2.21505.57`
- `func --version` = `4.0.3780`

**New V4 app or existing V3 app migrated to V4:**

New V4 .NET 6 inproc app
New V4 .NET 6 isolated app

**Issue**
Executing an HTTP Trigger using the sample projects in a .NET 6 inproc and .NET 6 isolated app is slightly different in the user experience. I used the function execution instructions in [official documentation](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp?pivots=programming-runtime-functions-v4&tabs=in-process#run-the-function-locally).

Using the in-proc app, this pre-filled prompt shows up and you can run the function with this body. 
![inproc-functionexecutionprompt](https://user-images.githubusercontent.com/35204912/138363954-78972c84-02e2-43cc-b28e-ad4d0153efa4.png)

In the isolated app, the prompt comes up empty so unless users are already aware of what the request body should look like, it may be confusing to fill in. 

Not a **major** bug but having similar user experiences and improving the .NET isolated experience would be great.

**Comment by ejizba** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2848
