### ISSUE TITLE
Precompiled Function Template Solution for Visual Studio

### ISSUE THREAD

**Issue by logischdenker** [Azure/Azure-Functions#208]
Recently I have created the repository 

https://github.com/logischdenker/AzurePrecompiledFunctionTemplate

It is a template solution for Visual Studio 2017 based on c# and it contains enough documentation to get you started with precompiled Azure functions quickly.

Maybe you'll find it helpful and you want to add it to your samples section?

All the best
Bastian

**Comment by lindydonna** [comment]
@logischdenker Wow, very nice!  Thanks for the contribution, we will definitely help promote.

One note: if you upload function.json via FTP, triggers won't be synced for the Consumption plan. A regular app service plan is not affected. Web Deploy does sync triggers. 

The Azure Functions CLI recently added a command for publishing and **does** sync triggers. Documentation is coming soon.

**Comment by logischdenker** [comment]
@lindydonna Thank you for the note on syncing triggers!

Can you provide a link to an issue that I can follow to stay up to date regarding the documentation of Azure Functions CLI and trigger syncing?

I'd love to make use of this and I plan to write a blog entry about precompiled functions development with Azure Functions CLI.

Finally a big thank you for your awesome work on Azure Functions!

**Comment by lindydonna** [comment]
@logischdenker Actually, it looks like we are missing documentation on this altogether. I've created this issue to track: https://github.com/Azure/Azure-Functions/issues/210. And this issue tracks the runtime improvements so that things like FTP would work: https://github.com/Azure/azure-webjobs-sdk-script/issues/1300

**Comment by lindydonna** [comment]
@logischdenker Added to https://github.com/Azure/Azure-Functions/wiki/Samples
