### ISSUE TITLE
Document behavior of timer trigger when scaled out

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#209]
When using a timer trigger, a storage lock is used to ensure that only one host executes a timer when scaled out. When sharing a storage account across Function Apps, you should use a different host ID, otherwise only one will run the timer.

Update this doc: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer

**Comment by SyntaxC4** [comment]
@lindydonna Can you expand a bit further on the fix? How does one use a different Host ID? Is this something that is in the host.json?

**Comment by SyntaxC4** [comment]
It looks like the host id is a property of host.json: https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

**Comment by SyntaxC4** [comment]
It looks like the solution would be to create multiple function apps, because that is the only way to have a different host ID.

**Comment by lindydonna** [comment]
@SyntaxC4 My original note must not have not have been clear. This is all by design: a timer trigger should not execute multiple times even if a function is scaled out.

The part we need to document is that this is controlled by the host ID in host.json. So, if someone is using multiple Function Apps for dev/test, they shouldn't share host IDs.
