### ISSUE TITLE
Error while running azure functions v4 .NET 6 through Azure portal - The hostname could not be parsed

### ISSUE THREAD

**Issue by srane804** [Azure/Azure-Functions#2094]
Hi Team,

I have an existing azure function which was created in .NET Core 3.1 and runnning in production. I moved it from .NET Core to .NET 6 with V4 Azure functions. It runs without issues while debugging in my local environment. But when I deploy it to portal and try to run a specific function (which involves key vault access), I encounter the following error :

System.UriFormatException : Invalid URI: The hostname could not be parsed.at System.Uri.CreateThis(String uri,Boolean dontEscape,UriKind uriKind,UriCreationOptions& creationOptions)

Can someone kindly help me on this ?

**Comment by v-anvari** [comment]
Hi @srane804 , We would like to know how is the config setup. Are you seeing this issue locally or after you publish?

**Comment by fabiocav** [comment]
@srane804 the error shared above shows the exception coming from using Key Vault in C:\Users\ranesa1\source\repos\XYZ Microservice\App Services\XYZ Microservice\XYZ\Services\KeyVaultService.cs : 28

Can you share what this code is doing and review the details on how it is getting the configuration to initialize the service?
