### ISSUE TITLE
Slow cold starts of functions in comparison to other cloud providers

### ISSUE THREAD

**Issue by pietz** [Azure/Azure-Functions#2095]
Hey team,

I'm currently struggling with slow cold starts of Azure Functions and I'm trying to optimize it as much as I can. However running comparisons between Azure, AWS and GCP results in Azure being extremely slow no matter what I do. It seems like the larger fraction of the time is due to how Azure Functions are run under the hood and there is only little I can do about it.

It's not like Azure Functions are 5% slower or even 50% slower. They're literally 500% slower (need 5x longer) than similar code run on AWS Lambda. How can this be?

I would like to know what you're doing to address this problem. The current situation is not acceptable.

**Comment by v-bbalaiagar** [comment]
Hi @pietz, Thank you for your feedback! We would like to know what cold start you are seeing and what times do you see.
Also, Could you share the app name using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately to understand what impact it cold start for your app.
