### ISSUE TITLE
Azure Functions Monitoring Documentation

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#21]

**Comment by SyntaxC4** [comment]
This isn't specific to monitoring a Function, but does talk about monitoring a Web App with a Function: https://github.com/Azure-Samples/functions-dotnet-azure-insights-trigger

**Comment by wesmc7777** [comment]
I plan to have a draft of this one done next week to discuss by our meeting on the 27th

**Comment by lindydonna** [comment]
@wesmc7777 Add a big red or yellow note that explains that the monitoring tile in the main resource blade will always be empty for Dynamic Plan function. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/4260261/19576794/47907f56-96c9-11e6-8003-e8dfabfcf975.png)

**Comment by SyntaxC4** [comment]
The App Service CLI has the Log Tailing capabilities which work for Functions: (in ASM)

```azure site log tail -v <site-name>```

**Comment by SyntaxC4** [comment]
@lindydonna Can you clarify as to why we won't ever see monitoring data in this part for the Dynamic hosting plan?

**Comment by lindydonna** [comment]
@wesmc7777 Please work with @dariagrigoriu on this topic, as this touches on features such as Dynamic compute and the spending cap.

> When using the Consumption hosting plan for Azure Functions, the Monitoring tile in the Function App Overview blade will not show any data. This is because the platform dynamically scales and manages compute instances for you, so these metrics are not meaningful on a Consumption plan. To monitor the usage of your Function Apps, you should instead use the guidance in this article.

**Comment by wesmc7777** [comment]
@dariagrigoriu  @lindydonna Is this also true for free tier?

**Comment by wesmc7777** [comment]
https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?branch=pr-en-us-987

**Comment by lindydonna** [comment]
@wesmc7777 Customers should not use a free app service plan, as they will already get a generous free grant on the Consumption plan. However, that tile will still show data on a Free App service plan. It's very confusing.
