### ISSUE TITLE
Document deployment options related to trigger syncing

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#210]
When using a Consumption or Premium plan, any changes to triggers that are made to function.json will be synced with the central listener when using the following deployment options:
- Browser editing in functions portal
- Continuous integration and deployment
- WebDeploy 
- `publish` command in Azure Functions CLI (`func azure publish functionapp <name>`)
- [Azure Functions plugin for Serverless Framework](https://github.com/serverless/serverless-azure-functions)

The following deployment options **will not** sync triggers on a Consumption Plan, aside from HTTP triggers:
- Editing using App Service Editor, Kudu, or Visual Studio Cloud Explorer
- Modifying files directly using Azure Storage
- FTP
- WEBSITE_RUN_FROM_PACKAGE scenarios where the package content is updated out of band

In order to synchronize triggers when these deployment options are used, open the Azure Portal and click the Refresh button, or make a API call to the sync triggers endpoint: https://github.com/davidebbo/AzureWebsitesSamples/blob/master/ARMTemplates/FunctionsWebDeploy.json#L90 

Powershell sample: https://github.com/davidebbo/AzureWebsitesSamples/blob/master/PowerShell/HelperFunctions.ps1#L360-L365

**Comment by tohling** [comment]
@jeffhollan, note sure if you are the right person to ask, but is it possible to expedite an official documentation on this?

**Comment by jeffhollan** [comment]
Just stumbled on this from a blog link - apologies I missed the initial notification.  This does seem like a doc we should work to track - especially with Run-from-zip options starting to light up in tools like VS and VSTS.  While most tools at this point *should* be syncing triggers, is the world where people modify files outside of a standard deployment path and do need to know about this. @ggailey777 @tdykstra can you create a P1 item on the doc backlog to have an article (or append existing) around deployment options.  Would likely link to docs like the one on ZipDeploy, but I think layout would be:

1. Explain different options available (Portal create, WebDeploy, ZipDeploy, and Run-from-Zip) and meaning of each (or link to full doc where we have them)
1. Explain "trigger syncing" and when it may be applicable (run-from-zip pointed to an external file, or one of options called out on original issue)

**Comment by iizotov** [comment]
Please add some clarity around the `WEBSITE_RUN_FROM_PACKAGE` method. 

Looks like the Event Hub trigger doesn't get registered upon a successful deployment via `WEBSITE_RUN_FROM_PACKAGE` either. What's weird is that pinging the Function (via its URI or the Portal) kicks the trigger off but the Function a) never scales beyond 1 instance and b) eventually falls asleep. Only the Restart operation seems to kick it off properly.

Also, worth documenting explicitly that setting the `SCM_DO_BUILD_DURING_DEPLOYMENT` flag to `"true"` does not have any impact when using `WEBSITE_RUN_FROM_PACKAGE`, e.g. no `npm` or `nuget` packages will be restored during the deployment process.

**Comment by aluong** [comment]
It would be helpful to document it in the [developer section of the public docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference),  because it is not intuitive that this call is necessary is certain deployment situations.

**Comment by josephxsxn** [comment]
This is still a massive issue without any straight forward answer. The fact that in some cases you can only have 1 consumption plan trigger function seems like a mistake too as many people will be mislead by lack of docs. It took 8 hours of searching to find one blog post that mentions this problem exists.. Even after following it our function is still not triggering on EventHubs. 

https://blogs.msdn.microsoft.com/benjaminperkins/2018/08/07/why-does-my-azure-function-sometimes-stop-being-triggered/

**Comment by ColbyTresness** [comment]
I kind of disagree with this issue - shouldn't trigger sync be an implementation detail @paulbatum? Happy to include in things like our wiki, but from my perspective, this should be something that we fix, not document better.

**Comment by paulbatum** [comment]
@ColbyTresness Unfortunately we do not have a timeline for when it becomes a pure implementation detail. Couple of examples:

- user deploys code using FTP - sync triggers is not run automatically and we have no plan to address that other than telling people "please don't deploy using FTP". 
- user is using run from package with a blob SAS, and they update that blob in place. Our system does not know that the blob changed.

We will keep chipping away at this problem but neglecting to document this is a case of "perfect is the enemy of good".

**Comment by ColbyTresness** [comment]
Fair enough, I think its worth investigating the public docs around deployments. But I don't think we should explicitly mention SyncTriggers or how it works.

**Comment by jeffhollan** [comment]
@ColbyTresness are you going to track this?  Per other thread on how if you are using `WEBSITE_RUN_FROM_PACKAGE={externalURL}` you need to manually sync triggers to get it to work at all. So in order to document that deployment gesture we'll need to reference some doc that explains what call they need to make and what it does.  I'm not a huge fan either FWIW but it is what it is.  

Let me know - expect either yourself, Asavari, me, or Glenn should be owner and making sure this gets delivered in next few weeks

**Comment by ColbyTresness** [comment]
I'll do it.

**Comment by m-mertz** [comment]
Can you post the necessary ARM API call here in the meantime until the official doc gets updated? Powershell is not an option for our scenario unfortunately.

**Comment by ggailey777** [comment]
@ColbyTresness we already have a work item ([1108377](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1108377)) open to track sync triggers related stuff.

There's also a work item for a general deployment options article ([1108365](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1108365)).

**Comment by egorchabala** [comment]
Is there any updates on this? Do you have any estimates when this can be applied?

**Comment by ColbyTresness** [comment]
No real estimate, but it's in progress. It'll hopefully get done within April.

**Comment by egorchabala** [comment]
@ColbyTresness have you had implemented the fix?

**Comment by ColbyTresness** [comment]
I've finished my work and it's being reviewed, this will be released within a week or two.

**Comment by aluong** [comment]
Related to documenting the sync triggers usages, can we also correct the Rest API Spec as well, because it actually affects the expected responses in the client SDKs? Ex: the Azure Python SDKs will actually throw an exception when it receives a 200 response after calling SyncTriggers.
- https://github.com/Azure/azure-rest-api-specs/issues/1275

**Comment by mguglani** [comment]
Hi Folks,

I stumbled upon this thread as I was facing a similar issue:

https://github.com/Azure/azure-webjobs-sdk/issues/2220

@ColbyTresness can you comment if I might be running in to this problem.

**Comment by mguglani** [comment]
I have been using "func azure publish functionap" to update my Javascript.

**Comment by deathgaze** [comment]
Any updates on this issue? I've been using VS Code extension to push and test functions. Some of my functions have ceased triggering. @lindydonna 's suggestion is... opaque to me. Can someone explain to me how to get my triggers working again? Like I'm 5? I think I understand the concept that triggers can be out of sync, but I'm not clear on what I need to do or refresh to fix it in my scenario as I'm not familiar with Azure backend terminology. I just want to get my functions to work...

This is also happening on my local, not just deployed.

**Comment by jeffhollan** [comment]
@ColbyTresness you mentioned to me you were almost done with this doc? Any ETA?

**Comment by jeffhollan** [comment]
However @deathgaze it should be noted syncing triggers is an Azure Functions service specific gesture. When running local it’s unnecessary as there’s no scaling involved (from zero or to n). So if you’re having troubles with a trigger locally likely a separate issue.

**Comment by ColbyTresness** [comment]
Yeah this was delayed from 3 weeks ago, but I promise it will be released soon (I've finished the edits and review, now just waiting to publish to docs). My doc should have the clear explanation of trigger syncing you're looking for - will link to it here when it's complete.

**Comment by ColbyTresness** [comment]
I've merged this into master and it will be published shortly. Titled "Functions deployment technologies" when released (tomorrow I believe).

**Comment by ColbyTresness** [comment]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies

**Comment by Ruud-cb** [comment]
After digging I have found this issue, yet when I review my deployment and function, it should be working fine. I have similar issues with Azure storage queue falling asleep. In AppInsights I see trace logs for each queue: Stopped the listener '{listenerName}' for function '{functionName}'.

- I use ZIP deploy from Azure DevOps, so according to the docs, that should NOT require manual trigger re-sync, correct?
- 'touching' the azure function in the portal or calling a http call on the same function triggers it to become alive again.
- `FUNCTIONS_EXTENSION_VERSION` set to ~3 and Runtime version under Function Runtime Settings also set to ~3.
- Updated Microsoft.NET.Sdk.Functions to the latest version 3.0.9

Anything else I can test? Or should I move on to open a new issue elsewhere?

**Comment by paulbatum** [comment]
@Ruud-cb Yes performing a zip deploy from devops should not require any manual trigger sync actions. If you haven't already done so, I recommend you file a support ticket - you can do that directly from the Azure portal. Alternatively, file a new issue in https://github.com/Azure/azure-functions-host and fill out the template so that we have enough information to investigate.
