### ISSUE TITLE
Not able to debug Azure Logic App workflow using Visual Studio Code

### ISSUE THREAD

**Issue by AvtsVivek** [Azure/Azure-Functions#2104]
I am following [this](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code) tutorial. 

I am now able to create the workflow in Visual Studio Code, and also see that in the designer.

[![Request Response logic app in Visual Studio Code][1]][1]

But further to this, I am not able to see the url as [mentioned here](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#run-test-and-debug-locally) after clicking the overview.

[![Overview of Azure Logic App Workflow.json file in Visual Studio Code context menu][2]][2]

I get this message 

`Workflow run history could not be loaded. Error: 'Could not establish connection to the host. Run your function project to view the run history. Failed to fetch.'`

[![Overview of Azure Logic App Workflow.json file in Visual Studio Code][3]][3]

What am I missing?

[I ensured Azurite](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#storage-requirements) is running. 

[![Azurite is running][4]][4]

[NGrok](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#set-up-call-forwarding-using-ngrok) is also configured.

[![NGrok is configured][5]][5]

And my local.settings.json file looks as follows.

	{
	  "IsEncrypted": false,
	  "Values": {
		"FUNCTIONS_V2_COMPATIBILITY_MODE": "true",
		"AzureWebJobsStorage": "UseDevelopmentStorage=true",
		"FUNCTIONS_WORKER_RUNTIME": "node",
		"WORKFLOWS_TENANT_ID": "d5y4kk56-f47h-df6h-2g7k-sd4fk8f5j5zd",
		"WORKFLOWS_SUBSCRIPTION_ID": "876af6yz-6xxx-1234-2nh7-xxx234gygrkls",
		"WORKFLOWS_RESOURCE_GROUP_NAME": "vivek-logic-app-trial-rg",
		"WORKFLOWS_LOCATION_NAME": "centralindia",
		"WORKFLOWS_MANAGEMENT_BASE_URI": "https://management.azure.com/",
		"Workflows.WebhookRedirectHostUri": "http://e91c-115-96-216-18.ngrok.io"
	  }
	}

Not only that, when I press F5, I get the following error, not clear to me what it says.

`Error message: correlationId='683df22d-5928-4149-97cc-2ee3116aa6d0', operationName='SubscriptionExtensions.ToCachedSubscription', message='Resource provider namespace is empty for subscription 'myedgeenvironment', properties '{"tenantId":"myedgeenvironment-tenantId","registeredFeatures":[]}'.', exception='<null>', organizationId='', 
activityVector='IN.02', additionalProperties='', extensionVersion='1.0.0.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='683df22d-5928-4149-97cc-2ee3116aa6d0'.`

[![Not able to debug Azure Logic Apps in Visual Studio Code][6]][6]

  [1]: https://i.stack.imgur.com/FBm2b.png
  [2]: https://i.stack.imgur.com/5sDFj.png
  [3]: https://i.stack.imgur.com/Id2Y0.png
  [4]: https://i.stack.imgur.com/wkC2Q.png
  [5]: https://i.stack.imgur.com/xYe12.png
  [6]: https://i.stack.imgur.com/ErIJ4.png

**Comment by v-bbalaiagar** [comment]
Hi @AvtsVivek, Thank you for your feedback! Please let us know if you are able to solve the issue with the information provided here - https://stackoverflow.com/questions/70004463/not-able-to-debug-azure-logic-app-workflow-using-visual-studio-code

**Comment by v-bbalaiagar** [comment]
Closing this issue as resolved in the above mentioned SO, please feel free to reach back to us in case of any further queries related to this issue.
