### ISSUE TITLE
Function's resultCode in Application Insights

### ISSUE THREAD

**Issue by m-yuka746** [Azure/Azure-Functions#2106]
When I log a Function in Application Insights, the resultCode in the request table of Application Insights is set to 0 by default, except for HTTP triggers.

I cannot determine that from the following documentation.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/data-model-request-telemetry#response-code
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring

Could you please add this information to some documentation?

**Comment by v-bbalaiagar** [comment]
Hi @m-yuka746, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Opened a new document issue for further validation - https://github.com/MicrosoftDocs/azure-docs/issues/84235. Closing this issue here
