### ISSUE TITLE
Not able to debug Azure Functions in Visual Studio Code

### ISSUE THREAD

**Issue by AvtsVivek** [Azure/Azure-Functions#2107]
I am trying to do [this tutorial](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/vscode-function-app-http-trigger/tutorial-vscode-serverless-node-install?tabs=bash) to run azure function app using vs code.

I am able to [run it locally](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/vscode-function-app-http-trigger/tutorial-vscode-serverless-node-test-local#run-the-local-serverless-function), but not debug it.

[![run function app locally using visual studio][1]][1]

When I browse to http://localhost:7071/api/category, I am getting the response.

But I place a breakpoint(see the above image on line 11), it is supposed to stop, but does not.

I see a difference in the image [shown here in the docs](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/vscode-function-app-http-trigger/tutorial-vscode-serverless-node-test-local#run-the-local-serverless-function) with mine.

[![debugging azure function apps in visual studio code][2]][2]

Contrast to that, I see a square in my case (see below). Does this make a difference? 

[![debugging azure function apps in visual studio code][3]][3]

  [1]: https://i.stack.imgur.com/K0CU3.png
  [2]: https://i.stack.imgur.com/oOExj.png
  [3]: https://i.stack.imgur.com/AQUBS.png

**Comment by anthonychu** [comment]
@nturinski can you please take a look?

**Comment by nturinski** [comment]
Somewhat unhelpful, but it seems to be working on my machine 😅


Could you tell me what version of VS Code and what OS you are using?  I'm using `1.62.0-insider` currently and am on Win32.

**Comment by v-bbalaiagar** [comment]
Hi @AvtsVivek, Can you provide us the above mentioned details if you are still facing this issue.
