### ISSUE TITLE
Add documentation which explains the limitations of Azure Functions

### ISSUE THREAD

**Issue by kaushalp** [Azure/Azure-Functions#211]
There is no documentation that I could find which mentions the limits of Azure functions. This link doesn't cover Azure Functions: https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits 

The pricing page doesn't contain any useful information either. 

For example AWS lambda limits are documented here: http://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by Nosmadas** [comment]
Please can we get some cursory guidance on any limits e.g. function apps per subscription etc.

**Comment by apengwin** [comment]
Any updates on this?

**Comment by lindydonna** [comment]
@Nosmadas We don't have any limits on function apps per subscription or functions per function app. We should publish limits on things like open sockets, etc.

**Comment by ColbyTresness** [comment]
@asavaritayal @alexkarcher-msft this is a pretty valid ask from a while ago, not sure of the status

**Comment by fabiocav** [comment]
@alexkarcher-msft @asavaritayal any comments on this?

**Comment by alexkarcher-msft** [comment]
We have a doc on github, but should really add it to the official documentation. https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#numerical-sandbox-limits

Probably this doc: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale

**Comment by alexkarcher-msft** [comment]
Bringing @ggailey777 into the loop 🌞🌞

**Comment by ggailey777** [comment]
@alexkarcher-msft we need to have something for functions [here](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits?toc=/azure/billing/TOC.json). We can create an include to use in both locations. Are the Sandbox numbers the right ones for consumption plan?

**Comment by alexkarcher-msft** [comment]
Bringing in @jeffhollan to help with this supportability doc 🙂

**Comment by jeffhollan** [comment]
@alexkarcher-msft are there any recent cases for this one or just as an FYI? Just trying to help make the call from priority PoV.

And yes @ggailey777 that doc looks accurate except for the connections count. We've up'd that recently and is currently reflected correctly in the connection management doc (600 active, 1200 total)

**Comment by alexkarcher-msft** [comment]
I have triaged the cases in a while, but looking at the last few sets of notes the platform limits is the largest single bucket of tickets. Specifically connection limits + platform limits.

I'm pretty sure this is larger than just a documentation bug, and more to do with how we notify users when their function was impacted by platform limits, so it's up to you :)

**Comment by jeffhollan** [comment]
Makes sense.  Thanks @alexkarcher-msft

**Comment by alexkarcher-msft** [comment]
Bumping this thread again, as we've gotten a decent amount of requests to document the Premium plan limits. There is this this nice [table for App Service in the docs](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#app-service-limits) and I'd love a similar table for the consumption and Premium plan.

**Comment by ggailey777** [comment]
We now have a [service limits section](https://docs.microsoft.com/azure/azure-functions/functions-scale#service-limits) both in the scale article and the [main service limits article](https://docs.microsoft.com/azure/azure-subscription-service-limits#functions-limits). If you see any limits missing, please let us know. 

@alexkarcher-msft can we close this issue?

**Comment by alexkarcher-msft** [comment]
Looks perfect! I'm closing the issue :)
