### ISSUE TITLE
Azure Portal Deployment for Azure Functions

### ISSUE THREAD

**Issue by g-ollis** [Azure/Azure-Functions#2110]
Azure Function deployments through the Azure portal deploy V1 storage accounts by default.

Could this be changed to V2, Is that possible?

V1 Storage accounts should be upgraded to V2: https://docs.microsoft.com/en-us/azure/storage/common/storage-account-upgrade?tabs=azure-portal

**Comment by v-bbalaiagar** [comment]
Hi @g-ollis, Thank you for your feedback! We can upgrade a storage account as mentioned in the document here - https://docs.microsoft.com/en-us/azure/storage/common/storage-account-upgrade?tabs=azure-portal

Please let us know if you have any further queries.

**Comment by g-ollis** [comment]
@v-bbalaiagar Thanks for the response, I'm aware of upgrading this but is there a possibility instead of getting people to upgrade the storage account after they have deployed it, when someone creates a new Function App in the Azure portal it is already a Storage Account V2?

**Comment by v-bbalaiagar** [comment]
Hi @g-ollis, Apologies for the delayed response, I tried to create a new storage account in the portal. It is showing storage version 2 as default.
![image](https://user-images.githubusercontent.com/74654421/145985538-b5abc35a-fb53-4533-be09-eee0854b58cc.png)
