### ISSUE TITLE
[UX] Test/Run functions is not working in Mozilla Firefox

### ISSUE THREAD

**Issue by djshaw01** [Azure/Azure-Functions#2111]
# [UX] Test/Run functions is not working in Mozilla Firefox on Mac OSX Big Sur

## Cannot use the Test/Run functionality in Firefox on Mac OSX Big Sur 11.6.1.  Console shows React js issue:

From the Code + Test screen in the Azure Portal, click Test/Run. entire panel becomes blank, and no further action is available.

![image](https://user-images.githubusercontent.com/1314045/143925833-c67c09b5-c9f8-4636-93e3-99942f233c68.png)
Clicked on Test/Run
![image](https://user-images.githubusercontent.com/1314045/143925998-b542a790-3ae9-405d-9e6d-b42169f112d8.png)

Console
![image](https://user-images.githubusercontent.com/1314045/143926156-cbc954de-9dd3-4a8d-bd1d-1f1bb4ca0b64.png)

HAR file attached:
[portal.azure.com_Archive [21-11-29 13-56-28].har.zip](https://github.com/Azure/Azure-Functions/files/7620499/portal.azure.com_Archive.21-11-29.13-56-28.har.zip)

**Comment by btardif** [comment]
@takyyon can you please take a look?

**Comment by Ved2806** [comment]
Hi @djshaw01, You can log UX related issues on the link below.
https://msazure.visualstudio.com/Antares/_workitems/create/Bug

**Comment by djshaw01** [comment]
Okay thank you

Warm Regards

Daniel

**Comment by Ved2806** [comment]
Closing this issue as it is related to UX, please feel free to reach back to us in case of any queries related to this issue.

**Comment by djshaw01** [comment]
Ok, sorry to bug you again, but Sujeet, I do not have access to
https://msazure.visualstudio.com/Antares/_workitems/create/Bug to create
the bug

401 - Uh-oh, you do not have access.
Your account, ***@***.*** is not authorized to view this page. Make
sure the URL is correct and your account has access. View a list of

**Comment by geofb** [comment]
Same issue on Windows 10 LTSC / Firefox 96.0b5 / Firefox 95.0.1
As Daniel and I can't create or check on the msazure.visualstudio.com link, is there any other way to track this issue?
