### ISSUE TITLE
Running Azure Functions with Cosmos DB locally - cannot find CosmosDBAttribute.ConnectionStringSetting

### ISSUE THREAD

**Issue by JWATSU** [Azure/Azure-Functions#2113]
All information avaialble in this Stackoverflow post: https://stackoverflow.com/questions/70171112/running-azure-functions-with-cosmos-db-locally-cannot-find-cosmosdbattribute-c

**Comment by v-bbalaiagar** [comment]
Hi @JWATSU, Thank you for your feedback! Please let us know if you are able to solve the issue with the information provided here - https://stackoverflow.com/questions/70171112/running-azure-functions-with-cosmos-db-locally-cannot-find-cosmosdbattribute-c

**Comment by JWATSU** [comment]
> Hi @JWATSU, Thank you for your feedback! Please let us know if you are able to solve the issue with the information provided here - https://stackoverflow.com/questions/70171112/running-azure-functions-with-cosmos-db-locally-cannot-find-cosmosdbattribute-c

Hi! I just tried the fixes mentioned there. They did not work. This is what I wrote back to them:

> This did not work. Let me clarify something, "CosmosDBAttribute.ConnectionStringSetting" is something that appeared in the error message and is not some value that I had defined. I only defined it afterwards. Originally I used a value like CosmosDbConnection. I should add that I am using Java, maybe that's what's causing some issue?

**Comment by v-bbalaiagar** [comment]
Hi @JWATSU, Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by JWATSU** [comment]
It seems the issue was that the Java version differed between what we had locally (the version in our JAVA_HOME) and what the function was running. Once we matched them to both use Java 11 it works.

**Comment by v-bbalaiagar** [comment]
Hi @JWATSU , Thank you for the update. Please let us know if this can be closed as resolved or you have further queries.

**Comment by JWATSU** [comment]
I will close this issue, but I do think that it would be good if I got an error message or warnign that the versions were differing. I could have solved my issue much sooner then. Maybe something you could look at!
