### ISSUE TITLE
Azure Function fails to load System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by fgheysels** [Azure/Azure-Functions#2116]
### Description

I have an Azure Function which imports the NuGet Package `System.Configuration.ConfigurationManager` v5.0.0
The Azure Function is a .NET Core 3.1 app and targets Azure Functions v3.

When I start the function, it crashes with a FileNotFoundException:

```
 System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```
When I look at my filesystem, I notice that the assembly System.Configuration.ConfigurationManager.dll is not present in the `netcoreapp3.1\bin` folder, whereas all my other assemblies that I require in my function are there.
However, the assembly is present in the `netcoreapp3.1` folder.

When I downgrade to a previous version (4.7.0), I don't have this issue. (I can also see that the assembly System.Configuration.ConfigurationManager.dll is now present in the `netcoreapp3.1\bin` folder.

### Configuration

.NET Core 3.1
Azure Functions v3
Targetting a Linux App Service

### Regression?

As mentionned in the description, it works with version 4.7.0 of System.Configuration.ConfigurationManager in a .NET Core 3.1 app.

### Other information

I have a small github repo where this problem is reproduced: https://github.com/fgheysels/FunctionApp_ConfigurationManagerIssue

Probably related to https://github.com/dotnet/runtime/issues/627
Originally posted [here](https://github.com/dotnet/runtime/issues/54642), but it seems that this is a better location for this problem.

**Comment by v-bbalaiagar** [comment]
Hi @fgheysels, Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by ajkimberley** [comment]
I am experiencing the same issue but targeting .NET 6.0 with Azure Functions v4. I have tried targeting System.Configuration.ConfigurationManager v.6.0.0, v5.0.0 and v4.7.0, but all I experience the same runtime issue with all of these.

**Comment by ajkimberley** [comment]
Apologies, I spoke to soon. After upgrading Microsoft.NET.Sdk.Functions from 4.0.0-preview2 to 4.0.1, I now no longer get the runtime when importing System.Configuration.ConfigurationManager v.6.0.0.

**Comment by fijsh** [comment]
Looks like I can workaround this issue in .NET Core 3.1 by adding 
a property to the project file like:

<PropertyGroup>
  <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
</PropertyGroup>

 Not sure yet if this causes side effects somewhere.

**Comment by v-bbalaiagar** [comment]
Hi @fgheysels , Let us know if the above information resolves your query, or if you have any further queries.

**Comment by fgheysels** [comment]
Hi, the `_FunctionsSkipCleanOutput` fixes the issue, but imho this is merely a workaround and not a clean solution ?

**Comment by fabiomaulo** [comment]
The *workaround* by @fgheysels saves my day (and night too).

**Comment by swagozaurus** [comment]
Here's what helped me:

I moved my project to another computer where I had a newer .NET Framework 4.8.1 and I got this error.
I installed .NET Framework 4.6.2 (originally I was using 4.6.1) and it ran with no errors.
