### ISSUE TITLE
ServiceBusTrigger connection ignoring TransportType=AmqpWebSockets

### ISSUE THREAD

**Issue by alexbenitez** [Azure/Azure-Functions#2119]
Function App name: (local)
Tools used: Visual Studio 2022/net6, Core Tools Version:       4.0.3971, Function Runtime Version: 4.0.1.16815 
New V4 app or existing V3 app migrated to V4: New

Hello, I have a Function App with a ServiceBusTrigger running local (e.g. debugging) in a development VM with port 5671 blocked. Sending messages (or polling) is not a problem (AmqpWebSockets option works OK). However, receiving with ServiceBusTrigger does not work. Note that I also tried appending TransportType=AmqpWebSockets (or TransportType=1)  to the connection string. Still does not work (I found a post at StackOverflow describing exactly the same issue). Because of this issue, I am forced to use a TimerTrigger to receive the messages in order to debug.

The same code with ServiceBusTrigger does work in another machine that does not have port 5671 blocked. Same, everything is OK when deployed to Azure.

Is there any way to make the ServiceBusTrigger work with AmqpWebSockets the same way it does work when sending messages (so the debugger can be used in a corporate network typically with port 5671 blocked)?

PS: an easy way to reproduce the problem is by blocking port 5671 with the Windows Firewall and attempt receiving messages (using the ServiceBusTrigger).

**Comment by guudan** [comment]
I am having same issue. Did not found any good way of changing transport type of the trigger to Amqp Web Socket to make it working in my corporate environment.

**Comment by guudan** [comment]
After digging deeper I was able to solve my issue by adding following startup class to my Azure Functions project.

```
using AzureFunctions;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Hosting;
using Microsoft.Extensions.Hosting;
using System;

[assembly: WebJobsStartup(typeof(Startup))]
namespace AzureFunctions
{
    public class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            if (IsLocalDevelopmentEnvironment)
            {
                builder.AddServiceBus(options =>
                {
                    options.TransportType = Azure.Messaging.ServiceBus.ServiceBusTransportType.AmqpWebSockets;
                });
            }
        }

        private bool IsLocalDevelopmentEnvironment => Environment.GetEnvironmentVariable("AZURE_FUNCTIONS_ENVIRONMENT") == "Development";
    }
}
```

**Comment by alexbenitez** [comment]
Thanks, @guudan ! It works flawlessly. My Azure Function uses `Startup : FunctionsStartup` . Id did not occur to me to create a second setup class to configure WebJobs (e.g. `IWebJobsStartup`) in order to configure the service bus. Now able to debug service bus trigger.

Thanks again!
