### ISSUE TITLE
Performance difference between App Service Plan and Consumption Plan

### ISSUE THREAD

**Issue by UnoSD** [Azure/Azure-Functions#212]
It would be useful to have performance indications in the documentation. Our team has done some testing and it looks like Azure Functions is massively slower than a .NET Core app on a F4 VM performing the same job (by 3-4 times on avg).

The Azure Function is running on a Consumption Plan so we do not have control over the scaling.

I presume the delay is due to the allocation of resources and we will do some testing to verify this does not apply to the App Service Plan, too.

Can this be clarified/explained for us (and maybe somehow included in the documentation)?

**Comment by yochay** [comment]
Can you provide more information to the actual workload you are running? Is it HTTP trigger, EventHub, Q?

**Comment by UnoSD** [comment]
@yochay sure; it's basically an HTTP triggered function sending a message to a service bus queue and, of course, same pattern in the .NET Core app. Thanks.

**Comment by lindydonna** [comment]
One big reason for the difference will be the VM size--F4 is much larger than the A1 that we use on the Consumption plan. Could you try running the test again on a smaller VM?  You're essentially comparing a 1 core VM to a 4 core one.

**Comment by UnoSD** [comment]
@lindydonna thanks for the response. That would explain it, unfortunately the team is no longer working on that project, but I presume there is no way of having a consumption plan running on higher specs borrowed VMs?

**Comment by lindydonna** [comment]
@UnoSD That's correct, on a consumption plan you can't choose the VM size. You can instead run on an App Service plan to have more cores.

**Comment by UnoSD** [comment]
@lindydonna thanks for the explanation, hope this will be available in the future as the consumption plan is really useful to handle unexpected spikes without having to scale up the app service plan in advance.
