### ISSUE TITLE
How to allow incoming traffic from azure (blob) storage for event grid azure function trigger.

### ISSUE THREAD

**Issue by gsamal** [Azure/Azure-Functions#2128]
We have a azure function app deployed with app service plan and it contains an event grid trigger function. The function can be triggered using https webhook. We use the following webhook to invoke the trigger when a new blob is created.
```
https://<function-app>.azurewebsites.net/runtime/webhooks/EventGrid?functionName=<function_name>&code=<system-key>
```

It was working fine but now we want to introduce vnet and also apply incoming traffic restrictions. For different reasons, we can't map the storage account to the vnet. So I would like to add an access rule that says incoming traffic from an azure storage account should able to access the function runtime.

Is that something that we can configure here? Would be fine to check other workarounds if any.
![image](https://user-images.githubusercontent.com/11225010/146127511-1fe66aae-ccf3-423c-b02d-87271583456f.png)

Thanks in advance!

**Comment by v-bbalaiagar** [comment]
Hi @gsamal,  Thank you for your feedback! Here is a blog post which addresses similar scenario where the blog talks about securing access to and from azure functions - https://blog.baeke.info/2019/04/29/securing-access-to-and-from-azure-functions/

Please check and let us know if this helps.

**Comment by gsamal** [comment]
@v-bbalaiagar thanks for sharing the doc. I am familiar with configuring the vnet but my requirement was on how to allow Storage endpoint points to access Azure function when they are not in vnet.

To be more clear, I have:
- An azure function linked to a vnet.
- An app service also linked to the vnet.
- The azure function has a incoming rule allowing the app service vnet. Now the app service can access the azure function.
- I have another storage account that I can't put in the vnet. It also has a trigger to the same azure function.

Problem is when the Blob trigger fires it fails because of access restrictions I assume. Since the Blob storage is not a vnet, I can either specify the ip of it or sepcifiy it as a generic Service f.e. AzureCloud. Thus I am looking at the latter option. I don't think the storage account has an ip, does it? If not, can I add a generic access rule saying any Azure storage account can acess the function app?

**Comment by v-bbalaiagar** [comment]
Hi @gsamal, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Tagging @balag0 / @pgombar  ,  for more inputs

**Comment by balag0** [comment]
@gsamal Shouldn't it be the function app that needs access to the storage account and not the other way?
Also can we simplify the scenario as - a function app in VNET needs to connect to a storage account outside the VNET?
