### ISSUE TITLE
Add documentation that input properties in binding expressions require a POCO definition

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#213]
I created a related issue in the SDK repo here to explore improving the error message: https://github.com/Azure/azure-webjobs-sdk/issues/1066. This issue links to the SO post with the details.

I looked for doc on this (e.g. here) but didn't find anything that really helps. I don't see anything that mentions that you must define a POCO bound to your input in C#/F# in order to use input properties in binding expressions.

**Comment by lindydonna** [comment]
@mathewc Thanks for filing this issue, I'm improving the doc now with the example from your SO post here: http://stackoverflow.com/questions/42829465/accessing-documentdb-from-azure-functions-with-dynamic-documentid

One question: can the input properties be on an input binding as well as a trigger?  In your example, you used an HTTP trigger.

**Comment by lindydonna** [comment]
Handled in https://github.com/Microsoft/azure-docs-pr/pull/10001

**Comment by lindydonna** [comment]
Done, see [Bind to custom input properties in a binding expression](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#bind-to-custom-input-properties-in-a-binding-expression)
