### ISSUE TITLE
Error while decoding Avro data with NodeJS

### ISSUE THREAD

**Issue by ArunAdPushup** [Azure/Azure-Functions#215]
Hi,

I am using ``Azure EventHubs archive`` to store my event hubs data to an azure blob storage. Eventhubs archive stores the data in ``avro`` format. I've written an ``Azure function`` in ``NodeJS`` that listens to the blob trigger event (fired whenever data is sent to Eventhubs and written to the blob storage in ``avro`` format). 

I am using the [avsc](https://github.com/mtth/avsc) library for doing this. 

As soon as the trigger is fired, I want to decode the data sent in ``avro`` format (which is a binary buffer) and convert it into ``json``. 
I tried using the ``fromBuffer`` method by specifying my ``avro`` schema, but it keeps giving me this error - 
```
TypeError: this.buf.utf8Slice is not a function
```
Here's my code - 

```
const avro = require('avsc');

module.exports = function (context, myBlob) {
    const schema = avro.Type.forSchema({
        "type" : "record",
        "name" : "EventData",
        "namespace" : "Microsoft.ServiceBus.Messaging",
        "fields" : [ {
            "name" : "SequenceNumber",
            "type" : "long"
        }, {
            "name" : "Offset",
            "type" : "string"
        }, {
            "name" : "EnqueuedTimeUtc",
            "type" : "string"
        }, {
            "name" : "SystemProperties",
            "type" : {
            "type" : "map",
            "values" : [ "long", "double", "string", "bytes" ]
            }
        }, {
            "name" : "Properties",
            "type" : {
            "type" : "map",
            "values" : [ "long", "double", "string", "bytes", "null" ]
            }
        }, {
            "name" : "Body",
            "type" : [ "null", "bytes" ]
        } ]
    });

    if(myBlob.length){
        context.log("JavaScript blob trigger function processed blob \n Name:", context.bindingData.name, "\n Blob Size:", myBlob.length, "Bytes");
        context.log(schema.fromBuffer(myBlob)); // myBlob contains the binary avro buffer data
    }
    context.done();
};
```

**Comment by brettsam** [comment]
@mamaso -- could this be another situation where we're not presenting the expected data type in node?

**Comment by mamaso** [comment]
@ArunAdPushup what does your `function.json` look like? You need to have `"dataType": "binary"` set on your blob trigger. If you do not you'll be triggered with a string. Try `context.log(typeof myBlob)` to see what type you have in your node function.

**Comment by ArunAdPushup** [comment]
Yes this was exactly the issue, changing the ``dataType`` to ``binary`` fixed the problem.
