### ISSUE TITLE
Slow/Incomplete Function Monitor Logs live Stream

### ISSUE THREAD

**Issue by ben-002** [Azure/Azure-Functions#2151]
I recently migrated a function from .net core 3.1 (with Azure function v3) to .net 6 (with Azure function v4). 
Before migrating, I was able to see the logs live in the function Monitor -> Logs section. Even now, if I select Filesystem Logs,  they are live. however, if I switch to App Insights Logs things move really slow. The logs are either partial or missing. On very rare occasions the a log is complete.  
I even let Monitor open for several minutes but had no success. All this time, the logs were actually saved in Application Insights, but not shown in Monitor.

Is this a known issue? Or is there a configuration to set in order to solve it?

**Comment by v-bbalaiagar** [comment]
Hi @ben-002 , Thank you for your feedback!  Can we know how you are configuring host.json file.
Meanwhile, Can you check the configuration as mentioned here - https://github.com/MicrosoftDocs/azure-docs/issues/25912#issuecomment-469145500

**Comment by ben-002** [comment]
Hey @v-bbalaiagar ,
This is my host.json file:
```json
{
    "version": "2.0",
    "aggregator": {
        "batchSize": 1000,
        "flushTimeout": "00:01:00"
    },
    "logging": {
        "logLevel": {
            "default": "Warning",

            "Function.MyFunctionName": "Information",

            "Host.Aggregator": "Information",

            "Host.Results": "Information"
        },
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "maxTelemetryItemsPerSecond": 20,
                "excludedTypes": "Exception;Request;Dependency;Trace", 
                "includedTypes": "PageView;Event" 
        }
    },
    "extensions": {
        "serviceBus": {
            "prefetchCount": 10,
            "messageHandlerOptions": {
                "autoComplete": false,
                "maxConcurrentCalls": 10,
                "maxAutoRenewDuration": "00:03:00"
            }
        }
    }
}
