### ISSUE TITLE
![Screenshot 2022-02-04 180126](https://user-images.githubusercontent.com/20049529/152614499-53ba4fc5-8d87-43af-ae09-a79a86ff0fc9.png)

### ISSUE THREAD

**Issue by dpomt** [Azure/Azure-Functions#2159]
Hi,
have exact same issue here. Function stopped working.
Any ideas? Where can I found the host.json to try the workaround?

![Screenshot 2022-02-04 180126](https://user-images.githubusercontent.com/20049529/152614499-53ba4fc5-8d87-43af-ae09-a79a86ff0fc9.png)

_Originally posted by @pchevallier in https://github.com/Azure/Azure-Functions/issues/1987#issuecomment-1030416179_

**Comment by pchevallier** [comment]
@dpomt unless you are using Visual Studio to develop and deploy your function in which case, you can access those files using this new portal (still in preview but pretty handy):
![image](https://user-images.githubusercontent.com/20049529/152970304-02b58de2-1e2c-42bb-8046-e3a3905fac14.png)
It gives you access to all your development files:
![image](https://user-images.githubusercontent.com/20049529/152970972-9c71f16a-33f2-474c-a222-f25c9a34ca8e.png)

**Comment by dpomt** [comment]
@pchevallier Thanks. I changed host.json to  "version": "[2.8.4, 3.0.0)" but still have same issue with

**Comment by dpomt** [comment]
I had restarted the  function app and error was still present.
However, I have just re-opened Azure function app page and there is no issue any more.

Thanks a lot for your support - this helped me a lot.

**Comment by dpomt** [comment]
Hi @v-bbalaiagar,
manually changing the host.json file as described above and restarting the function app  solved the problem for me.
Thanks!

**Comment by v-bbalaiagar** [comment]
Closing this issue as resolved, please feel free to reach back to us in case of any further queries related to this issue.
