### ISSUE TITLE
Azure Function started to throw errors when opened in portal

### ISSUE THREAD

**Issue by sergsalo** [Azure/Azure-Functions#216]
Errors are about two properties: 
WEBSITE_CONTENTSHARE
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING

It tells me that I now need to add these two properties, otherwise my function would not work. 

Are these required now? If someone can provide more details I would really appreciate.

**Comment by lindydonna** [comment]
How did you create your Function App?  If you create it from the portal or Visual Studio, those properties should be added.

If you created it from an ARM template, follow this sample: https://www.yammer.com/azureadvisors/#/Threads/show?threadId=857091106

**Comment by sergsalo** [comment]
ARM template. the link you shared requires subscription

**Comment by lindydonna** [comment]
@sergsalo Oops, copy-paste problem. Fixed the link.

**Comment by lindydonna** [comment]
Closing the issue as it is already documented.
