### ISSUE TITLE
VS C++ Redistributable not in Azure Function Environment 

### ISSUE THREAD

**Issue by joshlincoln** [Azure/Azure-Functions#217]
Hi,

Is there any chance we can get the [VS C++ 2015 Redistributable]( https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed into the Azure Functions environment?

There are certain libraries which I am wanting to use with Azure Functions which require this, such as Tesseract.

As far as I can tell, this doesn't exist in the Azure Function environment, and there is no way for users to install it.

**Comment by CiprianMo** [comment]
Any updates on when will vs c++ 2015 redistributable be available in azure functions ?
