### ISSUE TITLE
Storage account recommendation for Azure Function

### ISSUE THREAD

**Issue by Zoe1808** [Azure/Azure-Functions#2172]
Currently we just use one storage account for an Azure Function App. To improve performance, we are planning to separate the storage account.
Option 1: Use 3 storage accounts. One for function app, one for durable function and one for storage related trigger function.
Option 2: Use 2 storage accounts. One for function app, another for both durable function and storage related trigger function.

Which option would be better?

**Comment by v-bbalaiagar** [comment]
Hi @Zoe1808 , Thank you for your feedback!  We will check for the possibilities internally and update you with the findings. Meanwhile, can you please check the document here - https://docs.microsoft.com/en-us/azure/azure-functions/storage-considerations#storage-account-requirements

Please check and let us know if this helps.

**Comment by Zoe1808** [comment]
@v-bbalaiagar Thanks. We would split the function default storage account for sure.

As a following up question, If we want to change the function storage account, do we only need to update the value of AzureWebJobsStorage and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING (pointing to new storage account connection string) in staging slot and redeploy the function app then swap? Is there any other thing we should take care of?
AFAIK, the function storage stores all the function triggers' metadata, do we need to sync these infos to the new storage account?
