### ISSUE TITLE
Azure Functions v3 deadlock issue

### ISSUE THREAD

**Issue by roberAlb** [Azure/Azure-Functions#2181]
Some async actions that took 15-20 mins, they are not finishing now or taking hours. We have checked inside kudu in the eventlog.xml and we have found errors related with this

**One error**:*"Microsoft.AspNetCore.Server.Kestrel EventId: 22 Heartbeat took longer than "00:00:01" at "03/15/2022 10:10:56 +00:00". This could be caused by thread pool starvation."

**Second error**: "Application: w3wp.exe CoreCLR Version: 4.700.21.35901 .NET Core Version: 3.1.18 Description: The application requested process termination through System.Environment.FailFast(string message). Message: The operation 'ListBlobs' with id 'xxxxxxxxxx' did not complete in '00:02:00'. Hit maximum number (5) of timeouts. Terminating the process to mitigate potential deadlock. Stack: at System.Environment.FailFast(System.String) at DurableTask.AzureStorage.TimeoutHandler+<>c.<.cctor>b_5_0(System.String) at DurableTask.AzureStorage.TimeoutHandler+<ExecuteWithTimeout>d4`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DurableTask.AzureStorage.TimeoutHandler+<ExecuteWithTimeout>d4`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], DurableTask.AzureStorage, Version=1.9.4.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd]].ExecutionContextCallback(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DurableTask.AzureStorage.TimeoutHandler+<ExecuteWithTimeout>d4`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], DurableTask.AzureStorage, Version=1.9.4.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd]].MoveNext(System.Threading.Thread) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DurableTask.AzureStorage.TimeoutHandler+<ExecuteWithTimeout>d4`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], DurableTask.AzureStorage, Version=1.9.4.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd]].MoveNext() at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) at System.Threading.Tasks.Task.RunContinuations(System.Object) at System.Threading.Tasks.Task.FinishContinuations() at System.Threading.Tasks.Task`1[[System.Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System._Canon) at System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise.Invoke(System.Threading.Tasks.Task) at System.Threading.Tasks.Task.RunOrQueueCompletionAction(System.Threading.Tasks.ITaskCompletionAction, Boolean) at System.Threading.Tasks.Task.RunContinuations(System.Object) at System.Threading.Tasks.Task.FinishContinuations() at System.Threading.Tasks.Task`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(Boolean) at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetFromTask(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessInnerTask(System.Threading.Tasks.Task) at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessCompletedOuterTask(System.Threading.Tasks.Task) at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InvokeCore(System.Threading.Tasks.Task) at System.Threading.Tasks.UnwrapPromise`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(System.Threading.Tasks.Task) at System.Threading.Tasks.Task.RunOrQueueCompletionAction(System.Threading.Tasks.ITaskCompletionAction, Boolean) at System.Threading.Tasks.Task.RunContinuations(System.Object) at System.Threading.Tasks.Task.FinishContinuations() at System.Threading.Tasks.Task.FinishStageThree() at System.Threading.Tasks.Task.FinishStageTwo() at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread) at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() "

The interesting thing is that they work properly when we debug the functions using the local storage. We have read that this could be related with the deadlock trying to access the storage account but we are not sure if even it could be fixed or it's something related to the framework.

**Comment by v-bbalaiagar** [comment]
Hi @roberAlb , Thank you for your feedback! Could you please give us the function invocation Id and region to get the logs and check the cause.

**Comment by roberAlb** [comment]
@v-bbalaiagar  thanks for your comment. This is the Id ["938ce5d527f14c909f8c32ac4568ad12"] and the region is West Europe.

**Comment by v-bbalaiagar** [comment]
Apologies for the delay in response. This issue was somehow missed, we will be further investigating this issue and update the progress.
