### ISSUE TITLE
Better support for EF Core ConnectionStrings in Azure Functions Isolated

### ISSUE THREAD

**Issue by LucaMozzo** [Azure/Azure-Functions#2183]
Since migrating to Azure Functions v4 isolated process, I struggled with Connection Strings and EF Core more than any other project.

The 2 pain points that I want to report are:

**1. Fetching connection strings in a way that works in Azure and locally**
In order to use DI to inject an EF DbContext or any database service, the only way I could find to load connection strings was to use something like
```
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(_ =>
    {
        _.AddDbContext<MyDbContext>(options =>
            options.UseSqlServer(Environment.GetEnvironmentVariable("SQLAZURECONNSTR_MyConnectionString")));
    }
...
```
the problem with the code above is that it works in Azure, but not locally. On the other hand, looking for the environment variable `ConnectionStrings:MyConnectionString` works locally but not in Azure.

**2. EF Core scaffolding command doesn't support Azure Functions configuration for named connection strings**
The second issue that I found is that `dotnet ef dbcontext scaffold` relies on  `appSettings.json` to read named connection strings. This means that in the EF scaffolding script I have to copy the connection string (which is then added to the generated code and can only be overridden at runtime using the code I shared above), as named connection strings in `local.settings.json` are not detected.

### Features requested

- [ ]  Native support for loading Connection Strings in code OR ability to load them in a consistent way across Azure and the development environment
- [ ]  Use of a configuration that is supported by EF Core for named connection strings

**Comment by LucaMozzo** [comment]
@v-bbalaiagar thanks. I don't exclude the fact that I'm doing things wrong, but I did look at all the docs I could find!

**Comment by sofiaxtdev** [comment]
I got frustrated a today because can't execute the "dotnet ef dbcontext scaffold Name=ConnectionStrings:xyz" command. 
The exception thrown was "A named connection string was used, but the name 'ConnectionStrings:xyz' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information."

**Comment by tomaszpychynski** [comment]
I have got the same isssue in .NET 7 and dotnet-isolated.

local.settings.json :
"ConnectionStrings": {
"MyConnectionString": "<connection string>"
}

In code I read variable like this:
Environment.GetEnvironmentVariable("ConnectionStrings:MyConnectionString")

When I run this locally it works but after deploy to Azure I have got an error:
[Error] An error occurred using the connection to database '' on server ''. System.InvalidOperationException: The ConnectionString property has not been initialized.

Of course I set variable in Azure Function Configuration:
![Settings](https://user-images.githubusercontent.com/32390084/210338150-2b39fba7-3bac-4678-9083-34440b9f1d41.png)

**Comment by keisenb** [comment]
I'm running into the same issue. I have my connection string stored in local.settings.json 

`  "ConnectionStrings": {
    "DefaultDbConnection": ""
  }
`

but when I run 

`dotnet ef dbcontext scaffold Name=ConnectionStrings:DefaultDbConnection "Pomelo.EntityFrameworkCore.MySql"`

I get this error

A named connection string was used, but the name 'ConnectionStrings:DefaultDbConnection' was not found in the application's configuration. Note that named connection strings are only supported when using 'IConfiguration' and a service provider, such as in a typical ASP.NET Core application. See https://go.microsoft.com/fwlink/?linkid=850912 for more information.

Do I have to have a separate appsettings.json file or is there something I'm missing?

**Comment by AlexHolmes4** [comment]
This is still not clear, and is a high risk item for projects.
