### ISSUE TITLE
Error: Failed to sync triggers for function app

### ISSUE THREAD

**Issue by ckarcz** [Azure/Azure-Functions#2190]
Hi all,

My Azure Functions deployment from VSTS (Azure DevOps) fails with:

```
2022-03-29T18:29:08.7561306Z ##[error]Error: Failed to sync triggers for function app 'pex-app-auto-tagger-func4-qa'. Error: BadRequest - Encountered an error (InternalServerError) from host runtime. (CODE: 400)
```

The functions run locally just fine. A similar project with functions deploys just fine with same configurations and dependencies.

There is just not enough information logged in VSTS for me to know what the problem with deployment is. 😞 
There are no logs in the SCM UI, nor the Azure Function FTPs.

**Comment by balag0** [comment]
@ckarcz Looks like this has been working now?
Also another place to check is application insights (and I think that should have the error details in this scenario)

**Comment by ckarcz** [comment]
> @ckarcz Looks like this has been working now? Also another place to check is application insights (and I think that should have the error details in this scenario)

i got it to work, but how i'm not sure. i removed every dependency and slowly added them one by one back again. maybe it was a function services thing that went away. i can't say. i will close this ticket. thanks for investigating.
