### ISSUE TITLE
Unable to deploy function after adding Microsoft.Azure.Devices.Client

### ISSUE THREAD

**Issue by Fuchio** [Azure/Azure-Functions#2194]
Some details:
Windows 10
.NET 6
Azure Functions 4
VS Code

Hey all, hopefully someone can help me out here because I'm stuck. I am trying to create an Azure function with a cron trigger that reads an API and sends the data to IoT Hub. This works fine as long as I run it locally. However, when I try to deploy it gives me the error "Failed, reason: socket hang up" after 5 minutes of waiting at "Zip package size: 1.55MB".

I created a new function app; started adding functionality and deployed after each part. This works until I add "using Microsoft.Azure.Devices.Client". When I remove this library, it still doesn't work with the exact same code that I deployed a few minutes earlier. Edit: After fully removing the package I can deploy again, so the problem is definitely in the package.

Code that I can deploy:
```
using System;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace Company.Function
{
    public class Function
    {

        [FunctionName("Function")]
        public void Run([TimerTrigger("0 */1 * * * *")]TimerInfo myTimer, ILogger log)
        {
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }
    }
}

```

Code that I can not deploy:
```using System;
using Microsoft.Azure.Devices.Client;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace Company.Function
{
    public class Function
    {
        private static DeviceClient deviceClient;

        [FunctionName("Function")]
        public void Run([TimerTrigger("0 */1 * * * *")]TimerInfo myTimer, ILogger log)
        {
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }
    }
}
```

How can I add Microsoft.Azure.Devices.Client to my Azure Function?

UPDATE 1: "dotnet add package Microsoft.Azure.Devices.Client" is enough to make it crash on deployment... Runs fine locally. Really getting annoyed.

**Comment by Fuchio** [comment]
The issue might have somehow fixed itself. I waited a day, deployed the exact same code snippet/project and now it works.

**Comment by v-bbalaiagar** [comment]
Hi @Fuchio , let us know if this can be closed or you have further queries.
