### ISSUE TITLE
Update C# POCO Binding Docs

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#22]
https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/sample/HttpTrigger-CSharp-Poco/function.json

**Comment by wesmc7777** [comment]
I expect to have a draft of this one by the end of next week

**Comment by SyntaxC4** [comment]
Here is the doc that it needs to go in: https://azure.microsoft.com/en-us/documentation/articles/functions-reference-csharp/

**Comment by SyntaxC4** [comment]
This is probably a good example to show off #load if there isn't already a doc that covers this

**Comment by SyntaxC4** [comment]
@christopheranderson Should this be more of a serialization topic? I feel as though there are 1000 different articles online which would give great examples on how to serialize C# to XML or JSON

**Comment by christopheranderson** [comment]
I mean, it touches serialization. I think the idea was to show how to use POCO to strongly type your expected data coming in. I also like your #load idea to hint towards sharing common data models.

**Comment by wesmc7777** [comment]
Placed an example using #load with a shared POCO object here...

https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp?branch=pr-en-us-1204#reusing-csx-code
