### ISSUE TITLE
Consuming event hub events stops when not observed

### ISSUE THREAD

**Issue by erikogenvik** [Azure/Azure-Functions#220]
# The summary
It appears that my Javascript Function which consumes event from an EventHub only does this when I have a web browser open and observing the log stream. The moment I close the lid on my laptop and the log stream connection is severed the consumption stops. As soon as the web browser is reactivated the consumption resumes.
# Expected result
Azure Functions keeps consuming messages in an EventHub at all times.
# Actual result
Azure Functions only consumes messages in an EventHub when being observed from the developer portal.
# Details
I'm running Azure Functions with Consumption Plan on North Europe. The setup is an IoTHub which sends events on to SAS which puts them into an EventHub which is consumed by a Javascript Azure Function.
I've verified the strange behaviour multiple times now: consumption only happens when I'm actively watching the log stream through the Azure Portal.
As soon as I disconnect the consumption stops.
When later on I reconnect to the Azure Portal and start observing the function logs consumption restarts, now with a large pent up list of events from the Event Hub.

**Comment by erikogenvik** [comment]
This might be a duplicate of https://github.com/Azure/Azure-Functions/issues/122
I've changed my connection string by removing the EntityPath parameter. Let's see how it behaves during the evening.

**Comment by M-Andy** [comment]
Having the same problem. I trigger my function via an event from Event Hub. Nothing happens. As soon as I open my function in the Azure Portal all the queued events trigger the function and it executes multiple times.

Using West Europe Consumption Plan.

I can't try the workaround that removes the EntityPath from the connection string as my connection string does not contain an EntityPath. My Event Hub Connection String looks like this:

Endpoint=sb://XXXXX.servicebus.windows.net/;SharedAccessKeyName=XXXXX;SharedAccessKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=

[#122](https://github.com/Azure/Azure-Functions/issues/122) has been closed but I dont think its solved?!!

Suggestions appreciated :)

**Comment by brettsam** [comment]
@M-Andy, @erikogenvik -- are either of you still hitting this issue?

**Comment by erikogenvik** [comment]
Changing the connection string by removing the "EntityPath" fixed the issue.
I would suggest that this issue report remain open until the underlying issue is fixed; when I initially looked for a solution it took me a while to find a workaround since #122 had been closed, even though the issue remained.

**Comment by M-Andy** [comment]
My "stopping when not observed" part seems to be solved. I still have problems though. Sometimes the function stops working after hours, sometimes after days. Currently I dont have the time to look into that so I restart the function when it stops. I´m not sure if these issues (stopping when not observed and stopping after some time when not observed) are related.

**Comment by tohling** [comment]
@M-Andy, are you using a non-default consumer group?

**Comment by M-Andy** [comment]
I use the default consumer group 
("Generalized from resource: '/subscriptions/XXXXX/resourcegroups/myResName/providers/Microsoft.EventHub/namespaces/DataDisplay/eventhubs/myEvents/consumergroups/$Default'.") 
which is added automatically when I connect from Azure Functions using the "EventHubTrigger-CSharp" template.

**Comment by tohling** [comment]
@M-Andy, when you mention that it stops working, is it possible that there are no more events to be processed?  Is there a constant stream of traffic in your EventHub's $Default consumer group?

**Comment by M-Andy** [comment]
The stream stops sometimes and is not constant. But I thougth that being able to trigger the function occasionally was one reason why people used the connection EventHub - Functions App...

The thing is that sometimes the function is no longer triggered when new events come in. It kind of "died" instead of just "sleeping"

**Comment by tohling** [comment]
@M-Andy, yes you are correct.  If there are events coming in, even sporadically, the Function should have processed those events when they appeared in your Event Hub.  During the time when the stream has unprocessed events, the Function should have executed and ran your Function code.

I understand that you may not have time to look into this.  But when you get a chance, kindly include your Function App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly). Also, include a sample UTC time where you expected it to trigger and it didn't.  I will help investigate.

**Comment by M-Andy** [comment]
Thanks! I'll look into it as soon as possible.

**Comment by jtjk** [comment]
Hi, I have same issue. TrackerFunctionApp2 stops getting triggered. It was triggered correctly around yesterday 14.00 UTC but not anymore 20.00 UTC.

**Comment by brettsam** [comment]
@jtjk -- We've been looking through the logs to try to determine why your trigger stopped firing. Would you be able to share your function code with us? It may help us track down some of the things we're seeing. If it's easy enough to paste here, that works -- or if you'd rather not share it publicly, can you zip it up and send to the email address in my profile?

**Comment by lindydonna** [comment]
Closing due to lack of response. If you see the error again, please open a new issue.
