### ISSUE TITLE
Bicep Deployment Causing InternalServerError (BadRequest)

### ISSUE THREAD

**Issue by ajkimberley** [Azure/Azure-Functions#2203]
I have a bicep file (see attached) which I am using to deploy my Azure Function App, Azure Functions, and an Event Grid Topic and Subscriptions which have the Azure Functions as endpoints.

When I deploy this app, I get the following error message:

>{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"},{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"},{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n
}\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"},{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"},{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\":
[\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered
an error (InternalServerError) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"},{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n
\"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"},{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"},{"code":"BadRequest","message":"{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\",\r\n \"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"Encountered an error (InternalServerError) from host runtime.\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"}]}}

When I look at the resources in the portal after such a deployment, I find that the Functions appear to have deployed ok, but some of the Subscriptions have failed to deploy.

When I look at the Deployments section of the Resource Group I am deploying to, if I try and redeploy the failed deployment, I see that it is actually the Functions that are apparently failing to deploy, despite them actually appearing in the Function App after deployment. What is more confusing is that, each attempt at deployment results in a _different_ set of Functions failing to deploy.

I have also noticed that if I reduce the number of Functions in the Bicep file to <  ~15 no errors get produced (it appears to be indeterminate how many, but typically < 15 results in no error).

So it appears something is going wrong with the Functions deployment which is then resulting in the associated Event Grid Subs for those Functions not getting deployed - but, oddly, the Functions themselves are getting deployed.

Note, I am declaring the Functions in the Bicep file purely to add the Resource Ids of those Functions as the endpoints of the Subscriptions. I then do a ZIP deploy of the actual Function source code as a separate step after the Bicep deployment. Could it be this that's causing the issue?

[main.bicep.txt](https://github.com/Azure/Azure-Functions/files/8618626/main.bicep.txt)

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @ajkimberley The failure in this case is in publication of the pipeline. Please refer this [documentation](https://docs.microsoft.com/en-us/azure/data-factory/tutorial-control-flow-portal) and let us know if it is helpful.

**Comment by Ved2806** [comment]
Hi @ajkimberley Is this issue resolved?
