### ISSUE TITLE
Disabled Service Bus triggered Azure Function is still executed

### ISSUE THREAD

**Issue by winiarski91** [Azure/Azure-Functions#2205]
According to [docs](https://docs.microsoft.com/en-us/azure/azure-functions/disable-function) it should be possible to disable function via Disable attribute. Unfortunately it does not work with Service Bus triggered function. Function seems to be disabled according to Azure Portal UI, but it is still executed when message appears on ASB subscription.

I tried various combinations:
- using [Disable]
- using [Disable("variable_name")]

None of them work as expected. Message is consumed by Azure Function.

**Functions worker runtime:** dotnet-isolated
**Functions extension version:** v4
**Target framework:** .NET 6

Package references:
```
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.0.0-beta.6" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights" Version="1.0.0-preview4" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.30" />
```

```
    [Disable]
    [Function("AssetPublisher")]
    public async Task Run(
        [Disabled, ServiceBusTrigger("%ServiceBusTopic%", "%ServiceBusSubscription%", Connection = "ServiceBusConnectionString")]
        string input,
        FunctionContext functionContext)
    {
      // code
    }
```

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/9538522/166906732-caba5040-4823-4905-954e-fadcdb8cdd20.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/9538522/166908366-e51844cc-3a3b-4261-aa76-c76a48996e8b.png">

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @winiarski91 The [Disabled] attribute is not supported in dotnet isolated. The best way to disable it is through the app settings. Please refer [this document](https://docs.microsoft.com/en-us/azure/azure-functions/disable-function?tabs=portal) and let us know if it helps. Thanks.

**Comment by winiarski91** [comment]
Thank you for clarification!
