### ISSUE TITLE
Azure Functions v4 - Can't bind Queue to type 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue'

### ISSUE THREAD

**Issue by mswilson4040** [Azure/Azure-Functions#2208]
I am trying to upgrade my current v3/dotnet 3.1 function to v4/.net 6. However, when I follow the instructions [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=in-process%2Cazure-cli%2Cv4&pivots=programming-language-csharp#migrating-from-3x-to-4x), I am met with dependency issues. I believe the issue is partly because Microsoft.NET.Sdk.Functions has a dependency on WindowsAzure.Storage 9.3.1 which is deprecated.

Code Example:
```
    [FunctionName("test")]
    public static async Task RunAsync([TimerTrigger("0 */5 * * * *")] TimerInfo myTimer, ILogger log,
        [Queue("some-processor", Connection = "AzureWebJobsStorage")] CloudQueue cloudQueue)
    {
        log.LogInformation($"C# Timer trigger function executed at: {DateTime.UtcNow}");
    }
```

Result:

> [2022-05-10T16:15:21.819Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'test'. Microsoft.Azure.WebJobs.Host: Can't bind Queue to type 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue'.
> [2022-05-10T16:15:21.819Z] Possible causes:
> [2022-05-10T16:15:21.819Z] 1) Tried binding to 'Azure.Storage.Queues.QueueClient, Azure.Storage.Queues, Version=12.10.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' but user type assembly was 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue, Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
> [2022-05-10T16:15:21.819Z] 2) Tried binding to 'Azure.Storage.Queues.QueueClient, Azure.Storage.Queues, Version=12.10.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' but user type assembly was 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue, Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.

I am running Azure Core Tools 4.0.4483 locally. In this [article](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp), it mentions to install Microsoft.Azure.WebJobs.Extensions.Storage.Queues --version 5.0.0 but when doing so, you are met with the same errors. I believe there is a conflict between this package and WindowsAzure. But, since Microsoft.NET.Sdk.Functions requires it, you can't uninstall it.

[Company.FunctionApp1.zip](https://github.com/Azure/Azure-Functions/files/8663356/Company.FunctionApp1.zip)

**Comment by JoachimL** [comment]
I, too, am experiencing this. Are there any known workarounds?

**Comment by Ved2806** [comment]
Hi @JoachimL Thank you for the feedback, we will discuss this internally and let you know about the findings soon!

**Comment by mikegoatly** [comment]
@Ved2806 Same issue here - keen to know if there has been any outcome from your discussions!

**Comment by VladBitiusca** [comment]
Same thing here. Any news or clues on what actions need to be taken?

**Comment by kiranmaiparcha** [comment]
I am facing the same issue. Do we have any workaround?
 Microsoft.Azure.WebJobs.Host: Error indexing method 'ParseFunction'. Microsoft.Azure.WebJobs.Host: Can't bind Queue to type 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue'.
[2022-06-30T00:44:00.579Z] Possible causes:
[2022-06-30T00:44:00.579Z] 1) Tried binding to 'Azure.Storage.Queues.QueueClient, Azure.Storage.Queues, Version=12.10.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' but user type assembly was 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue, Microsoft.WindowsAzure.Storage, Version=9.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
[2022-06-30T00:44:00.580Z] 2) Tried binding to 'Azure.Storage.Queues.QueueClient, Azure.Storage.Queues, Version=12.10.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' but user type assembly was 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue, Microsoft.WindowsAzure.Storage, Version=9.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.

**Comment by fabiocav** [comment]
This is a limitation of the isolated model today, as documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=isolated-process%2Cextensionv5&pivots=programming-language-csharp#usage).

**Comment by fabiocav** [comment]
We have work currently in progress to improve the type binding experience in OOP, and will be posting updates in the worker repo as we work on that [here](https://github.com/Azure/azure-functions-dotnet-worker/discussions).

Closing as answered, but please let us know if you have any additional questions. Thanks!

**Comment by mikegoatly** [comment]
> This is a limitation of the isolated model today, as documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=isolated-process%2Cextensionv5&pivots=programming-language-csharp#usage).

@fabiocav I'm not running using the isolated model though - I'm running in-process and still see this error on upgrading. I don't think the OP's sample was running isolated either?

Is it really the case that there's no way to run an .NET 6 Azure Function app with a Queue trigger in any model?

**Comment by mikegoatly** [comment]
@fabiocav Sorry to pester, but I'd really like to understand whether it's expected that there's no way to run a .NET 6 function app with a Queue trigger binding (in-process *or* isolated). If it really is expected, then as I see it, the only version of .NET we're expected to use with Queue triggers is .NET Core 3.1.

I'm just looking for a little clarity around the situation in case we have to move away from Azure Functions and re-engineer our solutions before .NET Core 3.1 reaches end of support in December.

**Comment by mikegoatly** [comment]
@tleclaire Co-incidentally I was looking at this again yesterday. I tried to create my own minimal repro and found that it was all working fine there, so I was pretty sure it was something in our solution that was causing the problem. Your comment was very timely and pointed me in the right direction, so thanks!
