### ISSUE TITLE
Trust Center - HIPAA

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#221]
Sorry for opening this issue over here, but I believe it will be easier for you guys to route internally. In the following page, there's no mention to Azure Functions as covered services:

https://www.microsoft.com/en-us/TrustCenter/Compliance/HIPAA

**Comment by lindydonna** [comment]
CC @yochayk and @christopheranderson

**Comment by cbockman** [comment]
This is important to us as well--any clarifications would be very helpful.  Thank you!

**Comment by yochay** [comment]
We are working on the certification and expect to complete the process  by July 2017

**Comment by hmoen** [comment]
Hi @yochay, could you provide an update on the certification? Thank you.

**Comment by rob3c** [comment]
It appears they're covered now, according to the above Trust Center link. This can probably be closed.

**Comment by lindydonna** [comment]
Yes, Functions is now HIPAA compliant. Thanks for the reminder!
