### ISSUE TITLE
RetryPolicy - how does it work?

### ISSUE THREAD

**Issue by MhAllan** [Azure/Azure-Functions#2210]
I believe retry policy information and function executions count and status are all save in storage account, but there is no docs confirm that. Also we need to know how to access the number of retries executed in the SDKs and how to purge these retries information wherever they are stored.

**Comment by Ved2806** [comment]
Here is the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp) which contains storage information and you can find information related to the no of retries [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.retrycontext?view=azure-dotnet). Hope you find it helpful, please let us know. Thanks
