### ISSUE TITLE
Azure functions v4 net 6 on Linux

### ISSUE THREAD

**Issue by Pivomer** [Azure/Azure-Functions#2211]
I have developed an Azure Function `v4` with `.net 6.0.` It contains one triggered function.
![image](https://user-images.githubusercontent.com/4147698/168301973-90ca0b00-760e-4a05-beba-c18a6a90fea1.png)

Locally everything works fine. After deploying it to Azure it works fine for all plans with `Windows OS` but it doesn't work for plans: `Premium(EP1)` and `App Service Plan(P1V2)` (except `Consumption`) with `Linux`. 

I get the error message: "*Error: Error "SyntaxError: Unexpected token S in JSON at position 0" occurred while parsing the response body - Service Unavailable.*". Here is my not working config. Please note I'm using `Premium(EP1)
![image](https://user-images.githubusercontent.com/4147698/168302420-72956846-4c95-40ae-a518-15e46efbf088.png)

The same function is working fine on plans `Premium(EP1)` with `Windows OS`, `Consumption` with `Linux`
![image](https://user-images.githubusercontent.com/4147698/168302504-16b05ca3-092e-4342-8326-bb9758d26170.png)

My goal is to run Azure function `v4` with `.net 6.0.` on `Linux` on the plan `Premium(EP1)`

**Comment by Ved2806** [comment]
Hi @Pivomer Thank you for the feedback, we will discuss this internally and let you know about the findings soon!

**Comment by Pivomer** [comment]
Hi, @Ved2806 I have a function "azfun-scm-ecosystem-indexer-dev
" and I tried to upgrade it. But after getting an error I returned to .net 5 and started an experiment on the test function "func-prem-d1-lnx", please check.

**Comment by jacob7395** [comment]
FYI I have had the same issue, when deploying to a .net 6 azure function. It works when I use Y1 but not on B1.

I received the following error when deploying from vs code.

```
6:14:01 PM 014726-batch-azure-functions: Starting deployment...
6:16:02 PM 014726-batch-azure-functions: Creating zip package...
6:16:06 PM 014726-batch-azure-functions: Zip package size: 13.2 MB
6:18:09 PM: Error: Error "SyntaxError: Unexpected token S in JSON at position 0" occurred while parsing the response body - Service Unavailable.
```

Here is the terraform I used to deploy a failing recourse (a bit hacky but where still developing).

```
resource "azurerm_service_plan" "function" {
  name                = "${var.project}-batch-api-service-plan"
  location            = azurerm_resource_group.batch.location
  resource_group_name = azurerm_resource_group.batch.name
  os_type             = "Linux"
  sku_name            = "B1"
}

resource "azurerm_linux_function_app" "function" {
  name                       = "${var.project}-batch-azure-functions"
  location                   = azurerm_resource_group.batch.location
  resource_group_name        = azurerm_resource_group.batch.name
  service_plan_id            = azurerm_service_plan.function.id
  storage_account_name       = azurerm_storage_account.function.name
  storage_account_access_key = azurerm_storage_account.function.primary_access_key

  app_settings = {
    # ISSUE WITH KEYVAULT ACCESS REQURES ME TO USE VALUE
    "VaultUri"            = "${azurerm_key_vault.main.vault_uri}"
    "AzureWebJobsStorage" = azurerm_key_vault_secret.function-storage-connection-stirng.value
    # "AzureWebJobsStorage"           = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.function-storage-connection-stirng.versionless_id})"
  }

  site_config {
    always_on       = true
    app_scale_limit = 5
  }

  identity {
    type         = "UserAssigned"
    identity_ids = ["${azurerm_user_assigned_identity.identity.id}"]
  }

  tags = var.tags
}

```

**Comment by Pivomer** [comment]
Hi, @Ved2806 Do you have any updates?

**Comment by kshyju** [comment]
@jacob7395 Is your function app in-proc or isolated?

**Comment by jacob7395** [comment]
@kshyju I believe It failed when I used a B1 instance.

**Comment by Pivomer** [comment]
Hi, @Ved2806. Did you have a chance to check the issue with the Azure Function? The issue in our prod env.

**Comment by jacob7395** [comment]
Are people still having issues with this, I'm away from work so haven't been able to test?

**Comment by jacob7395** [comment]
@Pivomer are you still getting this issue?

**Comment by Pivomer** [comment]
@jacob7395 It's fixed, thanks.

**Comment by Ved2806** [comment]
Hi @Pivomer Closing the issue as it is fixed. Thanks.
