### ISSUE TITLE
Improve the ARM template article

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#222]
The ARM template article needs some updates (https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code):

- [x] Use the term Azure Resource Manager in both the title and the left nav. I'm seeing customers consistently fail to find this article.
- [x] The link for "Create a Consumption plan-based Azure Functions app" is pointing to an old commit. It needs to point to master.
- [x] (Nit) Use bullet points and possibly an H3 section to link to the sample quickstart templates, to make them easier to find.
- [x] The settings `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` and `WEBSITE_CONTENTSHARE` are not documented. These are required for the Consumption plan, and define where the Function App filesystem (source code, content files, and logs) are stored. Without these settings, the Function App will not work. See https://github.com/Azure/azure-quickstart-templates/blob/master/101-function-app-create-dynamic/azuredeploy.json#L75

**Comment by SyntaxC4** [comment]
Thanks @lindydonna I definitely want to rework this article a little bit more. I thought the structured worked out initially, but i'm definitely seeing the same observations as you are.

**Comment by SyntaxC4** [comment]
Some other items to track: 

- [ ] Providing a full ARM template at the bottom of the screen
- [ ] Providing a “Deploy to Azure” button such that the full template can be deployed
- [ ] Adding a sample Repository (with links), such that they can better understand the structure of the repository which is deployed.
- [ ] Adding a separate deployment step for WebDeploy Deployments, which is an option if you don’t use one of the integrated source control methods.

**Comment by lindydonna** [comment]
@SyntaxC4 Great ideas!  Feel free to add to the original issue.

**Comment by atrauzzi** [comment]
Remember that not everyone can run WebDeploy.  You'll probably want to include deployment examples for platforms where it's not available as well.

**Comment by lindydonna** [comment]
First round of changes are in progress at https://github.com/Microsoft/azure-docs-pr/pull/14057

Other changes are traced in #314
