### ISSUE TITLE
cannot easily use the newer HttpClientJsonExtensions Class

### ISSUE THREAD

**Issue by Spirch** [Azure/Azure-Functions#2223]
create new **azure function** from visual studio 2022, default template
add **using System.Net.Http;**
create a new http client, 
call **httpClient.PostAsJsonAsync** 

by default it will use the extension from **System.Net.Http.HttpClientExtensions** from assembly **System.Net.Http.Formating**, dependency coming from **Microsoft.NET.Sdk.Functions** --> **Microsoft.Azure.WebJobs.Extentions.Http** --> **Microsoft.AspNet.WebApi.Client** (and maybe somewhere else)

if you want to use the newer extensions https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions?view=net-6.0

normally you should be able to simply add
**using System.Net.Http.Json;**

but you must remove the **using System.Net.Http;** because it will still use the other one, a kind of name collision?, which mean the line that create the http client will need to be explicit

var httpClient = new **System.Net.Http.** HttpClient();

instead of

var httpClient = new HttpClient();

on a side note, if you use the "implicitusing" feature you must also disable / remove it otherwise you will never be able to use the new extensions

**Comment by Ved2806** [comment]
Hi @Spirch Thank you for the feedback, We will check this issue internally and let you know about the findings soon. Thanks.

**Comment by Ved2806** [comment]
Hi @Spirch This issue has been resolved in the latest version
