### ISSUE TITLE
Missing text resource 'ibizafication_ReadOnlyDotnetIsolated' in Azure Portal

### ISSUE THREAD

**Issue by kirodge** [Azure/Azure-Functions#2224]
1. Create an isolated process function.
2. Go to "Code + Test" in the portal
3. The message "ibizafication_ReadonlyDotnetIsolated" is shown
![image](https://user-images.githubusercontent.com/17931520/170993400-ce159924-0070-47fa-a4b8-22e60e08c9a4.png)

**Comment by wajidali** [comment]
Have this been resolved yet?

**Comment by Digital-Composition** [comment]
I have Azure Functions with FUNCTIONS_WORKER_RUNTIME": "dotnet" that allow me to run/test code. Is this a bug or a limitation of "dotnet-isolated"?

**Comment by ryansan** [comment]
Can we not run functions from the portal when using dotnet-isolated?

**Comment by tomaszpychynski** [comment]
Have this been resolved yet?

**Comment by AlbertCalvet** [comment]
BTW am I the only one wondering what the hell means ibizafication? 🏝️

**Comment by Digital-Composition** [comment]
> BTW am I the only one wondering what the hell means ibizafication? 🏝️

It means that the MS engineers in charge of Azure Functions went to Ibiza and haven't returned since then.

**Comment by shimedh** [comment]
This will be fixed by end of next week - 4/21

**Comment by LeeIsMe77** [comment]
> This will be fixed by end of next week - 4/21

Is there any update on the status of this fix, and thread https://github.com/Azure/azure-functions-dotnet-worker/issues/1033?  Both of them have gone silent this week after an expected fix by last week.

**Comment by kshyju** [comment]
Closing as this issue does not exist anymore. please open a new issue if you experience problems.
