### ISSUE TITLE
Linux hosted functions stopped working

### ISSUE THREAD

**Issue by seerj30** [Azure/Azure-Functions#2225]
From today (31-05-2022) all my Linux Azure Functions stopped working.

In the portal, under `Functions`, the following error is displayed: "Azure Functions runtime is unreachable".
Every function has its own storage account and does not have any firewall setting.

No errors are displayed in the Azure status portal but seem to be something wrong on your side because I tried the following:
- I've created two new Linux Functions (DOTNET 3.1 and 6) and none works
- I also created two new Windows Functions (DOTNET 3.1 and 6) and both works

The same issue was reported [here](https://docs.microsoft.com/en-us/answers/questions/871371/linux-hosted-function-apps-get-suddenly-34azure-fu.html).

**Comment by pascostefan** [comment]
We are facing the same issue, Linux functions not working since around 11 AM UTC, Windows functions working. West Europe.

**Comment by jan-source** [comment]
same here for linux functions. For new created linux function app, function code cannot not be successfully published with `func azure functionapp publish`. 
Response status: `response status code does not indicate success: 503 (Site Unavailable)`. All runtimes are python 3.9. 
SKU in service plan is Y1.

**Comment by frol25** [comment]
Same issue for me. Running .NET 6 Azure Function on Linux in West Europe.

**Comment by seerj30** [comment]
Started to work today morning
