### ISSUE TITLE
Azure Function EventHub Trigger receiving request but some requests don't trigger the function

### ISSUE THREAD

**Issue by haorzhan** [Azure/Azure-Functions#2226]
My Azure function is receiving messages from EventHub as I can see in App Insights from the request count. However, not all requests are triggering the function. One weird thing though, while I am running my tasks synchronously, each request is fulfilled. When I run the tasks in the async method and use await Task.WhenAll(), some requests are not fulfilled. When I check the App Insights through operation id or invocation id, I can only find 1 request records. Any idea about the issue?

**Comment by haorzhan** [comment]
`[Function("function1")]
        public static void Run([EventHubTrigger("eventhub", Connection = "connectionstring", ConsumerGroup = "consumergroup")] string[] input, FunctionContext context)
        {
            var logger = context.GetLogger("trigger");
            logger.LogInformation("Get {0} requests {1}", input.Length.ToString(), context.InvocationId);
            
            List<Task<double>> taskList = new List<Task<double>>();
            Task<double>[] taskArray = new Task<double>[queryList.Count];
            int index = 0;

            foreach (Query query in queryList)
            {
                logger.LogInformation("Request {0}: start execution", query._requestId);
                taskArray[index] = ExecuteMdmRequest(cert, logger, query);
                index++;
            }
            CancellationTokenSource source = new CancellationTokenSource();
            CancellationToken token = source.Token;

            try
            {
                Task.WaitAll(taskArray, 20000, token);
            }
            catch (OperationCanceledException e)
            {
                logger.LogInformation("Query Cancellation Exception{0}", e.Message);
            }
            catch (AggregateException e)
            {
                for (int i = 0; i < e.InnerExceptions.Count; i++)
                {
                    logger.LogInformation("Query Exception{0}", e.InnerExceptions[i].ToString());
                }
            }
        }
public static async Task<double> ExecuteMdmRequest(X509Certificate2 cert, ILogger logger, Query query)
        {
            logger.LogInformation("Request {0}: executing", query._requestId);
            var queryTimer = new Stopwatch();
            queryTimer.Start();

            IQueryResultListV3 results = await reader.GetDataAsync(query);

            logger.LogInformation("Request {0}: Finish execution", query._requestId);
            queryTimer.Stop();

            TimeSpan timeTaken = queryTimer.Elapsed;
            return timeTaken.TotalSeconds;
        }
`

**Comment by Ved2806** [comment]
Hi @haorzhan Please try to pass a list of requests as a parameter to the await Task.WhenAll() method. Let us know if that helps.
