### ISSUE TITLE
Dotnet Post Build Event Breaks Build

### ISSUE THREAD

**Issue by Spaceman1861** [Azure/Azure-Functions#2227]
I think this falls under " issues with the Functions Visual Studio tooling" but if I'm wrong apologies please redirect me :).

I am trying to generate an open api json spec for my function app html endpoints after every build.

It works if I:

1. Remove the PostBuildCustom
2. Build the app
3. Run the script manually

It doesnt work if I:

1. Add the PostBuildCustom
2. Build the app (This throws the error in the build below).
3. Then I try and run the script anyway and it throws the same error.

Im not sure what happening. :(

This is the projfile:

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <TargetFramework>net6.0</TargetFramework>
            <AzureFunctionsVersion>v4</AzureFunctionsVersion>
            <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
            <OpenApiDocumentName>2.0</OpenApiDocumentName>
            <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        </PropertyGroup>
        <ItemGroup>
            <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.3.0" />
            <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
        </ItemGroup>
        <ItemGroup>
            <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            </None>
            <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
            </None>
        </ItemGroup>

        <Target Name="PostBuildCustom" AfterTargets="PostBuild">
            <Exec Command="powershell.exe $(SolutionDir)Scripts\generateOpenApi.ps1 -ProjectPath $(ProjectDir)" />
        </Target>
    </Project>

This is the script

    param (
        [string]$ProjectPath
    )

    function Get-ChildProcesses ($ParentProcessId) {
        $filter = "parentprocessid = '$($ParentProcessId)'"
        Get-CIMInstance -ClassName win32_process -filter $filter | Foreach-Object {
            $_
            if ($_.ParentProcessId -ne $_.ProcessId) {
                Get-ChildProcesses $_.ProcessId
            }
        }
    }

    $func = $(Get-Command func).Source.Replace(".ps1", ".cmd")
    $user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name

    Write-Host "----|> Starting"
    Write-Host "----|> $ProjectPath"
    Write-Host "----|> $user"

    try
    {
        $x = Start-Process "$func" @("start --no-build --prefix bin/Debug/net6.0") -NoNewWindow -PassThru
        Write-Host "----|>"$x.Id

        # wait some time, etc.
        Start-Sleep 2

        # Send request to the function app and save it to swagger.json
        Invoke-RestMethod -Method Get -Uri http://localhost:7071/api/openapi/v2.json | ConvertTo-Json -Depth 100 | Out-File -FilePath v2.json -Force
    }
    finally {
        Get-ChildProcesses $x.Id | Foreach-Object {
            Write-Host "----|>"$_.ProcessId
            Stop-Process -Id $_.ProcessId
        }
    }

This is the error that is thrown:

    No job functions found. Try making your job classes and methods public. 
    If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) 
    make sure you've called the registration method for the extension(s) in your startup code 
    (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

**Comment by Ved2806** [comment]
Hi @Spaceman1861 Try downgrading the version of Microsoft.Extensions.Logging.Abstractions to 2.2.0. let us know if it helps

**Comment by Spaceman1861** [comment]
@Ved2806 Sorry for the slow reply I dont have Microsoft.Extensions.Logging.Abstractions installed in any project in the solution so I cant downgrade it :(

**Comment by Spaceman1861** [comment]
In addition I added the package and ran the same test with the same result.

**Comment by Spaceman1861** [comment]
@Ved2806 No the problem remains
