### ISSUE TITLE
When you download an Azure Function that was started in the portal, it doesn't open as a function project

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/Azure-Functions#223]
I created an Azure Function in the portal for a bot I'm working on.
I eventually downloaded it. After installing the Azure function tools for Visual Studio 2015, I noticed I could create new fn projects in VS and get a full debugging experience. However, when opening the solution downloaded, all I saw was a list of solution files and a "func.exe" at the root of the solution.
It seems that when using the tooling to create a new project, a csproj of type, .funproj is created, but when downloading from the portal, no such file is made.

**Comment by lindydonna** [comment]
Did you download the project from the Bot App or from the Function App?

**Comment by irwinwilliams** [comment]
Bot App.

**Comment by lindydonna** [comment]
Then this is actually an issue for the Bot App portal. I'll point them to the issue for follow up.

**Comment by lindydonna** [comment]
@irwinwilliams Could you post a question on StackOverflow with the tag Bot Framework? http://stackoverflow.com/questions/tagged/botframework

**Comment by raisingcode** [comment]
Not sure if this will help but if you create Function App its tied to an underlying storeage account file container that can mapped to directly or can copy its contents down through a tool like azcopy
