### ISSUE TITLE
Property name converted to lowercase

### ISSUE THREAD

**Issue by morozenkomv** [Azure/Azure-Functions#2233]
Function App name: nt-prro-manager
Tools used: VS Code
New V4 app or existing V3 app migrated to V4: new V4

Property name converted to lowercase. It happens when pass the object to response.

```
var model = new CompanyModel() { CompanyId = Guid.NewGuid(), FULL_NAME = "", C_STI_MAIN = 1 };
return new OkObjectResult(model);
```
![image](https://user-images.githubusercontent.com/17346853/174483132-e24b0322-1d41-4f40-9305-589dbe5ae271.png)

**Comment by kshyju** [comment]
It is not lowercase, but camel**C**ase. It is by design.

**Comment by Ved2806** [comment]
Hi @morozenkomv Is this issue resolved for you? can it be closed?

**Comment by morozenkomv** [comment]
Issue wasn't resolved. I used PascalCase property names, it fix my issue. I didn't check, may be this bug already fixed.

**Comment by Ved2806** [comment]
Hi @morozenkomv Do you still need any help with this?

**Comment by morozenkomv** [comment]
Ho @Ved2806, did you check this issue on your side? I can do it for you and confirm is it fixed or no.

**Comment by Ved2806** [comment]
Hi @morozenkomv, This is working for me

**Comment by morozenkomv** [comment]
I'm able to reproduce this issue. Here is a test [function](https://nt-log-manager.azurewebsites.net/api/case_issue_test?code=GZ72XNkbgT9nDJx_Ykj_5J_qHjiEoM6tz-vedca1RiCuAzFu3V9Kug%3D%3D).
![image](https://user-images.githubusercontent.com/17346853/179028005-04f5bdbd-2428-4d21-8d61-a549532aabca.png)

**Comment by Ved2806** [comment]
Hi @morozenkomv, It converts the property names to the camel case by default when all the letters are capital.

**Comment by morozenkomv** [comment]
Hi @Ved2806, very strange rule, isn't it? How can I disable case conversion?
By the way, `CompanyId` was converted as well, but it's not in the capital case. So it looks more like a bug, not a rule.

**Comment by morozenkomv** [comment]
Hi @Ved2806, why this issue is closed? It still reproduced on production. I think there shouldn't be implicitly conversations.

**Comment by syammehar** [comment]
I ended up converting my object response to JSON string and used Microsoft.AspNetCore.Mvc.ContentResult instence to return IActionResult from my azure function.
` return new Microsoft.AspNetCore.Mvc.ContentResult()
            {
                Content = JsonConvert.SerializeObject(resp),
                ContentType = "application/json; charset=UTF-8",
                StatusCode = 200
            };`

**Comment by fchb1239** [comment]
I ran into the same issue as well, I know I can manually convert it to JSON (As that's what I've been doing for months/years now), but I'd rather have this removed by default.
Thanks
