### ISSUE TITLE
Getting Client-IP from Azure Functions - .NET Isolated

### ISSUE THREAD

**Issue by Pritesh-Patel27** [Azure/Azure-Functions#2237]
I have seen many solutions of getting client IP address which are from Azure Functions .Net 3.1, 6, JavaScript, etc.
Our Project belongs to .NET Core 6 Isolated Version. So, can you help me how to get the Client-IP using **HttpRequestData** class present in **HttpTrigger .Net 6 Isolated** Azure Function?
I have tried the following code snippets to get, but unfortunately failed:

1. **var remoteAddress = req.HttpContext.Connection.RemoteIpAddress;**

To try this line, I'm not getting the HttpContext object of request.

1. Few Code snippets present in this [SO Reference](https://stackoverflow.com/a/37583005) are not working in .NET 6 Isolated.

2. Found another [SO Reference](https://stackoverflow.com/questions/67795531/what-is-the-proper-way-to-access-properties-in-a-url-in-isolated-azure-functions) which given me the code snippet of .NET 5 Isolated, but that doesn't worked for me in the same version of .NET 5 isolated also.

**Comment by satvu** [comment]
@Pritesh-Patel27 We will investigate this internally and see if we can validate the 3 code snippets.

**Comment by Pritesh-Patel27** [comment]
I was finally able to retrieve it by using the code below.

Please note that the header value "x-forwarded-for" is only available when hosted within azure.

```
public async Task<HttpResponseData> SendMessage(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequestData req,
    FunctionContext executionContext, 
    string requestName)
{
    var headerDictionary = req.Headers.ToDictionary(x => x.Key, x => x.Value, StringComparer.Ordinal);
    var key = "x-forwarded-for";
    if (headerDictionary.ContainsKey(key))
    {
        IPAddress? ipAddress = null;
        var headerValues = headerDictionary[key];
        var ipn = headerValues?.FirstOrDefault()?.Split(new char[] { ',' }).FirstOrDefault()?.Split(new char[] { ':' }).FirstOrDefault();
        if (IPAddress.TryParse(ipn, out ipAddress))
        {
            var ipAddressString = ipAddress.ToString();
        }
    }
}

```In my case the retrieved value contained the following value "105.224.244.204, 147.243.88.136:58088" The first IP address in the list contains the client IP address.

I also discovered that I could have retrieved it with key value "x-azure-clientip". The reason for this is the function is hosted behind Azure Front Door.

The link goes into more detail about what headers can be expected on the request when hosted behind Azure Front Door https://docs.microsoft.com/en-us/azure/frontdoor/front-door-http-headers-protocol

**Comment by Ved2806** [comment]
Hi @Pritesh-Patel27 Please let us know if this issue is resolved for you or you still need some inputs from us?

**Comment by sopelt** [comment]
@Ved2806 it was looking for clarification if using the X-Forwarded-For header is the only and correct way for getting the client IP with recent, isolated Azure functions. If you could point towards documentation or confirm that here would be much appreciated.

**Comment by GrahamTheCoder** [comment]
Warning: I think this no longer works as of dot net 8 - there is nothing in the request with the request IP
(the break is likely in the sdk library I updated to get to dotnet 8, since it's still broken on net7 if I just roll back the target framework)
I think it's just broken for "bring your own functions" to static web apps, it may work in other cases.

**Comment by amitdixit** [comment]
X forwarded for not working anymore .


Net help urgently

**Comment by jnappi** [comment]
X-Forwarded-For is not accessible from an Azure Function running as dotnet-isolated.  This reproduced in the attached sample.  

There are three azure function projects function that simply responds with the value in X-Forwarded-For header.  In the first one the value is returned, in the other two its empty.

```
        [FunctionName("GetForwarded")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            return new OkObjectResult(req.Headers["X-Forwarded-For"]);
        }
```
![image](https://github.com/Azure/Azure-Functions/assets/1458436/b56aa65a-2965-43d4-979f-8c8b4204855c)

[XForwardFor.zip](https://github.com/Azure/Azure-Functions/files/14948429/XForwardFor.zip)

- .NET 6 in process works
- .NET 6 isolated doesn't work
- .NET 8 isolated doesn't work

**Comment by jnappi** [comment]
I was able to find the value in bindingContext.BindingData and put it back into the Headers via middleware.

```
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.Azure.Functions.Worker.Middleware;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using System.Threading.Tasks;

var builder = new HostBuilder();

var host = builder
    .ConfigureFunctionsWebApplication(
        app =>
        {
            app.UseMiddleware<ForwardedForHeaderMiddleware>();
        })
    .Build();

await host.RunAsync();

public class ForwardedForHeaderMiddleware : IFunctionsWorkerMiddleware
{
    public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {   
        await RestoreForwardedForAsync(context);

        await next(context);
    }

    private static async Task RestoreForwardedForAsync(FunctionContext context)
    {
        var val = GetForwardedFor(context);
        var req = await context.GetHttpRequestDataAsync();
        req?.Headers.TryAddWithoutValidation(ForwardedHeadersDefaults.XForwardedForHeaderName, val);
    }

    private static string? GetForwardedFor(FunctionContext context)
    {
        var hdr = context.BindingContext.BindingData["Headers"];
        dynamic obj = JsonConvert.DeserializeObject(hdr.ToString());

        var val = obj?[ForwardedHeadersDefaults.XForwardedForHeaderName]?.Value as string;
        return val;
    }
}

```

**Comment by joostas** [comment]
> I was able to find the value in bindingContext.BindingData and put it back into the Headers via middleware.

For me this didn't work. Problem was that `X-Forwarded-For` header was added by Azure Functions in different casing:
a) `X-Forwarded-For` - if original request didn't have any X-Forwarded-For header
b) `x-forwarded-for` - if original request already had X-Forwarded-For header.

My solution was to use your middleware but replace binding data deserialization using System.Text.Json and "case insensitive" property deserialization:
```cs
using System.Text.Json;
using System.Text.Json.Serialization;
//...
private static readonly JsonSerializerOptions _serializerOptions = new(JsonSerializerDefaults.Web);
private string GetForwardedFor(FunctionContext context)
{
	var hdr = context.BindingContext.BindingData["Headers"];
	if (hdr is null)
	{
		return null;
	}

	var xff = JsonSerializer.Deserialize<XffHeader>(hdr.ToString(), _serializerOptions);
	return xff?.Value;
}
//...
private record XffHeader([property: JsonPropertyName("X-Forwarded-For")] string Value);
```
