### ISSUE TITLE
C++ support in Azure Functions?

### ISSUE THREAD

**Issue by iszczesniak** [Azure/Azure-Functions#224]
Hi,

I would like to use C++ REST SDK to develop my code in C++ and run it as an Azure Function.

Are there plans to support C++ for Azure Functions?

Best,
Irek

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1469

**Comment by Xyncgas** [comment]
I want this, microsoft has visual studio and it can be so easy and improving quality of life just compile things to webassembly
