### ISSUE TITLE
How to deploy the Azure Functions (.Net 6.0 isolated LTS) on premises IIS?

### ISSUE THREAD

**Issue by Pritesh-Patel27** [Azure/Azure-Functions#2240]
I have created a HttpTrigger Azure function (.Net 6.0 Isolated-LTS) using Visual Studio 2022. I have published the Project in a Local Folder in my system. Try to deploy the generated dlls in the Local IIS and call the API from browser but getting error.

I have done all the steps provided in following link: [Is it possible to deploy the Azure Functions in Local IIS?](https://stackoverflow.com/questions/47325106/is-it-possible-to-deploy-the-azure-functions-in-local-iis)

I have installed Azure Function Runtime and set processPath in web.config file.

`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="C:\Program Files\Microsoft\Azure Functions Core Tools\Microsoft.Azure.WebJobs.Script.WebHost.dll" hostingModel="InProcess">
      <environmentVariables>
        <environmentVariable name="AzureWebJobsStorage" value="UseDevelopmentStorage=true" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
`

**I am still getting the following error:**

**Comment by Ved2806** [comment]
Hi @Pritesh-Patel27 You may want to try [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs?tabs=in-process). Please let us know if it helps. Thanks.
