### ISSUE TITLE
"Missing value for AzureWebJobsStorage in local.settings.json"

### ISSUE THREAD

**Issue by onionhammer** [Azure/Azure-Functions#2244]
This warning shows when `AzureWebJobsStorage__accountName` is specified and using a managed identity, so the warning shows but then the app works just fine.

**Comment by Ved2806** [comment]
Hi @onionhammer Please refer discussion [here](https://github.com/Azure/azure-functions-host/issues/8135) Please let us know if it helps.

**Comment by onionhammer** [comment]
@Ved2806 that discussion is locked, and the warning is happening local settings still, so no it doesn't help. Using managed identity works fine, the warnings show up in build though.

**Comment by Ved2806** [comment]
Hi @onionhammer Could you please mention the warning message?

**Comment by onionhammer** [comment]
@Ved2806 

...\.nuget\packages\microsoft.net.sdk.functions\4.1.1\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning : Function [EmailSend]: Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than httptrigger, kafkatrigger, orchestrationTrigger, activityTrigger, entityTrigger. [C:\proj\src\Function.csproj]

**Comment by onionhammer** [comment]
FYI - This is still broken.

**Comment by Ved2806** [comment]
Hi @onionhammer Please refer this conversation [#2755](https://github.com/Azure/azure-functions-core-tools/issues/2755). Seems like this issue has been resolved. Please let us know if it helps?
@mattchenderson Do you have any inputs on this?

**Comment by onionhammer** [comment]
@Ved2806 it has not been resolved as version 4.1.1, which is the most recent version, as you can see in the comment above referencing

nuget\packages\microsoft.net.sdk.functions\**4.1.1**\build\Microsoft.NET.Sdk.Functions.Build.targets

```
  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
```

**Comment by onionhammer** [comment]
The offending code may be here?

https://github.com/Azure/azure-functions-vs-build-sdk/blob/011a27ec45c31e3af1315afebaf3d2a57a8ef085/src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs#L238

where instead of 

```C#
                    var azureWebJobsStorage = values.FirstOrDefault(pair => pair.Key.Equals("AzureWebJobsStorage", StringComparison.OrdinalIgnoreCase)).Value;
```

perhaps it could be

```C#
                    var azureWebJobsStorage = values.FirstOrDefault(pair => pair.Key.StartsWith("AzureWebJobsStorage", StringComparison.OrdinalIgnoreCase)).Value;
```

**Comment by Ved2806** [comment]
Hi @onionhammer Does this fixed your issue?

**Comment by onionhammer** [comment]
@Ved2806 It should; the code only exists to generate an invalid warning with no other side effects.

**Comment by Ved2806** [comment]
Hi @onionhammer Does it removed the warning message you were getting previously?

**Comment by onionhammer** [comment]
@Ved2806 yes, that is the point of the change; if you have `AzureWebJobsStorage__accountName` or `AzureWebJobsStorage` in your settings you will not receive a warning

**Comment by Ved2806** [comment]
Hi @onionhammer Thanks for confirmation, closing this as resolved.

**Comment by onionhammer** [comment]
@Ved2806 this isnt resolved unless my PR is accepted

**Comment by onionhammer** [comment]
This should be reopened
