### ISSUE TITLE
Service bus Queue trigger Azure Function app failed without a reason ( couldn't get trigger )

### ISSUE THREAD

**Issue by kumarsyamala** [Azure/Azure-Functions#2249]
I have created a azure function through cd/ci pipeline.

I send the mgs from Service bus queue and the mgs sent from service bus but the function app didn't get triggered, it failed with out proper explanation in App insights I couldn't see proper error

My service bus is :- Service bus queue trigger

Function app : - Python 3.9 , East Us ,linux

Function app code Here I am trying to trigger the databricks notebook
![fun code](https://user-images.githubusercontent.com/82040540/185237060-0dfa38e4-b4e8-4f89-b00a-297edca9e7fd.png)

Mgs from service bus:
![service bus mgs](https://user-images.githubusercontent.com/82040540/185237148-b73a47b1-b0fe-451c-a180-063dfde40655.png)

fun app insights:
![app insights](https://user-images.githubusercontent.com/82040540/185237215-fbb326b6-97ab-4e0d-8911-ace037ea992e.png)

Thanks

**Comment by Ved2806** [comment]
Hi @kumarsyamala Could you please provide the investigative information? Function App name, service bus name, timestamp. Thanks.
