### ISSUE TITLE
Telemetry Initializers and processors support

### ISSUE THREAD

**Issue by bveerendrakumar** [Azure/Azure-Functions#225]
Hi,

I have gone through app insights support for azure functions. There are some very key functionalities that App insights support are missing/not enabled. These are very important in Enterprise scenarios.

1) Telemetry Initializers
2) Telemetry Processor
3) Managing configuration thorough AI.config or code.
4)  Telemetry Channel properties and sampling modules.

The above mentioned features are used in many Enterprise scenarios to collect consistent, reliable, business oriented and correlatable Telemetry across apps. One Enterprise scenario may cut across various components like web, services, functions, workflows like logic apps etc.. It is important for us to have consistency in collecting, using the collected telemetry to complete that Enterprise scenario.

Without giving such control which is allowed by App Insights SDK today, providing just few scenarios may not help much in Enterprise scenarios. It might just provide only engineering scenarios like monitoring and diagnostics for that function alone. But Telemetry for a function alone will not help because in Enterprise application scenarios a function is just a small piece of code.

**Comment by bveerendrakumar** [comment]
Please feel free to contact me @vballa (company email) for more details or want to understand more from us on Enterprise business scenarios.

**Comment by lindydonna** [comment]
CC @christopheranderson

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1467
