### ISSUE TITLE
dotnet SDK for creating Function App

### ISSUE THREAD

**Issue by jackbond** [Azure/Azure-Functions#2250]
I've looked around a bit, and I haven't been able to find the SDK for creating Function Apps. I'm not talking the SDK to implement a function, but rather to dynamically create the Function App resource itself, something akin to Azure.ResourceManager.FunctionApps. Ultimately, I'd like to be able to create a Function App, process a set of durable entities, and then when finished, instead of attempting to clean up the individual entities, simply delete the Function App itself. I found this doc on creating a Function App via the CLI, https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-create-serverless, but is there a way to do it directly in dotnet code? Thanks.

**Comment by Ved2806** [comment]
Hi @jackbond Thank you for the feedback, we will discuss this internally and get back to you with findings soon.

**Comment by Ved2806** [comment]
Hi @jackbond This is not something that we are supporting today as we don't expose the management SDK.
