### ISSUE TITLE
Support dynamic scaling

### ISSUE THREAD

**Issue by DavidJFowler** [Azure/Azure-Functions#2255]
Hi,

Are you able to give an update on this:

https://github.com/Azure/azure-webjobs-sdk/issues/2838#issuecomment-1063196447

`Regarding the GA of Microsoft.Azure.WebJobs.Extensions.CosmosDB 4.0, it is currently waiting for required Functions features to support dynamic scaling, it is complete from the code perspective, but the service is still working on supporting Consumption Plan users. Functions team would be the right point of contact to get a release ETA.`

Packages `Microsoft.Azure.WebJobs.Extensions.CosmosDB` and `Microsoft.Azure.Functions.Worker.Extensions.CosmosDB` have been in preview for a year with no sign of a GA release.

Thanks

**Comment by ramya894** [comment]
@fabiocav could you please answer to the above query.

**Comment by cachai2** [comment]
Hi @DavidJFowler, there were some unexpected delays on the platform that held up GA of this feature. GA should be by end of calendar year.

**Comment by ramya894** [comment]
Closing as answered.
