### ISSUE TITLE
ZIP deployment failed due to - cannot swap site slots for site because the slot did not respond to http ping

### ISSUE THREAD

**Issue by kmadof** [Azure/Azure-Functions#2264]
I have an issue with Function App with a long name. The function app has 33 letters and the slot 26 letters so in total it is below 60 characters. To deploy I use these commands:

```
az functionapp deployment source config-zip -g -n -s --src --debug

az functionapp start -g {} -n {} -s {} --debug

az functionapp deployment slot swap -g {} -n {} -s {} --debug

az functionapp stop -g {} -n {} -s {} --debug

```

> ERROR: cli.azure.cli.core.azclierror: Cannot swap site slots for site 'long-name-here' because the 'long-slot-name-here' slot did not respond to http ping.

I tried many times, and I didn't get even a single success. However when I tried the name with 14 characters and the slot with 12 characters it works at the first time.

I also noticed the following entries in Activity Logs:

![obraz](https://user-images.githubusercontent.com/1680172/189214034-a4bb3913-a2be-474b-84f8-e7d71a715a1d.png)

On the `List Web App Slot Security Sensitive Settings` message is `Backup configuration not found for site 'function-app-name' with slot 'slot-name'`

And on the `Swap Web App Slots` message is `The resource operation completed with terminal provisioning state 'Failed'.`

The function app is deployed to Linux P1v3 App Plan.

I tested it also on a totally fresh plan and the behaviour was the same. With a long name it fails, with a short one is ok. It also happens **(but from time to time and usually few attempts succeeded in the end)** on functions with shorter names.

I know that this sounds crazy - this length of the function app, but it must be something there that under the same condition it is ok with a short name.

**Comment by ramya894** [comment]
@kmadof We will check this issue with our next level team and update you.

**Comment by ramya894** [comment]
@kmadof can you please provide us the function app name or invocation id and timestamp so that we can investigate it further with slot team.

**Comment by kmadof** [comment]
@ramya894 as soon as I will be back from holiday I will do it!

**Comment by ramya894** [comment]
@kmadof do you have inputs here.
