### ISSUE TITLE
[Premium] - Storage account connection string does not exist - deploying Queue storage trigger for Azure Functions

### ISSUE THREAD

**Issue by rahul-adpushup** [Azure/Azure-Functions#2268]
**Describe the bug**
I am trying to trigger my function via the storage queue. 

[Here is the complete details of problem](https://stackoverflow.com/questions/73673431/storage-account-connection-string-does-not-exist-deploying-queue-storage-trigg)

**To Reproduce**
Steps to reproduce the behaviour:
- Create a function and try to trigger it from the storage queue. 
- Check logs of the function after deployment 

**Expected behaviour**
The error should not come

**Screenshots**

**Additional context**

**Comment by ramya894** [comment]
@rahul-adpushup Please refer to this conversation https://github.com/Azure/azure-functions-core-tools/issues/2755 and let us know for any issues. Thanks.
