### ISSUE TITLE
Blog for inclusion on wiki

### ISSUE THREAD

**Issue by SteveALee** [Azure/Azure-Functions#227]
[AzureServerless](http://azureserverless.com/blog/) mainly posts on Functions but occasionally will do items on LogicApps and anything else Azure serverless related.

Cheers

**Comment by lindydonna** [comment]
Sure thing!

One request though, please update this text to make it clear that Functions is now generally available (as of Nov 2016): 
> However, these services are still new, with Functions still in Beta and LogicApps only recently formally released (or in GA, as Microsoft call it).

**Comment by SteveALee** [comment]
Oops, Done. A updated it text a little too.

**Comment by lindydonna** [comment]
Done!  https://github.com/Azure/Azure-Functions/wiki/Blogs
