### ISSUE TITLE
Can no longer manually run a Timer Triggered Function

### ISSUE THREAD

**Issue by euangordon** [Azure/Azure-Functions#2297]
I have no idea why you have now decided to prevent us from running Azure Timer Functions manually, but it is a real step backwards.... 

"test is only supported for http trigger functions"

![image](https://user-images.githubusercontent.com/32622054/201910736-a8907f50-9537-4f8f-bf2f-5a1c5ca5376b.png)

Here is my use case. 
1. Function runs on a timer once per week to connect to client API to fetch catalogue data
2. Their API was offline last week
3. I want to just kick the Function to run it now.

This has worked this way since Azure Functions v1.... Why have you changed this?

**Comment by ramya894** [comment]
@euangordon We have verified the Test/Run option is available on azure portal, if you still face the issue please comment on the below.

**Comment by euangordon** [comment]
@ramya894 I can confirm that the Test / Run button has now returned back. Thank you.

But you can see from my earlier screenshot that it wasn't available on the 15th of November. Was there a reason it was not available? Please don't remove this feature!

**Comment by ramya894** [comment]
@euangordon This feature will not be removed, the issue might be the portal was unable to load the button due to traffic/network issue.
