### ISSUE TITLE
The gRPC channel URI 'http://:<port>' could not be parsed.

### ISSUE THREAD

**Issue by oekstrand** [Azure/Azure-Functions#2298]
In VS2022, adding the nuget package **Microsoft.Azure.Functions.Worker.Extensions.ServiceBus** to a newly created Azure Function project breaks the debugging experience and I get an error 'The gRPC channel URI 'http://:7124' could not be parsed.'.

**Steps to reproduce**
1. Create a new Azure Function project in VS2022 using .net 7.0 Isolated Process
2. Select timer triggered function
3. Create
4. Ensure that the project runs by hitting F5
5. Install the Microsoft.Azure.Functions.Worker.Extensions.ServiceBus nuget package
6. Run again with F5 -> Causes bug mentioned above

**Comment by milannankov** [comment]
Hello, what is the solution for this? I get the same error.
