### ISSUE TITLE
How to use Azure Functions in Production

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#23]
There is an email thread that just started on this... I will update this thread with that conversation

Added by @lindydonna:
Examples of content to include:
- Functions should be stateless
- Use queues between functions
- Functions within an app share resources. If you're using something a Function App in production, don't add test functions to it.

**Comment by wesmc7777** [comment]
@SyntaxC4  @lindydonna should this be part of Functions Best Practice doc?

**Comment by lindydonna** [comment]
@wesmc7777 Yes, I didn't realize we had this issue. We should merge them into one article.

**Comment by wesmc7777** [comment]
@SyntaxC4  Cory can you forward me that email thread you mentioned regarding this.  It should help me scope this topic

**Comment by SyntaxC4** [comment]
@wesmc7777 I forwarded the thread internally. I think it will provide a good outline for the doc.

**Comment by wesmc7777** [comment]
Thanks I expect to have a draft of this one done next week to discuss by our meeting on the 27th

**Comment by lindydonna** [comment]
Additional things to add:

  - For .NET, if you're referencing a shared binary, put it in a common shared folder and do `#r "..\Shared\MyAssembly.dll"`.

**Comment by lindydonna** [comment]
Another one from a bunch of bugs we saw: using .Result is generally very dangerous and can cause deadlocks. See https://github.com/Azure/azure-webjobs-sdk-script/issues/774

**Comment by brettsam** [comment]
Some other things that have come up recently when talking with customers. These really apply to any cloud computing in general:

- Write functions to be idempotent. Notably, timers. For example, if you have something that absolutely must run once a day, write it so it can run every minute with the same end results. Make it so that it no-ops if that day's work is done or that if the previous run crashed 50% of the way through, that it can pick up where it left off.
- Building on that, assume your function host can crash at any time. If you're processing a bunch of items in a single function, something downstream may throw unexpectedly and bring your function down. You should be prepared to continue from that point when the function next runs.

**Comment by wesmc7777** [comment]
Email (11/8/2016 5:45 PM) from Donna concerning long running functions and Node functions with many (implicit or explicit) dependancies. Can cause timeouts....

Essentially, our platform has a hard time with a Node require that has a lot of dependencies, and cold start can take longer than a timeout from a third part that expects a timeout. This is a current limitation of the platform that will be improved in the coming months.
 
The advice we can give to customers is that if they have a long running function or a function with lots of Node dependencies (which is a fundamental problem with the way Node dependencies work), then they should return a response as soon as possible and do the work in another function, using queue triggers between.

**Comment by wesmc7777** [comment]
https://github.com/Microsoft/azure-docs-pr/pull/404

**Comment by lindydonna** [comment]
@wesmc7777 I reviewed the topic and it's a good draft. @christopheranderson Could you review as well and see if there's anything important that should be captured?

**Comment by wesmc7777** [comment]
https://github.com/Microsoft/azure-docs-pr/pull/987

**Comment by christopheranderson** [comment]
@wesmc7777 - what you have is all correct. Nothing springs to mind that we need to add in any desperate way. Feel free to ship and close this, and we can track additions in other issues.

**Comment by christopheranderson** [comment]
:shipit:
