### ISSUE TITLE
Migrating FUNCTIONS_EXTENSION_VERSION from V3 to V4 returns a Microsoft.Azure.webJobs.Extension.CosmosDB error

### ISSUE THREAD

**Issue by Kellswork** [Azure/Azure-Functions#2301]
Function App name: C#
Tools used:
New V4 app or existing V3 app migrated to V4: V3 App migrating to V4

Migrating a function app from v3 to v4 on azure cloud environment returns a cosmodb upgrade error. 
I am migrating Microsoft .net core app from 3.1 to 6.0 and v3 to v4. I updated the following Nuget package for the function and it's dependencies.

`<TargetFramework>net6.0</TargetFramework>`
 `<AzureFunctionsVersion>v4</AzureFunctionsVersion>`
 `<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.20.0" />`
 `<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.0" />`
 `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.10" />`
 `<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />`

This update worked fine when tested locally. The update was pushed and deployed on GitHub.
when updating the function app `FUNCTIONS_EXTENSION_VERSION` configuration value from `V3` to `V4` on Azure cloud.

I got this error message.
`Microsoft.Azure.WebJobs.Script: One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType CosmosDBWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.CosmosDB, Version=3.0.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 3.0.9.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.CosmosDB to 3.0.9 or later.`

The function app `FUNCTIONS_EXTENSION_VERSION` configuration was downgraded to `v3` for it to run on Azure cloud.

**Comment by ramya894** [comment]
@Kellswork Please find the below blog for more information, in case the issue is not resolved please contact us again.
https://techcommunity.microsoft.com/t5/apps-on-azure-blog/issues-you-may-meet-when-upgrading-azure-function-app-to-v4/ba-p/3288983
https://github.com/Azure/Azure-Functions/issues/1987
