### ISSUE TITLE
Cannot create Linux Consumption Plan in resource group

### ISSUE THREAD

**Issue by paulsmithkc** [Azure/Azure-Functions#2302]
1. When we attempt to create a new function app, using a Linux Consumption Plan, we are seeing the following error:
`{"code":"InvalidTemplateDeployment","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"LinuxDynamicWorkersNotAllowedInResourceGroup","message":"Linux dynamic workers are not available in resource group Production. Use this link to learn more http://go.microsoft.com/fwlink/?LinkId=825764."}]}],"message":"The template deployment 'Microsoft.Web-FunctionApp-Portal-0a0c1e52-b202' is not valid according to the validation procedure. The tracking id is '****'. See inner errors for details."}`

2. According to the page linked in the error, this is due to an issue with the Resource Group / Stamp:
[Creating Function Apps in an existing Resource Group](https://github.com/Azure/Azure-Functions/wiki/Creating-Function-Apps-in-an-existing-Resource-Group)

3. However, the NOTE at the top of this wiki page also indicates that this issue has been resolved:
`NOTE: The restrictions have been removed, the content below is left as is for reference.`

4. Is this page out of date? And what do we need to do to fix the issue now?

**Comment by ramya894** [comment]
@paulsmithkc We are able to create a linux based python function app using Consumption plan in azure portal, please try to create again.
If you still face the issue kindly revert back.

**Comment by paulsmithkc** [comment]
@ramya894 This is only a problem for some of our resource groups. Please see linked documentation.

**Comment by paulsmithkc** [comment]
Bump
