### ISSUE TITLE
[random idea] Has anyone tried running the Functions host withing Electron?

### ISSUE THREAD

**Issue by SteveALee** [Azure/Azure-Functions#231]
This might seem crazy but bear with me! :)

Electron allows us to pack our Web front ends and some parts of a Nodejs server into a native app. This then gives us access to the platform APIs that web sandbox doesn't (yet). It might make sense to move some of our backend functions to the native client....or it might not.

Seeing as the AzureFunctions CLI runs a host including nodejs I wonder if it might be possible to work within Electron.

Perhaps an intern project :)

**Comment by lindydonna** [comment]
The CLI runs on .NET, that seems difficult to get working in Electron.

Btw this might be a better post for the MSDN forums; not many people see the issues here.

**Comment by christopheranderson** [comment]
I'm pretty open minded about doing crazy things in Node.js, but this isn't really something that makes sense. Running the host from electron is a Node.js App invoking a .NET app. There isn't anything wrong, I suppose, if you have an Electron App that wants to start the Function host from you calling func.exe from Electron, but it's not something we're interested in offering official support for that we'd test. Not unless there was a real reason to use Electron.

Gonna close this so it doesn't show up on our list of things to dig into further, but that doesn't mean we won't hear more reasons on why it'd be interesting. I just don't have one that makes sense for our team or this project to track.

**Comment by SteveALee** [comment]
@lindydonna Thanks _ I'd forgotten the .NET layer which rather makes a nonsense of it really. That's the problem with brainstorms. Thanks for tip, in this case low response is fine. That' said it would be good to know you keep a regular watch here as Functions IS open source ;) Or perhaps have a clear note of contact preference (Forum or SO)

@christopheranderson Thanks for the polite closure :) That absolutely fine - was just a random idea after all.
