### ISSUE TITLE
Function process lifetime, suspension  ...

### ISSUE THREAD

**Issue by z1c0** [Azure/Azure-Functions#2317]
I cannot find any documentation on the lifetime of an Azure Function.
AWS Lambda e.g. is very clear that the function runtime will be frozen/suspended immediately after invocation.

In Azure Functions it seems, the process runtime (`dotnet-isolated` in my case) hosting the function code stays up for many minutes after the invocation. I did some experiments with a **background thread** created during a single function invocation and this thread was able to send out HTTP requests event up to an hour(!) after the invocation.

I would expect some kind of documentation regarding the runtime behavior.
I also wonder how this affects **billing**?

**Comment by bhagyshricompany** [comment]
@z1c0  please refer this below link
https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-process-guide and also share the step for invocation in isolated environment.

**Comment by z1c0** [comment]
Hi @bhagyshricompany,

I'm not sure how this link answers any of my questions.

Please also note that I was referring to `dotnet-isolated` simply as an example. I am interested in a broader answer to my questions. How is life time, suspension, ... managed for different language runtimes? I cannot find any documentation in regard to that.

**Comment by mattchenderson** [comment]
This depends on the hosting plan. I suspect this question is primarily about Consumption, so I think this would be the best article for any additional content needed on this front (and perhaps what's already there is helpful): https://learn.microsoft.com/en-us/azure/azure-functions/event-driven-scaling

App instances that may optimistically stick around to field subsequent invocations. This prevents your app from hitting a new cold start. We don't make guarantees about how long it sticks around, so you should be prepared for the instance to be terminated at any point. That article does highlight a drain mode that allows in-flight invocations to complete before termination, but if a given instance isn't actively fielding requests, it could just be removed. 

Your app can take advantage of the serial invocation on an instance, and things like connection pooling are considered best practices. However, any given invocation could start on a new instance or be the last for an instance. The platform attempts to reuse when it thinks it can, but it reserves the right to shift things around when it needs to. Any spawned process could be unceremoniously terminated at any point, but in practice it might stick around for slightly longer than the most recent invocation, at least. As in connection pooling, the function can optimistically leverage something already initialized, but it should always be prepared to start from nothing, or for there to be a full instance termination immediately after the invocation completes.

**Comment by z1c0** [comment]
Hi @mattchenderson,

thanks for answering my question.

> I suspect this question is primarily about Consumption.

Right, this is about consumption plan.

However, some things are still rather unclear to me:
* How does the described behavior affect billing?
  * If an instance stays around after the invocation, will this incur additional costs?
* If my function directly or indirectly (e.g. via a 3rd party library) has started a background thread:
  * Will this thread affect the life-time of the instance?
  * Will this have an effect on my billing?

Cheers,
Wolfgang

**Comment by bhagyshricompany** [comment]
@z1c0 hope you got the answer am closing this issue.
Thanks
