### ISSUE TITLE
Azure Function and Entity Framework Sql Server error - Could not load file or assembly Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0

### ISSUE THREAD

**Issue by tomaszpychynski** [Azure/Azure-Functions#2319]
It appears Microsoft.Azure.WebJobs depends on Microsoft.Extensions.Logging.Abstractions 2.1.0 and Microsoft.EntityFrameworkCore 7.0.0 depends on Microsoft.Extensions.Logging.Abstractions 7.0.0.

The 'Function1' function is in error: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=[7.0.0.0], Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by bhagyshricompany** [comment]
can you share the repro steps

**Comment by tomaszpychynski** [comment]
Steps:

1. Create a new HTTP Trigger Azure Function, .NET 6 or 7
2. Add the below class to create a new DbContext to SQL Server
- Add the following nuget packages to fix compile errors : Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.SqlServer
3. The azure function will no longer execute

**Comment by bhagyshricompany** [comment]
Microsoft doc which one you followed please share

**Comment by bhagyshricompany** [comment]
can you share the dbcontext  class as well as which doc you refered

**Comment by ThibaultLesuisse** [comment]
@bhagyshricompany this has nothing to do with his DbContext class. This problem is blocking us as well and mulitple duplicate issues are being openened. There is something wrong with using .NET 7 packages in de v4 function rumtime (whichi is .NET 6). Although on the NuGet page it states that for ex. [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions) is compatible with .NET 6. 

Other duplicate issues I could find:
 - [1](https://github.com/Azure/azure-functions-host/issues/8984)

Will add others when I find them

**Comment by bhagyshricompany** [comment]
ok   I will check this issue with our next level team

**Comment by bhagyshricompany** [comment]
@satvu please update on this

**Comment by bhagyshricompany** [comment]
@kshyju

**Comment by jasonni0** [comment]
I have the same issue after I add EF for Hot Chocolate GraphQL API Project.

**Comment by jasonni0** [comment]
I have the same issue after I add EF in Hot Chocolate GraphQL Project.

**Comment by fabiocav** [comment]
Support for those dependencies are restricted to 6.0.0. This is a limitation of the in-proc model in V4 running on .NET 6. 

The recommendation, if this is a requirement, is to move to the [Isolated Model}(https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide), where .NET dependencies are not restricted/unified.

**Comment by fabiocav** [comment]
@tomaszpychynski / @jasonni0 closing this as answered, but please let us know if you have any questions or issues that would prevent you from moving to Isolated.

Thanks!

**Comment by biste5** [comment]
> Support for those dependencies are restricted to 6.0.0

But this error happens also when targeting .NET 6
@fabiocav 

P.S. What prevents us from moving to isolated is having to update all our Functions (we have many).

**Comment by jasonni0** [comment]
@fabiocav I can confirm I’m using .Net 6 and tried EF 6 too, I can try to use isolated.

**Comment by vpetit-reimagine** [comment]
@jasonni0 
> @fabiocav I can confirm I’m using .Net 6 and tried EF 6 too, I can try to use isolated.

Did you manage to make it work?

I tried to use the sample, but so far, the issue remains the same

**Comment by ThibaultLesuisse** [comment]
@fabiocav 
![image](https://user-images.githubusercontent.com/15049731/212381830-29f4b1bb-2b44-40f4-8c30-1eff57a92bec.png)
The problem can be seen in the screenshot above. The 7.0.0 version states that it is compatible with .NET 6. So how should we read the NuGet page?

**Comment by jasonni0** [comment]
@vpetit-reimagine Yes, just tried isolated .net 6 today works.

**Comment by biste5** [comment]
@ThibaultLesuisse for what I understand from @fabiocav 's comment:

Yes, version 7 of those packages should be supported when targeting .NET 6, but the current version of the Azure Functions Runtime (for in-process model), which runs on .NET 6, doesn't support them. And it doesn't seem this is going to be fixed soon. So the only option is switching to isolated model.

A bit confusing, and inconvenient.

**Comment by vpetit-reimagine** [comment]
@jasonni0 Thanks, I did test on Friday but I might have done things in a wrong way as it didn't work. I tested again today differently, and it worked (after also changing some parts of the code, and making sure there were no issues related to other missing dependencies)

**Comment by bhagyshricompany** [comment]
Thanks for update will closing this issue

**Comment by biste5** [comment]
We need to be **very** careful in updating any NuGet package in .NET 6 function projects now. As packages start to pull dependencies such as System.Text.Json 7.x (e.g. latest Graph package version).

It creates a dependency that cannot be loaded in Azure Functions and that's not directly neither easily visible until deploy

**Comment by Swimburger** [comment]
Unfortunately, our [Twilio.AspNet.Core](https://www.nuget.org/packages/Twilio.AspNet.Core/) library also targets 7 through a transitive dependency, causing the same issues. 

Customers who are already using the library can't upgrade to the latest version with improvements and security fixes because it'll break in-process model.
If they go to the isolated model, they need to refactor their Twilio related code as [isolated model doesn't have Twilio bindings like the in-process did, not yet at least](https://github.com/Azure/azure-functions-dotnet-worker/issues/144).

**Comment by divieirasilva** [comment]
Any news about it ? Same problem here.

**Comment by blurlzy** [comment]
I can confirm that EF Core 7  is not compatible with Azure Function v4. The azure function  (HTTP Trigger) will no longer execute (always returns 404) when it has EF 7 refererenced.

**Comment by Bonnieliuliu** [comment]
My Issue:
1. Azure function upgrade to net8.0, Visual Studio started successfully.
2. But using `func start` failed with error message
`[2024-11-08T09:13:06.649Z] **Error configuring services in an external startup class**.
[2024-11-08T09:13:06.651Z] Error configuring services in an external startup class. Microsoft.Azure.WebJobs.Extensions.OpenApi.Configuration.AppSettings: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
[2024-11-08T09:13:06.888Z] A host error has occurred during startup operation '844863e8-cb28-41e3-86e2-950791178b20'.
[2024-11-08T09:13:06.889Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.WebJobs.Extensions.OpenApi.Configuration.AppSettings: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

My working solution:
1. Uninstall azure function core tools (administration role)
    my scenario: it is installed by chocolaty, so uninstall using choco too`choco install azure-functions-core-tools`.
    If you are using npm: using npm uninstall command
    or other ways to install azure function core tools, do remember uninstall using the same way how you installed it.
2. re-install azure function core tools (administration role) by the command shared here: https://www.npmjs.com/package/azure-functions-core-tools
3. `func start` & it works!
