### ISSUE TITLE
Consumption Plan Function Not Starting When Message Queued

### ISSUE THREAD

**Issue by andrewkittredge** [Azure/Azure-Functions#2321]
Is processing messages from a Service Bus Queue supported by functions on the Consumption App Service Plan?

I have function using Microsoft.Azure.WebJobs.Extensions.ServiceBus verions version 5.5.1 that does not process message from the queue until I open the portal for the function.

There is [much discussion](https://www.google.com/search?q=azure+function+on+consumption+plan+not+triggering+site:github.com&rlz=1C1CHBF_enUS892US892&sxsrf=ALiCzsadATTFT7yATxjdjZxsGfpB5DPc9A:1672329533735&sa=X&ved=2ahUKEwjdxrj-mJ_8AhWWFVkFHX6hCt0QrQIoBHoECAwQBQ&biw=1536&bih=793&dpr=2.5#ip=1) of this issue with conflicting responses, 

If this does not work it should be documented.

**Comment by bhagyshricompany** [comment]
Thanks for the updating will check on my side and update you soon

**Comment by bhagyshricompany** [comment]
can you share the step which you created the service bus queue ,region,id etc

**Comment by bhagyshricompany** [comment]
not received input
