### ISSUE TITLE
Document how to monitor the number of instances a function app is scaled out to

### ISSUE THREAD

**Issue by cachai2** [Azure/Azure-Functions#2323]
Outlining steps on how to monitor the number of instances a function app is scaled out to in AppInsights today.

**Steps**
1) Go to the function app in portal
2) Go to the Logs tab on the lefthand blade
3) Add and run the below kusto query

**Kusto query:**  
```
let timeSpan = 30s;
traces
| where timestamp >= ago(1d)
| summarize instances = dcount(cloud_RoleInstance) by bin(timestamp, timeSpan), appName
| render timechart 
```

[Additional ways to check the number of instances](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/how-to-check-elastic-premium-plan-function-app-allocated/ba-p/2697852#:~:text=1%201.%20Go%20to%20Diagnose%20and%20solve%20problems,allocated%20to%20this%20function%20app%20currently.%20More%20items)

**Comment by bhagyshricompany** [comment]
document features use for counting instances

**Comment by bhagyshricompany** [comment]
document for instance count

**Comment by eroomeoj94** [comment]
Would be good if we can get this in Metrics so its easier to monitor
