### ISSUE TITLE
Why Do Azure Blob Index Tags Identity Permissions Require Blob Data Owner

### ISSUE THREAD

**Issue by ttony678** [Azure/Azure-Functions#2325]
Please describe the documentation request or issue.  Be as specific as possible.
We found that in order to write Index Tags on a blob our service principal needed [Storage Blob Data Owner](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-owner) but we felt that [Storage Blob Data Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor) should be sufficient. 

If this is indeed correct then the `NotDataActions` should be updated to indicate the [Blob Index Tags](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-portal#upload-a-new-blob-with-index-tags) are not supported despite having very similar paths to what is supported.

Ex: Microsoft.Storage/storageAccounts/blobServices/containers/blobs/tags/write

**Comment by bhagyshricompany** [comment]
@ttony678   Thanks for the update will check with next level team update you soon

**Comment by bhagyshricompany** [comment]
Storage Blob Data Contributor role would not provide sufficient permissions to write Index Tags on a blob. The Storage Blob Data Owner role would be required as it provides full control over the blob, including the ability to write Index Tags. If this is the case, then the NotDataActions should be updated to indicate that Blob Index Tags are not supported with the Storage Blob Data Contributor role.

**Comment by bhagyshricompany** [comment]
@patelchandni  please comment and validate

**Comment by patelchandni** [comment]
> @patelchandni please comment and validate

@bhagyshricompany, I'm not owner for Storage blobs or these roles/permissions. I'm not sure why I'm tagged here, unless it is a deployment issue?

**Comment by tkent** [comment]
We also bumped into this and found it confusing. This has been open for quite some time and I hope the conversation doesn't just trail off. @ttony678's question is the same as ours.

**Comment by jvmap** [comment]
Same here. Looks like we need to make a custom role?
