### ISSUE TITLE
Does Timmer Trigger support Manage Identity?

### ISSUE THREAD

**Issue by dmitry-kharchenko** [Azure/Azure-Functions#2332]
I'm trying to enable manage identity with Queue and Timmer triggers + VMSS (WebJobs SDK uses directly, there is no Function app). 

I was able to get Queue trigger working using  “AzureWebJobsStorage__queueServiceUri”(see the code sniped below). But when I tried to enable Timmer trigger by using “AzureWebJobsStorage__accountName” it throws the error:

                Environment.SetEnvironmentVariable("AzureWebJobsStorage__accountName", "<myAccountName>");
                Environment.SetEnvironmentVariable("AzureWebJobsStorage__queueServiceUri", "<queueUri>");

                var builder = new HostBuilder()
                    .ConfigureWebJobs(b =>
                    {
                        b.AddAzureStorageCoreServices();
                        b.AddTimers();
                        b.AddAzureStorageQueues(queue =>
                        {
                            queue.BatchSize = 2;
                        });
                    });

                Host = builder.Build();
                using (Host)
                {
                    await Host.RunAsync();
                }

The listener for function 'ManagementGroupSync.EnlistAllCustomManagementGroups' was unable to start. ---> System.ArgumentNullException: Value cannot be null. Parameter name: connectionString at Microsoft.Azure.Storage.CloudStorageAccount.Parse(String connectionString) at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.get_TimerStatusDirectory() at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.GetStatusBlobReference(String timerName) at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.<GetStatusAsync>d__10.MoveNext()

Dependencies:
Microsoft.Azure.WebJobs v 3.0.33
Microsoft.Azure.WebJobs.Host.Storage v 4.1.0
Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.1

 My question is: does Timmer Trigger support Managed Identities? If yes, please provide example and guidance on how to fix error above. Thanks

**Comment by bhagyshricompany** [comment]
Yes, Timer triggers support Managed Identities. To fix the error you're encountering, you need to set the "AzureWebJobsStorage" connection string in the environment variable instead of using the "AzureWebJobsStorage__accountName" and "AzureWebJobsStorage__queueServiceUri" environment variables.

Here's an example of how to set the "AzureWebJobsStorage" connection string for a Managed Identity:
Environment.SetEnvironmentVariable("AzureWebJobsStorage", "UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://127.0.0.1;");



You can also use the UseManagedIdentity method to configure the storage account with Managed Identity.
var builder = new HostBuilder()
                .ConfigureWebJobs(b =>
                {
                    b.AddAzureStorageCoreServices().UseManagedIdentity();
                    b.AddTimers();
                    b.AddAzureStorageQueues(queue =>
                    {
                        queue.BatchSize = 2;
                    });
                });


Please ensure you have given the Managed Identity of your Azure Function App the correct permissions in your Azure Storage account.
Thanks.

**Comment by dmitry-kharchenko** [comment]
@bhagyshricompany thank you for reply. Using a connection string is not an option (that's what I'm trying to ger rid of) and use Managed Identity instead. Also there is no Function App in my case, I use WebJobs SDK directly in ServiceFabric app.

For option 2, compiler complains about UseManagedIdentity(). What nuget package/version does it come from?

**Comment by bhagyshricompany** [comment]
In that case, you can use Managed Identity to authenticate to Azure Key Vault from your Service Fabric application. Here's how:

Create a Managed Identity for your Service Fabric application in Azure Active Directory.
Grant the Managed Identity access to your Key Vault.
In your Service Fabric application, use the Managed Identity to retrieve the secrets from the Key Vault.
Here is an example code in C# to retrieve secrets from Key Vault using Managed Identity:


using Microsoft.Azure.Services.AppAuthentication;
using Microsoft.Azure.KeyVault;

var azureServiceTokenProvider = new AzureServiceTokenProvider();
var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
var secret = await keyVaultClient.GetSecretAsync("<Key Vault URL>", "<secret name>");
Note: Replace <Key Vault URL> and <secret name> with the actual values.

**Comment by bhagyshricompany** [comment]
The UseManagedIdentity method is part of the Microsoft.Azure.WebJobs.Extensions.KeyVault NuGet package.

Here's the latest version information:
Package name: Microsoft.Azure.WebJobs.Extensions.KeyVault
Version: 3.0.0
Since you mentioned that you're using the WebJobs SDK directly in a Service Fabric application, this package might not be directly applicable to your scenario. However, you can use the code sample I provided earlier in my previous response to retrieve secrets from Azure Key Vault using Managed Identity in a Service Fabric application

**Comment by bhagyshricompany** [comment]
please let me know if have any questions

**Comment by dmitry-kharchenko** [comment]
@bhagyshricompany that's what we do today - connect to KeyVault using ManagedIdentity, read Storage connection string, initialize WebSDK. My goal is to eliminate any connection strings and switch to clean ManagedIdentities pattern (where you usually need to provide resource name/uri only). So, I still have the same question - does TimerTrigger (outside of FunctionApp) support managed identities?

**Comment by bhagyshricompany** [comment]
Yes, TimerTrigger outside of Function App does support Managed Identities, but it depends on the underlying Azure Storage and Key Vault components supporting Managed Identities. To use Managed Identity for accessing an Azure Storage account, you need to assign a system-assigned managed identity to the Virtual Machine Scale Set (VMSS) hosting the WebJob, or assign a user-assigned managed identity to the individual virtual machine instance(s) within the VMSS. You can then grant that identity access to the required storage account.

Regarding Key Vault, the WebJob needs to be able to authenticate using the Managed Identity and retrieve the connection string from Key Vault. To do this, you need to grant the Managed Identity access to the Key Vault instance.

**Comment by dmitry-kharchenko** [comment]
@bhagyshricompany not sure what you mean saying "TimerTrigger depends on the underlying Azure Storage and Key Vault components". My VMSS has system assigned identity. SF app uses managed identity to connect to Azure StorageAccount and to AzureKV and it works great. The last piece is to get rid of connection string to storage which is required by WebJobs SDK. Is there E2E instruction on how to make TimerTrigger work without connection string but use managed identity?

Exception I posted in the very first message, any idea on it?
