### ISSUE TITLE
Keep support for Azure function proxies as a light weight alternative API Management Gateway

### ISSUE THREAD

**Issue by langedrag** [Azure/Azure-Functions#2339]
There are several use-cases where a very simple proxy is exactly what we need. Here are two simple and common user stories.

As a developer I would like to publish a simple function on the form [https://api.example.com/myfunction](mailto:https://api.example.com/myfunction) rather than [https://api.example.com/api/myfunction](mailto:https://api.example.com/api/myfunction,).

As a developer I need to trigger a function on the root level of my domain like [https://somepage.example.com](mailto:https://somepage.example.com).

Both use-cases are common, especially for very low volume or low criticality services. Using API Management gateway would be overkill in terms of both complexity and cost. I really would like to be able to keep using Azure functions for these simple use-cases.

Please [up-vote](https://feedback.azure.com/d365community/idea/7cbaaea3-66ad-ed11-a81b-00224850345d) the user stories if they also apply to you.

**Comment by bhagyshricompany** [comment]
Thanks for input  will update

**Comment by liliankasem** [comment]
Proxies have already been reenabled in v4 via a feature flag: https://learn.microsoft.com/en-us/azure/azure-functions/legacy-proxies
