### ISSUE TITLE
Remove HttpClient as a registered service advice

### ISSUE THREAD

**Issue by aardrasystems** [Azure/Azure-Functions#2343]
Hi

I am in the process of updating my Azure Function 3 to version 4.

I noticed that one requirement is to Remove HttpClient as a registered service.

I am calling certain APIs and calling durable functions using the following example:

HttpClient client = new HttpClient();
var Getresponse = await client.GetAsync(new Uri("https://test.com/Json"));
var Getresponse_string = await Getresponse.Content.ReadAsStringAsync();
Getresponse_json = JObject.Parse(Getresponse_string);

Do I need to necessarily change this approach?

**Comment by bhagyshricompany** [comment]
Thanks for update.pls share the all repro steps with error.
