### ISSUE TITLE
Unable to create azure function - LinuxDynamicWorkersNotAllowedInResourceGroup

### ISSUE THREAD

**Issue by shakthifuture** [Azure/Azure-Functions#2346]
**Describe the bug**
Unable to create azure function, error I am getting the LinuxDynamicWorkersNotAllowedInResourceGroup. In my resource group, there is no function is created in previously.

**To Reproduce**
1. click the create in azure function
2. select the RG
3. Select python and default OS is Linux incase of python
4. select the consumption(Serverless)
5. select the hosting
6. click "Review+Create" and click create

the below error is popup
{"code":"InvalidTemplateDeployment","message":"The template deployment 'Microsoft.Web-FunctionApp-Portal-fe3aa4a7-927f' is not valid according to the validation procedure. The tracking id is '1fad1de5-fc10-4f2a-89dd-506890f7ddca'. See inner errors for details.","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"LinuxDynamicWorkersNotAllowedInResourceGroup","message":"Linux dynamic workers are not available in resource group xxxx. Use this link to learn more http://go.microsoft.com/fwlink/?LinkId=825764."}]}]}

In the selected RG, previously we never created any Azure function before.

**Comment by bhagyshricompany** [comment]
Hi Thanks for Update .Can you share the screen shot of that.

**Comment by bhagyshricompany** [comment]
I tried But not got so can you share the screen shot.

**Comment by shakthifuture** [comment]
Please find the error screenshot
![image](https://user-images.githubusercontent.com/2995544/225690136-0c734791-7bca-472c-807e-b6bf3a3fd7f4.png)

**Comment by bhagyshricompany** [comment]
If you share the function app name ,time instance, region etc.
Please create the same in  other language and platform and if you getting same pls update
