### ISSUE TITLE
Add info about binary dataType setting in function.json

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#235]
Add info from this post: [Can Azure function's binding let message passing as buffer or with specific encoding](http://stackoverflow.com/questions/40375655/can-azure-functions-binding-let-message-passing-as-buffer-or-with-specific-enco)

To these docs:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs (just a link back to the binary info)

**Comment by ggailey777** [comment]
@lindydonna can you make sure to add the Pri assessments on these backlog items? Thanks.

**Comment by lindydonna** [comment]
Fixed in https://github.com/Microsoft/azure-docs-pr/pull/14054
