### ISSUE TITLE
Clean up input/output/trigger table in documentation

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#236]
In https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings

The table hasn't been updated in a while, and causes customer confusion. See https://stackoverflow.com/questions/42742229/why-are-events-queues-and-topics-not-considered-input

**Comment by lindydonna** [comment]
Improved here: https://github.com/Microsoft/azure-docs-pr/pull/10001

**Comment by dersia** [comment]
Hey @lindydonna I get a 404 when I try to acces the provided Link.

**Comment by lindydonna** [comment]
@dersia That link only works if you have access to the private Microsoft docs repository. The article itself will be published soon.

**Comment by dersia** [comment]
Oh I see! Thanks! 👍

**Comment by lindydonna** [comment]
Done, see [Azure Functions triggers and bindings concepts](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings)
