### ISSUE TITLE
Custom headers not passed to HTTP Trigger

### ISSUE THREAD

**Issue by aaavang-rvohealth** [Azure/Azure-Functions#2360]
I'm trying to send a custom header (e.g., `pfx-impersonate`) to my Azure Function app that's running locally.  I've confirmed that the header is being sent via Chrome's dev-tools, but when I try to access it via `context.req.headers`, it's not present.

Is there something I have to do to allow all headers to pass through to the handler?

**Comment by bhagyshricompany** [comment]
Thanks for informing.
Make sure that you are sending the custom header correctly from the client. You can verify this by checking the request headers in the browser developer tools or using a tool like Postman to send the request.

Check the Azure Functions app code to make sure that it is properly configured to accept custom headers. You can try modifying the code as follows:
module.exports = async function (context, req) {
  context.res = {
    headers: {
      'Access-Control-Allow-Headers': '*',
      'Access-Control-Allow-Origin': '*'
    }
  };

  const impersonateHeader = req.headers['pfx-impersonate'];
  context.log('Impersonate Header:', impersonateHeader);

  context.res = {
    body: {
      message: `Hello from the Azure Function! Your custom header value is: ${impersonateHeader}`
    },
    headers: {
      'Content-Type': 'application/json'
    }
  };
}

Note that in addition to setting the 'Access-Control-Allow-Headers' header to '', we are also setting the 'Access-Control-Allow-Origin' header to '' to allow cross-origin requests. The code also includes a log statement to output the value of the custom header to the console and returns a JSON response that includes the custom header value.

Try running your Azure Functions app in a different environment, such as a different computer or server, to see if the issue persists.
If none of these solutions work, please provide more details about the specific error or behavior you are experiencing, and I'll do my best to help you further.

**Comment by bhagyshricompany** [comment]
you can also refer this link :https://learn.microsoft.com/en-us/azure/azure-functions/functions-proxies

**Comment by aaavang-rvohealth** [comment]
Ugh... nevermind... it was 100% user error.  I forgot there was a middleware proxying the calls to the function app.  That middleware wasn't copying the `pfx-impersonate` header in the proxy calls.
