### ISSUE TITLE
I tried to create an Azure Python Function with a GitHub Repo and when I run the GitHubAction I obtained this error

### ISSUE THREAD

**Issue by carlos-314** [Azure/Azure-Functions#2365]
Linux Consumption plan has a 1.5 GB memory limit on a remote build container.
To check our service limit, please visit https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits
Writing the artifacts to a squashfs file
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /home/site/artifacts/functionappartifact.squashfs, block size 131072.

[===============================================================|] 146/146 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 322.86 Kbytes (0.32 Mbytes)
	27.28% of uncompressed filesystem size (1183.63 Kbytes)
Inode table size 1562 bytes (1.53 Kbytes)
	28.87% of uncompressed inode table size (5410 bytes)
Directory table size 16[57](https://github.com/carlos-314/WebScrappingOpcionesMEFF/actions/runs/4713490830/jobs/8359224824#step:3:58) bytes (1.62 Kbytes)
	38.35% of uncompressed directory table size (4321 bytes)
Number of duplicate files found 3
Number of inodes 169
Number of files 149
Number of fragments 11
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 20
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
Creating placeholder blob for linux consumption function app...
Malformed SCM_RUN_FROM_PACKAGE when uploading built content.
Deployment Failed. deployer = GITHUB_ZIP_DEPLOY deploymentPath = Functions App ZipDeploy. Extract zip.
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_4827092[60](https://github.com/carlos-314/WebScrappingOpcionesMEFF/actions/runs/4713490830/jobs/8359224824#step:3:61)3078[64](https://github.com/carlos-314/WebScrappingOpcionesMEFF/actions/runs/4713490830/jobs/8359224824#step:3:65)43.zip as ZipDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!

The YAML file was generated automatically from Azure when I created the python function.

**Comment by vijaykumar911** [comment]
@carlos-314  Thanks for your information will update

**Comment by vijaykumar911** [comment]
deploying your Python function to Azure Functions using the Linux Consumption plan. The error suggests that there was an issue with the deployment package.
you may need to modify your deployment configuration or optimize your deployment package to reduce its size. You can also try deploying your function to a different hosting plan,  Azure App Service Plan or the Azure Kubernetes Service, which may provide more resources and flexibility for your deployment.
