### ISSUE TITLE
Azure Functions using Web App

### ISSUE THREAD

**Issue by lolekjohn** [Azure/Azure-Functions#237]
Hi,

I was trying to create an Azure Functions to read the messages from the evenhub trigger and write the result into cloud blob storage. I tried creating a web app as mentioned in the link - [FunctionsAsWebProject](https://github.com/lindydonna/FunctionsAsWebProject). I am actually creating the blob storage binding direction as **inout** and for the entry point function, I am using the parameter type as CloudBlockBlob.

While, trying to run the application, I am getting error as shown below:

![image](https://cloud.githubusercontent.com/assets/12344656/24581232/91f0e7b0-16e5-11e7-996a-5d30463e6a9b.png)

Can you let me know whether it is not supported? This works fine when I write the code directly in the azure portal using run.csx

**Comment by lindydonna** [comment]
It is supported, so you might have made a mistake somewhere else. Do you have a folder for the function name with function.json in it?  Is the EntryPoint property correct?

**Comment by lolekjohn** [comment]
I figured out the problem. The issue was because i was using the latest version of Azure Storage dll. Once i downgraded it to 7.2.1 it started working.
