### ISSUE TITLE
RestSharp usage in .net 6.0 class library  gives the error Could not load the assembly System.Text.Json 7.0.0

### ISSUE THREAD

**Issue by rohiniknr** [Azure/Azure-Functions#2375]
I have created a .net 6.0 class library and installed the Restsharp 110.2.0 nuget and creating a rest client within the class.
I am then trying to call this method from Azure function version V4 by adding the reference to the above class library.
But the instantiation of rest client gives this error "Could not load file or assembly 'System.Text.Json, Version=7.0.0.0"
But if I call the same method from .net 6.0 console app it works

Here is the code in the class library

namespace Test
{
    public class Class1
    {
        public async Task GetSearchResult()
        {
            try
            {
                var client = new RestClient("[https://api.publicapis.org/");](https://api.publicapis.org/%22);)
            }
            catch (Exception ex)
            {
            }
        }
    }
}

This is the code in the azure function

public async Task<IActionResult> GetList(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = FunctionDefinitions.V1QuerySmsChemicalList.Route)] HttpRequest req)
        {
            Class1 obj = new Class1();
            var res = obj.GetSearchResult();
            return null;
        }

**Comment by vijaykumar911** [comment]
Hi @rohiniknr   thanks for information will check and update you

**Comment by vijaykumar911** [comment]
The error you're encountering indicates a problem with the assembly 'System.Text.Json' version. This can occur when there is a mismatch between the version required by the RestSharp library and the version available in your Azure Function project.
Update your Azure Function to .NET 6.0.  sure you have the required version of 'System.Text.Json' referenced in your Azure Function project. You can check the references in your project and ensure that the correct version (7.0.0.0) is being used. Verify that the RestSharp library is compatible with .NET 6.0. Check for any updates or newer versions of the RestSharp library that specifically support .NET 6.0 and update your NuGet package.

**Comment by rohiniknr** [comment]
I am using the .Net 6.0 version of Azure only. The Restsharp nuget site shows that the version of restsharp that I am using i.e 110.2.0 is compatible with .Net 6.0. 
![AzureRestSharpIssue](https://github.com/Azure/Azure-Functions/assets/45229359/c202fb34-1704-474b-adce-bd37331ae4b0)

**Comment by AlexKnowles** [comment]
I'm also having this problem and found rolling back to 109.0.1 and rebuilding fixes it, though sometimes I get the odd runtime error around the RestClient constructor which I can't consistently replicate. 

The weirdest thing about this issue is System.Text.Json is put into the bin and is the correct version:
![image](https://github.com/Azure/Azure-Functions/assets/25254827/1b52adbf-848d-41c3-98b8-1b0c5b2db62f)

**Comment by rohiniknr** [comment]
https://stackoverflow.com/questions/66084145/azure-functions-could-not-load-file-or-assembly/66084146#66084146
Doing this seems to work

**Comment by bhagyshricompany** [comment]
@rohiniknr  Thanks for sharing
