### ISSUE TITLE
ScaleControllerLogs logs unauthorized access exceptions

### ISSUE THREAD

**Issue by integration-services-v** [Azure/Azure-Functions#2379]
After enabling scalecontrollerlogs for our functions a while ago, we're now receiving multiple warnings with the following message:

Encountered unauthorized access exception while checking ServiceBusQueue '<queuename>'

The scaling seems to be working fine, but we're still receiving a steady flow of these warnings.

We're using a user assigned managed identity configured with:
- Azure Service Bus Data Sender
- Azure Service Bus Data Receiver

Looking at issues #351 and #1048, I would assume that we shouldn't be getting these warnings when using a listen connection string.

Could we get thes warnings fixed for when using the Azure Service Bus Data Receiver role assignment? 
Ideally we shouldn't need to add the Azure Service Bus Data Owner role assingment for getting rid of these warnings.

**Comment by bhagyshricompany** [comment]
Thanks for reporting .Verify that the managed identity is configured correctly for both the sender and receiver instances of your Azure Functions.

Ensure that the managed identity is properly configured in the Azure portal and associated with your function apps.
If you have already assigned the "Azure Service Bus Data Sender" and "Azure Service Bus Data Receiver" roles to the managed identity, ensure that the role assignments are correctly applied.

You can check this in the Azure portal or by using the Azure CLI or Azure PowerShell commands.
After making these changes, monitor your system to confirm if the warnings are resolved. If the warnings persist, consider reviewing the Azure service bus connection string configuration and ensure that the connection string being used in your Azure Functions is correct and has the necessary permissions.

PLs share the functoin name.nvocatoin id instance region etc for investigation

**Comment by integration-services-v** [comment]
Discussed this internally, we're closing this due to internal reasons.
