### ISSUE TITLE
How can I set the root of my Azure Functions project?

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/Azure-Functions#238]
I created an AF solution in VS2015 and it create a folder structure similar to this:
```
project_name
project_name\project_name\fun_1\run.fsx
project_name\project_name\fun_1\function.json
project_name\project_name\host.json
project_name\project_name\appsettings.json
project_name\project_name.sln
```
When I deploy via CI the functions are not visible in the UI as they're a level down!

How can I set `project_name\project_name` as the root of my AF project?

Warmest regards,

Garrard.

**Comment by lindydonna** [comment]
You can use a .deployment file or the PROJECT app setting to specify the folder. See example: https://github.com/lindydonna/TestFunctionsPublish/blob/master/.deployment

Documentation: https://github.com/projectkudu/kudu/wiki/Customizing-deployments

We have this bug to track the improvement to docs: https://github.com/Azure/Azure-Functions/issues/163

**Comment by garrardkitchen** [comment]
Thank you @lindydonna !
