### ISSUE TITLE
Documentation about execution mode and possible deprecations

### ISSUE THREAD

**Issue by SeverinFriede** [Azure/Azure-Functions#2383]
In the documentation about execution mode at https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-in-process-differences it is not clear if the "In-Process" execution mode will become deprecated at some point of time or if it will be always available but only with the LTS releases of .NET.
I'm asking this question because I'm not sure if I must update my functions to "Isolated" execution mode very soon or if .NET8 LTS will still support "In-Process" mode. 
Also I couldn't find a migration guide that explains how to migrate from an "In-Process" azure function to "Isolated" (with possible pitfalls).

**Comment by bhagyshricompany** [comment]
Thanks for informing.
you can refer this doc for migrating.
https://nicksnettravels.builttoroam.com/migrate-azure-function/

**Comment by bhagyshricompany** [comment]
Hope you got the answer if not pls raise new request
