### ISSUE TITLE
Per the discussion at the bottom of the comment thread on the tooling release page, after following the pre-reqs and installing the tools the functions template does not appear

### ISSUE THREAD

**Issue by cori** [Azure/Azure-Functions#239]
Installed the prerequisites and the tooling multiple times and no matter what the function template does not appear as expected.  Several users are having this problem starting at https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/#comment-212475 and proceeding from there.

I personally am running Visual Studio 2015 Community on a Windows 10 laptop. If more information would help in achieving a resolution to this problem I'm happy to help.

**Comment by chris-barnett** [comment]
+1. 

How strange, I was just about to raise this issue as I didn't get a reply in the article mentioned.

I'm running Visual Studio 2015, Windows 8.1.

![image](https://cloud.githubusercontent.com/assets/8687762/24656055/bcab1e8a-1938-11e7-8fee-98d3c504a258.png)

**Comment by bchrisb** [comment]
@lindydonna any ideas?

**Comment by lindydonna** [comment]
Some customers have reported issues if they had ever installed the Azure SDK 3.0. Is that the case here?

You'll generally have a better tooling experience if you use the precompiled functions with a regular web project. See https://aka.ms/precompiled-functions. The next version of Functions tooling will be based on this model.

**Comment by bchrisb** [comment]
I probably did have Azure SDK 3.0 initially but removed it and installed version 2.9.6 to try and get the template to work.

I will use the precompiled functions with a regular web project for now until the next version of tooling is available. 

Thanks for the reply @lindydonna.

**Comment by cori** [comment]
I also probably had 3.0 installed at some point. I see the notes at the top of the post in question have been updated; much appreciated.
