### ISSUE TITLE
Visual Studio 2022 cannot publish Linux function app on consumption plan

### ISSUE THREAD

**Issue by Neutrino-Sunset** [Azure/Azure-Functions#2390]
Create a new Linux Function App
Consumption plan
Runtime: Dotnet 6.0 LTS

Visual Studio 2022 17.6.5
Create a new function app
Publishing it to the Azure Function App will report the following error.

    17/07/2023 20:14:24
    System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---
    
    Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
    
    ===================

**Comment by Neutrino-Sunset** [comment]
Deleting the Application Insights connection string config value seemed to fix the problem once, but I was never able to get it to work again so I think that was a red herring.

The Connection String for the App Insights service dependency in Visual Studio appears to be corrupted. It should be just the connection string, but it looks like the entire JSON response from an Azure API request.

![image](https://github.com/Azure/Azure-Functions/assets/18445931/d60341d6-257d-4ac4-bcf4-c68509ebcb2a)

**Comment by Neutrino-Sunset** [comment]
Publishing to a Function App on a Windows consumption plan works fine. Cannot publish to Linux at all.

**Comment by Neutrino-Sunset** [comment]
Earlier today I updated from Visual Studio 17.5.6 to 17.6.5. It had been working perfectly for months, now it doesn't work at all.

I've just updated from Azure Core Tools v3 to 4.0.5198, but that hasn't made any difference, it still doesn't work.

**Comment by Neutrino-Sunset** [comment]
Publish from the command line works fine, so no problem with the project or the function app itself.

> func azure functionapp publish my-function-app-name

**Comment by bhagyshricompany** [comment]
Hi @Neutrino-Sunset  thanks for reporting still you getting same problem ?

**Comment by Neutrino-Sunset** [comment]
Just tested it and now it's working again. Did you make some backend changes?

**Comment by bhagyshricompany** [comment]
ok thanks for reply issue resolved hence closing this issue.
