### ISSUE TITLE
Getting ManagedIdentityCredential authentication failed: Service request failed. Status: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by swatirashmims** [Azure/Azure-Functions#2392]
### Library name and version

Azure.Identity 1.9.0
Azure functions - v4

### Query/Question

I am trying to call my web app from Azure function using timer trigger, for which I am using DefaultAzureCredential. I have already enabled a system-assigned managed identity for the function app. The code for getting the token:

                TokenCredential azureCredential = new DefaultAzureCredential();
                var token = azureCredential.GetToken(new TokenRequestContext(new[] { "api://<scope>" }), CancellationToken.None);
                var result = await this.httpClientHelper.GetAsync("<api-endpoint>", token.Token, null).ConfigureAwait(false);
                

This is the error that I am getting
ManagedIdentityCredential authentication failed: Service request failed.
Status: 500 (Internal Server Error)

Content:

Headers:
Date: Fri, 14 Jul 2023 00:25:08 GMT
Server: Kestrel
Transfer-Encoding: chunked
X-CORRELATION-ID: REDACTED
Content-Type: application/json; charset=utf-8

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot

The above code is working on my local with VisualStudioCredential. They redirected me here as the functions managed identity endpoint is returning the error without much context. Any kind of help is appreciated.

### Environment

net 6.0
AzureFunctionsVersion - v4

**Comment by bhagyshricompany** [comment]
Thanks for reporting @swatirashmims  pls share the all repro steps.
