### ISSUE TITLE
Update Azure Functions CI/CD Article

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#24]
Article: https://azure.microsoft.com/en-us/documentation/articles/functions-continuous-deployment

**Comment by SyntaxC4** [comment]
See also for CLI: https://azure.microsoft.com/en-us/documentation/samples/functions-dotnet-azure-insights-trigger

**Comment by christopheranderson** [comment]
Should link to this from the Azure Functions product landing page, instead of the App Service one since this is more relevant.

**Comment by lindydonna** [comment]
@christopheranderson You should follow up with Jeremy on that, he's managing the changes to the product page.

**Comment by cephalin** [comment]
https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment?branch=pr-en-us-1232

**Comment by cephalin** [comment]
IF there are no comments here i'm gonna move over to "Done"
