### ISSUE TITLE
Getting error: "Thread was being aborted"

### ISSUE THREAD

**Issue by atrauzzi** [Azure/Azure-Functions#240]
Attempt to run my function, and I'm told the following:

```
2017-04-05T00:18:15.969 Exception while executing function: Functions.AddAuthor. Microsoft.Azure.WebJobs.Script: Thread was being aborted.
```

**Comment by atrauzzi** [comment]
Any thoughts, @lindydonna / @davidebbo?

**Comment by davidebbo** [comment]
Can you  provide more details? e.g.

- What kind of function is it (language/trigger/...)?
- Does it happen sporadically, or on every run?

**Comment by atrauzzi** [comment]
This one is a manual trigger and it seems sporadic.  I click "run" for my function and I get the 202 accepted, but then I get no feedback on the console below.

**Comment by lindydonna** [comment]
Do you have context.done at the end of your function code? Can you provide the relevant code snippets?

**Comment by atrauzzi** [comment]
Yup!

https://github.com/atrauzzi/anecdote-azure/blob/master/functions/AddAuthor/index.js#L24

**Comment by lindydonna** [comment]
@atrauzzi I'm not sure what's going on. You might want to post on the forums or StackOverflow, where more people are monitoring. https://aka.ms/func-forum or https://aka.ms/func-so.

**Comment by atrauzzi** [comment]
Alright, done!

http://stackoverflow.com/questions/43359244/azure-functions-app-not-giving-any-kind-of-output-eventually-giving-error

Is there anything that could be made available so that I can better diagnose these kinds of situations?  I feel kind of hamstrung by the platform.

**Comment by lindydonna** [comment]
Closing since the conversation was moved to StackOverflow.
