### ISSUE TITLE
Migrating azure functions to .net8 isolated, function hangs when triggered

### ISSUE THREAD

**Issue by doorman02** [Azure/Azure-Functions#2425]
I am migrating from Azure Functions .Net 6 app to .Net 8 isolated and I am testing a demo function called HttpTriggerCSharp by debugging it in Rider (MacOs). The breakpoints have a green tick and when I call the function the browser starts loading but the request does not return and it hangs in loading state. However I can see the request start in the console within Rider:

```
Functions:

        HttpTriggerCSharp: [GET] http://localhost:7071/HttpTriggerCSharp

[2023-11-24T15:00:28.610Z] Executing HTTP request: {
[2023-11-24T15:00:28.610Z]   requestId: "f4e1b834-9dc6-4ecc-9b19-91ee4b3d881f",
[2023-11-24T15:00:28.610Z]   method: "GET",
[2023-11-24T15:00:28.610Z]   userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
[2023-11-24T15:00:28.610Z]   uri: "/HttpTriggerCSharp"
[2023-11-24T15:00:28.610Z] }
[2023-11-24T15:00:28.739Z] Executing 'Functions.HttpTriggerCSharp' (Reason='This function was programmatically called via the host APIs.', Id=123456)
[2023-11-24T15:00:28.810Z] Executed 'Functions.HttpTriggerCSharp' (Succeeded, Id=64dde9e1-69ef-446c-935e-6f6d82a6cb7f, Duration=94ms)
[2023-11-24T15:00:28.832Z] Executed HTTP request: {
[2023-11-24T15:00:28.832Z]   requestId: "123456",
[2023-11-24T15:00:28.832Z]   identities: "(WebJobsAuthLevel:Admin)",
[2023-11-24T15:00:28.832Z]   status: "200",
[2023-11-24T15:00:28.832Z]   duration: "219"
[2023-11-24T15:00:28.832Z] }
[2023-11-24T15:00:31.248Z] Executing HTTP request: {
[2023-11-24T15:00:31.249Z]   requestId: "123456",
[2023-11-24T15:00:31.249Z]   method: "GET",
[2023-11-24T15:00:31.249Z]   userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
[2023-11-24T15:00:31.249Z]   uri: "/HttpTriggerCSharp"
[2023-11-24T15:00:31.249Z] }
[2023-11-24T15:00:31.253Z] Executing 'Functions.HttpTriggerCSharp' (Reason='This function was programmatically called via the host APIs.', Id=123456)
```

Any idea why the call to function hangs and the breakpoint is not hit?

**Comment by doorman02** [comment]
Removed .ConfigureFunctionsWorkerDefaults() from startup

**Comment by JakeStanger** [comment]
I am hitting the same issue but I do not have `ConfigureFunctionsWorkerDefaults` in my Program.cs. Could this be re-opened pls? Has anybody found any alternative causes/fixes/workarounds?

**Comment by wjchristenson2** [comment]
I'm also having this issue after migrating from net6 in-process to net8 isolated. I believe it is related to AspNetCore. If you refactor the httpTrigger to use the built-in http model (HttpResponseData, HttpRequestData) and ConfigureFunctionsWorkerDefaults() the function works. If you enable AspNetCore ConfigureFunctionsWebApplication() and kill the built-in http model... the AspNetCore http trigger hangs/breakpoint never hit. Weird thing is, if you create a brand new isolated .NET 8 function app and enable AspNetCore + build out the same httpTrigger function, it works. I have mirrored all config, references, project settings between the new function project vs the migrated. No go. I've deleted all /obj /bin directories + clean, rebuild, restart and it does not help. At this point, I think its an environment issue - maybe something is cached on my machine. I'm not going to migrate to net8 if it means all devs have to reinstall VS or the like if that is the issue.

**Comment by jacob-barna** [comment]
> I'm also having this issue after migrating from net6 in-process to net8 isolated. 

Same here ... if i set the timeout to something artificially low, the http trigger always times out and never hits the breakpoint.  I am using .ConfigureFunctionsWebApplication() in Program.cs.  For testing, I am using a trivial "hello world" http triggered function.  

Edit: A while later, I noticed the following exception in the output console:
ExceptionData","baseData":{"ver":2,"exceptions":[{"id":15225125,"outerId":0,"typeName":"System.Text.Json.JsonException","message":"'/' is invalid after a value. Expected either ',', '}', or ']'. Path: $.extensions.durableTask | ... 
{"level":5,"method":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.AspNetMiddleware.**FunctionsEndpointDataSource.GetRoutePrefix**","assembly":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore,

someone had placed // comments in host.json. 
  "durableTask": { //do not do this

clean and rebuild and it was working.

**Comment by wjchristenson2** [comment]
I've opened a new issue [here](https://github.com/Azure/Azure-Functions/issues/2425) as this old one was closed.

**Comment by wjchristenson2** [comment]
@jacob-barna I don't know why I missed your message, but I also found the same exception as you and tracked it down to a comment in the host.json file. I can confirm removing the comments from host.json fixed it. The host.json file worked fine with NET6 and prior versions in-process. Seems isolated's kestrel aspNetCore server can't.

**Comment by dggmez** [comment]
Facing this issue right now but I don't have any comment in my host.json file. The only weird thing I see is this in the output about a null value for paraemter 'httpMethods' (even though I see that the attribute has the get value there):

Application Insights Telemetry (unconfigured): {"name":"AppExceptions","time":"2024-02-26T13:57:32.1614774Z","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"MNB423","ai.operation.id":"446775881d196e61ada8eddc83bf467b","ai.operation.parentId":"a3248540beeb3381","ai.internal.sdkVersion":"azurefunctions-netiso: 1.2.0+8a4944ddc2956da7182833ce4917d8fb1d7","ai.internal.nodeName":"localhost:7088"},"data":{"baseType":"ExceptionData","baseData":{"ver":2,"exceptions":[{"id":10366524,"outerId":0,"typeName":"System.ArgumentNullException","message":"Value cannot be null. (Parameter 'httpMethods')","hasFullStack":true,"parsedStack":[{"level":0,"method":"System.ArgumentNullException.Throw","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":1,"method":"System.ArgumentNullException.ThrowIfNull","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":2,"method":"Microsoft.AspNetCore.Routing.HttpMethodMetadata..ctor","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":3,"method":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.AspNetMiddleware.FunctionsEndpointDataSource.MapHttpFunction","assembly":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore, Version=1.2.1.0, Culture=neutral, PublicKeyToken=551316b6919f366c","fileName":"D:\\a\\_work\\1\\s\\extensions\\Worker.Extensions.Http.AspNetCore\\src\\AspNetMiddleware\\FunctionsEndpointDataSource.cs","line":108},{"level":4,"method":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.AspNetMiddleware.FunctionsEndpointDataSource.BuildEndpoints","assembly":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore, Version=1.2.1.0, Culture=neutral, PublicKeyToken=551316b6919f366c","fileName":"D:\\a\\_work\\1\\s\\extensions\\Worker.Extensions.Http.AspNetCore\\src\\AspNetMiddleware\\FunctionsEndpointDataSource.cs","line":63},{"level":5,"method":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.AspNetMiddleware.FunctionsEndpointDataSource.get_Endpoints","assembly":"Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore, Version=1.2.1.0, Culture=neutral, PublicKeyToken=551316b6919f366c","fileName":"D:\\a\\_work\\1\\s\\extensions\\Worker.Extensions.Http.AspNetCore\\src\\AspNetMiddleware\\FunctionsEndpointDataSource.cs","line":44},{"level":6,"method":"Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.CreateEndpointsUnsynchronized","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":7,"method":"Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.EnsureEndpointsInitialized","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":8,"method":"Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.get_Endpoints","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":9,"method":"Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":10,"method":"System.Threading.LazyInitializer.EnsureInitializedCore","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":11,"method":"Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":12,"method":"Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":13,"method":"Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":14,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":15,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":16,"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":17,"method":"Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware+<<Invoke>g__AwaitMatcher|10_0>d.MoveNext","assembly":"Microsoft.AspNetCore.Routing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0},{"level":18,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":19,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":20,"method":"Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__238`1.MoveNext","assembly":"Microsoft.AspNetCore.Server.Kestrel.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0}]}],"severityLevel":"Error","properties":{"ConnectionId":"0HN1MQBGBAGV8","RequestId":"0HN1MQBGBAGV8:00000001","_MS.ProcessedByMetricExtractors":"(Name:'Exceptions', Ver:'1.1')","FormattedMessage":"Connection id \"0HN1MQBGBAGV8\", Request id \"0HN1MQBGBAGV8:00000001\": An unhandled exception was thrown by the application.","DeveloperMode":"true","EventId":"13","RequestPath":"/api/TestHttp","TraceIdentifier":"0HN1MQBGBAGV8:00000001","OriginalFormat":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","CategoryName":"Microsoft.AspNetCore.Server.Kestrel","EventName":"ApplicationError"}}}}
