### ISSUE TITLE
[DocDB]: Add documentation for new SqlQuery property

### ISSUE THREAD

**Issue by brettsam** [Azure/Azure-Functions#244]
DocDB now supports a SqlQuery binding property. Documentation and some sample code can be found in the portal by expanding the "Documentation" node under the binding:

![image](https://cloud.githubusercontent.com/assets/1089915/24764383/0990c990-1aa9-11e7-9c3b-4293dcf9ad53.png)

**Comment by lindydonna** [comment]
In progress, see https://github.com/Microsoft/azure-docs-pr/pull/10887

**Comment by lindydonna** [comment]
Done, see https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb
