### ISSUE TITLE
Function getting terminated 

### ISSUE THREAD

**Issue by ArunAdPushup** [Azure/Azure-Functions#247]
I created an azure function in ``nodejs``. It seems to work at first, but after I make a few changes and save it, it doesn't work. It stops logging out info and gets terminated after a while.

![screen shot 2017-04-11 at 12 49 26 am](https://cloud.githubusercontent.com/assets/20511680/24878753/053c946c-1e52-11e7-8520-993abc6392ff.png)

**Comment by brettsam** [comment]
@ArunAdPushup -- are you still seeing this?

**Comment by Coderrob** [comment]
I get this somewhat often myself with C# functions. If you restart the app service it fixes it. That or try adding a new blank space inside a function and hitting save to see if it'll recompile.

**Comment by brettsam** [comment]
I actually believe this is related to https://github.com/projectkudu/AzureFunctionsPortal/issues/818.

The application is terminated and we lose the log stream, so it appears nothing is happening. However, I think you're just not getting logs via the portal.

Have you tried looking into the actual file logs or the dashboard to see if your function is still executing when you see this?

**Comment by lindydonna** [comment]
Closing due to lack of response. Please reopen if the issue reoccurs.
