### ISSUE TITLE
Unable to load metadata for function - KEDA Function running on AKS.

### ISSUE THREAD

**Issue by gaikwadsantosh** [Azure/Azure-Functions#2472]
We are deploying Azure Function in AKS using KEDA. 
As per design whenever a message arrived in a service bus, KEDA function will trigger and consume the message.

However intermittently I am getting error  "Unable to load metadata for function" and message in service bus is not even put in dead letter queue.

very similar to issue reported  here https://github.com/Azure/azure-functions-host/issues/7238

I am running this C# function in AKS, and utilization of AKS resources is well below 50% when this error occurs.

**However one important observation we have is, code works well is with version 5.1.0 of Microsoft.Azure.WebJobs.Extensions.ServiceBus and same code stops working with newer version 5.13.5**

kindly suggest some solution.

**Comment by bhagyshricompany** [comment]
pleasse reaise the req on  azure portal.Thanks

**Comment by gaikwadsantosh** [comment]
I had already created ticket in Azure, however they suggested me to open ticket with GitHub

**Comment by gaikwadsantosh** [comment]
could it be a problem because of having long running (heavy) code in function?

**Comment by raorugan** [comment]
May I know why functions are running as containers on AKS?

**Comment by bhagyshricompany** [comment]
Hi @gaikwadsantosh  can you share the exception log error details?Thanks

**Comment by bhagyshricompany** [comment]
Need user input it s been long time no response hence closing if have issue please raise new request.Thanks

**Comment by willydavidjr** [comment]
Is there a resolution to this issue already? Or any possible solutions?
