### ISSUE TITLE
.net framework update to 8 - Azure function inprocess model not working

### ISSUE THREAD

**Issue by kmughal** [Azure/Azure-Functions#2476]
I am trying to update .net frame work for one of our project which uses in-process model. When I try to run the function I am getting following error message. 

 **Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. FunctionApp: Could not load file or assembly 'System.ComponentModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.**

For clarity I am not updating to **isolated-process** as it will require a lot binding updates so in order to minimise the noise we 
decided to go ahead with the in-process model and simply update the target framework 

Below is the csproj of that function

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Queues" Version="12.17.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.23.0" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.10" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0-preview.3.24172.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0-preview.3.24172.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
    <PackageReference Include="Npgsql" Version="8.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0-preview.3" />
    <PackageReference Include="SlackAPI" Version="1.1.13" />
    <PackageReference Include="System.ComponentModel" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by bhagyshricompany** [comment]
Thanks for reporting please share the all the steps and function name timestamp etc.

**Comment by phatcher** [comment]
AFAIK They have not released in-process NET 8 function apps - a status update was promised in March but did not appear

**Comment by bhagyshricompany** [comment]
NET 8 was not supported in the host until this week.
 
Availability is still limited, but  need to follow the instructions here to use it: https://github.com/Azure/azure-functions-host/issues/9951#issuecomment-2174365098
