### ISSUE TITLE
Azure Function Swagger Fails to Generate if Model contains Implementation of ICollection<T>

### ISSUE THREAD

**Issue by TuckermanRav** [Azure/Azure-Functions#2494]
I have a function as defined with the following attribute.

`[OpenApiResponseWithBody(HttpStatusCode.OK, MediaTypeNames.Application.Json, typeof(ConnectorResponse), Description = "Returns the details of the Connector.")]`

The ConnectorResponse object has a property
`AuthConfigurationCollection AuthConfiguraitons {get; set;}`

Now lastly, and where it all falls down is:
The AuthConfigurationCollection class implements `ICollection<AuthConfiguration>` which causes the swagger generation to fail. 

You can easily reproduce this by trying to return `ICollection<string>` int, or anything.  If I change my model to List<AuthConfiguraiton> it works fine.

**Comment by bhagyshricompany** [comment]
Thanks for informing please share repro steps and code snippet.Thanks

**Comment by bhagyshricompany** [comment]
no update hence closing open again if have issue.Thanks
