### ISSUE TITLE
Guidance on package management

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#25]
Update: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version--package-management

**Comment by SyntaxC4** [comment]
Node should have a package.json at the root of the Function App so Functions can shared cached packages. You can add a package.json at a Function level if there are version conflicts, but it should be avoided for performance reasons.

.NET does project.json at the per Function level, never at the Function App level. We do cache a package with the same version between Functions, so we don't download the same nuget twice.

**Comment by SyntaxC4** [comment]
@fabiocav - Can you confirm that we are running NPM on save now too like we do with NuGet?

**Comment by fabiocav** [comment]
Currently, we do not automatically install Node packages on save.

**Comment by lindydonna** [comment]
@SyntaxC4 For Node, we should link to a sample deploy.cmd that does NPM restore manually.
