### ISSUE TITLE
ServiceBus-triggered functions: executed function is not the one which was triggered

### ISSUE THREAD

**Issue by myarotskaya** [Azure/Azure-Functions#250]
I have one function app with two [precompiled](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions) functions:

1. `FunctionA` is triggered on messages in ServiceBus queue `queue-function-a`
1. `FunctionB` is triggered on messages in ServiceBus queue `queue-function-b`

(both queues are in the same Service Bus namespace)

However the code of the second function is always executed regardless of what function is triggered.

**FunctionA**:

```json
{
  "disabled": false,
  "scriptFile": "..\\bin\\AzureFunctions.ServiceBusTrigger.Bug.Receiver.dll",
  "entryPoint": "AzureFunctions.ServiceBusTrigger.Bug.Receiver.FunctionA.Runner.Run",
  "bindings": [
    {
      "name": "message",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "queue-function-a",
      "connection": "ServiceBus",
      "accessRights": "manage"
    }
  ]
}
```

```csharp
namespace AzureFunctions.ServiceBusTrigger.Bug.Receiver.FunctionA
{
    public class Runner
    {
        public static void Run(string message, TraceWriter log)
        {
            log.Info($"FunctionA processed the message: {message}");
        }
    }
}
```

**FunctionB**:

```json
{
  "disabled": false,
  "scriptFile": "..\\bin\\AzureFunctions.ServiceBusTrigger.Bug.Receiver.dll",
  "entryPoint": "AzureFunctions.ServiceBusTrigger.Bug.Receiver.FunctionB.Runner.Run",
  "bindings": [
    {
      "name": "message",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "queue-function-b",
      "connection": "ServiceBus",
      "accessRights": "manage"
    }
  ]
}
```

```csharp
namespace AzureFunctions.ServiceBusTrigger.Bug.Receiver.FunctionB
{
    public class Runner
    {
        public static void Run(string message, TraceWriter log)
        {
            log.Info($"FunctionB processed the message: {message}");
        }
    }
}
```

---

I've created [AzureFunctions.ServiceBusTrigger.Bug](https://github.com/myarotskaya/AzureFunctions.ServiceBusTrigger.Bug) repository to demonstrate this unexpected behavior. 

Steps to reproduce:
1. Click  `Deploy to Azure`
1. FunctionApp `Receiver` will be created with `FunctionA` (with trigger on messages in `queue-function-a`) and `FunctionB` (with trigger on messages in `queue-function-b`)
1. FunctionApp `Sender` will be created with `FunctionA` (manual trigger) that sends messages to the `queue-function-a`
1. Run Sender

**Actual result:**

`FunctionA` is triggered with the following message in the log: "Function**B** processed the message"

**Expected result:**

 `FunctionA` is triggered with the following message in the log: "Function**A** processed the message"

**Note**: the bug is also reproducible locally using the Azure Functions CLI.

**Comment by fabiocav** [comment]
Thanks for reporting this. Will investigate and update with what we find

**Comment by fabiocav** [comment]
Thank you again for reporting this and for the amount of detail and the repository with the repro. 

The issue has been resolved and will be deployed with the next release.

**Comment by myarotskaya** [comment]
@fabiocav thank you for the quick fix, that's great that it will be included in the next release!

_Temporary workaround from the Azure support team_: rename Runners in `FunctionA` and `FunctionB` to `RunnerA` and `RunnerB` respectively.
