### ISSUE TITLE
Cannot debug while using https

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/Azure-Functions#2509]
Using vs code, isolated net8 c# functions http triggers

I have been trying to debug while using https and the debugger doesn't start, i can get it to run but debugging doesn't start making it really hard to debug with real browser behaviour.

I set the task in the task.json to this

``
      "label":"runSecureHost",
      "type":"func",
      "command":"func start --cert C:/temp/localhost.pfx --password yourP@ssword --useHttps --debug",
      "isBackground":true,
      "presentation":{
        "reveal":"always"
      },
      "options": {
        "cwd": "${workspaceFolder}/src"
      }
    }
``

i have the pfx setup and it runs but the debugging panel to pass through the code never gets added as soon as --useHttps is added.

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the all repro steps and code.Thanks.
please ref this doc  https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-enable-debugging-for-aspnet-applications?view=vs-2022 pls refer this doc.
 else 
you can check this also 
1-Check your launch.json configuration: Ensure your launch.json file is correctly set up to attach the debugger to the running process. 
2-Ensure you have the correct debugger installed
3-check for HTTPS settings in your Function App: Ensure that your Azure Function App is properly configured to support HTTPS. Sometimes, issues can arise if the Function App is not correctly set up.

**Comment by bhagyshricompany** [comment]
hope you found the soln of above if not please raise new req again here am closing.
