### ISSUE TITLE
Latest portal-version broke HttpTriggered functions

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#251]
Since the last update (new "next"-portal) there seems to an issue with Http-Triggered Functions.

I came across this issue when I added a second Http-Triggred function to my function app.

The Problem is with the Route-Template:

FunctionA - RouteTemplate: "{id]/"
FunctionB - RouteTemplate: ""

this causes the runtime to add the name of the function to the route for FunctionB but not for FunctionA.

So when you call FunctionB (postman or testing-tab in portal) FunctionA and FunctionB is called where for the FunctionA call the {id} is set to the name of FunctionB.

I understand why this is happening, but I think this is not attended and I'm almost sure it wasn't that way before.

The weirdest thing, though, is that there are no logs shown for the FunctionB call in the Portal.

I'm certain that this issue is not a WebJobsSDK issue and more a Azure Functions Portal issue.

**Comment by lindydonna** [comment]
This issue was moved to projectkudu/AzureFunctionsPortal#1211
