### ISSUE TITLE
Service Bus trigger stops consuming subscription in other region

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/Azure-Functions#252]
I have the same Azure Function deployed in 5 different regions. They all consume messages from each their subscription on an Azure Service Bus topic. When deploying the functions, all messages on all subscriptions are consumed. Over time, only the function deployed in the same region as the service bus topic consumes the messages. The 4 remaining functions seems to go to sleep. When I visit an idle function in the portal, it starts consuming messages, but becomes idle over time.

I've had a similar problem when using C# script for my function in the past. After having switched to compiled function, that problem seems to have disappeared. This is why I think that this problem is related to the different regions, but I'm not sure. The 5 functions are compiled as well.

**Comment by brettsam** [comment]
@ThomasArdal -- let me reiterate what you've said to make sure I understand the layout:

1. You have one Service Bus Topic with 5 subscriptions in Region A
2. You have 5 function apps, each watching one of the 5 subscriptions. These are in multiple regions (with one in Region A)
3. 4 of the 5 function apps go idle, but the one in Region A stays active.
4. When you visit the function in the portal, that region also becomes active and processes its subscription.

If that's correct, I have a couple of other questions:
1. How are you publishing/deploying the functions to each of the regions?
2. Would you mind sharing some of your function app names either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?

**Comment by ThomasArdal** [comment]
Correct.

The function apps are deployed using Visual Studio right now. Will switch to Kudu, but that didn't work either the day I set it up.

You cannot see the problem any longer, since I added an empty timed function to each of the 5 function apps. This makes the service bus trigger function stay alive.

**Comment by brettsam** [comment]
@tohling -- Does anything about this setup jump out at you as something that could affect scaling with SB topics?

**Comment by brettsam** [comment]
I chatted with @tohling and we both think that your setup should work. Even though you've addressed it with the timers, you really shouldn't have to do that.

If you could share your function name and a rough timeline of when you saw these issues, we can take a deeper look and see what the issue could have been.

**Comment by ThomasArdal** [comment]
I no longer recall which day it happened. But as soon as I get deployments configured with Kudu, I will try to disable the timered trigger in one of the function apps and let you know if it happens again.

Thanks.

**Comment by lindydonna** [comment]
Closing this issue. If there's a new repro, please open a new issue.
