### ISSUE TITLE
Azure function not working in Azure

### ISSUE THREAD

**Issue by prosperva** [Azure/Azure-Functions#2539]
I create an azure function using python in VS Code. When tested locally, everything works and was able to deploy successfully. But when I try it out in Azure, I am getting a 500 error. Below is the structure of my app. It is using flast and provides swagger UI. I am able to see the swagger UI in Azure but the endpoints do not work

![image](https://github.com/user-attachments/assets/b4253962-1bba-4f9a-9790-1af9d93eac1b)

**Comment by bhagyshricompany** [comment]
Hi @prosperva thanks for reporting please share the app name,invocation id region,timestamp.

**Comment by bhagyshricompany** [comment]
Hi @prosperva I checked created sample function it working local as well as portal  fine.![Image](https://github.com/user-attachments/assets/7a7c070e-0d75-4c9c-a210-0717ddbb9a6a)
![Image](https://github.com/user-attachments/assets/ab2eaf3c-a626-4e46-a06b-8aad1233fe74)
Try again please.

**Comment by prosperva** [comment]
@bhagyshricompany thanks for checking. The issue was with the code I had. After checking app insights, I was able to see the specific error

**Comment by prosperva** [comment]
@bhagyshricompany thanks for checking. The issue was with the code I had. After checking app insights, I was able to see the specific error
