### ISSUE TITLE
Investigate how upgrade PowerShell 4 to PowerShell 5

### ISSUE THREAD

**Issue by tohling** [Azure/Azure-Functions#254]
The WMF 5.1 installer for PowerShell 5 does not install on our custom OS image.  We have engaged the PowerShell team but this installer is using an older OS build than the one we are using.   We will need to investigate an alternative approach on installing PowerShell 5 on our workers.

**Comment by JustinGrote** [comment]
This should be closed because Server 2016 was deployed and thus now 5.1 is the native default Powershell language.
