### ISSUE TITLE
Support for dotnet publish -t:PublishContainer

### ISSUE THREAD

**Issue by christophwille** [Azure/Azure-Functions#2559]
https://devblogs.microsoft.com/dotnet/streamline-container-build-dotnet-8/

We are using that with "other" types of .NET containers, and it would be great if the Azure Functions tooling could support that as well (makes our lives on the CI servers a lot easier if Docker isn't needed)

**Comment by mattchenderson** [comment]
This is supported in the isolated worker model, using the (currently) preview V2 SDK. See https://learn.microsoft.com/azure/azure-functions/dotnet-isolated-process-guide#version-2x-preview

Our intent is to have this available as a GA package today. We'll be sharing updates in https://github.com/Azure/azure-functions-dotnet-worker/issues/2817
