### ISSUE TITLE
The new Portal is fancy but buggy as hell

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#256]
Hi there,

I'd like to know if there is a way to roll back to the old portal.

Don't get me wrong, I really like the new portal it is much more representable, but it is still full of bugs.
Often I have to restart the whole browser to get things working again, because changes are not taken into account, even after reloading.

Tonight I was experienceing another weird issue: for some reason I can't access the key-management, it tells me that it's not available because auth is enabled for the function-app, which is just wrong, I never activated auth for the function-app nor for any other function-app within the subscription.

I really appreciate the work that has been done on the new portal, but with all the bugs it is not ready for production!

especially with the Build-Event coming up a lot of us are going to present a lot of serverless with functions and if we can't show the full power of functions just because the portal is buggy, it'll put functions into a bad position, even though imho functions is the best serverless implementation i've seen.
I have a presentation coming up tomorrow and while I was going trough the last tests tonight I found myself in a position that I can't demo anything tomorrow, since neither logs nor the test-tab is working, obviously because there are no keys available.

So please either roll back to the old portal or at least give us a way to load the old portal!

That said, I happy to help investigating the bugs and I'd love to contribute to fix them.

Thanks,
Sia

**Comment by Bomret** [comment]
Can confirm. The *Manage* tab has become inaccessible on all the function apps that I looked at in our production environment here at work, too. Noone has enabled Auth on any app there.
![Manage tab of a functions app](https://cloud.githubusercontent.com/assets/246014/25220838/56c7afe8-25b3-11e7-8891-f917774b3e3a.png)

**Comment by 4c74356b41** [comment]
Hey folks, I can confirm, any way to revert?

**Comment by Bomret** [comment]
We have one dev in our team that can access the keys in the *Manage* tab of a function. Two others see what's in the screenshot. We're all on the latest version of Chrome.

**Comment by SteveALee** [comment]
I also hit problems with this tab from day one.

**Comment by machie27** [comment]
Also have the same problem as @Bomret. This is a real problem now as I cannot do anything or distribute functions.

**Comment by primegonzola** [comment]
Hitting the same issue since a couple of hours. Used to work fine before. This is seriously blocking our development team.

**Comment by lczc1988** [comment]
I am trying to contact product team. Thank you. -Fuciton app support.

**Comment by davidebbo** [comment]
Tracked by https://github.com/projectkudu/AzureFunctionsPortal/issues/1229.

**Comment by muratboduroglu** [comment]
Same here. Can't view the function url, can't see the Keys, can't run the tests.

**Comment by SteveALee** [comment]
FWIW the URL can also be found in the Kudu console
