### ISSUE TITLE
TableStorage out-Binding not working for node

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#257]
Hi I just realized that the table-storage out binding is not working any longer.

this is my function.js
```javascript
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "eventHubMessages",
      "direction": "in",
      "path": "myhubcommands",
      "connection": "myhubcommandsconnection",
      "cardinality": "many"
    },    
    {
      "type": "table",
      "name": "events",
      "tableName": "events",
      "connection": "stor_STORAGE",
      "direction": "out"
    }
  ],
  "disabled": true
}
```

and when I log out context.bindings this is what I get:
`bindings: { eventHubMessages: [ [Object] ] }`

as soon as change the binding to `in` it's back in the bindings.

**Comment by brettsam** [comment]
@dersia -- Are you trying to write something to a table or read something from a table? 

If you're using an output binding, the `events` object will not appear in `bindings` until you create it. The data from that object will then be written to the table. There's an example here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#outnodejs

**Comment by lindydonna** [comment]
Closing due to lack of response.

**Comment by dersia** [comment]
Hi @brettsam ,

sorry for some reason I totally missed it. And yes you are right and actually I knew that, looks like I was confused the day I created that issue.

Sorry for that!

Thanks for closing @lindydonna.
