### ISSUE TITLE
Event hub trigger binding: How to start reading events from a specific point

### ISSUE THREAD

**Issue by perthcha** [Azure/Azure-Functions#262]
Can I specify the starting point of reading for an event hub trigger binding? Currently, I can't control whether the function will start reading from the very beginning, or will pick up from the last run, or do something unexpected. I would like to be able to specify the timestamp or offset to start reading the event from (Event hub itself allows this.)

**Comment by lindydonna** [comment]
For this kind of question, [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so)  will get you a much faster reply.
