### ISSUE TITLE
Documentation AppInsights <-> Azure Functions is out of date

### ISSUE THREAD

**Issue by AranVinkItility** [Azure/Azure-Functions#263]
AppInsights for Azure Functions seems to be live (I can select it when creating a Function App),

The documentation doesn't reflect this however. Most recent I could find was:
https://github.com/Azure/Azure-Functions/wiki/App-Insights-Early-Preview
which clearly states it's still in preview and you need to use FUNCTION_VERSION=beta, which is no longer the case.

**Comment by ColbyTresness** [comment]
Closing this as I believe it's stale. @alexkarcher-msft to confirm.
