### ISSUE TITLE
Unable to build a precompiled function app with VSTS

### ISSUE THREAD

**Issue by iain-peddie-tessella** [Azure/Azure-Functions#267]
Issue
----
I am using a [pre-compiled function app](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions). I am using VSTS to hold my repository.

I have a solution which contains:
   - An assembly containing with buisiness logic and data entities 
   - A test assembly, which contains unit tests for the buisiness logic assembly
   - A pre-compiled function app

I would like to be able to build this function using a VSTS build agent, that is, build the solution, then run the tests to form part of a gated continuous delivery process. I am not doing the same as [Issue 130](https://github.com/Azure/Azure-Functions/issues/130) because I am using a pre-compiled function app, so the workaround listed there do not work.

I want to use a compiled funtion app because it provides intellisense while developing, and have been told it is the direction of travel for the local function runtime.

Actual behaviour
-----
I get this error:
```Processing\IngestProcessingApp\IngestProcessingApp.funproj(8,3): Error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AzureFunctions\Microsoft.AzureFunctions.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.```

Expected behavior
----
Either VSTS can build the function application with no errors, or some documentation is made available that explains how to configure VSTS to build a pre-compiled fucntion app.

**Comment by lindydonna** [comment]
VSTS does not work with .funproj type, and this project type is going away (see [Azure Functions Tools Roadmap](https://blogs.msdn.microsoft.com/webdev/2017/04/14/azure-functions-tools-roadmap/) blog post).

You should have VSTS build the web project, as outlined in this blog post: https://aka.ms/precompiled-functions.

**Comment by markmcgookin** [comment]
Hi, 

I am seeing this behaviour at the minute. We have written a compiled function using VS2017 - 15.3 using the New Project > Azure Function which creates a .csproj file, no web app no .funproj file and am getting the exact same error. 

Is there any way to build this latest iteration of azure compiled functions in VSTS?

**Comment by lindydonna** [comment]
@markmcgookin Can you open a new issue with the exact details of how you have configured your build?  Make sure you are using the VS 2017 build agent.
