### ISSUE TITLE
VS Function App creation page should be more streamlined

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#269]
- It should behave more like the Azure portal, where fields like resource group and storage account name are automatically set.
- Creating a new consumption plan should be much simpler; either a checkbox or a dropdown

**Comment by Andrew-MSFT** [comment]
This is being tracked in the internal Visual Studio backlog. We're working on redesigning the Azure provisioning experience from VS, so we can close this particular issue

**Comment by lindydonna** [comment]
Thanks @Andrew-MSFT
