### ISSUE TITLE
Event Hubs Trigger Docs

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#27]
This is published here...

https://azure.microsoft.com/en-us/documentation/articles/functions-bindings-event-hubs/

However, I need to add a couple more code examples to the reference. Should have that completed before the end of the week.

**Comment by wesmc7777** [comment]
The code examples are in the topic. Freshened the topic to include the optional consumer group trigger binding property.

https://github.com/Azure/azure-content-pr/pull/32250
