### ISSUE TITLE
Source for the new Azure Functions runtime

### ISSUE THREAD

**Issue by niemyjski** [Azure/Azure-Functions#270]
Will new new azure functions runtime be oss? https://azure.microsoft.com/en-us/blog/introducing-azure-functions-runtime-preview/

**Comment by fabiocav** [comment]
@niemyjski the runtime is entirely based on the code on the https://github.com/Azure/azure-webjobs-sdk-script repository.

@jvano might be able to share more information about the source availability of the changes made there.

**Comment by jvano** [comment]
It is a little bit confusing but the "Azure Functions Runtime" is a closed product that uses the actual "functions runtime" is oss.

The "Azure Functions Runtime" product is delivered as an msi which can be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=55239 and the actual "functions runtime" is distributed as container image in https://hub.docker.com/r/azfuncrun/functions.

The "Azure Functions Runtime" product will allows you to run a small functions cloud and the functions will run inside containers for security, isolation and compatibility.

For preview, you won't be able to point to custom container it but we will be patching the container image as needed, so all contributions to webjobs/functions will end up in the container image at some point.

**Comment by fabiocav** [comment]
@jvano makes a good point that the actual Functions Runtime (from the repo I've linked to) is one of many  components of the recently announced Azure Functions Runtime.

**Comment by KaiWalter** [comment]
Has anyone a working sample how to deploy the container image together with Function scripts etc. in Service Fabric?

**Comment by lindydonna** [comment]
CC @jvano

**Comment by jvano** [comment]
Hi, the "Azure Functions Runtime" is yet another container orchestrator specialized for Azure Functions. The docker image used by "Azure Functions Runtime" contains the actual Azure Functions "runtime" but the image is not designed to work with Service Fabric.

**Comment by KaiWalter** [comment]
Ah I see ...thanks @lindydonna and @jvano ... now I get it.
