### ISSUE TITLE
Azure Functions Runtime: Firewall is opened without any notice

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#273]
I just installed Azure Functions Runtime and I noticed that the installation is opening the Firewall on ports 443 and 4433 by allowing any inbound request.
I see, why this is happening, but it would be nice, if there was a notice on the configuration-tool to tell you what exactly is happening.

**Comment by jvano** [comment]
Thanks for the feedback, we will add this to the configuration tool to make this more explicit.

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

We added this information to the configuring tool
