### ISSUE TITLE
Azure Function Runtime: password credentials stored plain in Database

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#274]
After installation of the Azure Functions Runtime. While there were some issues that needed changes in the config files, I also looked into the Database that was created.

I noticed that the provided UserCredentials for the FileShares are stored in plain in the database. This is not good at all and also not ready for production, this should be definitly changed.

**Comment by jvano** [comment]
Yes, this is something we are aware and we have plans to fix. 

The version we released is currently in preview under a beta/pre-release license.

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version, all the sensible information is encrypted using SQL Server database level encryption.
