### ISSUE TITLE
Azure Functions Runtime: API-Hostname in web.config not changeable from config-tool

### ISSUE THREAD

**Issue by dersia** [Azure/Azure-Functions#275]
The Angular-App that is running the portal uses the API-App to load all the data needed for the portal.

The configuration for the API-App-Hostname is within the web.config of the portal-App. It would be good, if this can be changed from the Configuration-Tool, since a lot of users won't call the portal by the Servername but rather use a DNS entry from within their organization.

**Comment by jvano** [comment]
Thanks for the feedback, the idea was to make the deployment as easy as possible and try avoid dependency on infrastructure components like DNS. However, you can modify the site's config, and create the DNS record to make this work or create a proper certificate from your org CA.

**Comment by dersia** [comment]
Hi @jvano , changing dns and site config won't help, since the url to the api is put into the web.config of the angular (portal) site. It needs manual adjustment to work... it's not that hard, but since it is not documented, not everyone will find it.

anyhow, i just opened all the ticket just to keep track of what still needs to be done. in the end that's why we have preview, right?

**Comment by jvano** [comment]
Yes and thanks for letting us know!

I thought it will just work by using the site's config but I was wrong. I'm re-opening this issue and we will get this fixed for the next release.

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version, we added support for configuring the DNS name, so it can be easily hosted.
