### ISSUE TITLE
Azure Functions Runtime: Unable to connect to management role in non-English environment

### ISSUE THREAD

**Issue by regionbbs** [Azure/Azure-Functions#276]
I downloaded and installed Azure Functions Runtime, and completed required configurations. (Windows 10 Creator Update in Traditional Chinese language)

But when I connect to management portal with https://[computername], browser has no any response in screen. I use Fiddler to capture event, an error has been captured:

{"Message":"An error has occurred.","ExceptionMessage":"值 '週四, 11 五月 2017 09:38:55 GMT' 的格式無效。","ExceptionType":"System.FormatException","StackTrace":"   於 System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)\r\n   於 System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)\r\n   於 System.Net.Http.Headers.HttpHeaders.Add(String name, String value)\r\n   於 Microsoft.Functions.Runtime.Management.Helpers.CsmHelper.CreateResponseForMessageCollection[T](List`1 messageList, HttpStatusCode statusCode, String nextLink, String collectionResourceId)\r\n   於 Microsoft.Functions.Runtime.Management.Controllers.SubscriptionController.GetSubscriptions()\r\n   於 lambda_method(Closure , Object , Object[] )\r\n   ...

![image](https://cloud.githubusercontent.com/assets/1799428/25943225/ca1986dc-3671-11e7-8be8-78016bd18210.png)

Any idea to resolve this issue?

Thank you.

**Comment by chunye** [comment]
For now, can you try this on an English OS?

**Comment by igorguga** [comment]
Hi, guys. I was receiving a similar error, but for a Brazilian Portuguese format. My OS is English, but I was using Portuguese Brazilian language. I changed everything to English (US), and the error persisted. So I decide to investigate the IIS website. I discovered that the Portal and API Application pool accounts (ApplicationPoolIdentity) didn't have the necessary permissions on the Azure Functions Runtime folders. 
Then I changed both application pool identity for an Admin account. After that everything started to work and the error disappeared.

**Comment by jvano** [comment]
Thanks for letting us know, we will take care of this for the next update

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version we have fixed this issue, we identified an encoding issue of one HTTP header
