### ISSUE TITLE
Event hub trigger not working with VS2017 functions tooling

### ISSUE THREAD

**Issue by MarekLani** [Azure/Azure-Functions#278]
Hello, when I create Event Hub triggered functions usign VS2017 functions tools I am getting following error when running function: 

EventHubTriggerCSharp: Value cannot be null.
[5/11/2017 6:07:43 PM] Parameter name: receiverConnectionString. 

I am sure, that I provide right Path and Connection when creating EventHubTrigger attribute.

**Comment by lindydonna** [comment]
Can you provide the contents of local.settings.json?  Please remove connection strings, just include the structure of the file.

**Comment by MarekLani** [comment]
Hi Donna, when creating new EventHub triggered fubction, the connection string and event hub path are automatically added to EventHubTrigger attribute for eventHubMessage parameter of function's Run method: 

  public static class Function1
    {
        [FunctionName("EventHubTriggerCSharp")]
        public static void Run([EventHubTrigger("amyeventhub", Connection = "Endpoint=sb://***=")]string myEventHubMessage, TraceWriter log)
        {
            log.Info($"C# Event Hub trigger function processed a message: {myEventHubMessage}");
        }
    }

The local.settings.json stays unchanged

{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "",
        "AzureWebJobsDashboard": ""
    }
}

**Comment by lindydonna** [comment]
You can't use a connection string in the connection attribute. It should be the name of an app setting that's provided in local.settings.json, which you have to add manually.

**Comment by MarekLani** [comment]
Thank you. I was not sure, cause first I have done it this way, that I have put it into application settings, but I was getting different error, that the connection string is not in the format as expected. I have tried to copy it to settings file two time, but apparently, I was still doing it wrong. Now it works like a charm! Thanks a lot for helping me out.

**Comment by JawadS** [comment]
Hi @MarekLani , I am having the same issues running an EventHubTrigger locally, can you please help me with the format of the connection string you've added. Preferably the whole contents of local.settings.json that got yours to work? Thanks

**Comment by MarekLani** [comment]
Hi @JawadS 
Here is content of locale.setting.json file: 

`"IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "{StorageConnectionString}",
    "AzureWebJobsDashboard": "{StorageConnectionString}",
    "EventHub": "Endpoint=sb://{myeventhubnamespace}.servicebus.windows.net/;SharedAccessKeyName={KeyName};SharedAccessKey={key}",
  }`

Here is the definition of Run function:
` [FunctionName("EventHubTriggerCSharp")]
 public static async Task Run([EventHubTrigger("alarmevents", Connection = "EventHub")]string myEventHubMessage, TraceWriter log)
        {
            log.Info($"C# Event Hub trigger function processed a message: {myEventHubMessage}");
...
            `
Hope this help.

**Comment by JawadS** [comment]
Hi @MarekLani  Thank you very much for this it worked fine, however when I run the trigger in visual studio it just settles at the message `Job host started` and doesn't display any output for the actual execution of the function? i.e when i run the function in Portal and keeps getting triggered by messages received at the EventHub however locally nothing is happening ? any idea what might be the reason for that?

**Comment by melzoghbi** [comment]
Hi @MarekLani  and @JawadS  I am facing the same issue. I am not able to run my function app that uses iot hub (same as event hub) trigger locally using VS2017.

were @MarekLani able to get it up and running to load configs from local.settings.json

**Comment by lindydonna** [comment]
@JawadS and @melzoghbi Please open new issues to track, as we don't monitor closed issues. Please include your function signature (including attributes) and the contents of local.settings.json (removing connection string values).

**Comment by petetataliba** [comment]
was this issue addressed i cant seem to get the trigger to run in visual studio, mine also settles on job host started

**Comment by TheLever** [comment]
What all needs to be done in terms of getting the template to work out of the box with VS2017? I was trying to write an event hub trigger using the template which ships with VS2017 15.4.5, but the generated code does not compile. It is missing the EventHubTrigger attribute (as in the type is unknown) and the Connection parameter is not to be found. After way too long time messing around with the NuGet packages - which I ideally shouldn't have to spend my time doing - I got it to compile if the Connection parameter is commented out. Please advice.
