### ISSUE TITLE
Visual Studio tooling does not generate manual input bindings

### ISSUE THREAD

**Issue by brantb** [Azure/Azure-Functions#279]
## Environment
OS Version: Windows 10
Visual Studio version: 15.3 (26507.0-Preview)
Visual Studio 2017 Tools for Azure Functions version: 0.1

## Issue
I have a function which I would like to be able to invoke manually in the portal UI with user-provided input, like this:
```c#
public static class HelloWorld
{
    [FunctionName("HelloWorld"), NoAutomaticTrigger]
    public static void Run(string input, TraceWriter log)
    {
        log.Info($"Hello, {input}!");
    }
}
```

When I build this code, the msbuild outputs the following warning but does not generate a `function.json`:

> Method Run is missing a trigger attribute. Both a trigger attribute and FunctionName attribute are required for an Azure function definition.

## Expected result
I would like some some way for the Functions tooling to create a `function.json` with a `manualTrigger` binding similar to the following:
```json
{
  "bindings": [
    {
      "type": "manualTrigger",
      "name": "input",
      "direction": "in"
    }
  ]
}
```

I poked around for a `[ManualInputTrigger]` attribute or something similar but didn't find anything.

**Comment by fulls1z3** [comment]
Same here, even if i create a new `function.json` it is not respected. Routing doesn't work either :(

**Comment by fulls1z3** [comment]
Well I noticed that routing is possible.

It seems that the contents of `function.json` is supplied as a parameter for the `Run` method.

```
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log) ...
```

**Comment by lindydonna** [comment]
@fulls1z3 If you create your own function.json, you need to create it in the right folder and set it to copy to the output folder. You also need to set the scriptFile and entryPoint properties. See https://aka.ms/precompiled-functions.

**Comment by lindydonna** [comment]
Closing this issue in favor of https://github.com/Azure/azure-functions-vs-build-sdk/issues/15
