### ISSUE TITLE
Nir: Update Hubs output binding example

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#28]
I was building a C# web hook that sends a notification out. The doc (https://azure.microsoft.com/en-us/documentation/articles/functions-triggers-bindings/#azure-notification-hub-output-binding) sample in C# uses an out parameter, however, when creating a web hook template we use async methods (which are the recommended way we want folks to write functions in C#) so the sample doesn’t compile. I suggest we refresh the doc sample to be consistent with our templates. In my case I wanted to output to other bindings so I couldn’t just copy and paste the whole sample.

**Comment by wesmc7777** [comment]
Fixed.  I also added doc coverage for native notification support which has been added. Async code examples for APNS, GCM, and WNS native notifications along with async template examples. 

>>>Still need some Node.js examples for native notifications<<< 
 I'll add these later. Not sure which Node package we want to use.

https://github.com/Azure/azure-content-pr/pull/32436
