### ISSUE TITLE
Cant debug locally Timer Function

### ISSUE THREAD

**Issue by MikeWilliams-UK** [Azure/Azure-Functions#281]
I am trying to debug a Function I have written in Visual Studio.

I have followed the steps in https://blogs.msdn.microsoft.com/appserviceteam/2017/03/16/publishing-a-net-class-library-as-a-function-app/

Initially I could press <F5> to start and debug the function.
Suddenly it has stopped being able to attach the debugger.

Googling around I found some people saying that the id used in host.json should be unique per developer So on a hunch I changed the first digit of the id in the file and I can now debug my function again.

If I change the id back to what it was my ability to debug stops again.
I can flip flop this at will.

How can I clear the lock which survives a PC reboot?

**Comment by ahmelsayed** [comment]
probably related to this https://github.com/Azure/azure-functions-cli/issues/126 
where terminating the cli\core tools\runtime doesn't dispose of the blob lease held to better coordinate timer functions across instances.

**Comment by lindydonna** [comment]
Closing in favor of Azure/azure-functions-cli#126
