### ISSUE TITLE
Azure Functions Portal UX - Dead Letter Queue (DLQ) Name Doesn't Pass Validation

### ISSUE THREAD

**Issue by slideep** [Azure/Azure-Functions#282]
Not quite sure to which repo to report this but queue name being dead letter queue fails miserably validation - though, it's perfectly valid queue name! At least the function works and triggers as expected.
![az_functions_portal_ux_dlq_validation](https://cloud.githubusercontent.com/assets/100609/25998550/30d66bac-372a-11e7-8567-8e6a289c488f.PNG)

**Comment by ahmelsayed** [comment]
/cc @alrod and @soninaren 

I think it should go [here](https://github.com/Azure/azure-webjobs-sdk-templates/) where we keep the regex used to validate UX input.

**Comment by mwitlok** [comment]
The same is true of the "Subscription name"-field when creating a Topic/Subscription trigger.

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk-templates#450
