### ISSUE TITLE
KUDU REST POST /api/settings won't work how it supposed to?

### ISSUE THREAD

**Issue by rawlukMike** [Azure/Azure-Functions#283]
After posting to ***.scm.azurewebsites.net/app/settings** with body: 
{
"setting1":"test"
}
The setting1 is visible in ***scm.azurewebsites.net/api/settings**
but NOT in ***scm.azurewebsites.net/Env.cshtml**

Is this how supposed to be?
That would be a nice way to add values to App Settings and I suppose it should work like this.
Or only way is to post whole **appsettings.json** to **api/zip/site/wwwroot/** ?

**Comment by lindydonna** [comment]
@ahmelsayed Can you help out?

**Comment by ahmelsayed** [comment]
that settings API [` *.scm.azurewebsites.net/api/settings`](https://github.com/projectkudu/kudu/wiki/REST-API#settings) is not the same as what you get from /Env. The settings under `/api/settings` above are just kudu specific settings which are a mix of AppSettings defined in Azure and a local `settings.json` file for that app. Only kudu consumes that file and can read the settings in it.
For settings to show up as environment variables they have to be set through ARM not SCM.
I know it can be confusing, and I'm not entirely sure why `settings.json` exists, I think it's just a legacy thing from a long time ago.
