### ISSUE TITLE
Timeout when deploying function apps´from Bitbucket with Kudu

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/Azure-Functions#286]
I have a problem deploying multiple Function apps with Kudu. Some of my apps deploy perfectly fine using Bitbucket deployment. When I set up automatic deployment from Bitbucket, the deployment just hangs with the message "Fetch from git@bitbucket.org:...". Deployment is never finished.

One of the failing functions is located in east us and here's a successful function:

2017-05-12T18:57:34.702 Function completed (Success, Id=2595dd9a-97af-469b-9021-330ac86fcf50, Duration=0ms)

**Comment by lindydonna** [comment]
This can happen when the connection to Bitbucket is interrupted. It could a problem with the Bitbucket service itself. Can you provide the contents of your deployment log files from Kudu?  Look in the LogFiles/Deployment folder.

**Comment by ThomasArdal** [comment]
I'm seeing this in the log:

    ...
    Receiving objects:  98% (28876/29388), 69.16 MiB | 10.00 KiB/s
    Receiving objects:  98% (28882/29388), 69.17 MiB | 4.00 KiB/s
    Receiving objects:  98% (28889/29388), 69.18 MiB | 4.00 KiB/s
    Connection to bitbucket.org closed by remote host.
    fatal: early EOF
    fatal: The remote end hung up unexpectedly
    fatal: index-pack failed
    D:\Program Files (x86)\Git\cmd\git.exe fetch origin --progress

I'm not sure why the deploy fails with an early EOF.

I currently have all of my code in a single repository, but the plan where to split it up into multiple git repositories. Unless you have ideas for what could be wrong with my current repo, I think I'll split up and try deploying smaller repos instead.

**Comment by lindydonna** [comment]
@davidebbo Any ideas what might be going on here?

**Comment by davidebbo** [comment]
Not sure. To isolate, try going to Kudu console and doing a fresh 'git clone' of that same repo. DOes that also fail? Also, is this failure consistent or mostly random?

If the issue it pure git, we should move it to https://github.com/projectkudu/kudu, and the function part is likely incidental here.

**Comment by ThomasArdal** [comment]
I think this is related to the performance of the machines, when running on the consumption plan. If going to Kudu and cloning an empty Bitbucket repository, this normalle takes a few seconds. When cloning from Kudu on one of the Function apps running on the consumption plan, the clone of the empty project, takes more than a minute. When looking through the log file, it looks like the machines can actually communicate with Bitbucket, but because of the slow performance, it times out or something else related to the slow transfer.

It's funny though, that my Function app deployed to the consumption plan in west us, runs as fast as when running from Kudu on my regular websites. That also explains why setting up auto deploy to my west us Function app is successful, but the other regions aren't.

**Comment by davidebbo** [comment]
Any chance that in the slow case, the Function App is set up to use an Azure File share that's in a storage account in a different region? That would make it much slower (although it is generally a slower file system).

**Comment by ThomasArdal** [comment]
Any way I can see that through the UI? I didn't set up any file shares manually, but I guess the Function app needs some where to clone the code.

**Comment by lindydonna** [comment]
@ThomasArdal Just look up the region of the storage account associated with your Function App. Look at the storage account specified in the app setting AzureWebJobsStorage.

**Comment by ThomasArdal** [comment]
Spot on. My storage account is shared between function apps in all regions. And that storage account is in west us, which explains the speed of the function app in that region.

I guess a storage account per region would be the way to move forward? :smile:

**Comment by lindydonna** [comment]
Yes, we recommend using the same region as the Function App. When you use a Consumption plan, your app content is stored in Azure Storage file shares, so a different region will have a big impact on performance.

**Comment by lindydonna** [comment]
@ThomasArdal In fact, we're going to change the storage account picker in the New Function App blade to filter to only accounts in the same region. Thanks for reporting the bug!

**Comment by ThomasArdal** [comment]
Awesome. Thank you both for the help.

**Comment by ThomasArdal** [comment]
For future reference: Changing storage account to the same region as the function, fixed the problem. The deployment still runs slowly, but at least it succeed.

**Comment by davidebbo** [comment]
@ThomasArdal thanks for following up!
