### ISSUE TITLE
[visual studio] Function App and Functions Naming

### ISSUE THREAD

**Issue by BillRaymond** [Azure/Azure-Functions#287]
This is a change to consider changing in future previews. Right now, when you create an Azure Functions app in Visual Studio, it is really a C# project, yet it is called an 'app'. In reality, you are creating functions that may perform outside the scope of any one application. Maybe it would be better to call them _Function Groups_ or something along those lines?

For the functions themselves, you create a class and call it, say, _Function1_, yet you then select a Trigger Type, and whatever name you provide there is what you see in Azure. This can be confusing for the developer because, in Visual Studio, you are working on _Function 1_, but in Azure, you are working with something called _HttpTriggerCSharp1_. Can the VS Tools team reconsider the naming convention so there is clearly a 1:1 match between what is in VS and what is in Azure?

Thanks.

**Comment by danielmarston** [comment]
I think there is a bug in the tooling where when you Add... an Azure Function to the project, the name you give the file is not used for the file name but the function type/trigger is used instead. Azure seems to show the file name in the portal.

**Comment by lindydonna** [comment]
@danielmarston Are you seeing this with all function templates, or just particular ones?  Also, does the portal show the same name as in the "FunctionName" attribute?  That's the expected behavior.

**Comment by ColbyTresness** [comment]
Closing since this is stale - please reopen if you're still seeing this.
