### ISSUE TITLE
Cannot remove 'X-AspNet-Version' from response headers

### ISSUE THREAD

**Issue by AranVinkItility** [Azure/Azure-Functions#290]
Hi all,

I'm working on securing my Azure Functions NodeJS application, but can't seem to find a way to remove the X-AspNet-Version response header.

I have managed to remove other headers (Server, X-Powered-By) through Extensions:
1: https://github.com/gregjhogan/remove-insecure-response-headers-site-extension
2: https://github.com/tjrobinson/RemoveCustomHeaders
Number 2 SHOULD remove the X-AspNet-Version but unfortunately does not work. Also modifying number 1 did not help (explicitly removing the header).

Is there any way I can remove this response header?

Other related issues:

- https://github.com/projectkudu/kudu/issues/1879
- https://github.com/gregjhogan/remove-insecure-response-headers-site-extension/issues/2
- https://github.com/tjrobinson/RemoveCustomHeaders/issues/1

**Comment by ahmelsayed** [comment]
should probably be opened here https://github.com/Azure/azure-webjobs-sdk-script/issues

**Comment by AranVinkItility** [comment]
Thanks for the tip, found another related issue on webjobs-sdk and and added a reference.

**Comment by lindydonna** [comment]
Closing in favor of https://github.com/Azure/azure-webjobs-sdk-script/issues/1237

**Comment by mathewc** [comment]
Fixed in https://github.com/Azure/azure-webjobs-sdk-script/commit/8e05f36e2001a0e5c5c7257163bfe8c10e418a8f.
