### ISSUE TITLE
C# Azure Function ConnectionString always comes back null

### ISSUE THREAD

**Issue by adammodlin** [Azure/Azure-Functions#292]
I've created a C# Azure Function. I went into Platform Features -> Application Settings and added a connection string (Service Bus). I selected Service Bus from the dropdown and pasted the connection string for my Service Bus. 

I am accessing the ConnectionString in the following manner:

    var serviceBusConnectionString = ConfigurationManager.ConnectionStrings["ServiceBusConnectionString"];.ConnectionString;

Strangely, I get a NullReference exception on this line because the ConfigurationManager connection string is null.

```
2017-05-16T20:19:00.053 Exception while executing function: Functions.TimerTriggerCSharp1. mscorlib: Exception has been thrown by the target of an invocation. f-TimerTriggerCSharp1__-754716416: Object reference not set to an instance of an object.
```

Why would this connection string be returning null? When I hard code the ConnectionString, everything works as expected.

**Comment by mathewc** [comment]
This is a cross post. I responded to this in the forum issue here: https://social.msdn.microsoft.com/Forums/en-US/ef226a6d-a2e0-4ff0-89db-b4a034a74eaa/c-azure-function-connectionstring-always-comes-back-null?forum=AzureFunctions

It's a bug with a workaround (use type "Custom"). We've identified the issue and will be fixing it.

**Comment by adammodlin** [comment]
Thanks @mathewc , feel free to close this issue now if you'd like.

**Comment by VEERAIAH1** [comment]
Hi MAthew ,
i am getting smae error even conenction string sett to custom already can youplease help on this 

Regards,
Veeru.

**Comment by VijayCorinthian** [comment]
after you click the publish screen you will get a link to manage application settings inside Visual Studio itself. Use that (see picture attached). Alternatively you can go to the Azure Functions on the portal and 1> click on your function name link to open the relevant function blade 2> select the link that says 'Configuration'. Add your application setting or configuration setting there.

**Comment by smartpcr** [comment]
this seems to be a bug, call to `StorageAccountProvider` always returns null for `connectionString`, debug into the code shows `The name connectionString" does not exist in current context`. is different version of dll being used?
```
string connectionString = _configuration.GetWebJobsConnectionString(name);
            if (connectionString == null)
            {
                // Not found
                throw new InvalidOperationException($"Storage account connection string '{IConfigurationExtensions.GetPrefixedConnectionStringName(name)}' does not exist. Make sure that it is a defined App Setting.");
            }
```
