### ISSUE TITLE
Tooling Packages not Loading Properly

### ISSUE THREAD

**Issue by isaac2004** [Azure/Azure-Functions#295]
Just fired up the tooling for the first time, and I get this when creating an Azure function

![image](https://cloud.githubusercontent.com/assets/8878502/26220392/71031a4e-3be0-11e7-946e-e60b9f00ecbf.png)

Seems like the Prerelease Nuget Packages are not being loaded properly. Is there step I am missing?

**Comment by ahmelsayed** [comment]
Have you tried building? It should restore the packages. check your csproj, it should have references to [`Microsoft.Azure.WebJobs 2.1.0-beta1`](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.1.0-beta1)

**Comment by isaac2004** [comment]
I ended up having to delete my cached packages from .nuget folder. After clearing that out and doing a dotnet restore solved the issue

**Comment by ahmelsayed** [comment]
I'm glad you got it to work. Thanks for circling back!
