### ISSUE TITLE
[Visual Studio]  `host.json` being ignored during deploy

### ISSUE THREAD

**Issue by RPM1984** [Azure/Azure-Functions#296]
Noticed the `host.json` is being ignored when deploying.

In other words, in my project in Visual Studio i have this: (to remove the `api` prefix)

```
{
“http”: {
“routePrefix”: “”
}
}
```

But when i browse the Function App Settings in App Service Editor, the file is blank. So i have to manually browse in Kudu and patch the file each time.

Known issue?

**Comment by lindydonna** [comment]
Thanks for the bug report!  It looks like host.json is being published to the bin folder instead of the root. I've filed this issue to track: [host\.json is published to bin folder instead of wwwroot \#49](https://github.com/Azure/azure-functions-vs-build-sdk/issues/49)
