### ISSUE TITLE
[Visual Studio] How do we control the `authLevel` for HTTP triggers?

### ISSUE THREAD

**Issue by RPM1984** [Azure/Azure-Functions#297]
Hi,

How can we control the [authLevel](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook) for HTTP triggers? 

There’s no `function.json` anymore in the project structure in Visual Studio.

I'm guessing this now needs to be done via the WebJobs attributes, but i can't find documentation on how to do this.

Thanks

**Comment by lindydonna** [comment]
@RPM1984 You can pass a value to the HttpTrigger attribute. For instance:

```csharp
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Anonymous "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
```

**Comment by RPM1984** [comment]
Ah, i didn't even notice that... of course! Thankyou @lindydonna 😊
