### ISSUE TITLE
[Visual Studio] How to make JSON responses camelCase?

### ISSUE THREAD

**Issue by RPM1984** [Azure/Azure-Functions#298]
Hi,

I have a basic HTTP trigger function, which i'd like to return camelCased JSON.

I'm using the following JSON formatter to control indendation, but not sure how to control the casing:

```
return req.CreateResponse(HttpStatusCode.OK, data, new JsonMediaTypeFormatter
{
    Indent = true
});
```

p.s sorry for all the questions 😊

**Comment by slideep** [comment]
Probably you've figured this already but here's how it's done. You could always encapsulate settings into your very own derived settings from `JsonSerializerSettings` and use that everywhere in your response infrastructure logic etc.

![serializer_settings](https://cloud.githubusercontent.com/assets/100609/26293623/9efc8636-3ec6-11e7-8559-a29cd4125ffc.PNG)

![fiddler_serializer_settings](https://cloud.githubusercontent.com/assets/100609/26293627/a6b8ee96-3ec6-11e7-95fa-5192805eba1c.PNG)

**Comment by RPM1984** [comment]
That's exactly what i've done. 

Code, for others reading:

```
public static JsonSerializerSettings JsonSerializerSettings => new JsonSerializerSettings
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
            Formatting = Formatting.Indented,
            DateFormatString = "yyyy-MM-ddTHH:mmZ",
            NullValueHandling = NullValueHandling.Ignore
        };
```

then

```
private static HttpResponseMessage Respond(HttpStatusCode httpStatusCode, object model)
        {
            return new HttpResponseMessage(httpStatusCode)
            {
                Content = new StringContent(JsonConvert.SerializeObject(model, Constants.JsonSerializerSettings), Encoding.UTF8, "application/json")
            };
        }
```

**Comment by kevbite** [comment]
Within version 1.0.2 of Azure Functions SDK I get a Method not found exception so I resulted in the below work around:

```
return new HttpResponseMessage(HttpStatusCode.OK)
{
    Content = new StringContent(JsonConvert.SerializeObject(nextEvent), Encoding.UTF8, "application/json")
};
```

**Comment by JasonBSteele** [comment]
If you have a large object you may want to consider using PushStreamContent to serialise directly to the response stream rather than into a string first. This could save some time and memory which will improve performance and reduce Consumption costs.
