### ISSUE TITLE
Third-Party Integration with Twilio

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#30]
* SendGrid
* Twilio

**Comment by lindydonna** [comment]
@wesmc7777 OneDrive personal does not work and will be removed from the list in the product.

**Comment by wesmc7777** [comment]
@lindydonna  We still need to cover OneDrive Business right?

**Comment by lindydonna** [comment]
Yes, OneDrive Business should be included.

**Comment by lindydonna** [comment]
Removed the OneDrive and DropBox bindings from the list, they are not P0.

**Comment by wesmc7777** [comment]
Twilio binding doc support added here:

https://github.com/Azure/azure-content-pr/pull/32446
