### ISSUE TITLE
docker Services doesnt start

### ISSUE THREAD

**Issue by hannespreishuber** [Azure/Azure-Functions#300]
Azure Functions runtime 

Azure function host activation server starts only after reboot

Docker service can  not be startet "faile to start service docker"

Installed
Windows Creators DE
Visual Studio 17.3 preview
docker for windows 17.03.1-ce-win12 (12058)
Azure Functions Extensions for Visual Studio

**Comment by hannespreishuber** [comment]
after several uninstall -reinstall
there is a conflict with Docker Services for Windows

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version we fixed this issue. Basically, "Azure Functions Runtime" will install a new docker deamon that is configured in a different named pipe. 

If you need to interact directly with the docker deamon, you can use the "Azure Functions Runtime Command Prompt" shortcut from the Windows menu that will configure the DOCKER_HOST environment variable to point to the right named pipe.

**Comment by grahamehorner** [comment]
A system that has docker already installed and then is installed with Azure Functions Runtime; the original docker stops working; deploying images/containers seems to work but doing a docker ps displays nothing. xox
