### ISSUE TITLE
Node.js functions req object missing "url" property (under module.export=function(context, req)

### ISSUE THREAD

**Issue by globysdz** [Azure/Azure-Functions#302]
I am trying to use azure functions (node.js) for application insight integration. 
the application insight method trackRequestSync(req, context.res, timeelapsems) throws exception when req object doesn't have "url" property.

Turns out if my function code is defined as:
module.export=function(context, req) {
    context.log(req) // the request object does NOT have 'url' property
}

however, if the function code is defined as:
exports.run = function(context, req) {
    context.log(req) // this req object DOES have the 'url' property
}

**Comment by lindydonna** [comment]
@christopheranderson Could you take a look?

**Comment by christopheranderson** [comment]
@mamaso - I thought we did do this?

**Comment by ColbyTresness** [comment]
@mhoeger thoughts?

**Comment by mhoeger** [comment]
`req.url` is populated as expected, closing issue
