### ISSUE TITLE
Azure functions runtime portal: empty website

### ISSUE THREAD

**Issue by hannespreishuber** [Azure/Azure-Functions#303]
when opening the onpremise portal (click from azure functions runtime configuration manager)  in browser, it is complete empty
fiddler trace shows 
GET /subscriptions?api-version=2014-04-01 HTTP/1.1
as my system in German
{"Message":"An error has occurred.","ExceptionMessage":"Das Format des Werts \"Fr, 19 Mai 2017 19:46:09 GMT\" ist ungültig.","ExceptionType":"System.FormatException","StackTrace":"   bei

**Comment by hannespreishuber** [comment]
I see - this is a duplicate issue https://github.com/Azure/Azure-Functions/issues/276

**Comment by lindydonna** [comment]
Closing as a duplicate
