### ISSUE TITLE
[Visual Studio] How to bind to custom model in HTTP trigger?

### ISSUE THREAD

**Issue by RPM1984** [Azure/Azure-Functions#304]
Hi,

I have a HTTP trigger function like so:

```
[FunctionName("GetSomething")]
public static async Task<HttpResponseMessage> RunAsync([HttpTrigger(AuthorizationLevel.Anonymous, "GET", Route = "something/{id})]
                                                               HttpRequestMessage req,
                                                               SomethingInput query,
                                                               TraceWriter log)
{
// ... code
}

public class SomethingInput
{
   public int Id { get; set; }
}
```

But when i run, i get the error:

> Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.GetSomething---> System.InvalidOperationException : Exception binding parameter 'query' ---> System.InvalidOperationException : No value was provided for parameter 'query'.

I think [previously we could perform this with function.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference) but how do we do it declaratively with the new way of doing functions?

Thanks

**Comment by slideep** [comment]
It's not obvious first but for user type binding the order of the given functions's parameters seems to matter when it creates the `HttpTriggerBinding` and/or `HttpTriggerAttribute` in the binding provider. If you want to access HTTP request, just put it after your given type and/or route constraints. A bit of trial and error here as well as we are progressing with conversion to new SDK.

![httptrigger_something](https://cloud.githubusercontent.com/assets/100609/26292984/2877656a-3ec3-11e7-91ab-d2f7334c7fbd.PNG)
![httptrigger_something_fiddler](https://cloud.githubusercontent.com/assets/100609/26292996/3455746c-3ec3-11e7-8959-c37b8cc67ced.PNG)

Good luck!

**Comment by RPM1984** [comment]
@slideep awesome, it works!

thankyou :)

(btw, i noticed with the `TraceWriter` param, it errored, but thankfully i don't need it in my case).

**Comment by wobba** [comment]
Just what I needed! thank you @slideep

**Comment by jetstreamin** [comment]
I've been twiddling my thumbs with this for a couple of hours and can't get past it.  Here is my code.  What I am I missing?  

#r "Newtonsoft.Json"
#r "System.Web"
#r "System.Web.Mvc"
using System.Net;
using Newtonsoft.Json;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using Microsoft.Azure.WebJobs.Extensions.Http;

public class DigitalAsset {

    public string Id { get; set; }
    public string Name { get; set; }
}

public class OrderByClause {

    public int OrderBy { get; set; }

}

public static async Task<List<DigitalAsset>> Run(HttpRequestMessage req, TraceWriter log, 
    [HttpTrigger(Authorization.Anonymous, "post", Route = "CmcListAllOrderBy/{orderBy}")], int orderBy)
{

    log.Info("+++++++++++++++++++++++++++++++++++++++++++++++++");
    log.Info("Getting a list of digital assets sorted by 24 Hour Percent Changed.");        
    var url = "https://api.xxx.com/v1?limit=0"; 

...

}}}

Any help is greatly appreciated.

TY, Mike

**Comment by mcbridedm** [comment]
@jetstreamin try {orderBy:int}?

**Comment by omerlh** [comment]
Does Azure function support model validation? E.g. using `Required` attribute?
