### ISSUE TITLE
Get-AzureRMImage The term 'Get-AzureRMImage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by RashmiPankaj** [Azure/Azure-Functions#305]
I am trying to use Azure Function Powershell Http Trigger template. I am trying to create VM through azure functions. I tried importing custom modules of Azure.Compute 4.0 version. Still facing this issue.

Get-AzureRMImage : The term 'Get-AzureRMImage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I tried  Import-Module 'D:\home\site\wwwroot\createvm\bin\Modules\AzureRM.Compute\3.0.0\AzureRM.Compute.psm1' -Global 

Still no luck

**Comment by ahmelsayed** [comment]
bring your own powershell module per instructions here https://github.com/Azure/Azure-Functions/issues/294#issuecomment-302196391
