### ISSUE TITLE
We are not able to retrieve the keys for function ... This can happen if the runtime is not able to load your function.

### ISSUE THREAD

**Issue by ticapix** [Azure/Azure-Functions#306]
Hi,

I'm having the same error than in issue #226 

```
We are not able to retrieve the keys for function parsePublication. This can happen if the runtime is not able to load your function. Check other function errors.

Session Id: 40f3b6babc24406f93511dfac011bb5b

Timestamp: 2017-05-22T06:34:52.492Z
```

My two others working functions are in python2.7.
The one failing is in C# app https://publication-erdf.azurewebsites.net fctName parsePublication.

I also reset the secrets in D:\home\data\Functions\secrets but the error remains.

Any idea ?

**Comment by RashmiPankaj** [comment]
Try to make some changes in App settings of Azure Functions. Save it and  reload the azure function.

**Comment by ticapix** [comment]
error still here

**Comment by lindydonna** [comment]
FYI, for this kind of question, [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so)  will get you a much faster reply. Please include your configuration in your question.
