### ISSUE TITLE
Connection String Functions Runtime

### ISSUE THREAD

**Issue by hannespreishuber** [Azure/Azure-Functions#307]
I didn't get the story how to set a working  connection string (eg queue) for local development in local.settings.josn. Where to get the string for my Azure Functions runtime or the Visual Studio tools? 

the Microsoft Azure Storage Eplorer shows for 
(local and attached) - (Development) no propertys

-Hannes

**Comment by lindydonna** [comment]
See the video walkthrough here: [Azure Functions Visual Studio Tooling](https://www.youtube.com/watch?v=BN2sIRrOt8A)

**Comment by hannespreishuber** [comment]
you are using a azure queue, whats about the local runtime?

**Comment by slideep** [comment]
@hannespreishuber late to the party but you can use perfectly fine Azure storage's emulator for queues, tables and blobs. 

![development_storage_emulator](https://cloud.githubusercontent.com/assets/100609/26401448/b26b868a-408e-11e7-8973-4a28b6d221b5.PNG)
