### ISSUE TITLE
Error: We are unable to access your function keys

### ISSUE THREAD

**Issue by mag1971** [Azure/Azure-Functions#308]
<img width="369" alt="screen shot 2017-05-22 at 19 20 08" src="https://cloud.githubusercontent.com/assets/4283047/26322636/ce9db51a-3f23-11e7-8408-f667c0d6607a.png">

Have been getting this error for 2 days now. Functions are totally unusable for me at the moment. 
I am trying to trial functions with a view to using in a live production scenario in a few weeks so really need to be able to test this out.

Functions being totally out of action like this isn't a good start and would be disastrous in production usage. So I need to check I haven't done something wrong first.

The function group is orion-hunter and was last accessible on Saturday.

Thanks
Mike

**Comment by lindydonna** [comment]
FYI, for this kind of question, [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so)  will get you a much faster reply. Please include your configuration in your question.
