### ISSUE TITLE
Routing fails if parameters contains slash

### ISSUE THREAD

**Issue by piffarettig** [Azure/Azure-Functions#309]
I know this is a dumb question, but I really need to test this behaviour on Portal.

When the Azure function tries to do the attribute routing of a parameter that contains a slash to a string (for example an URL), it fails and returns a 404 Not Found Error.

I am using a C# HTTP trigger function.

I know that I should encode the URL, but as I said I am trying to test it on Azure Portal.

Is this an issue or just not supported (like it happens in Web Api 2 or REST APIs in general)?

Thanks in advance.

**Comment by russgove** [comment]
I am having the same issue! was this fixed?

**Comment by james1293** [comment]
Can you put a star in the route variable, like this?

```
{
  ....
  "bindings": [
    {
      ...
      "route": "app/{*everythingElse}"
    },
    .....
  ]
}
```

**Comment by dtaalbers** [comment]
Thanks @james1293 That seem to work for me! 

From 

```
[HttpGet, Route("{id}")]
```
to
```
[HttpGet, Route("{*id}")]
```

**Comment by jaslam94** [comment]
This does not allow double slash. How would that be allowed?

**Comment by jaslam94** [comment]
> Thanks @james1293 That seem to work for me!
> 
> From
> 
> ```
> [HttpGet, Route("{id}")]
> ```
> 
> to
> 
> ```
> [HttpGet, Route("{*id}")]
> ```

This does not allow double slash. How would that be allowed?

**Comment by james1293** [comment]
I don't know, as I haven't worked with Azure Functions since my 2019 post :sweat_smile:

Hopefully someone else will have input.

**Comment by jaslam94** [comment]
Actually, I was encoding the URL parameter with Base64. In order to solve the above issue, I opted for URL safe Base64 encoding. This has removed the prohibited characters from the encoded string.
