### ISSUE TITLE
Blobtrigger - Local Testing / Debugging Documentation

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#310]
_From @securityvoid on May 3, 2017 19:42_

I'm having a difficult time locating the documentation on debugging Blob trigger's locally. Is this possible with the CLI, or does stuff have to be deployed on Azure to test?

The main place you'd expect documentation is pretty much blank:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

This is the best docs I've found so far, but it leaves Blogtrigger's absent:
https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/

There are a few entries in the CLI that make it sound like it maybe supported, but real examples would really help. 

_Copied from original issue: Azure/azure-webjobs-sdk-script#1476_

**Comment by lindydonna** [comment]
_From @paulbatum on May 19, 2017 23:29_

@lindydonna Can you take a quick look at this?

**Comment by lindydonna** [comment]
_From @securityvoid on May 20, 2017 15:52_

Via trial and error, I was able to determine that local debugging of blog triggers DOES work. When the Azure Functions is running locally and a blog trigger is triggered, it will trigger the blob functions locally.

I still think this could handle to be doced clearer, but it definitely works.

**Comment by lindydonna** [comment]
_From @securityvoid on May 20, 2017 15:57_

While the doc is being worked on, it would also be good if somewhere it was more clear if blob triggers are only triggered on the creation of new files, and the updating of files, or if it also included the deletion of files (And if there is anyway to tell the difference).

The wording that is available is a little ambiguous with exactly how it works. Actually trying this stuff, its sometimes a little difficult to tell since if your function fails, it will retry. As a result, telling the difference between a retry (which has a delay), or the result of some other action you did (e.g. delete) complicates the empirical testing of this.

Its on my list of things to do to test this more carefully, but it would be even better if it was DOCed and I didn't have to guess/test.

**Comment by lindydonna** [comment]
@securityvoid I'm working on an updated doc this week. We had a lot of churn in the CLI commands, but it's much more stable now.

I'm moving this issue to Azure-Functions, where we track dock issues.

Blob triggers are only triggered on creates and updates. Deletes are not tracked, and there is no way to distinguish between create and update (without looking at the blob metatdata itself).

In general, queue triggers with a blob input are more reliable. For an example, see https://github.com/lindydonna/CoderCardsV2/blob/master/CoderCards/CardGenerator.cs#L20

**Comment by securityvoid** [comment]
@lindydonna Thank-you for the update on the blob triggers.

It was my understanding that in order to use Queue triggers, I had to upload the file within my own app and set the queue, rather than just using something like Storage Explorer. Am I understanding that correctly?

My C# is really bad, but my reading of that example code makes it look like my understanding above may not be correct?

**Comment by lindydonna** [comment]
@securityvoid You can use storage explorer to upload the file and to create the queue message.

Here's another example that shows the function.json: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#input-usage

**Comment by lindydonna** [comment]
Blob trigger behavior with the CLI will be documented as part of #112. Closing as a duplicate.
