### ISSUE TITLE
Document new dotted notation for bindings

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#311]
Support for dotted paths in binding expressions
- previously binding expressions could only reference the top level binding data properties
- now, if your trigger data contains nested objects, you can reference those properties as well
- see Http binding examples below which are a good example of this. However, this works with your own POCO objects as well

Http binding support for nested object properties
 
•	now, in addition to being able to reference top level properties of JSON bodies, you can reference nested properties as well
•	e.g. assuming JSON payload { a: 123, b: "testing", c: { d: 456 } }, you can use binding expression {c.d} to reference properties of the nested object

**Comment by ColbyTresness** [comment]
Closing (completed). Please reopen if any issues.
