### ISSUE TITLE
service bus binding does not accept EntityPath as connect string

### ISSUE THREAD

**Issue by globysdz** [Azure/Azure-Functions#315]
{
  "disabled": false,
  "bindings": [
    {
      "name" : "myFuncname",
      "topicName" : "request",
      "subscriptionName" : "processor",
      "connection" : "IncomingSubscription"
      "accessRights" : "listen",
      "type" : "serviceBusTrigger",
      "direction" : "in"
    }
  ]
}

the "incomingSubscription" was set via ARM template: 
    {
              "name": "IncomingSubscription",
              "value": "[listkeys(resourceId('Microsoft.ServiceBus/namespaces/topics/authorizationRules', parameters('bus_name'), 'request', 'perm-r'), variables('sbVersion')).primaryConnectionString]" 
     }

the result "inccomingSubscription" string contains ";EntityPath=xxxx" at the end of the string which AzureFunction throws exception at startup time:

Error indexing method 'Functions.globyscadProcessor' ---> System.ArgumentException : ConnectionString used to create MessagingFactory shouldn't include EntityPath as MessagingFactory is at Namespace level.

I am using the same connection string for my webapi application, which works fine. but for function it doesn't work. and there is no good way to automatically set the connection string variable (unless there is a way to obtain the connection string from ARM without EntityPath=xxx part).

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1168
