### ISSUE TITLE
Marketplace for Azure Functions

### ISSUE THREAD

**Issue by sebastus** [Azure/Azure-Functions#317]
I am writing a Function App that I hope many customers will want to use. I need an automated way to get it installed into their subscriptions. A marketplace seems like a good fit. Pricing isn't an issue, because once the function is installed, people pay according to the use of their function. 

For the time being, an ARM template with a button to install in Azure will have to do. Still have to figure out how to get a copy of my code into their Function App.

**Comment by lindydonna** [comment]
That seems like the best option. I'm not sure what the feature request is here?  You can deploy code using continuous integration or using MS deploy. Here's an example: https://github.com/davidebbo/AzureWebsitesSamples/blob/master/ARMTemplates/FunctionsWebDeploy.json
