### ISSUE TITLE
Input Parameters Published Incorrectly as Output Parameters

### ISSUE THREAD

**Issue by jchilde** [Azure/Azure-Functions#318]
Using VS 15.3 preview, .Net.Sdk.Functions 1.0.0-alpha5, and latest Functions VSIX

I created an Http Triggered function with following bindings:

public static async Task<HttpResponseMessage> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "graph/{TenantId}/{UPN}")]
             HttpRequestMessage req, 
            string TenantId, 
            [Table("Customers", partitionKey: "{TenantId}", rowKey: "TenantId")] CustomerEntity customerEntity, 
            TraceWriter log, 
            string UPN
            )

The functions works as expected from VS 2017 pulling customerEntity as an Input Table Binding.

Next I publish to Azure.

I notice that customerEntity is now identified as an Output Table Binding.  Function will not execute on Azure.

**Comment by lindydonna** [comment]
@ahmelsayed Could you take a look?

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#54
