### ISSUE TITLE
Comparison of Consumption vs. App Service plan features

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#32]
We've noticed that there is some confusion on the different Plan models:

![image](https://cloud.githubusercontent.com/assets/441607/19171977/6f34fce4-8bd4-11e6-9957-d3301f3b8b40.png)

Hopefully this can be clarified by Calvin or @dariagrigoriu

**Comment by lindydonna** [comment]
Note that classic will be renamed to "App Service Hosting Plan". See https://github.com/projectkudu/AzureFunctionsPortal/issues/586

**Comment by lindydonna** [comment]
Customer suggestion is to add a comparison table of what is and isn't supported in Dynamic vs. Classic. See https://github.com/Azure/azure-webjobs-sdk-script/issues/538.

**Comment by ctolkien** [comment]
Am not sure if this being addressed in GA, but creating a `Dynamic` plan wasn't available for Australia East, which was.. confusing.

**Comment by davidebbo** [comment]
It should already be available for Australia East. When did you last try?

**Comment by ctolkien** [comment]
@davidebbo - was a while back. Seems to have the dynamic options now!

**Comment by ggailey777** [comment]
@christopheranderson or @davidebbo do we have this info available?  If so, it's easy to add a table in [this topic](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale). Maybe that should then get linked to from the [Pricing page](https://azure.microsoft.com/en-us/pricing/details/functions/)?

**Comment by davidebbo** [comment]
The list is growing pretty quickly so doc would get out of date. I think the best way to test the list of regions that have Consumption is to look at the drop down when trying to create one.

**Comment by lindydonna** [comment]
@davidebbo @ggailey777 I think we're talking about different things. The proposal was to have a table to show the difference between feature sets in Dynamic and Consumption. 

Daria and I can provide this information, but we need to compile it and it will take some time.

**Comment by davidebbo** [comment]
Yep, sorry, I thought it was able listing regions...

**Comment by ggailey777** [comment]
@lindydonna thanks. I will add you to this issue to help track this.

**Comment by ggailey777** [comment]
@SyntaxC4 were you working this comparison table? Is that what you showed me on Tuesday?

**Comment by SyntaxC4** [comment]
Blog post has gone live here: https://blogs.msdn.microsoft.com/appserviceteam/2017/03/23/azure-app-service-web-api-mobile-ase-azure-functions-sku-comparison-matrix-2/
