### ISSUE TITLE
Functions monitoring history in portal is missing/broken

### ISSUE THREAD

**Issue by bedej** [Azure/Azure-Functions#320]
I have a function app with 4 functions that's been running for about a week. For the last 4 days there's no history in the "Monitor" section, as if the functions haven't run. The 4 functions run in a chained pipeline, initiated by an external service HTTP request. The functions write data to a storage table when they run. There are timestamped entries in the storage table for every day from the first function in the chain, indicating the functions have actually run. It appears that the functions runtime logging and/or portal monitoring UX is actually the issue.

Happy to provide the subscription ID/function app ID privately for someone to investigate.

**Comment by bedej** [comment]
This has stopped reproducing after applying a workaround for the linked issue above. May be appropriate to add more monitoring of the runtime with user/portal surfaced warnings to avoid this problem. But I'm unblocked, so please feel free to close.

**Comment by lindydonna** [comment]
@bedej Thanks for following up!
