### ISSUE TITLE
Document C# assemblies

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#321]
- Document use of attributes
- Link to NuGet packages that have the attributes
- Document use of return type for output binding

**Comment by nhwilly** [comment]
Really looking forward to this.  Anywhere we might go to figure out how some of these work? TIA

**Comment by paulbatum** [comment]
@nhwilly for now see here: https://blogs.msdn.microsoft.com/webdev/2017/05/10/azure-function-tools-for-visual-studio-2017/

**Comment by lindydonna** [comment]
@nhwilly You can also use this table to see what attributes are available: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#binding-at-runtime-via-imperative-bindings

**Comment by nhwilly** [comment]
Thanks @lindydonna

**Comment by lindydonna** [comment]
Available here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#triggers-and-bindings
