### ISSUE TITLE
External Table input (Google Spreadsheet) not found.

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/Azure-Functions#322]
Following the instructions from here: https://stackoverflow.com/a/41600108/27483
I created a function, established a link to my google account and then tried to hook up a spreadsheet.
It may be that the thing you refer to as "Data Set Name" in the External Table configuration is pointing to a name that I can't see on the spreadsheet I'd like to work with, but nothing I've tried works.
I used the spreadsheet Id and that failed. 
I tried the spreadsheet title and that failed to be found, too.
All calls resulted in this error on the console: System.Net.Http: Response status code does not indicate success: 404

**Comment by lindydonna** [comment]
@alexkarcher-msft Could you take a look?

**Comment by alexkarcher-msft** [comment]
Have you tried the instructions in our docs here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-external-table#data-source-settings

"The internal name (in bold) needs to be used as dataSetName, for example: docs.google.com/spreadsheets/d/**1UIz545JF_cx6Chm_5HpSPVOenU4DZh4bDxbFgJOSMz0**"

**Comment by irwinwilliams** [comment]
Thanks guys, the example I read on S/O didn't actually have the bold part, in bold. Followed this and it worked. 
Cheers.

**Comment by irwinwilliams** [comment]
Also, @alexkarcher-msft I think that link you provided should be in the section that says, 
"Documentation: This feature is experimental. Docs will be coming soon!"
A, la: 
![googlesheet_googlesheet](https://cloud.githubusercontent.com/assets/1428703/26656586/b7ce0a36-462d-11e7-822a-a6530b910f91.png)

**Comment by alexkarcher-msft** [comment]
That's an awesome idea! We'll totally try to sneak that in the next release :)
