### ISSUE TITLE
Azure Functions Runtime Uninstall and Reinstall does not work

### ISSUE THREAD

**Issue by venknar** [Azure/Azure-Functions#324]
Hi

Few issues that I am seeing with the Uninstallation and reinstallation of the Azure Functions Runtime.

On installing after the Uninstall, I see most of the files are not getting copied in the C:\Program Files\Azure Functions Runtime.

Also we  are not able to reset the database details since by mistake we had deleted the SQL Server db (azurefunctionsruntime).

See the below image:

![image](https://cloud.githubusercontent.com/assets/1523023/26724894/56700f4a-47b9-11e7-9b64-6338178bdd39.png)

For some reason it is getting cached and we are unable to reconfigure the database again.

The Azure functions portal is shown as empty:

![image](https://cloud.githubusercontent.com/assets/1523023/26724922/6eb5d468-47b9-11e7-9d9c-56c59422b0c0.png)

**Comment by jvano** [comment]
Thanks for letting us know. We will be improving the setup, uninstall, re-install and upgrade cases.
For now, to reset the configuration, please manually delete the following registry entries:

1. HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\FunctionsRuntime\FunctionsAdmin
2. HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\FunctionsRuntime\FunctionsManagement
3. HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\FunctionsRuntime\FunctionsWorker

Please don't delete the FunctionsRuntime registry

**Comment by venknar** [comment]
Thanks. It solved the issue. Closing it.
