### ISSUE TITLE
VS tooling should not pass explicit port when launching Functions Core Tools

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#325]
The Functions Core Tools allows changing the port in a config setting, but it's overridden by the command line. The VSIX should remove the port.

**Comment by aszalacinski** [comment]
Has this issue been road mapped for resolution?

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#288

**Comment by ColbyTresness** [comment]
Reverting move, tracking here.

**Comment by ColbyTresness** [comment]
This isn't applicable anymore since we run an EXE and the port property is configurable.
