### ISSUE TITLE
Codebase for Azure Functions proxies

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/Azure-Functions#327]
Hi,

where could I find codebase for proxies? I've checked both runtime and core and still not sign of it :(. Is it in other repository? I saw some branches where I can find some code related to proxies, but these are feature branches and don't seem to be correlated with the main functionality.

Best regards,
Kamil

**Comment by lindydonna** [comment]
@kamil-mrzyglod It's not public. @mattchenderson can provide more information.

**Comment by kamil-mrzyglod** [comment]
@lindydonna That made me sad :(

**Comment by alexkarcher-msft** [comment]
Proxies will remain MIT licensed, but closed source.
