### ISSUE TITLE
Continuous Integration, downloaded ZIP file can't be opened in Visual Studio

### ISSUE THREAD

**Issue by jantielens** [Azure/Azure-Functions#329]
I've created a new Bot Service in Azure (using the Proactive message template) it worked fine. :) I downloaded the zip file containing the source code, but after extraction Visual Studio wasn't able to open the Solution. Whatever I try I get the message "Some of the properties associated with the solution could not be read.". I tried Visual Studio 2017 and 2017 Preview. When using Visual Studio Code everything works find, but local debugging etc is not that nice.

Any ideas?

**Comment by lindydonna** [comment]
This repo is for issues in Azure Functions. I recommend posting on StackOverflow with the bot service tag.
