### ISSUE TITLE
Functions Runtime does not handle changing name of host.

### ISSUE THREAD

**Issue by ahelland** [Azure/Azure-Functions#330]
You might want to call out in the prereq section that the hostname should be configured/finalized before installing the Functions Runtime.

I know it is best practice to get things like that in order right after Windows is installed, but sloppiness in the lab had me running the installer first, and then changing the hostname. Completely borked things.

I thought it might be just an SSL issue, but it seems the hostname implants itself in many places that are hard to change afterwards. (Share name, database connection, web.config...) I don't need you to change the code to handle hostname change, but before people go troubleshooting their setup in a similar situation it's easier if they know the name should not be touched.

**Comment by jvano** [comment]
I totally agree, this is one of the first things we fixed after the preview release and it will be there for the next release.

Thanks for letting us know

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version we added the capability to configure the DNS name that is helpful when hosting the system and a "reset to factory" button in the configuration tool. In case you need to start from a clean state.
