### ISSUE TITLE
Application Settings for each one of Function, no more in Function App

### ISSUE THREAD

**Issue by jr-araujo** [Azure/Azure-Functions#333]
Hi Everyone,

As we know, Azure Functions were built based on WebJobs SDK and because of this, Azure Functions work almost like a WebJobs. But, If each one of Functions works into their own context, I am just wondering that maybe it would be more interesting IF each one of Functions had an **Application Settings** separately, like a Settings by Function Context.

**Conclusion**

It would be more interesting that when you create a new Function, this Function comes with its own **Application Settings**. Let's Imagine that today we have only one place on Azure Functions App Portal to configure ALL KEYS that we need to use in our functions. But, If we Have specific configurations for each one of them, How do you think can I solve this problem? So, what remains to me is to create KEYS like this:

**Application Settings**:

DB_KEY_FunctionX
DB_KEY_FunctionY

DocumentDB_Endpoint_FunctionX
DocumentDB_Endpoint_FunctionY

StorageBlobKEY_FunctionX
StorageBlobKEY_FunctionY

And so on!

I would like to hear from you about this scenario!

**Comment by ColbyTresness** [comment]
We won't be doing this. If there's a hard requirement for this, then the advice would be use multiple function apps.
