### ISSUE TITLE
We are not able to retrieve the runtime master key. Please try again later.

### ISSUE THREAD

**Issue by HarryMcCarney** [Azure/Azure-Functions#335]
This seems a common error and I have tried all the suggestions on similar issues here with no luck.  Session ID is below. Thanks.
Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: c008cf5e1b3341d283a0c9fe480a502c

Timestamp: 2017-06-10T21:58:12.520Z

**Comment by ahmelsayed** [comment]
It looks like you deleted your app, though the error I'm seeing was 

```
System.UriFormatException : Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri,Boolean dontEscape,UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.CreateResourceUri(Uri baseUri,IResourceDescription[] resourceDescriptions,String[] resourceNames,IDictionary`2 queryParametersAndValues)
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.GetAsyncResult`1.<GetAsyncSteps>d__22.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.Start()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.NamespaceManager.EndTopicExists(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,Func`2 endFunction,Action`1 endAction,Task`1 promise,Boolean requiresSynchronization)
   at async Microsoft.Azure.WebJobs.ServiceBus.Listeners.NamespaceManagerExtensions.CreateTopicIfNotExistsAsync(NamespaceManager manager,String path,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusSubscriptionListenerFactory.CreateAsync(CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Listeners.HostListenerFactory.CreateAsync(CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.StartAsyncCore(CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.StartAsync(CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 150
```

Which seems to point at an invalid service bus uri. What settings did you have for your function app? we should improve this error case. 

/cc @mathewc @fabiocav

**Comment by blade3** [comment]
@ahmelsayed, how can I see the error message (stack trace)? 
I'm looking in Kubu and I don't see that. (some error message or tracking log but not relevant information like this)
Because I have the same issues:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: ef244646d81d4aa1843e6813fc8f06a3

**Comment by ahmelsayed** [comment]
@blade3 is your app still having issues? The only exception I see is regarding an invalid host.json which was empty but it looks like it's fixed now.
regarding finding these exceptions, we are working to improve the discovery of these errors, but if you have AppInsights integration they should show up there, also if you go to `D:\home\LogFiles\Application\Function\Host` you should see log files there that contain this information.

**Comment by dtriana** [comment]
I'm having the same issue as well, on a function that was working last night, 
Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: b04be814293641509ba95606e4094d4f

Timestamp: 2017-06-15T01:34:43.236Z

Any idea? Thanks.

**Comment by dtriana** [comment]
Scenario: Function created with VS2017, published with VS2017, tested on the portal, working.

After that, on the portal, platform features, authentication, enable authentication, and then the "runtime master key" error starts showing again, and the function is dead. Disabling authentication, republishing, doesn't work.

Latests Session Id Session Id: f5df5f68f07e4c329f14fb8947fe747e

**Comment by urig** [comment]
Experiencing the exact same behavior. FUNCTIONS_EXTENSION_VERSION is ~1. How can this be fixed?

**Comment by sadgit** [comment]
I dropped an app and re-created with same name but different plan. Did it on Friday and am still getting this error after the weekend.

**Comment by ahmelsayed** [comment]
@dtriana it looks like you have an invalid Authentication\Authorization settings. In particular the OpenId Issuer setting. You have it set to `someName.onmicrosoft.com` while it should be `https://login.microsoftonline.com/someName.onmicrosoft.com` How did you end up with that setting? were you following some guide or what made you fill in that for a value there?

**Comment by ahmelsayed** [comment]
@sadgit are you still seeing errors? It looks like the errors that happened in session `163eda5c290943c3ac938f4fbc6eef73` were due to your functions running out of set quota. Did you have a quota set for your functions? I don't see any set now and it seems that your app is up at the moment.

**Comment by sadgit** [comment]
What is set quota
New sessions with same issues (3de47d9fd8744044b7aae368716ccc91, 179af3a64a4f4dd499d75aedd680c883) Dropped and re-created the app (again). Should be no quotas set. All functions are event hub/service bus and seem to run - but the UI won't permit tests or monitoring.

**Comment by ahmelsayed** [comment]
ah, the errors for these sessions are different. You are running into this issue https://github.com/Azure/azure-functions-ux/wiki/Manually-fixing-CryptographicException-when-trying-to-read-function-keys 

I had a nicer error message for this issue, but it looks like the string I was looking for changed so it's no longer showing the right error message. 

Can you try the steps in the wiki above?

**Comment by sadgit** [comment]
Just deleting the files in session f8f25972d1a64012921a16c07589d73b @ 2017-06-21T09:18:19.448Z still gives the same error, although the keys are regenerated still seeing a 500 with "Cryptographic error. Unable to encrypt or decrypt keys."
{"id":"5274e39a-3db4-4d33-b6bf-4fbd6ee2412c","requestId":"40aec39e-18c2-47ab-a76b-167e5218b9f8","statusCode":500,"errorCode":1000,"messsage":"Cryptographic error. Unable to encrypt or decrypt keys."}

**Comment by sadgit** [comment]
Still getting this issue despite clearing the key file several times
Session: ec463356b03546c3944822de3138ad5d

**Comment by ahmelsayed** [comment]
@sadgit which function app is having these issues? I see logs for few different apps, there is **01*** and **01**(slot), and **03**
the logs are referring to the 01 app as the one having issues, but that app doesn't exist any more so I can't look at it.

**Comment by sadgit** [comment]
I dropped the app and created #2 that is ok am going to wait for a few days
before rebuilding it under that name.

**Comment by ahmelsayed** [comment]
@sadgit let me know if you hit the same issue again. I'd like to look into it if there is a repro. Sorry about all the hassle

**Comment by sadgit** [comment]
@ahmelsayed - I had the same issue again today - I let the name I wanted lie idle for 10 days to let all caches drain.
Re-created the app under that name and after configuring the problem came back with a nicer message "can't decrypt keys".
So I dug around in the storage account ("AzureWebJobsSecretStorageType" = "Blob").
I found all sorts of old keys for apps and functions that no longer existed. So the secrets are not getting cleared from the Blob store on deletion of the function and/or overwritten when the mode is switched from Not-Blob to Blob.

What is the real impact of "AzureWebJobsSecretStorageType" - does it matter which to choose and why isn't it cleared out. PS - Google doesn't know what it's for either and Bing gives 8M results none actually relevant.

So by manually purging the blob store - I'm back in the game, but it's a bit too off-piste for my liking.

**Comment by ahmelsayed** [comment]
/cc @krolson and @fabiocav who would know more than I do about this.

What are the encryption keys used when the secrets are hosted on blob? I'm trying to understand what is the flow that could cause this error to happen.

**Comment by sadgit** [comment]
I'm not sure. However the blob store can be interrogated and you may well find a mass of old settings that don't relate to you current apps. On delete, make sure that the blob store is cleared out. On create ensure no conflict with previously stored keys.

**Comment by lindydonna** [comment]
It looks like the main issue was resolved, so I'm closing.

For this kind of question, [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so)  will get you a much faster reply. Please include your configuration in your question.

**Comment by niravbhalodiya** [comment]
Hi,

I am getting below error since last 2 days. Any Idea. How to diagnose this .. where  to look for the diagnostincs log or error log in azure functions ?

Error:

We are not able to retrieve the keys for function CampaignJobHandler. This can happen if the runtime is not able to load your function. Check other function errors.
Session Id: 14b8420b52bb4a87a65881277fb33c10

Timestamp: 2017-08-11T06:09:51.506Z

**Comment by DamianResler** [comment]
Hi,

I have similar issue sinse yesterday. New function (queue trigger), after deploing into azure causes error:

Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: 3ee2897e78f749868fa881dafa52160d

Timestamp: 2017-08-22T05:54:10.691Z

Any idea how to fix it?

**Comment by jnevins-gcm** [comment]
Not resolved. Been months. How do I fix?

**Comment by ahmelsayed** [comment]
@jnevins-gcm This is not the right place for posting this. 

open another issue and include your session ID and time stamp.
