### ISSUE TITLE
Migration of Azure Functions project (.funproj) from VS 2015 to VS 2017 fails consistently

### ISSUE THREAD

**Issue by urig** [Azure/Azure-Functions#336]
### Steps to reproduce

1. On Windows 10 (Home edition, v1703, build 15063.296)
2. Given a Visual Studio 2015 solution with an Azure Functions project (.funproj)
3. Open the solution in Visual Studio 2017 (either v15.2 Release or v15.3 Preview with the Tools for Azure Functions extension)

### Expected behavior:
Successful migration of the Azure Function project (to a .csproj project?)

### Actual behavior:
Review Project and Solution Changes window opens up showing this error:
> Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - MyProject, "C:\...\MyProject.funproj"

![image](https://user-images.githubusercontent.com/350687/27023700-5d7933a2-4f5c-11e7-8bb3-ec379e8e5c15.png)

When the migration is done, the Azure Function project is unloaded and cannot be loaded in Solution Explorer.

### Misc:

While this issue is open, might it be possible to provide instructions for manually migrating .funproj projects to the new project format?

PS - Also reported on [StackOverflow](https://stackoverflow.com/questions/43776035/unable-to-load-migrated-azure-functions-project-in-visual-studio-2017#comment75980198_43776035) (acceptable answer there is not really working though)

**Comment by urig** [comment]
As a side note, there's also a problem in the Migration Report following the failed migration. The report provides a link for further information. This link is broken.

> ..\MyProject.funproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660528&projecttype=33AD0EE8-D99B-4E14-8CD9-3F56ABEF97A2

![image](https://user-images.githubusercontent.com/350687/27023764-a1bf3d4a-4f5c-11e7-8735-b3dc06fe602b.png)

**Comment by lindydonna** [comment]
Unfortunately, project migration is not supported. The funproj project is fundamentally different from the new class library approach, so you'll have to migrate manually. This was covered a the bottom of the blog post here: https://blogs.msdn.microsoft.com/webdev/2017/05/10/azure-function-tools-for-visual-studio-2017/

**Comment by urig** [comment]
Thanks for the quick response @lindydonna .
I think it might be a good idea to fix the broken link in the Migration report so that it points an explanation like the one in the blog post.

**Comment by lindydonna** [comment]
@urig Unfortunately, to update the link, we'd have to do a new release of the VS 2015 tooling, which we aren't planning on doing. I apologize for the confusing experience.

**Comment by urig** [comment]
Thanks. Sorry for nagging, but what about fixing it from the other end? Putting a real page behind the link? :)

**Comment by lindydonna** [comment]
@urig Good point. I'll track down the page owners and follow up.

**Comment by lindydonna** [comment]
I followed up with the page owners, so we'll see if they fix it.
