### ISSUE TITLE
EventHub attribute not working in Visual Studio 2017 Azure Function tooling

### ISSUE THREAD

**Issue by cliffyq** [Azure/Azure-Functions#337]
I'm creating a simple function in VS2017 with an eventhub output binding:
```
using System;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Azure.WebJobs.ServiceBus;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("TimerTriggerCSharp")]
        public static void Run([TimerTrigger("0 */5 * * * *")]TimerInfo myTimer, 
            [EventHub( eventHubName: "productpublishevents", Connection = "ProductDiagnosticsEventHub" )]out string outputProductPublishEvents, 
            TraceWriter log)
        {
            log.Info($"C# Timer trigger function executed at: {DateTime.Now}");
            outputProductPublishEvents = "a";
        }
    }
}

```
But when I run it I'm getting this error:
TimerTriggerCSharp: Value cannot be null.
Parameter name: eventHubName.

I've tried using IAsyncCollector<string> instead of "out string", also tried putting the eventHubName in my local.setting.json and reference it in the attribute, but I keep getting the same error.

**Comment by bmoregeo** [comment]
Hello I'm having the exact same issue.  I was able to "fix" this by changing "eventHubName" to "path" in the function.json after it was published.  It looks like something is broken on the publication process that it is not setting the function.json correctly.

According to this link https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs the output should look like 

```{
    "type": "eventHub",
    "name": "outputEventHubMessage",
    "path": "myeventhub",
    "connection": "MyEventHubSend",
    "direction": "out"
}```

**Comment by lindydonna** [comment]
@bmoregeo and @cliffyq, have you tried updating your NuGet package Microsoft.NET.Sdk.Functions to alpha6?

**Comment by bmoregeo** [comment]
I thought I installed alpha6 in that package, but actually installed it in another package. It looks like upgrading did the trick.

**Comment by lindydonna** [comment]
Awesome, I'll go ahead and close this issue. Please reopen or open a new issue if the problem returns.
