### ISSUE TITLE
Http Function input always has a null content

### ISSUE THREAD

**Issue by Samwise001** [Azure/Azure-Functions#338]
I've been at this one 2 days now and I'm getting absolutely nowhere.

I'm doing a pre-compiled function app. Its brought in the following nugets:
Fare 
  Microsoft.AspNet.WebApi.Client 
  Microsoft.Azure.KeyVault.Core 
  Microsoft.Azure.WebJobs 
  Microsoft.Azure.WebJobs.Core 
  Microsoft.Azure.WebJobs.Extensions 
  Microsoft.CodeDom.Providers.DotNetCompilerPlatform 
  Microsoft.Data.Edm 
  Microsoft.Data.OData 
  Microsoft.Data.Services.Client 
  Microsoft.Net.Compilers ncy=true />
  Microsoft.Tpl.Dataflow 
  Microsoft.WindowsAzure.ConfigurationManager 
  ncrontab 
  Newtonsoft.Json 
  RestSharp 
  StackExchange.Redis 
  System.ComponentModel.EventBasedAsync 
  System.Dynamic.Runtime 
  System.Linq.Queryable 
  System.Net.Http 
  System.Net.Requests 
  System.Security.Cryptography.Algorithms 
  System.Security.Cryptography.Encoding 
  System.Security.Cryptography.Primitives 
  System.Security.Cryptography.X509Certificates 
  System.Spatial 
  WindowsAzure.ServiceBus 
  WindowsAzure.Storage 

My code looks like:
    public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, IAsyncCollector<UserPasswordChangeRequest> itemForQueue, TraceWriter log)
        {
            if (req.Content == null) // Always fails here
                return new HttpResponseMessage(HttpStatusCode.BadRequest);

    ... never gets further

I can add my content into the test pane on the right, with POST selected, and it always has a null content.

I've got this created via ARM so I've recreated the resource group many times, no change.

I have several other apps set up that as far as I can tell are identical that work...

If I got an error or something it would be a start, but nothing, I'm about ready to give up and choose another tech TBH

**Comment by slideep** [comment]
Hey there and cheers from sunny Creta . You are using Microsoft.NET.Sdk.Functions, correct? Have you tried running locally and/or creating a new function from a http trigger template?
`IAsyncCollector<T>` collector is an contravariant and takes in type of `T` item depending on which you are outputting your items. Also, **you need to curry and add parameter attributes** to both of your given parameters e.g. `[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "somefunction/name/{name}")]`
and `[ServiceBus()` etc.

Hopefully this makes some sense but the signature seems way too crispy and clear from our functions where they are polluted with all sorts of currying  noise .....

**Comment by Samwise001** [comment]
I'm following the instructions here:
https://blogs.msdn.microsoft.com/appserviceteam/2017/03/16/publishing-a-net-class-library-as-a-function-app/

I cannot get the func azure command line to switch accounts to get the appsettings.json file though so I can't get it running locally. I do the command "func azure account set Development01" and get back "Unable to find $Development01", despite it being there in the list when I run "func azure account list"

As for the code iteself, its a direct copy of code I have running in serveral other azure function apps, I know for sure I don't need to use attributes for this stuff, just a function.json file

**Comment by lindydonna** [comment]
Here's a working example (it binds to a POCO, but you can use HttpRequestMessage as well): https://github.com/lindydonna/CoderCardsV2/blob/master/CoderCards/CardGenerator.cs#L47

**Comment by Samwise001** [comment]
I'm getting the same issue, but it started happening when I upgraded the System.Net.Http nuget package. Been at this for HOURS now and getting nowhere

**Comment by Samwise001** [comment]
I'm not using the attribute-based as per my post above and not using the Sdk.Functions stuff so unfortunately thats not relevant.

I've actually recreated this in another function app now by upgrading the System.Net.Http nuget to the latest version

**Comment by lindydonna** [comment]
@fabiocav Can you comment on why System.Net.Http doesn't seem to work if on the latest version?

At any rate, @Samwise001 I think you have a workaround, which is to downgrade to the version of System.Net.Http that is specified as the dependency of the NuGet package [Microsoft\.Azure\.WebJobs\.Extensions\.Http](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Http/1.0.0-beta1).

We don't support binding redirects, so you can't use arbitrary NuGet packages. For instance, if you use a later version of the Azure Storage NuGet package, most things will not work.
