### ISSUE TITLE
ServiceBusSubscription Trigger Function: ESB connection string  not read from appsettings.json

### ISSUE THREAD

**Issue by sabbadino** [Azure/Azure-Functions#339]
Using vs.net 2015 and a azure function project:
**Functions.json**
{
  "disabled": false,
  "bindings": [
    {
      "name": "mySbMsg",
      "type": "serviceBusTrigger",
      "direction": "in",
      "topicName": "notification",
      "subscriptionName": "d3-monitoring",
      **"connection": "EsbConnection",**
      "accessRights": "Listen"
    }
  ]
}

**appsettings.json**
{
  "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "...",
        "AzureWebJobsDashboard": "..",
        **"AzureWebJobsEsbConnection": "..",**
        "mysetting": "aa"
    }
}

After I deploy I get this error 
 
Function ($ServiceBusTopicTriggerCSharp) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ServiceBusTopicTriggerCSharp'. Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string **'AzureWebJobsEsbConnection'** is missing or empty.

Isn't the appsettings.json supported ? I know I could write these settings in the azure portal or via an ARM template, but I'd like to know if there is a way to set settings for azure functions "in a file"
thank you 
Enrico

**Comment by sabbadino** [comment]
btw, I'm getting this behaviour running on Azure, running locally it does work (but I have to put EsbConnection and not AzureWebJobsEsbConnection in the appsettings.json file) .. same problem using vsnet 2017 15.3 preview

**Comment by lindydonna** [comment]
The connection string name should match what's in local.settings.json (appsettings.json is deprecated). See documentation here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#local-settings-file
