### ISSUE TITLE
Functions best practices topic

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#34]
Examples of content to include:
- Functions should be stateless
- Use queues between functions
- Functions within an app share resources. If you're using something a Function App in production, don't add test functions to it.

**Comment by wesmc7777** [comment]
@lindydonna send any other best practices you have that we want customers to keep in mind

**Comment by lindydonna** [comment]
Duplicate of https://github.com/Azure/Azure-Functions/issues/23
