### ISSUE TITLE
Function project with dashes in title does not compile

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#340]
To repro:
1. Using functions tools for VS 2017, make a new function project with dashes in title e.g. "functions-example"
2. Add a function (such as http trigger)
3. Attempt to compile

Expected result:
Compilation is successful. The default namespace has its dashes replaced with underscores

Actual result:
Compilation fails due to namespace having a dash.

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#289

**Comment by ColbyTresness** [comment]
Reverting move, tracking here.

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-templates#848
