### ISSUE TITLE
Visual Studio Functions Project deploying - not picking up correct azure resource groups

### ISSUE THREAD

**Issue by duckwaffle** [Azure/Azure-Functions#341]
This one is a bit of a pain in the ass to repro, but in my VS environment I have multiple Azure AD accounts attached, for different azure subscriptions. When I try to deploy a functions project to an existing functions app, switching between the accounts that I have added to VS updates the subscription list, but it doesn't seem to update the resource group list correctly.

This may only be related to my specific scenario, where the set up is:

- Main account in use has access to Subscription X, but can only write to resource group A
- Secondary account has access to Subscription X, and access to resource group A, B and C

When I switch from my main account to the secondary account, I still do not see resource groups B and C.

However, if I remove my main account from VS, and keep only the secondary account, I can see all 3 resource groups when choosing a deployment target.

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#290

**Comment by ColbyTresness** [comment]
Reverting move, tracking here.

**Comment by ColbyTresness** [comment]
This has been fixed.
