### ISSUE TITLE
Can't pick custom language in New Function dialog

### ISSUE THREAD

**Issue by julianatanasoae** [Azure/Azure-Functions#344]
Hi everyone,

When creating a new Azure Function from VS2017, it seems that you cannot choose a custom language, other than C#:

This is the New Function dialog in the VS2017 tooling:

![image](https://user-images.githubusercontent.com/3001526/27292747-10a16466-551d-11e7-9f60-c669766e37bd.png)

And this is the New Function dialog in older versions:

![image](https://user-images.githubusercontent.com/3001526/27292752-1652a596-551d-11e7-97a0-396da0a7cb17.png)

Are there plans to fixing this in the near future? :)
Thanks!

**Comment by lindydonna** [comment]
We do not plan to add a language picker to the Add Function dialog. We will add a new project template for F# however, and will add templates.

For other languages, we recommend using the Azure Functions Core Tools. See https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local
