### ISSUE TITLE
The clean and rebuild actions should allow overwrite of the function.json

### ISSUE THREAD

**Issue by ericleigh007** [Azure/Azure-Functions#347]
Currently, if I have a timer function with the entry point:
`        [FunctionName("FunctionTimerOrchestrator")]
        public static void Run([TimerTrigger("0 */5 * * * *")]TimerInfo myTimer, TraceWriter log)
`

and I change the CRON value to something like 

> 0 * */5 * * *,

 and rebuild, the function.json does not get updated, and therefore the timer continues to fire on that schedule.

I've found that if I delete the function.json file ONCE manually, it starts getting overwritten as would be expected, and seems to keep getting overwritten on each change.

**Comment by ahmelsayed** [comment]
which version of the build task do you have? You can find that from your csproj. 

![2017-06-20_16-59-41](https://user-images.githubusercontent.com/645740/27361095-e1f6bb94-55d9-11e7-88bf-19d50eec29e2.gif)

**Comment by lindydonna** [comment]
This issue should be fixed in the alpha6 version of the SDK. If the problem persists after upgrading, please reopen the issue.
