### ISSUE TITLE
[Visual Studio] IQueryable<T> Table binding direction is "out" in function.json

### ISSUE THREAD

**Issue by gjlumsden** [Azure/Azure-Functions#348]
I have the following parameter in a function decorated with the `TableAttribute`:

` [Table("%ArchiveTableName%", Connection="ArchiveTableConnection")] IQueryable<ArchivedEntity> tableQueryable`

Which results in the following binding configuration in function.json:

```
{
      "type": "table",
      "connection": "ArchiveTableConnection",
      "tableName": "%ArchiveTableName%",
      "direction": "out",
      "name": "tableQueryable"
}
```
with `"direction"` set to `"out"`. When the function runs, everything works as expected. Shouldn't the `"direction"` be set to `"in"` for an `IQueryable<T>` Table binding? According to the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#input-usage) for table bindings, `IQueryable<T>` is only valid for an input binding.

**Comment by ahmelsayed** [comment]
belongs in https://github.com/Azure/azure-functions-vs-build-sdk

**Comment by gjlumsden** [comment]
It does. Apologies. [The issue is already logged there](https://github.com/Azure/azure-functions-vs-build-sdk/issues/54).

**Comment by lindydonna** [comment]
@gjlumsden Thanks for following up. Closing this issue as a duplicate.
