### ISSUE TITLE
[Visual Studio] Adding a newer Azure Storage Nuget breaks app

### ISSUE THREAD

**Issue by brettsam** [Azure/Azure-Functions#349]
1. Create a fairly ordinary QueueTrigger that uses a `CloudQueueMessage` as a parameter:

       [FunctionName("QueueTriggerCSharp")]
       public static void Run([QueueTrigger("mover-items", Connection = "AzureWebJobsStorage")] CloudQueueMessage myQueueItem, TraceWriter log)
       {
          log.Info($"C# Queue trigger function processed: {myQueueItem}");
       }

2. Add the latest WindowsAzure.Storage nuget package as a new dependency.
3. Run

You'll end up with unexpected errors. It looks like because the versions don't match, we don't realize that `CloudQueueMessage` is a 'known' type. So we try to deserialize the contents of the message into it, which doesn't work.

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#59
