### ISSUE TITLE
Method not found on runtime from .dll

### ISSUE THREAD

**Issue by AnteDante** [Azure/Azure-Functions#35]
Hi,

I have a .dll I'm working on and using on the Azure Functions. The methods from .dll worker fine untill I added some new methods to it. 
When I upload the new .dll to the bin folder I created on the Azure functions and try to use the new methods I added I get 

2016-10-12T15:25:02.920 Function started (Id=xxxxxxxxxxx)
2016-10-12T15:25:03.045 Function completed (Failure, Id=xxxxxxxxxxxx)
2016-10-12T15:25:03.060 Exception while executing function: Functions.Report. mscorlib: Exception has been thrown by the target of an invocation. Report: Method not found: 'Void Company.Product.Compat.Report.SomeEngine.TestMethod()'.

It says that my TestMethod(); is missing. I am sure I uploaded the correct .dll versions as I tried creating a new seperate project, included that .dll's and tried to invoke the new methods I added and it worked, so they are there.

Compilation is successful when I add the .dll;s to Azure Functions, it's just that they are missing in runtime.

Could it be that Azure Functions compiler cached the dll's that I had before and is now trying to use them every time? That's the only think I can think of.

I tried deleting the Azure Function and creating a new one but the problem persisted.

EDIT: I tried to up the version of my .dll and it worked the first time I tried it. Now my TestMethod() runs normally, however when I added TestMethod2(), upped the .dll version again and rebuilded it, put it on Azure Functions the problem is the same. now TestMethod2() is not found. Maybe I just hit the time frame that Azure cleared it's cache and cached the .dll with only TestMethod() version on it.

This is a problem since I have to change the .dll frequently to test something out.

Thanks

**Comment by christopheranderson** [comment]
This is likely a host issue, if it is a bug. @fabiocav - can you confirm and then create the appropriate issue in azure/azure-webjobs-sdk-script (if there isn't one already)?

**Comment by AnteDante** [comment]
Any updates? Only solution I found was deleting the whole function app and creating it again.

**Comment by fabiocav** [comment]
@AnteDante if the assembly is properly versioned (i.e. the assembly identity changes as you change the types), this should work as expected and the new version will be resolved. Otherwise; you'll need to restart the function app to resolve the assembly. Deleting the function app is not required.

**Comment by lindydonna** [comment]
@AnteDante are you still experiencing this issue?  If so, please reopen.
