### ISSUE TITLE
Deployment documentation does not outline deploying code to prod

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#352]
The deployment section of the docs covers:
- continuous deployment
- ARM deployment of the function app resource

The section does not actually include instructions of how you would manage the deployment of your function app code to production. For example, using a release job in VSTS to do a msdeploy operation. Instructions for this step are going to be important once the customer wants to set up a release pipeline for their production function app.

**Comment by ColbyTresness** [comment]
I've recently merged a set of updates to the documentation around deployments that will be merged shortly. Please reopen this or a new issue if those changes doesn't cover this ask.
