### ISSUE TITLE
Run a function asynchronously?

### ISSUE THREAD

**Issue by apengwin** [Azure/Azure-Functions#358]
Is there a way to programmatically trigger a function, and have it run in the background? 

When I send a `POST` request to an HTTP trigger, I have to wait for the function to complete, but I'm looking for a way to get a response right away, and have the function run asynchronously.

**Comment by lindydonna** [comment]
This is usually accomplished by creating a queue output binding and using that to trigger another function. Here's a C# class library example: https://github.com/lindydonna/CoderCardsV2/blob/master/CoderCards/CardGenerator.cs#L47

Here's a graphical representation of the bindings (use my visualizer site at http://functions-visualizer.azurewebsites.net)

![image](https://user-images.githubusercontent.com/4260261/27503812-0e8ce3b0-5835-11e7-9307-c4550af8eff1.png)

**Comment by apengwin** [comment]
thanks for the quick response @lindydonna ! This looks like what i'm looking for. Is this any different from simply inserting a message into the queue from my client instead of the HTTP-triggered function?

**Comment by lindydonna** [comment]
@apengwin It's no different, but it can be more convenient to use an HTTP trigger, since then the client doesn't need permissions to write to the queue.

**Comment by artemious7** [comment]
Why use an Azure Queue? Can't I simply send an HTTP Request from the `RequestImageProcessing` function to the `GenerateCard` function and not wait for its result?

I could implement it like this (though with the `await Task.Delay(500)` workaround)

   
    [FunctionName("RequestImageProcessing")]
    public static async Task RequestImageProcessing([HttpTrigger(WebHookType = "genericJson")]
        HttpRequestMessage req)
    {
        // return from this Azure Function immediately
        using (var client = new HttpClient())
        {
            string anotherFunctionSecret = ConfigurationManager.AppSettings["GenerateCard_secret"];
            // change the RequestUri of the request to another Azure Function's 
            // public URL, providing the secret code, stored in app settings 
            // with key 'GenerateCard_secret'
            req.RequestUri = new Uri(req.RequestUri.AbsoluteUri.Replace(
                req.RequestUri.PathAndQuery, $"/api/GenerateCard?code={anotherFunctionSecret}"));

            // don't 'await' here. Simply send.
            client.SendAsync(req);
            // wait a little bit to ensure the request is sent. It will not 
            // send the request at all without this line, because it would 
            // terminate this Azure Function immediately
            await Task.Delay(500);
        }
    }

    [FunctionName("GenerateCard")]
    public static async Task GenerateCard([HttpTrigger(WebHookType = "genericJson")]
        HttpRequestMessage req)
    {
        // handle the request in a usual way
        await Worker.DoWorkAsync(req);
    }
