### ISSUE TITLE
Implement a Lease on File that holds Azure Function Code

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#361]
I was doing some tests with a Azure Functions and I realized that it creates many things inside my Azure Storage Account. I've removed content from "Blobs", "File Shares", "Tables" and "Queues" and now I realized the code of my Azure Functions is gone. 

For some important items there's a lease that blocks me to remove the content, but on the file that stored my code there wasn't. Here's my feedback, implement a lease on it.

**Comment by lindydonna** [comment]
We previously added a storage account lock, but it was a very confusing experience for most customers. Instead we've documented how the storage account is used, and it's also in the tooltip when you create an account. 

![image](https://user-images.githubusercontent.com/4260261/27554911-de3268d4-5a64-11e7-9555-72c95d5f2bc1.png)

Link goes here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-app-portal#storage-account-requirements
