### ISSUE TITLE
possbile portal bug

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#362]
Right now I can't remove my Azure Functions through the portal.
![bug](https://user-images.githubusercontent.com/1413082/27528548-0d9bfc58-5aa5-11e7-826b-d61633e7fa05.png)

**Comment by lindydonna** [comment]
Yes, this is a bug that will be deployed today. Closing as duplicate. https://github.com/Azure/azure-functions-ux/issues/1469
