### ISSUE TITLE
Functions Core Tools article should mention that it's currently Windows only

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#369]
The article https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local should add a note that the Core Tools only works on Windows.

**Comment by ggailey777** [comment]
I added this note during my most recent update to the Core Tools topic: https://github.com/MicrosoftDocs/azure-docs-pr/pull/17263

**Comment by ggailey777** [comment]
This fix is now live: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local 
Closing as fixed.
