### ISSUE TITLE
Dynamic plans Function Apps can't change their Dynamic Plans

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#37]
As the title says, Dynamic plan Function Apps can't change their Dynamic Plans. We should document this.

**Comment by wesmc7777** [comment]
@christopheranderson   I assume this should go here:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale

Is it possible to change to Dynamic/Consumption from an App Service Tier Function App?  I don't see that documented either.

**Comment by wesmc7777** [comment]
https://github.com/Microsoft/azure-docs-pr/pull/1608
