### ISSUE TITLE
VNET Integration from App Service Plan

### ISSUE THREAD

**Issue by ssatheeshkumar** [Azure/Azure-Functions#372]
Hello,

I am trying to establish a P2S connection between an Azure Function running in app service plan and a VM in a VNET. I have implemented a simple function to create / read a file in one of the shared folder of the VM but unable to do so. Using a tcpping from the kudu resulted in error "An attempt was made to access a socket in a way forbidden by its access permissions ". Not sure what i am missing here. Any help is greately appreciated.

Function info below :
2017-07-04T12:00:04.848 Function completed (Success, Id=bef785c0-e291-47e2-bfff-189b9ee7435b, Duration=3ms)

**Comment by lindydonna** [comment]
CC @MikeStall

**Comment by ColbyTresness** [comment]
@alexkarcher-msft for VNET

**Comment by alexkarcher-msft** [comment]
By "read a file in one of the shared folder of the VM" do you mean using Windows file sharing? This is explicitly blocked by P2S gateways. You will need to use FTP or some other file server. Our new preview direct VNET integration currently supports windows file sharing.

https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet
