### ISSUE TITLE
Error in code sample for blob binding

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#373]
The blob sample here shows an assignment from string to stream. Should change it to Stream.CopyToAsync, probably:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#incsharp

```csharp
// Copy blob from input to output, based on a queue trigger
public static void Run(string myQueueItem, Stream myInputBlob, out string myOutputBlob, TraceWriter log)
{
    log.Info($"C# Queue trigger function processed: {myQueueItem}");
    myOutputBlob = myInputBlob;
}
```

**Comment by tdykstra** [comment]
Fixed in https://github.com/MicrosoftDocs/azure-docs-pr/pull/28037/
