### ISSUE TITLE
Is there a way to read and write from blob storage without using an input binding?

### ISSUE THREAD

**Issue by apengwin** [Azure/Azure-Functions#374]
I'm wondering if there's a way to  could use the client libraries for blob storage in the function to access blob storage. 

I tried running  `from azure.storage.blob import BlockBlobService`  in the portal, but I get a no such module import error.

**Comment by lindydonna** [comment]
What language are you using?

**Comment by apengwin** [comment]
python, but also looking into C#

**Comment by apengwin** [comment]
@lindydonna  is this possible with python?

**Comment by ahmelsayed** [comment]
you'd need to pip install the module you want to import. We don't have any python modules preinstalled on the VMs
