### ISSUE TITLE
Document how to use Functions in an ILB ASE

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#377]
You should be able to just create a function app as you’d on azure. However to use the function UX (to be able to run and manage your functions from the portal) you need to be able to access https://yourApp.YourILBDomain.com and https://yourApp.scm.YourILBDomain.com from the machine you’re managing the function app from without ssl errors in the browser. 
So the requirements are:

1)	Be in the same vnet as your ILB ASE
2)	Have a valid cert for the default domain and the default scm domain. *.yourILBDomain.com and *.scm.yourILBDomain.com

**Comment by DivineOps** [comment]
The list is missing a step. In addition to having a certificate, you also must configure the DNS for the ILB domain. 
The easiest way to configure DNS in a test environment is by adding a mapping in the hosts file on the VM you are browsing from. The line in the hosts file must specify each subdomain, not a wild card. On Windows, the hosts file is located at C:\Windows\System32\drivers\etc. The line you need to add looks similar to the following:

192.168.XXX.XXX    yourFunctionApp.yourILBDomain.com   yourFunctionApp.scm.yourILBDomain.com

Also, for completeness sake, the steps to create a self-signed certificate for the ILB domain are outlined here (note that you can upload the certificate you create using the portal, not just by using an ARM template): https://docs.microsoft.com/en-us/azure/app-service-web/app-service-app-service-environment-create-ilb-ase-resourcemanager#uploading-and-configuring-the-default-ssl-certificate

**Comment by alexkarcher-msft** [comment]
This is documented here: https://docs.microsoft.com/en-us/azure/app-service/environment/network-info#functions-and-web-jobs
