### ISSUE TITLE
[Visual Studio] function.json bindings not generated correctly for ServiceBus output

### ISSUE THREAD

**Issue by sebastianroesch** [Azure/Azure-Functions#378]
Hi,

I downloaded the latest version of the Azure Function Tools extension for Visual Studio 2017 Preview. 
I created a function in C# with a ServiceBus queue output like this:
```cs
public static HttpResponseMessage Run([HttpTrigger(AuthorizationLevel.Function, "post")]
HttpRequestMessage req, 
[Table("lead", Connection = "STORAGE")]ICollector<Lead> outTable, 
[ServiceBus("createcompany", Microsoft.ServiceBus.Messaging.AccessRights.Manage, Connection = "SERVICEBUS")]out string serviceBusMessage, 
TraceWriter log)
```

When I publish from VS, the generated function.json has two errors and is not recognized by Azure. The JSON keys for `queue` and `access` are different compared to those the Azure portal generates when I add an integration there. 
```javascript
{
      "type": "serviceBus",
      "queue": "createcompany", // -> should be "queueName"
      "connection": "SERVICEBUS",
      "entityType": "queue",
      "access": "manage", //-> should be "accessRights"
      "direction": "out",
      "name": "serviceBusMessage"
}
```
When I change it manually in the portal, it works.
I'm using version 0.2 of the Azure Function Tools.

**Comment by lindydonna** [comment]
We had a bug in the initial version of the SDK that generates function.json. Please manually clean your project and upgrade your NuGet package to the latest: https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions

**Comment by sebastianroesch** [comment]
Thanks, I updated the package, cleaned the project files and cleared the Nuget cache but then it worked!

**Comment by lindydonna** [comment]
@sebastianroesch Thanks for following up!
