### ISSUE TITLE
We don't support Blob Only Storage Accounts

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#38]
We need to document in the Storage Account bindings section that we don't support Blob Only Storage Accounts.

Related:
https://github.com/Azure/azure-webjobs-sdk/issues/797

**Comment by SyntaxC4** [comment]
Here it is, they are called "Blob storage accounts" which provide block only support in blob storage (instead of both block and page) 

https://azure.microsoft.com/en-us/documentation/articles/storage-create-storage-account/#blob-storage-accounts

**Comment by lindydonna** [comment]
They also don't have queues, which are required for the primary storage account.

**Comment by wesmc7777** [comment]
https://github.com/Azure/azure-content-pr/pull/33110
