### ISSUE TITLE
Error when deploying with VSTS

### ISSUE THREAD

**Issue by tjrobinson** [Azure/Azure-Functions#380]
I can publish from Visual Studio 2017 Preview without problems but get this error when deploying using VSTS and a Hosted VS2017 host.

`C:\Users\buildguest\.nuget\packages\microsoft.net.sdk.functions\1.0.0-alpha3\build\netstandard1.0\Microsoft.NET.Sdk.Functions.targets(44,5): error : Could not load file or assembly 'Microsoft.Azure.WebJobs.Host, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.`

What other information would be helpful?

**Comment by leftler** [comment]
run the build with the `system.debug` variable set to `true` then re-create the error. After that on the failed build with the debug information click the "download all logs as Zip" button on the build and attach the logs as a reply to this issue..

**Comment by tjrobinson** [comment]
I am worried about posting potentially sensitive information to a public place. Is there somewhere private I can send the logs?

**Comment by leftler** [comment]
@tjrobinson the closest I know of is on the [Application Insights wiki page](https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview)#providing-feedback) Perhaps send a email there with the private details.

> # Providing feedback
> 
> Please provide feedback early and often. You can provide feedback in the format you prefer, but when in doubt, use GitHub.
> When you report an issue, especially on GitHub, please be sure to include:
>  - Description of the issue
>  - Provide a Function App name and any specific Functions you had issues with
>     - If you’d rather not share these publicly, please send me an email (chrande@microsoft.com) with the names and link to the issue.
>  - Provide a timestamp (include time zone, UTC preferred)
>  - Any error messages
>  - Repro + function.json

**Comment by lindydonna** [comment]
Please see https://blogs.msdn.microsoft.com/appserviceteam/2017/06/01/deploying-visual-studio-2017-function-projects-with-vsts/

For this kind of question, [MSDN forums](https://aka.ms/func-forum) or [StackOverflow](https://aka.ms/func-so)  will get you a much faster reply. Please include your configuration in your question. Tracking IDs are not sensitive information, so they can be safely posted.

**Comment by tjrobinson** [comment]
@lindydonna That seems to have worked, thank you! I used the blob post to get going. I think the main difference between that and what I had before is that I had been using `dotnet publish` rather than `Visual Studio Build`.

**Comment by tekguy** [comment]
@tjrobinson @lindydonna  

I have this same error, what did you do to fix it? I am using the latest stable nuget.exe (4.1.0) file to download the package and I am still getting this error, my setup is slightly different. I am using Team City (and the dotnet plugin).

I even tried issuing a dotnet publish on my local dev machine:

dotnet publish -c Release

But I get the following error:
C:\Users\gordo\.nuget\packages\microsoft.net.sdk.functions\1.0.0-alpha3\build\netstandard1.0\Microsoft.NET.Sdk.Functions.targets(44,5): error : Could not load file or assembly 'Microsoft.Azure.WebJobs, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. [C:\COMMENTOUT\Functions.Azure\Functions.Azure.csproj]

Any help would be greatly appreciated to fix this error. It's been driving me crazy for a couple days. Thank you!

**Comment by tjrobinson** [comment]
@tekguy I think the main difference that fixed it for me was to build/publish using Visual Studio/MSBuild rather than running `dotnet publish`. Good luck.

**Comment by tjrobinson** [comment]
For reference, I have had the same problem with TeamCity and changing the build configuration to use Visual Studio instead of `dotnet build` resolved the problem.

**Comment by jensdotbruggeman** [comment]
Having the same issue : utilizing the latest version of Visual Studio Build Tools 2017.
Issue when using dotnet build , but not when using MSBuild..  What is the reason for this?

P.S..
These actions are not ran within VSTS solution.
