### ISSUE TITLE
Binding error with SendGrid precompiled function using VS2017 preview tooling

### ISSUE THREAD

**Issue by mattridgway** [Azure/Azure-Functions#381]
I've created a precompiled function which uses the VS2017 functions preview tooling, which has a Service Bus Queue input trigger and a SendGrid output trigger. However whenever it runs it has an error

```
[10/07/2017 16:03:41] Microsoft.Azure.WebJobs.Host: 
Error indexing method 'Functions.SendEmail'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'message' to type SendGridMessage. 
Make sure the parameter Type is supported by the binding. 
If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

This is the same whether I run it through the portal or run it locally. I've created an [example repo here](https://github.com/mattridgway/SendGridPrecompiledFunction) which will show the error, although I've not checked in local.settings.json as these contain my keys for SendGrid, service bus and a storage account. If I remove the SendGrid binding the Queue trigger works fine, and it will run locally, so I have a work around that I could just create a SendGrid client and send the message without the output binding, but it would be tidier if this worked as intended.

**Versions**
OS: Windows 10 Enterprise
VS: Visual Studio Enterprise 2017 Preview 15.3.0 Preview 3.0
Functions: [0.2](https://marketplace.visualstudio.com/items?itemName=AndrewBHall-MSFT.AzureFunctionToolsforVisualStudio2017)
Libraries: 
* Microsoft.Azure.WebJobs 2.1.0-beta1
* Microsoft.Azure.WebJobs.Extensions 2.1.0-beta1
* Microsoft.Azure.WebJobs.Extensions.Http 1.0.0-beta1
* Microsoft.Azure.WebJobs.Extensions.SendGrid 2.0.0
* Microsoft.Azure.WebJobs.ServiceBus 2.1.0-beta1
* Microsoft.NET.Sdk.Functions 1.0.0-alpha3
* Newtonsoft.Json 10.0.2
* Sendgrid 9.5.0

**Comment by gjlumsden** [comment]
Not sure that the type `SendGridMessage` is supported. The [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-sendgrid) indicate that `Mail` is the supported type for SendGrid output bindings.

Might be worth trying the pre-release version of Microsoft.Azure.WebJobs.Extensions.SendGrid (2.1.0-beta1) if changing the type doesn't help. I had a similar message using 2.0.0 when binding to a parameter of type `IAsyncCollector<Mail>`.

**Comment by mattridgway** [comment]
Good suggestion on trying out the beta, I will have a go later this week. 

With regards to not using SendGridMessage, the SendGrid attribute XML docs/intellisense says `Attribute used to bind a parameter to a SendGridMessage that will automatically be sent when the function completes.` so i'd have assumed SendGridMessage was OK, although I wonder if this is anything to do with their breaking changes to the underlying SendGrid Library?

When I've got this working I will put in a PR to update the docs (https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#sendgrid).

**Comment by lindydonna** [comment]
I'm not sure of the question here. Are you asking whether `SendGridMessage` works, or just the `Mail` type?

**Comment by mattridgway** [comment]
Hi @lindydonna, it was more a question of how should the SendGrid output binding be added using precompiled functions with the preview tooling? I've tried using the SendGridMessage, as the XML docs suggest, however raises the error above. The [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#sendgrid) is a little unclear. In the 9.5.0 version of the SendGrid Library there doesnt appear to be a Mail type. 

It looks like there is an updated version of SendGrid (9.5.1) which i will try now, along with the preview version (2.1.0-beta1) of the WebJobs.Extensions.SendGrid library.

**Comment by mattridgway** [comment]
Looks like upgrading both has worked fine, although from the error i assume it was the WebJobs.Extensions.SendGrid library that made the most difference. The code now looks like this:

```csharp
[FunctionName("SendEmail")]
public static void Run(
    [ServiceBusTrigger("outgoingemails", AccessRights.Manage, Connection = "NOTIFICATIONSSERVICEBUSCONNECTION")] OutgoingEmail email,
    [SendGrid] out SendGridMessage message)
{
    message = new SendGridMessage();
    message.AddTo(email.To);
    message.AddContent("text/html", email.Body);
    message.SetFrom(new EmailAddress(email.From));
    message.SetSubject(email.Subject);
}
```

I will put in a PR for the docs so they now have a code sample.

**Comment by kubiozi** [comment]
I cant find SendGridAttribute to decorate the message variable. Which assembly am I missing?

**Comment by tokyo0709** [comment]
@kubiozi 
You are probably looking for Microsoft.Azure.WebJobs.Extensions.SendGrid
