### ISSUE TITLE
[Visual Studio] Include a local version of the Core Tools in the Functions Tooling

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#382]
To avoid the additional download, we should include a version of the Core Tools in the Azure Functions Tooling package for VS 2017.

**Comment by leftler** [comment]
I installed the core tools using `npm i -g azure-functions-core-tools` so 1.0.2 is installed in my `%appdata%\npm\func` folder and is added to my PATH, I then removed my `%localappdata%\Azure.Functions.Cli\1.0.0` folder. When i debug a function from inside visual studio it recreates the 1.0.0 folder and it uses that version during debugging.

the version from npm states when you run it
```
Azure Functions Core Tools (1.0.2)
Function Runtime Version: 1.0.11075.0
```

The version autogenerated from visual studio states when you run it
```
Azure Functions Core Tools (1.0.0-beta.101)
Function Runtime Version: 1.0.11075.0
```

Is using the fixed 1.0.0-beta.101 version when using visual studio the desired behavior?
