### ISSUE TITLE
Update document for handling of local.settings.json

### ISSUE THREAD

**Issue by brharr** [Azure/Azure-Functions#386]
Currently the documentation page which covers how to store and use values within the local.settings.json file is more than a year old and is not valid. 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

For example, there are references to using System.Environment and System.Configuration namespaces to retrieve values from the file and those are no longer valid namespaces. When creating a default Functions app within Visual Studio, I believe that is is using .NET Core which does not contain all of the namespaces and some of them do not even existing in .NET Core 1.1. 

As someone that has knowledge of different languages, I really depend on this documentation to help me get through these kind of issues. 

Thanks,
Brian

**Comment by lindydonna** [comment]
@brharr The article is actually quite new, it looks like we didn't update the date. The new Azure Functions project type is based on .NET Core 2.0, and the functions actually run on .NET 4.6 full framework.

What issue are you running into?  Can you provide some code that you can't get working?
