### ISSUE TITLE
General Availability of App Insights integration

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#388]
This is a tracking issue for the App Insights support in Azure Functions to go into general availability.

@brettsam @christopheranderson please expand this with a list of major outstanding issues or links to appropriate work items. This should include both UX and backend.

**Comment by leftler** [comment]
I know ILogger was introduced to provide better logging with App Insights. I reported a possible issue that may need to be fixed before GA.

Issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/1675

**Comment by mattchenderson** [comment]
Closing as this has occurred: https://azure.microsoft.com/en-us/blog/serverless-for-all-developers-bringing-azure-functions-to-linux-mac-planet-scale-nosql-real-time-analytics-and-productivity-apps/
