### ISSUE TITLE
Explain the Azure Files dependency on the Consumption plan

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#39]
Customers may be confused when they delete a function app but keep the storage account, and their files are still there. Similarly, if they delete their storage account, they will delete all of their code. This should go in the Dynamic Compute article (https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale). 

Use the text from this issue: https://github.com/Azure/Azure-Functions/issues/173

**Comment by lindydonna** [comment]
@rachelappel Would this be a topic you could take?

**Comment by rachelappel** [comment]
@lindydonna  Yep

**Comment by lindydonna** [comment]
@rachelappel Thanks Rachel!  Can you also take https://github.com/Azure/Azure-Functions/issues/173?

**Comment by rachelappel** [comment]
@lindydonna yep

**Comment by rachelappel** [comment]
https://github.com/Microsoft/azure-docs-pr/pull/7607
