### ISSUE TITLE
WebDeploy does not remove function.json file for functions which no longer exist

### ISSUE THREAD

**Issue by duckwaffle** [Azure/Azure-Functions#392]
I'm using VSTS to deploy a function app that is being written using the preview Functions Tooling in vs2017, and I'm following the steps defined [here](https://www.joshcarlisle.io/blog/2017/5/17/visual-studio-2017-tools-for-azure-functions-and-continuous-integration-with-vsts).

When I started the project, I created a test HttpTrigger, named "HttpTriggerTest". I have since replaced that endpoint with other ones, using different names. The new functions/triggers that I have created work just fine, however I noticed that in the Azure portal, the "HttpTriggerTest" trigger is still showing up in the portal.

Clicking on that trigger raised all sorts of errors, complaining that the entry point to that trigger is no longer valid (for good reason, it no longer exists). I had a poke around in Cloud Explorer and noticed that the folder named "HttpTriggerTest" and corresponding function.json file still exists in the file system.

Opening up my deployment package I confirmed that HttpTriggerTest is no longer present in the deployment Zip file, so I'm not sure if this is an issue with WebDeploy, or the Functions tooling, but it would be great if non-existent triggers could be cleaned up on deploy. Otherwise it's a giant pain the ass, requiring you to go into the azure portal, enable read/write for the function app (because it gets set to Read Only when you deploy from VSTS), and then manually delete the trigger.

Steps to repro:
- Create new Functions project
- Add a trigger
- Deploy to Azure
- Remove the trigger from your project
- Add a new one (probably not necessary)
- Redeploy to Azure

**Comment by lindydonna** [comment]
What version of the Functions SDK package are you using?  https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions. Make sure you're on the latest, as there were some bugs having to do with cleaning the output. We still have a bug that clean doesn't delete function.json, so please delete your bin folder manually.

If you're on the latest, take a look at your output folder and see if that test function is still there?

**Comment by duckwaffle** [comment]
I'm on the latest alpha6, the output folder definitely no longer has the old function folder/function.json, and the web deploy package no longer has it either. It's almost as if the webdeploy process isn't cleaning up and removing the old function.

I just ran another test deploying from Visual Studio and the same thing happens, even though the function.json is no longer in the obj\PubTemp folder the function is not deleted from the portal.

**Comment by lindydonna** [comment]
That is surprising, given that WebDeploy usually does a diff. I'll have to try to repro.

For now, check the box to "Remove additional files at destination"

**Comment by ColbyTresness** [comment]
Closing as this is stale. Please reopen if you're still seeing this.
