### ISSUE TITLE
Functions Tooling - Binding POST input as POCO in HttpTriggers?

### ISSUE THREAD

**Issue by duckwaffle** [Azure/Azure-Functions#397]
Reading through the documentation for .csx style functions, it looks like it's possible to bind the body of a POST request for a HttpTrigger to a POCO in the method signature, is this supported in the Function Tooling for VS? If there aren't any attributes that support this type of binding in the SDK yet, how would you go about creating the function.json file that corresponds to that function so we can manually create the binding?

It would be much nicer to be able to do this rather than having to read the request content as a string, then deserializing the JSON.

**Comment by lindydonna** [comment]
It is supported. Here's an example: https://github.com/Azure-Samples/functions-dotnet-codercards/blob/master/CoderCards/CardGenerator.cs#L47. It's binding the request to CardInfoMessage, which is a POCO.

**Comment by lindydonna** [comment]
It turns out that it's not actually documented (at least, not directly)!  Thanks for pointing it out. We've created an issue to track to the doc improvement: https://github.com/Azure/Azure-Functions/issues/401
