### ISSUE TITLE
Example of Mobile Apps table with both authentication and API key

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#4]

**Comment by SyntaxC4** [comment]
[Blocked]

**Comment by SyntaxC4** [comment]
Talk to @brettsam about the mobile binding, we should try to get this on the books soon to help boost Mobile usage.

**Comment by lindydonna** [comment]
It doesn't seem like a high priority to boost usage of this binding, as we have other topics that we know customers are interested in but don't have enough documentation (storage, event hub, service bus).
