### ISSUE TITLE
Functions Tooling for Visual Studio for Mac, or Visual Studio Code for Mac

### ISSUE THREAD

**Issue by balupton** [Azure/Azure-Functions#402]
I've recently become very excited with Azure Functions. I am currently a Visual Studio Code for Mac user.

I noticed that there is Functions Tooling for Visual Studio ([page](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio), [video](https://www.youtube.com/watch?v=A8y7kffqQ48)). I anticipated this meant Visual Studio for Windows as well as Visual Studio for Mac, turns out that isn't the case. Nowhere in that documentation page does it mention it is Windows only.

As an aside, I also noticed Data Science Tooling for Visual Studio ([video](https://www.youtube.com/watch?v=bq5US1GQTcc), [page](https://www.visualstudio.com/vs/rtvs/)) which is also interesting me, but again not available for Visual Studio for Mac.

Is there any plans to bring first-class cloud and functions support to Visual Studio for Mac or Visual Studio Code for Mac, in the same way that they have first-class support on their windows equivalents.

**Comment by ahelland** [comment]
It´s only in a preview version of Visual Studio for Windows as well, so as far as GA versions go they are on par (as in "no tooling") :)

As for Azure Functions specifically there have been some low-level bits and bytes that only work on Windows from the OS perspective regardless of Visual Studio. Not sure where things are with regards to that part.

**Comment by balupton** [comment]
Okay thanks. I guess it is a wait and see situation then. Seems the community ecosystem is going good work with extensions for Visual Studio Code, so will experiment with that until there is an official/comprehensive offering for mac users.

**Comment by lindydonna** [comment]
@balupton We do have preview tooling for VS for Mac, but it is not as full-featured as our Windows tooling. In particular, it has the following limitations:

* No file/item templates
* Functions that use Queues or EventHub don’t work
* No publishing support

We plan to update the tooling sometime this calendar year. CC @mhutch

**Comment by mhutch** [comment]
@balupton the version of Visual Studio for Mac in the alpha update channel has preview support for Azure Functions, with the limitations that @lindydonna mentioned.

**Comment by balupton** [comment]
@mhutch how do I get it? I've tried looking for instructions, but getting a lot of conflicting information

**Comment by Xamtastic** [comment]
When will Azure Function file/item templates for VS for Mac be available in the Alpha/Beta channels?

**Comment by RocketPop** [comment]
@balupton It's an extension right now for VS Mac 7.2 - go to the extensions manager and search for "functions". Then you can install the preview version.

**Comment by 0xced** [comment]
Visual Studio 2017 for Mac can [publish Azure Functions since version 7.6](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-mac-relnotes#--azure-functions).

**Comment by mattchenderson** [comment]
Closing old issue - VS for Mac can publish, as per prior comment.
