### ISSUE TITLE
[Visual Studio] DisableAttribute overloads not working as expected

### ISSUE THREAD

**Issue by martijns** [Azure/Azure-Functions#403]
The Azure Function Tools for Visual Studio 2017 appears to generate the function.json incorrectly when it comes to the DisableAttribute. Whenever the [Disable] attribute is placed on a class or method, the generated function.json always contains `"disabled": true`. This is as expected. However, when using the DisableAttribute overload, such as the `public DisableAttribute(string settingName)` overload, it still generates `"disabled": true`, but I would expect it to generate `"disabled": "mySettingName"`.

I'm expecting this is an issue in the VS2017 extension instead of the Azure CLI Runtime or the Webjobs host. Manually adjusting the function.json results in the expected behavior, both while debugging locally as when modifying the function.json remotely via FTP.

Currently using:
- VS2017 Enterprise Preview 15.3.0 Preview 4.0
- Azure Functions CLI 1.0.0-beta.100
- Microsoft.Azure.WebJobs 2.1.0-beta1
- Microsoft.NET.Sdk.Functions 1.0.0-alpha6

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#69
