### ISSUE TITLE
Health check / restart unresponsive function app

### ISSUE THREAD

**Issue by cliffyq** [Azure/Azure-Functions#405]
This is related to #389, a function app may be unresponsive for some reason and won't be triggered by new events unless we manually restart it in the portal, can we do regular health check on the function apps and try restart when they become unresponsive?

**Comment by christopheranderson** [comment]
So to clarify, this is a feature request to be able to define some kind of custom health check and then take some action like restarting the Function App? Have you considered using something like Azure Automation to do that? 

The other suggestion is to hook up App Insights and create an alert for when executions drop below a given threshold.

**Comment by christopheranderson** [comment]
Ping if we need to open this again
