### ISSUE TITLE
Add ability to enable CORS for Visual Studio debugging

### ISSUE THREAD

**Issue by briandunnington** [Azure/Azure-Functions#406]
I am using the Azure Functions Visual Studio tooling with Visual Studio 2017 Preview 3. When I launch the debugger, the runtime host launches in a shell window and I can make requests (ex: via Postman) to debug my functions. 

Sometimes though I need to debug calls from a browser. Since the browser has cross-domain restrictions, it issues a CORS OPTIONS request before making the actual request. However, the CLI runtime just returns a NotFound response.

I did read that you could launch the host manually with:
func host start --cors *

But I cannot find a way to set those arguments within the Visual Studio tooling.

**Comment by lindydonna** [comment]
You can do this in Project Properties -> Debug:

![image](https://user-images.githubusercontent.com/4260261/28637584-ea2aef2c-71f6-11e7-8957-f6c097cf6653.png)

**Comment by gagant** [comment]
Thanks, @lindydonna! Spent 1 hour going here and there for this setting!
