### ISSUE TITLE
Ensure cross-linking to App Service articles

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#41]
There are various App Service features that work similarly in Azure Functions, should make a resources page and link out to them.

**Comment by ggailey777** [comment]
+1 on cross-linking. Due to other asks,  we probably also need an App Service platform topic for Functions. We also have [this issue](https://github.com/Microsoft/azure-docs/pull/212) that should go in that topic rather than in the main Overview topic (as suggested by Matt)

**Comment by ggailey777** [comment]
Here's the info that @MattTatoczenko wanted included in the Overview topic:
>[!NOTE] Azure Functions are built on top of Azure App Services, so they have a limitation of only being able to listen on ports 80 and 443 for requests. See [Azure Web App sandbox network endpoint listening](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#network-endpoint-listening).

**Comment by SyntaxC4** [comment]
Tracked in Content Plan
