### ISSUE TITLE
Obey WEBJOBS_STOPPED or a similar environment variable

### ISSUE THREAD

**Issue by johndowns** [Azure/Azure-Functions#411]
I am making extensive use of the new (in preview) deployment slots feature for functions. My functions include both timer-triggered and queue-triggered functions. I want to ensure that only the production versions of my functions are executed. The staging slots are there only for deployment purposes, and occasionally for manually triggering functions when I need to check the logic before swapping them into the production slot.

I have tested using the `WEBJOBS_STOPPED` app setting (which disables webjobs from running on a standard App Service), but even with this flag set to `1`, my function continues to execute.

I know that I can use the `disabled` attribute in the function.json file to disable a specific function, but this is not very deployment slot-friendly - I would need to swap the slots and then programmatically disable/enable each function one by one.

It would be much simpler if I could use the `WEBJOBS_STOPPED` setting. I can then also set this to be a slot setting, so that my staging slot has this flag set to `1` while my production slot does not.

**Comment by johndowns** [comment]
I should note that as a workaround, I have set slot-specific app settings for the `AzureWebJobsStorage` and `AzureWebJobsDashboard` to point to an invalid storage account. This prevents queue-triggered functions from running, but I get lots of exceptions logged - and it also doesn't help with timer-triggered functions.

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#1729
