### ISSUE TITLE
Installing functions tooling for Visual Studio Pro 2017 (win 7) fails

### ISSUE THREAD

**Issue by rmacfadyen** [Azure/Azure-Functions#412]
I tried to install the tooling from https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio but it fails with the error "the extension cannot be installed to this product due to prerequisites that cannot be resolved".

I do have the web and azure workloads installed.

It would be helpful if there was some way of identify which prerequisite cannot be resolved.

I pulled the .vsix file apart and the extension.vsixmanifest file contains the following:

> &lt;InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0]" /&gt;

Which makes me suspicious that the .vsix might only be for the community edition of visual studio? 

Thanks!

**Comment by lindydonna** [comment]
You have to use the Visual Studio 15.3 preview. See Prerequisites in the documentation: https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#prerequisites

**Comment by rmacfadyen** [comment]
Is there a plan/timeline to support tooling in the released VS2017?

**Comment by lindydonna** [comment]
@rmacfadyen Yes, expect an update in the next month or so.
