### ISSUE TITLE
SQL Connection pool clarification (or overall shared static resources)

### ISSUE THREAD

**Issue by mnns** [Azure/Azure-Functions#415]
How does it work? is connection pool feasible on Functions? How about memory sharing (other types of static resources)? It is not clear in the documentation. Thanks

**Comment by christopheranderson** [comment]
If you create a connection pool singleton (either via a static variable or a factory model), then it can be shared by all invocations of that Function on a given machine. We'll scale out to potentially hundreds of machines. We don't special case SQL Connection pool - this is just generically how we treat static objects.
