### ISSUE TITLE
Document that TimerTrigger uses INameResolver

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#417]
_From @phatcher on June 1, 2017 16:16_

Should be some documentation that TimerTrigger can use a variable for the schedule definition which is passed to the INameResolver e.g.

       public async Task Schedule([TimerTrigger("%schedule1%")] TimerInfo timer)
        {
            await scheduler.Schedule();
        }

Was about to request the feature and found out it just works :-)

_Copied from original issue: Azure/azure-webjobs-sdk-extensions#232_

**Comment by mattchenderson** [comment]
Closing, as this is present in the docs now.
