### ISSUE TITLE
Is there any documentation on the limits/quotas for Azure Functions?

### ISSUE THREAD

**Issue by apengwin** [Azure/Azure-Functions#419]
I'm currently benchmarking an application and testing how many concurrent function invocations I can run at once. Once I try to run more than 20 concurrently, I get the following error.

```
    "exception": "[Error 5] Access is denied", 
    "exception_traceback": "Traceback (most recent call last):\n  File \"D:\\home\\site\\wwwroot\\filesys\\run.py\", line 170, in generic_handler\n    stdout=subprocess.PIPE)\n  File \"D:\\Repos\\azure-python-siteextensions\\source_packages\\python2.2.7.12\\tools\\Lib\\subprocess.py\", line 711, in __init__\n  File \"D:\\Repos\\azure-python-siteextensions\\source_packages\\python2.2.7.12\\tools\\Lib\\subprocess.py\", line 959, in _execute_child\nWindowsError: [Error 5] Access is denied\n", 
    "exception_args": [
        5, 
        "Access is denied"
    ], 
```

What could this mean? Are there any published limits/quotas for Azure functions?

**Comment by christopheranderson** [comment]
What are you trying to do here? Are you attempting to create processes or something? That seems like part of a stack trace.

You might be hitting a sandbox limit (which isn't the most obvious set of docs in the world - @SyntaxC4 might have some ideas to improve that). https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#numerical-sandbox-limits

You can definitely run more than 20 Functions concurrently, though.

**Comment by apengwin** [comment]
@christopheranderson I found the full stacktrace later, and it does look like this is an error with forking too many processes in a sandbox. 

Each function that I'm running is trying to fork a new process to run an executable. This works fine with small numbers of function invocations (~10-14), b I started getting problems with spawning processes at higher numbers.

**Comment by davidebbo** [comment]
Is your Function using Python? Please note that the current Python support is experimental, and is known to have limitations. Specifically, every function execution launches an instance of python.exe, which is inefficient. It works well enough under light load, but when hit to heavily as is the case here, it results in just too many parallel process launches, and things start to break down.

We are hoping to have real Python support in the future, though we don’t have a clear ETA.

**Comment by christopheranderson** [comment]
Yeah. That's a sticky problem because of how we manage concurrent executions and if you're not consuming tons of resources, you'll end up on a single instance - we're not looking at process counts, though, which might be considered a miss. You can try setting the batch size for queues to something lower. Be sure you keep the python function blocking until the process is done otherwise it'll degenerate. 

host.json queue settings: https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json 

As David suggested, you can try using C#, Node.js, or PowerShell which won't spin up a new process for each invocation which will give you more available processes.

**Comment by apengwin** [comment]
@christopheranderson gotcha. Is the reasoning behind decreasing batch size to decrease the number of functions that are being processed, to avoid hitting limits?

**Comment by christopheranderson** [comment]
Yep, less executions per instance. 

The biggest improvement would be moving off of Python for this example, though. Python is definitely in a non-production use case state until it moves onto the new language model that is rolling out soon.

**Comment by apengwin** [comment]
@christopheranderson  But if the limit I'm hitting _isn't_ the process limit, would I still be hitting similar resource limits with C# or node?

**Comment by christopheranderson** [comment]
If it isn't the process limit, maybe, but by removing Python from the equation, it makes it easier for us to debug. Python is near broken in many case, I'm afraid to say. If you try from those languages and give us an invocation id/timestamp, we can do some really rich debugging. For Python, we're not making any investments until this new language platform that's in progress comes around and we'll be doing a rewrite, so we're not likely to fix any Python bugs.

**Comment by apengwin** [comment]
@christopheranderson  @davidebbo I wrote a quick C# HTTP trigger function that tries to fork a child process and waits for it to sleep 20 seconds, before logging the mac address and returning. 
It seems that all of my threads/functions are running on the same machine, and as a result I can't scale past 30 concurrent functions, due to the process limit. Is there any way to achieve better scalability?

**Comment by davidebbo** [comment]
@apengwin take a look at https://github.com/Azure/azure-webjobs-sdk-script/wiki/Http-Functions#throttling. `maxOutstandingRequests` / `maxConcurrentRequests` gives you some amount of control over this, and should result in more scaling out behavior.

**Comment by apengwin** [comment]
Thanks @davidebbo. It seems that this solution is to, in effect, queue HTTP requests so that the system isn't overloaded. Is there a way to have the queued jobs invocations scale out to more machines, so that there isn't any latency?

**Comment by davidebbo** [comment]
Actually, it's not super clear in that doc, but this will in fact cause scale out if an instance starts returning 429s.

**Comment by mattchenderson** [comment]
Closing old issue for which an answer has been provided.
