### ISSUE TITLE
Plain exe or dll as a function

### ISSUE THREAD

**Issue by aL3891** [Azure/Azure-Functions#42]
Hello!

I'm fairly new to azure functions but as far as I understand it's not possible to upload a exe file and run that as a function, is that something that is planned? I really do prefer not to publish plain source code and would prefer to have deployment go though a more traditional build > package > test > deploy cycle.

I've previously used webjobs for this however they don't really feel like first class citizens in azure and have a few other issues such as possibility to be deleted by accident by a web deploy to the same site, no restart functionality, some times shutting down and so on. it feel like azure functions would be able to fill this gap, if only you could use it with precompiled code.

Is this something you have any plans for?

**Comment by asw** [comment]
This is possible if we use an HttpTrigger with Batch or C#, but neither option is very performant at the moment (and I'd love to get some feedback around this):

batch:

    echo OFF
    example.exe > %res%


C#:

    public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
    {
        Process process = new Process();
        process.StartInfo.FileName = @"D:\home\site\wwwroot\HttpTriggerCSharp1\example.exe";
        process.StartInfo.Arguments = "";
        process.StartInfo.UseShellExecute = false;
        process.StartInfo.RedirectStandardOutput = true;
        process.StartInfo.RedirectStandardError = true;
        process.Start();
        string output = process.StandardOutput.ReadToEnd();
        string err = process.StandardError.ReadToEnd();
        process.WaitForExit();
        return req.CreateResponse(HttpStatusCode.OK, output);
    }

**Comment by lindydonna** [comment]
Good news, this work is already in progress! Assigning to @fabiocav

**Comment by asw** [comment]
Excellent! I am looking forward to testing this as it is a very valuable workflow for us.

**Comment by aL3891** [comment]
Awesome! would love to see this, we have tons of webjobs that are clunky to manage compared to functions

**Comment by damienpontifex** [comment]
Reading the wiki on [Precompiled functions](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions) is this now available?

**Comment by fabiocav** [comment]
Yes, it is :)

I'll close this issue as completed to make sure others are aware.

**Comment by asw** [comment]
@fabiocav Great work on this! Does this provide a solution for the binary .exe use case I'd mentioned? I'd want to be able to compile an executable in any language (I am thinking of golang in particular) and invoke it efficiently using Functions.

**Comment by fabiocav** [comment]
@asw this works for .NET assemblies. For arbitrary executables, you'd need to invoke that from within your function at the moment.

**Comment by aL3891** [comment]
Looks great! thanks a lot for this :)

**Comment by lindydonna** [comment]
@Dafnafrank Could you open a new issue or forum post with the exact code you're using?  Post here: https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions
