### ISSUE TITLE
[Question] Getting Azure Function Tooling Outdated popup warnings

### ISSUE THREAD

**Issue by TheeJamesLee** [Azure/Azure-Functions#421]
Visual Studio Preview 15.3  Using the installed Azure Tools via the external visx link method.  - currently tools version 0.2 shown in my installed extensions.

I've just started having pop ups saying that Azure Functions Tooling is outdated and I need to update.

Is that talking about the .visx package here https://blogs.msdn.microsoft.com/webdev/2017/05/10/azure-function-tools-for-visual-studio-2017/

Want to check before I uninstall the extension and reinstall via that link.

Thanks,

**Comment by lindydonna** [comment]
You can ignore the popup: it's is a bug which we've fixed. We've just pushed out a new VSIX that removes the spurious warning.
