### ISSUE TITLE
Unable to find certain names in Named Entity Recognition

### ISSUE THREAD

**Issue by kvaibhav2009** [Azure/Azure-Functions#423]
Hi ,

We found out that for certain queries,named entity module was n't picking up the person name.This varied as follows:

1. transfer $400 to mike -       'Mike ' is recognized as person name.

2. transfer $100 to mike -       Due to the modification in amount , 'Mike ' doesn't seem to get recognised as person name.

3. transfer $300 to rahul -       'Rahul' is recognized as person name.

4. transfer $100 to rahul -       Due to the modification in amount , 'Rahul '  doesn't seem to get recognised as person name.

      

Please notify the resolution to this

**Comment by christopheranderson** [comment]
Could you please provide code samples/function.json settings/etc.? There isn't enough information for us to debug this, right now.

**Comment by kvaibhav2009** [comment]
This is a simple implementation to detect the named entity .We have created an experiment which implements named entity in Azure ML model

**Comment by fabiocav** [comment]
Closing this as there hasn't been activity and we're missing some context. Please let us know if you're still having problems and need assistance.
