### ISSUE TITLE
Can't run ServiceBusQueue function in VS2017

### ISSUE THREAD

**Issue by melzoghbi** [Azure/Azure-Functions#424]
Hi,

I am trying to run a function app that is triggered by a service bus queue binding. After creating the project in VS 2017 preview with latest function tooling. I get an error when i run the app:

![image](https://user-images.githubusercontent.com/11993393/28943560-3dca9bc4-786d-11e7-8d1a-f353ec81aea6.png)

So, When i try to run this command "func azure functionapp fetch-app-settings MYFUNAPPNAME" i get the below error:

![image](https://user-images.githubusercontent.com/11993393/28943527-1cf271c4-786d-11e7-8cae-8e78e7ce0719.png)

How to fix this? I am not able to run triggered based azure functions based on queues in VS2017.

Even i tried to copy the connection string for the storage account that hosts my function app as shown below:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=moapi11;AccountKey=KEY1;BlobEndpoint=https://moapi11.blob.core.windows.net/;QueueEndpoint=https://moapi11.queue.core.windows.net/;TableEndpoint=https://moapi11.table.core.windows.net/;FileEndpoint=https://moapi11.file.core.windows.net/;",
    "AzureWebJobsDashboard": "DefaultEndpointsProtocol=https;AccountName=moapi11;AccountKey=Key1;BlobEndpoint=https://moapi11.blob.core.windows.net/;QueueEndpoint=https://moapi11.queue.core.windows.net/;TableEndpoint=https://moapi11.table.core.windows.net/;FileEndpoint=https://moapi11.file.core.windows.net/;"
  },
  "Host": {
    "LocalHttpPort": 7071,
    "CORS": "*"
  }
}
```

Any ideas how to fix this?

**Comment by melzoghbi** [comment]
Any fix or how to resolve this @lindydonna @ahmelsayed ? Thanks.

**Comment by ahmelsayed** [comment]
what do you get if you run `func azure account list` is the current subscription the one where your function app is?
You can do `func azure account set <subId>` for the right sub id.

You can also do `func azure functionapp list` to see the function apps in the current sub.

**Comment by ahmelsayed** [comment]
closing in favor of https://github.com/Azure/azure-functions-cli/issues/199

**Comment by melzoghbi** [comment]
Thanks @ahmelsayed i will follow up with on on that thread!
