### ISSUE TITLE
Document the parameter format for blob containers

### ISSUE THREAD

**Issue by ggailey777** [Azure/Azure-Functions#426]
_From Matthew Charles:_
Here’s an example that pulls container/blob from an input:

	{
	  "bindings": [
		{
		  "type": "manualTrigger",
		  "direction": "in",
		  "name": "blobInfo"
		},
		{
		  "type": "blob",
		  "name": "inputBlob",
		  "path": "{containerName}/{blobName}",
		  "connection": "functionfun_STORAGE",
		  "direction": "in"
		}
	  ],
	  "disabled": false
	}

And here’s the code:

	using System;

	public class BlobInfo
	{
		public string ContainerName { get; set; }
		public string BlobName { get; set; }
	}

	public static void Run(BlobInfo blobInfo, string inputBlob, TraceWriter log)
	{
		log.Info($"BlobInfo: {blobInfo.ContainerName}/{blobInfo.BlobName}");
		log.Info($"Input blob: {inputBlob}");
	}

Not that for C# bindings, in order to be able to use input values in parameterized binding expressions, you have to map the input to a POCO.

**Comment by craigshoemaker** [comment]
@ggailey777 - yep. It looks like it's [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#input---c-script-example)
