### ISSUE TITLE
CFC: App Insights analytics queries for Functions

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#427]
# Call for content! - *Example queries*

We're looking to get a bunch of App Insights analytics queries put together for Functions. Leave a comment here with any samples/etc. you might have (either pasted directly or a link). I'll try to get them all in a wiki and we'll use some of them in our docs on docs.microsoft.com.

**Comment by nzthiago** [comment]
If you are also after custom metrics we used one on the [Customer Reviews sample](https://github.com/Azure-Samples/functions-customer-reviews). It gets added to a custom dashboard on the Azure Portal via ARM template, here's the line with the query:
https://github.com/Azure-Samples/functions-customer-reviews/blob/master/Provision/assets/template.json#L169

**Comment by christopheranderson** [comment]
## Percentiles on duration

### Code:
```js
let functionName = "queue-js";
requests
| where name == functionName
| summarize percentiles(duration, 50, 90, 99) by bin(timestamp, 5m) 
| render timechart 
```

### Example:
![image](https://user-images.githubusercontent.com/2252976/28982672-8c89c2c8-790b-11e7-9737-882074c565cc.png)

**Comment by christopheranderson** [comment]
@nzthiago - Does this formatting look right?

### Code:
```js
let truncationmaxrecords = 1000; 
customMetrics 
| project name, value 
| extend ModerationResult =
    iff(name == "ModerationResult" and value == 0, "Passed",
    iff(name == "ModerationResult" and value == 1, "Failed text",
    iff(name == "ModerationResult" and value == 2, "Failed image",
    iff(name == "ModerationResult" and value == 3, "Failed text and image", "Unknown"))))
| where ModerationResult != "Unknown"
| summarize count() by ModerationResult
| render columnchart
| project ModerationResult, count_
| order by ModerationResult desc
```

**Comment by twmurph** [comment]
Here are the links that I tweeted to you and the actual type query we are running to check if one of our on-prem services is still running.

http://www.geekswithblogs.net/tmurphy/archive/2017/02/16/logging-to-application-insights-in-azure-functions.aspx

http://www.geekswithblogs.net/tmurphy/archive/2017/08/04/query-application-insights-rest-api-to-create-custom-notifications.aspx

customEvents | where timestamp >= ago(20m) and name contains \"Service Started\" | count

**Comment by nzthiago** [comment]
@christopheranderson yes. This is what it looks like on the shared custom dashboard with piechart instead of columnchart:
<img width="392" alt="screen shot 2017-08-04 at 2 39 16 pm" src="https://user-images.githubusercontent.com/1563288/28988243-acf53e6c-7923-11e7-8c50-443411928ca5.png">

**Comment by nzthiago** [comment]
@mattchenderson was there a new doc created with all the queries examples?
