### ISSUE TITLE
Concurrent executions with asynchronous invocations

### ISSUE THREAD

**Issue by apengwin** [Azure/Azure-Functions#429]
I posted this in the [webjobs-sdk repo,](https://github.com/Azure/azure-webjobs-sdk-script/issues/1757) so sorry for the duplicate :(

I'm working with Azure functions. I've got a function triggered by a storage queue, where I put a large number of messages `(O(1000))` in bursts. I want them all to execute in parallel, but I'm currently throttled by the batch size of 32.
![screen shot 2017-08-07 at 1 41 23 pm](https://user-images.githubusercontent.com/7637700/29038575-270b9a62-7b76-11e7-9474-c245950354fc.png)

The HTTP trigger offers [unbounded paralleism](https://imgur.com/r/HighQualityGifs/cJlBUVL), but I want to be able to invoke functions asynchronously. That is, I want to be able to run some code that triggers a function and continue, without waiting for an HTTP response. Is there any way to achieve the best of both worlds? To be able to invoke a function asynchronously, and have an unbounded number run in parallel? 

Thanks!

**Comment by AmitBhatnagar24** [comment]
This seems like the perfect scenario for a Queue Trigger'd function. Have your HTTP Trigger process the request and place items on a queue and return. The real work is done processing each queue message.

**Comment by apengwin** [comment]
@AmitBhatnagar24  thanks for the response. Wouldn't I still get bottlenecked by the rate (32 concurrent) at which the queue is processed though?

**Comment by anthonychu** [comment]
The batch size of 32 is per function app instance. There is a scale controller that monitors metrics such as queue length that will scale your function app to more instances when it sees that work is backing up.

How this actually plays out will be dependent on the workload. If 1000 messages are dropped into a queue once in a while, they might finish processing all the messages before it has a chance to scale out. But if you continuously have a number of messages in the queue, the function app should scale out to accommodate that.

**Comment by mattchenderson** [comment]
Closing as answered - thanks @anthonychu!
