### ISSUE TITLE
Azure Functions as Notification Hubs Monitoring backend

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/Azure-Functions#43]
And with monitoring I mean support for the Event Hub compatible name/enpoint (as described in https://azure.microsoft.com/nl-nl/documentation/articles/iot-hub-operations-monitoring/)

This takes away the effort of putting StreamAnalytics/Eventhub between IoTHub and Azure Functions.

(note: This is not the same as issue: https://github.com/Azure/Azure-Functions/issues/31)

**Comment by lindydonna** [comment]
@sandervandevelde sorry for the late reponse. Can you elaborate more on the feature request?  Do you want a built-in support for IoT Hub triggers?
