### ISSUE TITLE
Document trigger retry behavior

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#434]
Timer, Http and EventHub do **not** retry if a function execution fails. We need to document this explicitly, because customers may expect similar behavior as queues.

**Comment by mattchenderson** [comment]
Covered here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#handling-binding-errors

**Comment by SeanFeldman** [comment]
Documentation has moved to https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-errors
