### ISSUE TITLE
[Visual Studio] Can't run local or debug - no function script files present

### ISSUE THREAD

**Issue by jstott** [Azure/Azure-Functions#435]
Installed latest Preview of Visual Studio 2017 15.3 (preview 7) and [Visual Studio 2017 Tools for Azure Functions extension](https://marketplace.visualstudio.com/items?itemName=AndrewBHall-MSFT.AzureFunctionToolsforVisualStudio2017).
Followed the example steps for a new Functions project:

1. Create a new project, choose File -> New Project, and the Azure Functions project type
2. Add a function to the application right click the project and choose “Add Item”, then choose the “Azure Function” item template - selected HttpTrigger.
3. New class was created.

Project compiles, but running executes func.exe & displays  ```HttpTriggerCSharp: No function script files present.``` as below:

```
Reading host configuration file 'C:\Users\demo\Source\repos\FunctionApp3\FunctionApp3\bin\Debug\net461\host.json'
Generating 0 job function(s)
Starting Host (HostId=demo-net461, Version=1.0.0.0, ProcessId=14060, Debug=False)
Listening on http://localhost:7071/
Hit CTRL-C to exit...
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
Job host started
The following 1 functions are in error:
HttpTriggerCSharp: No function script files present.

Http Function HttpTriggerCSharp: http://localhost:7071/api/HttpTriggerCSharp
```

The class generated by add Function HttpTrigger:
```csharp
namespace FunctionApp3
{
    public static class Function1
    {
        [FunctionName("HttpTriggerCSharp")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            // parse query parameter
            string name = req.GetQueryNameValuePairs()
                .FirstOrDefault(q => string.Compare(q.Key, "name", true) == 0)
                .Value;

            // Get request body
            dynamic data = await req.Content.ReadAsAsync<object>();

            // Set name to query string or body data
            name = name ?? data?.name;

            return name == null
                ? req.CreateResponse(HttpStatusCode.BadRequest, "Please pass a name on the query string or in the request body")
                : req.CreateResponse(HttpStatusCode.OK, "Hello " + name);
        }
    }
}
```

**Comment by ahmelsayed** [comment]
in you look in the output bin folder (where `func.exe` is running). You should see a folder named after your function `HttpTriggerCSharp` with a file `function.json` inside. Can you share the content of that file?

**Comment by ahmelsayed** [comment]
also if you look in your `csproj` make sure you have the latest build task `Microsoft.NET.Sdk.Functions`, latest version curretly is `alpha6`

**Comment by jstott** [comment]
All nuget packages are at the latest prerelease ver's - except Microsoft.Azure.WebJobs > 2.1.0-beta1 results in build issue with strong names.

Func.exe is 1.0.0-beta.9,

host.json: ```...FunctionApp3\FunctionApp3\bin\Debug\net461\host.json```
function.json: ```...FunctionApp3\FunctionApp3\bin\Debug\net461\HttpTriggerCSharp\function.json```

```
{
  "bindings": [
    {
      "type": "httpTrigger",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "function",
      "direction": "in",
      "name": "req"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\FunctionApp3.dll",
  "entryPoint": "FunctionApp3.Function1.Run"
}
```
![image](https://user-images.githubusercontent.com/1050436/29148459-8220ff3e-7d3b-11e7-8287-ea807e16b83e.png)

**Comment by ahmelsayed** [comment]
that is a very old version of func.exe. try deleting everything in this folder `C:\Users\<user>\AppData\Local\Azure.Functions.Cli` and restarting all instances of VS. Current build of func.exe is `1.0.0-beta.100`

**Comment by jstott** [comment]
Bingo - that fixed things right up!  

Thank you @ahmelsayed - and may I add this tooling looks outstanding - wow!
