### ISSUE TITLE
Url for deployment slot is cutting name.

### ISSUE THREAD

**Issue by janusznowak** [Azure/Azure-Functions#436]
The slot name 'the-name-of-the-slot-will-be-cut-in-url-of-deployment-slot'

Will be cut off in Url for deployment slot .

![image](https://user-images.githubusercontent.com/5168275/29162812-cb9d229e-7dba-11e7-8458-003fa165999e.png)

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-functions-ux#1678
