### ISSUE TITLE
 Newtonsoft.Json version 10+: Issue with returning JArray from Azure Functions HttpTrigger

### ISSUE THREAD

**Issue by alrod** [Azure/Azure-Functions#437]
I'm trying to return JArray object from Azure Function of HttpTrigger type:JArray a = JArray.Parse("[{\"reportId\": \"1111\",\"reportName\": \"AAAA\"}]"); return req.CreateResponse(HttpStatusCode.OK, a); However, for some reason, the response body returned as:[{"reportId":[],"reportName":[]}]

https://stackoverflow.com/questions/45603510/issue-with-returning-jarray-from-azure-functions-httptrigger

**Comment by lindydonna** [comment]
This is because they are using a later version of Newtonsoft than what we support. I replied on SO.
