### ISSUE TITLE
Third-Party Integration with SendGrid

### ISSUE THREAD

**Issue by wesmc7777** [Azure/Azure-Functions#44]
Add doc support for SendGrid bindings

**Comment by wesmc7777** [comment]
@SyntaxC4  Cory I added the issue to track doc support for SendGrid

**Comment by wesmc7777** [comment]
According Mathew Charles updates to support SendGrid v3 APIs are still in progress.  We have a sample here (https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample/SendGrid) but I can't test and document it unless I can get access to a test environment that supports it.  I'll check on doing that.

**Comment by wesmc7777** [comment]
Customer feedback for Sendgrid binding from Donna...

Wes,
 
It looks like a customer ran into an issue related to the SendGrid binding; this might be a good thing to document. The GitHub issue is here: https://github.com/Azure/azure-webjobs-sdk-script/issues/883

**Comment by SyntaxC4** [comment]
Here is the changeset from the latest update of the extension.. https://github.com/Azure/azure-webjobs-sdk-extensions/pull/152

**Comment by mathewc** [comment]
Another customer asking questions: https://stackoverflow.com/questions/41521465/azurefunctions-binding-to-sendgrid
