### ISSUE TITLE
Adding service bus output to http triggered function throws in runtime

### ISSUE THREAD

**Issue by fcasserfelt** [Azure/Azure-Functions#446]
I’m using Visual studio with Sdk.Functions v 1.0.2

When I add an Service bus output to a http triggered function I get the following error when I run:

Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'eventOut' to type ICollector`1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

This is my signature:

[FunctionName("Function1")]
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, [ServiceBus("myBus")] ICollector<string> eventOut, TraceWriter log)

If I’ll add a second Service Bus Topic triggered function the error disappears.

Am I doing something wrong?

**Comment by ChRonX13** [comment]
I'm also getting the same issue based on the Sdk.Functions v1.0.2. Upon opening a slightly older existing Function that had a working ServiceBus output binding, we have found this no longer works locally with the current tooling set.

**Comment by NicolasHumann** [comment]
Same here, I cant add Servicebus for output.. any workaround ?

**Comment by ChRonX13** [comment]
Looks like its been fixed on the  Azure side (ie if you publish to a real instance), however doesn't look like its working on the tooling side yet, see here: https://github.com/Azure/azure-functions-vs-build-sdk/issues/97#issuecomment-324195531

**Comment by mattchenderson** [comment]
Closing, as the referenced Azure/azure-functions-vs-build-sdk issue is resolved.
