### ISSUE TITLE
1.0 release depends on old version of Newtonsoft causing Nuget hell

### ISSUE THREAD

**Issue by Workshop2** [Azure/Azure-Functions#447]
Please upgrade your Newtonsoft dependencies. It currently requires exactly version 9.0.1 and we have other nuget packages requiring >= 10.0

This is stopping us from being able to upgrade to newer versions.

**Comment by lindydonna** [comment]
Yes, this is a general problem with all built-in assemblies. It will be solved when we move to an out-of-proc model for language workers. Currently, we load your code in the same App Domain as ours (and pass types back and forth) so the assemblies need to unify.

Closing this issue in favor of https://github.com/Azure/azure-webjobs-sdk-script/issues/1319

**Comment by Workshop2** [comment]
@lindydonna any idea when this would be addressed?

**Comment by lindydonna** [comment]
@Workshop2 We should have a preview available within the next 6 months (if not sooner).
