### ISSUE TITLE
EventHubTrigger not firing when executed via VS 2017

### ISSUE THREAD

**Issue by MattHoneycutt** [Azure/Azure-Functions#448]
Like the title says, I have an Azure Functions project in VS 2017, and that project contains a single function with an EventHubTrigger.  When I debug the project locally, there are no errors, but it never seems to actually fire the function.  The last line of output from func.exe is "Job host started."  

Here's the function:

```cs
    public static class ColdStorage
    {
        [FunctionName("ColdStorage")]
        public static void Run([EventHubTrigger("{real-hub-name}", Connection = "EventHub", ConsumerGroup = "{real-consumer-group}")]string myEventHubMessage, TraceWriter log)
        {
            log.Info($"C# Event Hub trigger function processed a message: {myEventHubMessage}");
        }
    }
```

And here's the local.settings.json:

```js
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "{real-connection-string}",
    "AzureWebJobsDashboard": "{real-connection-string}",
    "EventHub": "Endpoint=sb://{real-name}.servicebus.windows.net/;SharedAccessKeyName={snip};SharedAccessKey={snip};EntityPath={snip}"
  }
}
```

What am I doing wrong?

**Comment by MattHoneycutt** [comment]
The issue was 100% my fault: I had a typo in the ConsumerGroup property.  Once I fixed that, the function ran fine locally.

**Comment by lindydonna** [comment]
@MattHoneycutt thanks for following up.
