### ISSUE TITLE
Output bindings not being generated from attributes

### ISSUE THREAD

**Issue by ScottLeWarne** [Azure/Azure-Functions#450]
Hi, I have some prior experience putting a code driven solution in place with Functions from about a year ago and under VS 2015 so have somewhat limited experience with the function.json file and setting up bindings manually.

For a new project I've gotten VS 2017 and the new Azure Functions tooling which auto-generates the function.json file based on attributes used.  For some reason I cannot get any output bindings to generate in the json file.  Input bindings are there, but no output bindings.  I am not receiving any errors, just no bindings.

I was seeing it first with a function that uses an HttpTrigger for input and writes to a ServiceBus queue for output, no output bindings.  I also tried with a regular message queue attribute and no output bindings.  Here is the signature on that one:

`[FunctionName("Listener")]
        public static HttpResponseMessage Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, 
            [Queue("test")]out string queueItem,
            TraceWriter log)`

I then also tried adding a new 'Image resizer' function from the Add New list, which has a BlobTrigger and two Blob output params, and for that one it also is not including the output binding in the generated function.json.  HEre is that one.

`[FunctionName("test")]
        public static void Run(
            [BlobTrigger("sample-images/{name}", Connection = "")]Stream image,
            [Blob("sample-images-sm/{name}", FileAccess.Write, Connection = "")]Stream imageSmall,
            [Blob("sample-images-md/{name}", FileAccess.Write, Connection = "")]Stream imageMedium)  // output blobs`

I feel like I must be missing something here, I've seen several issues posted about _incorrect_ output bindings being generated, but nobody is talking about the lack of them.  I have the latest packages for Microsoft.Net.Sdk.Functions as well as Microsoft.Azure.WebJobs.ServiceBus.

Any ideas?

**Comment by fabiocav** [comment]
This is by design. You'll also notice that a new property indicating the configuration source is present. That eliminates the need for that metadata to be generated and triggers functionality that allows the runtime to load the bindings straight from the attributes you've applied. Trigger bindings are generated to ensure that information is available to infrastructure components.
