### ISSUE TITLE
[AppInsights] RoleInstance=WEBSITE_INSTANCE_ID causes uncontrollable number of nodes in the Enterprise plan

### ISSUE THREAD

**Issue by ebashmakov** [Azure/Azure-Functions#453]
`WEBSITE_INSTANCE_ID` is set as `RoleInstance` that could grow the number of nodes (Application Insights Enterprise) uncontrollably when your Function App is in the Dynamic mode.

As far as I know, Azure Functions team are going to make changes in the next release. Function app name will be set as `RoleInstance` (1 node per app) which makes perfect sense.

But for now I think it should be mentioned in [the doc](https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview)) so nobody will get unexpectedly high bills.

_Note: this issue was created after working with Azure Support team_

**Comment by ebashmakov** [comment]
I've created the example that partially solves the issue - https://github.com/ebashmakov/AzureApplicationInsightsNodesIssue/blob/master/AzureApplicationInsightsNodesIssue/Runner.cs#L31. We actually need to set up the `NodeName` (but better do both `RoleInstance` and `NodeName) because of this condition https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L479-L482

The issue is not totally related to Azure Functions but still it's really dangerous to use Application Insights with Azure Functions since you could lose a lot of money.

**Comment by ebashmakov** [comment]
Also extra nodes could be generated by the Performance counters traces - https://social.msdn.microsoft.com/Forums/en-US/4568d1a1-47f7-485e-8447-622429868452/ai-performance-counter-is-not-available-in-the-web-app-supported-list

**Comment by alexkarcher-msft** [comment]
This has been resolved with the integrated App Insights SDK that now ships with Functions.
