### ISSUE TITLE
Adding new function modifies Microsoft.NET.Sdk.Functions reference to old version

### ISSUE THREAD

**Issue by frli** [Azure/Azure-Functions#456]
Adding a new function to an existing project modifies the existing nuget Microsoft.NET.Sdk.Functions version to 1.0.0. 

**Repro steps**
1. Visual Studio 2017 update 3 (15.3.2)
2. Add new item on existing project with nuget reference Microsoft.NET.Sdk.Functions 1.0.2
3. Select Azure Function (I tried several trigger types)
4. Note the Microsoft.NET.Sdk.Functions version revert to 1.0.0
5. Bonus step if you have CI configured: commit & push -> deployment error

**Comment by sharpcoder28** [comment]
+1
I was wonder why the heck this was happening and then I remembered this issue
