### ISSUE TITLE
Blob input not generating in function.json

### ISSUE THREAD

**Issue by ADringer** [Azure/Azure-Functions#457]
Hi,

I have a function defined as:

`[FunctionName("CsvToJson")]   `
        `public static HttpResponseMessage Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "HttpTriggerCSharp/name/{name}")]HttpRequestMessage req, string name, TraceWriter log,
            [Blob("employees/{name}", Connection = "AzureWebJobsStorage")] Stream myBlob)
        {}`

So it's a HTTP trigger with a blob input (I believe that's possible?). But the generated `function.json' only mentions the HTTP trigger:

`"bindings": [
    {
      "type": "httpTrigger",
      "route": "HttpTriggerCSharp/name/{name}",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "function",
      "name": "req"
    }
  ]`

I've updated the `Microsoft.NET..Sdk.Functions` package to 1.0.2 but the `function.json` still says:

 ` "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0"`

Wasn't sure if that was the possible issue or just a redherring?

Thanks

**Comment by ahmelsayed** [comment]
That's is expected (https://github.com/Azure/azure-functions-vs-build-sdk/commit/3098dbdfc7a780d08f2a90c436d8ad0adf380686). Only the triggers are be serialized to json, other attributes are loaded as is from the assembly. you can see another property saying `"configurationSource": "attributes"` it can also be `"config"` though you'll have to put the settings there yourself. the 2017 tooling does `"configurationSource": "attributes"` by default.
