### ISSUE TITLE
Dotnetcore2.0 support?

### ISSUE THREAD

**Issue by digitaldias** [Azure/Azure-Functions#458]
I'm having a hard time updating my functions project to target dotnetcore2.0. 

There is a dependency, deep down in Microsoft.NETCore.App on System.Runtime v4.2 that seems to be unavailable to me (at least, that's how far I've come). 

Any plans to fix this in the near future?

**Comment by mamaso** [comment]
Hey @digitaldias, we know that for the current runtime we're unable to support .net standard 2.0 class libraries, follow along here: https://github.com/Azure/azure-webjobs-sdk-script/issues/1792

It's a high priority work item so hopefully we'll see a fix in the next couple weeks
