### ISSUE TITLE
HTTP Trigger Issue:

### ISSUE THREAD

**Issue by ArunSahu1992** [Azure/Azure-Functions#461]
I am sending 1000 Request asynchronously to API with timeout to each request is 10 seconds.
But the trigger execute only 400 - 500 requests and ignoring rest of all.

My questions is “Is Http Trigger execute all request in parallel or sequentially or there is any limit for parallel threads in Http Trigger”.

**Comment by mamaso** [comment]
Here's some info on Http Functions and configurable throttling behavior: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Http-Functions#throttling

**Comment by WmBlankenship** [comment]
It seems like throttling as a solution is saying 'send less,' but what about an application that needs to scale? Are there plans to address this limitation? We could certainly send less data to the Azure Functions, but that doesn't really address our problem. Sending less isn't an answer to something that is essentially supposed to scale without limit.
