### ISSUE TITLE
Azure functions unit testing with mocking SQL Server

### ISSUE THREAD

**Issue by bwwilliam** [Azure/Azure-Functions#462]
Can any one please provide some guidance on how I can write unit test test against the function app that has a SQL server backend? 

I am simply connecting to SQL Server DB using sql server command. 
I do not have any DAL or repository layer
Is there a way to mock the SQL Server context so that my function app does not have to have a sql server backend for running unit test? 

Thanks.

**Comment by mamaso** [comment]
Take a look at https://stackoverflow.com/a/34944777/5915331

I'd suggest encapsulating your sql logic within a wrapper class that you can mock.
