### ISSUE TITLE
No logs are displayed in Azure Portal

### ISSUE THREAD

**Issue by sergsalo** [Azure/Azure-Functions#466]
Usually one can see Logs under "Logs" tab in Azure Portal when opening an individual function. I noticed couple days ago that I can no longer see logs. I just created new Azure Function and can see no logs.

**Comment by ahmelsayed** [comment]
what do you see? are you seeing any errors? can you share your app name either directly or [indirectly](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)

**Comment by sergsalo** [comment]
I created test one: "testlogs3". I see no errors and no log messages in the "Logs" area:

![image](https://user-images.githubusercontent.com/242369/29886011-88e4bbac-8d6d-11e7-914b-910422f0af92.png)

**Comment by sergsalo** [comment]
It seems like I cannot attach to streaming logs for the app

**Comment by ahmelsayed** [comment]
do you have few different tabs open for the same function app by any chance? a browser would limit these streaming connections to 4 per host.

**Comment by sergsalo** [comment]
I don't have any other tabs opened. It seems like it connects after like 30 minutes if I leave the window opened.

**Comment by ahmelsayed** [comment]
I don't really know what could be happening. Do you have fiddler or something like that open by any chance that would buffer the request? The request is a long running "http streaming" request that times out after 30 minutes. Tools like fiddler will buffer the whole request before letting it pass, so it does that to these requests.

**Comment by sergsalo** [comment]
hmm, no longer occurring...
