### ISSUE TITLE
Application Insights - Specify function name which threw the server expection alert

### ISSUE THREAD

**Issue by harshithkashyap** [Azure/Azure-Functions#467]
We've setup webhook alerts to send it to our slack channel when functions fail. When alerts are sent from AI using server exceptions metric, the webhook payload does not contain the same of the failed function. We can only know that one or more AF failed. It'd be useful to track this in the alert. 

I can see "my-function-name failures" in the metric options but we'll have to manually do this for each function and remember to setup alerts for newly added functions.

**Comment by brettsam** [comment]
@harshithkashyap -- the 'Operation name' of the exception contains the function name (if applicable -- sometimes exception happen outside of a function execution). In the App Insights portal UX, you can click 'See all properties' to see that:

![image](https://user-images.githubusercontent.com/1089915/29982651-7405a836-8f07-11e7-85df-6b1f490b02aa.png)

Similarly, you can query in Analytics and see the `operation_Name`

Are you not able to see this in your exceptions? If not, would you mind sharing some details so I can investigate?
