### ISSUE TITLE
SAS Token access for QueueTrigger

### ISSUE THREAD

**Issue by Scooletz** [Azure/Azure-Functions#468]
Hi.
I've seen https://github.com/Azure/Azure-Functions/issues/199 but it does not answer why SAS could not be provided for queue triggers.

Currently, `QueueTriggerAttributeBindingProvider` uses the attribute values only for creating the queue. It's not used for other purposes. It looks that: an account address, SAS token and queue name would be sufficient for creating the binder

https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Queues/Triggers/QueueTriggerAttributeBindingProvider.cs#L107-L116

**Comment by mamaso** [comment]
As far as I can tell, it would be sufficient for queues - however, this would not be the case for other storage bindings.  We haven't implemented a special case for queue as such.

If you'd like to see this, I'd suggest submitting a pull request, or file a new issue on the webjobs sdk repo.
