### ISSUE TITLE
Update existing documentation pages which are missing F# Code Samples

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#47]
Adding code samples for F# to existing documentation.

**Comment by SyntaxC4** [comment]
@cephalin Here is the topic for F#. We should be able to hand off some of this work to the F# team. If you could document any of the issues you were having on this it would be great!

**Comment by lindydonna** [comment]
@dsyme @sylvanc Some of our doc pages are missing F# code samples. @cephalin will add the items as he finds them to this issue.

**Comment by cephalin** [comment]
Mobile Apps binding, both input and output:
https://github.com/cephalin/azure-content-pr/blob/bindings/articles/azure-functions/functions-bindings-mobile-apps.md

**Comment by SyntaxC4** [comment]
F# is going to GA, so we should really make sure that we get some samples in here shortly.

**Comment by sylvanc** [comment]
Hi @SyntaxC4 , is there a list of pages that need code samples available?
