### ISSUE TITLE
Project reference

### ISSUE THREAD

**Issue by sharpcoder28** [Azure/Azure-Functions#471]
I'm having an issue with a project reference from a function to a project dll in the solution. Both are 4.6. Using the latest VS 2017. 2 pictures attached.

![function1](https://user-images.githubusercontent.com/5140239/29895660-f92e325a-8da7-11e7-8832-90236e99353d.PNG)
![function2](https://user-images.githubusercontent.com/5140239/29895661-f9376348-8da7-11e7-82d7-3a9030c08bbb.PNG)

**Comment by sharpcoder28** [comment]
Restarted Visual Studio and it's working....

**Comment by lindydonna** [comment]
Yes, you need to use the 1.0.2 version of https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions
