### ISSUE TITLE
Azure Function Time Trigger does not accept valid CRON expression.

### ISSUE THREAD

**Issue by danielok1993** [Azure/Azure-Functions#473]
I have encountered a weird issue while trying to create a schedule to run on first Sunday of every month: 0 0 0 1-7 * SUN#1. Azure Functions tell me that this construct is wrong.

The construct is actually correct as seen here: http://cronexpressiondescriptor.azurewebsites.net/, even the linked wiki page on the documentation page mentions that use of # is valid: " '#' is allowed for the day-of-week field, and must be followed by a number between one and five. ". Can someone explain why Azure Function does not allow the use of # or is there a different way of achieving this?

**Related information**

Documentation Page Wiki: https://en.wikipedia.org/wiki/Cron#CRON_expression

**Comment by ahmelsayed** [comment]
looks like NCronTab doesn't support `#1` syntax

**Comment by danielok1993** [comment]
@ahmelsayed is there a chance this will be fixed? It clearly looks like a bug. If it might help I found that [NCronTab Advanced](https://github.com/jcoutch/NCrontab-Advanced) supports use of # L W

**Comment by davidebbo** [comment]
I don't think we want to move to a different package, as that could cause breaking changes. The best bet would be to open a bug against ncrontab and ask for that support. Looking at https://github.com/atifaziz/NCrontab/issues, there isn't one yet.

**Comment by davidebbo** [comment]
Turns out it's easy to express. Use `0 0 0 1-7 * 0` to achieve this. e.g. with this expression, the next 10 occurrences are:

```
10/1/2017 12:00:00 AM
11/5/2017 12:00:00 AM
12/3/2017 12:00:00 AM
1/7/2018 12:00:00 AM
2/4/2018 12:00:00 AM
3/4/2018 12:00:00 AM
4/1/2018 12:00:00 AM
5/6/2018 12:00:00 AM
6/3/2018 12:00:00 AM
7/1/2018 12:00:00 AM
```

Which is the first Sunday of each month.
