### ISSUE TITLE
[Visual Studio] Publishing of Function App does not sync/cleanup unused functions, portal throws error

### ISSUE THREAD

**Issue by spboyer** [Azure/Azure-Functions#474]
### Scenario
* Create **FunctionA.cs**
* publish using *right-click publish* 
* Folder is created "FunctionA" with **function.json**
* Create **FunctionB.cs** and delete **FunctionA.cs**  
* publish using *right-click publish*
* Folder is created "FunctionB" with **function.json** & folder "FunctionA" is still there with the portal showing/listing "FunctionA" in left panel. Error is presented in upper right corner [Master Key not found] with a guid.

The solution is to delete the function through the portal UI and/or delete via Kudu.

Potential related issue #469 

cc:/ @lindydonna

**Comment by ahmelsayed** [comment]
/cc @vijayrkn 
I there is a switch for msdeploy to do that. I remember you saying it was removed from the UI for some reason, but you can still put it in some file somewhere

**Comment by vijayrkn** [comment]
You can manually update this property in the pubxml 
Location of the pubxml \Properties\PublishProfiles\<profile>.pubxml
MsBuild Property to Update
```
    <SkipExtraFilesOnServer>false</SkipExtraFilesOnServer>
```
Setting this to false will remove all the additional files in the destination.

In the next release, there will be settings UI that will allow to update these settings

**Comment by ColbyTresness** [comment]
I believe this is now fixed. Please reopen if necessary.
