### ISSUE TITLE
New Function button in Function App UX

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/Azure-Functions#475]
I'm a new hire PM on the functions team (if whomever reads this doesn't know me).

The other day I went into the portal and tried to make my first function. I saw the function app button on the left blade, clicked, and was brought to the Antares-demo function apps. I saw all the apps and tried to make a new one from the page, and got confused since I couldn't.

I think it makes more sense to have a "make a new function app" button here at the top of the page rather than making the user click "new" and then find function app again.

**Comment by ahmelsayed** [comment]
tracked by https://github.com/Azure/azure-functions-ux/issues/986
