### ISSUE TITLE
Release notes for Functions nuget package?

### ISSUE THREAD

**Issue by duckwaffle** [Azure/Azure-Functions#476]
Hi guys,

Maybe I've completely missed it, but there seems to have been quite a bit of activity on the Microsoft.NET.Sdk.Functions nuget package over the last couple of weeks, notably that its out of alpha and has even had some point releases.

Is there anywhere that discusses whats new in these versions? What currently is/isn't supported?

**Comment by ahmelsayed** [comment]
This is the repo https://github.com/Azure/azure-functions-vs-build-sdk  but I haven't been creating any release notes, that's true. You can see the history from commits or PRs, but I'll try to draft something for the latest release.
