### ISSUE TITLE
TypeScript definitions for TS-enabled functions

### ISSUE THREAD

**Issue by s-KaiNet** [Azure/Azure-Functions#483]
Hey guys, 
do you have plan to publish official definitions for TypeScript based functions?   
I found community-driven [here](https://github.com/christopheranderson/azure-functions-typescript), but it's a bit outdated and for sure it will be great to have official one.   
Thanks!

**Comment by ahmelsayed** [comment]
@christopheranderson is hardly a community member, but I do agree Chris should move it under /Azure org.

**Comment by s-KaiNet** [comment]
Ah.... I haven't noticed owner's profile 😃    

I've found some gaps in published definitions comparing to the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node) - `params` missing for Request, `isRaw` for Response. That's only something that I've found.   
Will be cool if you move it and update missing pieces ☺️

**Comment by graham-sportsmgmt** [comment]
As we move into the next phase of migrating our node.js Web App to Functions it's becoming clear that we'll need TypeScript to handle business logic safely.  Would love to see more docs on this.

Thanks!

**Comment by suprak** [comment]
+1

I see Azure Functions now support TypeScript as a "preview" language, but where are the TypeScript definitions?

**Comment by zabirauf** [comment]
+1

**Comment by spontoreau** [comment]
Any news?

Just publish a definition might be ok for everybody.

**Comment by jryu01** [comment]
Any updates?

**Comment by fabiocav** [comment]
+ @mhoeger 

Marie has been working on the type definitions and they will be up on NPM under @azure/functions soon.

The types definitions are maintained in the Node worker repository [here](https://github.com/Azure/azure-functions-nodejs-worker/tree/dev/types/public)

**Comment by janaagaard75** [comment]
Great to hear that we are getting official support. 👍  I will remove my pull request to DefinitelyTyped.

**Comment by mhoeger** [comment]
@janaagaard75 thanks for the community submissions! The initial release will be coming soon, everyone please feel free to open issues on nodejs-worker for suggestions on the [typings we expose](https://github.com/Azure/azure-functions-nodejs-worker/tree/dev/types/public)

**Comment by mhoeger** [comment]
Please check out our published typings :) 
https://www.npmjs.com/package/@azure/functions

Thanks for your patience all

**Comment by spontoreau** [comment]
@mhoeger thanks!
