### ISSUE TITLE
[Visual Studio] During Debugging, NuGet package assembly could not be found.

### ISSUE THREAD

**Issue by pottereric** [Azure/Azure-Functions#484]
Using the latest version of the Visual Studio and the Azure Function Tools, I created a solution. It included an Azure Function and a .Net Standard class library.  The class library has a NuGet reference to a NuGet package. The Azure Function has a reference to the class library. When I try to debug the Azure function, I get a runtime error that says "Could not load file or assembly" and it references the NuGet package.

**Comment by alexkarcher-msft** [comment]
This has been fixed in an update to our extension
