### ISSUE TITLE
Issue: We are not able to retrieve the runtime master key.

### ISSUE THREAD

**Issue by henning-krause** [Azure/Azure-Functions#487]
I'm publishing an Azure Function via an On-Prem TFS to Azure (into a staging slot).

This error occurs:
We are not able to retrieve the runtime master key. Please try again later.
Session Id: 4e3f548160994a9a80340f966cdd3c12

Timestamp: 2017-09-07T18:57:58.396Z

And indeed, when I look at the Function App Settings, all function keys are gone. I've already deleted and recreated the function, but it didn't help.

I can't even create a new key, it results in the same error.

**Comment by henning-krause** [comment]
I've created the app using a different name, and now it works....

**Comment by Kaimonos** [comment]
I encountered the same issue using VSTS. Thank you @henning-krause for pointing me in the right direction. Deleting the function-app did not resolve the, only renaming.
![fa-issue-release](https://user-images.githubusercontent.com/22004184/30251277-fb1d96d8-965c-11e7-9c23-874d556fc172.png)

**Comment by Kaimonos** [comment]
The renamed version now has the same problem. Only after removing the content under  site/wwwroot and data/functions/secrets, and deploying using Visual Studio 2017, it works again.

**Comment by Kaimonos** [comment]
![image](https://user-images.githubusercontent.com/22004184/30371266-59f3697a-987a-11e7-845b-d771e283b315.png)
Setting the webdeploy option seems to result in a reliable deployment.

**Comment by NickDarvey** [comment]
@Kaimonos' solution works in the case where you're doing a deployment which removes functions and run into this error. Thanks @Kaimonos!

**Comment by henning-krause** [comment]
The issue occurred again now:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: 01d1a2bd7f0c414ba71d02ff5e2accb3

Timestamp: 2017-11-13T11:10:52.417Z
