### ISSUE TITLE
[Visual Studio] Visual Studio crashes when attempting to Publish to Azure

### ISSUE THREAD

**Issue by justcla** [Azure/Azure-Functions#490]
User (Ben Edwards) raised the following issue on [Marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools#review-details):

> Publish function to azure.
>
> * The first time I opened the "Create New" dialog in the publish settings, Visual Studio crashed. The second time, it crashed while trying the select the correct account to use. Worked after that, but I believe only because it remembered I changed the account.

Applies to extension version: 15.0.30901.0

**Comment by justcla** [comment]
Brian, would you be able to help us debug this crashing issue by providing us with a relevant dump file and call stack?

Some instructions from Engineering:

1.	Provide the build of Visual Studio where you're encountering the issue.
2.	If you can still repro the crash issue, please Attach to Process the target VS which has the bug via another instance of VS. Then, check Common Language Runtime Exceptions under Exception Settings, uncheck the Enable Just My Code in Options -> Debugging -> General. If an exception hits that causes the Provisioning dialog to crash, pause the debugging instance of VS, then go to Debug -> Save Dump As… to get the dump file. 
3.	If anything shows up in the Call Stack window, paste it into a text file and send it over separately.

Please let us know if you have any questions.

Thanks!

**Comment by elexisvenator** [comment]
More context:
I have 2 accounts (emails) registered with visual studio. The primary one is my personal email which has MSDN/Visual Studio sub associated with it, the second one is my work account which has access to my organisations VSTS and Azure subscriptions.

Visual Studio 2017 15.3.3
WebJobs Tools v1.0.0 - 15.0.30901.0
Windows 10 Enterprise 15063

Everyone in my team had the same pattern of crashes as I did, but now that it works the crashes do not seem reproducible.
