### ISSUE TITLE
[Visual Studio] Cannot create a publish profile if subscription contains any app service plans

### ISSUE THREAD

**Issue by justcla** [Azure/Azure-Functions#491]
User (Ben Edwards) raised issue on [Marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools#review-details):

> Publish function to azure.
> 
> * Cannot create a publish profile for a new consumption-based function app if the subscription contains *any* app service plans. Have to create app in the portal and then click "select existing".

Applies to extension version: 15.0.30901.0

**Comment by elexisvenator** [comment]
To clarify, it does not appear to be possible to create a consumption plan at all using the current version of Webjobs Tools - App Service Plan is now a required field, and is prefilled with the first suitable app service plan in your subscription.

**Comment by alexkarcher-msft** [comment]
This has been fixed in a VS update
