### ISSUE TITLE
Deployment Slots Documentation Missing Steps to Slot Setting Checkbox

### ISSUE THREAD

**Issue by tohling** [Azure/Azure-Functions#493]
## Issue
The [documentation for deployment slots](https://blogs.msdn.microsoft.com/appserviceteam/2017/06/13/deployment-slots-preview-for-azure-functions/) show the following slot setting snapshot. 

![slotsetting](https://user-images.githubusercontent.com/14911331/30237994-ecd2d630-94f2-11e7-8681-522cbcc5f8ab.png)

The above UI with checkbox is only available in the **Web Apps Application Settings** page, and not the **Function Application Settings** page.  Customers trying out deployment slots are not able to follow the instructions in the documentation due to this gap.

## Suggested fix
Option 1. Documentation should be updated with instructions on how to navigate to the page, or
Option 2. **Functions Applications Settings** page should be fixed to match.

**Comment by DinoMiniutti** [comment]
I also can't see the checkbox in the **Function Application Settings**. Also, I can't find the **Web Apps Application Settings** page, so I can't find the right place to configure the setting.

**Comment by alexkarcher-msft** [comment]
The docs and portal UI have both been updated :)
