### ISSUE TITLE
Azure Functions Proxies broken

### ISSUE THREAD

**Issue by facadev** [Azure/Azure-Functions#494]
I set my proxy config with custom domain months ago and it's been working properly, until someone notified me today that my API wasn't working (404). I checked my portal and the config was untouched.

Anyone experiences the same issue here?

PS. I can still access my function via custom domain through unproxied endpoint, so I assume it's not a problem regarding domain settings, which I haven't changed recently.

**Comment by efleming18** [comment]
@facadev I could potentially be running into a similar issue. Are you deploying your Functions app via VSTS? I opened [a ticket](https://github.com/Azure/Azure-Functions/issues/543) describing that the proxies.json basically doesn't take when deployed out. I just discovered I can go into the advanced editor in the portal -> copy/paste my proxy entries in the same file -> rename them -> delete the initial entries -> save and it works!

**Comment by facadev** [comment]
@efleming18 I deploy my app via online portal. It seemed that some update to Azure Functions broke my app somehow. Up till now, my Azure Proxy still malfunctions. Worse still, when tweaking the config, sometimes the built-in route (/api/xxx) may even stop working together with the proxy URL. In this case, if I disable and then enable Azure Proxy, then the default route pattern will start to work again.

I cannot figure out what is going on behind the stage. But your solution is definitely worth a trial. 😃

**Comment by sadgit** [comment]
Just noticed the same issue although it didn't affect me until a few changes had gone through.

Tried editing the file on the server.
Changed are noted in the UI but the proxies just give a 404

Can't see how to check logs.

**Comment by sadgit** [comment]
OK looking in Kudu in **D:\home\LogFiles\Application\Proxies**

Successful load shows
10/6/2017 11:47:43 PM  Initializing from poxies.json... 
10/6/2017 11:48:26 PM  Initialization successful. 

Unsuccessful load shows
10/20/2017 3:00:46 PM  Initializing from poxies.json... 
<but no successful entry>

**Comment by sadgit** [comment]
Now looking at the non-production auto-swap slot

10/23/2017 4:39:34 PM  proxies.json changed 
10/23/2017 4:39:34 PM  reloading proxies.json 
10/23/2017 4:39:48 PM  Initialization successful. 
10/23/2017 4:39:48 PM  proxies.json changed 
10/23/2017 4:39:48 PM  reloading proxies.json 
10/23/2017 4:39:48 PM  Initialization successful. 
10/23/2017 4:39:48 PM  proxies.json changed 
10/23/2017 4:39:48 PM  reloading proxies.json 
10/23/2017 4:39:50 PM  Initialization successful. 

Also found duplicate log file on Auto-Swap with equivalent entries except first entry falls in previous second. i.e. 10/23/2017 **4:39:33** PM  proxies.json changed

Also no corresponding log file on production slot

**Comment by efleming18** [comment]
@sadgit In your first comment above, did you actually **delete** the entries that were displayed in the Advanced editor or just edit them? Just editing the existing entries wasn't enough for me. I had to completely delete the entries I had, put new ones in with different names, and save for the changes to take.

**Comment by efleming18** [comment]
@alexkarcher-msft I'm not sure who to tag about this one, and [this one I opened a couple weeks ago](https://github.com/Azure/Azure-Functions/issues/543), but I saw you posted about a breaking change to Proxies. Not sure if they are related?

**Comment by safihamid** [comment]
Please take a look here: https://github.com/Azure/app-service-announcements/issues/50

**Comment by sadgit** [comment]
@efleming18 - read the linked post and it doesn't apply

OK - I've edited the file and the proxies show in the UI but still get a 404 via postman etc.

When I call the function directly it works fine but changes to the proxies display in the portal but give a 404.

Basically by proxies are FUBAR

**Comment by safihamid** [comment]
Please make sure, your function app does not have a ROUTING_EXTENSION_VERSION app setting, and if it does, just delete it. It should fix your 404 issue.

**Comment by sadgit** [comment]
I tried that before and it didn't fix it - now things are getting worse

Each time I select a function in the portal I get - "Error - Function ($<function name>) Error: An item with the same key has already been added."

removing ROUTING_EXTENSION_VERSION didn't help - what does it do?

**Comment by sadgit** [comment]
OK So we're now at the point where the proxies have different names from the functions and the ROUTING_EXTENSION_VERSION is deleted. 

Still only one slot of my app works through the proxy - will try @efleming18 's manual edit of proxy file

**Comment by safihamid** [comment]
Are you able to share your proxies.json file?

**Comment by sadgit** [comment]
`{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "pr-01-dial-over-route": {
      "matchCondition": {
        "route": "/dial/{route}/{value}",
        "methods": [
          "GET"
        ]
      },
      "backendUri": "https://%api_base_url%/dialout?number={value}&route={route}&code=%api_host_key%"
    },
    "pr-01-dial": {
      "matchCondition": {
        "route": "/dial/{value}",
        "methods": [
          "GET"
        ]
      },
      "backendUri": "https://%api_base_url%/dialout?number={value}&route=desk&code=%api_host_key%"
    },
    "pr-01-register-listener": {
      "matchCondition": {
        "route": "/register/listener",
        "methods": [
          "POST"
        ]
      },
      "backendUri": "https://%api_base_url%/register-listener?code=%api_host_key%"
    },
    "pr-01-settings-admin": {
      "matchCondition": {
        "route": "/settings/{value}/{uid}",
        "methods": [
          "GET",
          "POST"
        ]
      },
      "backendUri": "https://%api_base_url%/settings-admin?type={value}&uid={uid}&code=%api_host_key%"
    },
    "pr-01-settings": {
      "matchCondition": {
        "route": "/settings/{value}",
        "methods": [
          "GET",
          "POST"
        ]
      },
      "backendUri": "https://%api_base_url%/settings?type={value}&code=%api_host_key%"
    },
    "pr-01-simulate": {
      "matchCondition": {
        "route": "/simulate/{value}",
        "methods": [
          "GET"
        ]
      },
      "backendUri": "https://%api_base_url%/simulate?number={value}&code=%api_host_key%"
    }
  }
}`

**Comment by safihamid** [comment]
oh one more thing, did you delete that app setting from the slot and your main function app?

**Comment by sadgit** [comment]
Yes

**Comment by sadgit** [comment]
Also 

FUNCTIONS_EXTENSION_VERSION | ~1 
WEBSITE_NODE_DEFAULT_VERSION | 6.5.0 
AzureWebJobsSecretStorageType | Blob

**Comment by safihamid** [comment]
So are you saying you deleted the app setting(ROUTING_EXTENSION_VERSION) from both your slot and the main app, restarted both and still get a 404 on main app but slot works fine?

**Comment by sadgit** [comment]
OK we had a secondary issue over slot-settings, %api_base_url% and %api_host_key%

Both env variables need SlotSetting=false

Now seems to work - so you are right it was  removing ROUTING_EXTENSION_VERSION + de-duplicating names

**Comment by sadgit** [comment]
@safihamid - How would we get warned of similar changes to this before it takes effect and can we opt-out of changes until we have tested our compliance?

When was this change deployed?

This became quite high-profile so we need to reassure management that Function Apps can be relied upon.

Any ideas how we can get reassurance on this from the Azure team.

Thanks for your help - Dave

**Comment by safihamid** [comment]
This was all because of some major architectural changes in Proxies which are still in 'Preview'. We have all the fixes which broke the scenarios in the pipeline and should be deployed within the next few days. We have all the test scenarios in place now and do not expect any braking changes specially that we get close to Proxy GA.

**Comment by alexkarcher-msft** [comment]
All new fixed code has been deployed.
