### ISSUE TITLE
Monitor Tab occasionally drops function invocations

### ISSUE THREAD

**Issue by mamaso** [Azure/Azure-Functions#496]
See ICM 46981250

System logs show that function invocations have been processed, but the Monitor tab fails to show invocations.

This may be an issue with dropping logs on the way to TableStorage.

![image](https://user-images.githubusercontent.com/9870694/30352769-c2c2308e-97d6-11e7-9870-cc7f4c0c0428.png)

![image](https://user-images.githubusercontent.com/9870694/30352783-dd85b7f6-97d6-11e7-93ad-be4272d8dcb5.png)

**Comment by alexkarcher-msft** [comment]
Hi @mamaso !

This has been fixed with application insights. Hopefully you'll use that for all your future Functions projects
