### ISSUE TITLE
Azure Functions - Time Trigger does not work

### ISSUE THREAD

**Issue by danielok1993** [Azure/Azure-Functions#497]
We are working on a new solution for our customers. We are using functions time trigger to send messages to a topic on a specific time. Every customer has their own function app with multiple functions. They all run on the same consumption plan. The problem is that sometimes the functions will not trigger, even after going to the function and forcefully triggering it, the next execution will also not trigger. We have tried to develop a mechanism that will check if functions are past due their execution and forcefully triggering them by obtaining admin token and then calling https://FUNCTIONAPPNAME.azurewebsites.net/admin/functions/FUNCTIONAME, it works in postman, but in C# HttpClient keeps returning error 500. We are now considering using some other solutions as we cannot afford not to trigger those functions.

**Comment by nzthiago** [comment]
If you browse to https://FUNCTIONAPPNAME.scm.azurewebsites.net/azurejobs/#/functions and look at the invocation logs, are there any failed ones with any exceptions?

**Comment by davidebbo** [comment]
For us to investigate, we'll need the app name (which you can report [indirectly](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)), and the UTC time of one sample missed timer invocation.
