### ISSUE TITLE
Update get started videos

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#5]

**Comment by lindydonna** [comment]
Possibly an item for Glenn if he has cycles

**Comment by ggailey777** [comment]
We probably need to look at all of the videos, since there were pre-GA. This is non-trivial work item and we should triage the existing videos, as maybe some are still "close enough."

**Comment by SyntaxC4** [comment]
@lindydonna - Can you let us know when it would be good to move forward on this. I'm assuming there will be some changes coming in the UI which will require us to redo all of the videos.

**Comment by ggailey777** [comment]
We no longer have any Getting Started videos in Docs. If we want these again in the future, we will need to find a more creative way to resource them (maybe with help from CDAs).
