### ISSUE TITLE
Code Sections aren't rendering properly in Queue Binding topic

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#50]
https://azure.microsoft.com/en-us/documentation/articles/functions-bindings-storage-queue/

There are two sections which aren't rendering properly:

* Trigger sample in Node.js
* Output sample in C#

**Comment by ggailey777** [comment]
It looks like this issue has been resolved: https://github.com/Microsoft/azure-docs/commits/master/articles/azure-functions/functions-bindings-storage-queue.md
