### ISSUE TITLE
[VisualStudio] Inconsistencies with functions created in Visual Studio vs the Azure Portal

### ISSUE THREAD

**Issue by codymullins** [Azure/Azure-Functions#500]
The development experience when moving from the Azure Portal to Visual Studio has some inconsistencies which make building out functions a little more difficult, especially when understanding how they work.

To start, see below the structure of two projects. The top project was created with the Azure portal and downloaded via clicking "Download app content". The second was created using the VS tooling and adding a single function.

![image](https://user-images.githubusercontent.com/1738479/30603398-55019f12-9d35-11e7-9bbb-887f92751f49.png)

The functions created in Azure are organized into folders, with name of the file `run.csx` and includes the `function.json` file. This lines up with the documentation I found online. The second project does not create this folder nor does it create the function configuration file. Additionally, the new file is created with a different naming convention and extension for the created function `Function1.cs`.

Now digging into the contents of the files. 

**Function downloaded from the Azure Portal:**
![image](https://user-images.githubusercontent.com/1738479/30603623-1fcc7960-9d36-11e7-9ecb-f50d44011287.png)

**Notes:**
- No namespace declaration
- No static class wrapper
- Function name matches the file name

**Function created with VS tooling:**
![image](https://user-images.githubusercontent.com/1738479/30603675-3e0ed4fe-9d36-11e7-9d66-c5c662cc5ee1.png)

**Notes:**
- Namespace declaration
- Wrapped in a static class
- Using statements are added from the web jobs hosting, unlike in the Azure function downloaded from the portal.

---

These all may be expected and there may be reasons for these discrepancies, but it has been very confusing trying to get some of these items running - especially when the documentation mostly refers to the Azure portal style of things. It would be nice for there to be more consistency between what is automatically scaffolded out in both the portal and the tooling. I've worked around this so far by doing most work in the portal, but that proves difficult since debugging has been quite painful.

What I would expect here is at least for the scaffolding out of the new functions to closer match what is created through the Azure portal, at least in terms of the folder created with the same naming convention and function configuration file.

**Comment by asavaritayal** [comment]
This is expected since the version supported in the portal is C# script while Visual Studio supports .Net class library.
