### ISSUE TITLE
Azure Service Bus queue based function doesn't trigger locally

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/Azure-Functions#502]
VS2017 15.3.5

**Function**

```c#
[FunctionName("AzureServiceBusTriggeredFunc")]
public static Task Run([ServiceBusTrigger("myqueue", AccessRights.Manage, Connection = "ASB.ConnectionString")]string myQueueItem, TraceWriter log)
{
	log.Info($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
	return Task.CompletedTask;
}
```

**local.settings.json**

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "<strage connection string>",
    "AzureWebJobsDashboard": "<strage connection string>",
    "ASB.ConnectionString": "<asb connection string>"
  }
}
```

When running in debugger, function is executed, no errors in console, but it's never triggered for the messages I drop on `myqueue` queue.

**Comment by SeanFeldman** [comment]
Possibly a duplicate of #478

**Comment by SeanFeldman** [comment]
PEBCAK

**Comment by lindydonna** [comment]
@SeanFeldman glad you figured it out! Thanks for following up. :)

**Comment by jkoehring** [comment]
@SeanFeldman I am experiencing the same problem. Can you tell me how you resolved it? Thank you!

**Comment by SeanFeldman** [comment]
I think (can't recall the detail) I had the actual connection string rather than connection string name from the settings in the `ServiceBusTrigger`.

**Comment by asifaziz30** [comment]
Hi, 

Can you reopen this issue for Azure.Messaging.ServiceBuss version 7.2.0 is also not trigger on local IIS to receive messages or I have to post new issue?
