### ISSUE TITLE
Multiple custom domains mapped to Function (App Service) but cannot customize Proxy URL

### ISSUE THREAD

**Issue by sgwatgit** [Azure/Azure-Functions#505]
I have a Function that is using proxies to serve content from blob storage (html, css, javascript).

The proxies work great for the original custom domain I had for the function.

I added a new custom domain and I would like to be able to have the proxies work for both the original custom domain and the new one.

I don't see where I can change the `Proxy URL`. It's readonly in the form to configure the proxy after it has been created and doesn't exist in the form to create the proxy.

1. Can I only use 1 custom domain at a time with proxies?
2. Is there a way to create new proxies with a different custom domain as the `Proxy URL`?
3. Can I configure the existing proxies to use multiple custom domains?

Thanks!

Edit --

I just tested unassigning my original custom domain to the function/app service, deleting all my proxies and then creating a new proxy hoping that it would use the 1 custom domain remaining.

Nope! The proxy uses the old custom domain that is no longer assigned to the function/app service.

Looks like I might have to completely recreate the function and never have multiple custom domains?

Edit --

I turned off proxies in the function settings, deleted all my proxies, stopped the app, started the app again and received this error toast, which was not reassuring.

```
Error:

The function runtime is unable to start. Please check the runtime logs for any errors or try again later.
Session Id: cc2fdd32dde84ebda102b3b4b70b8697

Timestamp: 2017-09-20T16:12:18.676Z
```

Then I re-enabled proxies for the function and re-created my proxies and now the default azurewebsites domain is being used as the Proxy URL instead of the custom domain I have applied to the app service.

In addition to this, the proxies appear to not be working at all anymore.

-- Edit

It appears that the proxies work but proxies matching the domain root `/` do not

If my domain is https://test.azurewebsites.net, my route template is `/` and my backend url is a public blob storage container path to an `index.html` file, the proxy no longer works (it did previously). What loads is the `Your Function App is up and running` Azure Function page.

If I create a proxy with a route template of `/newpath` (or any pattern other than `/`) and enter the backend url as the same as the above proxy then loading https://test.azurewebsites.net/newpath loads my `index.html` correctly.

**Comment by safihamid** [comment]
Could you change your route template to {*rest} and your backend url to http://yourdomain/{rest} ?

If this is not loading, could you please share the content of your proxies.json file which is at the root of your function app? the UI basically updates this file.

**Comment by sgwatgit** [comment]
Yes, `{*rest}` works just fine - that's how I'm loading all the assets in my `index.html` since those are relative paths. The problem is with `/` needing to load `index.html`

Here is my `proxies.json`
```
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "Redirect root": {
            "matchCondition": {
                "route": "/"
            },
            "backendUri": "https://mydomain.blob.core.windows.net/mycontainer/appfolder/index.html",
            "requestOverrides": {
                "backend.request.method": "get"
            }
        },
        "Rewrite asset requests": {
            "matchCondition": {
                "route": "/{*assetpath}",
                "methods": [
                    "GET"
                ]
            },
            "backendUri": "https://mydomain.blob.core.windows.net/mycontainer/appfolder/{assetpath}"
        },
        "Redirect root (adb)": {
            "matchCondition": {
                "route": "/adb"
            },
            "backendUri": "https://mydomain.blob.core.windows.net/mycontainer/appfolder/index.html"
        }
    }
}
```
The `Redirect root (adb)` proxy is my temporary solution until I can get the routing of `/` to map to my `index.html` again. The `Redirect root` proxy is the one that no longer works.

**Comment by safihamid** [comment]
Thanks for reporting this issue. We have verified this is a bug in our latest version of Proxy/Functions and will be fixing it.

**Comment by tylorhl** [comment]
I'm getting the same issue. To make it work again for now, I went into my function's Application Settings and changed ROUTING_EXTENSION_VERSION from "~0.3" to "~0.2"

**Comment by alexkarcher-msft** [comment]
@tylorhl that's correct. 
At the moment our official workaround is to roll back to version ~0.2 of Proxies by updating ROUTING_EXTENSION_VERSION to "~0.2"

**Comment by aditya-kanekar** [comment]
I am still facing the same issue for root url event after rolling back to version ~0.2

**Comment by aditya-kanekar** [comment]
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "https://myproxy.azurewebsites.net": {
            "matchCondition": {
                "route": "/"
            },
            "backendUri": "https://mystorage.blob.core.windows.net/website/index.html",
            "requestOverrides": {
                "backend.request.method": "get"
            }
        },
        "https://myproxy.azurewebsites.net/{*restOfPath}": {
            "matchCondition": {
                "route": "/{*restOfPath}"
            },
            "backendUri": "https://mystorage.blob.core.windows.net/website/{restOfPath}"
        }
    }
}

**Comment by safihamid** [comment]
We no longer support 0.2 version. Looks like your issue here is that proxy names are actually URLs. Proxy names should follow the same naming restrictions as function names meaning alpha numeric plus few other characters. The next runtime release of functions being deployed soon will give you specific errors if this is found as well as the functions portal.

**Comment by jcbrooks92** [comment]
Hamid, for people who have added in the workaround with the appsetting, should they simply remove the app setting or is the .2 version app setting no longer valid?

**Comment by safihamid** [comment]
No we no longer need or in fact read that appsetting. so that app setting value will have no effect and can be removed. There has been a breaking change for proxies which are still in 'Preview'. they are outlined here: https://github.com/Azure/app-service-announcements/issues/50

**Comment by aditya-kanekar** [comment]
Thank you Hamid, removing URLs from proxy names solved the issue.
