### ISSUE TITLE
[Visual Studio] Publishing a function from Visual Studio to Azure does not generate bindings for DocumentDB input

### ISSUE THREAD

**Issue by devbeard** [Azure/Azure-Functions#507]
**Version**: Visual Studio 2017 Enterprise 15.3.5
**Extension**: Azure Functions and Web Jobs Tools 15.0.30901.0

**Steps to reproduce**:

1. Create a new function project
2. Add a new function, select timer/schedule trigger
3. Add an input to the Run signature for DocumentDB, here is an example:
```csharp
[FunctionName("ReproduceBehaviorSample")]
        public static void Run(
            [TimerTrigger("0 */1 * * * *")]TimerInfo myTimer,
            [DocumentDB(databaseName: "my-test-db", collectionName: "some-collection-name", ConnectionStringSetting = "DOCDB_CSTR")] ICollector<object> documents,
            TraceWriter log)
        {
            log.Info($"C# Timer trigger function executed at: {DateTime.Now}");
        }
```
4. Publish to an Azure Function App

**Observations**:

- The resulting function.json does not contain the input binding, example from above looks like this:
```json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "0 */1 * * * *",
      "useMonitor": true,
      "runOnStartup": false,
      "name": "myTimer"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\SampleFunctions.dll",
  "entryPoint": "SampleFunctions.ReproduceBehaviorSample.Run"
}
```
- The function never runs successfully, as it is missing the input configuration
- But the function runs fine locally when debugging (for reasons I can only assume are related to the different runtimes locally vs remotely, or the deployment transformation between local and Azure)

**Comment by ahmelsayed** [comment]
not creating input configuration is by design as you only need the trigger information in your function.json. If you look at the `"configurationSource"` property it says that the source is `"attributes"`, the other option for that value is `"config"`. That's what tells the runtime to load from attributes or function.json. 

What error do you get when you try to run your function on azure?

**Comment by ColbyTresness** [comment]
Closing due to lack of response.
