### ISSUE TITLE
Error when debugging : can't bind Table/Blob to type

### ISSUE THREAD

**Issue by pierre-weceipt** [Azure/Azure-Functions#508]
Hi,
I'm trying to debug in VS17 a project containing 4 functions and it was working until yesterday. I had to change storage for billing reason and now i got some console errors when running the project for 2 of them (see following image).

![image](https://user-images.githubusercontent.com/6052793/30752175-c213acca-9fbb-11e7-9e0f-fe8a181be0c3.png)

My local.settings.json has a value for `AzureWebJobsStorage` (storage connection string) and I checked for mispeling in container names between storage and functions a few times already.

Here is part of the code defining impacted functions : 
```c#
[FunctionName("ConvertXml")]
        public async static Task Run([QueueTrigger("file-to-convert", Connection = "AzureWebJobsStorage")]string name,
                               [Blob("xml-extracted/{queueTrigger}", FileAccess.ReadWrite, Connection = "AzureWebJobsStorage")]CloudBlockBlob blobToConvert,
                               [Blob("rewritten-texts/{queueTrigger}", FileAccess.ReadWrite, Connection = "AzureWebJobsStorage")]CloudBlockBlob textBlob,
                               Binder binder, TraceWriter log)
```
```c#
[FunctionName("QueueArchivesToDownloadFromFtp")]
        public static async Task Run([TimerTrigger("0 30 * * * *", RunOnStartup = true)]TimerInfo myTimer,
                               [Table("GzAlreadyDownloaded", Connection = "AzureWebJobsStorage")] CloudTable tableBinding,
                               Binder binder, TraceWriter log)
```
Any idea?

**Comment by pierre-weceipt** [comment]
After some testing, it seems that binding fails for each functions that have a bind to a `CloudSomething` object (`CloudQueue`, `CloudBlockBlob`, `CloudTable`)

**Comment by fabiocav** [comment]
What version of the storage SDK are you referencing?

**Comment by pierre-weceipt** [comment]
These are the nuggets packaged in the project : 
![image](https://user-images.githubusercontent.com/6052793/31073014-7c8fb44e-a76a-11e7-9e54-c3267c9a49c3.png)
I looked into the dependency tree and it is referencing 8.4.0

**Comment by fabiocav** [comment]
Can you add an explicit reference to the Azure storage SDK version 7.2.1 and retry?

**Comment by pierre-weceipt** [comment]
Just tried, it breaks the project (package downgrade error).

I tried yesterday to do some imperative binding for the `Cloud` objects, worked for blobs but not for tables and queues. I'm  now in the process of replacing all binders by regular call to storage SDK, leaving just the triggers in `Run` method declaration.

**Comment by skartknet** [comment]
Same issue here. I can't use imperative binding to any of the Cloud types. Any workarounds about this?

![image](https://user-images.githubusercontent.com/1685262/34854182-3399f926-f78c-11e7-9745-e43af722f8f7.png)

**Comment by mcbridedm** [comment]
Same issue here...no Cloud types.  When will this be resolved?

**Comment by fabiocav** [comment]
@skartknet / @pierre-weceipt  if you're using the V2 runtime, please reference the Storage SDK 8.6.0 for now. For V1, please use 7.2.1

**Comment by mcbridedm** [comment]
I am referencing 8.6.0 and cannot bond to CloudTable.  Major issue for us.

**Comment by fabiocav** [comment]
@mcbridedm what version of the runtime/Azure Functions are you using? What error do you see?

**Comment by mcbridedm** [comment]
V2, 1.0.7

Function example:
public static class WebHook { [FunctionName("Redox")] public static async
Task<IActionResult> Run ( [HttpTrigger(AuthorizationLevel.Anonymous, "get",
"post", Route = "", WebHookType = "genericJson")]HttpRequest request,
[Table("RequestHistory", Connection = "RequestHistoryConnection")]
CloudTable requestHistoryTable, TraceWriter log ) { ... }

Error:
[1/16/2018 12:11:21 AM] Run: Microsoft.Azure.WebJobs.Host: Error indexing
method 'WebHook.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter
'requestHistoryTable' to type CloudTable. Make sure the parameter Type is
supported by the binding. If you're using binding extensions (e.g.
ServiceBus, Timers, etc.) make sure you've called the registration method
for the extension(s) in your startup code (e.g. config.UseServiceBus(),
config.UseTimers(), etc.).

I have the following nugets installed:
Microsoft.AspNet.WebApi.Client 5.2.4-preview1
Microsoft.NET.Sdk.Function 1.0.7
Newtonsoft.Json 10.0.3
WindowsAzure.Storage 8.7.0

[1/16/2018 12:11:21 AM] Run: Microsoft.Azure.WebJobs.Host: Error indexing
method 'WebHook.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter
'requestHistoryTable' to type CloudTable. Make sure the parameter Type is
supported by the binding. If you're using binding extensions (e.g.
ServiceBus, Timers, etc.) make sure you've called the registration method
for the extension(s) in your startup code (e.g. config.UseServiceBus(),
config.UseTimers(), etc.).

**Comment by fabiocav** [comment]
As I mentioned above, in 2.0, please stick with the Storage SDK 8.6.0 for now. Can you please downgrade and verify?

**Comment by mcbridedm** [comment]
Sorry should have mentioned I did attempt a downgrade, (and just did it
again) and see no difference.

Below is visual studio and installed products versions, as well as a snippy
(using 8.6.0) of what I'm seeing.

Microsoft Visual Studio Professional 2017
Version 15.5.3
VisualStudio.15.Release/15.5.3+27130.2020
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA547
Microsoft Visual Basic 2017
Visual C# 2017   00369-60000-00001-AA547
Microsoft Visual C# 2017
Visual F# 4.1   00369-60000-00001-AA547
Microsoft Visual F# 4.1
Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio
ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017
ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.
ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/
Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0
Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.
Azure Data Lake Tools for Visual Studio   2.3.0000.1
Microsoft Azure Data Lake Tools for Visual Studio
Azure Data Lake Tools for Visual Studio   2.3.0000.1
Microsoft Azure Data Lake Tools for Visual Studio
Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft
Azure Tools.
Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events
JavaScript Language Service   2.0
JavaScript Language Service
JavaScript Project System   2.0
JavaScript Project System
Microsoft Azure HDInsight Azure Node   2.3.0000.1
HDInsight Node under Azure Node
Microsoft Azure Hive Query Language Service   2.3.0000.1
Language service for Hive query
Microsoft Azure Service Fabric Tools for Visual Studio   1.8
Microsoft Azure Service Fabric Tools for Visual Studio
Microsoft Azure Stream Analytics Language Service   2.3.0000.1
Language service for Azure Stream Analytics
Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3
Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and
continuous build delivery from within the Visual Studio IDE.
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP
compatible Java Virtual Machines
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target
environment. F5 your application directly into a container with debugging,
or CTRL + F5 to edit & refresh your app without having to rebuild the
container.
Node.js Tools   1.4.11025.7
Adds support for developing and debugging Node.js apps in Visual Studio
NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet,
visit http://docs.nuget.org/.
SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools
ToolWindowHostedEditor   1.0
Hosting json editor into a tool window
TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
WebJobs Tools v1.0.0   15.0.40108.0
WebJobs Tools v1.0.0



[image: Inline image 1]

**Comment by mcbridedm** [comment]
I suspect there is an issue with my migration from v1 to v2, so hold off on
looking into this any further (on my behalf).

Created a new v2 project and am manually moving code over.  Still running
into an issue "System.Private.CoreLib: Could not load file or assembly
'Microsoft.AspNetCore.Mvc.Abstractions" but I think this might have more to
do with the cli being loaded and not the functions sdk.  Still working on
this.

Thanks!
Devin

**Comment by mcbridedm** [comment]
Resolved this issue by removing the webapicompatshim

Thank you,
Devin

**Comment by MisinformedDNA** [comment]
I'm having a binding issue as well.

My code:
```
using Microsoft.Azure.WebJobs;
using Microsoft.WindowsAzure.Storage.Table;
using System.Linq;

namespace Purina.Panda.Common.WebJobs
{
    public class TestFunction
    {
        [FunctionName("TestFunction")]
        public static void Run(
            [QueueTrigger("test-queue")]string message,
            [Table("testTable")]IQueryable<TableEntity> hashQueueQuery)
        {
        }
    }
}

```
Runtime log:
![image](https://user-images.githubusercontent.com/1784452/35110837-678d9186-fc3f-11e7-8712-348dd52a4291.png)

Project with package references:
![image](https://user-images.githubusercontent.com/1784452/35110680-04707a14-fc3f-11e7-94b4-bb0d7e44320f.png)

What do you suggest?

**Comment by Anufriev** [comment]
I have the same issue. Anyone does know how to solve this?

**Comment by fabiocav** [comment]
@MisinformedDNA IQueryable is not supported in V2. That support was removed from the .NET Standard version of the Storage SDK. The Storage team will work on re-adding that, and once they do, we'll follow suit.

**Comment by jjkesinger** [comment]
![image](https://user-images.githubusercontent.com/40048257/41136151-9a1ee64e-6a9a-11e8-919e-85236f77f0a9.png)
Same issue here but only when I install Microsoft.Azure.Webjobs.ServiceBus. Downgraded to Functions sdk 1.0.7 and using Storage 8.6.0 but I get the same error:
![image](https://user-images.githubusercontent.com/40048257/41136214-d78a86be-6a9a-11e8-9784-ce3f4e9e0b52.png)

**Comment by bubusoft** [comment]
I'm having a binding issue as well.

My code:

` public static async Task<List<AzStorage>> GetStorages([ActivityTrigger] DurableActivityContext context,
            [Table("AccountStorage", Connection = "AnexosColStorageConnection")] CloudTable table, TraceWriter log)
        {
            var result = await table.GetListByPartition<AzStorage>("Client");

            return result;
        }`

![image](https://user-images.githubusercontent.com/8460258/42246521-89e8782e-7ee2-11e8-8b87-bc083e0b13a7.png)

**Comment by bubusoft** [comment]
ok, at least I already detected which is the library that is causing the conflict and does not let the binding work correctly, this is the library Microsoft.Azure.DataMovement (0.8.0) please if someone can give me an idea because they are incompatible. I leave the libraries that I am using.

![image](https://user-images.githubusercontent.com/8460258/42247639-4a2d21d0-7ee7-11e8-8738-bc7f3a607bc2.png)

**Comment by fabiocav** [comment]
@bubusoft , is this against 1.0 or 2.0?

**Comment by bubusoft** [comment]
@faviocav is this V2.0

**Comment by fabiocav** [comment]
Can you please open a separate issue with the details of your scenario and share the version of the Storage SDK you're using? Currently (and this restriction will soon be lifted), the storage extensions expect version 8.6.0.

**Comment by ColbyTresness** [comment]
Closing since this is stale. Please reopen if necessary.
