### ISSUE TITLE
StorageQueue  Topic only covers string example

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#51]
We should ensure that we have an example which covers the CloudQueueMessage implementation as well, or at least provide a link to some relevant content.

**Comment by SyntaxC4** [comment]
POCO is also an option for binding to, we need to document these more advanced scenarios as it will help our customers be successful with real-world implementations.

**Comment by fabiocav** [comment]
Yes, it would be good to document POCOs as well as more detailed documentation on using Storage SDK types for binding.

**Comment by lindydonna** [comment]
Updated in https://github.com/Microsoft/azure-docs-pr/pull/14229
