### ISSUE TITLE
Documentation Update Required - Code & Test Azure Function Locally

### ISSUE THREAD

**Issue by lohithgn** [Azure/Azure-Functions#512]
On Sep 25 @lindydonna had an announcement post about Azure Functions being Cross Platform now. Here is the blog post link: [https://blogs.msdn.microsoft.com/appserviceteam/2017/09/25/develop-azure-functions-on-any-platform/](https://blogs.msdn.microsoft.com/appserviceteam/2017/09/25/develop-azure-functions-on-any-platform/). 

In the announcement post, there is a link to documentation regarding "Code & Test Azure Functions Locally".  Here is the link [https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local). This doc still has the following note:

> At this time, the Azure Functions Core Tools package can only be installed on Windows computers. This restriction is due to a temporary limitation in the Functions host.

Since the core tools are now xplat, the documentation should be update to  remove the note.

**Comment by lohithgn** [comment]
created a pull request for the docs here: [https://github.com/MicrosoftDocs/azure-docs/pull/3235](https://github.com/MicrosoftDocs/azure-docs/pull/3235). waiting for azure docs team to accept it and will close this issue

**Comment by ggailey777** [comment]
Thanks @lohithgn for being proactive. We have 2.0/xplat updates about ready to publish, and I will merge your commits into my internal PR to make sure you get credit for helping out.

**Comment by lohithgn** [comment]
Thanks for the update @ggailey777. Will close this issue.
