### ISSUE TITLE
Warning for C# assembly reference

### ISSUE THREAD

**Issue by imsam67** [Azure/Azure-Functions#513]
I downloaded the HttpTriggerCore C# sample. Any idea why there seems to be a warning with the C# assembly reference? This is out of the box sample project without any changes to it.

![capture](https://user-images.githubusercontent.com/15844030/30983111-7b31bea0-a457-11e7-9b95-ad5aa1932fd3.PNG)

**Comment by lindydonna** [comment]
@vijayrkn Do you have any ideas on why this might be happening?

**Comment by vijayrkn** [comment]
@lindydonna - I think it is related to this issue - https://github.com/dotnet/project-system/issues/2835

**Comment by ColbyTresness** [comment]
Closing as I believe this has been fixed. Please reopen if necessary.
