### ISSUE TITLE
1PM UK Time - Has there been a functions update deployed on consumption plans?

### ISSUE THREAD

**Issue by TheeJamesLee** [Azure/Azure-Functions#515]
Hi,

A number of our function projects that are deployed have seemed to stop running (on the consumption plan) at near enough the same time, 1PM, today (UK time). These are deployed in North Europe

Not all of our deployed functions are showing this issue..

**Comment by Shakti213** [comment]
I also have issues with app functions deployed in Northern Europe. I get errors about failing to load runtime master keys and the functions aren't even listed

**Comment by TheeJamesLee** [comment]
So, looking further at the calls... we have had a period of very long calls that are not being responded to.

Then not too long ago, a period where all responses were 403 forbiddens.

Now we are back in a period of very long calls...

**Comment by TheeJamesLee** [comment]
@lindydonna - Tagging you because I think there is an issue in the North Europe datacentre with Azure Functions on consumption plan.  Or something that is affecting multiple customers as someone else has also identified a similar problem.

**Comment by TheeJamesLee** [comment]
@Shakti213 if you have any monitoring of your calls to your functions that are affected (or if you can just hit the endpoints) do you have any of either:
- The call will just continually be waiting for completion.
- or, get a 403 response.
?

**Comment by TheeJamesLee** [comment]
fyi, an alert for Virtual Machines in North Europe is being investigated.

**Comment by Shakti213** [comment]
Thanks! All my function apps are triggered internally by event-hubs so I don't use them externally so can't answer that question. Deployed the same apps to west europe and that works fine though...

**Comment by TheeJamesLee** [comment]
I am very confident now that this is being caused by the virtual machine and storage service alerts in North Europe:
https://azure.microsoft.com/en-gb/status/

**Comment by Shakti213** [comment]
Yup that seems to be it!

**Comment by TheeJamesLee** [comment]
changes (improvements in service) are following the pattern of Azure Engineers recovering a disruption in North Europe, so satisfied that it's highly unlikely to be an update on the consumption plan.
