### ISSUE TITLE
azure-functions-cli doesn't support spaces in path

### ISSUE THREAD

**Issue by AdrianLThomas** [Azure/Azure-Functions#52]
First, apologies if this doesn't belong here. It is regarding the tooling here:
https://www.npmjs.com/package/azure-functions-cli

If there is a space in your path, then you cannot run the function. ("func run MyAzureFunction") For example if your local user account has a space in it, or the project you are working on itself. I couldn't find a workaround apart from creating a new local account without a space and removing the space from the project.

Thanks,
Adrian

**Comment by lindydonna** [comment]
Thanks for reporting, looks related to https://github.com/Azure/azure-webjobs-sdk-script/issues/837

**Comment by AdrianLThomas** [comment]
Hi, yes that looks exactly the same (apart from being in German ;-) )

Would you like me to close this?

Thanks,
Adrian

**Comment by lindydonna** [comment]
Sure, you can just watch the other issue to track the fix. Thanks for reporting!

**Comment by AdrianLThomas** [comment]
I will, thanks!
