### ISSUE TITLE
Configure blob path for Azure function via app settings

### ISSUE THREAD

**Issue by debashis1982** [Azure/Azure-Functions#521]
Hi,

I have a Azure function app with a csharp function with a run method signature like:
 public static void Run([BlobTrigger("dev-blob-path/{name}", Connection = "AzureWebJobsDashboard")]Stream myBlob, string name, TraceWriter log)

I want to be able to parameterize blob path instead of hardcoding it. I tried something like 
 public static void Run([BlobTrigger("%Blob_Path%", Connection = "AzureWebJobsDashboard")]Stream myBlob, string name, TraceWriter log)
and I set Blob_Path = dev-blob-path/{name} in app setting but it did not work.
Is there a way to be able to configure the blob path via environment properties?

Thanks,
Debashis

**Comment by lindydonna** [comment]
@debashis1982 The path expression must be present in the setting. So you can use `%dev-blob-path%/{name}`. Here's an example: https://github.com/Azure-Samples/functions-dotnet-codercards/blob/master/CoderCards/CardGenerator.cs#L20
