### ISSUE TITLE
Azure Functions VSIX fails because the Extension is signed with an invalid certificate.

### ISSUE THREAD

**Issue by HaloX69** [Azure/Azure-Functions#522]
Extension is signed with an invalid certificate
Certificate is invalid: Microsoft.VisualStudio.Web.AzureFunctions.vsix

http://www.microsoft.com/pki/certs/MicCodSigPCA_2010-07-06.crt
Whether I update the Azure workload from VS 2017 (15.3) or I download the VSXI from the marketplace and manually install I get the same results.

**Comment by ColbyTresness** [comment]
I'm closing as I assume this has been fixed by now. Please reopen if necessary.
