### ISSUE TITLE
Disabled functions with queue trigger still fire

### ISSUE THREAD

**Issue by sharpcoder28** [Azure/Azure-Functions#525]
Http triggers disable properly however queue trigger functions still fire:

![image](https://user-images.githubusercontent.com/5140239/31195991-12bd4b9c-a91a-11e7-85d1-82944bc40c58.png)

**Comment by skyhoshi** [comment]
Was this published via visual studio? or developed and implemented through the portal only? 

It's been my experience that any changes such as state, must be "Redeployed" to take affect when using the visual studio tooling. 

on the other side of that coin, when developing in the portal, the all the portal features work correctly.

we had a Scheduled Function that would fire every second when disabled manually through the portal. only when we added the [Disabled()] binding did the function actually disable. (we did not attempt to "Enable" it within the portal after deployment. let me know what you find.)

Thanks

**Comment by sharpcoder28** [comment]
Yes it was published via visual studio. I shouldn't have to redeploy to disable a function. Thanks for the find. Is there a bug for this already?

**Comment by skyhoshi** [comment]
I'm not sure actually, @lindydonna mentioned it on twitter to me.

**Comment by skyhoshi** [comment]
Just Remembered, To shut off the VS Deploy'd applications, you have to shut down them at the App Service Plan Level. (Meaning you have to delete the App Service Plan) ours was stuck in an error state. (kept running and "Consuming") this was about 2 months ago so maybe they have address it. i'm not sure. just make sure that if your using consumption, you "Redeploy with the correct settings" OR Delete your ASP associated with the functions (and the functions) or it will continue to consume, if your on a normal web ASP, it won't matter. it just affects the performance of whatever else is attached to it.

**Comment by surenderssm** [comment]
Are there any plan to fix the same ? We also faced the same issue. Messages are being received by the function even as they are in disable state.

![image](https://user-images.githubusercontent.com/12485087/34682319-96d813ee-f4c4-11e7-825e-9c87d838614c.png)

**Comment by RichardMisiak** [comment]
Still encountering this issue, are there any updates?

**Comment by kenturley** [comment]
I'm experiencing the same. Using Azure Functions V2. Have a trigger bound to a Cosmos DB collection. I disabled my function, it still fired. I stopped my function app, function still fires. 

Related: "Delete function" is grayed out on all my functions. How can we delete an individual function?

**Comment by ColbyTresness** [comment]
Closing since referenced issue seems to resolve.
