### ISSUE TITLE
Writing in F# with code from a source repo

### ISSUE THREAD

**Issue by duncanmak** [Azure/Azure-Functions#527]
I'd like to deploy to an Azure Function App backed by a source repo, but I'm having trouble anything to load. I tried 2 options.

**Deploying _run.fsx_**

I can’t get the editor experience to work in my local dev environment because of the additional namespaces and assemblies loaded by Azure Function (https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-fsharp). The documentation referred to a `COMPILED` flag, but it didn’t work and I don’t see any reference of it in the Azure WebJobs repo (https://github.com/Azure/azure-webjobs-sdk-script/tree/master/src/WebJobs.Script/Description/DotNet/Compilation/FSharp).

I'd like to load additional assemblies from Paket later on, so my "prelude" looks like this:

```FSharp
#if !COMPILED
#I "../.paket/load"
#load "Microsoft.Azure.WebJobs.fsx"
#r "System.Net.Http.dll"
#r "System.Net.Http.Formatting.dll"
#r "System.Web.Http.dll"
open Microsoft.Azure.WebJobs.Host
open System.Net.Http
open System.Net.Http.Formatting
open System.Web.Http
#endif
```

I have code in my `build.cmd` to run `paket restore` and `paket generate-load-scripts` and that's working as expected.

When I do this, I see this in the error log -
```
2017-10-05T23:54:06.170 D:\home\site\wwwroot\.paket\load\Microsoft.Azure.WebJobs.Core.fsx(2,1): error FS247: A namespace and a module named 'Microsoft.Azure.WebJobs' both occur in two parts of this assembly
```

if I exclude the prelude, then the file deploys and runs as expected, however, on my local editor, I lose type definition for all the Types coming from `Microsoft.Azure.WebJobs.Host`.

**Deploy a precompiled assembly**

When I deploy a precompiled assembly, I get an error saying that my Run method cannot be found. My entrypoint is defined as so – 

```FSharp
module Hello

let Run(req: HttpRequestMessage, log: TraceWriter) = 
    ....
```

And when I try that, adding `scriptFile` and `entryPoint` into `function.json`, I get this error:

```
2017-10-06T00:39:08.461 Function compilation error
2017-10-06T00:39:08.461 error AF007: A method matching the entry point name provided in configuration ('Hello.Run') does not exist. Your function must contain a single public method, a public method named 'Run', or a public method matching the name specified in the 'entryPoint' metadata property.
2017-10-06T00:39:08.600 Exception while executing function: Functions.Hello. Microsoft.Azure.WebJobs.Script: Invalid entry point name.
```

The `OutputType` of my project in the `fsproj` is `Library`.

**Comment by duncanmak** [comment]
@mikhailshilkov just posted a sample project here - I haven't tried it yet, I'm gonna assume that it works.

https://github.com/mikhailshilkov/FSharpHttpCore/blob/master/HttpTriggerCore/HttpTrigger.fs

Both Mikhail and I are deploying using precompiled assemblies.

I noticed that the signature to the function entrypoint is very different. Mikhail has:

```FSharp
[<AbstractClass; Sealed>]
type HttpTrigger private () =
  static member Run(req: HttpRequest, log: TraceWriter) =
```

Where as I only tried:

```FSharp
module Hello
let Run(req: HttpRequestMessage, log: TraceWriter) = 
```

Is there a reason why my (simpler) signature doesn't work? cc @fabiocav @dsyme.

The proper signature should also be documented in https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-fsharp

**Comment by dsyme** [comment]
@duncanmak Why do you have ``HttpRequestMessage`` instead of ``HttpRequest`` or is that  typo?

**Comment by duncanmak** [comment]
@dsyme Actually, it's not a typo - the F# Azure Functions doc uses this type, `HttpRequestMessage`.

**Comment by fabiocav** [comment]
`HttpRequest` is supported on Azure Functions 2.0 (which is currently in early preview). `HttpRequestMessage` is supported in 1.x and 2x, but in 2.x, we recommend using `HttpRequest`

**Comment by mikhailshilkov** [comment]
@duncanmak My implementation was 1-on-1 translation of C# example, so I used static class and static method. I've changed it to a function inside module as you suggested - still works like charm, and looks cleaner indeed.

**Comment by duncanmak** [comment]
Yeah, turns out it didn't work for me because I had a typo in my `function.json`.

Thanks to @fabiocav for spotting it!

**Comment by duncanmak** [comment]
Leaving this open to track the `COMPILE` flag, which is not working right now.

**Comment by fabiocav** [comment]
@duncanmak since the core issue reported here has been resolved, could you just open a separate item so we can investigate the problem you're reporting with the `COMPILED` symbol?
