### ISSUE TITLE
A command that prompts the user failed  

### ISSUE THREAD

**Issue by ariel1974** [Azure/Azure-Functions#53]
When I'm trying to delete a file from a File storage account I'm getting this:

Exception while executing function: Functions.TimerTriggerPowerShell1. Microsoft.Azure.WebJobs.Script: PowerShell script error. System.Management.Automation: A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Are you sure you want to perform this action?
Performing the operation "Remove-AzureStorageFile" on target "drawings/7.filtered.json".

Any idea what I'm missing?

**Comment by SyntaxC4** [comment]
@christopheranderson @paulbatum @davidebbo Can you review this Issue?

**Comment by paulbatum** [comment]
Looks like a powershell related question, moving to script repo.
