### ISSUE TITLE
Add documentation for Trigger Binding data to Service Bus & Event Hub articles

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#532]
Many triggers have additional data that goes with the payload. I've incorporated this for Blob and Queue trigger, but it's also available for many others. The fields are all documented here: https://github.com/Azure/azure-webjobs-sdk/wiki/Trigger-Binding-Data

See examples: 
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#queue-trigger-metadata 
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#trigger-metadata

**Comment by pragnagopa** [comment]
Fixed!
