### ISSUE TITLE
Document the configurationSource behavior when building in VS

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#533]
In this article: https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs, we should explain that we add two properties to the generated function.json on build:

```
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.1.0",
  "configurationSource": "attributes",
```

When `configurationSource` is attributes, customers cannot edit things like disabled in function.json. This is currently only documented in a blog post (https://blogs.msdn.microsoft.com/appserviceteam/2017/08/14/azure-functions-tools-released-for-visual-studio-2017-update-3/).

The portal will show a message saying that you can't edit function.json, with the following fwlink: https://go.microsoft.com/fwlink/?linkid=856288. When this next section is created, please update the fwlink to point to it.

**Comment by tdykstra** [comment]
Fixed by https://github.com/MicrosoftDocs/azure-docs-pr/pull/30091

Changed 856288 to https://docs.microsoft.com/azure/azure-functions/functions-dotnet-class-library#conversion-to-functionjson
