### ISSUE TITLE
Ensure all Core Tools commands are documented

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#535]
I know we're missing the option `--publish-settings-only` in the documentation for `func azure functionapp publish` but someone should do a review to makes sure everything is up to date. Article is https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

**Comment by pragnagopa** [comment]
@ankitkumarr - Can you take a quick look at the documentation and check if it is up to date?

**Comment by ankitkumarr** [comment]
@pragnagopa, I think we are missing documentation for TypeScript stuff that just got announced. I can work with @ColbyTresness to have that updated.

We are missing `--no-bundler` documentation there for Python publishing flow, but @asavaritayal has specific documentation for that [here](https://aka.ms/func-python-publish).

On a quick look, the commands that are there there look updated to me. Although, we are missing any documentation for all `func durable` commands.

**Comment by pragnagopa** [comment]
Thanks @ankitkumarr . Can you please create individual issues in core tools repo for  `--no-bundler` and durable and close this issue?

**Comment by ColbyTresness** [comment]
Closing this in favor of tracking elsewhere. @ankitkumarr let's follow up on those other commands, and @ggailey777 @craigshoemaker as FYI
