### ISSUE TITLE
The function type name '{0}' is invalid

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/Azure-Functions#541]
In my C# class, per the template, I have a function attribute to rename the function
```
[FunctionName("AckDetailFunction")]
```

And though the code runs fine locally, in Azure I get the error
```
AckDetailFunction: The function type name 'PaymentManager.Functions.AckDetailFunction' is invalid."
```

I don't currently have access to Kudu, but locally, the Function folder name is correct `AckDetailFunction`

What am I doing wrong? What can I try?

**Comment by mathewc** [comment]
Can you provide more details? Can you share your function definition as well and your function.json? You'll get this error when we fail to lookup the function MethodInfo by that name in the compiled assembly. E.g. that lookup might fail if the "entryPoint" property has an incorrect namespace.

**Comment by MisinformedDNA** [comment]
The issue went away after redeploying.

**Comment by thomasjedstrom** [comment]
Just got this error as well.  Redeploying isn't fixing it.

![image](https://user-images.githubusercontent.com/13879165/43609217-000310c6-9669-11e8-8eaa-9412e731553a.png)


This is the function:

```
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Azure.WebJobs.Extensions.EventGrid;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Threading.Tasks;


namespace EventHandlingService
{
    public static class Responder
    {
        [FunctionName("Responder")]
        public static void Run([EventGridTrigger]JObject eventGridEvent, TraceWriter log)
        {
            SendEmail().Wait();
        }

        public static async Task SendEmail()
        {
            var apiKey = "<API_KEY>";
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("<EMAIL_SENDER>", "Example User");
            var subject = "Sending with SendGrid is Fun";
            var to = new EmailAddress("<EMAIL_RECEIVER>", "Example User");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
            return;
        }
    }
}
```

If I run the ```SendEmail``` as a standard function webhook it works fine locally and live.  If I run it like above, I get that error when I publish.

**Comment by MisinformedDNA** [comment]
@thomasjedstrom The `.` is not allowed. Here's a message I pulled from the portal:

> It must start with a letter and can contain letters, numbers (0-9), dashes ("-"), and underscores ("_").

**Comment by thomasjedstrom** [comment]
@MisinformedDNA are you talking about the . in the 'EventHandlingService.Responder'?  And if so, how do you remove it (and the prepended 'EventHandlingService' part)?

I'm not seeing where I'm doing this function really very differently than the other services I've stood up and either way I assumed it was drawing from ```[FunctionName("Responder")]``` for that name so I'm not sure why it's adding the namespace/project name.

**Comment by thomasjedstrom** [comment]
I think I've deduced it has something to do with either commenting out a function that was already deployed and/or deleting a deployed function app from theportal and then redeploying via VS.  There's something going on with cached meta files that aren't getting deleted when functions are deleted.  For instance, like above, deleting a function app (in the portal) and then redeploying (with several of the functions now deleted or commented out), when it shows up in the portal, it still contains the previously deleted functions.

In any case, if I create a new project using the eventgrid template and deploy it under a new name, everything works fine.  The issue I was running into apparently had to do with me destroying deployed apps and then republishing them under the same name.

**Comment by pijemcolu** [comment]
In my case, restarting the function app in the azure portal solved the issue.

**Comment by DarrylChallenger** [comment]
Same issue happened with me. I had to totally wipe the function app, then create a new one and connect it to a pipeline in DevOps - both in the Azure portal. A waste of more hours than I care to think about!

**Comment by GitMarJansen** [comment]
This happens still. For me it was just enough to press deploy again in Azure DevOps, but the process is not what you want (deploy, check, redeploy, check ... until it works)
Can you reopen the issue?

**Comment by GitMarJansen** [comment]
See the solution mentioned here: #1208 . Use the new Azure Functions deploy task instead of the Azure App Service Deploy

**Comment by rgomns** [comment]
I also have the error "The function type name {0} is invalid" but can't use the solution to use the devops pipeline because the previous dev used 2 different accounts for devops and azure (personal and work account). Whenever i try to create a azure function pipeline i recieve the message "You don’t appear to have an active Azure subscription.". 

Please help because the function was working before i made a change in the if statement and now it doesn't work and it is a really critical process for our company.
