### ISSUE TITLE
Possible Bug report - creating storage account through integrate tab

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#542]
I'm facing a very strange situation.

I've created a new storage account through integrate tab:

![01](https://user-images.githubusercontent.com/1413082/31461201-2c9176c6-ae9f-11e7-99d6-31922a27f192.png)

After that, it sets the connection, however the created storage account is not listed under any resource group. I can connect to it, using Storage Explorer and the same connection string that the Azure Function App is using, but it's not being displayed in the portal.

![02](https://user-images.githubusercontent.com/1413082/31461316-8d6662c2-ae9f-11e7-80eb-20364d09f1db.png)

![03](https://user-images.githubusercontent.com/1413082/31461416-d745b424-ae9f-11e7-9356-7cb8e28b7603.png)

**Comment by jeffhollan** [comment]
Thanks Thiago - I've been unable to repro this.  If you get it to repro can you email me the resource ID and I can pass the investigation on to the Azure storage team?  Thanks

**Comment by thdotnet** [comment]
At this moment, I can't reproduce it again. I don't think it was a refresh problem, but I'll close the issue anyway. Thanks for the support.
