### ISSUE TITLE
Proxies deployed from VSTS using a proxies.json not working

### ISSUE THREAD

**Issue by efleming18** [Azure/Azure-Functions#543]
Hello,

I'm running into an issue where if I deploy a `proxies.json` out to my Functions App, the proxy will be displayed in the Proxies section, but doesn't seem to work. If I delete the proxy, and recreate it from the portal with the exact values I used in my `proxies.json`, save, and try again - it works!

Steps to Repro:

- Create `proxies.json` (like the one I have below)
- Push it up to VSTS and trigger a build + deployment to the Functions App
- Confirm the proxy exists with the name given in `proxies.json`
- Attempt to hit the url where the proxy should come in to play and confirm it does NOT work
- Delete the existing Proxy just created
- Create a Brand new proxy with the same values as you gave it in your `proxies.json`
- Try the url where the proxy should have come in to play in the first place, it should work

The `proxies.json` I have is:
```
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "Redirect": {
      "matchCondition": {
        "route": "{path}"
      },
      "backendUri": "https://%WEBSITE_HOSTNAME%/api/Redirect/{path}"
    }
  }
}
```

If you need any additional information, logs from anywhere, or want me to try anything please let me know! Happy to provide any help I can.

Thanks.

**Comment by dariagrigoriu** [comment]
Closing since this should have been addressed in 2018, please reactivate if issue still occurs.
