### ISSUE TITLE
Reverse Proxy to Blob Storage fails when path ends with slash

### ISSUE THREAD

**Issue by HakanL** [Azure/Azure-Functions#544]
I have the following proxies.json entry:
        "Everything else": {
            "matchCondition": {
                "route": "/{*path}"
            },
            "backendUri": "https://teeoffofflineprod.blob.core.windows.net/offline-files/maintenance.html",
            "requestOverrides": {
                "backend.request.method": "get"
            }
        }

The issue is that if my input URL ends with / then I get this 404 response:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:92b1b544-001e-0015-5bf7-424b3d000000
Time:2017-10-12T01:16:18.5823563Z</Message></Error>

But if it ends with any character then it works fine. Is something broken or am I missing something?

**Comment by jamesgallagher-ie** [comment]
I think I'm seeing something similar to this (and came across your issue while searching). I'm trying to create a static site using function proxies (as per [https://markheath.net/post/static-websites-azure-blob-storage-functions-proxies](https://markheath.net/post/static-websites-azure-blob-storage-functions-proxies))

I'm looking at the scenarios where I have URLs
1. http://example.com/path1/path2
2. http://example.com/path1/path2/ (I think some of URLs of this form exist in the current site and I want to handle them on the static version without 404ing)

Scenario 1. works using the approach in that post where I set the backend URL to have the form ...blob.core.windows.net/public-html/{restOfPath}/index.html i.e. ...blob.core.windows.net/public-html/path1/path2/index.html is shown

Using debug and downloading the dump, I can see the following snippets in the log for when Scenario 2. is being processed:

`  {
    "source": "rewrite-uri",
    "timestamp": "2018-04-02T21:43:10.8954328Z",
    "elapsed": "00:00:00.0002779",
    "data": {
      "message": "Expression was successfully evaluated.",
      "expression": "string.Format(\"/public-html/{0}/index.html\",Uri.EscapeDataString(context.Request.MatchedParameters.GetValueOrDefault(\"restOfPath\",\"\")))",
      "value": "/public-html/path1%2Fpath2/index.html"
    }
  },`
The rewrite expression is processed correctly but in the next part where the backend URL is generated the trailing "/" is making an appearance again which obviously invalidates the URL

`  {
    "source": "rewrite-uri",
    "timestamp": "2018-04-02T21:43:10.8954328Z",
    "elapsed": "00:00:00.0003073",
    "data": {
      "message": "Updated request URL per specified rewrite template.",
      "request": {
        "url": "https://test2.blob.core.windows.net/public-html/path1%2Fpath2/index.html/"
      }
    }
  }
]`

**Comment by daronyondem** [comment]
This is essentially breaking up all SPA hosted by the combination of blobs + function proxies. I'm surprised this didn't get the attention it deserves yet. It looks like the issue is first reported in October 2017.

**Comment by safihamid** [comment]
One of our engineers is working on this. what is the actual scenario which is broken for you? is that what's described above?

**Comment by daronyondem** [comment]
@safihamid Same problem described in the original issue above. I saw this added to the "active questions" milestone and didn't know a fix was in active development. That's great news! Thanks.

**Comment by safihamid** [comment]
This issue was moved to Azure/azure-functions-host#2670
