### ISSUE TITLE
TimeTrigger Function log Trace is causing Application Alert Alert For metric Exception Rate

### ISSUE THREAD

**Issue by janusznowak** [Azure/Azure-Functions#546]
TimeTrigger Function log Trace is causing Application Alert Alert For metric Exception Rate

```csharp
const string Time = "0 * * * * *";
[FunctionName("MonitorFunction")]
public static void Run([TimerTrigger(Time)]TimerInfo myTimer, TraceWriter log)
{
  try
            {
                throw new Exception("exception throw");
            }
            catch (Exception dce)
            {
                 log.Info($"Info");
            }
}
```
![image](https://user-images.githubusercontent.com/5168275/31504963-0ed5d4a8-af74-11e7-8247-246acb8537d4.png)

**Comment by mathewc** [comment]
I don't understand - you've written a timer function that just throws exceptions. It looks like this would cause 1 per minute, not the 4/second that was hit. What do your error logs show - are errors coming from somewhere else, other functions in your Function App? Why do you think this is "log Trace" causing this?

**Comment by janusznowak** [comment]
We can close the issue, it ocures that this alert Metric is couting all handled and undahndled exception. Do not make sense do me but this is how this alert metric works.

**Comment by janusznowak** [comment]
This was one fucntion in app fun plan, and log show only trace no exceptions.
