### ISSUE TITLE
Unable to `Generate API definition template` of azure function

### ISSUE THREAD

**Issue by JiaLiPassion** [Azure/Azure-Functions#548]
I created a Azure function with java following the https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven#next-steps, and the functions run correctly.

And I want to access it via Azure API Management, so I think I need to config the swagger API definition of azure function, so I go to the `API Definition`, and want to generate the API definition from HTTP trigger automatically, but when I click the `generate the API definition` button, 
the error occurs,

```
We are not able to load the generated API definition. Please check the runtime logs for any errors or try again later.
```
here is the screenshot.

<img width="1223" alt="2017-10-15 16 12 04" src="https://user-images.githubusercontent.com/1442575/31582638-2b1c55f4-b1c4-11e7-87a3-417574021ff5.png">

Please help.
thanks a lot!

**Comment by soninaren** [comment]
This feature has not been implemented in beta/2.0 runtime yet. This is a portal bug, API Definition should not be accessible when the user has switched to beta runtime.

**Comment by soninaren** [comment]
Here is the issue for reference.
https://github.com/Azure/azure-functions-ux/issues/1882

**Comment by JiaLiPassion** [comment]
@soninaren , Thank you, but even I select 1.0 runtime, the error still occurs.

**Comment by soninaren** [comment]
The java functions are only supported in the beta/2.0 runtime. If you switch to 1.0 runtime for function app with a java function. The function runtime host would end up in a error state and cause the above error.

**Comment by JiaLiPassion** [comment]
@soninaren, Thank you, I will use external `swagger` to define the API definition for now.

**Comment by dariagrigoriu** [comment]
Closing based on lack of recent activity, please revisit if issue is still relevant.
