### ISSUE TITLE
Make "Change app service plan" option appear on main page for Platform Features

### ISSUE THREAD

**Issue by odvoskin** [Azure/Azure-Functions#549]
We should highlight the option to move plans for a Function App hosted in an App Service Plan. Currently very hidden under the "all settings" option.

**Comment by ljt91** [comment]
+1 - would be great to expose this at a higher level.

**Comment by valeriob** [comment]
+1

**Comment by Gaspa79** [comment]
Indeed, this would be so useful =)

**Comment by AhmedWafaeyBoeing** [comment]
It will make it more obvious and clear.

**Comment by sumanthkannedari** [comment]
Hi, Can Anyone guide me if there is an option to change the plan from "Consumption plan" to "App Service Plan" for a Function App. In Azure Portal it is greyed out, please help me if there is any other way for it

**Comment by odvoskin** [comment]
@sumanthkannedari - this is not possible at the moment. Please follow this GH issue for updates on the feature we're planning:
https://github.com/Azure/Azure-Functions/issues/155

**Comment by pragnagopa** [comment]
closing this as Dup of #155
