### ISSUE TITLE
Visual Studio F5/build does not refresh HTTP trigger routes

### ISSUE THREAD

**Issue by cgillum** [Azure/Azure-Functions#552]
## Summary
Changes to route information on HTTP triggers are not reflected by Visual Studio on subsequent F5 debug sessions.

## Repro Steps
1. Create a VS project with an HTTP-trigger function
2. Debug the project using F5
3. Change the HTTP route
5. Debug the project a second time using F5 and observe the output of the functions CLI

### Expected
The URL of the HTTP function changes and HTTP clients can use the new route information when sending requests.

### Actual
The URL of the HTTP function does not change. HTTP clients which target the new route URL will fail with 404. Clients which target the old route information will succeed.

## Workaround
Delete the contents of the bin/obj directories whenever making a change to the route configuration of HTTP triggers.

**Comment by felpel** [comment]
Any update regarding this issue? It just occurred for me. 😞

**Comment by cgillum** [comment]
Lately I've been able to do a "Clean" or a "Rebuilt" in VS to work around this, which is better than needing to delete the bin/obj directories, but I'm not yet aware of whether the VS team has looked into this.

**Comment by ColbyTresness** [comment]
I believe this has been fixed.
