### ISSUE TITLE
Input binding fails if $inputBlob doesn't exist

### ISSUE THREAD

**Issue by duckboy1981** [Azure/Azure-Functions#554]
Input bindings for Azure Blob Store fail in PowerShell if $inputBlob doesn't exist.  This prevents basic operations such as checking if a blob exists and either creating it if it does not or returning a custom error it it does.

Example binding from **function.json** -

    {
      "type": "blob",
      "name": "inputBlob",
      "path": "configs/{config}.json",
      "connection": "AzureWebJobsDashboard",
      "direction": "in"
    }

The issue can be replicated by following these steps -

1. Create a new Function App and Storage Account.
2. Create a PowerShell HTTP trigger Function.
3. Add the binding specified above.
4. Test the function, providing a value for the **config** query parameter.

Thanks,
David

**Comment by MikeStall** [comment]
We're tracking the work for this here: https://github.com/Azure/azure-webjobs-sdk/issues/1326
