### ISSUE TITLE
Renaming functions in Visual Studio creates a new function in the Function App

### ISSUE THREAD

**Issue by CrazyTuna** [Azure/Azure-Functions#555]
I am using Visual Studio 2017 et Azure Function Sdk.

1. I have created a simple function "test-function" and deployed it. On the portal, I could see this new function.

2. Then I renamed this function to "real-function" and redeployed. On the portal, another function has been created.

I now have two functions but I can't delete the first one because functions were generated and the function app is in readonly mode.

**Comment by justcla** [comment]
When you publish from Visual Studio, there is an option in the settings of the publish configuration profile that let's you "Remove additional files at destination".
![image](https://user-images.githubusercontent.com/17131343/31743417-f25a3724-b40f-11e7-9fac-32b97c7d41f8.png)
If you check that, it should remove the old function when it does the next publish.

**Comment by CrazyTuna** [comment]
Oh gosh... I feel stupid now :-)

Thanks !

**Comment by eralston** [comment]
![sketch](https://user-images.githubusercontent.com/636858/33037216-a50cb164-cde5-11e7-97b4-a5b1aa47af43.png)
There is an analogous setting to this under "Additional Deployment Options" in the VSTS Azure App Service Deploy action, meaning you can also have self-resetting apps with CI/CD in VSTS.
