### ISSUE TITLE
Attribute routing not working guid constraint.

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/Azure-Functions#556]
https://stackoverflow.com/questions/46743180/is-attribute-routing-possible-in-azure-functions

**Comment by pragnagopa** [comment]
Tracked here: https://github.com/Azure/azure-functions-host/issues/2279

**Comment by gzuber** [comment]
After investigation, it looks like this issue is unrelated to https://github.com/Azure/azure-functions-host/issues/2279. We're now tracking this with https://github.com/Azure/azure-functions-host/issues/2960
