### ISSUE TITLE
References (using) for Azure App Insights for custom telemetry are not working not working 

### ISSUE THREAD

**Issue by tecsined** [Azure/Azure-Functions#557]
Adding only this to my function make the build fail with the error 1:
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Extensibility;

Error 1:

Error CS0234: The type or namespace name 'ApplicationInsights' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)2017-10-20T20:10:38.933 run.csx(3,17): error CS0234: The type or namespace name 'ApplicationInsights' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)2017-10-20T20:10:38.933 run.csx(6,16): error CS0246: The type or namespace name 'TelemetryClient' could not be found (are you missing a using directive or an assembly reference?)2017-10-20T20:10:38.933 run.csx(5,29): error CS0103: The name 'TelemetryConfiguration' does not exist in the current context2017-10-20T20:10:38.933 run.csx(6,48): error CS0246: The type or namespace name 'TelemetryClient' could not be found (are you missing a using directive or an assembly reference?)2017-10-20T20:10:39.112 Exception while executing function: Functions.HttpTriggerCSharp1. Microsoft.Azure.WebJobs.Script: Script compilation failed.2017-10-20T20:10:39.237 

Azure function code

```
using System.Net;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Extensibility;

private static string key = TelemetryConfiguration.Active.InstrumentationKey = System.Environment.GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY", EnvironmentVariableTarget.Process);
private static TelemetryClient telemetry = new TelemetryClient() { InstrumentationKey = key };

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req,ExecutionContext context, TraceWriter log)
{
    // parse query parameter
    string requestId = req.GetQueryNameValuePairs()
        .FirstOrDefault(q => string.Compare(q.Key, "requestId", true) == 0)
        .Value;

    // Get request body
    dynamic data = await req.Content.ReadAsAsync<object>();

    // Set name to query string or body data
    requestId = requestId ?? data?.requestId;

    return requestId == null
        ? req.CreateResponse(HttpStatusCode.BadRequest, "Please pass a requestId on the query string or in the request body")
        : req.CreateResponse(HttpStatusCode.OK, "requestId: " + requestId);
}
```

I am using a basic configuration for here
https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview)#custom-telemetry

**Comment by alrod** [comment]
@brettsam, FYI

**Comment by brettsam** [comment]
Try adding a project.json file to your function with:
```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.ApplicationInsights": "2.4.0"
      }
    }
   }
}
```
That will get things compiling.

**Comment by naveedmcp** [comment]
Try adding
#r "Microsoft.ApplicationInsights"
in your run.csx file.

**Comment by pragnagopa** [comment]
@tecsined closing this as solution provided @brettsam should work. Please reopen if this still an issue.
