### ISSUE TITLE
EventHub output binding not working

### ISSUE THREAD

**Issue by bryantharpe** [Azure/Azure-Functions#558]
When trying to create an Azure function with an out parameter to EventHub it is not generating the function.json as expected. The EventHub output binding does not get added.

I've tried this on 15.3.x and 15.4.1 with similar results.

````csharp
    public static class TestFunc
    {
        [FunctionName("TestFunc")]
        public static void Run([ServiceBusTrigger("testtopic", "testsub", AccessRights.Manage, Connection = "Endpoint=sb://...")]string mySbMsg, TraceWriter log, [EventHub("MyEventHub", Connection = "Endpoint=sb://...")]out string returnValue)
        {
            returnValue = mySbMsg;

            log.Info(returnValue);
        }
    }
````

I've tried by referencing connection via an AppSetting name as well as a hard coded connection. The output json only recognizes the ServiceBusTrigger:

Generated Function.json
````json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "Endpoint=sb://...",
      "topicName": "testtopic",
      "subscriptionName": "testsub",
      "accessRights": "manage",
      "name": "mySbMsg"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\Test.dll",
  "entryPoint": "Test.TestFunc.Run"
}
````

**Comment by mikhailshilkov** [comment]
This is expected behavior. When using WebJobs attributes in precompiled functions, only trigger definition should end up in `function.json`. The rest will be inferred from the attributes directly.
