### ISSUE TITLE
Getting bubble error after going to Function App

### ISSUE THREAD

**Issue by davidebbo** [Azure/Azure-Functions#561]
This may be due to the machine key thing. After creating Linux Func App and going to the Functions UI, it spins for a while and eventually I got this bubble:

```
The function runtime is unable to start. Please check the runtime logs for any errors or try again later. 
Session Id: c5c464c78dff4b42a47884f39492ee12
Timestamp: 2017-10-23T22:16:36.667Z
```

After clicking away and then back, it seems ok.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-ux#2027
