### ISSUE TITLE
Always On not enabled, and clicking alert does nothing

### ISSUE THREAD

**Issue by davidebbo** [Azure/Azure-Functions#562]
Two related issues:

- After creating Linux Func App, it doesn't have Always On and you get the "*'AlwaysOn' is not enabled. Your app may not function properly*" warning.
- Hovering on it makes it look clickable, but clicking on it has no effect

I was able to turn it on by manually going to settings, after which the warning disappeared.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-ux#2026
