### ISSUE TITLE
[Visual Studio] Deleting a function in VS project doesn't delete it Azure Functions App

### ISSUE THREAD

**Issue by gitsparty** [Azure/Azure-Functions#564]
Visual Studio 2017 Version 15.4
 
Repro steps - 

1. Create a Functions project, add couple of Azure Functions and publish it to Azure. 
2. Delete one of the Functions, and re-publish the project to Azure. 

The deleted function is not deleted in the Azure Functions App

**Comment by gitsparty** [comment]
To add insult to injury, the portal is in read only mode when I publish functions from visual studio. It won't let me remove the function in the portal.

**Comment by justcla** [comment]
When you publish from Visual Studio, there is an option in the settings of the publish configuration profile that let's you "Remove additional files at destination".
If you check that, it should remove the old function when it does the next publish.

See [Issue #555](https://github.com/Azure/Azure-Functions/issues/555)

**Comment by eralston** [comment]
When using Build & Release in VSTS, is there an analogous setting for deleting the target app service's files? I have this same issue in my CI/CD pipeline, but it happens w/o the publish profile, so I cannot use the stated workaround.

**Comment by eralston** [comment]
The answer is YES! You have those exact options under "Additional Deployment Options" when using the "Azure App Service Deploy" action in VSTS...

![sketch](https://user-images.githubusercontent.com/636858/33037274-da471fa4-cde5-11e7-8bf7-18801ba5c504.png)

The more you know 👍

**Comment by Dan-cws** [comment]
What about local? If I delete a function and run Iocally get "The function type name [delete func} is invalid". Same with rename

**Comment by bjohndev** [comment]
Has there been any resolution for this? I don't see these settings in VSTS.

**Comment by spacem** [comment]
It seems this is only for version 1 of the "Azure App Service Deploy" task so if you use a newer version you don't get this option.

**Comment by jeevaeastpoint** [comment]
Not there is a bug in the build task but found a work around. Switch to the version 4 of the task and in the deployment option select zip deploy. Then switch to version 3 of the task which then exposed those addition deployment options to clean the existing files before deployment. Hope it helps others.
