### ISSUE TITLE
[Visual Studio] QueueTrigger Attribute is inflexible

### ISSUE THREAD

**Issue by gitsparty** [Azure/Azure-Functions#565]
The parameters for the QueueTrigger attribute can only be constants. However, most production code require Functions to be run in different environments like - production, pre-production, test, dev, etc. So, this is really inflexible. 

I am guessing this could be fixed by using [imperative binding pattern](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#imperative-bindings "Imperative binding") but I haven't really tried it. But, I don't see a reason why it should be this complex. 

Can this be simplified somehow?

```c#
[FunctionName("UpdateUserEntity")]
public static void Run(
        [QueueTrigger("<QueueName>", Connection = "<connection string>")]
        string myQueueItem,
        TraceWriter log)
{
        log.Info($"C# Queue trigger function processed: {myQueueItem}");
}
```

**Comment by jeffhollan** [comment]
Sounds like this is more of a feature request would that be accurate?  Where you would want to "parameterize" the QueueName and choose at publish/deploy-time which name to pass in?  Or do you want the queue name to be dynamic at runtime?

**Comment by gitsparty** [comment]
I learnt the hard way that the ```Connection``` parameter refers to a setting name in Application Settings. Can we provide a similar indirection for ```QueueName```? i.e. ```QueueName``` refers to a setting name in application settings. In addition, it should be a comma separated list in case you want to bind the function to many queues. 

If you end up doing the above, ```QueueName``` __should__ be renamed to something appropriate. ```QueueNameInApplicationSettings``` or something similar.

**Comment by mikhailshilkov** [comment]
You can use `%QueueName%` which should do exactly what you are asking for: it will lookup QueueName setting.

**Comment by jeffhollan** [comment]
Closing as @mikhailshilkov has provided answer. Feel free to open a feature request uservoice or applicable repo for things like multiple queue listeners for single function (not possible today without multiple functions)
