### ISSUE TITLE
Visual Studio Extension Race Condition?

### ISSUE THREAD

**Issue by rheckart** [Azure/Azure-Functions#566]
Version 15.0.30923.0, installed into VS 2017 Community Edition.

Steps to Reproduce:

- Created a Function,
- Chose the Publish option on the Functions project in the solution,
- Chose the Create New option and hit Publish,
- The dialog box that appears seems to be in a race condition. Fan starts running high and then Visual Studio force closes ([Screencast of the issue](https://www.screencast.com/t/Xf4hEjrd))

**Comment by jeffhollan** [comment]
Thanks a ton for the Screencast - very helpful.  I'll loop in the Visual Studio team on this one to see what info they may be able to grab.  In the meantime as a workaround if you can use the Azure Portal to create the Function App (or Azure CLI) then hopefully selecting "Existing" will at least allow you to publish.

**Comment by cartermp** [comment]
I haven't been able to reproduce this in quite some time, especially with the changes to provisioning and publishing in 15.6. I'll close this for now, but please ping if we see this with VS 15.7 + latest functions tools, @rheckart.
