### ISSUE TITLE
[Visual Studio] VS project downloaded from Azure Portal compiles with warnings

### ISSUE THREAD

**Issue by gitsparty** [Azure/Azure-Functions#567]
I am using __Visual Studio 2017 - 15.4.__

When I download the Azure function content (including the VS project) from the Azure Portal, it compiles with couple of warnings. See below for warnings and a snapshot. I had a simple manual trigger Azure Function. 

```
warning NU1603: Microsoft.NET.Sdk.Functions 1.0.0-alpha6 depends on Microsoft.Build.Framework (>= 15.1.298-preview5) but Microsoft.Build.Framework 15.1.298-preview5 was not found. An approximate best match of Microsoft.Build.Framework 15.1.548 was resolved.

Microsoft.NET.Sdk.Functions 1.0.0-alpha6 depends on Microsoft.Build.Utilities.Core (>= 15.1.298-preview5) but Microsoft.Build.Utilities.Core 15.1.298-preview5 was not found. An approximate best match of Microsoft.Build.Utilities.Core 15.1.548 was resolved.
```

![functions_vs_warning](https://user-images.githubusercontent.com/26638048/32003531-3c478ea6-b954-11e7-9253-b999ba830bca.PNG)

**Comment by ahmelsayed** [comment]
This issue was moved to projectkudu/kudu#2620
