### ISSUE TITLE
Running Linux function from portal causes two invocations

### ISSUE THREAD

**Issue by davidebbo** [Azure/Azure-Functions#568]
Running a C# function from portal, I first see a call directly to the Function. And then there is a second call going through https://functions-next.azure.com/api/passthrough.

Maybe it thinks the first one failed?

**Comment by ahmelsayed** [comment]
the first one must have failed. We try to hit the app directly first and if we get a CORS error, we go through the proxy. Linux apps don't have CORS yet, so any calls to the app itself should always fail.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-ux#2025
