### ISSUE TITLE
Feedback for Create your first Azure Function page

### ISSUE THREAD

**Issue by tohling** [Azure/Azure-Functions#57]
On page https://azure.microsoft.com/en-us/documentation/articles/functions-create-first-azure-function/

1. Under Watch the video:  The following video **shows** ....
2. Under Create a function from the quickstart:  Item #2: **auto-**generated
3. Under Test the function: **"Hello ...."** response

**Comment by SyntaxC4** [comment]
@ggailey777 I know you've updated this topic, can you just check to see if this has been reflected?

**Comment by ggailey777** [comment]
https://github.com/Microsoft/azure-docs-pr/pull/6098
