### ISSUE TITLE
function app error  (Python-httpTrigger)

### ISSUE THREAD

**Issue by Farzad-Jalali** [Azure/Azure-Functions#570]
I created a function-app and add a function to it which is called: HttpTriggerPython31 (Python is language and it's HTTP trigger function ), also I set it to be anonymous.
it was working until yesterday which stops working and now even when I open it, it gave me the below error (even before I try to run it )

Error:

The function runtime is unable to start. Please check the runtime logs for any errors or try again later.
Session Id: ef8abace73b24209afda7d6617668403

Timestamp: 2017-10-27T10:21:59.786Z

Here is the contains: (it's the default contain)
```
import os
import json

postreqdata = json.loads(open(os.environ['req']).read())
response = open(os.environ['res'], 'w')
response.write("hello world from "+postreqdata['name'])
response.close()
```

**Comment by jeffhollan** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#2076
