### ISSUE TITLE
Upgrade to VS2017 15.5.0 Preview 2 results in functions publishing failure

### ISSUE THREAD

**Issue by NichUK** [Azure/Azure-Functions#571]
I was previously working with VS2017 15.3 Preview which published my Azure functions with no issue, but after upgrading to 15.5.0 Preview 2, I now get an error publishing, to do with my two project dependencies. (Error message below)

The dependency projects build and rebuild perfectly (as does the Azure Functions project), but the Azure Functions then fails to publish.

The same dependencies are also used in a web project, which still publishes perfectly, so I think this is something to do with the Azure tooling.

EDITED: To note that it's the last two lines of the output below which are causing the problem, not the warnings. The error is "OutputPath property is not set".

```
1>Done building project "functions.xxx.com.csproj".
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
  Publish Started
G:\Dev\yyy\xxx\xxx.com\functions.xxx.com\functions.xxx.com.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.Azure.WebJobs.Extensions.SendGrid 2.0.0 requires Sendgrid (>= 8.0.5 && < 9.0.0) but version Sendgrid 9.9.0 was resolved.
G:\Dev\yyy\xxx\xxx.com\functions.xxx.com\functions.xxx.com.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.NET.Sdk.Functions 1.0.0 requires Newtonsoft.Json (= 9.0.1) but version Newtonsoft.Json 10.0.2 was resolved.
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(750,5): error : The OutputPath property is not set for project 'dto.xxx.com.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [G:\Dev\yyy\xxx\xxx.com\dto.xxx.com\dto.xxx.com.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(750,5): error : The OutputPath property is not set for project 'models.xxx.com.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [G:\Dev\yyy\xxx\xxx.com\models.xxx.com\models.xxx.com.csproj]

```

**Comment by marxxxx** [comment]
The Azure functions runtime has a hard dependency to Newtonsoft.Json 9.0.1 for some reason. So if you reference an assembly from your  solution which references a newer version, this will result in this error.

So you have 2 options:
1. Downgrade your Newtonsoft.Json version for every project your reference from your function.
2. Completely isolate the code in your function project and make sure don't reference another version of Newtonsoft.Json.

Btw there is also a hard dependency to the Azure DocumentDb package (1.13. i think).

**Comment by NichUK** [comment]
Thanks @marxxxx, but that's not the issue... that's just a warning, which doesn't cause a problem, and has been working fine. It's the next two lines which are the error, and actually stop the publishing in its tracks.

**Comment by sonjabijou** [comment]
I'm experiencing this at the moment too (on 15.5 preview 2). A new functions project publishes fine, but when I reference another class library project, I get the above error.  I removed the existing reference and tried publishing; the function app published and worked fine. I added a new, completely vanilla class library with a simple empty method, without any packages installed, and referenced that. The function app won't publish from VS, with error:

> The OutputPath property is not set for project 'Temp.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Code\Reporting\Reporting\Temp\Temp.csproj]

Note that the output path for the referenced project is definitely set. Also, this occurs when trying to publish both Debug and Release configurations.

**Comment by maxstoll** [comment]
+1 same problem here after update to 15.5.0
we cant publish our backand at the moment

**Comment by hoshauch** [comment]
Same error with preview 3 :(

**Comment by vijayrkn** [comment]
We have fixed this issue and should be available in the next VS update. 

Work-around:
Update this line in Properties\PublishProfiles\<ProfileName>.pubxml (Remove the space in Any CPU). 
`    <LastUsedPlatform>AnyCPU</LastUsedPlatform>`

(Updating the profile may re-add the space. Please remove it after any profile modification).

**Comment by NichUK** [comment]
Thanks Guys! Nice easy workaround for the meantime, too, tested as functional.

**Comment by kennymatic** [comment]
@vijayrkn Just started exploring Azure Functions and encountered this issue in Visual Studio 2017 v15.5.6. 

Removing the space from AnyCPU did resolve the issue though.
