### ISSUE TITLE
integration with SQL Databases

### ISSUE THREAD

**Issue by thdotnet** [Azure/Azure-Functions#577]
As SQL Database does not support CRL Stored Procedures, it would be good if we could notify consumers when a new row is created on SQL Azure. I can use T-SQL Triggers and add the inserted row to another table, and then, write a code to read from this new table every X seconds / minutes.

A better solution would be if I could call an Azure Function or push this inserted row to Azure Event Grid.

**Comment by jeffhollan** [comment]
Would it be fair to say this is a feature ask on the SQL team?  Not sure what is actionable for us on our end or what we could build for this as we already have an Event Grid trigger.

**Comment by MV10** [comment]
Apparently it already exists:

https://github.com/Azure/azure-webjobs-sdk-extensions/issues/85#issuecomment-349661094
