### ISSUE TITLE
The "GenerateFunctions" task could not be loaded from assembly ...

### ISSUE THREAD

**Issue by Oddleif** [Azure/Azure-Functions#580]
Create a new Azure Functions project from visual studio 2017 with latest updates.
Add a new http triggered function. 
Build. Everything succeeds.
Now upgrade Microsoft.NET.Sdk.Functions from 1.0.5 or earlier to 1.0.6 I get the following issue:

![image](https://user-images.githubusercontent.com/1284732/32433952-ff13d98a-c2dc-11e7-94d1-193462895c63.png)

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "GenerateFunctions" task could not be loaded from the assembly C:\Users\OddleifHalvorsen\.nuget\packages\microsoft.net.sdk.functions\1.0.6\build\netstandard1.0\..\..\tools\net46\\Microsoft.NET.Sdk.Functions.MSBuild.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	FunctionAppTest	C:\Users\OddleifHalvorsen\.nuget\packages\microsoft.net.sdk.functions\1.0.6\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets	32

**Comment by cgillum** [comment]
@ahmelsayed do you know what this is?

**Comment by R00iBaard** [comment]
See this - https://github.com/Azure/azure-functions-vs-build-sdk/issues/128

**Comment by Oddleif** [comment]
Yes, it was the same issue. The work around solved it for now.
