### ISSUE TITLE
[Visual Studio] References to beta packages

### ISSUE THREAD

**Issue by MV10** [Azure/Azure-Functions#587]
VS2017 15.4.3

New Azure Functions projects declare nuget dependencies on beta packages. Is this intentional? I wouldn't have expected this using the release version of the Azure workload (or whatever the VS Installer calls these feature groups).

I am posting here instead of azure-webjobs-sdk-templates (which is where I think the dependencies are defined) specifically because these templates are collectively deployed through the release-version tooling. We're new to Azure Functions, so maybe this is normal or commonplace, perhaps some side-effect of the ultimate deploy-target being the shared cloud infrastructure?' In our case we had utility assemblies which declared nuget dependencies on Azure release packages which resulted in CopyLocal build conflicts (one of several examples in the screen shot).

Obviously any multi-assembly project may require synchronizing versions but slipping beta refs into what seems to be presented as release-train doesn't feel right to me.

![image](https://user-images.githubusercontent.com/794270/32726635-a103ba34-c847-11e7-9939-072735b37ae7.png)

![image](https://user-images.githubusercontent.com/794270/32726515-3e31b604-c847-11e7-9e9c-8077d8e0ec37.png)

**Comment by ahmelsayed** [comment]
in regard to the `beta` version of the assembly, I'm not sure if we have this documented somewhere (@mathewc do you know?), but the packages are beta for WebJobs users, not Functions users. The same packages are shared between the 2, but are used differently in both and they have a different release schedule\tax.

as for consolidating the versions, the package called `Microsoft.NET.Sdk.Functions` is the one locking these versions. See here for more details. https://github.com/Azure/azure-functions-vs-build-sdk/issues/107 

@fabiocav had a good idea of how we can relax that, and I'll try to get that in soon.

does that answer your questions?

**Comment by MV10** [comment]
So Functions don't depend on beta-related changes? I hadn't considered that ... but assuming I understood you correctly, that still wouldn't justify beta dependencies. We're over a year from any production deployments, so it isn't really a big deal to me, I just wanted to check whether this was intentional and normal. I appreciate the response.
