### ISSUE TITLE
[Visual Studio] Can't set debugger ports in launchSettings.json - fails to launch with F5

### ISSUE THREAD

**Issue by Rockies98** [Azure/Azure-Functions#588]
Installation: I installed v15.0.31110.0 of the Azure Functions VSIX into VS15.5 Preview 4 (build 27109.1.d15rel).  Install was successful.

What works: I was able to create a new project and then update two existing Azure Functions projects to use ‘netstandard2.0’ as the TargetFramework. I had to also fix up the code for my HTTP-based functions since the parameters and return type are now different for the Run method. After some fiddling with my nuget package cache and references to other projects, I was able to successfully build & debug locally each of the two projects and they now reference .NetCore (netstandard2.0) projects/assemblies.

What doesn’t work: I had to remove my custom debug cmd line arguments from the launchSettings.json file because they cause the host launch to fail during F5. This is a problem for me because I want to F5 launch both of my Azure Functions projects simultaneously (they interact with one another).  What I had done for this with the previous version was to configure the launchSettings.json file so that one of the projects avoids using the same ports as the other project (func cmd line arguments).

**Comment by tohling** [comment]
Could you try the suggestions posted here: https://github.com/Azure/Azure-Functions/issues/584?

**Comment by Rockies98** [comment]
I used the suggestion from #584, but with the above installation I switched my project to support .NetCore using "netstandard2.0" as the target framework.  Since this is .netcore, the command launched with the debugger (or with CTRL-F5) doesn't use the same project settings.  Not sure how to edit the launchSettings.json file now.

**Comment by ColbyTresness** [comment]
Closing in favor of tracking on #325
