### ISSUE TITLE
Nodejs reference updates

### ISSUE THREAD

**Issue by mamaso** [Azure/Azure-Functions#59]
A few suggestions for the [node docs](https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node):

- I'd suggest removing some of the discussion of the arguments object, a bit of unnecessary complexity imo.  Nothing about it seems functions specific to me.
- Mention that we support promises / include a [sample](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/sample/HttpTrigger-Node-Promise/index.js)
- Mention the support for express/connect style request and response objects and update the http sample [accordingly](https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Documentation/httpTrigger.md#example-javascript-code-for-an-http-trigger-function)
- `"You can include packages in your function by uploading a package.json file to your function's folder in the function app's file system."`
    - This implies that adding the package.json will automatically install the relevant node_modules which (unless I'm mistaken) it will not, the user still needs to run npm install

**Comment by SyntaxC4** [comment]
Please make sure #67 and #77 are done as part of this update.

**Comment by akanieski** [comment]
Are there plans to add `npm install` on deployment updates? It make little sense to recommend package.json and not support npm install. We should at least be able to add some sort of post deployment hook to call npm install. Not sure Kudu supports this.

**Comment by ggailey777** [comment]
@SyntaxC4 I am going to check in a PR for #67 and #77, but I need more time to investigate the improvements and updates that @mamaso is suggesting in this issue.
