### ISSUE TITLE
[Visual Studio] Allow publish of app settings from VS

### ISSUE THREAD

**Issue by jeffhollan** [Azure/Azure-Functions#595]
Allow for publish for app settings during VS publish. Either from current local settings, or through a key/value editor

**Comment by justcla** [comment]
Done. Added key/value editor. Released on Tuesday night. See related [blog post](https://blogs.msdn.microsoft.com/webdev/2017/11/15/improvements-to-azure-functions-in-visual-studio/#ManageApplicationSettings).

**Comment by justcla** [comment]
Got it. That's on the radar. Plus, the ability to select another settings.json file. (i.e. I want to upload all the settings from my test.settings.json, or my uat.settings.json.)
