### ISSUE TITLE
Proxy duplicating header values

### ISSUE THREAD

**Issue by dixitsuneel** [Azure/Azure-Functions#596]
I have a function and a proxy for that function in my azure env. 

I am invoking the proxy from logic app and what I am seeing is that by the time the function receives the request all the header values have been duplicated. 

For e.x:= logic app sends x-ms-execution-location as eastus
but when the function receives the request the header value is turned to
x-ms-execution-location : "eastus, eastus"

why is this happening? How do I avoid this kind of duplication? 

I tried to do a request override by setting x-ms-execution-location: ""
This simply concatenates the header x-ms-execution-location  with a comma "eastus,"
Please help.

**Comment by omkarmore83** [comment]
Looks like an issue in proxies code when calling a local function. Working on a fix. 
Note that this does not occur when your Proxies and Backend Function are on separate function apps.

**Comment by dixitsuneel** [comment]
That's too much of a hassle. For now we have a code workaround to handle the duplicate scenario. 

We will wait for this fix. Thank you.

**Comment by safihamid** [comment]
The fix is released.
