### ISSUE TITLE
DocumentDB output binding for DocumentClient in precompiled C# lacks documentation... or fails to function as expected.

### ISSUE THREAD

**Issue by Coderrob** [Azure/Azure-Functions#597]
I'm not sure if this is the right place to ask this so pardon if it is not.

I've looked at the samples here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Samples/DocumentDBSamples.cs. 

Using the sample knowledge I've read through the Azure Functions output bindings for DocumentDB here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb#docdboutput. 

I have found binding out from `[DocumentDB] DocumentClient` to fail when used in precompiled C# AF functions. When deployed to the app service environment I immediately see the following in the log stream:

`. Microsoft.Azure.WebJobs.Extensions.DocumentDB: 'Id' is required when binding to a DocumentClient property.` 

I don't see where this is a requirement of the output binding. 

Can someone create some documentation on the output binding for DocumentDB that is tailored for precomiled C# not just C# script? I believe there may be a bug here since this supposedly works for the webjobs SDK but not Azure Functions. Function.json displayed for the functions list does not include any output bindings for the specified property post-deployment.

**Comment by MV10** [comment]
Does the object you're serializing into the collection have an id property?

The sample serializes this class: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Models/ItemDoc.cs

**Comment by Coderrob** [comment]
@MV10 The function app doesn't compile when using the `[DocumentDB("database", "collection")] DocumentClient blargClient`. See the DocumentDBSamples.cs link in my original post for examples of using the DocumentDB binding. If I swap `DocumentClient` out for `IAsyncCollector<type>` the function app will compile fine.

**Comment by Coderrob** [comment]
Not even doing anything fancy at this point. It's a function app created with Visual Studio 2017 15.4.3 and adding a new Function. Adding a document DB attribute like the following:

```
        public static async Task Run(
            [QueueTrigger("analytics-query")] QueryRequest queryRequest,
            [DocumentDB("analyticsdb", "query-results", CreateIfNotExists = true)] IAsyncCollector<string> documents,
            [Queue("analytics-query")] IAsyncCollector<QueryRequest> queryRetryQueue,
            TraceWriter log)
        {
```
That'll work fine. I just lose the ability to choose what collection to output to as I would be able to do using DocumentClient. I would have to add a `DocumentDB` binding for each possible collection output. I am under the impression that I _should_ be able to use `DocumentClient` as all the examples show with the SDK. However, changing the IAsyncCollector<blarg> to DocumentClient results in the functions failing to compile with errors that 'Id' is required when binding to a DocumentClient property. If I'm using DocumentClient for an output binding then I won't have an Id property until I create a document. Either some documentation is missing for precomipiled functions using DocumentDB and DocucmentClient or there is a bug in Azure Functions resulting in this failed binding.

**Comment by MV10** [comment]
I'm pretty sure `[DocumentDB] DocumentClient dc` is an input binding, not output. You couldn't use the `DocumentClient` output binding with an async Function because `out` parameters aren't permitted for async.

I've been messing around with a related issue, see #599 -- maybe you can use the same approach.

**Comment by MV10** [comment]
Yeah notice lines 41 and 42 in the sample program you linked to:

        // Document input binding
        //   This binding requires the 'Id' property to be specified. The binding uses

**Comment by Coderrob** [comment]
Hrm, well I imagine the point still stands that the documentation isn't super clear on how to accomplish the DocumentClient binding in context of multiple document output. Lines 41-42 seemed to be related to binding to a JObject where the sample for DocumentClient didn't reference any restrictions. 

For multiple output documents it seems to have a different set of requirements that didn't explicitly rely on Id. 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb#using-a-documentdb-api-output-binding

**Comment by Coderrob** [comment]
From the sample this is the one that leads me to believe it's possible to use a DocumentDB DocumentClient binding. 
```
        // DocumentClient input binding
        //   The binding supplies a DocumentClient directly.
        public static void DocumentClient(
            [TimerTrigger("00:01", RunOnStartup = true)] TimerInfo timer,
            [DocumentDB] DocumentClient client,
            TraceWriter log)
        {
            var collectionUri = UriFactory.CreateDocumentCollectionUri("ItemDb", "ItemCollection");
            var documents = client.CreateDocumentQuery(collectionUri);

            foreach (Document d in documents)
            {
                log.Info(d.Id);
            }
        }
```

**Comment by MV10** [comment]
Yeah I see your point. Hard to say. I certainly agree the docs, uh, leave a lot to be desired. (Nothing infuriates me more than docs in the style of, "OfferType: Specifies the Offer Type." ... uh, gee, thanks a bunch.)

**Comment by jwyoung9** [comment]
If you have a direct reference to the Microsoft.Azure.DocumentDB nuget package, try removing it.  That resolved this issue for me.

**Comment by jeffhollan** [comment]
Apologies for getting to this late. Definitely some improved documentation needed here and we are going through and fixing much of our binding docs.  As for the ID Property - I believe the behavior is if you are binding to a output type that isn't a DocumentClient, the Azure Webjobs SDK will generate an ID for you before calling the document client.  If using DocumentClient directly you need to provide an ID (as the step referenced above isn't executed).  That's why your `IAsyncCollector<string>` is working but `DocumentClient` is not.

Will make a note for docs - let me know if that helps and unblocks

**Comment by jeffhollan** [comment]
Closing for now - let me know if still not working

**Comment by Afterisk** [comment]
it is still not working. I've used the latest library (1.21.1) and yet:

Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.EmployeeOpsFunction'. Microsoft.Azure.WebJobs.Extensions.DocumentDB: 'Id' is required when binding to a DocumentClient property.

:(
.

**Comment by adamreed90** [comment]
Same, I've even supplied an ID, in both places....

` public static void ProcessCompletedCall(
            [QueueTrigger("completedhangup", Connection = "HangupQueue")] VoiceCallback call,
            [DocumentDB("hangupdb", "hangupdialer", Id = "{AccountSid}", SqlQuery =
                "SELECT TOP 1 * from collectionName WHERE Id = '{AccountSid}' and Type = 'Company'", ConnectionStringSetting = "CosmosDb")]
            Company company,
            [DocumentDB("hangupdb", "hangupdialer", ConnectionStringSetting = "CosmosDb")] out VoiceCallback doc,
            TraceWriter log)
        {`
