### ISSUE TITLE
Dispose a DocumentClient reference in async Functions

### ISSUE THREAD

**Issue by MV10** [Azure/Azure-Functions#599]
I have an Http Function that needs to use a Cosmos database. Async Functions can't bind to an Azure-managed document db reference because async methods can't return `out` parameters. The DocumentClient documentation says:

> It is recommended to cache and reuse this instance within your application rather than creating a new instance for every operation.

However, that recommendation is written with the assumption the reference is used by code with a defined application lifecycle. All sample code I've seen just wraps the reference in a using() scope. I assume ignoring this will cause a leak. Since Functions do not expose lifecycle features, I am searching for a way to safely dispose the reference. I found the following technique on [stackoverflow](https://stackoverflow.com/a/18709110/152997) -- is this safe in a Function?

**Edit: Code copied from SO removed. Per Raymond Chen's article on [the GC and finalizers](https://blogs.msdn.microsoft.com/oldnewthing/20100809-00/?p=13203/), it is not safe to assume the finalizer will ever run. It seems the [other](https://stackoverflow.com/a/13258842/152997) suggestion on SO to use the `AppDomain.CurrentDomain.ProcessExit` event is probably a safer bet.**

**Comment by VividDigital** [comment]
Haven't used Comos yet so not sure if this applies but FWIW when using table storage if the method is async you can use an IAsyncCollector<T> and get around having to use an out param ie:

[Table("TableName")] IAsyncCollector<TableEntity> document

**Comment by MV10** [comment]
Unfortunately the collector approach won't work in my case (assuming it's an option, I haven't checked) because it only commits the writes after the method returns. I think I saw an open issue somewhere discussing possible changes to this behavior, though. But I need to be sure the writes execute before posting messages which reference those document records.

**Comment by MV10** [comment]
Going to try to verify this works.

        private static DocumentClient CachedDocClient = null; 
        
        public static DocumentClient DocClient
        { 
            get
            {
                if(CachedDocClient is null)
                {
                    CachedDocClient = new DocumentClient(new Uri(Config.DocumentDbUri), Config.DocumentDbKey);
                    Thread.GetDomain().ProcessExit += (object sender, EventArgs e) => { CachedDocClient.Dispose(); };
                }
                return CachedDocClient;
            }
        }

**Comment by jeffhollan** [comment]
Apologies I didn't see this earlier.  You can also use the IAsyncCollector approach and just run a `.Flush()` operation in the function to execute/catch exceptions before the return.  Let me know

**Comment by MV10** [comment]
We ended up going back to SQL but yes, it sounds as if that would have worked. Can IAsyncCollector deal with multiple write/flush cycles?

**Comment by jeffhollan** [comment]
That is a great question I do not yet know. I'll have to try it out

**Comment by MV10** [comment]
I'd be interested in hearing the results. I like Cosmos although it seemed pricey, and the partition key / storage relationship felt a lot like "make a big decision up front and hope you got it right the first time".

That being said, any thoughts about whether my `ProcessExit` event-driven Dispose ought to work? (With dependency injection so popular, I was really surprised to see Functions as statics.)

**Comment by MV10** [comment]
@jeffhollan While investigating Azure Functions dependency injection, I started looking at WebJobs Function Filters. It looks like a better solution might be to register a global-scope invocation filter and Dispose the reference in the `OnExecutedAsync` method, which seems to indicate the host is shutting down (which I'm assuming since the global scope is the "outermost" layer).

https://github.com/Azure/azure-webjobs-sdk/wiki/Function-Filters

**Comment by jeremy001181** [comment]
hey @MV10 does `ProcessExit` works well for you? also I am not sure I understand why you think it is better to release heavy object in the `OnExecutedAsync` method, which it gets called at the end of every function execution?

**Comment by MV10** [comment]
@jeremy001181 Yes, `ProcessExit` is working great.

I don't remember what led me to `OnExecutedAsync`. I later determined we can't get to enough of the WebJobs hosting by the time a Function is running, so it's a moot point. Since the "executed" verb is past-tense I think that indicated the entire _host_ is shutting down (i.e. the five-minute timeout, or something of that nature), not just a particular function invocation. I could have been wrong though, I stopped looking once I worked out the limitations getting to the host APIs.

**Comment by jeffhollan** [comment]
Sorry lost track of this - just checking we can close this issue? Using the cosmosDb bindings we will keep the client around for subsequent requests on an instance and you can send multiple documents with IAsyncCollector<>.  Hope that helps but let me know if you have any other ?s or plan to close issue.

Thanks
