### ISSUE TITLE
Add a link to the "Known Issues" page on the Wiki

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#6]

**Comment by SyntaxC4** [comment]
I think that we should add this to the left nav. It would make sure that people find the known issues quicker than if we bury it in a topic somewhere.

**Comment by ggailey777** [comment]
@SyntaxC4 is this the correct [Known Issues page](https://github.com/Azure/Azure-Functions/wiki/Known-Issues)? I only see one issue documented right now. Are there other GitHub links that need to be in the docs TOC?

**Comment by ggailey777** [comment]
Won't fix per @christopheranderson
