### ISSUE TITLE
Error:  We are not able to retrieve the runtime master key. Please try again later.

### ISSUE THREAD

**Issue by arnonea** [Azure/Azure-Functions#600]
I have one Azure function running for about two weeks now but noticed on Saturday when I go to the app instance I see: 

Error:

We are not able to retrieve the runtime master key. Please try again later.
Session Id: 9b2385c6129d4de588c1a73cca53853a

Timestamp: 2017-11-20T16:56:55.810Z

I read on previous thread about deleting a file so I tried to get to debug console via kudu and got this:

![image](https://user-images.githubusercontent.com/33840792/33031088-2eed305c-cdeb-11e7-9f95-48a373aff677.png)

**Comment by jeffhollan** [comment]
Are you still seeing issues on this? Let me know.
