### ISSUE TITLE
Azure function is invoked but the code is never executed

### ISSUE THREAD

**Issue by dixitsuneel** [Azure/Azure-Functions#601]
I can see in the monitoring log that the azure function is getting invoked. 
But the code never receives the control for execution. 

But if I hit the same http request to the function multiple times, then it starts working correctly after couple of tries. 

I know that the control is never received by my code as the first line I have in my function app is context.log.info and that doesn't get executed. 

What do we have to do to fix the issue? 

Here's the screen shot where you can see multiple requests not completing and the logs section is empty for the selected request(2nd from the top)
![request not completing](https://user-images.githubusercontent.com/12703917/33035099-fee90d10-cdf7-11e7-9c1e-7682cb2abf61.PNG)

Here's the screen shot of the first request which completed and you can see the log
![request complete](https://user-images.githubusercontent.com/12703917/33035161-2b5f6f6a-cdf8-11e7-93ae-c7495b6f4f21.PNG)

I have also added global exception handling, just in case there is an exception then that method will terminate the context with an error. 

Here's the code for the same
 process.on('uncaughtException', function (err) {
        context.log.error(err);
        context.done(err);
      });
There is no logging at all. Please help

**Comment by dixitsuneel** [comment]
Is there any update? We need an answer on this to make sure that we are able to use azure functions in production correctly. We are blocked because of this issue.

**Comment by dbronk** [comment]
It doesn't look like this issue has been looked at yet or assigned.  This is a production blocker for us.  How can we escalate this issue?

**Comment by jeffhollan** [comment]
This issue was moved to Azure/azure-webjobs-sdk-script#2151

**Comment by jeffhollan** [comment]
Moved to other repo to help track - do you know what version of the runtime you are using?  For critical blockers I'd recommend opening a support ticket as well, but in meantime will help from our side.

**Comment by christopheranderson** [comment]
Sorry, I missed this one. +1 what Jeff said. For production issues, we recommend a support ticket for fast response. GitHub is just best effort.
