### ISSUE TITLE
Cannot run & debug durable functions from Visual Studio using Azure Functions Core Tools (1.0.7)

### ISSUE THREAD

**Issue by handeeadiguzel** [Azure/Azure-Functions#602]
Hi, 

I'm trying to run & debug the following code sample locally, targeting .NET core (netstandard2.0) from Visual Studio:
https://azure.github.io/azure-functions-durable-extension/files/VSDFSampleApp.zip

And I've been getting the following error: 
`Microsoft.Azure.WebJobs.Host: Error indexing method 'HttpStart.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).`

I created the following issue, thinking that it was related to azure-functions-durable-extension: 
https://github.com/Azure/azure-functions-durable-extension/issues/95 

However it seems to be related to Visual Studio: 
I'm using Visual Studio Professional 2017 15.4.4
And Visual Studio uses:
Azure Functions Core Tools (1.0.7)
Function Runtime Version: 1.0.11375.0

When I try to run the same solution using CLI from command line, with the following version I can actually target .NET Core (still using SDK & Runtime 2.0.3) and I get no errors:
Azure Functions Core Tools (2.0.1-beta.21)
Function Runtime Version: 2.0.11370.0

Would it be possible to change the core tools version VS is using? How is it possible to run & debug Durable functions locally from Visual Studio?

**Comment by christopheranderson** [comment]
If you upgrade to the latest version of VS you can get access to 2.0 via a drop down when you create your Function App project. Check out this blog post for more information: https://blogs.msdn.microsoft.com/webdev/2017/11/15/improvements-to-azure-functions-in-visual-studio/

**Comment by handeeadiguzel** [comment]
I am able to run & debug durable functions from VS after upgrading VS to 15.5.0 Preview 4.0 which uses Azure Functions 2.0. 

However when I did the upgrade my proxies stopped working locally. This explains that
