### ISSUE TITLE
Deployment error using [CosmosDBTrigger] in one function before a collection is created from function using [DocumentDB] set to CreateIfNotExists = true

### ISSUE THREAD

**Issue by Coderrob** [Azure/Azure-Functions#604]
Scenario:

Create two new functions:

Function1 - AddDataToCosmosDb
- [DocumentDB("database", "somecollection", CreateIfNotExists = true)] IAsyncCollector<SomePoco> documents

Function2 - TrackAddedDataToCosmosDb
- [CosmosDBTrigger("database", "somecollection")] IReadOnlyList<SomePoco> modifiedDocuments

Deploy Visual Studio 2017 15.4.3 function app and see log streaming errors and clicking on function brings up ugly pink error dump on the function in the Azure portal. Errors indicate source collection "somecollection" doesn't exist from Function2. 

- - - - - - 

I have a new Azure Function with the [CosmosDBTrigger] set to a collection that doesn't exist. That'd be all find and good except I have another function with a [DocumentDB] output binding with `CreateIfNotExists` setting set to true for the collection.

This makes creating two new Azure Functions where one creates and feeds a collection and the second that will trigger off that collection impossible without having manually created the collection before deploying the function app.

**Comment by jeffhollan** [comment]
Unfortunately for us to setup the trigger listener we need a CosmosDB collection to listen to.  I believe you may be able to get this to work by leveraging a lease collection as documented [here](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed#using-the-change-feed-processor-library) and then setting up your Azure Function to listen to the lease as [documented here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb#trigger---configuration).  Let me know if that works

**Comment by camhart** [comment]
This should get solved...
