### ISSUE TITLE
Project creation support for Java

### ISSUE THREAD

**Issue by asavaritayal** [Azure/Azure-Functions#607]
**Objective**
Establish a consistent mechanism to initialize Function Apps for project-full or compiled languages such as Java and C#.

Note: The document references Java but the details apply to any language that involves an explicit compile or build step.

**Goals**
	1. Using the Functions CLI and VS Code, a user can create a Functions Java project.
	2. For language specific pieces such as generating templates and samples, the core tools elegantly defer to domain specific tooling e.g. Maven for Java.

**Non Goals**
Enable core tools to replicate the cause of domain specific tools and processes.

**Current Challenges**
- No support for Java projects through the Functions CLI and VS Code extension.
- No support for Java templates and samples.

**Proposed Experience**

[CLI and VS Code support for Java](https://microsoft.sharepoint.com/teams/AzureWebjobs/SiteAssets/AzureWebjobs%20Notebook/Tooling/Core%20Tools.one#Java%20Support%20for%20CLI%20and%20VS%20Code&section-id={98E953A1-08C8-B347-8ADF-65A1B24B8F8E}&page-id={D0181A0C-BCF1-EE43-AE29-6C2E6D61F83B}&end)

**Comment by jeffhollan** [comment]
@asavaritayal want to make sure this ends it right repo for discussion. Not sure how many open questions remain but could potentially move the azure-functions-cli repo? Let me know your thoughts.

**Comment by mathewc** [comment]
@asavaritayal - there haven't been any updates on this in over a year. Any work remaining here? If so, please reopen.
