### ISSUE TITLE
Credentials Error When Attempting to Move a File

### ISSUE THREAD

**Issue by cturner-nbme** [Azure/Azure-Functions#608]
We have a simple function that installs a python wheel and when archives the file. Up until recently it worked just fine, however when we attempted to run it today we got the following error:

`2017-11-28T19:26:47.164 Exception while executing function: Functions.WebFredPyInstall. Microsoft.Azure.WebJobs.Script: PowerShell script error. mscorlib: The user name or password is incorrect.`

The error occurs when moving and copying files, in both PowerShell and Batch scripts. Deleting files works as expected

We hadn't made a change to the python code in a few weeks so I unfortunately do not know how recently this problem actually popped up. An alternate solution is in place and working fine, but thought this should be posted here just in case.

**Comment by jeffhollan** [comment]
Not sure if you still have around but can you confirm this is still happening? Saw this issue a few weeks ago and believe has since been resolved but want to confirm.
