### ISSUE TITLE
.NET reference topic added is incorrect

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#61]
The link added in this commit is wrong: https://github.com/Microsoft/azure-docs-pr/commit/964167931b31ff528325475204b4995f80c79851

**Comment by SyntaxC4** [comment]
@lindydonna Did you report this back to the Docs team? I think I saw an email on it.

**Comment by lindydonna** [comment]
Yes, and it's fixed in the live docs. Closing this. (FYI these are the kinds of issues we are supposed to file in the docs VSTS repo.)
