### ISSUE TITLE
Forcing VS2017 to update tooling

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#611]
_From @SeanFeldman on November 24, 2017 22:41_

VS2017 (15.4.4) was modified and I needed to re-install Azure Functions tools.
Unfortunately, the extension (Azure Functions and Web Jobs Tools) is not updating nor can I force it to do so to get the latest version (15.0.31114.0).

![image](https://user-images.githubusercontent.com/1309622/33225035-b0185d6a-d12d-11e7-8492-914f0daf4490.png)

Any ideas how to address it? Thanks.

_Copied from original issue: Azure/azure-webjobs-sdk-extensions#336_

**Comment by paulbatum** [comment]
Hey @vijayrkn any idea what might be happening here?

**Comment by vijayrkn** [comment]
Min required version of VS : Visual Studio 2017 15.5 or later

Details here https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools 

After updating VS to 15.5+, it should update automatically.

**Comment by SeanFeldman** [comment]
@vijayrkn VS2017 15.5 is a *preview*. Can't expect the world to run on an experimental build 🙂
As a VS2017 15.4.5 (**stable**) user, what am I to do?

**Comment by vijayrkn** [comment]
@SeanFeldman - Currently the updated Azure functions tooling extension can only target 15.5 and above (Functions tooling version - 15.0.31114.0). You should be able to install the 15.5 preview build side-by-side with the current stable version (without any impact on the stable install).  

We don't have an updated version of functions tooling targeting 15.4.5. The previous version of the functions tooling should continue to work with 15.4. Sorry for the inconvenience

**Comment by SeanFeldman** [comment]
@vijayrkn I'm clearly communicating my personal point of view and not trying to generalize, but this strategy seems a bit off tbh. As almost if you expect to install both stable and preview versions just to be able to work with the update version of Functions tooling.

There might be a heavy reason behind this deciosion. Could you share it please?

**Comment by vijayrkn** [comment]
The updated functions tooling has dependency on components shipped in 15.5 and that is the reason the minimum version requirement was bumped up to 15.5. 

We completely understand your concern and going forward will try to make these tools available for the recent stable versions as well.  For this version, Can you try the preview version and switch to stable version when 15.5 is released?

**Comment by SeanFeldman** [comment]
15.5 preview does get the update.

You should really turn this around. Functions have GA-ed.
Meaning provide support to the stable version of VS2017. Production doesn't quite tollerate non GA-ed bits and tools.

**Comment by paulbatum** [comment]
Sean, just want to understand where you're coming from... if 15.0.31114.0 was actually version 15.0.31114.0-preview, would your same concern apply?

Basically the way that I look at it is that there is a new, preview version of functions tooling which is available in a new, preview version of VS, and that seems fine. What seems off is the version number of that preview tooling..

**Comment by SeanFeldman** [comment]
@paulbatum the update was showing in VS2017 stable. I couldn't get it installed for the reasons stated in this [comment](https://github.com/Azure/Azure-Functions/issues/611#issuecomment-347969427). Is VS2017 Stable is doing something wrong by showing an update that is for preview I shouldn't have seen to begin with?

**Comment by paulbatum** [comment]
Ahh, this makes sense.  Vijay, does this basically boil down to a feature request on the VS extension UX/gallery? I agree with Sean that its not ideal that an update appears for 15.4 users that can't be installed.. ideally the UX would filter any such update out.

**Comment by vijayrkn** [comment]
@SeanFeldman Does VS prompt that an update is available? 

The above screenshot is not showing an update option which means that this is the latest version available for the installed VS version (15.4.4)

**Comment by SeanFeldman** [comment]
It was showing up on the [tooling page](https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools)

![image](https://user-images.githubusercontent.com/1309622/33413464-e5eedffc-d54e-11e7-8fbe-02d5ffc60a52.png)

That's why I got confused that VS was on an older version while Marketplace was saying there's a newer version.

**Comment by ColbyTresness** [comment]
In VS2019, this is fixed.
