### ISSUE TITLE
Overriding where storage account connection string is retrieved from

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/Azure-Functions#612]
With webjobs, it is possible to override where storage account connection string is retreaved from by overriding `JobHostConfiguration` instance used to run webjob.

```c#
var config = new JobHostConfiguration();
config.DashboardConnectionString = Environment.GetEnvironmentVariable("ProjectName:AzureWebJobs:Dashboard");
config.StorageConnectionString = Environment.GetEnvironmentVariable("ProjectName:AzureWebJobs:Storage");
var host = new JobHost(config);
```

With Azure Functions I can't find a way how to achieve this. `JobHost` host is created on Functions' behalf and there's no way to specify connection strings or their sources. Default are used (`AzureWebJobsStorage` and `AzureWebJobsDashboard`).

What a way to override those to retrieve storage account connection string values from a different environment variable(s)?

**Comment by SeanFeldman** [comment]
cc @christopheranderson @lindydonna

**Comment by jeffhollan** [comment]
I don't believe this is possible today per reasons you mentioned above (Function service creates the JobHost). Is there a reason you want to use a differently named app setting?

**Comment by SeanFeldman** [comment]
Thanks @jeffhollan. There's always a reason and I'll be happy if you point me to a more efficient option.

When running locally different projects that involve functions, they all use the same storage account settings key. I normally set my things via environment variables and so does the rest of the collaborators.
Challenge with that is that either one has to change storage connection string each time another project is loaded or share the same storage account which is not ideal.

**Comment by jeffhollan** [comment]
Thanks @SeanFeldman that helps. Is the problem then that:

1. You have multiple function projects which all have the same local.settings.json file values you have to change
2. You have multiple collaborators working on the same function app and each need a unique value for the storage account

If it's 1 or 2 I think the problem could be solved by either having each contributor have their own local copy of local.settings.json pointing to whatever storage they need (including storage emulator locally), and for 2 would be the same (each app has the right storage account).  You could additionally remove the values from the local.settings.json file and just set an environmental variable for "AzureWebJobsStorage" - but that wouldn't work if you were doing 1 AND 2 (as you'd have to reset the environmental variable before running each function).  But if that's the case it seems like just setting the local.settings.json value would be simplest here.

Let me know if I'm missing anything

**Comment by SeanFeldman** [comment]
@jeffhollan your observations are accurate.
In general, I'd rather not rely on files that could be committed. That's why using environment variable.
Sounds like invluencing storage connection strings for Functions would be a feature request.

**Comment by jeffhollan** [comment]
Would be for now - and if it helps the local.settings.json are added to .gitignore by default and shouldn't ever show up in a commit unless you add it there.  Still not sure if allowing custom storage account mapping on the function runtime layer is best workaround for concerns though. May be unnecessary, or a band-aid on a bigger problem. I'll keep chewing on it though and feel free to keep conversation going. Good thoughts.

**Comment by SeanFeldman** [comment]
Thanks @jeffhollan. For now I'll have to stick to local.settings.json

**Comment by jeffhollan** [comment]
Sounds good - for now I'm going to close to keep issue log clean - but feel free to ping this thread if hit any blockers with local.settings.json

**Comment by iryanzhang** [comment]
@jeffhollan  for our case, we would like to put all the storage account connection stuffs in the Key Vault.

So we also want to find a way to override reading them from config files
