### ISSUE TITLE
Connection management documentation

### ISSUE THREAD

**Issue by brettsam** [Azure/Azure-Functions#613]
We need a new piece of documentation to help people diagnose connection limit thresholds and how to address them. 

This can include adding new perf metrics that we log to app insights or internal tracking.

**Comment by dariagrigoriu** [comment]
@brettsam is this still relevant?

**Comment by brettsam** [comment]
No, I should have closed this a long time ago. Docs are up at https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections
