### ISSUE TITLE
[Visual Studio] Connection field grows with inputed text when adding new function

### ISSUE THREAD

**Issue by BrainCrumbz** [Azure/Azure-Functions#615]
## Description

When adding a *New Azure Function* to a function app project, when filling *Connection* field in *Service Bus Queue trigger* form, each field gets larger and larger with inputed text, to the point that field labels disappear to the left. See screencast below:

![newazurefunctionitem](https://user-images.githubusercontent.com/3185573/33571147-64b6d63a-d92f-11e7-94bc-aed059d59394.gif)

## Steps to reproduce

1. Create a new Azure function app project, then start adding a new function
1. Select *Service Bus Queue trigger* as source
1. Fill *Connection* field with a long text

## Expected behavior

When text grows too large, the field content scrolls to the left, but label stays firm.

## Actual behavior

When text grows too large, both the field content and label scroll to the left, and label is not visible anymore.

## Environment

* Windows 10 64b 1703 build 15063.726
* Visual Studio 2017 15.4.5
* Azure App Service Tools v3.0.0 15.0.30915.0
* Azure Functions and Web Jobs Tools 15.0.30923.0

**Comment by justcla** [comment]
Will look into this.

**Comment by ColbyTresness** [comment]
Please open a VS developer community ticket for this.

https://developercommunity.visualstudio.com/spaces/8/index.html
