### ISSUE TITLE
Creating External Table triggered functions in Visual Studio

### ISSUE THREAD

**Issue by MV10** [Azure/Azure-Functions#616]
What NuGet packages are required to create an External Table triggered Function in Visual Studio?

I created one in the Portal, and based on that I pulled down Microsoft.Azure.ApiHub.Sdk, but I can't locate any WebJob packages that refer to table triggers (other than the unrelated Storage Tables, of course). I see ApiHub contains ITable but I'm guessing the attribute to mark the Run method as a table trigger would come from some WebJob package.

Also, is there any documentation relating to the connection information required by External Table Functions?

**Comment by ConnorMcMahon** [comment]
See this [chart](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings) and note that the External Table bindings do not support trigger bindings. 

You should be able to bind to a table as an External Table using the ApiHubTableAttribute in Microsoft.Azure.WebJobs.Extensions.ApiHub.

**Comment by MV10** [comment]
Bah! I can't believe I missed that. Thanks.
