### ISSUE TITLE
azure function not working after being published to azure

### ISSUE THREAD

**Issue by esmonica** [Azure/Azure-Functions#618]
I have use VS2017 community edition to create an azure function app, and while debugging locally it was working fine (it gets triggered by a service bus message). The function is quite simple, it only logs a message

```   
[FunctionName("SendPINTxtServiceBusTrigger")]
       public static void Run([ServiceBusTrigger("testqueue", AccessRights.Listen, Connection =  "ServiceBusConnection")]string myQueueItem, TraceWriter log)
        {
            log.Info($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
           
        }
```

Now I try to publish this to azure, and apparently it is publishing OK, however the azure function is not getting triggered when a new messsage is put on the service queue. The logs read:

2017-12-07T16:56:19  Welcome, you are now connected to log-streaming service.
2017-12-07T16:57:19  No new trace in the past 1 min(s).
2017-12-07T16:58:19  No new trace in the past 2 min(s).
2017-12-07T16:59:19  No new trace in the past 3 min(s).
2017-12-07T17:00:20  No new trace in the past 4 min(s).

**Comment by ConnorMcMahon** [comment]
Do you mind sharing your function application name with us? This will help us debug why your function is not triggering. If you don't feel comfortable sharing it publicly, you can follow these [instructions](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately).

**Comment by esmonica** [comment]
Hi,

I have followed the instructions on your post. However since I cannot run it after publishing it, or well, when I hit run nothing happens on the portal, the screen appears to refresh (momentarily I can spot the red cancel button) but there are no logs messages printed (apart from the 'No new trace in the past X min(s).'
, I have retrieved the information I believe you required from the cli client when running locally in debug mode:

[08/12/2017 12:36:28] Function started (Id=d444d435-ebef-431b-922e-c1f1173ea5b2)

And I can see the function being executed when a new message appears in the queue

[08/12/2017 12:36:28] Executing 'SendPINTxtServiceBusTrigger' (Reason='New ServiceBus message detected on 'XXXqueue'.', Id=d444d435-ebef-431b-922e-c1f1173ea5b2)

Region: UK-south

Hope it helps, and thanks for looking into this.

**Comment by jeroenwo** [comment]
Did Is it a v2 Azure Function? If so, did you create it with an ARM template? Apparently you have to set the version to `beta` if it is a V2..
See also https://stackoverflow.com/questions/48441111/deployed-azure-function-v2-not-running

**Comment by rzn-netcompany** [comment]
I have the exact same problem

**Comment by rzn-netcompany** [comment]
Having the exact same problem.

**Comment by ConnorMcMahon** [comment]
@esmonica Sorry for the delay in the response. Unfortunately the information you gave me is too old for us to identify your function application. Can you give us information from within the last 30 days?

@rzn-netcompany, if you are having a similar issue, please also follow the instructions linked above so we can investigate your function app.

**Comment by ConnorMcMahon** [comment]
Thanks for following up!

**Comment by rzn-netcompany** [comment]
No problem, you too!

It might be helpful to others to put this into some of the examples if it isnt already (I didnt find it at least).

**Comment by DreamsOnCloud** [comment]
@ConnorMcMahon i have the issue that my azure Function terminates after 30 mins.It is a Http Trigger .I t doent receive requests after 30 mins and starts to work when i refresh the page of azure function.Name of App is  "TestCommd".I dont see "always on" option as well.Please help me

**Comment by mathewc** [comment]
Closing since the original issue was resolved.

**Comment by iceisrael** [comment]
Why is closed? I don't see any working solution. I have the same problem, http trigger doesn't work if I publish, only work locally. I work around this with Scheduled function, but now I need again HTTP Trigger because I have to use SignalR Service, and the examples use HTTP post with clients. To verify this, use the signalr chat example with azure functions, the example works fine locally but not when I publish to azure

**Comment by sdeshbhratar** [comment]
hi
if you are still facing this issue then please go to the portal and open the function application (different from the function itself) you will see Manage Application settings as an link towards the top.
here at the bottom there are connection strings where you need to recreate the connection string to the service bus. once this is done the app will listen to the service bus and trigger the function.
