### ISSUE TITLE
Most Function types missing after upgrade to Visual Studio 15.5

### ISSUE THREAD

**Issue by MV10** [Azure/Azure-Functions#619]
After upgrading to VS 15.5 yesterday, the New Azure Function dialog box only lists five options (Http, Timer, Queue, Blob, and Durable Orchestration). 

Prior to this (VS 15.4.x) I had the full list as pictured [in the documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#create-a-function). 

Under Extensions and Updates, it does show that the Azure Functions and Web Job Tools was also updated yesterday (15.0.31201.0). Reverting does restore the full list (15.0.31106.0) but obviously that's not desirable.

How do I get the full list back with the newest release?

**Comment by MV10** [comment]
![screenshot](https://i.imgur.com/KFcvxBo.jpg)

**Comment by justcla** [comment]
This would be because your Azure Functions project must be v2 (.Net Core).
There is a limited set of templates available for Functions v2.

If you want to use one of the other Functions templates, try creating a Functions v1 project.
This is something you choose during new project creation.

**Comment by justcla** [comment]
When creating a new Functions project, choose "Azure Functions v1 (.NET Framework) from the template group picker.
![image](https://user-images.githubusercontent.com/17131343/33740851-065fb14a-db57-11e7-8c50-47c2c2ff3248.png)

**Comment by MV10** [comment]
Thank you!

**Comment by kaagati** [comment]
I am unable to compile Service Bus Queue trigger, 
![image](https://user-images.githubusercontent.com/1251951/33874324-e48fc92a-df65-11e7-88b0-2b5df84075be.png)
I have some unresolved nuget references.

**Comment by pvanroos** [comment]
@kaagati did you get this resolved?  I'm having same problem

**Comment by MV10** [comment]
@pvanroos I've had that happen a few times, closing and restarting all Visual Studio instances cleared it up.

**Comment by Fredrik-C** [comment]
I have the same issue with the template and selecting V1 does not help.
![image](https://user-images.githubusercontent.com/8351958/35060146-c6562e3a-fbbd-11e7-901e-fd8f8c5dc1e5.png)

![image](https://user-images.githubusercontent.com/8351958/35060287-49fe114e-fbbe-11e7-964c-0e8afd07f5ed.png)

**Comment by MV10** [comment]
@Fredrik-C I just noticed that happens every time when I start from a blank SLN and add a Functions project. (I haven't seen it otherwise.)

**Comment by mariusagur** [comment]
Same issue. Restarting VS does not help, creating new functions does not help, creating new solutions or projects does not help.
![image](https://user-images.githubusercontent.com/25456745/53836112-71956480-3f8f-11e9-809d-23aefd6c496f.png)
