### ISSUE TITLE
Unable to update storage account keys for slot function

### ISSUE THREAD

**Issue by imkheong** [Azure/Azure-Functions#626]
Problem statement:
Function app has one and only one Cosmos DB trigger function, named as Function A.
Created a staging slot for the function app above, set AzureWebJobsDashboard and AzureWebJobsStorage appsettings as slot settings, and change the values from storage A to storage B. Storage A and storage B are both generic standard LRS account that supports all blobs, queues etc. When selecting Function A under staging slot, Azure Portal show an error:

> Error:
> 
> The function runtime is unable to start. Please check the runtime logs for any errors or try again later. Microsoft.AspNetCore.DataProtection: The payload was invalid.
> 
> Session Id: 95879e19113846b6a1eafbd400e54d56
> 
> Timestamp: 2017-12-14T14:38:52.147Z

Synopsis:
Expect swapping of storage account as slot settings. Actual it was not working.

**Comment by patricklee2** [comment]
Are there any error in the runtime logs?

**Comment by imkheong** [comment]
There was nothing show in the log below the function on the Azure Portal.

**Comment by patricklee2** [comment]
Can you provide steps to reproduce this?

**Comment by imkheong** [comment]
Okay, but I have to find time for that. Hold on while I do that.
