### ISSUE TITLE
Is there a way to retrieve the master key inside an Azure Function

### ISSUE THREAD

**Issue by CrazyTuna** [Azure/Azure-Functions#627]
I have a Logic App that trigger an HTTP Azure Function. This Azure Function will trigger a job that perform a long task.
When the Logic App calls the function, the function returns a 202 and a new location (Another Function) to check the result of the job.

My code looks like that:

    [FunctionName("async-test")]
    public static HttpResponseMessage Accept([HttpTrigger(AuthorizationLevel.Function, "get", Route = null)]HttpRequestMessage req)
    {
        var response =  req.CreateResponse(HttpStatusCode.Accepted);
        response.Headers.Location = new Uri("https://myfunctionapp.azurewebsites.net/api/check-result?code=xxx");
        response.Headers.RetryAfter = new System.Net.Http.Headers.RetryConditionHeaderValue(TimeSpan.FromSeconds(10));
        return response;
    }

    [FunctionName("check-result")]
    public static HttpResponseMessage Run([HttpTrigger(AuthorizationLevel.Function, "get", Route = null)]HttpRequestMessage req,
        TraceWriter log, ExecutionContext context)
    { 
        return req.CreateResponse(HttpStatusCode.OK, "This is a test");
    }

I figured out that I need to send the function key (or the master key) for the logic app to be able to call the second function otherwise the logic app fails with an unauthorized exception.

I don't really want to add the master key as an app setting and I am wondering if I can retrieve this key from code inside the function ?

**Comment by kashimiz** [comment]
First, we strongly advise against using your app's master key for invoking a function; it should be reserved for management operations.

We currently don't have a first-class way to retrieve function or host-level keys from inside a function. If you'd like to request this feature for a future release, please file an issue with the [WebJobs SDK](https://github.com/Azure/azure-webjobs-sdk-script) (aka Functions runtime) repo.

It's not awful to add a function-level key as an app setting. However, if you really don't want to do this, there's a more involved approach of calling the [Kudu APIs](https://github.com/projectkudu/kudu/wiki/Functions-API): See the "Getting a function's secrets" section. To authenticate, you can [set the Function app up as a service principal.](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal)

**Comment by DoubleCouponDay** [comment]
For informational purposes, what is the point of fetching ["a short lived token that can be exchanged for a master key."](https://docs.microsoft.com/mt-mt/dotnet/api/microsoft.azure.management.websites.webappsoperationsextensions.getfunctionsadmintoken?view=azure-dotnet) if we are not permitted to programmatically access the master key?
