### ISSUE TITLE
Upgradeing to SDK 1.0.7 causing my Function debug to fail 

### ISSUE THREAD

**Issue by baget** [Azure/Azure-Functions#628]
Using VS2017 15.2.2

1. Create a new Azure Function with HTTP Trigger
2. Run it (F5)
3. See no error in the Azure function console
4. Right Click "Manage NuGet Packages"
5. Upgrade Microsoft.NET.Sdk.Functions from 1.0.6 to 1.0.7" 
6. get the following error

```
[16/12/2017 20:42:49] ScriptHost initialization failed
[16/12/2017 20:42:49] System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

```

**Comment by patricklee2** [comment]
which version of the runtime are you using?

**Comment by patricklee2** [comment]
I think this is related to https://github.com/Azure/Azure-Functions/issues/625

**Comment by baget** [comment]
i'm used also 2.0

**Comment by TonyHenrique** [comment]
I have similar issue, 
I upgraded Microsoft.NET.Sdk.Functions to version 1.0.9

and get this
 ScriptHost initialization failed

> [14/03/2018 21:38:46] System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

![image](https://user-images.githubusercontent.com/6307623/37432392-f3d8bed4-27b6-11e8-9675-470467acfa55.png)

It only works if I downgrade to version 1.0.6

**Comment by patricklee2** [comment]
@TonyHenrique I suggest trying the workaround mentioned in #625 
@justcla has there been any progress with #625 or this issue?

**Comment by leftside** [comment]
Same error here with 1.0.9

**Comment by TravisLRiffle** [comment]
Same error here with 1.0.13

**Comment by fabiocav** [comment]
@patricklee2 are you in a position to test this against the latest bits (VS tools 2.1.0/CLI 2.0.1-beta.26)? There were updates in this area and this should no longer occur.

I just validated with the steps above and can no longer repro. I'm closing this issue, but please let us know if you continue to experience issues and we'll re-open.
