### ISSUE TITLE
Unit tests + Azure functions == DLL Hell

### ISSUE THREAD

**Issue by nebosite** [Azure/Azure-Functions#632]
I'm starting up a very simple Azure functions project in visual studio 2017 (version 15.5.2)  My project looks like this:

- Azure Functions with some common code
- Test project that references Azure function project

Example Signature of a method I want to unit test:
        public int CountStuff(HttpRequestMessage request) 

For the test to work I need to provide an HttpRequestMessage, which is in both System.Net.Http.dll and System.Web.Http.dll.   It appears Azure uses the one in System.Web.Http.dll, but there is no nuget package for that.   I naively tried to add a nuget reference to Microsoft.NET.Sdk.Functions, but it won't load because of this error:

**Unable to resolve dependencies. 'Microsoft.Azure.WebJobs 3.0.0-beta4' is not compatible with 'Microsoft.NET.Sdk.Functions 1.0.7 constraint: Microsoft.Azure.WebJobs (= 2.1.0-beta4)'.**		

I don't know why I'm getting this message or how to get around it, so I went down one level to the package Microsoft.Azure.Webjobs.Extensions.http, because it include System.Web.Http.dll.    Azure functions uses 1.0.0-beta4 of the package, so I picked that version.   This installs and compiles OK, but when I run my test, I get this error:

**System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

I have been trying all kinds of incantations, including tricking my project using the bindingRedirect setting to override the dll version,  but nothing is working.   I cannot get my unit test code to play nice with Azure function code because of this dll incompatibility.   **ARRRRGGHHHH!**   What I am resorting to  is adding another method down the stack that does not rely on any symbols from System.Web.Http.   That's a crappy workaround for now, and I really think that azure functions needs a better story for getting symbols right with unit test projects.

**Comment by paulbatum** [comment]
I assume you are trying to do this for functions v1. I haven't tried to cover v2 in this answer.

My first suggestion is to avoid referencing Microsoft.NET.Sdk.Functions in projects other than your function app project. This nuget includes some custom build steps that don't really apply for other projects. So don't reference it from your unit test project. If you need to, its fine to reference its dependencies (e.g. Microsoft.Azure.WebJobs).

To get a working test project (assuming you're trying to use the built in template in VS), that can test the default HTTP function our template creates, try the following:
1. Create the test project
2. Right click the test project -> Add a reference to your function app project
3. Right click the test project -> Manage NuGet packages -> Install `Microsoft.Azure.WebJobs.Extensions.Http` version `1.0.0-beta4`.
4. Build, confirm that there are no errors.
5. Update UnitTest1.cs to the below code. You'll just need to fix the using statement based on the namespace your function is in.
6. Build, run all tests, confirm you got a running, passing test.

Alternatively, if you'd like to use something like xunit, starting from a class library, following the above steps and then referencing the xunit nugets should work just as well too.

Let me know how it goes!

Example code using MS test and testing the function defined in the default HTTP trigger template:
```
using System;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using FunctionApp22_UnitTesting;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject3
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public async Task TestMethod1()
        {
            var configuration = new HttpConfiguration();
            var request = new HttpRequestMessage(HttpMethod.Get, new Uri("http://myserver.com/api/run?name=paul"));
            request.Content = new StringContent(string.Empty);
            request.Properties[System.Web.Http.Hosting.HttpPropertyKeys.HttpConfigurationKey] = configuration;
            var traceWriter = new ConsoleTraceWriter(TraceLevel.Verbose);

            var result = await Function1.Run(request, traceWriter);

            Assert.AreEqual(HttpStatusCode.OK, result.StatusCode);
        }
    }

    public class ConsoleTraceWriter : TraceWriter
    {
        public ConsoleTraceWriter(TraceLevel traceLevel) : base(traceLevel)
        {
        }

        public override void Trace(TraceEvent traceEvent)
        {
            if (Level < traceEvent.Level)
            {
                return;
            }

            Console.WriteLine(traceEvent.Message);
        }
    }
}
```

**Comment by nebosite** [comment]
OK, that helped.  Thanks!

My Steps:

1. verified that my azure functions project is referencing v1.0.7 of Microsoft.Net.Sdk.Functions.  
2. created a brand new Unit test project (.net framework, c#) 
3. Added reference to my azure function project
4. added a nuget package reference to Microsoft.Azure.WebJobs.Extensions.Http version 1.0.0-beta4 ( I double-checked this).   
5. Compiled (looks good at this point)
6. Run tests gives error: missing Netwonsoft.Json, v10
7. Updated newtonsoft.json reference from 9.0.1 to 10.0.3
8. Rebuild solution, rerun tests.
WORKS!

So overall feedback:    It is not at all obvious what nuget package I need to successfully set up a test project.   It's not clear to me how I would discover this, either.

Question:   I am early in the implementation of this project.   Do you recommend moving to Azure functions v2?   If yes, what's the best way to upgrade what I have to v2?

**Comment by paulbatum** [comment]
@nebosite It sounds like there is still a problem with your setup. You should not have needed to update Json.NET to version 10. This might cause you more errors further down the road. The most likely explanation is that your function project is referencing a more recent version of Json.NET than it should (it should reference 9.0.1). Often this happens because your functions project is referencing some other library that requires a later version of Json.NET. Just keep this in mind if you start getting type conversion errors relating to Json.NET types.

As for your question of v1 vs v2, I recommend you stick with v1 for now as we have no GA date yet for v2. At this point in time our v2 users are mostly limited to users that need features that are v2 only (ability to run on mac/linux, java support, etc).

Closing this as resolved.
