### ISSUE TITLE
Update functions docs to link to function.json schema in schemastore

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#633]
The official schema for function.json lives in schema store here:
http://json.schemastore.org/function

The documentation at https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings should link to this.

See:
https://github.com/Azure/azure-webjobs-sdk-script/issues/2196#issuecomment-353606026

**Comment by tdykstra** [comment]
I added it in a separate h2 section so it shows up in the internal TOC -- please review https://github.com/MicrosoftDocs/azure-docs-pr/pull/30581

**Comment by tdykstra** [comment]
Fixed by https://github.com/MicrosoftDocs/azure-docs-pr/pull/30581
