### ISSUE TITLE
Can't properly parse multipart/form-data inside Azure functions using Node.js

### ISSUE THREAD

**Issue by celicoo** [Azure/Azure-Functions#636]
I'm trying to parse multipart/form-data from my Azure function writing in Node.js, but the `context.req.body` is not binary, and if I try to parse a PDF (for example) it will fail. Is there a way to bypass it? I've searched a LOT and it seems that this is a knowing issue.

    module.exports.handler = (context) => {
      context.info(context.req.body) // This is a string, not a binary
    }

I've also tried to change the `dataType` to `binary`, inside the functions.json, but it still keeps going as string, so I guess this is a bug.

**Comment by pragnagopa** [comment]
Can you try setting the content-type request header to application/octet-stream. See Related discussion [here](https://github.com/Azure/Azure-Functions/issues/253)

**Comment by pambardekar** [comment]
I got this to work only with v2 function runtime. It fails with v1.

**Comment by dagda1** [comment]
@pambardekar do you have an example of how you got this to work?

**Comment by pambardekar** [comment]
@dagda1 Please take a look at https://stackoverflow.com/questions/50526133/how-to-upload-a-file-using-node-js-function-in-azure.

I got this to work but soon realized that Azure functions are not optimized for use cases like file upload. Its not efficient and there are file size limitations depending on the language runtime you use. I have switched to using blob storage upload directly from the client.

**Comment by dagda1** [comment]
@pambardekar i was coming to that conclusion so i’m going to take this good advise.  do you use [this](https://github.com/azure/azure-storage-js) if so how do you handle sas tokens.  i was thinking of an azure function to return one.

**Comment by pambardekar** [comment]
@dagda1 I use https://www.npmjs.com/package/azure-storage. But yes, I have an azure function that returns SAS token for required container.

**Comment by mathewc** [comment]
@mhoeger Isn't there a host repo issue for this that you were/are involved with?

**Comment by mhoeger** [comment]
Yeah, this is a dupe and the solution is here: https://github.com/Azure/azure-functions-host/issues/2009

This is fixed in V2 but not in V1. In V1, this would have been a breaking change so we will not be going back and fixing that behavior: https://github.com/Azure/azure-functions-host/issues/2385
