### ISSUE TITLE
Fix Cosmos DB Javascript example

### ISSUE THREAD

**Issue by pragnagopa** [Azure/Azure-Functions#642]
Example code [here](https://docs.microsoft.com/en-US/azure/azure-functions/functions-bindings-documentdb#input---javascript-example) needs to be fixed to match the name in function.json
```
// Change input document contents using Azure Cosmos DB input binding, using context.bindings.inputDocumentOut
    module.exports = function (context) {   
    context.bindings.outputDocument = context.bindings.inputDocument;
    context.bindings.outputDocument.text = "This was updated!";
    context.done();
    };
```
Also, add CosmosDB output binding with parameter name: outputBinding

Here is the [related customer question](https://social.msdn.microsoft.com/Forums/en-US/6961888a-77bd-4a93-84cd-6ae991566774/cosmosdb-inputoutput-in-javascript?forum=AzureFunctions)

**Comment by jeffhollan** [comment]
Assigning to @tdykstra to help out

**Comment by tdykstra** [comment]
This is [1157913](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1157913/) in VSTS.

**Comment by tdykstra** [comment]
Fixed by https://github.com/MicrosoftDocs/azure-docs/pull/5117
