### ISSUE TITLE
Run Azure CLI

### ISSUE THREAD

**Issue by giorgited** [Azure/Azure-Functions#644]
Is it possible to use azure cli within Azure Functions?

I am wanting to run a command `az acs scale ...` on a timely bases from Azure Functions.

**Comment by pragnagopa** [comment]
You can use PowerShell Azure functions and run Azure Powershell commands once you logged in with [ServicePrincipal ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authenticate-service-principal)credentials. 
Store your service principal user and password in Function App's AppSettings
Sample code for[ logging in from command line](https://stackoverflow.com/questions/37249623/how-to-login-without-prompt):

$secstr = New-Object -TypeName System.Security.SecureString
$password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $env:spusername, $secstr

Login-AzureRmAccount -Credential $cred -ServicePrincipal -TenantId 72f988bf-86f1-41af-91ab-2d7cd011db47
Write-Output "PowerShell Timer trigger function logged in";

Once logged in, you should be able to run any other commands

**Comment by pragnagopa** [comment]
Closing this issue. Please reactivate if you still need help.

**Comment by tiny-dancer** [comment]
@pragnagopa can you execute azure cli within Azure Functions?

**Comment by AbhishekHumagain** [comment]
https://github.com/Azure/azure-functions-powershell-worker/issues/221
![image](https://user-images.githubusercontent.com/18373668/61863295-0f61df80-aeef-11e9-895c-7648d1bcefc7.png)
