### ISSUE TITLE
Methods property of HttpTrigger attribute does not populate function.json

### ISSUE THREAD

**Issue by jackfoxy** [Azure/Azure-Functions#645]
The methods property is missing from the function.json

## F# code
````
[<FunctionName("HttpFunc")>]
let run([<HttpTrigger(AuthorizationLevel.Anonymous, Route = "hellosanta", Methods = [|"get"|])>] req: HttpRequest, log: TraceWriter) =
````

Resulting function.json is
````
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.7",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "route": "hellosanta",
      "methods": [],
      "authLevel": "anonymous",
      "name": "req"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/HttpFunc.dll",
  "entryPoint": "HttpFunc.PrecompiledHttp.run"
}
````
Microsoft.NET.Sdk.Functions (1.0.7)

(dependency graph for WebJobs is confusing)
```
Microsoft.Azure.WebJobs (2.1.0-beta4) - restriction: || (== net47) (&& (== netstandard2.0) (>= net46))
Microsoft.Azure.WebJobs (3.0.0-beta4) - restriction: || (&& (== net47) (< net46) (>= netstandard2.0)) (== netstandard2.0)
Microsoft.Azure.WebJobs.Extensions (2.1.0-beta4) - restriction: || (== net47) (&& (== netstandard2.0) (>= net46))
Microsoft.Azure.WebJobs.Extensions (3.0.0-beta4) - restriction: || (&& (== net47) (< net46) (>= netstandard2.0)) (== netstandard2.0)
Microsoft.Azure.WebJobs.Extensions.Http (1.0.0-beta4) - restriction: || (== net47) (&& (== netstandard2.0) (>= net46))
Microsoft.Azure.WebJobs.Extensions.Http (3.0.0-beta4) - restriction: || (&& (== net47) (< net46) (>= netstandard2.0)) (== netstandard2.0)
```

**Comment by christopheranderson** [comment]
@ahmelsayed - any ideas why we wouldn't pick up the `Methods` property here?

**Comment by mikhailshilkov** [comment]
[<HttpTrigger(AuthorizationLevel.Anonymous, [|"get"|], Route = "hellosanta")>]

or simply

    [<HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "hellosanta")>]

should work just fine.

**Comment by jackfoxy** [comment]
@mikhailshilkov then it is working when the Methods property is positional, but not when named. I'll try as workaround for now.

**Comment by jackfoxy** [comment]
This code builds, so it is a bug. 

@mikhailshilkov pointed out if I had gone one link level deeper in the documentation I would have found an example of coding the property by position instead of by name.

**Comment by ian-moore** [comment]
I can also reproduce then when specifying `AuthLevel` as a named parameter instead of by position. Code compiles, but property is not reflected in `function.json`

**Comment by mathewc** [comment]
I believe these issues have all been addressed since this issue was opened a year ago. If you're still having problems let us know.
