### ISSUE TITLE
ARM template setting 'httpsOnly' is not acknowledged

### ISSUE THREAD

**Issue by jeanpaulsmit** [Azure/Azure-Functions#647]
I'd like to set the httpsOnly setting to true by default so I added it to my linked ARM templates. 
However it seems this setting is ignored on deployment (I use VSTS release management) and always set to false.

I read about someone else with the same experience on this blog post:
https://blogs.msdn.microsoft.com/benjaminperkins/2017/11/30/how-to-make-an-azure-app-service-https-only/

Is this a known issue or am I doing something wrong?

I can reproduce it using this template:
https://github.com/Azure/azure-quickstart-templates/tree/master/101-function-app-create-dynamic

Just add the httpsOnly field like specified in this tweet:
https://twitter.com/jeanpaulsmit/status/950839423486365698

The result is a Function where the HTTPS Only field still is set to 'Off'.

**Comment by davidebbo** [comment]
Closing this one since it is not related to Functions (it's a general App Service setting), and the other issue tracks the status (it will be fixed by end of month).
