### ISSUE TITLE
Function API definition (Swagger)

### ISSUE THREAD

**Issue by JORGEGO** [Azure/Azure-Functions#649]
From yesterday to today API Editor not show content...!!

Please it is so urgent because I need to change the API definition...

![af](https://user-images.githubusercontent.com/3842104/34764602-53a783c6-f5ef-11e7-85ed-162b38e82162.png)

**Comment by JORGEGO** [comment]
I believe the browsers it is blocking the information... but I do not know why...

Please I need an answer as soon as possible...

![af2](https://user-images.githubusercontent.com/3842104/34767098-94ba8734-f5f7-11e7-80a7-5afc3cc3c62a.png)

**Comment by JORGEGO** [comment]
More information
![af3](https://user-images.githubusercontent.com/3842104/34767498-8b2017ce-f5f8-11e7-9666-fec70903b614.png)

**Comment by JORGEGO** [comment]
I could continue working from visual studio, please confirm to me it is a best practice update swagger file from VS 2017
![af4](https://user-images.githubusercontent.com/3842104/34768522-55207a26-f5fb-11e7-9bca-58144fed1737.png)

**Comment by brettsam** [comment]
We're investigating this... will report back.

**Comment by alexkarcher-msft** [comment]
This issue should be all resolved. We deployed a hotfix around 2:15PST that should have the editor working on all regions. I tested it working just fine on Edge and Chrome :)

Thanks for all the help alerting us to this issue!

**Comment by JORGEGO** [comment]
Yes I confirm its working again.
Also, as I have commented are another option to change the swagger document from Visual Studio and works correctly, although I prefer the online editor more useful.

Thanks for your great job, an excellent support.
Great team.
