### ISSUE TITLE
Support for dot net core based functions that target x64

### ISSUE THREAD

**Issue by Oceanswave** [Azure/Azure-Functions#651]
In the current Azure Functions preview, it's possible to create functions that target x64, including dotnet core based functions.

However, when attempting to deploy a x64-based function to Azure, the Azure Functions runtime invokes the x86-based dotnet executable, regardless of the platform architecture specified for the app service.

**Comment by jeffhollan** [comment]
Thanks @Oceanswave - let me see what all is involved here and make sure we are tracking in the right repo.

/ cc @fabiocav @paulbatum to help with triage / milestones

**Comment by Oceanswave** [comment]
Thanks for the eyes, @jeffhollan, let me know if I can help.

**Comment by flashfm** [comment]
Hi,
I found that netstandard 2.0 dll compiled with x64 target framework still does not work on Azure Functions 2.0 (beta) (I get HTTP 404), even if Platform is set to 64-bit in the Application Settings.
Is it expected now? Is there any workarounds or maybe any plans to fix this?

BTW:
1. `func start` works locally with the same dll.
2. Also, If I have AnyCPU dll which references x64-targeted dll (both netstandard 2.0), then I get "Could not find or load a specific file. (Exception from HRESULT: 0x80131621)" exception for the referenced dll, however locally `func start` still works

Thanks!

**Comment by paulbatum** [comment]
We are in the process of deploying a release that has a fix for this issue.
https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11946-alpha

I expect the release will be deployed globally by 8/3. If you want to try it out early, create a function app in West Central US and use that for your testing.

If you're having problems, first verify that you're getting 11946 or newer:
![image](https://user-images.githubusercontent.com/10663/43421878-d999696c-93fc-11e8-94d6-d31c62a05a7a.png)

The platform switcher is here:
![image](https://user-images.githubusercontent.com/10663/43422042-5b52ae50-93fd-11e8-9a3b-4dd2254e1f67.png)


The following HTTP triggered C# function will demonstrate:

```csharp
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;

public static IActionResult Run(HttpRequest req, TraceWriter log)
{    
    var is64bit = Environment.Is64BitProcess;
    log.Info($"Is x64: {is64bit}");
    return new OkObjectResult(is64bit ? "x64" : "x86");    
}
```

**Comment by eerhardt** [comment]
@paulbatum @fabiocav - are there any instructions for getting x64 Azure Functions running locally in VS during `F5`?

**Comment by paulbatum** [comment]
Hello, see this comment and the associated linked resource:
https://github.com/Azure/azure-functions-core-tools/issues/117#issuecomment-422578505

That should be enough to unblock you (if not being exact step by step instructions).

**Comment by paulbatum** [comment]
For further questions about x64 in local development scenarios, see https://github.com/Azure/Azure-Functions/issues/376
