### ISSUE TITLE
Publish as Azure Webjobs hangs for hours when several Configurations in project

### ISSUE THREAD

**Issue by LRomano72** [Azure/Azure-Functions#654]
My project has over 100 Configurations as we have different deployment sites. We have a webjob project and when adding a new publish profile in Visual Studio, the UI just hangs for over 5 hours. I start the process and check it the next day.
This is has been happening for every version of VS2017 RTM and Preview 2.0. 

Dump file to big to include, and some screen shots, 
More details and history here. https://developercommunity.visualstudio.com/content/problem/46397/publish-as-azure-webjob-just-hangs.html

Is this code in github and open source so we can see what is going on? It seems like the tooling is trying to resolve every URL and publish profile. This is a pain and its been on going for over a year.
![azurepublishbug](https://user-images.githubusercontent.com/1781282/34909946-84933b24-f879-11e7-92e3-d39115e28001.png)

**Comment by jeffhollan** [comment]
This repro is for Azure Functions tools - looks like you were able to get a hold of VS team though here https://developercommunity.visualstudio.com/content/problem/46397/publish-as-azure-webjob-just-hangs.html

**Comment by LRomano72** [comment]
Where is the repo for Webjobs specifically as MS keep sticking everything in to the same group that you can find anything and market the coolest stuff. It's like the Taco Bell dish where they stick a taco in a burrito the the burrito into hard shell taco, then cover it in cheese and call it Azure functions but in the bottom is Webjobs. Can you point us to the right place?
