### ISSUE TITLE
Swagger API definition api keys when using traffic manager / load balancer

### ISSUE THREAD

**Issue by devlead** [Azure/Azure-Functions#655]
We've utilized that you can provide your own keys for functions when running multiple instances of a function app fronted by a load balancer or routed by traffic manager, to ensure keys match after deployment and key rotation.

With the swagger API definition there's only AFAIK renew key.

How would one go about to solve this, the end user has no way of knowing which instance they'll end up on and we rather not expose the internal azurewebsites domains.

For now we worked around by proxying to one specific instance, but that does feel a bit klunky.

**Comment by alexkarcher-msft** [comment]
Hi @devlead ! 

At the moment you have a couple of different options. 
First, the swagger key is a system key called `swaggerdocumentationkey` stored in `D:\home\data\Functions\secrets\host.json`. You can read about [using the Kudo API to read back function secrets here](https://github.com/projectkudu/kudu/wiki/Functions-API). You can use the advanced tools (kudo) editor, and it's associated APIs to edit that file and update your swagger key to be uniform across your functions.

You can also use the master key to access your OpenAPI definition, although that does expose your master key to anyone accessing the OpenAPI definition. Depending on how your traffic manager is set up, this might not be an issue.

**Comment by jeffhollan** [comment]
Closing as it looks like @alexkarcher-msft provided some options to set a uniform key.  Feel free to ping if that doesn't work or have any issues.
