### ISSUE TITLE
New Azure Functions Visual Studio 2017: project creation failed

### ISSUE THREAD

**Issue by TonyHenrique** [Azure/Azure-Functions#656]
I am trying to create a new Azure Functions Project on Visual Studio 2017 (Preview) but it displays this message:

> Creating project 'FunctionApp3'... project creation failed.

![af1](https://user-images.githubusercontent.com/6307623/34945875-90a22ee6-f9e3-11e7-9ef7-bebf16655182.png)
![af2](https://user-images.githubusercontent.com/6307623/34945882-94567d62-f9e3-11e7-897f-0ec48e576e5d.png)

### Microsoft Visual Studio Community 2017 Preview
Version 15.6.0 Preview 2.0
VisualStudio.15.Preview/15.6.0-pre.2.0+27309.0
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual F# 4.1   00369-60000-00001-AA447
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.11.01205.4
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40105.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51208.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31213.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

C# Tools   2.7.0-beta2-62412-03. Commit Hash: 84aeb8e6713068caf62ef90516bfc1ba45bf57dd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DotNetForHtml5.VisualStudioExtension.ShellIntegration   1.0
DotNetForHtml5.VisualStudioExtension.ShellIntegration

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.3.2000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.2000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   1.8
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.2000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51208.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.10-pre (f143ac1)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.6.11207.2
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta2-62412-03. Commit Hash: 84aeb8e6713068caf62ef90516bfc1ba45bf57dd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   3.6.0.1
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.27309.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WebJobs Tools v1.0.0   15.0.40108.0
WebJobs Tools v1.0.0

Xamarin   4.9.0.669 (8dcd9ff4f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.4 (b1abf46ec)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.1 (HEAD/1e47e7ed5)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.8.0.0 (d15aa28)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

XAML Editor (C#/XAML for HTML5)   1.0
(...)

**Comment by SurushS** [comment]
I had the same issue i think. What i did to solve it was uninstall the "Azure Functions and Web Jobs Tools" through the "Extensions and Updates" menu and restart Visual Studio. After that somehow the Azure functions tools were still installed and i could create new azure function projects based on the template. I'm not 100% sure but i think it has something to do that since Azure Functions tools for visual studio arent preview anymore ([source](https://blogs.msdn.microsoft.com/appserviceteam/2017/08/14/azure-functions-tools-released-for-visual-studio-2017-update-3/)), something got messed up. Hence the uninstall of the extensions and updates of azure functions from a previous install when it was still in preview.

**Comment by TonyHenrique** [comment]
Thank you. After I reverted the "Azure Functions and Web Jobs Tools" I was able to create a new Project in Visual Studio 2017
![fa1](https://user-images.githubusercontent.com/6307623/35117652-0e32444a-fc6e-11e7-8bbc-2f366eb88a7c.png)

**Comment by TonyHenrique** [comment]
With this Version 15.0.31213.0, it Works.

![image](https://user-images.githubusercontent.com/6307623/35120960-8d2c6424-fc78-11e7-916b-cb0dbc8fd822.png)
