### ISSUE TITLE
Service bus topic message not triggering function

### ISSUE THREAD

**Issue by mandarsj** [Azure/Azure-Functions#657]
I have function which is triggered with service bus topic message.
It works perfectly locally. however, when i publish, and push messages to topic. 
there is nothing happening in the function.no logs. absolutely nothing.

Worth mentioning, that I also have a timertrigger function in the same app. and it works.

What can i check?

**Comment by mhoeger** [comment]
I wonder if this is related to #478. To confirm, could you try the workaround detailed in that issue? (The workaround is to manually change the function.json file to have a "direction": "in" property and a "configurationSource": "config" property, as WayneMcRae and FAImeidaActionpoint propose).

**Comment by mandarsj** [comment]
Well, It was with the "Connection" property on the ServiceBusTrigger. I had mentioned Connection="TopicConn", the runtime was going and searching for "WebJobsTopicConn" in the portal application settings and it was crashing.

If I have only mentioned "TopicConn" why does runtime need to append "WebJobsTopicConn" ? can't it just look for what the code has mentioned.

**Comment by mhoeger** [comment]
It should work with just "TopicConn"! We check for both the prefixed and unprefixed name. If you saw an error earlier saying that you needed to add the connection string "AzureWebJobsTopicConn" once you published, the error should actually specify that "AzureWebJobsTopicConn or TopicConn" could not be found.

You can verify this by changing your connection string name to "TopicConn" in App Settings through the Azure Portal. It should still work!

**Comment by mathewc** [comment]
Yes, both prefixed and non-prefixed connection strings should work. If not, then it's a bug (however we have tests verifying both work :))

I do agree with @mhoeger that the error message (coming from code [here](https://github.com/Azure/azure-webjobs-sdk/blob/b67e4c9299ac51c935fd9aeae20c086f75a13bac/src/Microsoft.Azure.WebJobs.ServiceBus/MessagingProvider.cs#L123)) is a bit misleading. It looks like our error handling for Storage connection strings is a bit different (code [here](https://github.com/Azure/azure-webjobs-sdk/blob/d6cbe7410dd21bae7d49070c2827d8164cfc29a3/src/Microsoft.Azure.WebJobs.Host/Executors/StorageAccountParser.cs#L89)). It only applies prefixes for the "built-in" Dashboard/Storage connection strings, not custom user connection strings.

**Comment by mandarsj** [comment]
Indeed,When I added an App Setting with name "TopicConn",  I got an error of "AzureWebJobsTopicConn" Could not be found in Kudu Console. That's when i changed it to "AzureWebJobsTopicConn" and it just worked. Maybe I can try again and give you some logs if it helps you track it.

**Comment by mathewc** [comment]
@mhoeger likely has all the info she needs to repro the issue and create a tracking bug for improving our error messages. Thanks :)
