### ISSUE TITLE
Azure functions seems to be slower

### ISSUE THREAD

**Issue by pierre-weceipt** [Azure/Azure-Functions#659]
Hi, I'm using functions to unzip some archives (2 or 3 daily but hundreds for initial import, max 15mb) and it was working fine until monday/tuesday where the extracting process started to timeout (used to run in the 10min extended limit fixed in host.json). I'm wondering if any change was done to be more strict on timeouts (maybe these used to last more than 10min but were not directly cut) or if this is a consequence of meltdown/spectre patches and things are just slower?

**Comment by jeffhollan** [comment]
Difficult to say - we didn't make an high-level changes in the last few weeks that I'm aware of that would impact performance to this degree. May be worth one of the following to help use track internally:

1. If more urgent, best bet is to open a support ticket with Azure. Eventually notifies our team of developers who are on call and response ASAP
1. If have a little more time, I'd recommend posting on StackOverflow under the azure-functions tag. We have a developer each week who monitors that and usually a bit easier for us to track down than this GitHub repo

Let me know - if you fail to find traction feel free to ping me on GitHub or Twitter and I'll help try to get to bottom. Know eventually what we'll need is things like the App Name and Function name and timespan for when you saw the timeouts.  Would be interesting to know as well what the duration was before the last week (was it 8/9 minutes or 5/6).

Gonna close for now but let me know if you need more.

**Comment by pierre-weceipt** [comment]
Thanks for the answer, I'll tryto fill a ticket. Hard for me to say which exact duraction it took before as I just  launched extraction on whole sources (hundreds of archives) and just look after in the poison queue if there are any fail (and all managed to extract before). 
I'm thinking of a solution rerouting the timedout archives to a service app plan always on execution. I filled up an issue on SO already as I don't know how to catch the timeout event : https://stackoverflow.com/questions/48284394/detect-timeout-on-azure-function-to-reroute-message-to-app-service-plan?noredirect=1#comment83579111_48284394

**Comment by pierre-weceipt** [comment]
Hey, I did more testing and implemented my solution with a reroute to a Web App service plan when timing out. I just wanted to add that the problem seems to be ressources concurency, when too much archives are extracted at same time (and files extracted are dealt with in another function), extraction becomes slower (when rerouted to the long running function they run much faster even though it's just a basic plan app).
