### ISSUE TITLE
Azure Functions and Web Job Tools extension stops SpecFlow feature files from generating code-behind

### ISSUE THREAD

**Issue by yorkshirefellman** [Azure/Azure-Functions#660]
Referencing the following issue https://github.com/techtalk/SpecFlow/issues/857

I have found that for me, disabling the Azure Functions and Web Job Tools extension resolved the issue. As soon as I re-enable the extension then when trying to generate the feature file code-behind the following error is given "Generation error: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0"

I am using the latest version of Visual Studio 2017 Enterprise (v15.5.4)

**Comment by DanielTheCoder** [comment]
Have you tried the new pre-release versions from techtalk/SpecFlow#857 ?

VS Extension: TechTalk.SpecFlow.VsIntegration.2017-Fix857.vsix.zip
New SpecFlow version: https://www.nuget.org/packages/SpecFlow/2.3.0-preview20180201
