### ISSUE TITLE
Correct way to use async in Azure functions

### ISSUE THREAD

**Issue by mandarsj** [Azure/Azure-Functions#662]
In the Azure functions Performance considerations part,  https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices
Under Use async code but avoid blocking calls
 async programming is the suggested practice for performance improvement.however what is the best way to use it. for example, in my scenarion, I have a Service Bus Trigger

 public static void Run([ServiceBusTrigger("topicname", "subname", AccessRights.Manage, Connection = "TopicConnection")]string message, TraceWriter log)
        {
            try { 
            log.Info($"C# ServiceBus topic trigger function processed message: {message}");
          

            Task.Run(() => PushToDb(message, log));
            }
            catch(Exception ex)
            {
                log.Info($"Exception found {ex.Message}");
            }
        }

In the above code, I call PushToDb method async ,however since it runs in the background, Function runtime assumes that the messages is consumed successfully and completes it. What if the PushToDb method throws an exception, How can I make sure runtime knows that it's not complete, but rather should be abandoned.

Looking to use async as much as possible for performance.

**Comment by mhoeger** [comment]
Closing issue as your question was answered here. Thanks!
https://stackoverflow.com/questions/48339829/async-programming-and-azure-functions

**Comment by solsolomon** [comment]
This guy shows how to do this... https://www.youtube.com/watch?v=0AiPK_RVDeM

**Comment by SamaneSharifiMonfared** [comment]
I had watched the video suggesting by @solsolomon and it was not even related to this issue.
