### ISSUE TITLE
Function.json mismatch errors occur unless you do a full clean/rebuild

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#664]
There is a significant user impacting issue where function.json files are not being correctly generated unless a full solution clean is performed prior to build.

Environment:
- VS 15.5.4
- Functions and Web Jobs Tools 15.0.40108

Steps to reproduce:
1. Open VS and create a new v1 function app and create a HTTP trigger
2. Do a nuget update to make sure the app is on Microsoft.NET.Sdk.Functions 1.0.7
3. Build and run the app locally - it should work fine.
4. Do a parameter rename for 'req' to 'req2' in the HTTP trigger
5. Hit F5.

Expected result: the function app runs correctly.
Actual result: `error AF003: Missing a trigger argument named 'req2'`

This error occurs because the function.json file was not regenerated. 

Workaround: Clean solution, then rebuild.

The underlying issue is tracked here:
https://github.com/Azure/azure-functions-vs-build-sdk/issues/153

**Comment by reddy6ue** [comment]
I'm using visual studio to create an azure functions project. What is this function.json that everyone keeps talking about? Theat file never gets generated when I create the project. I only see host.json and local.settings.json. 

Manually creating a function.json object has no apparent impact on this visual studio project.

**Comment by paulbatum** [comment]
The file is generated on build, not when you create the project. Its found in the build output folder. It doesnt appear in your solution.

**Comment by reddy6ue** [comment]
Phew! Mystery solved.

**Comment by paulbatum** [comment]
The fix is now available, grab this release of the NuGet: https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.8
