### ISSUE TITLE
The version of Functions on your Azure host does not match the local version.

### ISSUE THREAD

**Issue by petarvucetin** [Azure/Azure-Functions#667]
Azure function runtime 2.0 (beta)

Whenever I publish from VS I am getting below error. Where do I change local settings so that VS does not pop this dialog box every time I publish?

---------------------------
Microsoft Visual Studio
---------------------------
Update Functions Version on Azure

The version of Functions on your Azure host does not match the local version.

The application setting for FUNCTIONS_EXTENSION_VERSION should be updated to "~1".

Update Azure application settings to match local Functions version?
---------------------------
Yes   No   
---------------------------

**Comment by justcla** [comment]
Hi Petar

From engineering:
> If the user is seeing this, then it means the user has their local project targeting net46. 

You can disable the warning by adding the following to your CSProj
`<DisableFunctionExtensionVersionUpdate>true</DisableFunctionExtensionVersionUpdate>`

Alternatively, you could upgrade the project target.

Can you share your CSProj file?

**Comment by petarvucetin** [comment]
@justcla Here is the proj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    <Configurations>Debug;Release;E2E</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\Debug\netstandard2.0\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='E2E|AnyCPU'">
    <OutputPath>bin\e2e\netstandard2.0\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="2.4.0-preview" />
    <PackageReference Include="Microsoft.Azure.KeyVault.Core" Version="2.0.5-preview" />
    <PackageReference Include="Microsoft.Azure.Management.DataFactories" Version="4.13.0" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.1.0-preview" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.1.0-beta2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.7" />
    <PackageReference Include="Polly" Version="5.7.0" />
    <PackageReference Include="RestEase" Version="1.4.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0-preview1-25914-04" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Data.SqlClient">
      <HintPath>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.data.sqlclient\4.4.0\ref\netstandard2.0\System.Data.SqlClient.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Comment by hardikkhandhedia** [comment]
I am also getting the same error. can any one help to resolve?

**Comment by JohnReeson** [comment]
See whether this [so thread](https://stackoverflow.com/questions/49672576/message-update-functions-version-on-azure/49684960#49684960) helps. Note that we better create a new v2 function instead of change targetframework  in `.csproj ` because upgrading of runtime(netframework to netstandard) may cause breaking changes in your code.
