### ISSUE TITLE
Do Dependencies impact performances

### ISSUE THREAD

**Issue by mandarsj** [Azure/Azure-Functions#668]
If I read this documentation
 https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices

it states in the first section about 

A function can become large due to many Node.js dependencies. Importing dependencies can also cause increased load times that result in unexpected timeouts. Dependencies are loaded both explicitly and implicitly. A single module loaded by your code may load its own additional modules.

But this is not clear? which dependencies can impact loading time ? 
for example, if i am referring other projects in the Function App like my Business layer or my Data layer.
to fetch or do crud operations from function trigger. then does that mean, it is also not a good practice?

can someone make it more clearer?

**Comment by MisterJames** [comment]
@mandarsj The question you are asking has an answer that will be language and library specific.

If your business or data layer have small footprints and few (or no) dependencies, you won't have an issue. 

The warning is talking about apps that reference libraries that reference libraries that reference libraries that reference libraries (on so on). If you look at the dependency graph of an application and see a sprawling tree, you have to keep in mind that in order for your function to work it's going to have to load all of those dependencies into memory.

It's also not just reliant on the number of dependencies, but also on the size of them. For instance, a .NET library with many statically created types, or poorly crafted constructors that have I/O bound operations, or a myriad of other bottlenecks can have an impact on your startup time and ultimately cost of your Function execution.

You needn't be worried about shipping code that has 2-3 dependencies in most cases. Also, remember that Azure Functions has a number of assemblies by default in the hosting environment (see [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp) for more).

Hope this helps.
