### ISSUE TITLE
Accessing static files in referenced webapi project

### ISSUE THREAD

**Issue by shyamal890** [Azure/Azure-Functions#669]
Azure function app references a `webApi` project which uses `razorEngine` to build `cshtml` view.

The problem is accessing the `cshtml` file. Till now I was using:

`HostingEnvironment.MapPath("~/Views/templates/") + "test.cshtml";`

to access the file which used to work with `webApi` as a standalone project. Now as a referenced assembly the path evaluates to

`E:\Web\Proj.Func\bin\Debug\net461\test.cshtml`

which doesn't evaluate to be the right path to the `cshtml` file.

How to solve this?

**Comment by shyamal890** [comment]
@justcla @davidebbo @jeffhollan any thoughts on this?

**Comment by davidebbo** [comment]
If you're looking for the root of the user's function files, try `context.FunctionAppDirectory`. Example [here](https://github.com/davidebbo-test/FunctionAppVS2017/blob/e2badeb6d44cf18f20c8fd69e744616028eb1fcc/FunctionAppVS2017/HelloHttp.cs#L39).
