### ISSUE TITLE
Use small VMs when running node.js functions on dedicated plan

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#67]
See https://github.com/Azure/azure-webjobs-sdk-script/issues/917 for context. Until this is resolved, our documentation should make it clear that customers are better off provisioning their node.js based functions on small VMs when using dedicated compute.

**Comment by SyntaxC4** [comment]
Please complete with #77 and #59

**Comment by ggailey777** [comment]
@paulbatum @SyntaxC4 does this note sound OK?

### Use small VMs when using App Service Plan

When creating a function app that uses App Service Plan for your JavaScript functions, we recommend that you use multiple small VMs rather than a medium or large VM. At this point, Functions runs JavaScript functions more efficiently on small VMs; using larger VMs will not produce the expected results.

**Comment by paulbatum** [comment]
@ggailey777 looks good to me.

**Comment by ggailey777** [comment]
Thanks @paulbatum. Just to be as clear as possible, are we recommending plans with less cores and a higher tier (if needed)?

**Comment by paulbatum** [comment]
By higher tier I assume you mean basic/standard/premium? That simply depends on which features the customer wants. It has no bearing on performance (other than the fact that to do larger deployments you sometimes need to move to a higher tier).

**Comment by ggailey777** [comment]
Sorry, I guess I mean to say more instances of a single-core VM. (Instances are affected by tier, right?)

**Comment by paulbatum** [comment]
You could say "single core plan" instead of "small VM". That would more closely match the content on the "choose your pricing tier" page.

**Comment by ggailey777** [comment]
I have tweaked this slightly, which is staged for revidew [here](https://review.docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?branch=pr-en-us-9679#considerations-for-javascript-functions)

**Comment by paulbatum** [comment]
Yep, looks good.
