### ISSUE TITLE
Dependency on MVC

### ISSUE THREAD

**Issue by forki** [Azure/Azure-Functions#671]
Things like https://github.com/mikhailshilkov/tictactoe/blob/master/TicTacToe.Functions/Functions.fs#L37 depend on MVC - that's really really weird. Since we don't use MVC - can we move these helpers to somewhere else?

**Comment by forki** [comment]
@mathewc closed without comment?

**Comment by mathewc** [comment]
I closed this because the linked issue points to problems in https://github.com/mikhailshilkov/tictactoe which doesn't seem Functions related at all. Perhaps I misunderstood? What is the actual Azure Functions issue?

**Comment by forki** [comment]
Things like ObjectResult and ContentResult are the proposed ways to return data. But they live in MVC. Which is a very heavy dependency which we only need to reference for this little thing. Those return types should be put into smaller lib and mvc should depend on that as well.

**Comment by mathewc** [comment]
So this issue is about proposed changes to MVC then? That doesn't concern this repo - not sure what action you want us to take here :)

**Comment by forki** [comment]
No this is something you would need to push. As a user this kind of azure functions relying on MVC is hurting. I don't want to change mvc. I want you to provide a lighter version. If that requires to change mvc then ok. Other solutions would be fine as well.
