### ISSUE TITLE
Timer trigger Function stops scheduling

### ISSUE THREAD

**Issue by sergsalo** [Azure/Azure-Functions#672]
I have a timer trigger function. Should execute every minute. Not sure what causes it to stop being scheduled. But it is not scheduling anymore. 

Function:
 (2018-01-26T00:41:40.260 Function started (Id=7cf0010f-8d2b-4be0-ab78-1a13cf8422d5).

I don't know what causes my function to get into this state, but this isn't the first time its happening.

My function is on consumption plan. 

If I recreate function with different name - it starts working again.

**Comment by davidebbo** [comment]
@sergsalo can you provide a sample time (UTC) at which it did not fire?

**Comment by sergsalo** [comment]
currently happening

**Comment by davidebbo** [comment]
@sergsalo ok, please leave it in that state so we can investigate.

**Comment by davidebbo** [comment]
@sergsalo you have several timer triggered functions. Which one specifically is affected right now?

**Comment by sergsalo** [comment]
workload_balancer

**Comment by sergsalo** [comment]
note: This app was initially published via VSTS online task. But I also published to it via the function tools: 

> func azure functionapp publish xxxxx

**Comment by davidebbo** [comment]
I don't think how it was published matters. The issue appears related to the fact that the app is widely scaled out (due to other functions' activity), and something goes wrong with the 'singleton lock' that's supposed to decide which instance needs to fire the timers.

@mathewc will look into this further.

**Comment by sergsalo** [comment]
you mentioned that app is "widely scaled". Is there a way for us to check that - what is the resource consumption? I understand it is different question, but maybe you can provide some link to a document. thanks.

**Comment by paulbatum** [comment]
Yeah with App Insights its really easy. You can view the current status in the [live metrics view](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-live-stream). If you want historical data you could use a custom query that does a `dcount(cloud_RoleInstance)` on your customMetrics table for the appropriate time range. There's an example of this in the 'Partition Configuration' section of [this blog post](https://blogs.msdn.microsoft.com/appserviceteam/2017/09/19/processing-100000-events-per-second-on-azure-functions/).

**Comment by mathewc** [comment]
@sergsalo I notice from logs that you appear to be using a static host ID set in your host.json config file. What can happen in such cases is if you have a local CLI version running it's using the same ID as your app running in the cloud and this can cause conflicts. The timer relies on acquisition of a blob lease and when using a hardcoded host ID like this any locally running instance will be competing for the lease with instances running in Azure.

Can you make sure you don't have any local versions running? Ideally you'd remove the hard coded host ID completely so local/remote aren't in conflict.

**Comment by sergsalo** [comment]
I removed the id property from host.json. It looks like it is working again. Thanks!

**Comment by davidebbo** [comment]
@sergsalo do you know how you ended up with a hard coded id in the first place? Some old tooling used to do this, but in theory none of the new tools should do this.

**Comment by mathewc** [comment]
Out of curiosity, how did you end up with the id in your host.json? In Azure Functions it's not recommended - setting this is an advanced capability. Our tooling/guidance shouldn't lead to people setting this.

**Comment by sergsalo** [comment]
@davidebbo I am not sure. I think it was done using tooling. I used "func init" to create new function in VS Code. It was created more than a month ago, and maybe the tooling I've used wasn't updated. I didn't add "id" myself (not quite sure of its purpose). If I"ll notice it created again in future - I'll post back to this channel.

**Comment by davidebbo** [comment]
@sergsalo yes, it's probably an old CLI. I just tried with latest (1.0.7), and got an empty host.json (i.e. `{ }`)

**Comment by sergsalo** [comment]
@davidebbo we have two slots - production and staging. The timer function wasn't disabled in staging slot and having that id in host.json caused them to fight for that resource, I think. I guess we will need to disable all the functions in staging slot after deployment is completed.

**Comment by davidebbo** [comment]
So your goal is for the timer function *not* to run in staging?

**Comment by sergsalo** [comment]
yes. We deploy to staging and then swap with production to minimize the down time.
