### ISSUE TITLE
return type unit is not allowed

### ISSUE THREAD

**Issue by forki** [Azure/Azure-Functions#673]
Consider this little function:

    [<FunctionName("Heartbeat")>]
    let heartbeat([<QueueTrigger("heartbeat")>] heartbeat:string, log: Host.TraceWriter) = task {
        let heartbeat = Newtonsoft.Json.JsonConvert.DeserializeObject<Heartbeat>(heartbeat)
        ....
        ()
    }

It gives: 

`Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'Functions.heartbeat' ---> System.InvalidOperationException : Cannot bind parameter '$return' to type Unit&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).`

How are we supposed to do function that only work on a queue and have no return?

**Comment by MikeStall** [comment]
Queue messages are asynchronous. The function itself should be side-effecting - such as writing to storage or queuing another message on output. You can bind a [Queue] to the return value 

You can switch to http trigger if you want a synchronous reply/response pattern.

**Comment by forki** [comment]
I want async. That's fine. I just want no return value.

Am 26.01.2018 19:20 schrieb "Mike Stall" <notifications@github.com>:

**Comment by forki** [comment]
I used similar code with explicit function.json and without attributes and it worked fine. Then I tried to convert to the new style and things broke.

**Comment by cocogorilla** [comment]
I have the same issue.  I started with a C# azure function template, then changed it to an Fsharp project so I could use a compiled model.  I based on task snippet: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-fsharp

I modified to return unit instead of http resonse because, yea, its a queue.

I get the same:

> Cannot bind parameter '$return' to type Unit

**Comment by Elonon** [comment]
I know this issue is old, but I just hit this same problem. It seems to work if you pipe the task computation expression into ``ignore``, but I'm not sure if this is good/safe. 
E.g.
```fsharp
[<FunctionName("Heartbeat")>]
let heartbeat([<QueueTrigger("heartbeat")>] heartbeat:string, log: Host.TraceWriter) = task {
    let heartbeat = Newtonsoft.Json.JsonConvert.DeserializeObject<Heartbeat>(heartbeat)
    ....
    ()
} |> ignore
```

Has anyone found a better way?

**Comment by forki** [comment]
I don't think it's a valid workaround. You need to await the task or
otherwise the runtime may just throw it away

Am Mo., 14. Jan. 2019, 22:19 hat Elonon <notifications@github.com>
geschrieben:

**Comment by Elonon** [comment]
Sorry, I updated my original comment. You're right that piping to ignore isn't a good idea. But upcasting to Task should be fine.

**Comment by forki** [comment]
Yes a cast will probably do work.

Am Mo., 14. Jan. 2019, 22:42 hat Elonon <notifications@github.com>
geschrieben:

**Comment by mathewc** [comment]
Fixed via https://github.com/Azure/azure-functions-host/issues/3171
