### ISSUE TITLE
Referencing an ASP.NET Core (netcoreapp2.0) project from a Functions App (netstandard2.0) project

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/Azure-Functions#674]
In order to re-use code from an existing ASP.NET Core MVC/Web API project we need to reference that project from a Functions app.

However, we get this error:

![image](https://user-images.githubusercontent.com/888718/35474465-e0492b66-038e-11e8-8b8d-1a38860bd6f4.png)

Thanks for any insights.

VS 2017 15.6.0 Preview 3.0
Azure Functions tools 15.0.40118.0
Azure Functions SDK 1.0.7

**Comment by MV10** [comment]
I don't think it's possible to create references in that direction.
.NET Core is a superset of the APIs defined by .NET Standard.

**Comment by ChristianWeyer** [comment]
OK, that is what I thought.
When trying to use .NET Standard libs, we are running into other roadblocks:
https://github.com/Azure/azure-webjobs-sdk-script/issues/2364

Thanks and cheers.
