### ISSUE TITLE
Suggestion: Tooling or Runtime Enhancement to Test/Warn for Property Visibility Settings

### ISSUE THREAD

**Issue by MisterJames** [Azure/Azure-Functions#675]
I've grown accustomed to using the "Generate Property" shortcut in Visual Studio, which is a great feature that does it's best to set property visibility.

When building types in a c# Functions project using non-typed serialization, this can be problematic. I'm in VS 2017 15.5.2. Here's my scenario:

 - Create a class as a placeholder
 - Start coding the function using queue inputs and outputs (triggers, output params)
 - Example output param: `[Queue("provision-user-complete")] out ProvisioningInfo provisioningInfo`
 - Write the body of the code, assign a value to a property that doesn't exist
 - Use VS shortcut to "Generate Property", which results in `internal` setter
 - Create a second function that reads from the output queue, in this case `provision-user-complete`
 - The second function will not populate the data as the setter is internal

![image](https://user-images.githubusercontent.com/1197383/35520088-a273fcb4-04db-11e8-8d5f-fb96c5d5a5dc.png)

My suggestion is to add a check in the tooling or runtime to output a warning on such properties. I.E., the queue binding could see that there is a JSON property there with the same name as in the class, but because the class has an internal setter, it could warn.  

I like the tooling approach as it could give red squigglies under the `QueueTrigger` property, for instance, and let the coder know there could be unintended data loss.

Ran into this with a workflow that chains together 8 functions/queues and it took me a while to track down the source. I feel like Visual Studio is doing the correct thing. I'm also not a huge fan of having the types in the same project as the Functions app (a separate project would change VS's assumptions about `internal`). But I do think this is something folks could trip on.

**Comment by ColbyTresness** [comment]
Please open this as a developer community request https://developercommunity.visualstudio.com/spaces/8/index.html
