### ISSUE TITLE
Update Azure Functions repo names

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#678]
Several of the functions related repositories have confusing names. Below is a proposed update.

Rename:
- azure-webjobs-sdk-script -> azure-functions-host
- azure-webjobs-sdk-templates -> azure-functions-templates
- azure-functions-cli -> azure-functions-core-tools

Keep as is:
- azure-webjobs-sdk
- azure-webjobs-sdk-extensions

**Comment by davidebbo** [comment]
These seem like the best name (since we can't use azure-functions-runtime 😢).

**Comment by paulbatum** [comment]
@ahmelsayed Does this CLI rename sound good to you?

**Comment by ahmelsayed** [comment]
yep it looks good

**Comment by paulbatum** [comment]
Done!
