### ISSUE TITLE
Service Bus Topic Trigger goes to Sleep - Messages are not picked up real-time by Function API

### ISSUE THREAD

**Issue by ChandanaWije** [Azure/Azure-Functions#681]
**Background for the project:**

**Function API:** .Net 4.6.1 class library Function API with Service Bus configured Topic Single Subscription Triggered

**Service Bus:** With single Topic - single subscription with filter configuration for that given subscription.

**Configurations:** The Service Bus (Standard tier) and the Azure Functions (Consumption plan) are in the same Resource Group in 'Australia East'

**Function Process:** Messages that are comes into to Service Bus Topic Subscription should be picked up by Function API in real-time. 

**Problem (Issue):** Messages that are arrive to service bus are not getting triggered real-time. Some messages are getting picked by function API without a delay, but sometimes trigger goes to sleep before picking up messages to function API.

Similar problem discussed in #350 

Adding @tohling  @bwwilliam

If you need more info can email Azure endpoints details.

Many Thanks,
Chandana

**Comment by tohling** [comment]
Could you provide us details about your Function execution directly or [indirectly](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)? We will need the following:

1. Function App Name
2. Region
3. Function Name
4. Time range when issue(s) occured.

**Comment by ChandanaWije** [comment]
Hi @tohling 
Thanks you for the quick response.
Here you go with the details for the function.

**UTC execution time:** 2018-02-05T02:08:13.919
**execution Id value:** 8bccb669-334b-42fc-bdc7-a98358364ada
**Region :** Australia East

Many Thanks, Chandana

**Comment by tohling** [comment]
@ChandanaWije , our internal logs indicate that no triggers were registered for your Function App.  IN order for Azure Functions to monitor the ServiceBus endpoint for messages, all active triggers in your Function App have to be correctly registered.  

In the typical dev workflow, this is transparent to you as a user, however, there are exceptions if the code-editing or deployment workflow was done out-of-band as documented here:

https://github.com/Azure/Azure-Functions/issues/210

Kindly re-sync your triggers as mentioned by @lindydonna in the link above.  The easiest approach is to resync the triggers through the Azure Portal.  That should cause your triggers to be registered and monitored from here on out and the issue will go away.  Feel free to update this thread when you have done so and I can double-check to confirm that for you as well.

**Comment by ChandanaWije** [comment]
@tohling Thank you for the help. With you direction we manage to get the function trigger to pickup messages within the service bus in real-time.
