### ISSUE TITLE
publish to local Azure Function runtime

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/Azure-Functions#682]
_From @grahamehorner on January 26, 2018 20:34_

not sure if this is the correct place; but I'm having issues when attempting to publish to a local AzureFunctions runtime when using VS 15.5.5 there is no option other than AzureFunctions, Folder or Import Profile; none of these seem to work for AzureFunction Runtime Deployments and the Import Profile does nothing at all no dialog ... 

_Copied from original issue: Azure/azure-functions-vs-build-sdk#159_

**Comment by apwestgarth** [comment]
@grahamehorner I am unable to reproduce, when I choose to import profile I am presented with a file browser dialog and am able to import the profile.  Post this I am hitting an issue on publish but your issue appears to be with the VSIX so I'd like to confirm.

**Comment by vijayrkn** [comment]
@apwestgarth - Is it the untrusted certificate issue that you are running into during publish?

**Comment by grahamehorner** [comment]
@apwestgarth took a little while click around as its not clear that selecting  'Import Profile' then need you to click 'create' ... ? so this issue can be closed; but I do have an different issue post publish where the IIS process seems to crash ?

**Comment by jvano** [comment]
@grahamehorner - I'm seeing you have a different issue. I'm going to close this issue but feel free to create a new one if the post publishing error is still happening.
