### ISSUE TITLE
Cant add EventHubTrigger from Azure portal (v2 runtime)

### ISSUE THREAD

**Issue by craig006** [Azure/Azure-Functions#685]
Hi sorry if this is at the wrong spot, I can move it to a better repo on your recommendation.

Runtime version: 2.0.11415.0 (beta)

I cant seem to get an EventHubTrigger function working. After many failed attempts at trying to create one from attributes and code, I fell back to manually trying to creating one on the portal to see if the setup would highlight any issues... But manually creating one does not seem possible, this is the problem I'm experiencing.

I hit the add button to manually add a function:
![screen shot 2018-02-09 at 14 11 16](https://user-images.githubusercontent.com/23329523/36027253-26fc6848-0da3-11e8-9d61-d029723f6836.png)

After that I select "Event hub trigger"
![screen shot 2018-02-09 at 14 09 25](https://user-images.githubusercontent.com/23329523/36027219-0ccea17a-0da3-11e8-9e75-d67363874ba3.png)

I'm then presented with this dialog, where I select install:
![screen shot 2018-02-09 at 14 09 38](https://user-images.githubusercontent.com/23329523/36027291-505898a6-0da3-11e8-88ff-c85c4f44f527.png)

The process runs for a few minutes
![screen shot 2018-02-09 at 14 16 47](https://user-images.githubusercontent.com/23329523/36027425-e50cec18-0da3-11e8-9267-9c933e76c371.png)

And finally results in this error:

We are not able to install runtime extension. Install id 1ca3291d-1865-4d72-95b8-6451b92fbcc1
Session Id: d958af905c5a4433baa064d6de1a1314
Timestamp: 2018-02-09T11:58:51.396Z

Do EventhubTriggers work on the Beta runtime yet? I have seem some other issues but no conclusive yes/no it works/does not work.

Any help appreciated!

**Comment by craig006** [comment]
I managed to get around this by creating a fresh functions app with no existing functions. This allowed me to add the event hub extension which in turn made all my eventhub functions work (after re-adding them to this functions app).

On a side note the  SDK that generates function.json from attributes does not generate correctly for eventhub triggers. It also adds some extra properties like "Generatedby" that break the triggers until removed.

**Comment by soninaren** [comment]
This is fixed now. There is a template for EventHubTrigger in Visual studio.

**Comment by Khayralla** [comment]
I got the same error:
error:
We are not able to install runtime extension. Install id 3e11851b-eae9-45b5-807e-c4183ff69a2a 
Session Id: 1cfe3101cfcb44ada28310eeac0879e2
Timestamp: 2018-05-14T21:29:58.098Z

**Comment by soninaren** [comment]
Can you perform the following steps. This is to ensure any existing binaries are not causing installation issues.

1. Stop the function app.
2. Access kudu console through Platform Features -> Advanced Tools -> Debug Console (cmd)
3. Navigate to d:\home\site\wwwroot
4. Delete the bin directory
5. Delete extensions.csproj file.
6. Start the function app
7. Run through installation steps again.

**Comment by mukana-lahtelat** [comment]
Getting the same error. I'm using a Function app with Linux preview for OS, is the event hub extension only working for Windows?

**Comment by SachaLhopital** [comment]
Hi, I am also facing the same issue on the portal with a Linux Preview (for EventHub of course)
