### ISSUE TITLE
Blob storage file corrupted

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [Azure/Azure-Functions#689]
Hi,

  I have tried to upload file to Azure blob storage using Azure Function but the file got corrupted while i get the file from blob. I have attached the code in image format both angular and Azure function.

![1 fileupload](https://user-images.githubusercontent.com/16976667/36148132-dd8144e0-10e0-11e8-9ff5-11d5371ad9d7.PNG)
![2 subfunction](https://user-images.githubusercontent.com/16976667/36148133-ddbf00aa-10e0-11e8-96af-06c0cf00cdc0.PNG)
![3 htmlcode](https://user-images.githubusercontent.com/16976667/36148134-ddf69bfa-10e0-11e8-95a4-572bbeeaf630.PNG)
![4 typescriptcode](https://user-images.githubusercontent.com/16976667/36148135-de2f6430-10e0-11e8-8789-06d5c8150586.PNG)

**Comment by ColbyTresness** [comment]
Closing as I don't believe this is actionable/it's from a while ago. Please reopen if you're still experiencing issues.
