### ISSUE TITLE
Incorrect lookup path for Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll

### ISSUE THREAD

**Issue by xperiandri** [Azure/Azure-Functions#690]
## Issue
```
Error	MSB4062	The "GenerateFunctionsExtensionsMetadata" task could not be loaded from the assembly 
C:\Users\Xperi\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\build\..\tools\net46\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll. 
Could not load file or assembly 
'file:///C:\Users\Xperi\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\tools\net46\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll'
 or one of its dependencies. The system cannot find the file specified. Confirm that the 
<UsingTask> declaration is correct, that the assembly and all its dependencies are available, 
and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
PaketFunctions
C:\Users\Xperi\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets	16
```

## Repro steps

1. Clone https://github.com/xperiandri/azure-functions-fsharp-examples
2. Open `8-paket\PaketFunctions.sln`
3. Build solution
4. Get error in Visual Studio

Error happens because there is no folder `net46` in `microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\tools`. Only `netstandard2.0`.
And even if I copy `netstandard2.0` to `net46` error remains.

If you build with `dotnet build` command then it finishes successfully

**Comment by felipecruz91** [comment]
Having the same issue here... Any updates on this?

**Comment by ColbyTresness** [comment]
Sorry for the long delay on this, are you still experiencing the above issue?

**Comment by ColbyTresness** [comment]
Closing due to lack of response. Please reopen if still relevant.

**Comment by AartBluestoke** [comment]
You can have this problem if you have a visual studio solution with multiple projects, with different versions of azure functions present ; in my case i had .29 in one project and .28 in another.
