### ISSUE TITLE
Speed up extension installation for functions V2 portal scenarios

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#697]
Since most templates now need an extension to be installed, the speed of installing the first extension impacts the user experience. Right now it can take several minutes because there is no fallback cache on the worker and 800mb of NuGets is pulled into azure files. We need the fallback cache to be present on the worker or some other solution that makes extension installation take less than 30 seconds.

**Comment by paulbatum** [comment]
@soninaren We can close this right?

**Comment by paulbatum** [comment]
Do we need any followup issues to track work to make sure we keep the fallback cache up to date as part of our engineering processes?

**Comment by soninaren** [comment]
We can close this one. Will need to add generating and deploying fallback folder as a part of the documentation for extension/nuget release process. Additionally we can automate the fallback folder generation process
