### ISSUE TITLE
Azure function being called multiple times

### ISSUE THREAD

**Issue by rakeshchauhan91** [Azure/Azure-Functions#699]
i am using Azure function to listen to Eventhubtrigers. problem is that my azure function gets called many times and with old data which i have sent to event hub how  can i mark it read so that i don't stays in storage and i don't read all the time for the retention time.  As of now i was sending json as string. my eventhub is attached to Azure storage account

**Comment by ahmelsayed** [comment]
/cc @MikeStall 

are there errors processing some of the eventhubs data? my understanding is that eventhub triggers will retrieve a batch of events at once and process all of it. If they were all successful, it should make a checkpoint and not reprocess old events. Maybe checkpointing is failing for some reason?

**Comment by ColbyTresness** [comment]
Closing due to lack of customer response. please reopen if you're still experiencing issues.
