### ISSUE TITLE
Quickstart/Get started UI updates

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#7]
New Photos of recent Portal updates

**Comment by christopheranderson** [comment]
If this needs to be split up because there is a lot of stuff, let's split up the work.

**Comment by SyntaxC4** [comment]
We have an issue here as 0.7 changed a bunch of things that we have a lot of customer feedback about. There is a meeting this after to figure out what we need to address GA.

**Comment by lindydonna** [comment]
What does this work item include? Is it just screenshots or is a video?

**Comment by wesmc7777** [comment]
@lindydonna  To my knowledge, just screen shots and maybe some related instructions that may change along with the UI.

**Comment by wesmc7777** [comment]
Glenn already refreshed the following:

https://github.com/Microsoft/azure-docs-pr/commit/20009ee8866e2b2858eb0bf1f289e70dc1f29c83#diff-3d7b7e1f75c1aa028493ec657ad1b11c

**Comment by wesmc7777** [comment]
@ggailey777  Glenn do you want to take this?

**Comment by ggailey777** [comment]
I have refreshed UI on the 4 get started topics. I think we need a work item for video updates as those are a significant investment.
