### ISSUE TITLE
Remove mention of Java from Azure Functions Overview

### ISSUE THREAD

**Issue by tohling** [Azure/Azure-Functions#70]
On page https://docs.microsoft.com/en-us/azure/azure-functions/functions-overview

There is mention of Java being the supported language.  Customers on Twitter are asking now asking how they can setup a Java Function and have also started adding the #Java hashtag with their Azure Functions tweet.  We should remove the mention of Java from our docs.

**Comment by lindydonna** [comment]
Fixed now

**Comment by travis5555** [comment]
does this mean Java support is not on the roadmap for Functions?

**Comment by tohling** [comment]
@travis5555, no, it just means that Java is **currently** not supported and should not be in the documentation.

**Comment by travis5555** [comment]
cool, thank you! I have been anxiously awaiting Java support within Functions so I'll stay tuned for any updates around when it might be available.

**Comment by ranjan545486** [comment]
@tohling, when do you think the Java support will be there within Functions? We are explicitly looking for this support. I know there is a hack ( https://github.com/Azure/azure-webjobs-sdk-script/wiki/Creating-a-Java-Azure-Function ) to do that but we need a native support.

**Comment by lindydonna** [comment]
@ranjan545486 We don't have any dates to share, other than the fact that we're working on it. When we have a public preview beyond the manual workaround, we'll announce on the App Service Team blog. https://blogs.msdn.microsoft.com/appserviceteam/
