### ISSUE TITLE
CosmosdbTrigger  is not being called

### ISSUE THREAD

**Issue by rakeshchauhan91** [Azure/Azure-Functions#700]
Hi 
i am using CosmosdbTrigger to Cosmosdb Database document collection.  But its not getting called no errrors when i run it.  i have given storage connectionstring & cosmosdb connectionstring in localsettings. 

>  [FunctionName("ConnectionMonitor")]
        public static void Run([CosmosDBTrigger(
            databaseName: "ToDoList",
            collectionName: "Connections",
            ConnectionStringSetting = "cnConnection",
            LeaseCollectionName = "leases")]IReadOnlyList<Document> input, TraceWriter log)
        {

**Comment by ahmelsayed** [comment]
/cc @brettsam @ealsur 

are you seeing the function being correctly loaded in the console log output?

**Comment by rakeshchauhan91** [comment]
Yes loaded successfully but giving error. 


 A ScriptHost error has occurred
[03-03-2018 03:47:27] Exception while executing function: ConnectionMonitor. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'input'. Microsoft.Azure.WebJobs.Extensions.DocumentDB: Binding can only be done with IReadOnlyList<Document> or JArray
[03-03-2018 03:47:27] Parameter name: type.
[03-03-2018 03:47:27] Exception while executing function: ConnectionMonitor
[03-03-2018 03:47:27] Exception while executing function: ConnectionMonitor. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'input'. Microsoft.Azure.WebJobs.Extensions.DocumentDB: Binding can only be done with IReadOnlyList<Document> or JArray

**Comment by brettsam** [comment]
Your parameter needs to be of type `IReadOnlyList<Document>`, not `IReadOnlyList`. 

Our error message should say that, but it looks wrong above. Here's where we throw: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/v2.x/src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerValueBinder.cs#L24

Yet the text above shows:
> Exception while executing function: ConnectionMonitor. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'input'. Microsoft.Azure.WebJobs.Extensions.DocumentDB: Binding can only be done with IReadOnlyList or JArray

@rakeshchauhan91, can you check if the output has the `IReadOnlyList<Document>` in the error message? I wonder if github just formatted it wrong when it was pasted.

**Comment by ealsur** [comment]
@rakeshchauhan91 Are you using the DocumentDB SDK package that comes with the Functions Extension (1.13.2) or are you using another version?

**Comment by rakeshchauhan91** [comment]
@ealsur yes when i downgraded 1.20 to 1.13.2 then function got fired and i got the document from cosmosdb as well. 

@brettsam  yes thanks for pointing out  i have changed to  

> IReadOnlyList<Document> 
and it worked. but wondering will it work with 1.20 version DocumentDB.

**Comment by ealsur** [comment]
As far as I know (@brettsam can correct me), the Functions runtime does not support binding redirects and will try to run on the 1.13.2 version, even though the code is compiled against 1.20. The type check might fail at runtime due to this.

**Comment by syedhassaanahmed** [comment]
@ealsur I really want to use `ConsistentPrefix` consistency level but it doesn't exist in 1.13.2. Would love the Functions runtime to support new version of Cosmos DB SDK.

**Comment by ealsur** [comment]
@syedhassaanahmed We updated the SDK on Functions V2. V1 is locked on 1.13.2.

**Comment by ColbyTresness** [comment]
Closing as it appears this has been resolved. Please reopen if not.
