### ISSUE TITLE
Azure functions on Premises - Why use a SQL Database configuration for connection?

### ISSUE THREAD

**Issue by israelcr** [Azure/Azure-Functions#701]
Do Yo u know what is the pourpose of using Database Configuration (Connection),
for Azure functions on Premises (runtime V2).

**Comment by ahmelsayed** [comment]
as I mentioned on the forums 

> It just acts as a data store for all the data that the solution needs to function. Accounts (usernames, passwords, profiles), subscriptions, functions list, etc. All that information need to be saved in some data store.

also tagging @apwestgarth

**Comment by israelcr** [comment]
Thank You for Your quick response.

Do you know if there is any reference point with the documentation and more details on this topic?

**Comment by israelcr** [comment]
Thank You for Your quick response.

Do you know if there is any reference point with the documentation and more details on this topic?

**Comment by apwestgarth** [comment]
@israelcr what further details are you requesting?

**Comment by ColbyTresness** [comment]
Closing this due to lack of customer response
