### ISSUE TITLE
Version Conflict for Newtonsoft.Json and System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by justinkneff** [Azure/Azure-Functions#704]
I've been implementing the manual validation of tokens in an Azure Function using System.IdentityModel.Tokens.Jwt. Similar to the Azure example code for Manual Validation of JWT Tokens. When installing the latest Microsoft.NET.Sdk.Functions it doesn't have compatibility with the latest System.IdentityModel.Tokens.Jwt package because of the constraints listed below with Newtonsoft.Json.

> Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue. 
>  AzureFunctionsProject -> System.IdentityModel.Tokens.Jwt 5.2.1 -> Newtonsoft.Json (>= 10.0.1) 
>  AzureFunctionsProject -> Microsoft.NET.Sdk.Functions 1.0.8 -> Newtonsoft.Json (= 9.0.1).

The workaround I have for now is to force install a different version.  System.IdentityModel.Tokens.Jwt 5.2.0-preview1-408290725. 
Is there any concerns with this workaround using the preview release of the Jwt tokens?
Is there any known estimate resolving the compatibility between the two?

**Comment by cgillum** [comment]
Have you tried adding an explicit nuget reference to Newtonsoft.Json 10.0.1 to your .csproj file?

```xml
<PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
```

**Comment by SimonCropp** [comment]
@cgillum can you point to some doco that explicitly states newtonsoft 10 (and 11) are supported. and what if any extra changes are required to get it working.

**Comment by cgillum** [comment]
I am not aware of any such docs - this was merely a suggestion. Does it not work?

**Comment by cgillum** [comment]
@SimonCropp There is a lot of context missing here and I think it's quite reasonable to ask clarifying questions rather than relying on assumptions. I suggest we focus on this particular issue rather than having meta-discussions about internal engineering procedures which I may or may not be involved in. If you're having a similar issue, I'd love to hear about it and make sure it's getting the attention it needs.

**Comment by SimonCropp** [comment]
Thanks for spening the time to follow up. 

I dont have a specific issue as i am not currently using azure functions. I am evaluating it for future projects. As part of this evaluation i had discussions with others who had experimented with it. One concern i heard from multiple sources was the architecture/approach to managing app domains and the effect on assembly loading and dependency versioning. This issue was one i was pointed to. 

So without some clarity around the support of dependencies and bersioning, and confidence that you proactively verify these complexities, i am wary of investing too much time in this stack. 

Hence me asking about docs and engineering practices.

**Comment by justinkneff** [comment]
@SimonCropp 
I do versioning with the recommendations of[ Jason Roberts in his blog post](http://dontcodetired.com/blog/post/Creating-Versioned-APIs-with-Azure-Functions-an-Proxies). You could also do the Global Assembly Cache versioning (GAC). But that doesnt work well when resolving dependencies through [Dependency Injection](https://github.com/BorisWilhelms/azure-function-dependency-injection) if certain services don't exist. But overall I haven't had any issues besides the above question.

**Comment by justinkneff** [comment]
@cgillum when adding the above Newtonsoft reference in my csproj file I get warnings in my function at build time and internal exceptions at runtime.

> AzureFunctionsProject.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.NET.Sdk.Functions 1.0.13 requires Newtonsoft.Json (= 9.0.1) but version Newtonsoft.Json 10.0.1 was resolved.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

runtime exception:

> Exception while executing function: AzureFunctionsProject -> An unexpected exception occurred while binding a dynamic operation","errorDetails":"Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: AzureFunctionsProject ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException : An unexpected exception occurred while binding a dynamic operation

**Comment by justinkneff** [comment]
I dug a little deeper and I got the following exception 

>  Exception while executing function: Matrix. Microsoft.Azure.WebJobs.Host: [A]Newtonsoft.Json.Linq.JObject cannot be cast to [B]Newtonsoft.Json.Linq.JObject. Type A originates from 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' in the context 'Default' at location 'C:\Users\[Account]\AppData\Local\Azure.Functions.Cli\1.0.10\Newtonsoft.Json.dll'. Type B originates from 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' in the context 'LoadFrom' at location '[ProjectPath]\bin\Debug\net461\bin\Newtonsoft.Json.dll'.

**Comment by FeynmanFan** [comment]
Did you ever resolve this issue? I'm dealing with the same problem.

**Comment by justinkneff** [comment]
No i haven't. Just the above mentioned specific versions.

**Comment by FeynmanFan** [comment]
We're trying to sort it out on SO if you're interested:

https://stackoverflow.com/questions/50457268/how-can-i-resolve-this-newtonsoft-version-conflict

**Comment by JohnReeson** [comment]
@justinkneff Find one solution, you can have a try.

In `dynamic data = await req.Content.ReadAsAsync<object>();`, if we sent request content in `application/json` format, content is internally converted to JObject(Newtonsoft.Json v9) by host. While in `Dictionary<string, object> paramsDictionary = ((JObject)data).ToObject<Dictionary<string, object>>();`, we explicitly use JObject(v11) to cast it. Then error occurs.

So just change the ReadAsAsync<object> to ReadAsAsync<JObject>(), request content will be processed using v11.

**Comment by ColbyTresness** [comment]
I think this was resolved on the linked SO post, but also, this category of problems has been resolved with Azure Functions 2.x. Please reopen if you're still experiencing issues.
