### ISSUE TITLE
App Insights integration with existing Function App 

### ISSUE THREAD

**Issue by masterarun** [Azure/Azure-Functions#706]
Live Metrics Stream not working, When I enable App Insights integration to existing Function App with below steps.

1. Create an Application Insights instance.
  1.1 Application type should be set to General
  1.2 Grab the instrumentation key
2. Update your Function App’s settings
  2.1 Add App Setting – APPINSIGHTS_INSTRUMENTATIONKEY = {Instrumentation Key}

It says 'Not available: your app is offline or using an older SDK'

When I enable App Insights while creating Function App, its populating 'Live Metrics Stream' as expected.

Is there any known issue? Or I am missing something here.

**Comment by cgillum** [comment]
Are you seeing any metrics at all in your App Insights instance when you configure it via the app setting? It would be good to rule out an invalid/incorrect instrumentation key.

**Comment by mcollier** [comment]
I've noticed this issue with Live Metrics Stream when using a v2 Function app. I do see data in Application Insights Analytics and Search.

**Comment by masterarun** [comment]
I can see data in Analytics(requests / traces, etc...)  in my App Insights instance. Only Live Metrics Stream not available.

Function Runtime version: 2.0.11587.0 (beta)
Binding Type : blobTrigger

**Comment by leftside** [comment]
The Live Metrics Stream tab isn't available for me. I see Application map, Smart Detection, Metrics Explorer, Metrics (preview), Search, Availability, etc.

To the OP - I had a similar problem. Make sure you are using the correct AI key  within your Function App settings.

![ai](https://user-images.githubusercontent.com/4562114/37732831-75ef78a8-2d03-11e8-98c3-1eb1e96102f0.jpg)

**Comment by ColbyTresness** [comment]
Are you still experiencing this issue? Sorry for the long delay.

**Comment by ColbyTresness** [comment]
Closing due to lack of response. Please reopen if still experiencing issue.

**Comment by umer990** [comment]
Remove the app insight Guid from configuration of function app and then go to Function app monitor link and Press configure button to select or create an application insight
