### ISSUE TITLE
Azure functions on Premises - Why use a Docker container?

### ISSUE THREAD

**Issue by israelcr** [Azure/Azure-Functions#707]
Do You know what is the purpose of using Docker container, for Azure functions on Premises (runtime V2).

**Comment by cgillum** [comment]
I suspect it's the same reason you might want to use a docker container for anything - you can test and develop your functions in the same OS context that you deploy it to. When deploying directly to the OS, you're not guaranteed to have all the dependencies and configuration that you had on your development OS.

**Comment by israelcr** [comment]
Thank You for Your quick answer, I appreciate this comment.

**Comment by cgillum** [comment]
No problem. :)
