### ISSUE TITLE
Support Functions Portal running on an ILB ASE

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#71]
The Azure Functions portal experience doesn't currently don't work on an ILB ASE. This issue is to track the feature request.

**Comment by gregjhogan** [comment]
@lindydonna what do you mean it currently doesn't work?  We deployed a simple function app to an ILB ASE and it works just fine.  Are there specific features that don't work?  Thanks!

**Comment by lindydonna** [comment]
What we found was that the ILB was having problems accessing the functions editor, but perhaps that was a problem with the environment we were testing in (perhaps the browser didn't have the right permissions). Thanks for the info, I'll follow up.

**Comment by gregjhogan** [comment]
@lindydonna so that is a UI issue?  Are there non-UI issues?  The title seemed much more broad than what you mentioned (e.g. you can't run functions at all on an ILB ASE).  I haven't run into any issues yet running functions on an ILB ASE, but I haven't used the UI (since we limit people to the RBAC reader role).

**Comment by gregjhogan** [comment]
How is this different than projectkudu/AzureFunctionsPortal#793?

**Comment by lindydonna** [comment]
@gregjhogan The RBAC reader role issue is separate from ILB ASE.

The Functions runtime should work fine on an ILB ASE. For the portal, did you set up an SSL cert with SCM in SAN, and then access the portal from within the ILB VNET?

**Comment by gregjhogan** [comment]
@lindydonna we automate deployments using the kudu API.  But now I understand what you are talking about.  Thanks!

**Comment by KaiWalter** [comment]
I deployed a Function App into an ILB ASE, added functionapp.custom.domain and functionapp.scm.custom.domain to my local hosts. file. With that I see the empty Function App when opening in the browser.
However when opening the Function App in the Portal I get
Error:
We are unable to access your function keys. If the error persists, please contact support.

**Comment by ahmelsayed** [comment]
@KaiWalter what do you get if you go to `https://functionapp.scm.custom.domain ` and `https://functionapp.custom.domain ` in your browser? are you seeing a cert warning?

**Comment by KaiWalter** [comment]
@ahmelsayed with `https://functionapp.custom.domain` I get "Your Function App is up and running", with `https://functionapp.scm.custom.domain` I'm requested to enter a user and password

[here is how I created the Function App in the ILB ASE and what I tried already](https://github.com/KaiWalter/ARM-FunctionApp-in-ILBASE-SelfSignedCert)

**Comment by ahmelsayed** [comment]
so you have valid certs for these domains? The reason I ask is that the portal talks directly to these end points of your functions. If there is a cert error, and you haven't accepted it, then any XHR sent by the portal will be failed automatically by the browser. However if you have a valid cert and still seeing the portal not working with your ILB ASE, can you share your app name or a session id you get from the portal along with the errors?

**Comment by KaiWalter** [comment]
name is zeissesbdevnl 
Session Id: afe2a91c33ae4c0f87fe89879f727f66
Timestamp: 2017-05-04T03:40:36.215Z

I do not have to accept the certificate in the browser as I have added the certificate to the Trusted Root CA of my jump VM.
 If you like more details or access to the test/jump VM we should put do on another/private channel.

@ahmelsayed thanks for looking into it

**Comment by lindydonna** [comment]
This is now available. See https://github.com/Azure/Azure-Functions/issues/377 for configuration steps.

**Comment by amararam** [comment]
The RBAC reader role is not suporting for azure functions   could you please provide the solutions how to work   RBAC reader role  for azure function
