### ISSUE TITLE
Publish Azure Functions with Consumption Plan from Visual Studio

### ISSUE THREAD

**Issue by TclasenITVT** [Azure/Azure-Functions#710]
I am just wondering why there is no option to publish my Azure Function (C# Compiled) using a Consumption Plan when doing the right click publish inside Visual Studio 2017 15.4.2. Is that because I don't use the .csx way of creating a function?

**Comment by cgillum** [comment]
You can definitely public C# compiled functions to the Consumption plan. I do this all the time (I've never done it with csx).

A few questions to hopefully narrow down the problem:
1. Have you tried upgrading to the latest version of Visual Studio? The tooling for Azure Functions is evolving rapidly.
2. Have you signed-in to your Azure-enabled account in Visual Studio?
3. Are you able to publish simple web apps (not Function Apps) to Azure?

**Comment by cgillum** [comment]
Also, have you installed the `Microsoft.Net.Sdk.Functions` NuGet package?

**Comment by TclasenITVT** [comment]
For the Nuget Package
![image](https://user-images.githubusercontent.com/35216119/37198098-6b3b5fc4-237d-11e8-908a-00359ae2e40e.png)

Visual Studio Publishing 
![image](https://user-images.githubusercontent.com/35216119/37198122-7d4d6d42-237d-11e8-9caa-62750dc13f57.PNG)
![image](https://user-images.githubusercontent.com/35216119/37198130-89268824-237d-11e8-8ec1-08ae85bfd1c4.PNG)

**Comment by jhueppauff** [comment]
I think you need to download the publish settings.
![grafik](https://user-images.githubusercontent.com/20532954/37229659-00a9eb68-23e5-11e8-90dd-19e73ea4dd08.png)

**Comment by TclasenITVT** [comment]
@jhueppauff  but that would force me to create a function in Azure first. I would prefer to create the resource from the Visual Studio.

**Comment by TclasenITVT** [comment]
![publish15 6 3](https://user-images.githubusercontent.com/35216119/37658404-bb64186e-2c4d-11e8-91f6-cf87c07b193f.PNG)
I updated my Visual Studio but there is still no option for a consumption plan deployment.

**Comment by aherrick** [comment]
@TclasenITVT @cgillum I'm also seeing this behavior in VS2017. I can only publish my Azure Function project from VS to an App Service plan. Same screenshots from above. 

Can you not publish to a consumption plan from VS?

**Comment by aherrick** [comment]
I got around this by creating Consumption in Azure first, then downloading the Publish Profile. Seems odd there isn't away to crate Consumption from VS.

**Comment by jhueppauff** [comment]
I updated to the latest version (15.0.40405.0) of the Azure Functions and Web Job Tools for VS. 
Within the publish setting I do have now the option to publish to a consumption plan.
![unbenannt](https://user-images.githubusercontent.com/20532954/38636788-86f22d22-3dc9-11e8-8374-1244444b2e2e.png)
