### ISSUE TITLE
Link Does Not Provide Expected Content

### ISSUE THREAD

**Issue by Mike-EEE** [Azure/Azure-Functions#724]
- For issues with the Functions Visual Studio tooling, provide detailed steps to reproduce, including details about your environment (OS, VS version, etc)

Hello there.  In creating my first Azure Function, I believe I found an issue.  Clicking the link in the lower left of this screen:
![](https://docs.microsoft.com/en-us/azure/includes/media/functions-vstools-create/functions-vstools-add-new-function.png)

Takes you to here:
https://docs.microsoft.com/en-us/visualstudio/?AzureFunctions

Where there is no mention of Azure Functions. Additionally, typing in "Azure Functions" in the top right search bar of this URL results in the following page:
https://docs.microsoft.com/en-us/search/index?search=Azure+Functions&scope=VS+IDE

Where there is no mention of Azure Functions, either.

Thought I would bring this up to see if there is something wrong here and/or if there is something I am doing incorrectly.  Thank you for any assistance and/or consideration!

**Comment by pragnagopa** [comment]
Thanks for reporting. 
/cc: @soninaren

**Comment by ggailey777** [comment]
We should probably be linking to here: <https://docs.microsoft.com/azure/azure-functions/functions-develop-vs>

**Comment by ColbyTresness** [comment]
This is fixed.
