### ISSUE TITLE
Experimental Template: CDS-CSharp

### ISSUE THREAD

**Issue by Mike-EEE** [Azure/Azure-Functions#725]
_If you're not sure where to file your issue, feel free to file it here. Please provide detailed steps to reproduce, including code if applicable._

This falls in the "not sure" category.  In this article:
https://docs.microsoft.com/en-us/common-data-service/entity-reference/cds-sdk-azure-functions-get-started

It references a `Scenario` -> `Experimental` -> `CDS-CSharp` template.  This appears it is no longer available, so I am looking to see if it is possible somehow to access this template somewhere so that I and others can run the demo as prescribed.

Thank you for any consideration and assistance!

**Comment by basijan** [comment]
I spoke with someone at MSFT about this, and they said they removed the template as the product is in preview and they weren't sure if they would continue with it, however it sounds like it is going ahead.

The suggested method of getting a function up and running was to download the CDS SDK preview nuget in VS and create your function from there (using the Azure function project template in VS). You can then publish that directly do Azure.

There is also a template sitting on github somehwere (I dont have the link on me right now), but it seemed to be missing a few components.

Finally, when I actually did publish my function to Azure, I was getting an error saying tha the CDS SDK dlls were missing, but you can actually navigate to the server in Azure and just copy the dlls over manually.

Hope this helps

**Comment by sebasijan** [comment]
I spoke with someone at MSFT about this, and they said they removed the template as the product is in preview and they weren't sure if they would continue with it, however it sounds like it is going ahead.

The suggested method of getting a function up and running was to download the CDS SDK preview nuget in VS and create your function from there (using the Azure function project template in VS). You can then publish that directly do Azure.

There is also a template sitting on github somehwere (I dont have the link on me right now), but it seemed to be missing a few components.

Finally, when I actually did publish my function to Azure, I was getting an error saying tha the CDS SDK dlls were missing, but you can actually navigate to the server in Azure and just copy the dlls over manually.

Hope this helps

**Comment by Mike-EEE** [comment]
Cool thanks for the information @sebasijan.  To be sure I got the Azure Function up and running.  That was the easy part. 😄  The issue here is that the template has boilerplate code to paste into the actual `Run` method as it works its magic to/from the Common Data Service.  That's what is of value here that I and others are seeking.

**Comment by Mike-EEE** [comment]
Looks like there is a PowerApps documentation on GitHub.  I have created an issue here:
https://github.com/MicrosoftDocs/powerapps-docs/issues/2

I am thinking if we bark up enough trees we'll finally find the one that has what we're looking for. 😉

**Comment by joshbooker** [comment]
Don't bother. Join the new private preview instead by sending request to email address listed at top of the docs article mentioned.

**Comment by joshbooker** [comment]
cdspreviewprogs@microsoft.com

**Comment by Mike-EEE** [comment]
Cool, thanks @joshbooker ... I have done that.  Any idea how long that process takes, by chance?  I'm already antsy. 😛

**Comment by joshbooker** [comment]
The cat is out of the bag.  https://aka.ms/businessappsreleasenotes
  This CDS 1.0 SDK is going away and the new CDS for Apps is based on xRM framework.  So the new SDK for CDS is the xRM SDK here:  https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/developer-guide

**Comment by Mike-EEE** [comment]
Going to close this now as I do not think this is as relevant as it was two days ago. 😉

**Comment by Mike-EEE** [comment]
So @joshbooker I have been checking out the documentation and see that Dynamics365 is tied up with Windows Workflow:
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/custom-workflow-activities-workflow-assemblies

However, I have yet to have seen any mention of Azure Functions in the new PowerApps documentation.  In fact, typing "Azure Functions" in the search top right [fails to yield any obvious results](https://docs.microsoft.com/en-us/search/index?search=azure+functions&scope=PowerApps).  

I hate to ask but... have Azure Functions been demoted in place of Windows Workflow?

**Comment by sebasijan** [comment]
Mike-EEE If you read my original comment, I actually suggest how you can get that "boilerplate code"...

**Comment by Mike-EEE** [comment]
Boh @sebasijan ... My eyes got distracted by "There is also a template sitting on github somehwere" and disengaged from the good parts, LOL.  Sorry about that.

In any case, it seems like Azure Functions have been replaced with the good ol' days of WCF/WF... they way it should be. 😄

**Comment by sebasijan** [comment]
@Mike-EEE They have not been replaced, its just a different way of hosting a service.

The existence of azure functions never prevented you from setting up a WCF service on azure

**Comment by Mike-EEE** [comment]
I get that @sebasijan but it's where the guidance is directing us now.  All the documentation says WCF/WF now so that is where a vast majority of developers will be spending their time in doing so, thereby creating more documentation/help/assistance/community around this area where problems arise, and therefore reducing overall cost and maintenance in developing applications, etc.  

Why spend my time investing in a path that there is no assistance/help/documentation in doing so?  More expensive that way.  I guess is my point.  I am of course bringing this up on the repository of the now replaced tech (again, from a conceptual/branding and not technical point of view) for the sake of awareness and hopefully further discussion to perhaps bring them back into inclusion.  

I am also wanting verify my understanding of the landscape now as there has been a lot of changes and I want to make sure I am not misunderstanding something obvious.
