### ISSUE TITLE
Invalid validation Error when Publishing an Azure Function in Visual Studio 2017

### ISSUE THREAD

**Issue by markb57** [Azure/Azure-Functions#729]
When using the publish feature within Visual Studio it is no longer allowing dashes within the middle of an App Name. 
Steps to recreate
1. Right click on the function and click publish
2. Select Create New and click publish
3. A dialog appears allowing you to name the function see screenshot below with invalid validation message. I have added a dash in the middle of the app name but it is still showing it as invalid.

![image](https://user-images.githubusercontent.com/37442606/37706490-9a27c5ec-2cf7-11e8-9c30-d505fca73466.png)

Environment
---
Azure Microsoft Visual Studio Enterprise 2017 
Version 15.6.2
VisualStudio.15.Release/15.6.2+27428.2005
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Enterprise
Architecture Diagrams and Analysis Tools   00369-60000-00001-AA152
Microsoft Architecture Diagrams and Analysis Tools
Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA152
Microsoft Visual Studio Tools for Applications 2017
Visual C++ 2017   00369-60000-00001-AA152
Microsoft Visual C++ 2017
Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA152
Microsoft Visual F# Tools 10.1 for F# 4.1
ASP.NET and Web Tools 2017   15.0.40301.0
ASP.NET and Web Tools 2017
ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.
ASP.NET Web Frameworks and Tools 2012   4.0.21208.0
ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio
Azure Functions and Web Jobs Tools   15.0.40215.0
Azure Functions and Web Jobs Tools
Azure Logic Apps Tools for Visual Studio   1.0
Add-in for the Azure Resource Group project to support the Logic App Designer and template creation.
C# Tools   2.7.0-beta3-62707-11. Commit Hash: 75dfc9b33ed624dff3985c7435c902c3c58c0e5c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events
JavaScript Language Service   2.0
JavaScript Language Service
JavaScript Project System   2.0
JavaScript Project System
JetBrains ReSharper Ultimate 2017.3    Build 111.0.20171218.133305
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.
Microsoft Azure HDInsight Azure Node   2.2.9000.1
HDInsight Node under Azure Node
Microsoft Azure Hive Query Language Service   2.2.9000.1
Language service for Hive query
Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio
Microsoft Azure Stream Analytics Language Service   2.2.9000.1
Language service for Azure Stream Analytics
Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2
Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards
Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package
Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio
NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
Project   1.0
Information about my package
ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info
SQL Server Analysis Services   14.0.1016.248
Microsoft SQL Server Analysis Services Designer 
Version 14.0.1016.248
SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools
SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 14.0.3002.68
SQL Server Reporting Services   14.0.1016.246
Microsoft SQL Server Reporting Services Designers 
Version 14.0.1016.246
SsmsVsIntegration   1.0
Information about my package
ToolWindowHostedEditor   1.0
Hosting json editor into a tool window
TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio
Viasfora   3.9.163
Add color to your Visual Studio editor!
Visual Basic Tools   2.7.0-beta3-62707-11. Commit Hash: 75dfc9b33ed624dff3985c7435c902c3c58c0e5c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by pragnagopa** [comment]
I cannot repro with the latest tools: VS 2017 15.5.7 Can you update and retry?

**Comment by markb57** [comment]
I am using VS 2017 Version 15.6.2 and this issue came with the latest update

**Comment by paulbatum** [comment]
I think @vijayrkn should be able to help track this one down

**Comment by vijayrkn** [comment]
This was an issue with our name validation logic in VS. We have fixed this issue and should be available in the next upcoming release of VS (next VS 15.7 preview).

**Comment by ColbyTresness** [comment]
Closing as this should be fixed.
