### ISSUE TITLE
Having object derive from TableEntity with Microsoft.NET.Sdk.Functions 1.0.9 results in exception

### ISSUE THREAD

**Issue by cincuranet** [Azure/Azure-Functions#730]
Code below results in error `Function: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.` under `Microsoft.NET.Sdk.Functions` 1.0.9. Works fine with 1.0.6.

```csharp
namespace FunctionApp1
{
	public static class Test
	{
		[FunctionName("Function")]
		public static void RunAsync(
			[TimerTrigger("*/5 * * * * *")]TimerInfo timerInfo,
			TraceWriter log)
		{
			log.Info("Test");
		}
	}

	class FooBar : TableEntity
	{ }
}
```

Removing the `FooBar` class and it's OK.

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.9" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by pragnagopa** [comment]
@ahmelsayed  - Installing Microsoft.NET.Sdk.Functions 1.0.9 on a .Net Standard project failing. Can you please look into this?

@cincuranet - How did you create a project with Microsoft.NET.Sdk.Functions 1.0.9 reference?

**Comment by cincuranet** [comment]
I manually updated the package version (because I saw newer version)..

**Comment by ahmelsayed** [comment]
What version of full framework do you have on that machine? I know you're targetting .NETStandard, but I've seen odd behavior when having an old full framework installed. I can't repro this issue myself. 

Also I just pushed `1.0.10` :)

**Comment by cincuranet** [comment]
I have `v4.0.30319` (the `C:\Windows\Microsoft.NET\...`) and targeting pieces in VS:
![img](https://user-images.githubusercontent.com/4540597/37734986-0e7aebae-2d4d-11e8-873d-a011ecfad06b.png)

**Comment by ahmelsayed** [comment]
That's what I have too. 

Actually let me step back a bit, where are you seeing this error `Function: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`? I assumed it was a build error, or is it somewhere else?

**Comment by cincuranet** [comment]
It's when starting the project from VS2017 (15.6).

**Comment by ahmelsayed** [comment]
okay that makes more sense. Sorry I was assuming it's a build error initially. When you run, what version do you see here 

![image](https://user-images.githubusercontent.com/645740/37738647-dcd39188-2d14-11e8-8403-4d5c2e06a880.png)

**Comment by pragnagopa** [comment]
@ahmelsayed - I fixed my machine. Nuget cache had other versions for webjobs sdk that I was testing. Running into a different issue. opened #[Azure/azure-functions-vs-build-sdk/issues/181](https://github.com/Azure/azure-functions-vs-build-sdk/issues/181)

**Comment by cincuranet** [comment]
I have `2.0.11353.0`.

**Comment by vbouret** [comment]
It seems the CLI tool has 8.6.0 version of WindowsAzure.Storage so if your version inside the project is newer, you get the problem.

![image](https://user-images.githubusercontent.com/321950/39611160-8d59784e-4f23-11e8-87c5-6679bb717c47.png)

**Comment by ColbyTresness** [comment]
Closed as customer resolved issue
