### ISSUE TITLE
V2 Could not load file or assemby

### ISSUE THREAD

**Issue by ADringer** [Azure/Azure-Functions#734]
Hi,

I'm using the following:

- VS2017 15.6.4

- Azure Functions and WebJobs Tools 15.0.40322.0

And creating a V2 (.Net Standard 2) function that references Microsoft.NET.Sdk.Functions 1.0.10.

I'm adding a reference to the nuget package Microsoft.IdentityModel.Protocols.OpenIdConnect 5.2.1 but am getting the following error:

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

I'm not too sure what I should be looking at to solve this issue. The package is for .Net Standard 1.4 so assume it's backwards compatible? I can see the file in the build output so it is there.

Thanks

**Comment by ciwchris** [comment]
For me the last version Microsoft.NET.Sdk.Functions works on is 1.0.6. After this version I start receiving similar errors.

> System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by ciwchris** [comment]
@ADringer thank you, that does appear it will resolve my issue

**Comment by ADringer** [comment]
Found a workaround for the issue [here](https://github.com/Azure/azure-functions-vs-build-sdk/issues/182). Have to target a lower version of the package.
