### ISSUE TITLE
Why Azure function not working with Generics?

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/Azure-Functions#735]
_From @viveknuna on March 21, 2018 7:23_

I have a requirement that I have to use TEntity with the class. But Azure function not working when using Generics with class. It's not even showing on the console also. But If I remove TEntity from class declaration it's showing in the console. So is this not supported? or is there any workaround for this? I have searched on internet but found nothing related to this.

```
public static class DataFilesIngestJobs<TEntity>
{
    [FunctionName("IngestDataFilesScheduled")]
    public static async Task RunScheduleAsync(
        [TimerTrigger("%DataFiles:IngestJob:ScheduleExpressionTrigger%")] TimerInfo timer,
        ExecutionContext context,
        TraceWriter log)
    {
        await RunAsync(context, log);
    }

    [FunctionName("IngestDataFilesOnDemand")]
    public static async Task RunOnDemandAsync(
        [QueueTrigger("%DataFiles:IngestJob:OnDemandQueueNameTrigger%", Connection = "ConnectionStrings:BlobStorageAccount")] string queueItem,
        ExecutionContext context,
        TraceWriter log)
    {
        await RunAsync(context, log);
    }
}
```
**Console output on removing TEntity from class.**

> Found the following functions: [3/21/2018 6:52:41 AM] MyCompany.MyProject.DataFilesIngestJobs.RunScheduleAsync [3/21/2018 6:52:41 AM] MyCompany.MyProject.DataFilesIngestJobs.RunOnDemandAsync

_Copied from original issue: Azure/azure-functions-core-tools#415_

**Comment by paulbatum** [comment]
This is not supported and we have no plans to support this (its hard to define how this would work). 

If you want to achieve code reuse by using generics you can totally do this - just move your logic into a generic class and then use that class from your functions. 

If you need to create multiple function definitions from a common pattern and you don't want to code it by hand, then consider traditional code generation techniques.

**Comment by GilShalit** [comment]
Hi, is this still the case and outlook in 2021?  Do Azure functions still not support Generics?  I was planning to implement a generic CRUD API I have  used on .Net Core very successfully with the advantage of adding and modifying the data model almost effortlessly.  This is a serious disadvantage of Azure Functions.

**Comment by RiRiSharp** [comment]
Hi, as mentioned above, it's not that hard.

```csharp
public class GenericCrudFunction
{
    private readonly GenericCrudFunctionInnerFactory _factory;

    public class GenericCrudFunction(GenericCrudFunctionInnerFactory factory)
    {
        _factory = factory;
    }

    [Function("GenericGetExample")]
    public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "{objectName:alpha}/{id:int}")] HttpRequest req, string objectName, int id)
    {
        var inner = _factory.GetInnerFunction(objectName);
        return inner.Get(objectName, id);
    }
}

public class GenericCrudFunctionInnerFactory
{
    public IGenericCrudFunctionInner GetInnerFunction(string objectName)
    {
        return objectName.ToLower() switch
        {
            "users" => new UsersCrudFunction(),
            "products" => new ProductsCrudFunction(),
            _ => throw new NotImplementedException($"No CRUD function implemented for {objectName}")
        };
    }
}

public interface IGenericCrudFunctionInner
{
    IActionResult Get(string objectName, int id);
}

public class UsersCrudFunction : IGenericCrudFunctionInner
{
    public IActionResult Get(string objectName, int id)
    {
        // Simulate fetching a user by ID
        var user = new { Id = id, Name = "User" + id };
        return new OkObjectResult(user);
    }
}

public class ProductsCrudFunction : IGenericCrudFunctionInner
{
    public IActionResult Get(string objectName, int id)
    {
        // Simulate fetching a product by ID
        var product = new { Id = id, Name = "Product" + id };
        return new OkObjectResult(product);
    }
}
```

We create an inner function which actually does all the heavy lifting. From that one you can create multiple implementations. Each implementation uses their own type and handling logic, but it will always return an action result.

If you want even more magic, you can then create a `GenericCrudFunction<T> : IGenericCrudFunctionInner`, which for instance gets an `ICrudService<T>` injected.
