### ISSUE TITLE
Document how to disable a function in V2

### ISSUE THREAD

**Issue by pragnagopa** [Azure/Azure-Functions#736]
"disabled" property in function.json is no longer valid in Functions V2.  You can disable a function via portal:
![image](https://user-images.githubusercontent.com/1874279/37934511-48b8fe82-3103-11e8-8da3-7c8424e63ab6.png)
This adds an app setting key: AzureWebJobs.FunctionName.Disabled value: true

**Comment by paulbatum** [comment]
We might want to expand this to a general documentation topic on disabling, that explains the different workflows that are possible and not possible based on whether its v1/v2 and whether its a VS authored function or not.

**Comment by rams78** [comment]
From my experience disabling compiled queue-triggered function in Azure Portal did not have any effect, we still had them running even after re-deployment.

**Comment by AuroraBrignola** [comment]
Any joy on this? Would very much appreciate some clear guidelines, thanks

**Comment by paulbatum** [comment]
@AuroraBrignola the information above should be enough to unblock you, assuming you're asking about V2.

**Comment by ltouro** [comment]
It would be great if functions generated by templates does not add this obsolete property.

```
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

Also, the documentation should not present this property on 2.X samples: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook

**Comment by ColbyTresness** [comment]
ping @ggailey777

**Comment by ggailey777** [comment]
Is this the article that was needed?
[How to disable functions in Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/disable-function)

**Comment by pragnagopa** [comment]
Yes @ggailey777  thanks. Will close this issue.

**Comment by ltouro** [comment]
Main documentation is still wrong at https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook.

This will be source of confusion for Func V2 users trying to disable a function using obsolete "disable" property. 

At least, a disclaimer should be added somewhere, pointing to the new article regarding disabling functions.

**Comment by danielcrisp** [comment]
Does this mean that I can't disable functions locally? Only globally?

I'm trying to debug a new function but when I run locally all my other functions run, which I don't really want. But I don't want to disable the deployed functions.

**Comment by ColbyTresness** [comment]
@ggailey777 can you take care of the docs issue?

**Comment by ltouro** [comment]
@danielcrisp you can disable functions locally. You should use local.settings.json instead App Settings (as you would do in Azure) (Env vars might work also. Not tested)

It will be something along these lines (deprecated keys might be present. This file is some months old):

```json
{
  "IsEncrypted": false,
  "Values": {   
    "APPINSIGHTS_INSTRUMENTATIONKEY": "...",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "...", 
    "AzureWebJobs.myFuncNameHere.Disabled": true,
  },
  "ConnectionStrings": {
    
  }
}
```

**Comment by ggailey777** [comment]
@craigshoemaker we probably have this same issue in all the binding reference articles that still show the disabled property.

**Comment by craigshoemaker** [comment]
@ggailey777 should we use an include file for this?

**Comment by ggailey777** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/126055
