### ISSUE TITLE
Access Rights field in New Function template is confusing

### ISSUE THREAD

**Issue by ggailey777** [Azure/Azure-Functions#739]
Customers have reported confusion about the **Access rights** field for an HTTP trigger Visual Studio:

![image](https://user-images.githubusercontent.com/1388263/37997149-f45a5ff8-31ce-11e8-8958-593274f66345.png)

This field is in both the new function and new function app template. Can we instead use **Authorization level**, so that it closer to the HTTP trigger metadata?

https://github.com/MicrosoftDocs/azure-docs/issues/5955

**Comment by Mike-EEE** [comment]
+1 to renaming to Authorization Level. Additionally, it would be incredibly useful to link to the documentation in regards to these levels.

Also, please consider renaming "Admin" to "Host" or "Host Key" to be consistent with the documentation.  If you use "Host Key", consider also renaming "Function" to "Function Key" to keep everything consistent.

**Comment by Mike-EEE** [comment]
I'm going to get myself in trouble here. 😆 

Been thinking about this a little more.  Another consideration might be something like this:

http://michael351.webflow.io/

This would be wrapped in a group control (which is not readily available at webflow, unfortunately) named `Security` and allows the user to select between all 3 states in a more intuitive manner (if I do say so myself LOL).

**Comment by ColbyTresness** [comment]
This actually comes from the templates repo, moving there.

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-templates#850
