### ISSUE TITLE
Doc tags as dynamic for NH bindings

### ISSUE THREAD

**Issue by wesmc7777** [Azure/Azure-Functions#74]
Some customers seem to think the tags used for notification hub bindings are static.  Document tagExpression as dynamic and provide dynamic tagExpression example

**Comment by pragnagopa** [comment]
Related question and sample: **[here](http://stackoverflow.com/questions/40165148/azure-notification-hub-registration-from-android/40224435#40224435)**

**Comment by wesmc7777** [comment]
I should have this one checked in by the end of this week

**Comment by mathewc** [comment]
Another customer having problems here: https://social.msdn.microsoft.com/Forums/azure/en-US/0d0750df-6f29-473c-8cfa-75b1c581f799/missing-assemblies-since-two-days

**Comment by pragnagopa** [comment]
One more customer looking for this info posted comment in: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-notification-hubs#wns-native-notifications-with-c-queue-triggers

**Comment by martin-weber** [comment]
For my solution the mentioned samples are not working, because I get an array of messages via eventhub from stream analytics and need to send multiple messages with different tags. Could you please provide a sample? Thanks, Martin
