### ISSUE TITLE
Visual Studio 2017 Azure Function "Exclude From Project" issue

### ISSUE THREAD

**Issue by desinole** [Azure/Azure-Functions#741]
OS; Windows 10 Enterprise N
IDE: Microsoft Visual Studio Community 2017 
SDK: Azure Functions and Web Jobs Tools   15.0.40215.0

Steps to reproduce:
1. Create an Azure Functions project and add two new function, for instance, one with a Timer Trigger **TimerFunc** and one with a Queue Trigger **QueueFunc**
2. Build the project
3. Right click on one of these functions (say Timer Trigger function **TimerFunc**) and **Exclude from Project**
4. Hit **F5** to run the project
5. You will observe the following error messages in red on the console:

> [3/28/2018 5:12:51 PM] The following 1 functions are in error:
> [3/28/2018 5:12:51 PM] TimerFunc: The function type name 'TestProject.TimerFunc' is invalid.

6. Stop debugging/close the console
7. Right-click on project and **Open Folder in File Explorer**
8. Navigate to **bin->Debug->*framework*** folder. You will observe a **TimerFunc** folder.
9. Right-click on the project and **Clean**. 
10. You will notice that the **TimerFunc** folder disappears. _**Note**: Alternatively you can delete the **TimerFunc** folder manually._
11. Repeat step 4 and you won't see the error messages in the console anymore.

**Comment by ColbyTresness** [comment]
@nimakms for VS

**Comment by JohnReeson** [comment]
No repro in VS2017 15.9.4, Azure Functions and Web Jobs Tools 15.10.2046.

**Comment by ColbyTresness** [comment]
Closing since this doesn't repro. Please reopen if necessary.
