### ISSUE TITLE
Unable to use Azure Functions in Visual Studio ...

### ISSUE THREAD

**Issue by bdcoder2** [Azure/Azure-Functions#743]
My original post may be viewed at:
[https://developercommunity.visualstudio.com/content/problem/226035/unable-to-use-azure-functions-in-visual-studio.html](https://developercommunity.visualstudio.com/content/problem/226035/unable-to-use-azure-functions-in-visual-studio.html)

I was told to post the issue here via the Microsoft Documentation team.

In a nutshell (it appears) Microsoft.NET.Sdk.Functions 1.0.12 is causing the following when a project is run:

`Microsoft.Azure.WebJobs.Host: Error indexing method 'f3.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type TraceWriter. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).`

The above can be reproduced easily by creating a NEW Azure Functions project in Visual Studio (I am using Visual Studio Community 2017 v15.6.4) -- the VS project template uses v1.0.6 of Microsoft.NET.Sdk.Functions and the project will run just fine.

However, once you upgrade (via NuGet) to Microsoft.NET.Sdk.Functions to v1.0.12 -- the project will fail when run with the error shown above, i.e.: **Cannot bind parameter 'log' to type TraceWriter.**

If I downgrade Microsoft.NET.Sdk.Functions to v1.0.11 -- the project runs again without error.

**Comment by tiagonmas** [comment]
I have the same issue [#744](https://github.com/Azure/Azure-Functions/issues/744)

**Comment by bdcoder2** [comment]
Looks like this is fixed now that Microsoft.NET.Sdk.Functions to v1.0.13 is out and the CLI has been updated as well -- Thanks MS !
