### ISSUE TITLE
Azure Function - Docker

### ISSUE THREAD

**Issue by espray** [Azure/Azure-Functions#747]
Azure Function docker starting running 

I used this repro as a base
https://github.com/cmendible/dotnetcore.samples/tree/master/azure.function.docker
Then changed to 2.0.0-jessie

C:\GitRoot\dotnetcore.samples\azure.function.docker>docker build -t myfunc .
Sending build context to Docker daemon  1.383MB
Step 1/3 : FROM microsoft/azure-functions-runtime:2.0.0-jessie
 ---> 217799efa500
Step 2/3 : ENV AzureWebJobsScriptRoot=/home/site/wwwroot
 ---> Using cache
 ---> 6d78cae6fcf0
Step 3/3 : ADD wwwroot /home/site/wwwroot
 ---> Using cache
 ---> 6a455abcae0a
Successfully built 6a455abcae0a
Successfully tagged myfunc:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
C:\GitRoot\dotnetcore.samples\azure.function.docker>docker run -it -p 8080:80 myfunc
docker: Error response from daemon: driver failed programming external connectivity on endpoint optimistic_johnson (0c40fd489c35eacd2926c672fe064fb53c53fb36199147132de8bbfeebdd6ab5): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.17.0.2:80: input/output error.
C:\GitRoot\dotnetcore.samples\azure.function.docker>

Docker for Windows
Docker Community Edition 18.03.0-ce-win59 (16762)
Engine: 18.03.0-ce
Compose: 1.20.1
Credential Helpers: 0.6.0
Machine: 0.14.0
Notary: 0.6.0

**Comment by ConnorMcMahon** [comment]
It looks like this generally means the port is already in use (see [here](https://stackoverflow.com/questions/39508018/docker-driver-failed-programming-external-connectivity-on-endpoint-webserver)). I don't think this is an issue with Azure Functions.
