### ISSUE TITLE
Unable to see exception and Error logs for precompiled Azure timer functions in the event of function failure.

### ISSUE THREAD

**Issue by jfelner** [Azure/Azure-Functions#749]
We have a precompiled timerTrigger c# Azure Function that was receiving an error on execution in Production and was not logging any information to the portal or scm website, so it appeared like the timer was not firing.

Function has been in Prod since 3/24 with a cron timer set to "0 0 23 * * 1-5" to run nightly at 11 PM using the WEBSITE_TIME_ZONE app setting set to CST.  It didn't appear to run as there was nothing logging in the portal or scm website.  It wasn't updating the values it was supposed to either.  We tried everything we could think of and were unable to find any relevant log files that would pinpoint the issue.  So we had no way to verify the timerTrigger was firing properly or if some other issue was occuring.

After opening a support ticket with Azure support they were able to see the actual error to let us know the timerTrigger was firing but an error was occuring.

![image](https://user-images.githubusercontent.com/5042746/38337022-7575fa06-3829-11e8-90b7-4e2cbee2dc78.png)

**Comment by ColbyTresness** [comment]
Was this resolved through Azure support? Are you still experiencing this issue? Sorry for the delay in responding to this.

**Comment by jfelner** [comment]
Azure Support was able to provide enough information to us to help us figure out the issue and resolve it.
