### ISSUE TITLE
Cosmos extension install example in run local docs is out of date

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#752]
Re: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

A customer reported an issue with the instructions here:
https://github.com/Azure/azure-functions-host/issues/2598#issuecomment-379225951

I think the main problem is the docs have a hardcoded version reference:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#register-extensions

`func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0-beta6`

We released a newer version of this extension, but customers are running the above command and getting an old version, which doesn't work anymore.

Can we change this line somehow so that it gets the latest 3.x so that it doesn't have to be updated repeatedly?

**Comment by paulbatum** [comment]
cc @ggailey777 @tdykstra

**Comment by ggailey777** [comment]
@paulbatum I did not want to include the version # for just this reason 😦  
I don't suppose there is any way to show the CLI command without the hardcoded version #?

**Comment by ggailey777** [comment]
Or maybe there's an extension that will change less often?

**Comment by ColbyTresness** [comment]
I believe this has been fixed per the referenced PR
