### ISSUE TITLE
Visual Studio downgrades / overwrites the NuGet packages version with the one in the ItemTemplate

### ISSUE THREAD

**Issue by soninaren** [Azure/Azure-Functions#753]
Source GitHub issue:
https://github.com/Azure/azure-functions-durable-extension/issues/211

Steps:
- Create a function app on VS
- Install the latest version of the following NuGet pacakge
   - Microsoft.Azure.WebJobs.Extensions.CosmosDB
   - Microsoft.Azure.WebJobs.Extensions.DurableTask
   - Microsoft.Azure.WebJobs.Extensions.EventGrid
  - Microsoft.Azure.WebJobs.Extensions.EventHubs
- Add a template: Right click project -> Add -> Function -> select one of the template that refers one of the pacakges in the above list.

Currently with Visual studio extension version 15.0.40405.0. we are referring the latest NuGet package. so this issue would not reproduce. But as soon as there is a new version of extension package available on NuGet. This issue will reproduce again.

![durablefunctions](https://user-images.githubusercontent.com/360052/38022996-0295933a-3279-11e8-904e-918e2fbfbe02.gif)

**Comment by ColbyTresness** [comment]
@nimakms for VS

**Comment by JohnReeson** [comment]
No repro in VS2017 15.9.4, Azure Functions and Web Jobs Tools 15.10.2046.

**Comment by ColbyTresness** [comment]
Closing due to lack of repro. Please reopen if necessary.
