### ISSUE TITLE
Current runtime is tied to Microsoft.Extensions.DependencyModel 2.0.3; current version is 2.0.4

### ISSUE THREAD

**Issue by mwadams** [Azure/Azure-Functions#755]
(As per title - I realise that this is an ongoing race condition between projects)

**Comment by paulbatum** [comment]
@mwadams Hi can you please expand on this.. there is no description of what you are trying to achieve, how you are blocked, etc.

**Comment by mwadams** [comment]
Hi - sorry. I am using libraries that are built against the current shipping versions of e.g Microsoft.Extensions.DependencyModel. The recent functions V2 runtime release skipped against the previous version of this assembly (at least), causing a 500 error when my function is invoked because it cannot load the current version of the library.

**Comment by mwadams** [comment]
(shipped, not skipped)

**Comment by ColbyTresness** [comment]
Is this still an issue?

**Comment by ColbyTresness** [comment]
Closing due to lack of response. Please reopen if still experiencing issues.
