### ISSUE TITLE
Unable to locate resource manager JSON for new alerts

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/Azure-Functions#756]
I have created some of the new alerts through the portal UI and now need to deploy these by resource manager template, but I am unable to locate the JSON schema for this resource type.

I can find the resource listing in the relevant resource group in the Resource Explorer website (looks like type microsoft.insights/scheduledqueryrules), but the JSON to create the resource does not exist.

There is [documentation for templating the classic alerts](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-enable-alerts-using-template), but nothing for the new type.

**Comment by paulbatum** [comment]
As far as I can tell this issue does not relate to Azure Functions at all, it is about Azure Alerts. I found this uservoice so I suggest you provide the feedback there:
https://feedback.azure.com/forums/602299-azure-alert-management
