### ISSUE TITLE
Azure Functions on App Service Plan and Function Proxies

### ISSUE THREAD

**Issue by IshamMohamed** [Azure/Azure-Functions#758]
I have couple of questions to be clarified on Azure Functions on App Service Plan. 
1)  https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale, here the documentation says "A single function app will only scale to a maximum of 200 instances" - is this only applicable for the "Consumption Plan" as it is the one that dynamically scales? or, since I have my function on a app service plan which leverages a "S1 Standard Pricing tier" which was not enabled with "Auto scaling" - does this mean, my function will run on only one instance?
2) https://channel9.msdn.com/Shows/Azure-Friday/Serverless-APIs-with-Azure-Function-Proxies, in this video @alexkarcher-msft says then the proxies is not running, its totally free (and also touches the consumption rate thingy). while I notice  "Proxies" is available for the Azure Functions on App Service Plan - is @alexkarcher-msft is still correct on his statement when it comes to Azure Functions Proxies on App Service Plan

**Comment by alexkarcher-msft** [comment]
Hi @IshamMohamed, 

You are running your Function app in dedicated mode by selecting an App Service plan tier other than dynamic. When you are running your Function app in dedicated mode your only cost is the App Service plan cost, and you can only scale up to the number of instances you have allocated to that App Service plan. Proxies executions follow the same model as all other Functions.

You can read more about the dedicated plan hosting specifics here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#app-service-plan

Thanks!

**Comment by IshamMohamed** [comment]
Hi again, since I have disabled "Auto scaling" in my "S1 Standard Pricing tier" - it will not scale, am I correct?
