### ISSUE TITLE
Update Visual Studio item template "Connection" string to make it clearer what it does

### ISSUE THREAD

**Issue by Andrew-MSFT** [Azure/Azure-Functions#764]
Currently when a user creates a new Azure Function in Visual Studio, for trigger types that require a connection string, it just says "Connection" (VS displays this information from the item template).  

This is confusing if you don't know what it does, changing the string to "Connection String Key" would be clearer that the user is providing the key name, not the connection string itself

![image](https://user-images.githubusercontent.com/12432803/38770084-171bceb8-3fc2-11e8-84aa-dd2c7b291983.png)

**Comment by mhoeger** [comment]
@jeffhollan - This seems like a good suggestion! Would you mind triaging?

**Comment by ColbyTresness** [comment]
@nimakms I think this is in the pipeline, but adding you here in case

**Comment by JohnReeson** [comment]
See `Connection string setting` right now.

![capture](https://user-images.githubusercontent.com/35160013/50555253-99085080-0d04-11e9-9365-29b285a9f807.JPG)

**Comment by Andrew-MSFT** [comment]
Do you think "setting" is as clear as "name" or "key"?

**Comment by JohnReeson** [comment]
@Andrew-MSFT Hmm, I am just an Azure Function leaner but IMO it's fine, which indicates it's a setting in local.settings.json or app settings on Azure.  When I get started with Azure Function, I would go for the document first, where I could understand the setting. If I don't know anything about Azure Function, I would wonder why a Connection string needs a name or key.

**Comment by ColbyTresness** [comment]
I agree we should make this string clearer.

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-templates#851
