### ISSUE TITLE
How to test Azure Functions locally using System.Net.Http.HttpClient in C#

### ISSUE THREAD

**Issue by bdcoder2** [Azure/Azure-Functions#767]
I am trying to test azure functions (HTTP trigger) locally using a project that issues HTTP POST requests from a program created in Visual Studio, i.e.: using System.Net.Http.HttpClient.

However, when HttpClient issues a POST request to localhost, the following exception is thrown:

`System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:7170
`

I can make POST requests using PostMan or GET requests using a browser, but when trying to test functions locally using System.Net.Http.HttpClient calls from within Visual Studio -- it seems impossible, due to the error above.

I understand localhost is a loopback address, but PostMan seems to be able to complete localhost POST requests, so I should as well when testing from Visual Studio - correct?

What magic setting must be enabled (or disabled) to allow POST request from Visual Studio (using System.Net.Http.HttpClient) when testing locally?

Thanks in advance.

**Comment by ahmelsayed** [comment]
> `127.0.0.1:7170`

did you explicitly change the default port? is this the same url you are hitting in the browser?

**Comment by bdcoder2** [comment]
Oh good grief – my sincerest apologies!

I had http://localhost:7170/ as the base URL in a config file rather than (the correct) http://localhost:7071/

Two hours looking at the exception and I didn’t clue in – time for a holiday!

Once again – sorry for the false alarm and thanks for the quick reply !!
