### ISSUE TITLE
Different types of Azure Functions development - which is recommended

### ISSUE THREAD

**Issue by IshamMohamed** [Azure/Azure-Functions#769]
There are two ways to create Azure Functions for the development
1) By invoking `func new --language C# --template QueueTrigger --name IshamTrigger`
2) By invoking `dotnet new azureFunctionsProjectTemplates`

the first provides the .csx way and the second provide .cs way of programming Azure functions. Can you clarify which is recommended and which gives more flexibility of programming a function.

**Comment by mhoeger** [comment]
.cs is generally the recommended way of programming Azure functions locally. C# script files (.csx) are more limited, and the main use case is for quick and simple development in the portal. @ahmedelnably to comment on the CLI commands. 

@IshamMohamed - was there documentation that you found that needs clarification? How can we resolve this issue?

**Comment by IshamMohamed** [comment]
Say if I use the second approach and will I be still able to deploy the function to the cloud? will it be converted as a .csx file?

**Comment by mhoeger** [comment]
Yes! Here's some documentation on publishing your local function app: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#publish. The .cs files aren't converted to .csx files. On publish, your compiled code (.dll file) is uploaded to the cloud.

C# developers usually develop through Visual Studio, which does a lot of the project setup and deployment: https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs

**Comment by paulbatum** [comment]
There is also tooling for writing C# functions using VS code:
https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions

**Comment by paulbatum** [comment]
You do not need to hardcode the queue name. Just use a binding expression against an app setting. See here for an example: https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#binding-expressions---app-settings

**Comment by IshamMohamed** [comment]
That's cool. One last question, when I tried to publish the class library
function, there is an option to publish as files locally rather than to the
cloud. Is there a way through REST API calls I can send these locally
published files to the cloud and make it work? I guess Zip Push (which
works for .csx functions) won't work here. I want to distribute my class
library function without disclosing the code.

**Comment by ColbyTresness** [comment]
Closing as this is resolved IMO
