### ISSUE TITLE
Document NodeJS HTTP Trigger req.params object

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#77]
Today we only document that the route binding items are only available on the `context.bindingData` object, but they are also available on the `req.params` object.

**Comment by SyntaxC4** [comment]
If we could get these done with #67 and #59 that would be awesome!

**Comment by ggailey777** [comment]
@christopheranderson and @SyntaxC4 I have made updates that you can review in [this PR](https://github.com/Microsoft/azure-docs-pr/pull/9679)
