### ISSUE TITLE
Linux: tenant and SourceMoniker don't get correctly populated in the logs

### ISSUE THREAD

**Issue by davidebbo** [Azure/Azure-Functions#774]
Tenant shows up as `DefaultTenant` and SourceMoniker as `LWAWSTest`. We should pass the Stamp info to the container so it can write the right thing.

Also, `RoleInstance` could be set to the container machine name instead of just `DefaultRoleInstance`.

**Comment by bala16** [comment]
Tenant is populated now. SourceMoniker is more expensive to customize. Will add this later if required.
