### ISSUE TITLE
func host start --nodeDebugPort does not work

### ISSUE THREAD

**Issue by ixevix** [Azure/Azure-Functions#788]
It does not affect the port

however using `func host start --workers node:debug=5859` works

**Comment by ixevix** [comment]
I read it from the source code. It's like that.

**Comment by ColbyTresness** [comment]
Can you still repro this? Sorry for the delay in responding.

**Comment by ixevix** [comment]
Can still repro

**Comment by ColbyTresness** [comment]
@mhoeger can you look into this?

**Comment by mhoeger** [comment]
[`--nodeDebugPort`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#start) is a setting that's been deprecated for V2 (only available on V1). If you have issue with the deprecation of this command, could you file an issue [here](https://github.com/Azure/azure-functions-core-tools/issues) about it? Thanks!
