### ISSUE TITLE
New Azure Functions Project Dialog

### ISSUE THREAD

**Issue by Mike-EEE** [Azure/Azure-Functions#793]
FWIW, found this while creating a project in Visual Studio 2017 15.7 Preview for #789:

![](https://dragonspark.tinytake.com/media/75e7ca?filename=1525414376582_04-05-2018-02-12-55.png&sub_type=thumbnail_preview&type=attachment&width=698&height=405)

The annoying spinner of doom (which doesn't precisely tell the user _exactly_ what it is doing nor does it give the user any way of cancelling it, leading to a most uneasy feeling) never goes away.

**Comment by JohnReeson** [comment]
Azure Functions and Web Jobs Tools is updated to `15.0.40502.0` recently.

The first time we create an Azure function after this update, we can see the tip on the dialog `Making sure all templates are up to date....`. It means VS is downloading necessary cli and templates to this folder `C:\Users\UserName\AppData\Local\AzureFunctionsTools`. Once it completes, we can see `Updates are ready`.

**Comment by Mike-EEE** [comment]
Cool @JohnReeson thanks for letting me know.  To my point there was no indication/indicator/UI to let me know any sort of notion of progress.  Furthermore there's no actionable link to click to see what it's doing, so it just looks frozen and broken.  In any case I tried again and it worked as described this time.
