### ISSUE TITLE
Not Getting Dependencies from bin\Debug\netstandard2.0\bin

### ISSUE THREAD

**Issue by thiagospassos** [Azure/Azure-Functions#794]
Context: 
- Visual Studio 2017 15.6.7
- Azure Functions and Web Jobs Tools 15.0.40405.0
- Microsoft.NET.Sdk.Functions 1.0.13

Steps to reproduce
1. I'm creating a brand new Azure Functions app with Visual Studio, selecting Azure Function v2 Preview.
2. **F5** everything works fine
3. Add a new dependency via nuget package.
4. Build is successful
5. **F5** System.Private.CoreLib: Could not load file or assembly

I banged my hand on the wall for several hours and nothing made sense, until I realized that when running the function app locally, the tooling was getting the dlls from **C:\Users\thiago\AppData\Local\Azure.Functions.V2.Cli** instead of the relative path **bin\Debug\netstandard2.0\bin**. So of course, none of the new dependencies would be in the Azure.Functions.V2.Cli folder.

Do I need to set any specific flag when running using Visual Studio or the Cli in order to get the dependencies from the bin folder?

**Comment by ColbyTresness** [comment]
@nimakms this might be resolved by the fact that we're no longer in preview, but please investigate.

**Comment by ColbyTresness** [comment]
Closing as I'm assuming this is fixed now. Please reopen if that isn't the case.
