### ISSUE TITLE
Processing EventHub events serially using Azure Functions

### ISSUE THREAD

**Issue by himanshu219** [Azure/Azure-Functions#795]
I have following setup
EventGrid --> EventHub --> Azure Function

I want to process messages in eventhubs serially Currently there are following drawbacks which does not allow to have this feature
1) One cannot decrease  EventHub partition count to one as this would have enabled inorder processing of messages
2) One cannot provide publisher option while creating event subscription for eventhubs so that all messages go to a single partition
3) Singleton azure function are not available(though it is possible in web jobs ) 

Any of the above 3 will allow inorder processing of messages from EventHub

**Comment by ColbyTresness** [comment]
Please read the following blog post which describes a solution to this problem:

https://medium.com/@jeffhollan/in-order-event-processing-with-azure-functions-bb661eb55428
