### ISSUE TITLE
Azure Functions v2 referencing .NET Core 2.0 

### ISSUE THREAD

**Issue by johnkwaters** [Azure/Azure-Functions#797]
I have an API that is written in AspNetCore 2.0/2.1, which has a DTO assembly and a Repository assembly using EntityFrameworkCore.
I wish to reference these from my Azure Functions. But after adding a reference I get this on compiling the Azure Function project:

NU1201	Project NorthStar.DTO is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project NorthStar.DTO supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	NorthStar.Functions	D:\src\repos\MWOP\NorthStar.Functions\NorthStar.Functions.csproj	1	

My DTO project is compiled as a .NET Core 2.0 target framework
My Azure func project has .NET Standard 2.0

How do I get it to work?

Ahah - I need to make my DTO a .NET Standard project!

**Comment by paulbatum** [comment]
Sounds like you found the workaround. I will note that in theory, Azure Functions could support making your function project target NetCoreApp2.0 so that you did not need to change your DTO project. This is tracked here: https://github.com/Azure/Azure-Functions/issues/805

**Comment by Tealons** [comment]
This also a blocker for us. Would be nice to get this fixed in the near future!
