### ISSUE TITLE
Azure Function running on consumption plan stopped working

### ISSUE THREAD

**Issue by peppi-scaleforce** [Azure/Azure-Functions#798]
Hi, we have a intermittent stopping of all the functions running in one app service. It was stopped for more than 10 hours tonight and it continues to stop today a few times. Looks like all triggers on the functions are not working e.g. Timer,  CosmosDBTrigger. When function is started manually all continues working. 

Can you please investigate:

2018-05-09T13:32:13.874 [Info] Function started (Id=cd721738-606e-4376-b056-cf5875856c83)
Region: Central India

Thanks a lot!
Penka

**Comment by FabioReis** [comment]
I have exactly the same problem and we need a solution for this, i ended up creating a issue on azure-functions-host repository. [https://github.com/Azure/azure-functions-host/issues/2870](url)

Any updates on this?

**Comment by ColbyTresness** [comment]
The referenced issue doesn't exist anymore, so I'm assuming this was resolved. Please reopen if you can still repro.
