### ISSUE TITLE
Visual Studio item templates should include "using System;"

### ISSUE THREAD

**Issue by Andrew-MSFT** [Azure/Azure-Functions#799]
the item templates don't currently include using System, it's very rare when writing meaningful C# code that you don't use a type from system, and it's annoying to have to keep adding it.

**Comment by ColbyTresness** [comment]
@soninaren do you think this should be in the templates repo or is it appropriate to track here?

**Comment by soninaren** [comment]
@ColbyTresness yes this should be in the templates repo

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-templates#847
