### ISSUE TITLE
Deploy Azure Functions with ARM

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#8]
I have a sample of this here: https://github.com/SyntaxC4-MSFT/CoderCards

**Comment by lindydonna** [comment]
FYI we have 2 deployment templates in the ARM templates repo already, but needs the following changes:
- The Dedicated one needs to add AlwaysOn (as in your sample https://github.com/SyntaxC4-MSFT/CoderCards/blob/master/azuredeploy.json#L77)
- Need to use the version of Functions at RC, which will be **~1.0**

Then the doc can point to these:
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-function-app-create-dedicated
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-function-app-create-dynamic

**Comment by lindydonna** [comment]
Remove AZUREJOBS_EXTENSION_VERSION

**Comment by SyntaxC4** [comment]
It's blocked due to updating the TOC with the article, however, it's available here: https://github.com/Microsoft/azure-docs-pr/pull/3799
