### ISSUE TITLE
RestSharp.dll version is wrong

### ISSUE THREAD

**Issue by alcoforado** [Azure/Azure-Functions#801]
Guys I know that the azure functions cli has a dependency with RestSharp.dll and I think that is conflicting with one of the Azure Functions. 

I am getting a runtime type exception
System.TypeLoadException: 'Could not load type 'RestSharp.IAuthenticator' from assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null'.'

Now my azure function is dependent of RestSharp nuget Version 104.4.0.0. And here is the interesting thing. I searched my entire computer for that dll version and I found it at AppData\local\Azure.Functions.Cli\1.0.12

Is that it ? Is the Azure functions runtime trying to link with the RestSharp.dll used by the runtime instead of the dll version of my project ?

**Comment by ColbyTresness** [comment]
This class of problems is resolved in Azure Functions 2.x. Please reopen if you're still experiencing issues.
