### ISSUE TITLE
mscorlib: Cannot create an abstract class error when implementing IExtensionConfigProvider

### ISSUE THREAD

**Issue by gdodd1977** [Azure/Azure-Functions#803]
I'm implementing a custom function binding for dependency injection. I have that custom binding attribute as well as an abstract base class implementing IExtensionConfigProvider in a common dll. I'm referencing that common dll in an azure function project and inheriting from that abstract base class. When I launch the function locally, I get an error saying A ScriptHost error has occurred mscorlib: Cannot create an abstract class.

I'm on cli version 1.0.12.1.

**Comment by mathewc** [comment]
This is coming from the activation code [here](https://github.com/Azure/azure-functions-host/blob/13769982b62bc7c3865fcd3d9b5a699e009454cd/src/WebJobs.Script/Binding/ExtensionLoader.cs#L134). We currently assume registered config providers are concrete Types and we `Activator.CreateInstance` them.

PR out now with the fix - we'll get it in the next release.
