### ISSUE TITLE
Service Bus Queue Trigger works locally but not after published to production

### ISSUE THREAD

**Issue by tokyo0709** [Azure/Azure-Functions#806]
We have a function within a function app that we have been testing locally and everything works great. The function in question pulls items down from the queue as they pop into the queue and processes them. We are pointing to the queue in Azure that we are using for production as well. Once we publish, our other queues from the same service bus work fine except for this one function. We have added the app setting in Azure to match exactly to what we have locally in our local.settings.json file. We have also created a service bus queue trigger as another function in that function app as a test to see if we could pull down from that queue in production and that also worked fine. We have also tried remote debugging but nothing hits the breakpoints we have set.

**Function in question**

```csharp
[FunctionName("ProcessEmail")]
public static void Run([ServiceBusTrigger("email-queue-jobs", AccessRights.Manage, 
    Connection = "MicroServicesServiceBus")]OutgoingEmail outgoingEmail, TraceWriter log,
    [ServiceBus("email-queue-cleanup", Connection = "MicroServicesServiceBus", EntityType = Microsoft.Azure.WebJobs.ServiceBus.EntityType.Queue)] ICollector<OutgoingEmail> cleanupEmailQueue,
    [SendGrid] ICollector<SendGridMessage> messageCollector)
{
    try
    {
        log.Info($"Attempting to send the email {outgoingEmail.Id}");
        var message = SendgridHelper.ConvertToSendgridMessage(outgoingEmail);
        messageCollector.Add(message);

        log.Info("Successfully sent email:");
        log.Info(JsonConvert.SerializeObject(outgoingEmail));
    }
    catch (Exception ex)
    {
        log.Info($"Unable to process email {outgoingEmail.Id}");
        throw ex;
    }

    // Add email to the cleanup queue
    log.Info("Sending email to the cleanup queue.");
    cleanupEmailQueue.Add(outgoingEmail);
}
```

**Service Bus Connection in Application Settings in Azure**
![queueconnection](https://user-images.githubusercontent.com/14184583/40206849-f40b5dfc-59ee-11e8-91ee-9d117a7d6ca8.PNG)

**Service Bus Explorer showing a message to be processed**
![queueimage](https://user-images.githubusercontent.com/14184583/40206874-09137072-59ef-11e8-9e7a-908a8fab9e58.PNG)

Just can't get this function to pull anything down from the queue _email-queue-jobs_ from our Service Bus _MicroServicesServiceBus_

**Comment by tokyo0709** [comment]
Just solved this. We had to explicitely define our connection to SendGrid in the SendGrid attribute. Feel free to delete this if necessary.

**Comment by mathewc** [comment]
Closing
