### ISSUE TITLE
Timer Function\Using the host ID in host.json.

### ISSUE THREAD

**Issue by NohaNabawi** [Azure/Azure-Functions#809]
If  you have more than one function app with the same host ID, only one of them will run the timer trigger and the other timer trigger functions will not get triggered. Based on timer function design under the consumption plan , the timer will not start because another Function App has a lock on the timer.
I am suggesting having a warning message displayed to the user on creating multiple function apps with multiple timer functions .

**Comment by NohaNabawi** [comment]
Thanks for the info

**Comment by ColbyTresness** [comment]
Closing as I believe this has been resolved, please reopen if necessary

**Comment by CatchSandeepVaid** [comment]
Is specifying host ID is not recommended, then how to solve [this issue](https://github.com/Azure/azure-functions-core-tools/issues/1012)?
