### ISSUE TITLE
Document which properties support binding expressions

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#81]
See SO post here: http://stackoverflow.com/questions/40855278/how-do-you-apply-a-filter-at-runtime-with-a-node-js-azure-function-hitting-table

Most of our binding properties support binding expressions, but I'm not sure we make that clear anywhere. We should have (if we don't already) a general binding doc section that provides details on the binding pipeline, parameters, etc. Then we can link to this from other places.

Per binding, it would also be good to point out which properties support binding expressions. E.g. the filter property of TableBinding. Not all properties do.

**Comment by lindydonna** [comment]
@mathewc I've improved the info about binding parameters (see [Bind to custom input properties in a binding expression](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#bind-to-custom-input-properties-in-a-binding-expression)), but I don't have a list of what properties for each binding support binding expressions. 

How can I determine this?  Do I look at the code and look for the "autoresolve" attribute?
