### ISSUE TITLE
Consumption plan\ sandbox limits

### ISSUE THREAD

**Issue by NohaNabawi** [Azure/Azure-Functions#810]
Functions app under the consumption plan have sandbox limits. Is it possible that users receive a warning explaining that they are approaching those limits? What happens now is that the users will get exceptions like "Function host is not running" or "Listener cannot start " or the function app will stop running and they will not relate that to the consumption plan sandbox limits.

**Comment by mathewc** [comment]
We already output errors to the logs - the [Host Health Monitor](https://github.com/Azure/azure-functions-host/wiki/Host-Health-Monitor) is running in the host monitoring sandbox limits and logging errors / restarting when limits are hit. If you're running into the limits you should see these errors in your logs.

If you can share us some app details / timeframe we can take a look

**Comment by ColbyTresness** [comment]
Closing due to lack of customer response. Please repoen if necessary.
