### ISSUE TITLE
ARM `listSecrets` function does not work with custom routes

### ISSUE THREAD

**Issue by johndowns** [Azure/Azure-Functions#811]
The Functions ARM provider's [`listSecrets` function](https://github.com/projectkudu/kudu/wiki/Functions-API#getting-a-functions-secrets) allows for retrieving the trigger URL of a function. However, if using a custom route for the function (for example, to make a RESTful URL), the `listSecrets` function does not return the correct (custom) route.

For example, if I have a function like this:

```csharp
[FunctionName("UpdateCustomers")]
public static async Task<IActionResult> UpdateCustomers(
    [HttpTrigger(AuthorizationLevel.Function, "post", Route = "customers/update")]HttpRequest req)
{
    // ...
}
```

then my expectation would be that the trigger_url would be evaluated to "https://myfunctionapp.azurewebsites.net/api/customers/update". However, in fact it gets resolved to "https://myfunctionapp.azurewebsites.net/api/UpdateCustomers".

**Comment by mathewc** [comment]
This issue will be addressed by the work for https://github.com/Azure/azure-functions-host/issues/3994. Closing this in favor of that issue.
