### ISSUE TITLE
V2: Could not load file or assemby: System.Net.IPNetwork, Version=2.1.2.0

### ISSUE THREAD

**Issue by sebader** [Azure/Azure-Functions#813]
I'm using the following:

- VS2017 15.7.1
- Azure Functions and WebJobs Tools 15.0.40502.0
- Creating a V2 (.Net Standard 2) function that references Microsoft.NET.Sdk.Functions 1.0.13.

I'm referencing a custom .NET standard library that references the Nuget package System.Net.IPNetwork (https://www.nuget.org/packages/IPNetwork2/2.1.2)
Running the function locally in VS works fine. But when I publish it to Azure and execute it there, I'll get Could not load file or assemby: System.Net.IPNetwork, Version=2.1.2.0

I checked the /bin via Kudo folder and the DLL is definitely there. Already recreated it etc pp.
Any ideas how to solve this? 

Thanks a lot!

**Comment by daveh101** [comment]
I'm having similar issues with BinaryFormatter Serialization - I can make it work locally if I revert the tools back to 15.0.40424.0 - Doesn't work locally on 15.0.40502.0, and doesn't work when publishing to Azure

**Comment by sebader** [comment]
I just realized that I also doesn't work in my local debug environment anymore as well. I think there is a bigger issue with external references going on here?!

**Comment by sebader** [comment]
Ok, so this one seems to be rooted in the restriction regarding System.* namespace usage with the new Functions update.
