### ISSUE TITLE
Blob trigger bind should exclude when URL contains Thumbnails

### ISSUE THREAD

**Issue by Tirupathitemburu** [Azure/Azure-Functions#814]
I would like to unbind blob trigger if the path contains thumbnails. I tried with BlobTrigger("ProfilePhoto/*~thumbnails*/{name}" this. it's not working. Could you please help me here.

**Comment by paulbatum** [comment]
You will need to apply this logic yourself in the function code. There is no way to express it as part of the binding itself.
