### ISSUE TITLE
Function V2: Nuget package DocumentFormat.OpenXml 2.8.1 encounter exception

### ISSUE THREAD

**Issue by ExileLee** [Azure/Azure-Functions#816]
Hi everyone

I'm using the following:

VS2017: 15.7.1
Microsoft.NET.Sdk.Functions: 1.0.13
Function Enviroment: V2

I'm installing the Nuget package DocumentFormat.OpenXml 2.8.1 (https://www.nuget.org/packages/DocumentFormat.OpenXml)
Running the function locally works fine. But when I publish it to Azure  I'll get 
**Could not load file or assembly 'System.IO.Packaging, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Could not load the specified file.**

Does anyone encounter the same issue?

Thanks a lot!

**Comment by JohnReeson** [comment]
Test with [2.0.11857](https://github.com/Azure/azure-functions-core-tools/releases/tag/2.0.1-beta.29) locally, works. So just wait for the release to complete in Azure.

**Comment by JohnReeson** [comment]
`2.0.11888` release is complete everywhere. This issue has been solved.
