### ISSUE TITLE
timerTrigger functions with dashes in name don't run

### ISSUE THREAD

**Issue by kayone** [Azure/Azure-Functions#818]
When creating a timerTrigger function, if the function name contains a dash `-` the function refuses to run. and running it manually results in a 404

eg. 

``` json
{
  "disabled": false,
  "bindings": [
    {
      "name": "name-with-dash",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "*/5 * * * * *"
    }
  ]
}
```

**Comment by JohnReeson** [comment]
@kayone It's not the function name, it's the name that represents the timer object in function code. And dash is not supported for timer object name, only alphanumeric is valid.

![1](https://user-images.githubusercontent.com/35160013/40928470-1c6dbcd6-6854-11e8-91aa-c37138797970.png)
