### ISSUE TITLE
V2 - Service Bus Topic trigger not working?

### ISSUE THREAD

**Issue by sebader** [Azure/Azure-Functions#819]
I'm using the following:

- VS2017 15.7.1
- Azure Functions and WebJobs Tools 15.0.40502.0
- Creating a V2 (.Net Standard 2) function that references Microsoft.NET.Sdk.Functions 1.0.13.
- Microsoft.Azure.WebJobs.ServiceBus 3.0.0-beta5

I'm migrating an Azure Function with a Service Bus Topic trigger from v1 to v2. All compiles well and the function starts but it never gets fired by new messages in the topic. Is there a known issue or should this work?

        [FunctionName("MyProgressListener")]
        public static async Task Run([ServiceBusTrigger("mytopic", "mysubcription", Connection = "ServiceBusConnection")]string message, TraceWriter log)
  
ServiceBusConnection is set in the the local.appsettings.json to the SB connection string.

**Comment by marxxxx** [comment]
do you have an instance of the function also deployed to the cloud using the same subscription?

**Comment by sebader** [comment]
No, I created a new subscription to test with.

Am 26.05.2018 um 12:38 schrieb Markus <notifications@github.com<mailto:notifications@github.com>>:


do you have an instance of the function also deployed to the cloud using the same subscription?

**Comment by omgsarge** [comment]
Also getting this issue with functions v2, function works in local development environment with same keys & subscription settings. After publishing to Azure the function never responds to the messages put onto my topic.

**Comment by sebader** [comment]
@omgsarge it does work locally for you? Which functions tool version are you running? 15.0.40502.0 as well?

**Comment by omgsarge** [comment]
Yes works locally - same code when packaged & released to our Azure Function simply refuses to be triggered. Almost like the web-host has not have the config.UseServiceBus() method from the ServiceBus Nuget package invoked.

Our other V2 functions are working, HTTP Trigger, and Timers - I'm concerned these are the ones which do not rely on external registration of bindings via plugins. Our web-host starts up, but just does nothing.

Our runtime is 15.0.40502.0 yep

**Comment by sebader** [comment]
hmm, interesting. Now I just tried it again. And now it works locally as well as in Azure!? :) No idea what changed, but looks solved for me

**Comment by omgsarge** [comment]
What does your function.json look like? Ours was missing a few parameters like 'direction' and so forth, but even adding them in hasn't made a difference.

**Comment by omgsarge** [comment]
Was there more than one message to process on the queue at the time?

**Comment by sebader** [comment]
@omgsarge it's a topic, not a queue ;-) But yes, there are multiple messages to be processed. So normally "maxConcurrentCalls":1 should cover exactly that case and make sure that messages only get processed in sequence.

**Comment by omgsarge** [comment]
It should yes - we will need to enforce this too, so will let you know if we get the same issue

**Comment by rogersmj** [comment]
I'm having this same issue -- functions never trigger in v2 using a Service Bus topic subscription, but work fine locally.

@omgsarge , I'm also deploying via VSTS, but I'm not completely following how you managed to solve this. Do you mean that you created a function using the portal first, and THEN deployed your code into that function?

**Comment by rogersmj** [comment]
I figured it out. For anyone else suffering from the same "something in the mysterious Functions black box broke" pain, here's how to resolve:

1. Go to your function app in the Azure portal.
2. Click "+" next to Functions in the left panel, to start the process of creating a new function
3. Select "Service Bus Topic Trigger" from the list of template functions. This will bring up a blade telling you that extensions are not installed.
4. Click install, wait for the extensions to install, and then close the blade. You do not have to create a new function. The installed extensions will now allow your existing SB-triggered functions to work.

Clear as mud.

**Comment by omgsarge** [comment]
Yes, exactly what we had to do. It is tucked away in the MSDN documentation
but not obvious!

**Comment by jeffhollan** [comment]
@rogersmj @omgsarge  just confirming the function you published was from Visual Studio (C# class libraries)?  The workaround you described shouldn't be necessary so if so there may be a bug I want to make sure we are tracking

**Comment by sebader** [comment]
@jeffhollan I deployed my function from Visual Studio and didn't install the extension from the portal. In face, when I tried that after I read this workaround here, the installation through the portal never seemed to finish.
So as I wrote above, for me the Service Bus trigger seems to work in general, but the maxConcurrentCalls setting is not observed

**Comment by rogersmj** [comment]
@jeffhollan No, I did not publish from Visual Studio -- my function app is Node, and locally I use Visual Studio Code (on a Mac) but I build and deploy using VSTS. I develop purely locally, I don't use the in-portal editor, so when I create a new function it's first created on my local machine. Eventually it gets included in a build and deployed. The service bus trigger would not work at all in Azure until I did the workaround I described above.

**Comment by jeffhollan** [comment]
@rogersmj for yours you should be able to run a command (during build locally or in VSTS) of: func install extensions

That will do the same thing the portal is doing

**Comment by omgsarge** [comment]
@jeffhollan - nope, created the function object in the Azure portal itself - but hadn't enabled the service bus extensions, I think I incorrectly expected the presence of the service bus plugin dll to make it all work, but the documentation does clearly state you need to enable the extensions on the function resource itself so this must be working as intended?

**Comment by fgauna12** [comment]
I'm having the same issue reported.  I'm using:
- Visual Studio 15.8.7
- C# and V2
- `Microsoft.Azure.WebJobs.ServiceBus` version `3.0.0-beta5`

When I run it locally it says 
"The binding type(s) 'serviceBusTrigger' are not registered. Please ensure the type is correct and the binding extension is installed."

I tried following the instructions as here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#packages---functions-2x

**Comment by jeffhollan** [comment]
@fgauna12 many of the beta packages are no longer compatible with latest GA version. Version should be 3.0.1 for current bits

**Comment by fgauna12** [comment]
Ah yes sorry. I might have gotten confused with v1 package. Thanks

**Comment by sonic1981** [comment]
For me this issue was caused by using a v5 version of the `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package in a .Net Core v3.1 function app. Error message could be better. Downgrading that package to v3 fixed the problem
