### ISSUE TITLE
[Docs][WebJobs] Broken links on Getting Started page

### ISSUE THREAD

**Issue by christopheranderson** [Azure/Azure-Functions#82]
These two links are broken:
•	[How to use WebHooks with the WebJobs SDK, with examples for GitHub, IFTTT, and HTTP](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/WebHooks-Walkthrough)
•	[Azure WebJobs SDK Quick Reference (PDF download)](http://go.microsoft.com/fwlink/?LinkID=524028&clcid=0x409)

Quick reference needs to be fixed. The WebHooks needs to be removed.

**Comment by ggailey777** [comment]
@christopheranderson can you provide a link to exactly which page has the broken links? Thanks.

**Comment by christopheranderson** [comment]
https://docs.microsoft.com/en-us/azure/app-service-web/websites-webjobs-resources

**Comment by ggailey777** [comment]
@christopheranderson do you have the correct link for that PDF download? Perhaps the file got taken down?

**Comment by SyntaxC4** [comment]
https://jhaleyfiles2016.blob.core.windows.net/public/Azure%20WebJobs%20SDK%20Cheat%20Sheet%202014.pdf

**Comment by ggailey777** [comment]
Fixed download link: https://github.com/Microsoft/azure-docs-pr/pull/9130
