### ISSUE TITLE
Azure Functions Proxies - BLOB backend not working

### ISSUE THREAD

**Issue by JesperJakobsen** [Azure/Azure-Functions#820]
Hi,

I'm not sure what changed but since yesterday I'm not able to use a Proxy for a SPA hosted in BLOB storage, I get an error when i try to access the url.

> The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

The exact same file works in another Function App.

**Comment by jeffhollan** [comment]
@alexkarcher-msft

**Comment by JesperJakobsen** [comment]
I think that there was a few issues regarding Azure on this day, so it's not possible to replicate the issue as of now.
