### ISSUE TITLE
Azure Functions Runtime Preview 2 not connecting to local SQL Server

### ISSUE THREAD

**Issue by SujitGokhale** [Azure/Azure-Functions#826]
Hi,

On Azure Functions Runtime Configuration wizard, I have tried to connect to local SQL Server DBs including (localdb)\MSSQLLocalDB and .\SQLExpress (version 2017) but both do not work. I can connect to these DB servers from VS.NET 2015 and SSMS. Temporarily I opened all firewall TCP ports and applications but to no avail. 

The error I am getting is - 
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (Provider: SQL Network Interfaces, error: 26 - Error locating Server/Instance Specified).

On the other hand, I was able to connect to Azure SQL Server but I want to keep things locally. Would you please help?

Thanks,
Sujit

**Comment by apwestgarth** [comment]
Hi,
   you need to ensure that the tcp/ip protocol is enabled on your installation of SQL Server, here is the documentation on how to do this - https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-2017

Thanks

Andrew

**Comment by burf2000** [comment]
Did this work for you as I have dropped the firewall, enabled TCP-IP and still it wont talk to Azure installer

**Comment by imkheong** [comment]
@apwestgarth worked for me!

**Comment by gokhalesujit** [comment]
@apwestgarth and @burf2000 - thank you for the inputs. Apologies for delayed response. We ended up not pursuing preview version of Azure Functions Runtime. We are now using Azure Functions version 2 with VS.NET 2017 for development and so far it is all working great.

**Comment by fabiocav** [comment]
@SujitGokhale based on the comments/answers above, I'm closing this as answered. Please let us know if you need additional information.

**Comment by siata13** [comment]
In case someone else will have similar problems - in my case I didn't have 'SQL Browser' service started which caused the network specific issue (Azure Runtime Preview 2).
