### ISSUE TITLE
Not able to delete the FunctionApp

### ISSUE THREAD

**Issue by ssashok10** [Azure/Azure-Functions#827]
We created a FunctionApp using ARM template and the deployment went successful. However, we are seeing three strange behaviors,

1. When we click the "Stop" button on the Azure Portal, it says that "Failed to stop app "xxxx". However, we noticed that the FunctionApp is stopped in couple of minutes. It's the same behavior when we tried to "Start" the "FunctionApp"

2. We tried to delete the "FucntionApp" and it's in progress for the last couple of hours and it's still spinning.

**Comment by jeffhollan** [comment]
Confirming a few things:
1. You don't see this behavior in this subscription/type when creating from the portal?
1. If you can send any details of the ARM template - may be some config in there that is throwing things off.  Anything we can do help get a repro would be great
