### ISSUE TITLE
"Waiting for container start" / "Container not started" in Azure Functions Runtime Preview 2

### ISSUE THREAD

**Issue by trickpatty** [Azure/Azure-Functions#829]
I have Azure Functions Runtime Preview 2 installed according to https://docs.microsoft.com/en-us/azure/azure-functions/functions-runtime-install. I am able to complete installation and configuration without issue. When attempting to run a function, however, I see the following in the logs:

```6/1/2018 1:25:59 PM [SVR-FUNC] Provisioning container testapp_0
6/1/2018 1:25:59 PM [SVR-FUNC] 9994457ffb9d3a5d5e4cb86e1ed9e757595030d13bfa9033fb7d52401949d657
6/1/2018 1:26:03 PM [SVR-FUNC] Container testapp_0 has been created.
6/1/2018 1:26:03 PM [SVR-FUNC] Container testapp_0 has been created.
6/1/2018 1:26:56 PM [SVR-FUNC] Waiting for container start: testapp_0 (Total elapsed time: 00:00:53.0102334)
6/1/2018 1:27:48 PM [SVR-FUNC] Waiting for container start: testapp_0 (Total elapsed time: 00:01:45.0197409)
6/1/2018 1:28:58 PM [SVR-FUNC] Waiting for container start: testapp_0 (Total elapsed time: 00:02:55.0436867)
6/1/2018 1:30:08 PM [SVR-FUNC] Waiting for container start: testapp_0 (Total elapsed time: 00:04:05.0536982)
6/1/2018 1:31:20 PM No new trace in the past 1 min(s).
6/1/2018 1:31:18 PM [SVR-FUNC] Waiting for container start: testapp_0 (Total elapsed time: 00:05:15.0645844)
6/1/2018 1:31:57 PM [SVR-FUNC] Container not started: testapp_0
6/1/2018 1:31:59 PM [SVR-FUNC] Issuing stop command to container: testapp_0
6/1/2018 1:31:59 PM [SVR-FUNC] Error response from daemon: Cannot kill container: testapp_0: No such container: testapp_0
6/1/2018 1:32:00 PM [SVR-FUNC] Stop complete for container: testapp_0
6/1/2018 1:32:00 PM [SVR-FUNC] Container could not be started: testapp_0
```

I am running this on a physical system with Windows Server 2016 Version 1607 with Hyper-V and Containers enabled.

What should I do to get the containers running?

**Comment by trickpatty** [comment]
It looks like this is the same issue that is described in this forum post: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b6916e39-c46e-420b-a904-6f491f4c752d/does-not-start-normally-container-of-azure-functions-runtime-preview-2?forum=AzureFunctions.

It appears that when Azure Functions Runtime launches the docker container, it passes in a WEBSITE_INSTANCE_ID. If this value includes a slash ('/'), then the container will not be built correctly. This value is apparently auto-generated based on the computer name. I was unable to find a way to override this value.

The problem was resolved by simply changing the name of the computer. It took a couple of tries because even after renaming, the next variation also included a slash.

Hopefully this post will help someone else who runs into the same issue!

**Comment by jeffhollan** [comment]
Thanks for responding with the resolution - you are the real hero 👍 .  Closing for now only as I don't believe Azure Functions Runtime (onprem) issues are tracked here.  Looking into this
