### ISSUE TITLE
Node.js: document "isRaw" flag for responses

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#83]
See https://github.com/Azure/azure-webjobs-sdk-script/issues/942#issuecomment-263358417

**Comment by SyntaxC4** [comment]
We need to point out that XML is handled differently in the docs. This should probably also be investigated for C# functions, although, I doubt that it will have the same issue.

**Comment by fabiocav** [comment]
@SyntaxC4 can you expand on what you mean about XML? Also, when using raw responses, our content negotiation logic is completely bypassed, so all formats would behave the same way.

**Comment by ggailey777** [comment]
Added the isRaw flag to the response object reference [here](https://github.com/Microsoft/azure-docs-pr/pull/9679). 
@lindydonna Do you think an example of using _isRaw_ is necessary?

**Comment by lindydonna** [comment]
@ggailey777 No, I think reference is sufficient for now.
