### ISSUE TITLE
Publish to Azure menu option missing on OS X

### ISSUE THREAD

**Issue by dwhiteddsoft** [Azure/Azure-Functions#831]
Created a simple function using VS Community 2017 on OS X. Where I try to publish the menu option is missing. Version is 7.5.2 (build 40). 
<img width="373" alt="screen shot 2018-06-02 at 7 06 14 am" src="https://user-images.githubusercontent.com/4751106/40873693-80a0ec6e-6633-11e8-8036-f9cba1c844f2.png">
Am I missing something?

**Comment by jeffhollan** [comment]
Looking now but know this was on their backlog and may have slipped. I've asked the VS team for an update

**Comment by mrward** [comment]
Publishing Azure Functions projects is supported in Visual Studio for Mac 7.6 and later - https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-mac-relnotes-v7.6

Publishing ASP.NET Core projects to Azure was supported in earlier Visual Studio for Mac versions.

**Comment by ColbyTresness** [comment]
This is supported in VS For Mac 7.6 and later
