### ISSUE TITLE
High storage costs

### ISSUE THREAD

**Issue by makar-sasha** [Azure/Azure-Functions#832]
Hello
I have 5 functions (v2 beta) with low insensitivity (3 calls per minute for the most "popular" function with < 1 sec duration). However storage account cost is about 300$ per month (Standard IO - File Write Operation Units (in 10,000s)).  Interesting if I disable and enable one of the functions the traffic goes away. 
![5](https://user-images.githubusercontent.com/1519465/40904273-de414c64-67e2-11e8-9398-f6d3fc36dea7.jpg)
But unfortunately this hack works temporary. The function is pretty simple and fast (and rare)

        public static void Run([TimerTrigger("0 0 * * * *")]TimerInfo myTimer, TraceWriter log, ExecutionContext context)
        {
            log.Warning($"C# Timer trigger function executed at: {DateTime.Now}");
            var config = new ConfigurationBuilder()
                .SetBasePath(context.FunctionAppDirectory)
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();

            const string statement = ...
            using (var connection = new SqlConnection(config.GetConnectionString("SqlConnectionString")))
            {
                connection.Execute(statement);
            }
        }

Could you help to analyse what is the reason of this high file IO insensitivity and costs? 

COMMENT:
I see storage account File Transactions number is about 25K per minute again. I have disabled\enabled another function and the problem goes away. So it is not related to particular function. Also it is a consumption plan.

**Comment by joshdcar** [comment]
You could look in your storage to see the source of the activity but based on personal experience I've found most storage costs and activity are related to the logging and possibly with V2 they've got additional logging in there during the preview (just a guess). Have you considered disabling standard logging and\or use App Insights and see if you have reduced activities and costs (you have a lot more dials to control logging costs w/ App Insights as well).  To disabled the built in logging simply delete the AzureWebJobsDashboard app settings.

**Comment by makar-sasha** [comment]
thanks, I have enabled only app insights with low rate (10 messages per minute), recreated functions and storage account but the costs still are really high. 
![6](https://user-images.githubusercontent.com/1519465/40945351-18ce362a-6861-11e8-8f3d-da3e5e21a688.jpg)
when I disable\enable one of the functions it temporary resolves the problem. My functions only use azure sql and event hub so I don't understand what File System activity is going on.

**Comment by makar-sasha** [comment]
I have added one more function that updates function.json disable property of the first post function every minute. Looks like it resolves "300$ per month" problem. Please let us know when the problem will be resolved completely.
![7](https://user-images.githubusercontent.com/1519465/41095506-42d025d2-6a5a-11e8-9cc4-33e0992031b9.jpg)

**Comment by jeffhollan** [comment]
What is the function that was causing the issues?  Is it the one above that executes the SQL statement every hour?

**Comment by makar-sasha** [comment]
sorry, I'm not sure (looks like disable\enable for any function results in temporary fix) as we have returned to app service plan. After this all high cost file io traffic has disappeared.

**Comment by jeffhollan** [comment]
My suspicion based on that is that the cost is coming from the out-of-box telemetry dashboard (AzureWebJobsDashboard in app settings) where all traces and logs are stored. As @joshdcar mentioned in newer functions we are prompting to enable App Insights.  Assuming you have app insights enabled you can safely delete the connection string from AzureWebJobsDashboard application setting which won't hit your storage account with these logs.  Expect that may resolve as well.

Let me know if that works or if you are good for now and I can close issue or keep open as needed

**Comment by jeffhollan** [comment]
Ok - if you see it again or have more details (or others who may see this issue and have similar stuff) feel free to let us know
