### ISSUE TITLE
Visual Studio 2015 : After successfully setup of  azure tools for azure functions we not able to get template of Azure Functions on visual studio template selector

### ISSUE THREAD

**Issue by renishdadhaniya** [Azure/Azure-Functions#833]
Follow this link 
https://buildazure.com/2016/12/14/azure-functions-visual-studio-tools-preview/

![screenshot 206](https://user-images.githubusercontent.com/39939697/40957030-d8a5a27c-68b0-11e8-93ac-a61db4ea7303.png)

**Comment by paulbatum** [comment]
That post and the preview tools it mentions are both out of date.

You'll need to update to VS 2017 to get the supported tools. See here for info:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs
