### ISSUE TITLE
PowerShell .Net Standard 2.0 support

### ISSUE THREAD

**Issue by wobba** [Azure/Azure-Functions#834]
I understand the decision for traditional PowerShell not making it out of experimental for v1 of Azure Functions.

Can you share any loose thoughts about supporting PowerShell .Net Standard 2.0 in the future, as this probably would fit the Azure Functions v2 platform a lot better, and possibly scale a lot better.

**Comment by paulbatum** [comment]
See this issue for the latest and much discussion:
https://github.com/Azure/Azure-Functions/issues/585

I'm going to close this one as a duplicate.
