### ISSUE TITLE
Is there a way to remote debug a slot? 

### ISSUE THREAD

**Issue by vinguan** [Azure/Azure-Functions#835]
I want to remote debug a slot but it does not show me a option to do that in Azure Explorer.

**Comment by jeffhollan** [comment]
Remote debugging should behave the same on slots as they do on the base function.  This may be a bug on the Azure Cloud Explorer - not sure though. Also make sure you have enabled remote debugging in the application settings.

**Comment by vinguan** [comment]
Sorry a late reply on this. It seems to be indeed a Azure Server Explorer bug. The slots to debug in the Azure App Services show just fine.
