### ISSUE TITLE
Support for netcoreapp2.0?

### ISSUE THREAD

**Issue by hanblee** [Azure/Azure-Functions#836]
Instead of targeting netstandard2.0, is there a way to target a function app for netcoreapp2.0 (it has a hard dependency on a netcoreapp library)?

It looks like AWS Lambda allows one to target netcoreapp2.0 (https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-0-support-released/).

**Comment by paulbatum** [comment]
Tracked here, still more investigation required:
https://github.com/Azure/Azure-Functions/issues/805
