### ISSUE TITLE
Support for Chunked Transfer Encoding

### ISSUE THREAD

**Issue by jklim96** [Azure/Azure-Functions#838]
It seems that requests for Azure Functions with the header
`Transfer-Encoding: Chunked`
are rejected with a status code of 502. 

I am currently using the runtime version: 1.0.11702.0
I don't seem to have the issue when I'm running the function locally, which runs the runtime version: 1.0.11535

I don't believe this was an issue until the beginning of June (it only caught my attention that the header is causing the problem once it started breaking after that time), so perhaps there were some updates that caused this issue.

Thanks!
Jinkyu

**Comment by ahmelsayed** [comment]
can you share a repro?

**Comment by mathewc** [comment]
@jklim96 can you share a repro please?
