### ISSUE TITLE
Url binding issues in Azure functions??

### ISSUE THREAD

**Issue by sonumalik1990** [Azure/Azure-Functions#839]
I have created an azure function as below:

```csharp
[FunctionName("Test")]
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Anonymous, WebHookType = "genericJson")]HttpRequestMessage req, TraceWriter log)
{
}
```

and host.json:

```json
{
    "functions": [ "Test" ],
    "http": {
        "routePrefix": "api/webhooks/incoming",
        "maxOutstandingRequests": 20,
        "maxConcurrentRequests": 10,
        "dynamicThrottlesEnabled": true
    }
}
```

 "routePrefix": "api/webhooks/incoming", is mandatory to use.

Url : http://localhost:7071/api/Product/incoming/Test is working

Url: http://localhost:7071/api/webhooks/incoming/Test is not working

Please suggest.

**Comment by xscript** [comment]
Have you checked this [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#customize-the-http-endpoint)?

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#3000
