### ISSUE TITLE
Document that additional references are needed when using netstandard assemblies

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#84]
Since netstandard broke up system libraries into various NuGet packages, customers need to manually reference more things, which leads to confusion. See e.g. https://github.com/Azure/azure-webjobs-sdk-script/issues/980.

@fabiocav can provide scenarios that need to be documented. Samples might be the best option for this.

**Comment by SyntaxC4** [comment]
This should be included on here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp

**Comment by lindydonna** [comment]
We expect that most customers who use netstandard assemblies will use precompiled functions, where the Visual Studio tooling will do this automatically. Closing this issue.
