### ISSUE TITLE
Azure Functions Project and docker-compose

### ISSUE THREAD

**Issue by MichaelPetrinolis** [Azure/Azure-Functions#845]
In a VS2017 15.7.3 solution file with a docker-compose.yml , I added an Azure Function targeting netstandard2.0 and a dockerFile

I added the path to Dockerfile in docker-compose file, and from command line it builds and works as expected

From VS when targeting docker-compose, it fails with the following error

```
1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(294,5): error : Value cannot be null.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(294,5): error : Parameter name: stream
1>Done building project "docker-compose.dcproj" -- FAILED.
```

If I move the dockerFile to a folder named for example 'Docker' under Project's Directory and modify the docker-compose, it works as expected

**Comment by cgillum** [comment]
@ahmelsayed any ideas?

**Comment by ahmelsayed** [comment]
I never used VS Docker integration before. I'm not entirely sure it has to do with Functions, but I'll try to get a repro. 

@MichaelPetrinolis Would you mind sharing a bit more about your Dockerfile and docker-compose.yml setup?

/cc @vijayrkn in case he knows who in VS knows about Docker integration.

**Comment by MichaelPetrinolis** [comment]
Based on eshoponcontainers , I added an azure function project and have the following docker file
`FROM microsoft/azure-functions-runtime:v2.0.0-beta1 AS base
ENV AzureWebJobsScriptRoot=/home/site/wwwroot
WORKDIR /home/site/wwwroot

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY . .
WORKDIR /src/src/Services/Test/Test.Functions
RUN dotnet restore -nowarn:msb3202,nu1503
RUN dotnet build --no-restore -c Release -o /app

FROM build AS publish
RUN dotnet publish --no-restore -c Release -o /app


FROM base AS final
WORKDIR /app
COPY --from=publish /app .`


and the docker compose is

`version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.api:
    image: petricorp/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data

  test.api:
    image: petricorp/test.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Test/Test.API/Dockerfile

  test.functions:
    image: petricorp/test.functions:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Test/Test.Functions/Docker/Dockerfile`

if I move the dockerfile under the project's dir the error is thrown when running from VS, from command line is ok

**Comment by lisaguthrie** [comment]
The Visual Studio container tools do not currently support Azure Functions projects. We will consider this in a future version of the tooling. Thanks!

**Comment by jeffhollan** [comment]
Also as an aside the referenced image in the dockerfile was deprecated as noted on the Docker Hub page. Likely want to change Base to `microsoft/azure-functions-dotnet-core2.0`

**Comment by jeffhollan** [comment]
Closing per [lisaguthrie comment](https://github.com/Azure/Azure-Functions/issues/845#issuecomment-398230067).  SEems like this is an ask and feature request on the VS container tools.

**Comment by ashi20007** [comment]
Hi, Could you please please provide us with any timeline as to when this feature will released.

**Comment by tomkerkhove** [comment]
Any update on this?
