### ISSUE TITLE
Add host.json reference for v2

### ISSUE THREAD

**Issue by pragnagopa** [Azure/Azure-Functions#848]
We need V2 version of [functions-host-json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json) matching schema at [host.json schema](https://github.com/Azure/azure-functions-host/blob/dev/schemas/json/host.json)

**Comment by mathewc** [comment]
At the top of our wiki page is "Note: This page is no longer being updated, as it has been replaced by the host.json page on docs.microsoft.com." which was added by the doc team.

I think we've been keeping this wiki page up to date, but going forward the doc team wants us to move to the new online doc.

**Comment by jeffhollan** [comment]
If any doc items here for the docs paged referenced let me know. Can't quite parse it out from the details in this alone.

**Comment by fabiocav** [comment]
@brettsam has updated this. Closing as resolved.
