### ISSUE TITLE
Azure Function suddenly stopped being triggered by events from Event Hub

### ISSUE THREAD

**Issue by murugend** [Azure/Azure-Functions#852]
I have an event triggered Azure Function with non-default consumer group running on an app service plan. Yesterday it suddenly stopped being triggered by events from the Event Hub, until restarted some hours later. I am unable to find the cause of this.

Incoming/Outgoing messages to event hub:
![image](https://user-images.githubusercontent.com/20225583/41767193-4adb4012-7609-11e8-8963-5edd73fdf32d.png)
As you can see, the events come in continuously. But, around noon they stop flowing out. When the Function App is restarted the events flow out again. There are no errors on the Event Hub.

Server requests for Function App:
![image](https://user-images.githubusercontent.com/20225583/41767317-93aa1926-7609-11e8-9ce8-666dc505d953.png)
Even though the events flow into the Event Hub continuously, the Azure Function stops being invoked, until restart some hours later. There are no failures in the Function App.

I need to find the cause of this.

**Comment by tohling** [comment]
We will need more information to troubleshoot. Kindly open a new GitHub issue at https://github.com/Azure/azure-functions-host/issues/new and we will investigate.

**Comment by murugend** [comment]
Thanks. New issue created under azure-functions-host:
https://github.com/Azure/azure-functions-host/issues/3054
