### ISSUE TITLE
DataProtection AuthenticatedEncryptorDescriptorDeserializer version missmatch

### ISSUE THREAD

**Issue by oliverluethi** [Azure/Azure-Functions#857]
Hi there...

I'm using the NugetPackages "Microsoft.AspNetCore.DataProtection 2.1.1" and "Microsoft.AspNetCore.DataProtection.Extensions 2.1.1" in a .NET Standard 2.0 library, referenced in an AzureFunctions project.

Initializing of the DataProtectionProvider and Protector

`var destFolder = Path.Combine(System.Environment.GetEnvironmentVariable("LOCALAPPDATA"),"myKeys"); provider = DataProtectionProvider.Create( new DirectoryInfo(destFolder)); _protector = provider.CreateProtector("MyCache"); }`

If I try to protect a plain string `var encrypted = _protector.Protect(json);` I get the following message:

The type 'Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not assignable to 'Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Maybe I'm doing something wrong here? If referenced in a clean ConsoleApp the code runs as expected.

**Comment by tohling** [comment]
This is likely related on an known issue with binding redirects. Kindly see the ongoing thread here:
https://github.com/Azure/azure-functions-host/issues/992

Could you try this workaround and see if that would work for your use-case?
https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/
