### ISSUE TITLE
Running function published using func CLI returns 404.

### ISSUE THREAD

**Issue by bala16** [Azure/Azure-Functions#858]
Steps: (no consistent repro)
Create new linux consumption app. using func cli add httptrigger and timertrigger ( all default value)
publish the function app.

From the functions portal , you can see both the functions listed along with their function body. But running the function returns 404

**Comment by davidebbo** [comment]
It was caused by having `FUNCTIONS_WORKER_RUNTIME:"node"` and trying to run c# functions...
