### ISSUE TITLE
[VS2017] - Unable to change location of Storage Account once set

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/Azure-Functions#861]
When publishing a new Azure Function from VS 2017, I am given the ability to select the subscription, RG, Hosting plan, and Storage Account to be used by the Function. However, I can get in to a state where I can't change the location of the Storage account.

## Repro steps
1. Create a new Publish Profile for a new Azure Function
![image](https://user-images.githubusercontent.com/20270743/41873057-72d0d276-7889-11e8-8b6a-4886f415676c.png)

Note the storage account will be one that already exists in the chosen Subscription, if one is available.
2. Create a new storage account for the Function to use:
![image](https://user-images.githubusercontent.com/20270743/41873252-172bb53e-788a-11e8-837c-78e378a0500b.png)

Note this new Storage Account is in the same region as the Hosting Plan.
3. Change the region of the Hosting Plan
![image](https://user-images.githubusercontent.com/20270743/41873285-2bdb566a-788a-11e8-8ce7-6e589a01a734.png)

Observe the region of the Storage Account doesn't change:
![image](https://user-images.githubusercontent.com/20270743/41873294-31d1d238-788a-11e8-895d-6d1a044b2a6b.png)
4. Try to create a different new Storage Account:
![image](https://user-images.githubusercontent.com/20270743/41873314-3e5cfcee-788a-11e8-86c2-9c7fcb376beb.png)

observe it stays in the old region:
![image](https://user-images.githubusercontent.com/20270743/41873324-458f62e0-788a-11e8-9547-ca057fdfba00.png)

Now you can't get the storage account's location changed without restarting the Publish dialog completely.

## Workarounds
Change the hosting plan location before touching the storage account. If you neglect to do this, must restart the Publish dialog.

**Comment by jeffhollan** [comment]
@cartermp can you help track this

**Comment by cartermp** [comment]
Since this is in app service provisioning, I don't think it's functions-specific. cc @Andrew-MSFT

**Comment by Andrew-MSFT** [comment]
We'll add something to the backlog, to set expectations, at this point it'll have to be in Visual Studio 2019

**Comment by nzthiago** [comment]
@Andrew-MSFT so the publish functionality is ingrained into VS and can only be updated via a whole VS update?

**Comment by Andrew-MSFT** [comment]
The App Service provisioning dialog is part of the VS platform and can only be updated as part of a VS platform update

**Comment by brandonh-msft** [comment]
@Andrew-MSFT where are we at with this one? while doing a deploy this morning, I was able to finagle my way around the wizard to get **it** to say the right region for the storage account, but when the deploy happened, it didn't go to what was shown in the wizard; it went to what was shown previously (before my finagling)

**Comment by Andrew-MSFT** [comment]
Per my previous comments about setting expectations that we wouldn't be able to fix this until Visual Studio 2019, 2019 is still in early development (not even in public preview yet).  So still on the backlog, but will be a bit until the fix ships publicly.

**Comment by brandonh-msft** [comment]
my bad; thought we were talking about future state of VS, not the next major rev. I've seen quite a few changes come thru the func tools interface in the latest revs of '18, so thought it could've been bundled w/ one of those. Thanks for the clarifications.

**Comment by Andrew-MSFT** [comment]
We're able to update most of the components out of band from Visual Studio proper.  This dialog however is one of the few components that comes from the Core IDE and can't be updated via our extension.

**Comment by ColbyTresness** [comment]
This is fixed in VS19.
