### ISSUE TITLE
Outbound calls to a web service over SSL/TLS 1.0 started failing on June 12/13

### ISSUE THREAD

**Issue by larry-lau** [Azure/Azure-Functions#864]
My Azure Functions call an external web service that only support TLS 1.0.  It has been working great and suddenly the call started to fail on June 12/13 2018 time frame.    I don't have any control over the external web service to upgrade to newer TLS version. So am I left with option to migrate off Azure Functions?  Any other options?

**Comment by ColbyTresness** [comment]
@jeffhollan
