### ISSUE TITLE
Azure Functions and WebJob Tools throws  Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/Azure-Functions#865]
Hi, 

I'm Writing an Azure Function app with CosmosDB trigger with V2 functions.

It works well on the Azure Function App. 

However, when I execute on my local machine with Visual Studio, it through an error related Microsoft.Extensions.Configuration.Abstractions. 

I don't use that library, however, I install via nuget the exact version, it doesn't help. 
Maybe, we need to update Visual Studio Azure Functions and Web Jobs Tools. 

## Local: (Doesn't work)
* Visual Studio Enterprise 2017 Preview : Version 15.8.0 Preview 2.0
* Azure Functions and Web Jobs Tools : Version 15.8.2027.0  (seems latest)

## Azure: (Works)
* Runtime Version: 2.0.11888.0 (beta)

## Error message
```
 System.Private.CoreLib: Exception while executing function: DowntimeBatch. Autofac: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = DocumentService (ReflectionActivator), Services = [Services.IDocumentService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'DocumentService'. ---> The type initializer for 'Services.DocumentService' threw an exception. (See inner exception for details.) (See inner exception for details.). Autofac: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'DocumentService'. ---> The type initializer for 'Services.DocumentService' threw an exception. (See inner exception for details.). SharedLibrary: The type initializer for 'Services.DocumentService' threw an exception. SharedLibrary: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.
```

**Comment by gwendo** [comment]
I have the same problem locally.

**Comment by luismanez** [comment]
Same here :(

**Comment by luismanez** [comment]
This seems fixed for me with latest Azure SDK Tools (downloaded Today when running again locally the project in Visual Studio)

**Comment by Listenreich** [comment]
It still have the exception when running the function locally.
I'm using MS Azure Functions and Web Jobs Tools in version 15.0.40617.0 and Visual Studio 2017 15.7.4.

**Comment by ColbyTresness** [comment]
I believe this is fixed now - most up to date version tools version is 15.10.2046.0. Please reopen if that's not the case

**Comment by cjjohansen** [comment]
I Get similar error : Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.

All my nuget package references points to the same version 3.1.2.0

In my case it works locally but not on Azure

im using Microsoft.NET.Sdk.Functions-3.0.3
and running dotnetcore2.2
and running Runtime version: 2.0.13017.0 (~2)
