### ISSUE TITLE
 [Azure Functions Runtime] AzureFunctionsDockerDeamonForWindows service might not be installed.

### ISSUE THREAD

**Issue by rtumac** [Azure/Azure-Functions#869]
**Operating System**: Windows Server 2016

I installed the Azure Functions Runtime. I configured the Database, Credentials, File Share, and IIS tabs. When I got to Services, both the Azure Functions Host Activation Service and the Docker Service are not running.

When I click on the 'Start Service' button for Azure Functions Host Activation Service I get the following error message:

>  Cannot start service FunctionsHostActivationService on computer '.'.

Looking in Event Viewer:

> The Azure Functions Host Activaction Service service depends on the following service: AzureFunctionsDockerDeamonForWindows. This service might not be installed.

**Comment by jvano** [comment]
Please run the following commands to see the current state of these services:

```
C:\>sc query FunctionsHostActivationService
C:\>sc query AzureFunctionsDockerDeamonForWindows
```

**Comment by ColbyTresness** [comment]
Please reopen if necessary
