### ISSUE TITLE
[Feature request] Visual Studio Integration: When launching an Azure Functions project, add the project Name to the command prompt window to help distinguish between apps easily

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/Azure-Functions#873]
Hi,

I have a total of 5 function apps running as microservices that need to be executed a the same time. Currently, I end up with several command prompts with all the same visual appearance and title, making it difficult to distinguish which app is running in which window.

Adding the project name to the command prompt window title would help selecting the right app. Currently, I need to scroll up to check to log, trying to figure out which app is running in the window. 

It would be great if upon startup, Visual Studio would initialize the window title with the project name of the function.

Thanks!

**Comment by ColbyTresness** [comment]
This is something we won't be able to do, since we're just opening an executable. Maybe @vijayrkn would have a way but I'm closing for now.

**Comment by SimonLuckenuik** [comment]
Why not using System.Console.Title or something similar inside that executable? (https://docs.microsoft.com/en-us/dotnet/api/system.console.title?view=netcore-2.2)

Where would I need to raise the issue then if this is not in the scope of this project?
