### ISSUE TITLE
Timer trigger firing multiple times

### ISSUE THREAD

**Issue by hiraldesai** [Azure/Azure-Functions#875]
I am seeing an issue where a timer trigger is firing multiple times at the same time (a few microseconds apart from each other to be precise). 

Product version: V2
Runtime version: 2.0.11888.0 (beta)
Cron expression for the job: 0 0 20 * * *
Evidence: screenshot below
![image](https://user-images.githubusercontent.com/1005174/42342641-8c1e4924-804b-11e8-8c04-4da81b8d4105.png)

I'm running the function app under S2 app service plan (not consumption plan) with instance count of 5. I have now changed it to 1 as I don't need 5 right now but I have a feeling that might be what's causing it. I can provide more information via private message if required.

**Comment by fabiocav** [comment]
@hiraldesai looks like this issue happened on a beta version of the runtime. Can you please re-open if you run into any problems with the current service?
