### ISSUE TITLE
Use of IdentityDbContext not supported in Azure Function?

### ISSUE THREAD

**Issue by gizmo3399** [Azure/Azure-Functions#878]
I am trying to create an Azure Function that modifies some data in an SQL database.
I have setup EntityFrameworkCore in a separate .NETStandard 2.0 class library.
In the web project I configured EF for I make use of the Identity service provided by the web template (individual user accounts) therefore I use the `IdentityDbContext` over the regular `DbContext`.

I have referenced the class library in my functions project which is a (V2 preview azure functions project).

```cs
var options = new DbContextOptionsBuilder<HumbleGameKeysContext>();
var connectionString = Environment.GetEnvironmentVariable("ConnectionStrings:HumbleGameKeysContext");
options.UseSqlServer(connectionString);
return new HumbleGameKeysContext(options.Options);
```
If i instantiate my `DbContext` like above, I get the following error:
![image](https://user-images.githubusercontent.com/8982539/42414415-504cae22-8235-11e8-8d4a-a2f82a2788f5.png)
Even though this is the exact same way it is instantiated in the AspCore web project.

If I instantiate it without a connection string it creates a context but when getting all users on it I get the following error:
![image](https://user-images.githubusercontent.com/8982539/42414459-0d7bff52-8236-11e8-8b83-1cb39d63a965.png)

I am not sure if this is because it has no connection string, but I would expect some kind of connection error instead.

But when I change the `HumbleGameKeysContext` into a regular `DbContext` instead of a `IdentityDbContext` everything works fine and I can instantiate a context using the above code.
Retreiving data from the Database also works.
But for the function I want to write I actually need to access the `Users` DbSet which only exists on the `IdentityDbContext`.
I could separate the data I need to access into a separate table or I could maybe model the Users table myself. But I am interested to know if this can be supported out of the box.

But for now it seems that an `IdentityDbContext` is not supported or did I make a mistake anywhere?

I have used these tools and NuGet packages:
- Visual Studio 2017 v15.7.4
- Azure Functions and Web Job Tools extension v15.0.40617.0
- Azure Functions CLI tools v2.2.2
- Microsoft.AspNetCore.Identity.EntityFrameworkCore v2.1.1
- Microsoft.EntityFrameworkCore v2.1.1
- Microsoft.EntityFrameworkCore.SqlServer v2.1.1
- Microsoft.NET.Sdk.Functions v1.0.14

If anyone has got this working before or has any information that could help I would appreciate it.

**Comment by pragnagopa** [comment]
Can you please attach a simple repro project? It will make it easier to investigate.

**Comment by gizmo3399** [comment]
[Azure functions IdentityDbContext Repro.zip](https://github.com/Azure/Azure-Functions/files/2182286/Azure.functions.IdentityDbContext.Repro.zip)
Hi @pragnagopa 

I have attached a stripped down version of my project.
I have switched EF to use the in-memory database to make testing easier.

You can verify that the `IdentityDbContext` is working in the web project.
You can log in with the following credentials: username: `test@gmail.com` password: `Test123`

If you run the Azure functions project you will get the above mentioned error.
I have also included a `TestContext` which is based on the normal EF `DbContext` so you can verify that that one does not cause errors in the functions project.

I create the context in the `SetupDatabase` method of the `ResetClaimingPeriod` function

Please note that i was using .NET Core 2.1.1 SDK so you might need to install it.

If you need more info or having trouble running the repro project let me know.

**Comment by Doddler** [comment]
I created a bare-bones repository that cleanly represents the issue over at: https://github.com/Doddler/FunctionsIdentityTest

Function1 attempts to instantiate an empty context derived from IdentityContext. Function2 does the same for an context derived from DbContext. Function2 works, but Function1 always returns the following:

`[2018-07-19 9:42:52 PM] Executed 'Function1' (Failed, Id=e486157c-740c-4de5-8be1-d3d16e6bfe28)
[2018-07-19 9:42:52 PM] System.Private.CoreLib: Exception while executing function: Function1. FunctionsIdentityTest: GenericArguments[0], 'FunctionsIdentityTest.TestDbIdentityContext', on 'Microsoft.EntityFrameworkCore.DbContextOptionsBuilder`1[TContext]' violates the constraint of type parameter 'TContext'.`

**Comment by Doddler** [comment]
After additional testing, I found that downgrading the EntityFrameworkCore and Identity packages from 2.1.1 to 2.1.0 resolved the issue. Some kind of regression somewhere perhaps...?

**Comment by gizmo3399** [comment]
Thanks @Doddler!

I have also downgraded to version 2.1.0 of EF Core and Identity and can confirm it is now working
I also saw today that version 2.1.2 was available for `Microsoft.AspNetCore.Identity.EntityFrameworkCore` and tried with that. But sadly no luck.

I will use version 2.1.0 for now but hope this issue gets fixed so I can go back to the latest version later.

Thanks for your help!

**Comment by espray** [comment]
+1 downgraded to 2.1.0 as workaround

**Comment by pragnagopa** [comment]
@Doddler - Thank you for the detailed repro.
@fabiocav - Can you please take a quick look?

**Comment by fabiocav** [comment]
This is because that is currently flagged as a runtime restricted assembly and the runtime currently runs on 2.1.0. This will be updated on the next release.

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-host#3168

**Comment by pajohns** [comment]
Is there any update on this as to what version is supported? I tried using 2.2.2 and it didn't work, so reverted to 2.1.0 and works fine, so guessing not.

**Comment by shemseddine** [comment]
Any workarounds for v 2.2.0?
