### ISSUE TITLE
[Visual Studio] Should allow customizing the command line for running the Functions CLI

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#88]
This would allow changing the port and potentially other settings. For instance, the Functions CLI listens on port 7071 by default. This is configurable on the command line but not via Visual Studio.

**Comment by SimonLuckenuik** [comment]
Modifying to include `--cors` option would be interesting to see, I guess that with the complete customizing this will be supported.

**Comment by lindydonna** [comment]
@SimonLuckenuik We fixed the --cors option in the CLI in 0.9 btw.

**Comment by SimonLuckenuik** [comment]
@lindydonna, yes for the CLI, but it seems that visual studio tooling doesn't enable it by default, which forces to start the CLI manually rather than using F5 to use HTTP functions locally with an SPA web app. Unless, there is an updated visual studio tooling preview update that I missed.

**Comment by ahmelsayed** [comment]
Here is a hacky workaround that I personally usually use for situations like this :)
It utilizes a [Windows feature for debugging](https://msdn.microsoft.com/en-us/library/a329t4ed(VS.71).aspx)

Steps:
1. Create this powershell script somewhere on your machine (or really you can rewrite the same logic in your favorite language)

``` powershell
$exe = $args[0] -Replace "func.exe", "_func.exe"
$exeConfig = -join($exe, ".config")

# You can no longer launch the original exe.
# Any call to CreateProcess with "func.exe" as a file name will launch this
# script instead. Therefore, we need to create a copy of the executable.
if (!(Test-Path $exe) -Or !(Test-Path $exeConfig))
{
    Copy-Item $args[0] -destination $exe -force
    $config = -join($args[0], ".config")
    Copy-Item $config -destination $exeConfig -force
}

$command = "$args"
# Only match the exact command VS uses
# Leave other CLI scenarios untouched.
if ($args.Length -eq 5 -And
    $args[1] -eq "host" -And
    $args[2] -eq "start" -And
    $args[3] -eq "--port" -And
    $args[4] -eq "7071")
{
    # Add whatever cors you like in here
    $command = "$args --cors http://www.test-cors.org,https://functions.azure.com"
}

$command = $command -Replace "func.exe", "_func.exe"

Invoke-Expression $command
```

2. Open `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\currentversion\image file execution options` in regedit, and add a new key called `func.exe`
3. Add a `REG_SZ` named `Debugger` value `powershell.exe -NoProfile -ExecutionPolicy unrestricted  -File "C:\Path\to\script\above.ps1"`

![image](https://cloud.githubusercontent.com/assets/645740/22271006/4da9b730-e247-11e6-95e6-0349c1ee73cf.png)

4. F5 in VS
5. [Test](http://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Flocalhost%3A7071%2Fapi%2FHttpTriggerCSharp%3Fname%3Dtest&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)
6. Profit?

**Comment by dapaxx** [comment]
Is there any update on this issue?
This is especially a problem, if more than one user is working on one machine...

**Comment by lindydonna** [comment]
@dapaxx I would recommend using precompiled functions with a Web Project, customizing the start action. From there, you can choose the port. See https://aka.ms/precompiled-functions.

**Comment by lindydonna** [comment]
Handled in new tooling
