### ISSUE TITLE
Cannot delete Azure Function

### ISSUE THREAD

**Issue by tiloc** [Azure/Azure-Functions#885]
I have gone through the following sequence of steps:
- Created 3 Azure functions in Visual Studio 2017 and successfully deployed them
- Removed one of the functions from my VS project, deployed again

Now, whenever I look at the functions in the Azure Portal, the removed function is still listed. Clicking on it occasionally throws a red message box to the effect that a function with that ID no longer exists. Trying to delete it in the "Manage" section is not possible. The delete button is grayed out, as this function is allegedly managed through the VS deployment and cannot be touched manually.

How do I get rid of this stale function?

**Comment by tiloc** [comment]
I have found a current workaround: Setting the "delete existing files" option during publishing fixes the situation. But would expect something more intuitive.

**Comment by ConnorMcMahon** [comment]
@tiloc, if you have a concrete idea of how to make this process clearer or more intuitive, I would recommend creating another issue with your suggestion and label it as an improvement. As is, there isn't a bug here that matches the title description, so I'll be closing this issue.
