### ISSUE TITLE
Can I change ConnectionMode of DocumentDB when use DocumentDBClient binding?

### ISSUE THREAD

**Issue by meomeo0110** [Azure/Azure-Functions#886]
Hi everybody,

I have a Azure function that uses DocumentDBClient output binding.
```
 {
      "type": "documentDB",
      "name": "dbClient",
      "databaseName": "my-db",
      "createIfNotExists": false,
      "connection": "DocumentDbConnStr",
      "direction": "out"
}
```

I want to change connection mode of DocumentDB binding to Direct, but I cannot found documentation about setup "ConnectionMode" in function.json
In other hand, I try to set: 
`dbClient.ConnectionPolicy.ConnectionMode = ConnectionMode.Direct.`
However I wonder whether this code above is applied to binding dbclient.
Please help me confirm or guide me how to check.
Thank in advance.

**Comment by kashimiz** [comment]
@meomeo0110 , are you running your function app on a consumption or app service plan? 

If you're running on a consumption plan, [Cosmos DB recommends keeping your connection policy in Gateway Mode.](https://stackoverflow.com/questions/51363447/cosmosdb-direct-w-tcp/51371348#51371348) Direct Mode opens several outbound connections by design, which hits a consumption plan's limit on number of open socket connections.

**Comment by meomeo0110** [comment]
Hi Kashimiz,

I am using app service, the number of connection is not problem. Current is around 300 ~ 600
I hope Azure team can add setting: "ConnectionMode" in function.json in future.

**Comment by kashimiz** [comment]
@ealsur for Document DB binding.

**Comment by ealsur** [comment]
This is possible, you can set it on the `host.json` file and it will affect all the `DocumentClient` instances created in the Functions within (for bindings and trigger): https://github.com/Azure/azure-functions-host/blob/v1.x/schemas/json/host.json#L286

If you are using the Webjob Extensions, this can also be set on the `DocumentDBConfiguration` instance.

**Comment by ealsur** [comment]
I referred to a JSON Schema, that describes the possible attributes and values.

So:

{
"documentDB": {
"connectionMode":"Direct",
"protocol":"Tcp"
}
}

This also depends on the DocumentDB Extension Package version, I'm not familiar with which started including this, but I'm assuming the latest one should.

For that, probably someone in the Functions team can specify ??
________________________________

**Comment by meomeo0110** [comment]
Thank you very much, @ealsur!
It works.
