### ISSUE TITLE
[document issue] Could you change the requirement for Azure functions on ILB ASE  ?

### ISSUE THREAD

**Issue by mekamata** [Azure/Azure-Functions#887]
I think this sentence is not exactly. :
The machine accessing the portal must be **in the same VNET** as your ILB ASE
(From https://github.com/Azure/Azure-Functions/wiki/Using-Azure-Functions-on-an-ILB-ASE)

Because I can use azure functions on ILB ASE in this case:
on-premises environment -> ER（Private Peering） -> VNET (Functions on ILB ASE)  

In Addition, this documet says :
Both Functions and web jobs are supported on an ILB ASE but for the portal to work with them, you must have network access to the SCM site. This means your browser must either be on a host that is either in **or connected to the virtual network.**
(From https://docs.microsoft.com/en-us/azure/app-service/environment/create-ilb-ase#web-jobs-functions-and-the-ilb-ase. )

Therefore , I think this sentence is better :
The machine accessing the portal must be on a host that is either **in or connected to the same VNET** as your ILB ASE .

Thank you.

**Comment by fabiocav** [comment]
@alexkarcher-msft can you take a look at this and properly route?

**Comment by alexkarcher-msft** [comment]
The document has been updated! Thanks for the advanced heads up!
