### ISSUE TITLE
Geo-availability integration a la CosmosDB for Consumption Plan

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/Azure-Functions#890]
Not sure where else to file this idea/feature request so thought I'd do it here.

For Functions in a Consumption Plan, it's a bit arduous to get them to be geo-distributed (have to set up deployment to all the various regions you want to support, add APIM/Traffic Manager to handle). It would be *super* awesome if Functions had a setup like CosmosDB where you deployed them once, then "lit up" the geos you want the code replicated to. Then, not too much different than the request in #214 , an "invisible" Traffic Manager service could be provided on the endpoint for the Function to hit the nearest geo to the end user.

Just thought I'd toss it out there!

**Comment by ColbyTresness** [comment]
This isn't currently planned. It would be great if you could add an item to our UserVoice though, since that's where we more frequently track long term feature area requests. https://feedback.azure.com/forums/355860-azure-functions

**Comment by brandonh-msft** [comment]
done! [created here](https://feedback.azure.com/forums/355860-azure-functions/suggestions/36968170-geo-availability-integration-a-la-cosmosdb-for-con)
