### ISSUE TITLE
How to catch exceptions thrown by output bindings in azure functions?

### ISSUE THREAD

**Issue by SainiAshish** [Azure/Azure-Functions#891]
Currently there is no way to catch the exception thrown by output binding in azure functions. Filters are there but they are still in preview and hence cannot be used in production.

Also the behavior is different for different output bindings.
In case of service bus we can put the code to add the message to service bus queue n try catch and it is able to catch the exceptions. But in case of eventhub output it didn't throw exceptions and there is no way to catch that exception. 

Apart from filters is there any way we can catch the output binding errors?

**Comment by marxxxx** [comment]
Are you using IAsyncCollector or ICollector ? 
For the output bindings i use (CosmosDb, BlobStorage and TableStorage), when you use IAsyncCollector and call FlushAsync() on the binding, the operation is executed and you are able to catch errors related to that operation.

**Comment by kashimiz** [comment]
The approach @marxxxx describes is what we recommend for catching exceptions thrown by output bindings in C#. (This approach unfortunately won't work for non-.NET languages such as JavaScript.)

**Comment by SainiAshish** [comment]
Thanks @marxxxx and @kashimiz 
For output bindings what is the retry mechanism. Can we set the retry policy for output bindings.
Does it handle the transient error itself and retry them or developer has to take care of these?

**Comment by kashimiz** [comment]
Unfortunately we don't have an explicit retry policy for output bindings. As the developer, you'll need to catch and handle transient errors within your code.
