### ISSUE TITLE
BindAsync inside a parallel.Foreach

### ISSUE THREAD

**Issue by Lakshminarayana537** [Azure/Azure-Functions#892]
Hi,

I am facing an issue with BindAsync inside a parallel.Foreach loop.
We are trying to push multiple blobs to the Blob storage using Azure function . For this, we came across Binder.BindAsync. 

But facing below error.

Error : This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

Parallel.ForEach(carlist, async (requestInfo)=>
       {
            outputJSON = ProcessURLAsync(requestInfo.ToString(),outputJSON,token.access_token,log);
            tasks.Add(outputJSON);
            var attributes = new Attribute[]
            {    
                new BlobAttribute($"mystoragecontainer/{requestInfo}"),
                new StorageAccountAttribute("myStorage_STORAGE")
            };
            using (var writer = await binder.BindAsync<TextWriter>(attributes)) 
            {
               writer.Write(outputJSON.Result);
            }
       });

**Comment by kashimiz** [comment]
Hi there. This is a warning that shows up when you've written an async method without 'await' operators in its body, as it says. It's unclear which line of your code the error is referring to. It also looks like your environment is treating it as an error. Check if you have the ['treat warnings as errors' option checked](https://stackoverflow.com/questions/2520853/warning-as-error-how-to-rid-these) in Visual Studio.

**Comment by Lakshminarayana537** [comment]
Hi Kashimiz,

Thanks for the reply.
sorry. Its warning. Not error.
Warning: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

Will binder.async works with azure functions? our requirements is to bind multiple blob files parallely using azure functions(output azureblobstorage) using binder.async object.

**Comment by kashimiz** [comment]
Yes, Binder.BindAsync works with Azure Functions. There's an (example of this usage)[https://github.com/Azure/azure-functions-durable-extension/blob/master/samples/precompiled/BackupSiteContent.cs#L73] in the Durable Functions extension's samples you can refer to.

**Comment by Lakshminarayana537** [comment]
Thank you. This worked.
