### ISSUE TITLE
Content type application/json inside the Bindasync

### ISSUE THREAD

**Issue by Lakshminarayana537** [Azure/Azure-Functions#895]
Hi all,

I am using binder.bindasync to perform multi output binding to azure storage. But the content type is always set as "octa-stream", how can we modify the content-type to "application/json" using binder object??
Below is the code. 

 var attributes = new Attribute[]
            {    
                new BlobAttribute($"Containername/{filename}"),
                new StorageAccountAttribute("storage account")
            };

 using (var cloudBlob  = await binder.BindAsync<TextWriter>(attributesOrg)) 
            {
                cloudBlob.Write(outputJSON.Result)
            }

**Comment by mathewc** [comment]
You should be able to bind to a CloudBlockBlob (e.g. `binder.BindAsync<CloudBlockBlob>(attributes)`) and use the CloudBlockBlob APIs to set the ContentType.

**Comment by Lakshminarayana537** [comment]
Ok. Thank you so much. Its working now.
