### ISSUE TITLE
Text version of Create Azure Connected function

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/Azure-Functions#9]
This is making a "transcript" of the video version

**Comment by rachelappel** [comment]
First draft is up
https://acom-sandbox.azurewebsites.net/en-us/documentation/articles/functions-create-an-azure-connected-function/?rnd=1

**Comment by SyntaxC4** [comment]
In "Step 3" of the Queue Trigger, could you replace the quotes around the Cron expression, and instead use an inline code block? This will make it much easier to be copied and also make it stand out to the reader

**Comment by SyntaxC4** [comment]
There is one formatting issue, where the ordered list breaks back to 1. instead of  5. If we could get that addressed to avoid confusion, that would be great as well.
