### ISSUE TITLE
[Visual Studio] No way to add references to the funproj projects

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/Azure-Functions#90]
Hi,
In order to be able to unit test my functions and leverage compilation, I keep the code found inside the csx to a minimum, and the actual implementation of the function is in an external assembly (csproj in same solution).

Currently, there is no way to add those references to funproj project:
1) the external assemblies are not getting published along with my Functions
2) when starting debugging, external assemblies are not recompiled (since not a reference/dependency), so I am sometime debugging the wrong version of the code.

In order to achieve my need, I currently use a simple Web site csproj, and everything works fine for the deployment. It would be nice if funproj would behave like a normal project for those aspects.

Thanks!
Simon

**Comment by brbarnett** [comment]
+1

**Comment by wesselkranenborg** [comment]
+1

**Comment by gdgudmundson** [comment]
+1

**Comment by markanewman** [comment]
+1

**Comment by DarkNoir** [comment]
+1000000000000000

**Comment by skorunka** [comment]
+1

**Comment by lindydonna** [comment]
Just wanted everyone to know we're listening and totally agree this is an important feature, particularly with the precompiled function support (https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions). 

This is certainly the top feature request for the VS tooling and we'll try to make sure the next update to the tooling has this in place.

**Comment by lindydonna** [comment]
@SimonLuckenuik Here's a workaround for getting your assembly to build when you run the function project: right click on the function project, and go to Build Dependencies -> Project Dependencies. 

![image](https://cloud.githubusercontent.com/assets/4260261/21870492/80d073f0-d811-11e6-9e8d-791c48e1a45e.png)

**Comment by lindydonna** [comment]
FYI you can also upvote this UserVoice request: https://feedback.azure.com/forums/355860-azure-functions/suggestions/17709979-visual-studio-tooling-for-precompiled-functions

**Comment by thduttonuk** [comment]
Any update on when the tooling will be updated to allow adding project references?

**Comment by lindydonna** [comment]
@thduttonuk We're working on it, but don't have a date to share. In the meantime, you can use precompiled functions with a web project. That will give you all the VS features you're used to. Here's a blog post with details: https://aka.ms/precompiled-functions

**Comment by lindydonna** [comment]
Handled in new tooling, which will come out soon
