### ISSUE TITLE
Functions v2 - Cannot bind parameter 'log' to type TraceWriter 

### ISSUE THREAD

**Issue by richardrobberse** [Azure/Azure-Functions#900]
Whenever I call my published azure function it results in the following error:
Cannot bind parameter 'log' to type TraceWriter. Make sure the parameter Type is supported by the binding.
The same happens if I use the ILogger instead of the TraceWriter, am I missing something?

Error indexing method 'GetScriptsDownloadUri.Run'
Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

#### Investigative information
- Timestamp: 2018-07-25T19:35:04.560
- ProblemId: System.InvalidOperationException at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer+<IndexMethodAsyncCore>d__20.MoveNext
- Function App version: 2.0-beta
- Function App name: navbaasbuildapi-test
- Function name(s) (as appropriate): GetScriptsDownloadUri
- Invocation ID: N.A.
- Region: West Europe

#### Repro steps
Standard HTTP Trigger function with the following signature: 
```csharp
public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", Route = null)]HttpRequest req, TraceWriter log)
```

**Comment by brettsam** [comment]
This often happens due to a version mismatch between what you're running locally and what you're running when deployed. 

It looks like you may be building a functions v2.0 applicaiton locally, but you're deploying to a functions v1.0 site (I see your site is using v1.0.11913.0).

**Comment by richardrobberse** [comment]
oh that's weird, thanks for the hint, I'll look into the deployment!

**Comment by richardrobberse** [comment]
You're completely right, how did I miss that eh?
Thanks again 👍

**Comment by timmyreilly** [comment]
How do you recommend configuring the Site Version? When I push to Azure it defaults to v1 and in the Function App Settings won't let me change Runtime Version: "Cannot Upgrade with Existing Functions Major Version upgrades can introduce breaking changes..." But if I create another function app I can't push to it... "please change the version using the the portal or update your FUNCTION_EXTENSION_VERSION appsetting and retry..." I'm able to build and test locally... Any ideas?

**Comment by richardrobberse** [comment]
I've initially created the function app in Azure as v2 and I push to it from a VSTS release so pushing to it should definitely be possible, however I can't help you with how to do it.
