### ISSUE TITLE
Azure logic apps (Add a condition is not visible)

### ISSUE THREAD

**Issue by Lakshminarayana537** [Azure/Azure-Functions#901]
Hi Logic apps team

Are there any new patches released to azure logic apps?
 We were not able to see the "add a condition" option after a new trigger created. What we are seeing only two options now "Add an action" and "Add a parallel branch" options only.
We tried many like created new logic app, created a simple connector, but there is no "Add a condition" option now. Earlier we were able to see this option.

Please fix this issue.

![logicappissue](https://user-images.githubusercontent.com/41471449/43439283-33c49f3e-94b0-11e8-98c9-b45ce25e1f3f.png)

Regards,
K. Lakshmi.

**Comment by Lakshminarayana537** [comment]
Hi Experts,

Please help on my request.

Regards,
K. Lakshmi.

**Comment by paulbatum** [comment]
This github repository is for azure functions.

I suggest you ask your logic app question in one of these places:
https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=azurelogicapps
http://stackoverflow.com/questions/tagged/azure-logic-apps

**Comment by RebelSyntax** [comment]
Just FYI, the Condition can be found by looking for the Condition Control in the Actions sub menu.  

![image](https://user-images.githubusercontent.com/11604180/43665938-e56f371c-973f-11e8-9b29-4b449e606a42.png)

**Comment by drmabuzo** [comment]
> Just FYI, the Condition can be found by looking for the Condition Control in the Actions sub menu.
> 
> ![image](https://user-images.githubusercontent.com/11604180/43665938-e56f371c-973f-11e8-9b29-4b449e606a42.png)

Thanks, this help me
