### ISSUE TITLE
CosmosDB Trigger won't trigger

### ISSUE THREAD

**Issue by thejasondt** [Azure/Azure-Functions#903]
## Steps to reproduce
Create new azure function app in app service basic 1 
Create a cosmos sql document DB with DB and Collection
Point a Function App CosmosDB trigger to said Collection

## Expected  behavior
CosmosDB Trigger should trigger when document in the DB change

## Actual behavior
CosmosDB Trigger work at first and after a bit of time it stops triggering

## Environment data
Runtime v2(beta)
node: 8.11.1

Doing a Function Health Check provides:

Info | Functions that fail to initialize will never be triggered and appear offline.
-- | --
Current Functions in error | The following 1 functions are in error: <cosmostrigger-name>: Invalid character after parsing property name. Expected ':' but got: }. Path 'bindings[0].createLeaseCollectionIfNotExists', line 13, position 4.

This is odd as I am checking the function.json

{
  "bindings": [
    { 
      "type": "cosmosDBTrigger",
      "name": "input",
      "direction": "in",
      "leaseCollectionName": "leases",
      "connectionStringSetting": "DB",
      "databaseName": "DBN",
      "collectionName": "collection",
      "createLeaseCollectionIfNotExists": true
    }
  ]
}

The createLeaseCollectionIfNotExists is firstly on line 11, not 13, and secondly, it has ":" and not "}" following the property name.

I am not sure if over time something is causing the reading of the function.json to corrupt over time? 
If I restart the Function it again works for a bit before the error appears.

NB I have another cosmostrigger in the same function, pointing at a different collection (has leases in the same collection) that works fine.
I have tried deleting and recreating the trigger and collection all which again makes it work then stop working.

**Comment by mhoeger** [comment]
Can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? And could we also get the name of the function that works vs. the one that fails? Thanks!

**Comment by thejasondt** [comment]
Can I send it to the email on your profile?

**Comment by mhoeger** [comment]
Yes - that would be great!

**Comment by thejasondt** [comment]
@mhoeger - emailed

**Comment by adrianknight89** [comment]
@mhoeger 

My Cosmos DB trigger won't work either despite the fact that I followed the documentation (unless I'm missing something obvious...)

```
[FunctionName("CosmosTrigger")]
public static async Task RunAsync([CosmosDBTrigger("MyDB", "MyCollection", ConnectionStringSetting = "MyConnectionString", LeaseCollectionName = "leases", CreateLeaseCollectionIfNotExists = true)]IReadOnlyList<Document> documents)
{
     // process code
}
```

I was able to deploy it successfully, but it never gets hit. My functions are zip deployed. Would this cause the problem? I really don't know where to go from here...

**Comment by ColbyTresness** [comment]
Assuming this is done.
