### ISSUE TITLE
Consolidate all application insights into one

### ISSUE THREAD

**Issue by Lakshminarayana537** [Azure/Azure-Functions#905]
Hi Experts,

We have 10 Azure functions with 10 application insights[Each function has 1 app insight].

We are looking to consolidate 10 application insights into single application insight[Many to one]

**Example : 10 Azure functions --> 1 application sight[Should contain 1 to 10 azure functions telemetry 
 or log data]

Is this possible? if yes please guide. Thank you.

Regards,
K. Lakshmi.

**Comment by paulbatum** [comment]
Yes, simply configure each of your function apps with the same value for APPINSIGHTS_INSTRUMENTATIONKEY (you can find this in App Settings).

**Comment by paulbatum** [comment]
I'm going to close this as answered.
