### ISSUE TITLE
IAsyncCollector<string> parameter binding error in 2.x Function

### ISSUE THREAD

**Issue by josh-endries** [Azure/Azure-Functions#906]
I'm getting a parameter binding error in a v2 Function with this signature:

    [FunctionName("ElapseTimer")]
    public static async Task ElapseTimer(
        [TimerTrigger("%" + AppSetting.ScheduleExpression + "%")] TimerInfo timerInfo,
        [EventHub("%" + AppSetting.HubName + "%", Connection = AppSetting.HubConnectionString)] IAsyncCollector<string> eventHubAsyncCollector,
        CancellationToken cancellationToken,
        ILogger webJobLogger
    )

This works fine locally and deployed in v1 (with `TraceWriter`). In v2, *when deployed to Azure*, it says it can't bind the `IAsyncCollector` parameter. It works without issue locally. The [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs) say:

> To write multiple messages, you can use ICollector<string> or IAsyncCollector<string> in place of out string.

But they don't explicitly say v1 or v2. The project was created using the new project wizard in VS2017 with the latest SDK package (1.0.14 I believe it is), although I've tried every version back to 1.0.10 and it made no difference in the outputted `function.json` file (I saw other people try this with similar errors).

**Comment by josh-endries** [comment]
I was able to get the same exception (null reference) locally, though I'm not 100% sure if it's the same problem. This one is being caused somehow by line 114 in this file (line 118 in my error or through sourcelink):

https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/EventHubConfiguration.cs

Though if I debug it, nothing is null... I have three functions that use the same hub, and if I comment out two of them, it seems to work fine, so it seems like some sort of race condition or something.

**Comment by josh-endries** [comment]
Creating an EventHubClient manually works fine so I can just go that route and give up on the retarded magic parameter crap. I'm really tired of all the problems with Functions.

**Comment by paulbatum** [comment]
Thanks for the bug report! It looks like the latest bits were missing a fix for this. I just opened a PR:
https://github.com/Azure/azure-webjobs-sdk/pull/1835
