### ISSUE TITLE
Azure function .net core(v2) GA estimated date

### ISSUE THREAD

**Issue by vjhbtigoyal** [Azure/Azure-Functions#907]
Hi,
Do we have any estimated timeline for GA of v2. We are planning to start a project and wanted to decide on framework based on this timeline. I couldn't find about this on internet.

Thanks,
Vijay

**Comment by mhoeger** [comment]
See this comment here:
https://github.com/Azure/app-service-announcements-discussions/issues/63#issuecomment-411533901
