### ISSUE TITLE
CI/CD doesn't remind me of the runtime mismatch as VS publishing does

### ISSUE THREAD

**Issue by JohnReeson** [Azure/Azure-Functions#908]
When I publish a v2 function from VS to a new created Function app(whose runtime is ~1 by default), VS will read Application settings and ask me whether to update Function runtime version to beta on Azure.

But If I use  CI like Git to deploy my code, no related warning or message is shown. So is it possible to tell the runtime difference during CI/CD and inform us of the change, or just update runtime automatically if the confirm is not necessary?

**Comment by paulbatum** [comment]
The infrastructure that accepts deployments via git, etc knows nothing about the contents of what is being deployed and cannot infer things based on that contents. VS on the other hand does understand the contents of the app and is able to show these prompts.

Once you're using CI/CD, its basically expected that you have the appropriate combination of code + configuration. I would suggest that you just make sure that for any repos/branches you have that are using V2 code, you hook those up to apps that are configured to run as "beta". 

Or, you could write your own deployment scripts that do the version checking yourself. You could use the [azure cli](https://docs.microsoft.com/en-us/cli/azure) to retrieve and set app settings (e.g. detect the app is V1, update to V2).

Closing this one as answered - let me know if you need any additional info.

**Comment by JohnReeson** [comment]
@paulbatum Thanks for your detailed explanation!
