### ISSUE TITLE
WebJobs NuGet packages should be tagged with AzureFunctions

### ISSUE THREAD

**Issue by paulbatum** [Azure/Azure-Functions#909]
WebJobs core and extension packages are used as part of the .NET developer experience for Azure Functions and should be tagged appropriately so that users can easily find them via NuGet.

**Comment by ColbyTresness** [comment]
@paulbatum is this still relevant?

**Comment by paulbatum** [comment]
Looks I forgot to close this. If you look at https://www.nuget.org/packages/Microsoft.Azure.WebJobs you'll see its now appropriately tagged.
