### ISSUE TITLE
[Visual Studio] Suggestion: Function project should leverage the CLI at compile time in order to validate the scripts and project structure

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/Azure-Functions#91]
Hi,
Currently, it seems nothing happens when building the funproj projects from Visual Studio. I would recommend having some kind of validation of the structure of the Function App in order to be Continuous Integration friendly. Having to publish on the portal or starting debugging locally and check visually in order to validate if the content of the function make sense and is valid is not optimal in a daily development process. At compile time, you could maybe just start the CLI and return an error code if anything happens at CLI startup time (problem indexing function, problem compiling, missing references,...).
Thanks,
Simon

**Comment by svdoever** [comment]
While the functions editor in the portal DOES compilation! I totally agree!

**Comment by lindydonna** [comment]
Solved with precompiled assemblies
