### ISSUE TITLE
Azure Functions breaks Newtonsoft.Json TypeNameAssemblyFormat.Simple

### ISSUE THREAD

**Issue by samuelcavendish** [Azure/Azure-Functions#911]
When running Azure Functions (V1), there seems to be a problem using Newtonsoft.Json with TypeNameAssemblyFormat set to Simple. 

I've put together a simple project to demonstrate the issue [here](https://github.com/samuelcavendish/FunctionsOddities/tree/master)

When running from the Azure function, trying to deserialize the message below throws an exception:

```
{
    "$type": "Core.Derived, Core",
    "Foo": "a",
    "Bar": "b"
}
```

The same code run in the WebJob works for the message above. The only way to stop the function erroring is to have the full assembly name in the message, e.g. 

```
{
    "$type": "Core.Derived, Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
    "Foo": "a",
    "Bar": "b"
}
```

This suggests that, for some reason, the TypeNameAssemblyFormat in Newtonsoft.Json does not work correctly in Azure Functions. It seems to be an isolated issue with Functions rather than Newtonsoft so I've raised it here. Both the Azure Functions & the WebJobs projects use Newtonsoft.Json V9.0.1 so I don't think it's a problem with the dependencies

**Comment by paulbatum** [comment]
There aren't any error details in the issue report but if I had to guess I'd say its related to assembly loading. Also I'll note that it seems like this JSON.NET setting is now obsolete (mentioned [here](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_TypeNameAssemblyFormat.htm)).

Since there is a known workaround, this is a rarely used JSON.NET feature, and its for functions V1, I'm going to close this as wont-fix.

**Comment by samuelcavendish** [comment]
@paulbatum The workaround (if you're talking about the different message) is not usable by us, is there another workaround that works with the original message? Also, whilst as you mention it's obsolete in the latest version of Newtonsoft, the functions sdk is hardcoded to Newtonsoft 9.0.1 where it is not obsolete.

This is currently a blocker for us moving to functions as there are multiple sources queuing messages that can't all be changed to queue the new format

**Comment by paulbatum** [comment]
Makes sense. I know functions V2 is still in preview, but have you tried it to see if it has the same issue?

**Comment by samuelcavendish** [comment]
We're still reliant on the full framework for a couple of the dependencies, which I believe V2 doesn't support?

Lots of refactoring to do before we can swap the target framework of the dependencies to NETStandard to make V2 viable

**Comment by paulbatum** [comment]
Got it. Sorry that your scenario is blocked right now :/
