### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0 ...'

### ISSUE THREAD

**Issue by grik001** [Azure/Azure-Functions#913]
Hi I am getting the following error with Azure Function V1: 

I have the following packages installed:

![image](https://user-images.githubusercontent.com/27157850/44190340-92e35000-a126-11e8-87e9-63199809f77c.png)

I cannot remove the Newtonsoft library or downgrade it as my project gets package conflict. Is it possible to use redirects?

Although might not be related I am getting this error after solving this issue:

https://github.com/Azure/Azure-Functions/issues/910

**Comment by paulbatum** [comment]
Please put the full error message into the github issue itself, including stack trace and any other relevant output.

**Comment by grik001** [comment]
I solved this using the following thread: https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/

To reproduce this error simply create a V1 function which uses Storage and add the Newtonsoft v11 package.

**Comment by grantzvolsky** [comment]
For me it worked to simply install Newtonsoft.Json v10.0.3 rather than the latest v11.0.2.
