### ISSUE TITLE
Azure Functions Runtime 2 preview - Doesn't run always on App Service Plan S2 and Always On Enabled

### ISSUE THREAD

**Issue by ericbrunner** [Azure/Azure-Functions#914]
Hi,

I have noticed today that the Azure Function with Runtime v2 does not run always even when `Always On` is **enabled**.

Runtime version: `2.0.11961.0 (beta)`
App Service Plan: `Pay-As-You-Go` , `App-Service Plan Standard S2`

I marked that in AppicationInsights Screenshot below with a red arrow. The last successful request is marked with green arrow.

Last sucessful request: `8/15/2018, 2:49:00 PM `
New request:               `8/16/2018, 9:18:15 AM`
Time between: `approx. 18 hours`
Expected Result: `The the new request gets executed immediately`
Actual Result: `The Function started and swallowed the first request. The second request was executed successful. `

![image](https://user-images.githubusercontent.com/6480047/44195174-88ca4d00-a138-11e8-87b4-119d06a6fcbb.png)

My Settings

![image](https://user-images.githubusercontent.com/6480047/44194870-992df800-a137-11e8-9d4f-847f1ba1c6c0.png)

![image](https://user-images.githubusercontent.com/6480047/44194909-c084c500-a137-11e8-81f4-da2267177b97.png)

best
Eric

**Comment by ColbyTresness** [comment]
Closing - several issues in this area have been addressed since the preview. Please let us know if you continue having issues with the release version.
