### ISSUE TITLE
NuGet Package : Add `repository` metadata. 

### ISSUE THREAD

**Issue by MaximRouiller** [Azure/Azure-Functions#915]
Basically, we can now add a repository metadata on a nuspec file to allow the repository to be surfaced on NuGet. This allows you to have a `projectUrl` as well a repository URL now.

I've talked about it [on Twitter](https://twitter.com/MaximRouiller/status/1030468873945075712) but the most basic things to know is here:

[NuSpec Reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec?WT.mc_id=social-github-marouill#repository)

Reference Implementation in Json .NET
![image](https://user-images.githubusercontent.com/209384/44277447-b1c20f00-a218-11e8-9406-4f1f05879d47.png)

**Comment by fabiocav** [comment]
Have you found any packages where that is not set? All of the Functions and WebJobs packages should already have that.

**Comment by MaximRouiller** [comment]
## Missing altogether

https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DocumentDB
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ApiHub
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.NotificationHubs

## Missing for the V2.X (non-beta, still updated) of the package

https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions
https://www.nuget.org/packages/Microsoft.Azure.WebJobs
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Http
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging.ApplicationInsights
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Core
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ServiceBus
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.SendGrid
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Twilio
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.CosmosDB
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.MobileApps
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.AuthTokens
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.MicrosoftGraph

**Comment by MaximRouiller** [comment]
If other issues are opened, can we link back to this one? If not, can you @ me on the other issues?

**Comment by fabiocav** [comment]
Opened issues to track. Here's the breakdown: 

|Package|Comment|
|-|-|
|https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions|Tracking update [here](https://github.com/Azure/azure-functions-vs-build-sdk/issues/220)|
|https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator|Tooling package - Tracking update [here](https://github.com/Azure/azure-functions-host/issues/3282)|
|https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DocumentDB|Package renamed (DocumentDB -> CosmosDB). New package has all information. Old package will only be updated if a change is required|
|https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ApiHub|Old extension package, not migrated/update to 3.0. This would get that information if updated or in 3.0 if migrated|
|https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.NotificationHubs|Old extension package, not migrated/update to 3.0. This would get that information if updated or in 3.0 if migrated|

All 2.x releases would only be updated if new packages are required to address defects.

**Comment by MaximRouiller** [comment]
@fabiocav You rock! Thanks a lot! 😀

**Comment by ColbyTresness** [comment]
@MaximRouiller @fabiocav can this be closed since it looks like individual issues are tracked elsewhere?

**Comment by MaximRouiller** [comment]
@ColbyTresness Not only has this been tracked in other repos but it has also been fixed.

Older packages won't see a release just for that but from what @fabiocav mentioned, the commit to fix the issue is there. 

So I'm closing this issue.
