### ISSUE TITLE
Azure Functions v2 Assembly Binding Issue

### ISSUE THREAD

**Issue by jnevins-gcm** [Azure/Azure-Functions#916]
I have a v2 Azure Function App that has an IExtensionConfigProvider that uses Autofac. When Azure Functions runtime tries to load my function app IExtensionConfigProvider, I see this exception (debugging locally)
```
System.IO.FileLoadException
  HResult=0x80131621
  Message=Could not load file or assembly 'Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
```

in 

`Microsoft.Azure.WebJobs.Script.dll!Microsoft.Azure.WebJobs.Script.Binding.ExtensionLoader.LoadCustomExtensions.AnonymousMethod__5_1(System.Reflection.Assembly assembly, string typeName, bool ignoreCase) Line 101	C#
`

There are definitely several versions of Autofac referenced by different assemblies in the mix (ranging from 4.2.2 to 4.8.1.0, but I would have expected Azure Functions to correctly resolve the highest version of Autofac correctly (which is 4.8.1.0 and is correctly in the bin directory).

My Azure Function app also has 
`AzureFunctionApp.deps.json
`
in the parent directory (because Microsoft.NET.Sdk.Functions moves dlls to a subdirectory called bin) and it looks correct, so I would not expect to have a problem here...
I am using the following PackageReferences:

```

    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta5" PrivateAssets="None" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta5" PrivateAssets="None" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.0-beta5" PrivateAssets="None" />
    <PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="3.0.0-beta5" PrivateAssets="None" />
    <PackageReference Include="NLog" Version="4.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <!-- Required only for transitive references -->
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.*" PrivateAssets="None" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.0-*" PrivateAssets="None" />
    <PackageReference Include="Autofac" Version="4.8.*" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.*" />
```

**Comment by paulbatum** [comment]
cc @fabiocav

**Comment by fabiocav** [comment]
@jnevins-gcm is your extension triggering an assembly load against the default context? Can you point us to the code or provide a repro? Unification will be handled, but as an extension author, certain load patterns may cause issues, bypassing our load context.  

A repro here would be helpful in identifying what is happening.

**Comment by jnevins-gcm** [comment]
Got to the root of it. Seems like Microsoft.NET.Sdk.Functions 1.0.14 is the culprit and that assembly resolution is general broken when using this build.

Here is a bare csproj (created via Visual Studio New > Azure Function with HTTP trigger for simplicity). No changes were made from the empty skeleton created by Visual Studio, except for the version of the Microsoft.NET.Sdk.Functions PackageReference

```

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="**_1.0.13_**" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

And the default HTTP Trigger:

```
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.WebJobs.Host;
using Newtonsoft.Json;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequest req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = new StreamReader(req.Body).ReadToEnd();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
    }
}

```
Navigate to `http://localhost:7071/api/Function1` and I get `Please pass a name on the query string or in the request body` as expected. Change to

    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="**_1.0.14_**" />

and I get:

```
[08/21/2018 1:26:06 AM] Executed 'Function1' (Failed, Id=1c54370a-0778-42bd-b6a3-0ee5f18ce061)
[08/21/2018 1:26:06 AM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
```

Using dotnet 2.1.301

**Comment by fabiocav** [comment]
Very odd. This doesn't repro with the same steps for me. Do you see the same issue if you deploy this to Azure? Could  you show the console information (including the version) you're seeing when you run the function from VS?

**Comment by jnevins-gcm** [comment]
Here is the full output:


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Hosting environment: Production
Content root path: C:\source\repos\FunctionApp1\FunctionApp1\bin\Debug\netstandard2.0
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[08/21/2018 3:13:35 AM] Reading host configuration file 'C:\\source\repos\FunctionApp1\FunctionApp1\bin\Debug\netstandard2.0\host.json'
[08/21/2018 3:13:35 AM] Host configuration file read:
[08/21/2018 3:13:35 AM] {}
[08/21/2018 3:13:35 AM] Starting Host (HostId=w10dt-144893519, InstanceId=f56a5d39-b244-4908-a95a-a47a4974cef5, Version=2.0.11651.0, ProcessId=21180, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[08/21/2018 3:13:35 AM] Unable to configure java worker. Could not find JAVA_HOME app setting.
[08/21/2018 3:13:35 AM]
[08/21/2018 3:13:35 AM] Could not configure language worker Java.
[08/21/2018 3:13:35 AM]
[08/21/2018 3:13:36 AM] Generating 1 job function(s)
[08/21/2018 3:13:36 AM] Found the following functions:
[08/21/2018 3:13:36 AM] FunctionApp1.Function1.Run
[08/21/2018 3:13:36 AM]
[08/21/2018 3:13:36 AM] Host initialized (758ms)
Listening on http://localhost:7071/
Hit CTRL-C to exit...

Http Functions:

        Function1: http://localhost:7071/api/Function1

[08/21/2018 3:13:36 AM] Host started (1259ms)
[08/21/2018 3:13:36 AM] Job host started
[08/21/2018 3:13:36 AM] Host lock lease acquired by instance ID '0000000000000000000000004F4D8A76'.
[08/21/2018 3:14:31 AM] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=b0eedcea-d71d-415a-8ba8-6e759424e6a6)
[08/21/2018 3:14:32 AM] Executed 'Function1' (Failed, Id=b0eedcea-d71d-415a-8ba8-6e759424e6a6)
[08/21/2018 3:14:32 AM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load file or assembly 'Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'.

**Comment by jnevins-gcm** [comment]
And confirmed - it does work when deployed to Azure.

**Comment by jnevins-gcm** [comment]
When using .14 locally seems like all assembly loading for assemblies also used by the host is broken. 

For example, NLog works fine in general. Autofac works if I reference the same version at the host with my PackageReference (4.6.1). Same with Newtsoft.Json.

**Comment by paulbatum** [comment]
@jnevins-gcm I am pretty sure its because you're using out of date V2 bits locally. The version number is printed here:

[08/21/2018 3:13:35 AM] Starting Host (HostId=w10dt-144893519, InstanceId=f56a5d39-b244-4908-a95a-a47a4974cef5, Version=**2.0.11651.0**, ProcessId=21180, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)

The 11651 release was in March, before we completed all the assembly resolution improvements:
https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11651-alpha

Thing is, VS automatically grabs the latest bits, so I'm very unclear as to why you have such an old version. Check the `%userprofile%\AppData\Local\AzureFunctionsTools\Releases\` folder - you should see something like this (with 2.4.0 corresponding to the latest release as of time of writing).

```
Directory of C:\Users\pbatum\AppData\Local\AzureFunctionsTools\Releases

08/16/2018  10:19 AM    <DIR>          .
08/16/2018  10:19 AM    <DIR>          ..
05/02/2018  03:35 PM    <DIR>          1.0.11
05/02/2018  05:47 PM    <DIR>          1.0.12.1
06/15/2018  10:35 AM    <DIR>          1.2.0
07/30/2018  04:06 PM    <DIR>          1.3.0
05/02/2018  03:35 PM    <DIR>          2.0.1-beta.26
05/11/2018  03:17 PM    <DIR>          2.0.1-beta.27
05/22/2018  10:13 AM    <DIR>          2.1.0
07/30/2018  04:06 PM    <DIR>          2.3.2
08/07/2018  09:34 AM    <DIR>          2.3.3
08/16/2018  10:30 AM    <DIR>          2.4.0
```

**Comment by jnevins-gcm** [comment]
I don't have that folder - only %localappdata%\Azure.Functions.V2.Cli

**Comment by paulbatum** [comment]
Hrm just to confirm, are you using VS? Might want to follow the steps here to check if you're using the latest bits:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs

**Comment by jnevins-gcm** [comment]
Yes I am. I am running 15.7 and have the azure workload installed

**Comment by paulbatum** [comment]
When you followed the steps at:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#check-your-tools-version

What was your tools version? 15.0.40617.0 ?

**Comment by jnevins-gcm** [comment]
No - it was 15.8 and had auto-update enabled. 

I just uninstalled and reinstalled and now it installed function tools 2.4.0 on first launch... and it works. Thanks!

**Comment by paulbatum** [comment]
OK great.
