### ISSUE TITLE
Monitor pane records get mixed up when logging to Application Insights from two functions with the same name from different function apps

### ISSUE THREAD

**Issue by micheldewinter** [Azure/Azure-Functions#917]
Recently I noticed that a brand new function app of mine which is connected to application insights, released via VSTS RM, was already showing 'log' records in the monitor pane of one of its functions. The log records were from before the function had ever been deployed to Azure.

What is actually happening:
I have two function apps:

Function app named: Foo (first deployed on 1 August)
- Function Alice
- Function Bob

Function app named: Bar (first deployed on 1 September)
- Function Alice
- Function Eve

Both of the function app's are logging to the same application insights instance and both function app's have a function called Alice. They have a separate azure storage back-end. When looking at the monitor pane of function Alice in the Azure Functions backend of Function app Bar it showed log records/runs from the Alice function of function app Foo (it actually showed log records from before 1 September). A closer look by clicking on the 'Run in Application Insights' link. It shows that the query only queries on the name of the function.

`requests | project timestamp, id, name, success, resultCode, duration, operation_Id | where timestamp > ago(30d) | where name == 'Alice' | order by timestamp desc | take 20`

The problem with this is that both the functions have the same name and that by querying like this it all gets cluttered together. This would suggest that function names over function app's logging to the same application instance name should be unique. Wouldn't it be better to extend the query which filles the Monitor pane with the cloud_RoleName? like this:

`requests | project timestamp, id, name, success, resultCode, duration, operation_Id, cloud_RoleName  | where timestamp > ago(30d) | where name == 'Alice' and cloud_RoleName == 'Foo' | order by timestamp desc | take 20`

**Comment by alexkarcher-msft** [comment]
Good catch! This is an A+ UI Bug.

If you can move this issue to the UX repo and tag @nertim in this issue, they should be able to resolve this pretty quickly :)
