### ISSUE TITLE
Code Sharing in Node.js Functions

### ISSUE THREAD

**Issue by AaronFriel** [Azure/Azure-Functions#92]
I'm curious about what the best method of implementing shared library code for Azure Functions is. Here's my thought process, and hopefully someone from the team can help me understand a better way to do this.

I have an Azure Bot Service and Azure Functions app [the UNIFI Bot Service](https://github.com/unifreethought/unifi-bot-service) and it deploys, right now, three functions:

1. `everyMinuteFunction`, which does what it says on the tin. It runs every minute, and conditionally sends some messages using the bot service.
2. `plivo-in`, which acts as an input interface for SMS received from [Plivo.com](https://www.plivo.com/)
3. `messages`, the default Bot Service function.

Now I have shared code which needs to be in each of these, for example: all three need to be able to send SMS messages through Plivo, access data in a shared database, and so on.

Right now I'm duplicating code between each function, so in every function I have a `lib` folder containing the TypeScript source, a `src` folder containing the compiled typescript, and in `lib` I have my shared code too, for example I have:

* `./messages/src/bots/UnifiConnector.ts`
* `./everyMinuteFunction/src/bots/UnifiConnector.ts`
* `./plivo-in/src/bots/UnifiConnector.ts`

And likewise for the `lib` folder. So, what would happen if I deployed this with a shared `node_modules` in the root? What are the limits of what I can do in terms of putting extra modules in a shared directory, e.g.: `./.shared/src/bots/UnifiConnector.ts`, will this cause problems for the Functions deployment?

Please let me know if this question has already been asked. I will experiment with a few different options for code sharing but I want to avoid the Functions framework from glitching out if I add additional folders to the root.

**Comment by AaronFriel** [comment]
This was a relatively easy experiment, I'm pleased to say. I implemented code sharing here:

https://github.com/unifreethought/unifi-bot-service/tree/codesharing

It looks like the deployment runs fine if you use relative paths in the functions, so here is my `messages/package.json`:

```json
  "dependencies": {
    "unifi-bot-service-shared": "file:../.shared/svc"
  }
```

And here is the index.js:

```js
"use strict";
module.exports = require('unifi-bot-service-shared/lib/functions/messages');
```

Then from the root of the repository, `./.shared/svc` contains the unifi-bot-service-shared package.

My question now is: will this break in the future with a change to Azure Functions?

**Comment by lindydonna** [comment]
@christopheranderson Can you comment on best practices for Node.js functions?

**Comment by christopheranderson** [comment]
I think this is more of a documentation issue where we don't have any documentation around project structure for Node.js based Functions applications.

Here's some rough notes, but we should probably turn this into a doc.

What Azure Functions expects for Node.js is:

- A directory per Function
- A directory contains a function.json
- A .js file (defaults to using index.js) or a `scriptFile` entry in `function.json`

So you have two big choices for shared code in Node.js Functions:

1. Each Function references a shared library which contains the code from an index.js file in each directory
2. Each Function is just a `scriptFile` (and usually, but optionally, `entryPoint` if we have more than 1 method returned by a shared library which contains our functions) in the `function.json`

Which one to choose doesn't have any concrete answers, but I'll give this advice:

- Option #1 is good if you plan on adding/removing Functions often from the portal. 
- Option #2 is good if you want to work mostly locally and don't want to manage your Functions in directories, you want more of a "shared library" approach.

I'm gonna assign this to myself to come up with a larger sample. If you have clarifying questions, I'll try to respond to them here.

(Sorry for this taking a long time to respond. Just found this as we were cleaning up older issues in this repo.)

**Comment by lukojewel** [comment]
Any updates on this^ ? Correct me if I am wrong. I want to use same code in different functions. How can I achieve this ? Can I have a shared folder from which I can import files and use. I tried this using 'serverless'. But once deployed it doesn't work. I have an application which needs to authenticate each api call which will use a common code. Any help would be great.

**Comment by murraybauer** [comment]
@mpseidel I suspect if you configure `watchDiectories` to monitor the shared directory, there would be no need to restart. [See this](https://stackoverflow.com/questions/40683516/azure-function-in-node-js-and-shared-files)

**Comment by jeffhollan** [comment]
Believe we can close this with new local tools and experience.  Simple `require()` statements should work great
