### ISSUE TITLE
Logging each and every line of Azure functions

### ISSUE THREAD

**Issue by Lakshminarayana537** [Azure/Azure-Functions#922]
HI Guys,

We want to log each and every line or important piece of codes for checking the failures in our azure functions. I understand that application insights provide a way to do this. But, alternatively can we use log analytics to log all the errors, warnings and code exceptions. 
Please suggest on the best approach to log the azure functions exceptions/failures/errors/application without using application insights??

**Comment by alexkarcher-msft** [comment]
Currently App Insights is our preferred logging pipeline. Those logs will become available for you to query in log analytics. You can get to a few pre-baked queries by opening the monitor tab in the Functions portal.

Can you provide a bit more background on what you are looking for in a different logging solution?

**Comment by Lakshminarayana537** [comment]
Hi Alex,

We have an azure function which retrieves transnational data from the REST API. The raw data coming from the REST API we are storing that to a BLOB storage. We have logic app which will trigger if any blob is added to the storage container, parses the data and pushes data to the downstream systems. So from azure function to till logic app we want to monitor all the failures. But, i understand that in logic app we have log analytics feature which does same like azure app insights, so want to confirm which one is most efficient for monitoring the failures.
