### ISSUE TITLE
Binding issues after update to  2.0.12050-alpha

### ISSUE THREAD

**Issue by vmedic** [Azure/Azure-Functions#926]
Hi,
this morning  I updated the runtime to  2.0.12050-alpha and the functions that I was able to debug don't run anymore. I have followed instructions in [https://github.com/Azure/app-service-announcements/issues/129](url) but i get following errors when i press F5:
![erroromni](https://user-images.githubusercontent.com/42870229/44917744-8885a080-ad39-11e8-9131-f9079ae8514c.JPG)

Azure Functions Core Tools (2.0.1-beta.36)
Function Runtime Version: 2.0.12050.0

Any idea how to solve this issue?

Thanks

**Comment by JMayrbaeurl** [comment]
Same problem with eventHubTrigger extension

**Comment by brettsam** [comment]
@vmedic -- there's a new storage extension that you need to install (in addition to your upgraded extension): https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/3.0.0-beta8. Let me know if you still have issues after installing that.

**Comment by rodobros** [comment]
I am seeing the same error with ServiceBus : 
![image](https://user-images.githubusercontent.com/9136873/44929220-0ed8bd00-ad0f-11e8-9a9b-05116ed79ff4.png)

Here are my package references:
![image](https://user-images.githubusercontent.com/9136873/44929256-3c256b00-ad0f-11e8-924c-a0ee326ebfc5.png)

**Comment by brettsam** [comment]
@rodobros -- That looks similar to https://github.com/Azure/Azure-Functions/issues/928. Feel free to follow along there -- hopefully we figure out the culprit soon.

**Comment by vmedic** [comment]
@brettsam : I had that extension installed, that was the part of instructions in announcement. Without it I was not able to build the project, but this issue happens at runtime, when I try to start the functions.

**Comment by brettsam** [comment]
Can you take a look at #928 and see if those steps help? Specifically --
- What's in the `extensions.json` file in your output directory?
- What if you delete your `bin` and `obj` directories and rebuild?
- Do you have a direct reference to ExtenstionsMetadataGenerator?

**Comment by vmedic** [comment]
Hi,
Removing direct reference to ExtenstionsMetadataGenerator solved the issue with extensions.json being empty. However, I have another issue with custom bindings which occurred at the same time. I had a custom binding that stopped working since upgrade:

[Binding]
    [AttributeUsage(AttributeTargets.Parameter)]
    public sealed class ConnectToSqlAttribute : Attribute
    {
        public ConnectToSqlAttribute(string connectionString)
        {
            ConnectionString = connectionString;
        }

        [AutoResolve]
        public string ConnectionString { get; }
    }

    public class ConfigurationExtensionConfigProvider : IExtensionConfigProvider
    {
        public void Initialize(ExtensionConfigContext context)
        {
            var rule = context.AddBindingRule<ConnectToSqlAttribute>();
            rule.BindToInput(ConvertConnectionStringToSqlConnectionAsync);
        }

        private static async Task<SqlConnection> ConvertConnectionStringToSqlConnectionAsync(ConnectToSqlAttribute attribute, CancellationToken cancellationToken)
        {
            var connection = new SqlConnection(attribute.ConnectionString);
            await connection.OpenAsync(cancellationToken).ConfigureAwait(false);
            return connection;
        }
}

Then it is used as input in method:

public static void Run([BlobTrigger("%blobContainerName%/{name}", Connection = "")]Stream myBlob, string name, ILogger log, [ConnectToSql("%AggregationSQLConnectionString%")] SqlConnection connection)

When I launch the application I get the following error message

Error indexing method 'AggregateDeltaFunction.Run'
[9/19/2018 12:49:30 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'AggregateDeltaFunction.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'connection' to type SqlConnection. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.)

Azure Functions Core Tools (2.0.1-beta.39)
Function Runtime Version: 2.0.12095.0

Is there anything that I need to add for the new release?

**Comment by ColbyTresness** [comment]
Closing as this is the same problem as #928
