### ISSUE TITLE
Get rid of 2.5.1

### ISSUE THREAD

**Issue by jnevins-gcm** [Azure/Azure-Functions#927]
How do I get Visual Studio and the Azure deployments back to version 2.4.1?

**Comment by darrenhull** [comment]
I too have issues with the 2.5.1 update. How do you "pin"  to a version? I have tried to copy the tags folder v2 to pinned and set lastKnownGood to a previous version. I have also tried to remove all references to 2.5.1. 

How do we pin to a specific version?

**Comment by jnevins-gcm** [comment]
Would be great to get some kind of response from the functions team. A massively breaking change was just forced out upon all users.

**Comment by jnevins-gcm** [comment]
https://github.com/Azure/app-service-announcements/issues/129
