### ISSUE TITLE
Azure Function Returning 404s suddenly without any update

### ISSUE THREAD

**Issue by YonasMetaferia** [Azure/Azure-Functions#929]
The azure Function in question was behaving well till suddenly it started returning 404s with no updates or Config changes done to it. It has an exception log as below. 

Function (****) Error: Could not load type 'Microsoft.Azure.WebJobs.ExecutionContext' from assembly 'Microsoft.Azure.WebJobs.Extensions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.

Could anyone help what we need to do to resolve it?

Thanks in advance for the help!

**Comment by mhoeger** [comment]
@YonasMetaferia - It looks like your function app was updated to the latest runtime bits, which contains breaking changes (see [release notes](https://github.com/Azure/app-service-announcements/issues/129) for a complete list of breaking changes). 

_Temporarily_, you can fix your issue by updating the App Setting `FUNCTIONS_EXTENSION_VERSION` to `2.0.11961-alpha`. To update your code, please see the announcement issue I linked! There is also a thread on issues people are running into [here](https://github.com/Azure/app-service-announcements-discussions/issues/64) that functions team members are actively monitoring.

**Comment by mhoeger** [comment]
I'm going to close this issue in favor of this one: https://github.com/Azure/app-service-announcements-discussions/issues/64. Please feel free to @ me if you do run into blockers or questions!

**Comment by YonasMetaferia** [comment]
Thank you @mhoeger! I made the update as you suggested and function looks to be stable now.  We will have a task to actually upgrade our functions to Permanently resolve the issue.

You can go ahead and close this issue.
