### ISSUE TITLE
Document FUNCTIONS_EXTENSION_VERSION and versioning strategy

### ISSUE THREAD

**Issue by lindydonna** [Azure/Azure-Functions#93]
There currently isn't any documentation on the app setting FUNCTIONS_EXTENSION_VERSION. We need to document the syntax and what values can be used.

CC @christopheranderson

**Comment by SyntaxC4** [comment]
There isn't really a precedent for this across all of the App Service content. We need to figure out a good place to put stuff like this. 

I think it would be wise to have it in the Developer Reference topic under a heading of **Versioning**.
