### ISSUE TITLE
R 3.3.3 x64 Extensions No Longer in Extensions List

### ISSUE THREAD

**Issue by jamesaarondevlin** [Azure/Azure-Functions#932]
Hi,

After creating a Functions App to perform some testing I have noticed that the R extensions no longer appears in the list of available extensions.

Here are our versions 
Functions Runtime Version - 2.0.11961
FUNCTIONS_EXTENSION_VERSION - 2.0.11961-alpha

This is a fairly critical issue for us if we are no longer able to run the R extension on Azure Functions. To be fair we could still manually install the extension but it'd be nice if the extension didn't disappear overnight.

~~Do we need to downgrade our version of the Azure Functions runtime?~~ _Update: have checked against runtime version 1.0.11959.0 (~1) and this extension still no longer appears_

Regards,
James

**Comment by tdwright** [comment]
Hi guys,

We're experiencing this too. Any idea what's going on?

Cheers,
Tom

**Comment by tdwright** [comment]
https://giphy.com/gifs/tumbleweed-1Zbeweu52ZaQE

**Comment by mishal153** [comment]
I ran into this same problem today. It is a blocker till we find a work around. I am using the functions runtime 2.0.12050

**Comment by Stighebbelstrup** [comment]
I am having the same issue. Is the only solution to use Azure functions on linux and create our own docker containers with R?

**Comment by tdwright** [comment]
Bump! FYI - this is still an issue...

What's going on? Should we expect not to have R available in Azure Functions going forward?

**Comment by tdwright** [comment]
In case this helps anyone, it seems like it's super easy to [work with R from AWS](https://aws.amazon.com/blogs/big-data/running-r-on-aws/).

**Comment by megel** [comment]
What is the current state of this issue? We want to use R-Script from Azure function but run into the same issue - no R-Script Site Extension is available.
Are there any other options to run R-Scripts in an Azure Function / App Service in our Azure Environment or is AWS the only way provide a service with R-Scripts?

**Comment by tdwright** [comment]
@megel Judging by the response to this thread, I think this has been quietly dropped by MS. It _is_ possible to make R work on Azure Functions, but it requires a bit of messing around in Kudu and manually copying files around. Unless you're wedded to Functions, I'd probably recommend just going with AWS.

**Comment by intui** [comment]
I really hope this feature will be back soon, as I'm currently exploring serverless R scenarios.
Pretty please - prio up.
Cheers, Wido

**Comment by tdwright** [comment]
Can't believe that four months on we'd still be waiting for a response. What's going on?

**Comment by JohnReeson** [comment]
See whether [this SO post](https://stackoverflow.com/a/53544639/9191057) mitigates.

**Comment by franperic** [comment]
Facing the same problem. @Stighebbelstrup, did you try using docker? If yes, can you recommend the work around?

**Comment by ColbyTresness** [comment]
Sorry for letting this sit for so long, this should have been responded to ages ago. Delay was unintentional, and we'll try to do better in the future.

Azure Functions doesn't support R, and we don't have any current plans to change that. So, I'm closing this since it's not something we officially support anyways. There's an open UserVoice item on adding R support, so if you'd like this, comment/vote there:
https://feedback.azure.com/forums/355860-azure-functions/suggestions/17440162-support-for-r

Until then, the linked SO post is probably your best bet.
