### ISSUE TITLE
Publish failed when referencing ASP.NET project

### ISSUE THREAD

**Issue by caill26** [Azure/Azure-Functions#933]
Hello,

I've tried to publish an Azure Functions 1.1 projects and it failed. After investigating, the error message was pretty clear 

`
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.targets(4368,5): error : The value for PublishProfile is set to 'functiontest - Web Deploy', expected to find the file at 'C:\Users\....\TestFunction\WebApplication1\Properties\PublishProfiles\functiontest - Web Deploy.pubxml' but it could not be found. [C:\Users\....\TestFunction\WebApplication1\WebApplication1.csproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.targets(4375,4): error : PublishProfile(functiontest - Web Deploy) is set. But the $(WebPublishMethod) does not have a valid value.  Current Value is "". [C:\Users\....\TestFunction\WebApplication1\WebApplication1.csproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.targets(4382,5): error : Target ValidatePublishProfileSettings Failed [C:\Users\....\TestFunction\WebApplication1\WebApplication1.csproj]
`
The publisher tried to acces the file in the wrong directory, the Web API project, instead of the TestFunction project (Yes the Solution is called TestFunction and the Functions project also).

Easy way to reproduce (VS 2017 Pro - 15.8.2)

1. Create a Solution with an Azure functions 1.1 project (.NET Framework 4.6.1)
2. Create an ASP.NET project inside the solution, in my case Web API
3. Reference the project Web API into the Azure functions project
4. Try to publish the Azure functions project

My work-around (does not work if the publish profile was meant to generate a ZIP file) :

1. Copy/Paste the publish settings of Azure functions into the publish profiles of the Web API
2. It will first publish the Web API project and then remove it and publish the Azure functions project

It seems that it is the same error as here https://stackoverflow.com/questions/47808507/visual-studio-looking-in-my-asp-net-publish-profiles-folder-for-my-azure-functio?rq=1

Don't know if it's a known issue, or the right place, but I wanted to report it in case

**Comment by joshnoe** [comment]
Another workaround: If there's already a PublishProfiles folder at the location stated in the error, remove or rename this folder.

**Comment by Specials** [comment]
If I use the workaround described [here](https://github.com/Azure/Azure-Functions/issues/933#issue-356734621), for step 2, it does not delete the Web API project again when publishing the Azure Functions, even though `SkipExtraFilesOnServer` is set to false.

Any news or comments on this issue?

**Comment by caill26** [comment]
@Specials What do you mean by "it does not delete the Web API project **again** when publishing the Azure Functions" ? I can see that there's always the WebConfig from my WebApi project under "\home\site\wwwroot>" and some other folders but it's not used by Azure Functions. Does it not work for you ?

**Comment by Specials** [comment]
@caill26 I meant that, as you wrote in step 2:
> It will first publish the Web API project and then remove it and publish the Azure functions project

when I published, it did not remove the Web API project again, it even deployed and started the webjobs referenced by the API too.

I figured out why, though! I had chosen the ZIP package deploy for the function (as they recommend, and you mentioned not to use), so I had to go back to the web deploy. I still need to make a new publish profile in the Web API with the same name as the profile for the Function.

Now it deploys Web API + web jobs first, then starts deploying the Function, which deletes all the Web API files and folders, then deploys Function. So I think I'm left with only the Web API DLLs I need in the bin folder. Happy!

Next issue: How can I override the [Newtonsoft.Json version being forced to 9.0.1](https://github.com/Azure/azure-functions-vs-build-sdk/issues/107) when I need 11.0.2? :worried:

**Comment by caill26** [comment]
@Specials You can't... :( but I use a trick, which I'm not sure it will help, that I found somewhere here, I dont remember the sources and I can't find it anymore sorry... I modify it a little to go search for specific dll in the publish folder of the functions. I was having problems deserializing data from a custom library and it solve it, maybe it will allow you to load the right version if the code is called from another library. If you can use Azure functions V2 I think they are implementing what you want and you will have better performance : https://github.com/Azure/Azure-Functions/issues/996

If you are stuck in V1, try this : 
`public class AzureFunctionsResolveAssembly : IDisposable
    {
        private ILogger _logger;
        public AzureFunctionsResolveAssembly()
        {
            AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
        }

        public AzureFunctionsResolveAssembly(ILogger log) : this()
        {
            _logger = log;
        }

        void IDisposable.Dispose()
        {
            AppDomain.CurrentDomain.AssemblyResolve -= CurrentDomain_AssemblyResolve;
        }

        private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs arguments)
        {
            var assembly = AppDomain.CurrentDomain.GetAssemblies()
                .FirstOrDefault(a => a.GetName().FullName == arguments.Name);

            if (assembly != null)
            {
                Log($"Assembly not null {assembly.FullName}");

                return assembly;
            }

            // try to load assembly from file
            var assemblyDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var assemblyName = new AssemblyName(arguments.Name);
            var assemblyFileName = assemblyName.Name + ".dll";
            string assemblyPath;

            if (assemblyName.Name.EndsWith(".resources"))
            {
                var resourceDirectory = Path.Combine(assemblyDirectory, assemblyName.CultureName);
                assemblyPath = Path.Combine(resourceDirectory, assemblyFileName);
            }
            else
            {
                assemblyPath = Path.Combine(assemblyDirectory, assemblyFileName);
            }

            if (File.Exists(assemblyPath))
            {
                Log($"File exist {assemblyPath}");

                return Assembly.LoadFrom(assemblyPath);
            }

            Log($"File does not exist in assembly path {assemblyPath}");

            //Custom code added from original source
            string otherAssemblyPath = $"../../../../../../../../../home/site/wwwroot/bin/{assemblyName}.dll";
            if (File.Exists(otherAssemblyPath))
            {
                Log($"File exist {otherAssemblyPath}");

                return Assembly.LoadFrom(otherAssemblyPath);
            }

            Log($"File does not exist {otherAssemblyPath}");

            return null;
        }

        private void Log(string message)
        {
            if (_logger != null)
                _logger.LogDebug(message);
        }
    }`

and you call it before calling custom library like this : 

`using (new AzureFunctionsResolveAssembly(log))
{
//Call to your custom assembly that use Newtonsoft 11.0.2
}`

**Comment by Specials** [comment]
@caill26 I'm having trouble deserializing models from Cosmos DB due to some issues with default constructors and dictionaries, that are handled in the newer libraries.

I'll give your suggestion a try. Thanks a lot! :pray:

**Comment by ColbyTresness** [comment]
Closing as it seems like this has been resolved. Please reopen if necessary.
