### ISSUE TITLE
Build Failures Due to Locked Files

### ISSUE THREAD

**Issue by JamesRandall** [Azure/Azure-Functions#934]
Since updating to the latest runtime (2.0.1-beta.37 - obtained from func --version), corresponding extensions and Visual Studio tooling (15.8.5023.0) I'm occasionally experiencing build failures due to locked files. For example:

`error MSB3021: Unable to copy file "D:\wip\bookmarkReading\platform\src\blahblahblah\bin\Debug\netstandard2.0\blahblahblah.pdb" to "bin\Debug\netstandard2.0\bin\blahblahblah.pdb". The requested operation cannot be performed on a file with a user-mapped section open.`

The target folder is the Functions project output.

This seems to happen (intermittently) after terminating a debug session.

**Comment by ColbyTresness** [comment]
Sorry for the lack of response here - is this still an issue for you?

**Comment by JamesRandall** [comment]
I believe its been resolved in one of the updates - I've not seen it for some time.
