### ISSUE TITLE
Process is misspelled "porcess"

### ISSUE THREAD

**Issue by daviburg** [Azure/Azure-Functions#937]
This is happening in the azure functions CLI tools for Visual Studio local debugging, when you restart a function shortly after ending the previous session.

Port XXXXX is unavailable. Close the porcess using that port, or specify another port using --port [-p].

@nertim

**Comment by daviburg** [comment]
https://github.com/Azure/azure-functions-core-tools/pull/698

**Comment by ColbyTresness** [comment]
Closing as this is complete
