### ISSUE TITLE
VISUAL STUDIO - After adding a new function the code editor does not act as expected

### ISSUE THREAD

**Issue by IntelligentLabs** [Azure/Azure-Functions#94]
After creating a new function I am unable to use return or delete, ctl-v within the code editor. I can enter plain text characters. If I close visual studio I then get a warning message. After reopening it works as expected. I am only using C# HttpTrigger functions, but this happens every time.

Steps carried out:
Open a Azure Functions solution in visual studio
Right click solution and select Add > New Azure Function...
Choose C# HttpTrigger function and enter a name for it
Open Run.csx and attempt to press the return key [Nothing happens]
Open Project.json and attempt to press the return key [Nothing happens]
Close Visual Studio [Error prompt displayed]
![capture](https://cloud.githubusercontent.com/assets/14219081/20921809/b4829d80-bb9d-11e6-9401-ed4d1c48a8b6.PNG)

Environment:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90000-12803-AA590
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-90000-12803-AA590
Microsoft Visual Basic 2015

Visual C# 2015   00322-90000-12803-AA590
Microsoft Visual C# 2015

Visual C++ 2015   00322-90000-12803-AA590
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-90000-12803-AA590
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   7.14.01128.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.21111.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.6   14.0.21129.0
Azure App Service Tools v2.9.6

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.2100.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

Elite Platform Installer AddIn Project   1.0
The project type for creating EPI Add-Ins

InstallShield 2015 Editor   
InstallShield. For more information visit the Flexera Software website at <http://www.FlexeraSoftware.com>. For customer support visit <http://support.InstallShield.com>. Copyright © 2015 Flexera Software LLC. All Rights Reserved.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure Hive Query Language Service   2.2.2100.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40211.2

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.41104.6

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Quantum.VSPackage   1.0
Elite Integration Framework (EIF) Visual Studio Extensions

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.34.0
TypeScript tools for Visual Studio

Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.25420.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.1.0.530 (2e39740)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.0.71 (4e27558)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.0.323 (39ebb77)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by lindydonna** [comment]
Thanks for the bug report, we're investigating.
