### ISSUE TITLE
Injecting ILogger in .NET Standard library

### ISSUE THREAD

**Issue by isaac2004** [Azure/Azure-Functions#940]
Since the recent changes for DI I have not been able to properly inject ILogger into different assemblies. In the past, I was able to load the referenced assemblies and load ILogger into the container. With the new DI changes, I am not sure where to wire this up.

Here is a repo with a sample that I would like to get working. When I run this, I get an error saying ILogger did not resolve in IService which is in a .NET Standard library. 
 
https://github.com/isaac2004/AzureFunction-DI

**Comment by isaac2004** [comment]
@fabiocav any ideas?

**Comment by fabiocav** [comment]
@isaac2004 apologies for the significant delay on this. Some of the issues in this repo were unfortunately missed. 

I'm assuming (and hoping) you have found the answer to this by now. While this is supported today, we're working on a better model for service injection in Functions and close to having that released. I'll close this, but please let us know if you still have unanswered questions.

**Comment by isaac2004** [comment]
@fabiocav I appreciate the response, if you know of a solid workaround I would appreciate it. The ones that I have tried involve coding changes to deploy different apps
