### ISSUE TITLE
Post build script firing before Azure Function files updated in $(TargetDir)

### ISSUE THREAD

**Issue by KirkMunro** [Azure/Azure-Functions#945]
I'm using Visual Studio 2017 version 15.8.1 with an Azure Function project that uses the latest stable release of the Microsoft.NET.Sdk.Functions Nuget package. I have added a post-build step that invokes a ps1 script that creates a zip file of the contents of $(TargetDir), so that I can use that zip file in CI/CD work to publish the latest build to my Azure function. The problem I have is that the post-build step script fires before the Azure Function build has fully completed (the event fires, then the build script runs to create the archive, then Visual Studio adds functions for each Azure Function endpoint I have in my project, with function.json files in those folders).

Shouldn't the deployment of those folders happen before any of the post-build event command-line commands are invoked, so that you can properly work with the entire package produced by Visual Studio as part of the build?

I don't think it's necessary for this issue, but here is the post-build script:

```PowerShell
param(
	[Parameter(ValueFromRemainingArguments=$true)]
	[string]$TargetDir
)

$ErrorPreference = [System.Management.Automation.ActionPreference]::Stop
try {
	# Create the archive
	$buildPath = Join-Path -Path $TargetDir -ChildPath "$([System.DateTime]::UtcNow.ToString('yyyyMMddHHmmss')).zip"
	Write-Output -InputObject "Creating archive '${buildPath}'."
	Compress-Archive -Path $TargetDir\* -DestinationPath $buildPath
	Write-Output -InputObject "Archive created."
} catch {
	throw
}
```

**Comment by ColbyTresness** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#297
