### ISSUE TITLE
Unable to publish Function - "GatherAllFilesToPublish does not exist in the project"

### ISSUE THREAD

**Issue by rndthoughts** [Azure/Azure-Functions#95]
Upon attempting to publish my function to Azure or locally, the publish procedure terminates with the error message: The target "GatherAllFilesToPublish" does not exist in the project" referencing Functions.funproj.

**Comment by lindydonna** [comment]
@rndthoughts Can you provide a project that has the weird behavior?  I assume you're using Web Deploy (right-click publish)?

**Comment by lindydonna** [comment]
@rndthoughts Also, are you trying to do local publish by doing **File System** as the publish method?  If so, that is not supported (as mentioned in the blog post here: https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/). 

For the Web Deploy workflow, can you provide the exact steps you followed?

**Comment by rndthoughts** [comment]
@lindydonna - you're quite right, I was attempting to publish locally,  my bad.  But I can't find where that's mentioned in the blog post?

**Comment by lindydonna** [comment]
@rndthoughts You're right, it's not in the list of known issues in the blog post. Good catch--I'll ask that it be updated. 

Are you having any problems with publishing to Azure when you use the regular Web Deploy (not a web deploy package)?

**Comment by rndthoughts** [comment]
@lindydonna No, that's all working fine :)  Thanks for all the help, if only I could get the Azure B2C team to respond in the same way :(
