### ISSUE TITLE
Calling a azure function from another azure function c#

### ISSUE THREAD

**Issue by Lakshminarayana537** [Azure/Azure-Functions#951]
Hi Guys,

Is it possible to call one azure function from another azure function???

We have a requirement where we want to call a HTTPTriggered azure functions from a ServiceBusTopic triggered azure function. Is it possible? if possible please post some answers and links here. 

Ex:
[Azurefunction1]  --Servicebus triggered topic
Run()
{
  string secondAzFunResp = Azurefunction2(); 
}

[Azurefunction2] --HttpTriggered azure function
Run()
{
   -- Post the response back to Azurefunction1
}

**Comment by Lakshminarayana537** [comment]
Any suggestions??

**Comment by german95n** [comment]
I am not an expert on this. But have you taken a look onto [Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview)?

There is always the option to send an HTTP Request to the other function and wait for the response on your first function.

**Comment by Kainatn** [comment]
@Lakshminarayana537 how did you do this?
