### ISSUE TITLE
Not trigger Java Function by Storage trigger: The binding type(s) 'queueTrigger' are not registered

### ISSUE THREAD

**Issue by romanovs** [Azure/Azure-Functions#956]
I have Functions based on Java, which are triggered by Storage (queue, blob). In the end of August, it discontinued triggering by Storage. Looks like it is connected with the latest changes in the Runtime engine.

I can see this error message in Portal:
_"Function ({name}) Error: The binding type(s) 'queueTrigger' are not registered. Please ensure the type is correct and the binding extension is installed."_
The same for 'blobTrigger'.

I confirmed I have this settings set:
_FUNCTIONS_EXTENSION_VERSION=beta
FUNCTIONS_WORKER_RUNTIME=java_

Also confirmed that 'host.json' contains this property:
_"version": "2.0"_

I opened the Kudu Console and did this:
1. Following the instruction _(https://github.com/Azure/azure-functions-host/wiki/Updating-your-App-(portal)_) I faced that there is no 'bin' directory and no 'extensions.csproj'. I created this file manually, redeployed the Function and executed this command:
_'dotnet build extensions.csproj -o bin --no-incremental --packages D:\home\.nuget'_
After Function restart, nothing changed: the Function is still not triggered and the Error Message is still present.

2. Tried to execute this command too, but faced this command can not be executed from Kudu Console:
_'func extensions install --package Microsoft.Azure.WebJobs.Extensions.Storage --version 3.0.0-beta8'_

Can you please help me to figure the issue out?

**Comment by romanovs** [comment]
I'm sorry if I took your time. It appeared that following the instruction I didn't update the version of ExtensionsMetadataGenerator . Now it looks to work well.

And I'm wondering if we have to do all the steps from the instruction everytime for every new Function App?

**Comment by ColbyTresness** [comment]
@asavaritayal for FYI and docs update, but this looks resolved.
