### ISSUE TITLE
extension.json not generating consistenly

### ISSUE THREAD

**Issue by Chocrates** [Azure/Azure-Functions#957]
Copy of my question on SO: https://stackoverflow.com/questions/52375223/azure-functions-not-generating-extensions-json
Let me know if this isn't the right place for this.

We are seeing an error when deploying azure functions:  
    
    Error: The binding type(s) 'blobTrigger' are not registered. Please ensure the type is correct and the binding extension is installed  

My functions app (maintained another dev) has been updated with the [Alpha 2.0.12 changes](https://github.com/Azure/app-service-announcements/issues/129).  
On our development machines, we can build and package and upload the the zip to an Azure Function and have it run just fine.  

On our build machines however, the publish directory generated is slightly different and is missing the file `extensions.json`.  When it is published to the Azure function, we get the error mentioned above.

As far as I can tell the relevant versions of things between the build machines and the dev machines are the same.  .Net on the Build machine was a minor version behind, but after bumping that up it made no difference, and .Net core and Visual studio were the same.

**Comment by klesouza** [comment]
I'm experiencing the same issue (also commented [here](https://github.com/Azure/Azure-Functions/issues/928#issuecomment-420679962).

But I'm using a `dotnet:2.1-sdk` docker image to ***pack*** my function in the build server, but `extensions.json` is not consistent with local build.

**Comment by klesouza** [comment]
I'm also curious to know why it's not behaving consistently.

**Comment by gaikovoi** [comment]
See my comment for the linked issue. [https://github.com/Azure/Azure-Functions/issues/928#issuecomment-427036687](url)

**Comment by fabiocav** [comment]
Closing this as there were several updates to the generator in this area. 

Still leaving #4057 open, but please let us know if you're still running into the original issue.
