### ISSUE TITLE
Issue with application settings variables of azure functions of different slots on Azure Portal

### ISSUE THREAD

**Issue by RajdeepSenGupta** [Azure/Azure-Functions#959]
I have an Azure Function App and it has 2 different **_slots_**, viz. **staging** and **production**. Both has its individual application settings. I have a timer trigger function on both of the slots. However, when I update the trigger time of the function of **staging** slot, it automatically updates the trigger time of the **production** slot as well, and vice versa. It might cause some misbehavior of the function of the **production** slot, as the website is live.
Is it a natural behavior? Or am I missing some setting of the Azure Function App?
If this is a natural behavior, is there another way to prevent this, other than separating the Function Apps for **staging** and **production**?

**Comment by karandesai28** [comment]
+1 
Not only timer triggers, but any change in Function.json of either slot, changes Function.json of other one. (For ex, enabling/disabling an azure function on **Staging** slot, does the same in **Production** slot and vice versa)

**Comment by RajdeepSenGupta** [comment]
Have resolved the issue on the following thread - https://github.com/Azure/azure-functions-ux/issues/3198#issuecomment-425285101
So, closing this thread.
