### ISSUE TITLE
Improve DocDB input binding document

### ISSUE THREAD

**Issue by mathewc** [Azure/Azure-Functions#96]
See SO post here: http://stackoverflow.com/questions/41039785/how-do-i-use-a-documentdb-database-input-binding-with-a-service-bus-trigger-bind. The guy was trying to follow our documentation and was lead completely into the weeds. If he's reading our documentation, it should lead him to success. See my answer on his post.

The "id supports bindings similar to {queueTrigger}, which uses the string value of the queue message as the document Id." documentation isn't really useful at all. We should have documentation for this to the effect: "This value can be a string literal or may contain a binding expression that binds to a property from the trigger input. See this page on binding parameters for more information". Then we link off to a page that talks all about binding parameters, how for C# functions this only works for POCOs, etc.

We should review the doc for all the other bindings - likely the same issues exist.

**Comment by lindydonna** [comment]
To summarize the feedback:

On the DocDB doc page (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb), we have the following non-descriptive info:

**id supports bindings similar to {queueTrigger}, which uses the string value of the queue message as the document Id.**

@mathewc suggests that all binding documentation be reviewed as this same issue likely appears elsewhere.

**Comment by ggailey777** [comment]
Things like this will be less of an issue when we start leveraging the portal reference in Docs topics, as prototyped in #80.

**Comment by SyntaxC4** [comment]
Similar to #111. However this is more general to how the templates are used. Can we be sure to review all binding topics to ensure that we provide a consistent level of detail across all bindings.. If you find another issue similar to this, but not DocDB, please create a new issue.

**Comment by lindydonna** [comment]
In progress, see https://github.com/Microsoft/azure-docs-pr/pull/10887

**Comment by lindydonna** [comment]
Article has been published.
