### ISSUE TITLE
How to replace TraceWriter With ILogger in azure function V2 in Code.CS, unable to start Functions

### ISSUE THREAD

**Issue by mslugx** [Azure/Azure-Functions#961]
We are trying to migrate azure function to sdk.functions 1.0.21 and we upgraded everything to 3.0.0-rc1 . The console prompted us that the traceWriter is getting obsolete, using ILogger instead. However We are unable to change traceWriter to ILogger without issues. Here are the code examples. Anything helpful suggestion is welcomed. Thanks.

This is the Code.cs file

public static async Task Run(Message queueItem, ILogger log, ExecutionContext context){}
function.json

{
  "bindings": [
    {
      "queueName": "%InvoiceDetailCalculate_Queue%",
      "connection": "ServiceBus_Connection",
      "name": "queueItem",
      "type": "serviceBusTrigger",
      "direction": "in",
      "accessRights": "manage"
    }
  ],
  "disabled": false
}
Run.csx

#r "../bin/Best.Billing.Functions.dll"
#r "../bin/Best.Libraries.Utility.dll"

public static async void Run(Message queueItem, ILogger log, ExecutionContext context)
{
    try
    {
        Code.Run(queueItem, log, context).Wait();
    }
    catch (Exception ex)
    {        
        ex.Rethrow();
    }
}
The error messages are

 Run.csx(4,26): warning AF008: This method has the async keyword but it returns void

 Run.csx(4,30): error CS0246: The type or namespace name 'Message' could not be found (are you missing a using directive or an assembly reference?)

 Run.csx(8,9): error CS0103: The name 'Code' does not exist in the current context

 Run.csx(12,13): error CS1061: 'ILogger' does not contain a definition for 'Error' and no extension method 'Error' accepting a first argument of type 'ILogger' could be found (are you missing a using directive or an assembly reference?)

Run.csx(13,12): error CS1061: 'Exception' does not contain a definition for 'Rethrow' and no extension method 'Rethrow' accepting a first argument of type 'Exception' could be found (are you missing a using directive or an assembly reference?)

 Run.csx(4,26): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
Function compilation error

**Comment by tjrobinson** [comment]
Try making the type of `queueItem` `string` instead of `Message`.

**Comment by ColbyTresness** [comment]
Closing since this seems to be resolved with above advice. Please reopen if necessary.
