### ISSUE TITLE
No connection is available to service this operation: HGET

### ISSUE THREAD

**Issue by grik001** [Azure/Azure-Functions#962]
Hi,

Feel free to delete this post if you believe it is not the correct place to post this. I am trying to use Redis Cache with Azure Functions.

I keep getting the following error: No connection is available to service this operation: HGET

I have tried both using a static lazy connection and a connection per request. Almost all my calls get this error. I am using latest StackExchange.Redis for .Net 4.7. I am only sending a single message to Azure Functions so its not a matter of load and connection limit.

My code is working locally, errors start after I publish my function.

Any idea what it might be?

**Comment by ConnorMcMahon** [comment]
@grik001, it looks like this is an issue in StackExchange.Redis, based on [your thread here](https://github.com/StackExchange/StackExchange.Redis/issues/959). If you need anything else from the functions side of things for this issue, just reopen this issue.

**Comment by grik001** [comment]
Understood, thanks.
