### ISSUE TITLE
ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER

### ISSUE THREAD

**Issue by stofte** [Azure/Azure-Functions#963]
What's the recommended workarounds for these kinds of issues? They seems almost systemic to the whole AF experience.

Obviously: 
 - I'm using MSDEPLOY_RENAME_LOCKED_FILES=1 with no effect
 - `<EnableMsDeployAppOffline>False</EnableMsDeployAppOffline>`
 - Function App is stopped (I really feel this should be a cincher, but nope)

In my issue, the file being locked is D:\home\site\wwwroot\bin\Microsoft.Azure.WebJobs.ServiceBus.dll, presumably because the env/host combination I'm seeing issues with actually has alot of SB traffic, or possibly the whole netcore/desktop bullshit scism has some other effects.

I'm currenctly thinking about using zip file deployment but really, what's the point since there's zero guarentee that that approach will actually keep working. There are no slots being used in this function app, that would be optimistic at this point :)

Edit: Using the kudu panel to try to download the file yields some funny errors (delete leads to a "404" from the UI):

    {"Message":"An error has occurred.","ExceptionMessage":"Access to the path 'D:\\home\\site\\wwwroot\\bin\\Microsoft.Azure.WebJobs.ServiceBus.dll' is denied.","ExceptionType":"System.UnauthorizedAccessException","StackTrace":"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)\r\n   at Kudu.Services.Editor.VfsController.CreateItemGetResponse(FileSystemInfoBase info, String localFilePath) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Editor\\VfsController.cs:line 77"}

**Comment by ConnorMcMahon** [comment]
To the best of my knowledge, you should not be getting these file-lock errors if your function application is stopped. We should definitely investigate this, though having your function application name would be helpful in diagnosing what is going on here. If you don't feel comfortable sharing your function application publicly, just give us [this information](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) and we can get your application name ourselves.

As for recommended deployment options to avoid this issue, we recently released a new way to [run Azure Functions from a package file](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package). This deployment method was introduced specifically to help us work around issues with file copy-locking.

**Comment by stofte** [comment]
The app is located at: https://nocredisapprod2.azurewebsites.net/

Just now, when loading that URL the actual webpage was the github page for Azure Function Host Limitations. This was like this in Edge and on coworkers machines as well. Very fun:

https://i.imgur.com/6et70EU.png

I can't even start to fathom how THAT occured.

**Comment by stofte** [comment]
Unfortunantly someone else cleaned up, so the function app is no longer existing and thus this is no longer and issue.

**Comment by stofte** [comment]
Thanks for the follow @ConnorMcMahon but I guess I don't feel any inclinations for going down that rabbit hole :)
