### ISSUE TITLE
Could not load file or assembly 'Microsoft.Azure.KeyVault, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

### ISSUE THREAD

**Issue by shrikant1984** [Azure/Azure-Functions#966]
Team,

Getting the Key Vault dll issue as mentioned below.

Could not load file or assembly 'Microsoft.Azure.KeyVault, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Thanks,
Shrikant

**Comment by jeffhollan** [comment]
What version of the Azure Functions runtime are you using? Any additional info to try to get a repro?  Thanks

**Comment by fabiocav** [comment]
Closing issue as there has been no response. Please let us know if you still have problems.
