### ISSUE TITLE
How to publish Visual Studio Azure Functions project (Multiple functions) to different Azure Function Apps.

### ISSUE THREAD

**Issue by DreamingDevs** [Azure/Azure-Functions#971]
I have an Azure Functions project in Visual Studio holding two functions - **HttpTriggerFunction1** and **TimerTriggerFunction1**.

I want to publish Azure Function project from Visual Studio to different Azure Functions Apps - **HttpFunctionApp** and **TimerFunctionApp** which I created at Azure.

1. **HttpTriggerFunction1** should be deployed to **HttpFunctionApp**.
2. **TimerTriggerFunction1** should be deployed to **TimerFunctionApp**.

Is there an option from Visual Studio to achieve above deployment strategy (probably customize publish profile?)? Or do I need to use Release definition of VSTS to have the appropriate functions to be published to appropriate function app, in such a case, how to achieve this because my DLL might have code related to other functions (Run methods) which should not be making to all function apps? 

What are my other options?

I am using VS 2017 15.8.2 with latest Azure Webjobs and Tools.

**Comment by pragnagopa** [comment]
Closing as this is answered on stackoverflow: https://stackoverflow.com/questions/52576322/how-to-publish-visual-studio-azure-functions-project-multiple-functions-to-dif
