### ISSUE TITLE
Error while debugging custom attribute in Azure Functions project

### ISSUE THREAD

**Issue by yaroslav-rudchenko** [Azure/Azure-Functions#975]
Hi
A'm trying to add custom binding attribute to azure functions projects. I did it in the following way:
`[Binding]
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
    public class InjectAttribute : Attribute
    {
        public InjectAttribute(Type type)
        {
            Type = type;
        }
        public Type Type { get; }
    }`
Then register it within the class which implemented IExtensionConfigProvider in the following way:
`    public class InjectConfiguration : IExtensionConfigProvider
    {
        private IServiceProvider _serviceProvider;

        public void Initialize(ExtensionConfigContext context)
        {
            var services = new ServiceCollection();
            _serviceProvider = services.BuildServiceProvider();

            context
                .AddBindingRule<InjectAttribute>()
                .BindToInput<dynamic>(i => _serviceProvider.GetRequiredService(i.Type));
        }
    }`
But once i run my project before execution all the things i came into an error:

> Error indexing method 'IPNHandlerFunction.Run'
[10/3/2018 11:12:48 AM] Microsoft.Azure.WebJobs.Host: Error indexing method 'IPNHandlerFunction.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'pService' to type IPaymentService. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

My function looks like below:
`[FunctionName("IPNHandlerFunction")]
        public static async Task<HttpResponseMessage> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post")]HttpRequestMessage req,
            TraceWriter log,
            [Inject(typeof(IPaymentService))]IPaymentService pService)`

**Comment by jeffhollan** [comment]
Is this v2? There were significant changes in the injection used in v2. We haven't yet fully documented this for 3rd party developers and custom bindings but are tracking.  If feeling ambitious could follow patterns used by other extensions like [this one](https://github.com/azure/azure-functions-signalrservice-extension).

@mattchenderson as FYI and to correct as needed

**Comment by ColbyTresness** [comment]
Closing due to lack of customer response. Please reopen if necessary.
