### ISSUE TITLE
Azure functions Runtime version: 2.0.12115.0 (beta) for java which is in preview can we use it for production

### ISSUE THREAD

**Issue by pragathikadaganchi** [Azure/Azure-Functions#976]
I have a question regarding azure functions using java. Currently we developed an application using azure serverless functions in java and now are not having any breaking changes with  Azure functions Runtime version: 2.0.12115.0 (beta). we would like to continue our project with java which is in preview. And we are expecting to go in production by end of the year. When can we expect java to be GA? can we continue with java preview version and go live?

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-java-worker#191
