### ISSUE TITLE
No Canonical reference for Javascript function deployments from VSTS

### ISSUE THREAD

**Issue by GuyHarwood** [Azure/Azure-Functions#982]
Over the last few months we managed to figure out how to deploy a Javascript functions app to Azure from VSTS through support requests to Azure and reading MSDN blog posts.  I have [documented this process on my blog](https://guyharwood.co.uk/2018/07/26/deploy-node-js-azure-functions-from-vsts/), but it no longer works.

The steps we used were as follows...

- run `npm install`
- run `funcpack`
- delete `node_modules`
- run `func extensions install`
- zip the functions app folder
- deploy using App Service Deploy build task

This is now broken as `funcpack` no longer works and is obsolete.
I removed the funcpack and delete node_modules steps, and now the deploy task times out with..
`Error: Failed to deploy App Service package using kudu service : Cannot read property 'retryRequestTimedout' of undefined` 

There appears to be **no canonical reference** on how to do successfully deploy a javascript functions app from VSTS to Azure.

Can someone please explain how this is supposed to work, and if this is a known issue that is not yet supported please confirm.  We have invested time in developing Javascript functions for a national project here in the UK and currently have no way to deploy them successfully via our VSTS CI/CD pipeline.  

We have tried using the Deployment center tools, but even the [local git deployment is broken](https://github.com/Azure/azure-functions-ux/issues/3265).

We are targeting a linux app service function, without docker.  

Would we have more success with Dockerized functions that can be deployed as containers?

**Comment by jeffhollan** [comment]
Is this resolved now with the related issue and note that `WEBSITE_RUN_FROM_PACKAGE` isn't yet supported on Linux?

**Comment by GuyHarwood** [comment]
Also, a roadmap on Linux & docker capabilities would be good.  We are rolling out a national service and it would be great to have the longer view

**Comment by ColbyTresness** [comment]
Assigning @mhoeger to help out with the latter ask, creating a better experience for DevOps for JS Functions. Will leave this as the tracking issue for the integration.

**Comment by ColbyTresness** [comment]
This might be resolved now, tagging @ahmedelnably to take a look

**Comment by ahmedelnably** [comment]
This is currently documented here
https://aka.ms/functions-azure-devops

Closing this issue as resolved
