### ISSUE TITLE
Missing systemkey

### ISSUE THREAD

**Issue by jansoren** [Azure/Azure-Functions#983]
Why is the system keys empty when migrating from Azure Function v1.0 to v2.0?

The http trigger is set up like this:
``` csharp
    [FunctionName("MyFunc")]
    public static async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.System, "get", Route = "someData")]HttpRequest req,
        ILogger log)
    {
       ...
    }
```

When I try to retrieve the function apps system key with the url `https://myFunc.ase.host.com/admin/host/systemkeys` I get empty result after migrating:

```json
{
    "keys": [],
    "links": [
        {
            "rel": "self",
            "href": "https://myFunc.ase.host.com/admin/host/systemkeys"
        }
    ]
}
```

I have also deleted the version 1.0 function app and recreated it in version 2.0.

Any suggestion on how to get the system key?

**Comment by cgillum** [comment]
This is probably related to how key storage changed between v1 and v2. I suggest reading through this issue for the latest information on key-related migration issues: https://github.com/Azure/azure-functions-host/issues/3411

**Comment by jeffhollan** [comment]
Just circling back to see if this was resolved via linked issue? With v2 by default we store keys in the storage account (a blob in the function container called "secrets" I believe - encrypted with a key assigned to your site).  We have work items this coming half (2019 first few months) to improve the keys API though as well.  That's a seperate issue though

**Comment by fabiocav** [comment]
Closing issue as there has been no response. Please let us know if you still have problems.

**Comment by daniel-refahi** [comment]
i have this issue on version 1

![image](https://user-images.githubusercontent.com/5209991/69399564-53001500-0d3a-11ea-965a-e9e7b46a4467.png)
