### ISSUE TITLE
Delete Function App->Create New App Same Name->Failure

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/Azure-Functions#984]
Repro:

Deleted V1 app
Immediately created fresh V2 app of the same name
Tried to create a function in app
"Functions Runtime inaccessible"
Restarting site doesn't help.

I'm guessing something about the deletion isn't happening properly so I'm getting into a weird state.

**Comment by ahmelsayed** [comment]
You'll need to wait for DNS TTL to expire on your machine. When you delete and recreate the app with the same name, it will almost always end up with a different IP, but you're machine will have a DNS cash for the old CNAME for a bit.

**Comment by ColbyTresness** [comment]
Cool. Is there any way we could surface what's happening better then?

**Comment by jeffhollan** [comment]
I don't think so personally as its your machine DNS cache that's doing it - but assigning you to decide how deep into this you want to check :smile:

**Comment by ColbyTresness** [comment]
It's probably not worth it TBH - I think its pretty intuitive that things may not work 100% correctly if you delete something and immediately create another with the same name. Small scenario so I'll close for now.

**Comment by ahmelsayed** [comment]
I actually [had code in the UX for a while](https://github.com/Azure/azure-functions-ux/commit/0d4c8a65a6276de078cd2c21d2899dc9ff6cbcd4) that was looking at the "created" timestamp for an app to see if it has been created in the past 5 minutes and if it's a failure then suggests that it could be a DNS issue. But it ended up masking other legitimate bad creation issues and was confusing to everyone it was removed
