### ISSUE TITLE
IoTHub Trigger: VS Tooling not helpful in setting up connection string

### ISSUE THREAD

**Issue by wickste** [Azure/Azure-Functions#987]
When creating an Azure Function with IoTHubTrigger the UX asks me to fill out "Connection String setting" field. Intuitively I will enter my IoTHub's connection string here, which will result in an obscure error at build that is not obvious to recover from.

Even if I can figure out that this is really only about the key name for the actual connection string value retrieved from local.settings.json, I still don't know which string to put as value - as V1 functions used a different string than V2 functions.

I don't understand why we even need this field. VS could pick a name for this setting automatically (like it does for the function name) and put that in the code and the local.settings.json. Most users will not care what the key name is called. Any advanced user who does care can edit the two files and change it if needed.

**Comment by ColbyTresness** [comment]
Closing in favor of #799

**Comment by wickste** [comment]
@ColbyTresness[ #799](https://github.com/Azure/Azure-Functions/issues/799) seems to completely unrelated.

**Comment by ColbyTresness** [comment]
Sorry, #764
