### ISSUE TITLE
[Core Tools] IoTHubTrigger connection string setup is a mystery

### ISSUE THREAD

**Issue by wickste** [Azure/Azure-Functions#988]
When creating and IoTHubTrigger C# Azure Function via "func new" command it won't work out of the box and there is no guidance how to set it up correctly. The Connection property is left empty, and it is unclear what to put there. Entering the connection string results in build error.

A couple of suggestions on how to improve it:
- include a comment in the generated code explaining what to put there
- pick a name for the "Connection" key and put it in both the code and the local.settings.json. Now the developer only needs configure one file
- from the CLI optionally task the developer for their IoTHub and do the configuration for them

**Comment by ColbyTresness** [comment]
I'm going to close this since it's not IoT Hub specific. I'll track this elsewhere as a more generic improvement to the CLI.
