### ISSUE TITLE
[VSCode ext] IotHubTrigger and EventHubTrigger missing from the default list of templates

### ISSUE THREAD

**Issue by wickste** [Azure/Azure-Functions#989]
Using the Azure Functions extension for VS Code, my goal was to create a function that hooks up to my IoTHub. I understand I can use either the IoTHubTrigger (preferred) or the EventHubTrigger template.

When creating a new Function in VS Code I am presented with a list of templates (HttpTrigger, QueueTrigger, etc.), but both IoTHub and EventHub are missing.

By chance I tried changing the template filter from "Verified" to "All" and then the two templates showed up!

What will it take to promote EventHubTrigger and IoTHubTrigger to be in the "Verified" category? What does "Verify" mean in this context anyway?

**Comment by EricJizbaMSFT** [comment]
@wickste We have an issue here for more info and tracking: https://github.com/Microsoft/vscode-azurefunctions/issues/690

**Comment by paulbatum** [comment]
@EricJizbaMSFT thanks! Closing this as a dupe.
