### ISSUE TITLE
Cannot run / debug C# sample AF - Visual Studio tooling

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/Azure-Functions#99]
Hi,

I have followed the steps in https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/ but up to and not including the **Publishing to Azure** section.

I am unable to debug / run successfully a default c# queue trigger function.  I select and do not modify the QueueTriggerCSharp sample.  I enter in the Storage account name when prompted to and I then enter in connection string in appSettings.json.

I set a break point on the only line - log.Info($"C# Queue trigger function processed: {myQueueItem}"); - and start the debug.

This is the console output:
```
Listening on http://localhost:7071/
Hit CTRL-C to exit...
Reading host configuration file 'f:\users\garrard\documents\visual studio 2015\Projects\FunctionApp2\FunctionApp2\host.json'
Host lock lease acquired by instance ID '0000000000000000000000004179EEE2'.
Generating 1 job function(s)
Starting Host (HostId=gk-mbp-pc-functionapp2, Version=1.0.0.0, ProcessId=11716, Debug=False)
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTriggerCSharp'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
Error indexing method 'Functions.QueueTriggerCSharp'
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. confi
Job host started
The following 1 functions are in error:
QueueTriggerCSharp: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTriggerCSharp'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
```

I also run without debug, same outcome.

I then tried with F# first (same queue trigger sample) with no modifications like with the C# sample I tried.  The article I refer to at the top of this post does say that debug isn't available with F# so I did run without debug and I get this:

```
Listening on http://localhost:7071/
Hit CTRL-C to exit...
Reading host configuration file 'f:\users\garrard\documents\visual studio 2015\Projects\FunctionApp2\FunctionApp2\host.json'
Host lock lease acquired by instance ID '0000000000000000000000004179EEE2'.
Generating 1 job function(s)
Starting Host (HostId=gk-mbp-pc-functionapp2, Version=1.0.0.0, ProcessId=28860, Debug=True)
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTriggerCSharp'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
Error indexing method 'Functions.QueueTriggerCSharp'
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. confi
Job host started
The following 2 functions are in error:
QueueTriggerFSharp: Access to the path 'C:\Users\garrard\AppData\Local\Temp\f-QueueTriggerFSharp__1573643635.pdb' is denied.
QueueTriggerCSharp: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTriggerCSharp'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.
```

Please let me know if you need further info or for me to try something.

Warmest regards,

Garrard.

**Comment by lindydonna** [comment]
Did you set a value for AzureWebJobsStorage?  We have a bug to fix that error message: https://github.com/Azure/azure-webjobs-sdk-script/issues/972

**Comment by garrardkitchen** [comment]
Hi @lindydonna, yes, I can confirm that this is set in the `appsettings.json` file in the root of the project.

appsettings.json:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=<hidden...>",
    "AzureWebJobsDashboard": ""
  }
}
```

Warmest regards,

Garrard.

**Comment by lindydonna** [comment]
Can you provide the contents of function.json?

**Comment by jsiegmund** [comment]
I'm seeing kind of the same thing. Cannot run functions from either visual studio or CLI with the error that port 7071 is already in use. Running as administrator does not make a difference. When I run "func host start -p 7073" for instance, the CLI works fine. I have no clue what would be running on port 7071 otherwise, I tried http://localhost:7071 but that doesn't return anything. Is there a way to check?

**Comment by garrardkitchen** [comment]
Hi @lindydonna,

Here you are:

```
{
  "disabled": false,
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "samples-fsharp",
      "connection": "{masked}"
    }
  ]
}
```

Warmest regards,

Garrard.

**Comment by NicolasHumann** [comment]
Hi @garrardkitchen 
I had the same issue. In the function.json, you should have 

`{
  "disabled": false,
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "samples-fsharp",
      "connection": "AzureWebJobsStorage"
    }
  ]
}`

"AzureWebJobsStorage" is the name of the connection string in appsettings.json

**Comment by lindydonna** [comment]
This looks like a situation with a poor error message and the tooling not getting you on the right path. The value of "connection" in function.json MUST be an app setting that you specify in appsettings.json. This is how it works in the portal, where it automatically sets things up for you the right way. The Visual Studio tooling doesn't yet have any support for the equivalent of the "Integrate" tab, which is why this is so confusing.

**Comment by garrardkitchen** [comment]
Hi @lindydonna & @NicolasHumann, thank you, I am now able to debug locally!

Warmest regards,

Garrard.

**Comment by newportsolutionsgroup** [comment]
@garrardkitchen Thank you! It's two months later and your answer is still solving this problem. I spent a couple hours poking around the azure function documentation for this answer. 
Confirmed this solution by: Azure Portal > Create Function App > Create Function > View Files > Choose Function.json
