### ISSUE TITLE
"Getting Started with Azure Functions" link on VS2017 "New Project" dialog is broken

### ISSUE THREAD

**Issue by wickste** [Azure/Azure-Functions#990]
The "Getting Started with Azure Functions" link on VS2017 "New Project" dialog is broken. Clicking on it will redirect me to the generic root page of the Visual Studio documentation:

https://docs.microsoft.com/en-us/visualstudio/

**Comment by paulbatum** [comment]
@soninaren do we manage this FW link?

**Comment by soninaren** [comment]
It is managed by VS, let me follow up on it and get this fixed.

**Comment by soninaren** [comment]
This is fixed now.
