### ISSUE TITLE
Azure Function is not running on a blob trigger

### ISSUE THREAD

**Issue by shkrishms** [Azure/Azure-Functions#991]
I have an Azure Function in consumption plan and its binded to a blob trigger. recently i saw "Function inaccessible" error and after multiple restarts the error went away. But now, the function does not seem to pick up payloads. The status seems to be running.  Restarts do not help.

The last succesful operation had this log:
Function started (Id=d552b484-64c1-41e7-8adf-84ba1246b801)
Timestamp: 2018-10-10T10:01:35.157

Can provide more details if necessary.

**Comment by cgillum** [comment]
What region is your function app running in?

One thing to remember about blob triggers is that they can sometimes be delayed by as much as 10 minutes when you're not actively using the Azure Portal. The other issue to be aware of is that certain deployment actions, such as uploading a function app using a storage account connection string or FTP will not register the triggers, in which case you would need to click the Refresh button next to your function app in the portal to complete the registration.

**Comment by shkrishms** [comment]
Location is West US 2. Its definitely more than 10 min. There was no new deployment recently. I just retstarted multiple times. And its weird in the sense that, there are 2 function in the same app. One is running fine. Other is not running.

**Comment by shkrishms** [comment]
Is there any update on this? There is consistent repro in the last 2 days. New payloads are not picked up.

**Comment by ColbyTresness** [comment]
@jeffhollan who may be able to help - can you provide us with the function app name so we can look deeper?

**Comment by shkrishms** [comment]
I dont see this anymore. I think we can close this.

**Comment by mudithaa** [comment]
I am seeing this issue. I have a Blob Triggered function in Aust East region. It only needs to run once a week as that's the frequency currently. Last week I found two blobs in the storage and I have to restart the app and then delete and reupload the two blobs to get it triggered. Today I see a new blob that hasn't been picked.
