### ISSUE TITLE
Publishing via publish profile and Visual Studio fails for Azure Government environment

### ISSUE THREAD

**Issue by mhoeger** [Azure/Azure-Functions#995]
In Visual Studio, Whenever attempting to publish a Functions project (1.0 or 2.0) to an Azure Government Function App/App Service by using a publishing profile instead of Azure Environment Selector, the publishing attempt fails quickly with a pop-up window saying "Publishing failed".

This appears to occur when signed into an account through Visual Studio (VS isn't able to find subscriptions within Government accounts).

**Workarounds:**
 1. Remove all accounts you are signed into (_View_ > _Cloud Explorer_ > Person icon (top right) > _Manage Accounts_ > Remove all accounts you are signed into). Restart VS and publish with imported publish profile.
 2. Use Azure Environment Selector

**Comment by jeffhollan** [comment]
@nimakms  I *think* this came up in the VS sync but if not we should just make sure we are tracking

**Comment by vijayrkn** [comment]
This issue should be fixed in Visual Studio 2019. You can download the RC candidate build from here - https://visualstudio.microsoft.com/downloads/
