### ISSUE TITLE
Binding Redirects still an issue in AzureFunctions 2.0. Guidance needed

### ISSUE THREAD

**Issue by thedonmon** [Azure/Azure-Functions#996]
According to this issue https://github.com/Azure/azure-functions-host/issues/992 
It was stated that this problem was fixed in the GA version of functions 2.0. However the Newtonsoft issue still exists as it is required to have Newtonsoft 11.0.2 ONLY installed. Nuget dependency states 
![image](https://user-images.githubusercontent.com/22967202/47047388-0d4b4300-d15d-11e8-922e-f2001701ddd4.png)

So how do we get around this issue with referenced projects or nuget packages that can't support a higher version or throw the classic file not found exception for a version that isnt referenced?

**Comment by jeffhollan** [comment]
At this point we are doing an implicit binding redirect for you.  In other words if you pulled in the non-existent Newtonsoft 12, we will still resolve the assembly for you at your own risk without you having to define an explicit binding redirect.  The main reason it is listed here is just a NuGet packaging constraint - but you can always override and we will implicitly bind for you.
