### ISSUE TITLE
Could not load file or assembly 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### ISSUE THREAD

**Issue by sjha2** [Azure/Azure-Functions#997]
I am facing issue while creating search client though it worked perfectly fine when I run locally.
I get below same error When I run function after publishing to Azure at
var indexClient = new SearchIndexClient("xxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxx",
new SearchCredentials("xxxxxxxxxxx"));

Error:
Could not load file or assembly 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

I have tried all the version of azure search but still not working.
Current nuget version:
Microsoft.Azure.Search : 5.0.0
Microsoft.NET.Sdk.Functions : 1.0.13

**Comment by JohnReeson** [comment]
`System.Net.Http.WebRequest` seems not available in ~2 runtime i.e. .NET Core env. What's your function runtime version?

**Comment by sjha2** [comment]
Yes System.Net.Http.WebRequest is not supported runtime 2.x. 
When I change runtime to 1.x then it it works.  any idea how Ican include in 2.x ?

**Comment by JohnReeson** [comment]
Unfortunately I don't find any way, I tried to work with `PowerBIClient` before, it leverages this assembly internally as well.  The assembly  can't even be loaded correctly in a simple .Net Core console app.

**Comment by jeffhollan** [comment]
If it's supported by .NET Core 2.1 it should work in your function. However in this case it sounds like you are trying to leverage an assembly that isn't supported by .NET Core 2 which would be unsupported in v2 as it uses .NET Core to run.  May be best to track the ask with the Azure Search SDK to provide a .NET Core compatible SDK, or use v1 for now.
